### ISSUE TITLE
Presence of funding_rate data dramatically slows down backtesting on futures

### ISSUE THREAD

**Issue by a18** [freqtrade/freqtrade#9106] opened 2023-08-26 06:18 UTC
## Describe your environment

  * Operating system: WIndows 10
  * Python Version: 3.10.10
  * CCXT version: 2.8.17
  * Freqtrade Version: 2023.6
  
## Describe the problem:
1. Backtest launch for dates 20220513-20220930, pair 'ETH/USDT:USDT': **total time 330 seconds**
2. Same launch, after removing the file with funding rates : **total time 111 seconds (3x faster)**
Removed file name: user_data\data\binance\futures\ETH_USDT_USDT-8h-funding_rate.json

### Steps to reproduce:
See above
  
### Observed Results:
See above

### Relevant code exceptions or logs

Log with funding rates file:
  ```
2023-08-26 08:53:37,245 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-05-13 00:00:00 up to 2022-09-30 00:00:00 (140 days).
2023-08-26 08:53:37,254 - freqtrade.data.history.idatahandler - WARNING - ETH/USDT:USDT, funding_rate, 8h, data starts at 2022-09-27 00:00:00
2023-08-26 08:53:37,302 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2023-08-26 08:53:37,303 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy XXXX
2023-08-26 08:53:37,304 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-08-26 08:53:39,189 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2022-05-13 00:00:00 up to 2022-09-30 00:00:00 (140 days).
2023-08-26 08:58:48,485 - freqtrade.misc - INFO - dumping json to XXXX
  ```

Log without funding rates file:
  ```
2023-08-26 09:05:20,046 - freqtrade.optimize.backtesting - INFO - Loading data from 2022-05-13 00:00:00 up to 2022-09-30 00:00:00 (140 days).
2023-08-26 09:05:20,049 - freqtrade.data.history.idatahandler - WARNING - No history for ETH/USDT:USDT, funding_rate, 8h found. Use `freqtrade download-data` to download the data
2023-08-26 09:05:20,086 - freqtrade.optimize.backtesting - INFO - Dataload complete. Calculating indicators
2023-08-26 09:05:20,087 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy XXXX
2023-08-26 09:05:20,088 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2023-08-26 09:05:22,003 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2022-05-13 00:00:00 up to 2022-09-30 00:00:00 (140 days).
2023-08-26 09:06:50,321 - freqtrade.misc - INFO - dumping json to XXXX
  ```

**Comment by stash86** [comment] 2023-08-26 10:29
It's not a bug or an issue. We already know it and it's part of the downside of trying to make backtest closer to dry/live run. If you have a suggestion of how to make it faster without deleting the funding rate data, please submit a PR.

**Comment by a18** [comment] 2023-08-26 13:43
> It's not a bug or an issue. We already know it and it's part of the downside of trying to make backtest closer to dry/live run. If you have a suggestion of how to make it faster without deleting the funding rate data, please submit a PR.

Thanks for the explanations! In fact, according to the log file, this feature is mostly useless (or even harmful) for that specific data range, as most part of the time, from 2022-05-13 up to 2022-09-26, we can't get funding rate data - probably, due to Binance history limit (I downloaded fresh data today).
So a fast suggesstion is to include a flag to config like "use_funding_rates" (similar to "use_order_book"). 
BTW, thanks for introducing the warning - it actually saved hours for me while investigating this case.

**Comment by xmatthias** [comment] 2023-08-26 18:08
> So a fast suggesstion is to include a flag to config like "use_funding_rates" (similar to "use_order_book").

this actually translates to having a flag that says "make backtesting inaccurate".
i don't really see why we should have this - it'll be missleading for no good reason.

the ACTUAL impact will be strongly depending on the strategy. a high impact is expected if you're in trades for a long time (in which case, the impact of funding-fees can be significant, pulling a profitable strategy into the negatives).

If you're in trades only for minutes, the impact will be minimal (both from a financial standpoint, as well as from a performance standpoint).


>  as most part of the time, from 2022-05-13 up to 2022-09-26, we can't get funding rate data - probably, due to Binance history limit (I downloaded fresh data today).

this is clearly wrong, and is another strong point against your suggestion.
It may be limited to the pair you're using (maybe it wasn't listed until september?).


For BTC/USDT:USDT - i just got data (all futures, funding and mark) starting from january 2021.

```
2023-08-26 20:06:43,965 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, futures interval 1h...
2023-08-26 20:06:43,970 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 23227.
2023-08-26 20:06:43,970 - freqtrade.data.converter - DEBUG - Converting candle (OHLCV) data to dataframe for pair BTC/USDT:USDT.
2023-08-26 20:06:43,992 - freqtrade.data.converter - DEBUG - Dropping last candle
2023-08-26 20:06:43,992 - freqtrade.data.history.history_utils - DEBUG - New Start: 2021-01-01 00:00:00
2023-08-26 20:06:43,993 - freqtrade.data.history.history_utils - DEBUG - New End: 2023-08-26 17:00:00
2023-08-26 20:06:44,009 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data fo
...


2023-08-26 20:06:44,878 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, funding_rate interval 8h...
2023-08-26 20:06:44,925 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, funding_rate interval 8h...
2023-08-26 20:06:44,988 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, funding_rate interval 8h...
2023-08-26 20:06:44,989 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 2904.
2023-08-26 20:06:44,989 - freqtrade.data.converter - DEBUG - Converting candle (OHLCV) data to dataframe for pair BTC/USDT:USDT.
2023-08-26 20:06:44,994 - freqtrade.data.converter - DEBUG - Dropping last candle
2023-08-26 20:06:44,995 - freqtrade.data.history.history_utils - DEBUG - New Start: 2021-01-01 00:00:00
2023-08-26 20:06:44,995 - freqtrade.data.history.history_utils - DEBUG - New End: 2023-08-26 08:00:00

...

2023-08-26 20:06:45,878 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, mark interval 8h...
2023-08-26 20:06:46,125 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, mark interval 8h...
2023-08-26 20:06:46,369 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, mark interval 8h...
2023-08-26 20:06:46,370 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 2904.
2023-08-26 20:06:46,370 - freqtrade.data.converter - DEBUG - Converting candle (OHLCV) data to dataframe for pair BTC/USDT:USDT.
2023-08-26 20:06:46,376 - freqtrade.data.converter - DEBUG - Dropping last candle
2023-08-26 20:06:46,376 - freqtrade.data.history.history_utils - DEBUG - New Start: 2021-01-01 00:00:00
2023-08-26 20:06:46,377 - freqtrade.data.history.history_utils - DEBUG - New End: 2023-08-26 08:00:00

```

Maybe you've had prior historic data which caused the download to not work - but the data on binance is clearly available.

(downloaded with ` freqtrade download-data --exchange binance --trading-mode futures --pairs BTC/USDT:USDT --timerange 20210101- -t 1h -v`).
Using `-v` makes it quite verbose - but shows the new start/end times.

**Comment by a18** [comment] 2023-08-27 19:10
> (downloaded with ` freqtrade download-data --exchange binance --trading-mode futures --pairs BTC/USDT:USDT --timerange 20210101- -t 1h -v`). Using `-v` makes it quite verbose - but shows the new start/end times.

Here's the log of executing this very command on my env (for pure experiment I've deleted the "data/binance" folder):
```
...
2023-08-27 22:00:06,947 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 23252. 
...
2023-08-27 22:00:07,058 - freqtrade.exchange.exchange - DEBUG - Fetching pair BTC/USDT:USDT, funding_rate, interval 8h, since 0 (1970-01-01T00:00:00+00:00) ... 
2023-08-27 22:00:07,572 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, interval 8h ...
2023-08-27 22:00:07,573 - freqtrade.exchange.binance - INFO - Candle-data for BTC/USDT:USDT available starting with 2022-09-28T16:00:00+00:00.
2023-08-27 22:00:07,574 - freqtrade.exchange.exchange - DEBUG - one_call: 28800000000 msecs (11 months)
2023-08-27 22:00:07,575 - freqtrade.exchange.exchange - DEBUG - Fetching pair BTC/USDT:USDT, funding_rate, interval 8h, since 1664380800000 (2022-09-28T16:00:00+00:00) ...
2023-08-27 22:00:07,910 - freqtrade.exchange.exchange - DEBUG - Done fetching pair BTC/USDT:USDT, interval 8h ...
2023-08-27 22:00:07,911 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 1000. 
```
So it seems the OHLCV data is OK (23252 candles), while funding rate data is limited to the last 1000 candles.

**Comment by stash86** [comment] 2023-08-28 03:19
I can download the funding data just fine

`freqtrade download-data -c 'user_data/other_configs/config-static-usdt-futures-mc.json' -p BTC/USDT:USDT --timerange 20210101- -t 5m 15m 30m 1h`

```
2023-08-28 03:10:22,826 - freqtrade.data.history.history_utils - INFO - About to download pairs: ['BTC/USDT:USDT'], intervals: ['5m', '15m', '30m', '1h'] to /root/freqtrade/user_data/data/binance
2023-08-28 03:10:22,829 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 5m, futures and store in /root/freqtrade/user_data/data/binance. From 2021-01-01T00:00:00 to now
2023-08-28 03:15:03,145 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 279112.
2023-08-28 03:15:03,876 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 15m, futures and store in /root/freqtrade/user_data/data/binance. From 2021-01-01T00:00:00 to now
2023-08-28 03:16:38,918 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 93038.
2023-08-28 03:16:39,122 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 30m, futures and store in /root/freqtrade/user_data/data/binance. From 2021-01-01T00:00:00 to now
2023-08-28 03:17:27,168 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 46519.
2023-08-28 03:17:27,265 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 1h, futures and store in /root/freqtrade/user_data/data/binance. From 2021-01-01T00:00:00 to now
2023-08-28 03:17:52,304 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 23260.
2023-08-28 03:17:52,352 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 8h, funding_rate and store in /root/freqtrade/user_data/data/binance. From 2021-01-01T00:00:00 to now
2023-08-28 03:17:53,998 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 2908.
2023-08-28 03:17:54,008 - freqtrade.data.history.history_utils - INFO - (1/1) - Download history data for "BTC/USDT:USDT", 8h, mark and store in /root/freqtrade/user_data/data/binance. From 2021-01-01T00:00:00 to now
2023-08-28 03:17:57,248 - freqtrade.exchange.exchange - INFO - Downloaded data for BTC/USDT:USDT with length 2908.
```

**Comment by xmatthias** [comment] 2023-08-28 04:43
@a18 You will want to make sure to use an updated version (2023.7 is currently the latest) - and (this is more important) - dependencies that correspond to that version's requirements files (that's the version we test it with).

Version 2023.6 did NOT have a ccxt version < 2.0 (which you seem to have installed).
It's very well possible that you're running into an incompatibility between the 2 versions. That's not something we test for - and won't - as we pin dependencies for a reason.

Please follow the [how to update](https://www.freqtrade.io/en/stable/updating/) guide for your installation method to install matching dependenies (please follow the same process for future updates).

---

In theory, there can be a few things causing this
* odd config settings with incompatible proxies configured
* not using binance.com, but binance.us or some other subsidiary


However the highest chance is for sure due to the mismatching verisions.

**Comment by xmatthias** [comment] 2023-09-06 18:08
Closing this as we didn't hear back from you, so we'll assume the above did help you get your funding rates downloaded properly.

Feel free to comment below if it's still unclear.

**Closed as completed by xmatthias** 2023-09-06 18:08 UTC
Labels: Question, Backtest

**Comment by a18** [comment] 2023-09-07 08:36
> Closing this as we didn't hear back from you, so we'll assume the above did help you get your funding rates downloaded properly.
> 
> Feel free to comment below if it's still unclear.

Thanks for your time and help, now I fully understood the motivation of this feature.
I'll check the new version a bit later, will report if anything goes wrong.
