### ISSUE TITLE
huobipro: None type error when bot is canceling order

### ISSUE THREAD

**Issue by jamesbaber1** [freqtrade/freqtrade#5515] opened 2021-08-30 22:02 UTC
## Describe your environment
  * unbuntu 18.04 EC2 t3.small with docker
  * Freqtrade Version: freqtrade 2021.3
  * CCXT 1.51.94 huobipro

## Describe the problem:

I am running Freqtrade instances in dockers and have had them dying on me lately and took a look at the logs and I seem to be getting a None type error when I think that bot is trying to cancel a partially filled order.

### Steps to reproduce:

  1. Run the freqtrade docker
  2. Let the bot buy and then try and cancel to cancel and order it cant fill
  3. When it dies check the docker logs
  
### Observed Results:

  * Still narrowing the repro case, but I think that is how it is happening
  * I recently was running on binance and switch to huobi so that is a factor
  * Also I updated to the latest docker so maybe their was a breaking change?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  2021-08-30 21:30:31,174 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=10, pair=LINK3L/USDT, amount=55410.58230000, open_rate=0.01801100, open_since=2021-08-30 04:00:23)
2021-08-30 21:30:33,170 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=11, pair=ETH3L/USDT, amount=58.23140000, open_rate=17.13850000, open_since=2021-08-30 04:00:31)
2021-08-30 21:30:41,169 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=10, pair=LINK3L/USDT, amount=55410.58230000, open_rate=0.01801100, open_since=2021-08-30 04:00:23)
2021-08-30 21:30:43,203 - freqtrade.wallets - INFO - Wallets synced.
2021-08-30 21:30:45,172 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_cancel, 'trade_id': 10, 'exchange': 'Huobipro', 'pair': 'LINK3L/USDT', 'gain': 'profit', 'limit': 0.021069, 'order_type': 'limit', 'amount': 55410.5823, 'open_rate': 0.018011, 'current_rate': 0.020184, 'profit_amount': 165.11466956, 'profit_ratio': 0.16511533, 'sell_reason': 'roi', 'open_date': datetime.datetime(2021, 8, 30, 4, 0, 23, 796580), 'close_date': None, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'reason': 'partially filled - keeping order open'}
2021-08-30 21:30:47,182 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=11, pair=ETH3L/USDT, amount=58.23140000, open_rate=17.13850000, open_since=2021-08-30 04:00:31)
2021-08-30 21:30:49,189 - freqtrade.commands.trade_commands - ERROR - '>' not supported between instances of 'NoneType' and 'int'
2021-08-30 21:30:49,189 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 176, in process
    self.check_handle_timedout()
  File "/freqtrade/freqtrade/freqtradebot.py", line 1003, in check_handle_timedout
    self.handle_cancel_sell(trade, order, constants.CANCEL_REASON['TIMEOUT'])
  File "/freqtrade/freqtrade/freqtradebot.py", line 1087, in handle_cancel_sell
    trade.update_order(co)
  File "/freqtrade/freqtrade/persistence/models.py", line 492, in update_order
    Order.update_orders(self.orders, order)
  File "/freqtrade/freqtrade/persistence/models.py", line 181, in update_orders
    oobj.update_from_ccxt_object(order)
  File "/freqtrade/freqtrade/persistence/models.py", line 165, in update_from_ccxt_object
    if order.get('filled', 0) > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2021-08-30 21:30:49,201 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-08-30 21:30:49,201 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-08-30 21:30:49,505 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-08-30 21:30:49,511 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "5 open trades active.\n\nHandle these trades manually on Huobi Pro, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-08-30 21:30:49,866 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-08-30 21:30:49,866 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
INFO:     Shutting down
2021-08-30 21:30:49,881 - uvicorn.error - INFO - Shutting down
INFO:     Waiting for application shutdown.
2021-08-30 21:30:49,982 - uvicorn.error - INFO - Waiting for application shutdown.
INFO:     Application shutdown complete.
2021-08-30 21:30:49,983 - uvicorn.error - INFO - Application shutdown complete.
INFO:     Finished server process [1]
2021-08-30 21:30:49,983 - uvicorn.error - INFO - Finished server process [1]
2021-08-30 21:30:49,984 - apscheduler.scheduler - INFO - Scheduler has been shut down
root@ip-10-0-2-207:~#
  ```

**Comment by jamesbaber1** [comment] 2021-08-30 22:12
So I think the issue is that there was a partial fill
`2021-08-30 21:30:45,172 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_cancel, 'trade_id': 10, 'exchange': 'Huobipro', 'pair': 'LINK3L/USDT', 'gain': 'profit', 'limit': 0.021069, 'order_type': 'limit', 'amount': 55410.5823, 'open_rate': 0.018011, 'current_rate': 0.020184, 'profit_amount': 165.11466956, 'profit_ratio': 0.16511533, 'sell_reason': 'roi', 'open_date': datetime.datetime(2021, 8, 30, 4, 0, 23, 796580), 'close_date': None, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'reason': 'partially filled - keeping order open'}`

The weird thing to me is the stacktrace:

```
File "/freqtrade/freqtrade/persistence/models.py", line 165, in update_from_ccxt_object
if order.get('filled', 0) > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```


which the dict by default  return 0 so the comparision should be `0 > 0` not `None > 0`

If the order object was None id expect
`AttributeError: 'NoneType' object has no attribute 'get'` 
so I think the None Type error is actually coming from another location? @xmatthias any ideas?

**Comment by xmatthias** [comment] 2021-08-31 04:38
Freqtrade is an open source project, where we're investing our free time in that project.

As such - we're supporting at max 2 versions back.
Your version is from march (2021.3) - which is now 5 versions back.

Therefore, please update and retry to verify if the problem is gone with an uptodate version (we're fixing bugs all the time, so it's pretty likely it's been fixed already).

**Comment by jamesbaber1** [comment] 2021-08-31 14:14
Ok makes sense. Ill run it on `freqtradeorg/freqtrade:stable` which at this point in time is `freqtrade 2021.8` And Ill report back in a weekish if I encounter another runtime error or else Ill close this if this is no longer an issue

**Comment by jamesbaber1** [comment] 2021-09-03 13:48
So I hit this again this morning
![image](https://user-images.githubusercontent.com/31859220/132014252-f8eff111-9a92-4380-b642-afbfa3229b45.png)

But a different tracktrace
```
2021-09-03 12:10:37,249 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.8', state='RUNNING'
2021-09-03 12:11:23,230 - freqtrade.commands.trade_commands - ERROR - argument of type 'NoneType' is not iterable
2021-09-03 12:11:23,230 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 179, in process
    self.exit_positions(trades)
  File "/freqtrade/freqtrade/freqtradebot.py", line 680, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/freqtrade/freqtrade/freqtradebot.py", line 716, in handle_trade
    sell_rate = self.exchange.get_rate(trade.pair, refresh=True, side="sell")
  File "/freqtrade/freqtrade/exchange/exchange.py", line 1040, in get_rate
    ticker = self.fetch_ticker(pair)
  File "/freqtrade/freqtrade/exchange/common.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 946, in fetch_ticker
    data = self._api.fetch_ticker(pair)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/huobi.py", line 605, in fetch_ticker
    ticker = self.parse_ticker(response['tick'], market)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/huobi.py", line 489, in parse_ticker
    if 'bid' in ticker:
TypeError: argument of type 'NoneType' is not iterable
2021-09-03 12:11:23,231 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-09-03 12:11:23,231 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-09-03 12:11:24,181 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-09-03 12:11:24,183 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "3 open trades active.\n\nHandle these trades manually on Huobi, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-09-03 12:11:24,502 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-09-03 12:11:24,503 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2021-09-03 12:11:24,504 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2021-09-03 12:11:24,572 - uvicorn.error - INFO - Shutting down
2021-09-03 12:11:24,673 - uvicorn.error - INFO - Waiting for application shutdown.
2021-09-03 12:11:24,673 - uvicorn.error - INFO - Application shutdown complete.
2021-09-03 12:11:24,673 - uvicorn.error - INFO - Finished server process [1]
2021-09-03 12:11:24,674 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2021-09-03 12:11:24,674 - apscheduler.scheduler - INFO - Scheduler has been shut down
```

So looks like an issue with ccxt huobis `parse_ticker` method.  Ill open an issue there. And see if this solves the original issue

**Comment by xmatthias** [comment] 2021-09-03 13:56
if i remember correctly, then huobi must use orderbook for pricing, as their "fetch_ticker" method doesn't contain current prices - at least not reliably.

**Comment by jamesbaber1** [comment] 2021-09-03 14:34
Yes doing some testing calling that method and cant repro that error so it just must be intermittently that this happens.  I dont know if this would be an issue neccessarily fixed by ccxt other than making the exception handling better since my guess is its just a huobi issue. Here is the issue I opened.
https://github.com/ccxt/ccxt/issues/9928

Looks like on the freqtrade side I could just handle this by overriding the `get_rate` method in a huobi exchange subclass and prevent the hard crash that way
https://github.com/freqtrade/freqtrade/blob/93c1dff71bbae773b922794f956013e0d0b9c908/freqtrade/exchange/exchange.py#L1011

@xmatthias hopefully this weekend Ill add this subclass into my dockers that I run and if I dont hit the issue again in about a weekish Ill submit a PR

**Comment by xmatthias** [comment] 2021-09-03 15:01
i don't think you'll need to subclass stuff to handle errors properly - it can fail on any other exchange too (if a low value pair has no bids / ask at that moment).

Apart for that - i'd still recommend to use orderbook for pricing - it's a "faster" endpoint in most exchanges - and the one recommended (the prices in `fetch_tickers` may lag on some exchanges - at least that's what i read a while ago in some documentation).

**Comment by jamesbaber1** [comment] 2021-09-03 15:39
Gotcha, yea looks like I am not using the order book on my ask strategy, I mustive missed that. That will probably solve my issue then... Yea I guess if this is a potential issue with all exchanges then it makes sense to handle it in the exhange class

**Comment by xmatthias** [comment] 2021-09-03 17:36
it's an issuee in ccxt nonetheless (apparently only for huobi) - sorry, didn't pay 100% attention to the exception before.

but independent of the error or not - i always recommend to use orderbook now - which is also the new default (since a few months).

**Comment by jamesbaber1** [comment] 2021-09-07 14:22
So hit this crash again on what still looks like when it is trying to cancel a partially filled order.
![image](https://user-images.githubusercontent.com/31859220/132360546-90d3155d-0fe5-4764-9d67-84aad72ef09e.png)

I  am using the order book 
![image](https://user-images.githubusercontent.com/31859220/132360926-e2a87c0d-da31-40ec-9307-a32a1ecc5e09.png)

And here is the docker logs
```
021-09-07 10:02:59,531 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:01,537 - freqtrade.freqtradebot - WARNING - Unable to sell trade FIL3L/USDT: Could not create limit sell order on market FIL3L/USDT. Tried to sell amount 615.5173 at rate 1.3781. Message: huobipro {"status":"error","err-code":"order-limitorder-amount-max-error","err-msg":"Number of orders can not be more than 478.6152 FIL3L","data":null}
2021-09-07 10:03:05,556 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:05,559 - freqtrade.freqtradebot - WARNING - Unable to create trade for ETH3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:07,547 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:07,549 - freqtrade.freqtradebot - WARNING - Unable to create trade for ZEC3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:09,542 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:09,544 - freqtrade.freqtradebot - WARNING - Unable to create trade for BTC3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:11,552 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:11,555 - freqtrade.freqtradebot - WARNING - Unable to create trade for EOS3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:13,556 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:13,558 - freqtrade.freqtradebot - WARNING - Unable to create trade for BSV3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:13,559 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2021.8', state='RUNNING'
2021-09-07 10:03:15,542 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=15, pair=LTC3L/USDT, amount=904.40440000, open_rate=1.10570000, open_since=2021-09-07 10:00:21)
2021-09-07 10:03:17,548 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=16, pair=LINK3L/USDT, amount=30023.71870000, open_rate=0.03330700, open_since=2021-09-07 10:00:29)
2021-09-07 10:03:19,537 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=17, pair=XRP3L/USDT, amount=4709.22860000, open_rate=0.21234900, open_since=2021-09-07 10:00:37)
2021-09-07 10:03:21,543 - freqtrade.freqtradebot - INFO - Executing Sell for FIL3L/USDT. Reason: stop_loss
2021-09-07 10:03:23,561 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:25,543 - freqtrade.freqtradebot - WARNING - Unable to sell trade FIL3L/USDT: Could not create limit sell order on market FIL3L/USDT. Tried to sell amount 615.5173 at rate 1.3857. Message: huobipro {"status":"error","err-code":"order-limitorder-amount-max-error","err-msg":"Number of orders can not be more than 478.6152 FIL3L","data":null}
2021-09-07 10:03:29,561 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:29,563 - freqtrade.freqtradebot - WARNING - Unable to create trade for ETH3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:31,573 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:31,575 - freqtrade.freqtradebot - WARNING - Unable to create trade for ZEC3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:33,569 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:33,571 - freqtrade.freqtradebot - WARNING - Unable to create trade for BTC3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:35,574 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:35,576 - freqtrade.freqtradebot - WARNING - Unable to create trade for EOS3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:37,574 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:37,578 - freqtrade.freqtradebot - WARNING - Unable to create trade for BSV3L/USDT: Available balance (617.669778001823 USDT) is lower than stake amount (1000 USDT)
2021-09-07 10:03:39,550 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=15, pair=LTC3L/USDT, amount=904.40440000, open_rate=1.10570000, open_since=2021-09-07 10:00:21)
2021-09-07 10:03:41,553 - freqtrade.freqtradebot - INFO - Buy order cancelled due to timeout for Trade(id=15, pair=LTC3L/USDT, amount=904.40440000, open_rate=1.10570000, open_since=2021-09-07 10:00:21).
2021-09-07 10:03:41,553 - freqtrade.freqtradebot - INFO - Buy order fully cancelled. Removing Trade(id=15, pair=LTC3L/USDT, amount=904.40440000, open_rate=1.10570000, open_since=2021-09-07 10:00:21) from database.
2021-09-07 10:03:43,568 - freqtrade.wallets - INFO - Wallets synced.
2021-09-07 10:03:43,569 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 15, 'type': buy_cancel, 'buy_tag': None, 'exchange': 'Huobi', 'pair': 'LTC3L/USDT', 'limit': 1.1057, 'order_type':'limit', 'stake_amount': 1000.0, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'amount': 904.4044, 'open_date': datetime.datetime(2021, 9, 7, 10, 0, 21, 407928), 'current_rate': 1.1057, 'reason': 'cancelled due to timeout, fully cancelled'}
2021-09-07 10:03:45,554 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=16, pair=LINK3L/USDT, amount=30023.71870000, open_rate=0.03330700, open_since=2021-09-07 10:00:29)
2021-09-07 10:03:47,571 - freqtrade.freqtradebot - INFO - Buy order cancelled due to timeout for Trade(id=16, pair=LINK3L/USDT, amount=30023.71870000, open_rate=0.03330700, open_since=2021-09-07 10:00:29).
2021-09-07 10:03:47,571 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=16, pair=LINK3L/USDT, amount=458.75400000, open_rate=0.03330700, open_since=2021-09-07 10:00:29)
2021-09-07 10:03:49,563 - freqtrade.commands.trade_commands - ERROR - must be real number, not NoneType
2021-09-07 10:03:49,563 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/freqtrade/freqtrade/worker.py", line 111, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/freqtrade/freqtrade/worker.py", line 132, in _throttle
    result = func(*args, **kwargs)
  File "/freqtrade/freqtrade/worker.py", line 145, in _process_running
    self.freqtrade.process()
  File "/freqtrade/freqtrade/freqtradebot.py", line 171, in process
    self.check_handle_timedout()
  File "/freqtrade/freqtrade/freqtradebot.py", line 909, in check_handle_timedout
    self.handle_cancel_buy(trade, order, constants.CANCEL_REASON['TIMEOUT'])
  File "/freqtrade/freqtrade/freqtradebot.py", line 990, in handle_cancel_buy
    self.update_trade_state(trade, trade.open_order_id, corder)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1275, in update_trade_state
    new_amount = self.get_real_amount(trade, order)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1352, in get_real_amount
    return self.fee_detection_from_trades(trade, order, order_amount)
  File "/freqtrade/freqtrade/freqtradebot.py", line 1388, in fee_detection_from_trades
    if not isclose(amount, order_amount, abs_tol=constants.MATH_CLOSE_PREC):
TypeError: must be real number, not NoneType
2021-09-07 10:03:49,564 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2021-09-07 10:03:49,564 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2021-09-07 10:03:49,858 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2021-09-07 10:03:49,859 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "4 open trades active.\n\nHandle these trades manually on Huobi, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \n"}
2021-09-07 10:03:50,166 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2021-09-07 10:03:50,166 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2021-09-07 10:03:50,166 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2021-09-07 10:03:50,194 - uvicorn.error - INFO - Shutting down
2021-09-07 10:03:50,295 - uvicorn.error - INFO - Waiting for application shutdown.
2021-09-07 10:03:50,295 - uvicorn.error - INFO - Application shutdown complete.
2021-09-07 10:03:50,295 - uvicorn.error - INFO - Finished server process [1]
2021-09-07 10:03:50,296 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2021-09-07 10:03:50,296 - apscheduler.scheduler - INFO - Scheduler has been shut down
root@ip-10-0-2-222:~#
```

**Comment by xmatthias** [comment] 2021-09-07 18:59
Without having exchange-response logging turned on (`exchange.log_responses: true` in the config) it's pretty difficult to determine this - especially on an exchange where you're probably the first to run it with.

I suspect (from the context) that `order_amount` is the one at fault in the line pointed out - which can ONLY be `None` if both "filled" and "amount" are both None.
That however would mean that the order was not partially filled, but not filled at all (or the exchange API is lying to you) - and that it's also missing the "amount" section.

---

Please also run the below - so we can see the response you're getting.

The first against the sql database (to get the order_id that you suspect was at fault)

``` sql
select * from orders where ft_trade_id = 16;
```

and the 2nd part in a python shell with ccxt installed (you can get there with docker by running `docker-compose run --rm --entrypoint python3 freqtrade`) - which will get us the response from the exchange.

``` python
import ccxt
exchange = ccxt.huobi({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(order_id, pair)
print(res)
```

**Comment by xmatthias** [comment] 2021-10-20 18:09
@jamesbaber1 any news on this? otherwise i'll have to close this as we'll not be able to recreate the issue.

**Comment by jamesbaber1** [comment] 2021-10-20 18:58
You can close, I ended up moving to KuCoin so I haven't had this issue anymore

**Closed as completed** 2021-10-21 04:30 UTC
Labels: Question, unsupported exchange
