### ISSUE TITLE
Please add volume profile to strategy 

### ISSUE THREAD

**Issue by esmaeilifardi** [freqtrade/freqtrade#8794] opened 2023-06-17 20:50 UTC
## Describe your environment
(if applicable)

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)

## Describe the enhancement

*Explain the enhancement you would like*

**Comment by xmatthias** [comment] 2023-06-18 06:16
Please use the search to see if similar issues already exist (duplicate of #6845).

Also, please get used to fill out the issue template - as well as putting actual content into the issue.

Even without this being a duplicate, i'd have closed this as it has 0 detail or content.

**Closed as completed by xmatthias** 2023-06-18 06:16 UTC
Labels: Duplicate
