### ISSUE TITLE
Enhancement proposition: Sample_full_hyperopt file 

### ISSUE THREAD

**Issue by Kaidokuni** [freqtrade/freqtrade#3004] opened 2020-02-29 23:35 UTC
Hey everyone, 
I had the idea to have a sample_full_hyperopt like we have a sample_strategy file with a lot of indicators in it, where you can just grab the indicator you're interested in but for it to be useful in a hyperopt file the "def buy/sell_strategy_generator"&"def buy/sell indicator_space()" must also be configured, which requires a specific configuration for each indicator, and it can be confusing and subject to error to do it yourself, so it might be good to have a sample_full_hyperopt where all indicators present in the sample_strategy file can also be present in that file in their default characteristic and where you can just take the indicator you want to use. 
(or maybe even have a page in the documentation dedicated to this or a link to how to use the indicators for example).

**Comment by xmatthias** [comment] 2020-03-01 07:58
honestly, i think that's a bad idea. 

Hyperopt is rather complex / verbose to configure ... so this would lead to a multiple 1000 lines file - which will be very difficult to navigate through.

It will lead to people simply enabling all indicators and trying to get a strategy out of it.

The problem is, that approach will have such a huge search-space that it's not going to work with baesian search (what we use) - as hyperopt may run into one local minima, but ignore 100 other, better minimas.

**Comment by Kaidokuni** [comment] 2020-03-01 20:16
@xmatthias I understand your thoughts on the complexities that this would entail that's why said in the end at least maybe having a page in the documentation dedicated to this or a link to how to use the indicators for example. At least to know how to use as many indicators as possible.

And for the problem that would make everyone activate all the indicators I'm in this case I've already thought about it and the computing power of the computer would not solve this problem?
If you can quickly enlighten me on how it works it would be cool, I'm interested to know so I can get better results.

**Comment by xmatthias** [comment] 2020-03-02 05:22
no, mor computational power would not solve this.
That's why it's also mostly pointless to run hyperopt for more than 1000 epochs or so ... - and it's advisable to instead run hyperopt a few times for 1000 epochs - results will almost always differ - sometimes by a lot (unless you use `--random-state`).

I'll let @hroff-1902 explain the details of the why - but very simplified, it's because hyperopt does not use random search, but uses Bayesian search instead - which can find a local minimum in search space - and stay there without finding the other possible minimas.

**Comment by xmatthias** [comment] 2020-05-31 07:22
Since a "full" hyperopt file would increase the search-space too much to be efficiently optimized (not with Bayesian search, anyway), i'll close this as we're very unlikely to ever add this (simply because it does not make sense).

Also, I think users should understand what they do / use - which i don't see given when spoon-feeding finished solutions.

**Closed by xmatthias** 2020-05-31 07:22 UTC
Labels: Hyperopt, Question
