### ISSUE TITLE
configure fee to 0 using --fee argument take default exchange fees instead of 0

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#3594] opened 2020-07-15 07:04 UTC
Hi,

During early stage of developing a strategy i put fees to 0 to see winrate when i close the trade after 1 bar, 2 bars, ... .
No matter i 'force' the fees to 0 it seems the fallback to default exchange fees if the value choose is under the exchange fee.

Have a nice day.

**Comment by xmatthias** [comment] 2020-07-15 07:55
--fee is only applicable to backtesting / hyperopt.

Also - it's not really meant to set to 0 - but to the "real" value the exchange is offering for you (assuming it's different than the default). 
I assume since 0.0 is "falsy", it's assuming it ain't set. try to set it to 0.00001 or something very low - and you'll see that this will fix it.

**Comment by hroff-1902** [comment] 2020-07-15 10:02
should be fixed if confirmed

**Closed** 2020-07-15 17:52 UTC
Labels: Bug
