### ISSUE TITLE
Bug when calculating ROI in backtest

### ISSUE THREAD

**Issue by gianlup** [freqtrade/freqtrade#1478] opened 2019-01-09 08:27 UTC
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Branch: Master | Develop
  * Last Commit ID: _____ (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:

A few days ago user M4DF135H on Slack shared a strategy that showed performance [too good to be true](https://imgur.com/a/W2mq3pn). 

What has caught my attention was the ROI dictionary:
```
minimal_roi = {
    "40": 0.3,
    "30": 0.05,
    "20": 0.07,
    "0": 0.10
}
```

When are used higher values of ROI at higher time durations, the bot fails to calculate the correct rate at which close the trade.

Using `"use_sell_signal": false` and `"ignore_roi_if_buy_signal": false` amplifies the effects.

### Proposed solution:

Change the way bot determines ROI to be applied in function `_get_sell_trade_entry` from `backtesting.py`. Using something like that:
```
# This line don't take in account if profit is > of minimal ROI
# roi_entry = max(list(filter(lambda x: trade_dur > x, self.strategy.minimal_roi.keys())))    
                                                
current_rate = sell_row.high or sell_row.open
current_profit = trade.calc_profit_percent(current_rate)                                             
                            
for duration, threshold in self.strategy.minimal_roi.items():
    if trade_dur <= duration:
        continue
    # The profit must be greater than threshold
    if current_profit > threshold:   
        roi_entry = duration    
        break                        
                            
roi = self.strategy.minimal_roi[roi_entry]
```

I don't know if this is the best approach, I've only adapted code used in `min_roi_reached` in `interface.py`.
  
### Observed Results:

  * What happened? Profit too high
  * What did you expect to happen? Negative profit

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment] 2019-01-09 09:17
the logic of the "roi_entry" line (first line in your snippet) is to get the first value in the ROI dict which has the key bigger than the current duration, which should return the same result than the loop.

so after 21 minutes, it should contain `20` (using your example above) - which will then resolve to a ROI of 0.07.

Looking at the commented line 2 - the problem might be the usage of `max()` - i think `min()` should be used - but will need to test this.

The idea was to simplify the logic of the loop with the above statement once it's proven (apparently it's failing) ... that's why it's done slightly different than in `interface.py`.

**Comment by gianlup** [comment] 2019-01-09 09:40
>the logic of the "roi_entry" line (first line in your snippet) is to get the first value in the ROI dict which has the key bigger than the current duration, which should return the same result than the loop.

>so after 21 minutes, it should contain 20 (using your example above) - which will then resolve to a ROI of 0.07.

exactly, but after 45 min if the profit is grater than 0.05 (30 min) a ROI sell is returned. So the bot calculate the closerate in `_get_sell_trade_entry` using the wrong ROI (0.3).

There are no checks if the current profit is actually greater than that specified in the dictionary.

**Comment by xmatthias** [comment] 2019-01-09 10:11
they don't need to be - these checks have been in the interface.py - where the return-value of "sell_type.ROI" has been determined. 
This part of the code is only ever executed if ROI hit for this trade - so we need the correct value for this to use "ROI" - not the close value of that candle (which would be unrealistic during dry/live running).

**Comment by gianlup** [comment] 2019-01-09 11:43
Sorry but I don't get your point.
I try to explain step by step using the ROI dict above:

1. trade entry
...
2. after 35 min profit is 4%
...
3. after 45 min profit is 6%
4. `should_sell` returns "sell_type.ROI" using `"30": 0.05`
5. now in `_get_sell_trade_entry` we have to calculate the `closerate` to store results
6. BUT since 45 > 40 is used a profit of 0.3 - because `roi_entry=40` so `roi=0.3`
7. the trade is stored with a profit much higher

In this example every time a trade has a profit > 5% and time > 40 min is stored with a profit of 30%.

**Comment by xmatthias** [comment] 2019-01-09 13:05
My point is that changing the code from 
```
roi_entry = max(list(filter(lambda x: trade_dur > x,
                                                self.strategy.minimal_roi.keys())))
```
to 
```
roi_entry = min(list(filter(lambda x: trade_dur > x,
                                                self.strategy.minimal_roi.keys())))
```
should also give you the correct results. 

The idea is to use the lowest entry (time only) where time is above the current trade time. not sure how `max` got in there - as that's clearly wrong.

Checking profit amount again does not make sense.

**Comment by gianlup** [comment] 2019-01-09 13:47
>Checking profit amount again does not make sense.

Yes you are right.

I think changing to min function doesn't fully resolve the problem (at least for a ROI dict like this - very strange). 

Suppose you have a profit of 6% after 45 minutes, the trade will be saved with a 10% profit.

**Comment by xmatthias** [comment] 2019-01-09 14:04
You're right - i'll need to play with this when i get to a "freqtrade" enabled pc, as i think that max used to be correct.

Also quickly testing something does return correct results (play with it yourself eventually)
``` python
roi_keys = [0, 10, 20, 30, 40]
trade_dur = 21
max(list(filter(lambda x: trade_dur > x, roi_keys))) 
>> 20
```

However: if a trade is longer than 45 minutes - then it should only be sold with a profit of > 30% with reason ROI.
If you're saying it returns after 45 minutes, with reason ROI - but without having high > 30% - then that would mean that the problem is not in `backtesting.py` - but in `interface.py`...

**Comment by gianlup** [comment] 2019-01-09 15:35
In my opinion the root problem is the weird ROI dict - I can't see any useful use cases in prod and it sounds like an error:
```
minimal_roi = {
    "40": 0.3, -> maybe it had to be 0.03
    "30": 0.05,
    "20": 0.07,
    "0": 0.10
}
```

>If you're saying it returns after 45 minutes, with reason ROI - but without having high > 30% - then that would mean that the problem is not in backtesting.py - but in interface.py

Yes after 45 min with 6% profit it returns reason ROI because the condition `"30": 0.05` is satisfied - and I think is right. But afterwards in `backtesting.py` it fails to determine which ROI to applicate.

`roi_entry = max(list(filter(lambda x: trade_dur > x, self.strategy.minimal_roi.keys())))` this line works with the assumptions that ROIs are ordered.

 Maybe we can add some sort of validation to the ROI dict like only ascending or descending values and not mixed.

**Comment by xmatthias** [comment] 2019-01-09 18:08
> Yes after 45 min with 6% profit it returns reason ROI because the condition "30": 0.05 is satisfied - and I think is right. But afterwards in backtesting.py it fails to determine which ROI to applicate.

that's wrong to me - after 45 minutes only 0.3 should be active.

i'm not sure - i think that depends on the strategy - i may have a strategy where i want "out quick" - or a bigger win if it takes longer ... at least i can imagine something like this

No matter HOW the roi-dict is composed (descending, ascending, ...) - the above should never happen.

**Comment by gianlup** [comment] 2019-01-09 20:56
Well after thinking more about it I agree with you. The problem is in `interface.py`.

**Comment by xmatthias** [comment] 2019-01-12 12:49
You have been right - all ROI entries > trade_duration have been active in `interface.py`.

I gave fixing this a shot in #1486 ... 
@gianlup  I would appreciate if you could have a look at the proposed fix

Thanks in advance

**Comment by xmatthias** [comment] 2019-01-19 14:41
closing this as #1486 fixes the problem.

**Closed by xmatthias** 2019-01-19 14:41 UTC
Labels: bug
