### ISSUE TITLE
kucoin outworldly losses, entry rate wrong

### ISSUE THREAD

**Issue by hippocritical** [freqtrade/freqtrade#8302] opened 2023-03-10 14:19 UTC
## Describe your environment

  * Operating system: ubuntu 20
  * Freqtrade Version: 2023.2 docker-image (stable)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
This was a dry run, this happened 2x before already with the current stable version.
freqtrade seems to record the entry rate wrong sometimes.
![grafik](https://user-images.githubusercontent.com/41228167/224331667-8c088745-9b45-429f-b504-46ffde9ad1d1.png)
![grafik](https://user-images.githubusercontent.com/41228167/224337846-2d7c4c4c-5657-49c4-8a88-f8b676b79355.png)
![grafik](https://user-images.githubusercontent.com/41228167/224332191-61f5089d-b1c6-4ad5-8201-d4f1ae8a7dc3.png)
![grafik](https://user-images.githubusercontent.com/41228167/224337255-49ae1ca4-1dfa-4a9c-9814-d1dad967a368.png)

It already happened twice on other VPSes that run stable docker too, don't know where this is coming from.
the orders themselves look fine including the amounts, just the profit calculation is totally wrong.

I sadly do not have any logs of that happening, restarted the bot to get the .wal files in the main sqlite and the normal script purges the logs on reboot... 

This will very likely happen again since this happened twice already, if you need to see the logs.

**Comment by xmatthias** [comment] 2023-03-10 15:37
Please provide the output of the following command for the affected trade:
`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>` 
Please use a "details block" to keep the issue itself kindof readable (see below for details on how to do that). 

<details>
<summary>Expand to see how to do details blocks</summary>

```
<details>
<summary>Expand full </summary>
(wrap in tripple ticks `)
Trades output ...
</details>
```
</details>

**Comment by hippocritical** [comment] 2023-03-10 16:35
Trade(id=670, pair=FLOKI/USDT, amount=0.00000000, is_short=False, leverage=1.0, open_rate=0.00370827, open_since=closed)  

Pictures didnt want to be enclosed in details, it breaks the pictures.

**Comment by xmatthias** [comment] 2023-03-10 17:27
well the above info is pointless, - i'd need the command with `--print-json` (for next time).

---

As i have the database containing this trade though:
it's kukoin's fault for not using "sane" limits (maybe also the pair's for not being really sane).

this trade has an amount precision of 1e-10, and a price precision of 1e-9.
This means, the smallest tradable amount for this trade is technically 0.0000000001 FLOKI.
As this is dry-run - we do then round prices and amounts to these limits - effectively having you trade values like 143101.5242977354 (that's the initial entry amount). 
In reality, i doubt you'll be able to trade even `.1 FLOKI` (from a precision perspective)...  as it's that low priced that everything else is a rounding error.

now obviously, KuCoin won't allow that - but their API is really reporting a precision of 1e-10 - so that's the limit that both freqtrade, as well as ccxt are using.

technically, this trade is "almost" open - it's still got an amount of 1e-10 (it's in the database, but we don't show 10 decimals anywhere i think).
Because of this, the Trade amount is getting updated when the recalculation runs.
i can reliably reproduce this calculation hickup - with the outcome being the following (that's when the trade is closing).

```
current_amount_tr=1e-10, current_amount=Precise(0.0000000001), current_stake=Precise(0.0000000000003708269408411112)
```

I do seriously wonder about the logs - as this trade should in reality still be open - as it can't really close if there's amount left.
Without logs, there's little we can look at for this case - as mathematically, based on the values and limits applied, it's correct (even though we know it's not).
The real problem is that the trade is closing - it should stay open due to this rounding error. 
While that'd be a different problem - it'd correspond to how i'd expect it to behave.

That said - i doubt there's too much we can do for this case. I don't think it's a good idea to force-modify the limits the exchange provides (even if they're clearly wrong).
Calculations say it's not fully closed - depending on the pair - still owning 1e-10 could be a valid case, especially if it's against non-USDT stake currencies.

Unfortunately, there's reasons kucoin is not a supported exchange - one point is their api stability - and then it's also just their oddity in handling price and amount limits.

**Comment by hippocritical** [comment] 2023-03-10 18:27
ok, it only happened dry anyways so I dont care if the trade didnt close properly 100% (but 99.9%)

will attach logs when / if this happens again. Dont know of anyone else having that issue, so ... np

**Closed as completed** 2023-03-10 18:32 UTC
Labels: Triage Needed
