### ISSUE TITLE
activate "fee" parameter in config file

### ISSUE THREAD

**Issue by PandaProgParis** [freqtrade/freqtrade#2649] opened 2019-12-12 04:58 UTC
For exemple, on Binance, I use BNB to pay fees at 0.075% against 0.1%.
In documentation it is possible to set "fee" in config file but this parameter is only use with with backtesting.

### Steps to reproduce:

  1. Allow in Binance fees paiements with BNB
  2. Buy a pair in freqtrade
  3. Open database.sqlite
  4. In fee columns, you can see 0.1% and not 0.075%
  
### Observed Results:

Calculs of profits and loss are wrong

### Code to use to fix this problem
In "freqtrade/freqtradebot.py" file Line 424
  ```
        # Fee is applied twice because we make a LIMIT_BUY and LIMIT_SELL
        # fee = self.exchange.get_fee(symbol=pair, taker_or_maker='maker')
        if self.config.get('fee'):
            fee = self.config['fee']
        else:
            fee = self.exchange.get_fee(symbol=pair, taker_or_maker='maker')
  ```

**Comment by xmatthias** [comment] 2019-12-12 06:21
while this may seem like a good idea, i'm not sure that the resulting calculations will be better (they will be in some circumstances, but not in all).

The idea of using `get_fee()` is that it provides the "most basic" fee.
Fees will only get lower after that by 
a) having a ton of volume so raising in tiers
b) using BNB

This means that while your calculations will be slightly off - profits cannot be lower than expected, but can only be higher.

The problem with setting a fixed lower amount is that you can't be sure this really applies for the below reasons:
* you ran out of BNB - so now 1% fees apply again
* you disabled BNB fees to test something and forgot to reenable it

Assuming your fees are set lower than what they really are - then the bot may sell with ROI = 1% - but really has a loss since your calculation is off.


Ideally, we could pull the fees from the exchange, however, unfortunately, i've not yet found how to retrieve that from the API reliably before trading - all "fee" endpoints only return the basic fees (or the tier-based list - but not what tier your'e in).

I think the best way would be to update the fee to the 0.075 after the buy-order did happen. This way, we use the "known" fee of 0.075 - but use the default fee on sell to calculate the profit - since due to the above reasons, this is a valid possibility.

**Comment by hroff-1902** [comment] 2019-12-12 09:40
@xmatthias what about adding custom slippage for dry-run? As a part of the fixed fee value set in the config, so same will be used for backtesting...
(but it will require more changes, not only this kind of simple fix)

**Comment by xmatthias** [comment] 2019-12-12 11:34
that's not necessarily true.

slippage in simulations (backtesting, dry-run) is just a fixed (or dynamic) percentage you subtract from your profits ... so using 0.076 instead of 0.075 would be 0.2% slippage (fees are applied twice).
ideally it could be a random value between two limits to simulate a more realistic slippage - but that would give non-reproducible results, so i'd stay away from that if we can.

It's not very obvious - but even if a separate parameter is added for slippage for simulation modes, the would just be `fee + slippage / 2` - so the result is the same as you'd have by specifying it all in the fee parameter - so i'm not sure what other changes would be needed.

I wouldn't dive into slippage as part of this issue though - since that's not related to this.

**Comment by PandaProgParis** [comment] 2019-12-14 17:47
@xmatthias Hi and thanks for all your work :)

In here, there is commission and commissionAsset in the response of the request. It is not what we are looking for ? (I imagine you saw it already ^^)
[Api Binance new_order-trade](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade)

**Comment by xmatthias** [comment] 2019-12-14 18:27
Yes ... but we need to be carefull - the link points to "new_order" - but commission and commissionAsset (or fee / feeCurrency - as it's called after ccxt) is only available once the order is filled - not when creating a limit order.

**Comment by PandaProgParis** [comment] 2019-12-16 03:43
Ok, thanks again for your work.

**Closed** 2020-05-14 15:48 UTC
Labels: Enhancement, Triage Needed

**Comment by hroff-1902** [comment] 2020-05-14 15:55
the fix was merged into develop, pls verify
