### ISSUE TITLE
VolatilityFilter is not working correctly on okx

### ISSUE THREAD

**Issue by kennylbj** [freqtrade/freqtrade#9850] opened 2024-02-21 04:35 UTC
## Describe your environment

  * Operating system: __Ubuntu 22.04__
  * Python Version: _3.7.3____ (`python -V`)
  * CCXT version: __using docker with latest version of freqtrade___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _2024.1 (image ID 753e49c5dd3a)___ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

`VolatilityFilter` is not working correctly in the latest freqtrade (image id 753e49c5dd3a) on okx exchange, but it did work in the old version of freqtrade (image id 1ae1d68a76ef)

Once the VolatilityFilter is applied in the config, all pairs will be filtered with the output `Removed xxx/USDT from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.02-0.75`.

*Explain the problem you have encountered*

### Steps to reproduce:

  1. pull the latest version of freqtrade using docker
  2. config VolatilityFilter in pairlists
  3. docker compose up -d
  
### Observed Results:

  * What happened?

  All pairs will be filtered with the output `Removed xxx/USDT from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.02-0.75`.

  * What did you expect to happen?

  VolatilityFilter works correctly on okx

Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

```json
{
            "method": "VolatilityFilter",
            "lookback_days": 3,
            "min_volatility": 0.02,
            "max_volatility": 0.75,
            "refresh_period": 1800
        },
```

  ```
2024-02-21 04:24:19,891 - VolatilityFilter - INFO - Removed ETH/USDT from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.02-0.75.
  ```

**Comment by xmatthias** [comment] 2024-02-21 05:45
Docker Image id's are not deterministic (and as such - not really relevant outside of your system) - please use `freqtrade -V` to provide the proper version.

---

Testing this with a (very much reduced) pairlist (4 pairs) (on the latest develop with uptodate dependencies) - it's not something i can reproduce.

static pairlist in front of your volatilityfilter:

```
           "SOL/USDT",
           "XRP/USDT",
           "BTC/USDT",
           "ETH/USDT",
```

```
2024-02-21 06:41:52,395 - VolatilityFilter - INFO - Removed XRP/USDT from whitelist, because volatility over 3 days is: 0.010 which is not in the configured range of 0.02-0.75.
2024-02-21 06:41:52,396 - VolatilityFilter - INFO - Removed BTC/USDT from whitelist, because volatility over 3 days is: 0.014 which is not in the configured range of 0.02-0.75.
2024-02-21 06:41:52,397 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 2 pairs: ['SOL/USDT', 'ETH/USDT']

```


Now the range starts at 2% ... which i assume is intentional - so it's justified to throw out XRP and BTC ... but that's a configuration setting, and the bot is clearly stating so, too.

It might be that you ran into a temporary problem with the exchange itself - but at the moment of writing this - it's not something i can reproduce / recreate - volatilityfilter does work fine - on both okx spot and futures.

**Comment by kennylbj** [comment] 2024-02-21 06:41
Do you use the freqtrade 2024.1 on okx? I tested on 2 environments and both have this error.

It is worth noting that the old freqtrade did work fine on okx.

Here is my completed pairlist config 
```json
"pairlists": [
        {
            "method": "VolumePairList",
            "number_assets": 35,
            "sort_key": "quoteVolume",
            "refresh_period": 1800
        },
        {
            "method": "AgeFilter",
            "min_days_listed": 14
        },
        {
            "method": "SpreadFilter",
            "max_spread_ratio": 0.005
        },
        {
            "method": "PriceFilter",
            "low_price_ratio": 0.10,
            "min_price": 0.001
        },
        {
            "method": "RangeStabilityFilter",
            "lookback_days": 3,
            "min_rate_of_change": 0.05,
            "refresh_period": 1800
        },
        {
            "method": "VolatilityFilter",
            "lookback_days": 3,
            "min_volatility": 0.02,
            "max_volatility": 0.75,
            "refresh_period": 1800
        },
        {
            "method": "VolumePairList",
            "number_assets": 30,
            "sort_key": "quoteVolume"
        }
    ],
```

**Comment by Alexwijn** [comment] 2024-02-21 18:05
I can confirm that I also have the same issue since past week, but on Bitvavo. I tried downgrading, but that obvious won't work due the migrations. I also tried `develop` without any success.

````
2024-02-21 19:01:32 | 2024-02-21 18:01:32,238 - VolatilityFilter - INFO - Removed BTC/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,241 - VolatilityFilter - INFO - Removed JASMY/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,244 - VolatilityFilter - INFO - Removed ETH/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,247 - VolatilityFilter - INFO - Removed SOL/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,250 - VolatilityFilter - INFO - Removed FET/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,255 - VolatilityFilter - INFO - Removed ADA/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,258 - VolatilityFilter - INFO - Removed WLD/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,261 - VolatilityFilter - INFO - Removed GLM/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,264 - VolatilityFilter - INFO - Removed XRP/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,267 - VolatilityFilter - INFO - Removed VTHO/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,269 - VolatilityFilter - INFO - Removed VET/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,272 - VolatilityFilter - INFO - Removed RLC/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,275 - VolatilityFilter - INFO - Removed MANTA/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,278 - VolatilityFilter - INFO - Removed XAI/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,281 - VolatilityFilter - INFO - Removed FIL/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,284 - VolatilityFilter - INFO - Removed RNDR/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,287 - VolatilityFilter - INFO - Removed ALT/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,290 - VolatilityFilter - INFO - Removed SEI/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,293 - VolatilityFilter - INFO - Removed HBAR/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,296 - VolatilityFilter - INFO - Removed MATIC/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,298 - VolatilityFilter - INFO - Removed LINK/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
2024-02-21 19:01:32 | 2024-02-21 18:01:32,301 - VolatilityFilter - INFO - Removed AGIX/EUR from whitelist, because volatility over 3 days is: nan which is not in the configured range of 0.05-0.75.
````

**Comment by xmatthias** [comment] 2024-02-21 19:58
it seems like what changed is that okx is no longer providing the candles correctly.

providing 2024.1 with a start-date of 1708041600000 - which is midnight on the 16th - the start-date of the daily candle from the 16th, does no longer yield the 16th candle on okx.
Other exchanges don't seem to be impacted by this - which is why all reports focus on okx.

I'm pretty sure this changed recently - as we didn't have changes to these files in the last 3 months (up to 2024.1). now develop changed slightly - but current changes don't really affect behavior with okx - neither does it  address this at the moment, as it seems to be a "since" bug in okx more tha anything.

**Comment by abbaselmas** [comment] 2024-02-21 20:57
I am having this problem on binance, its not only okx problem.
In my tests on pairlist filters, combination of Volatility and RangeFilter is the problem. Cause of the problem lies on the last week updates on freqtrade.

**Comment by kennylbj** [comment] 2024-02-22 02:30
> it seems like what changed is that okx is no longer providing the candles correctly.

> I'm pretty sure this changed recently - as we didn't have changes to these files in the last 3 months (up to 2024.1). now develop changed slightly - but current changes don't really affect behavior with okx - neither does it address this at the moment, as it seems to be a "since" bug in okx more tha anything.

This can't explain why it would work if I downgrade the freqtrade to 2023.12.

**Comment by xmatthias** [comment] 2024-02-22 06:08
> In my tests on pairlist filters, combination of Volatility and RangeFilter is the problem. Cause of the problem lies on the last week updates on freqtrade.

then it's a different problem than the one here - not related besides the name of the module seemingly causing it - and one that will be fixed in the very last version (once i push).

The particular issue here can ONLY be reproduced on okx - but on no other exchange (which is odd in it's own right - but that's a different topic entirely).

---

> This can't explain why it would work if I downgrade the freqtrade to 2023.12.

Well yes it can - ccxt updates happen roughly once a day - we update the pinned dependency roughly once a week.
A changed since offset by 1 is probably not something we actively test for ... at least not as far as i'm aware.

there's a few changes in this section of the okx exchange - and downgrading ccxt to below this point does seem to fix it (`ccxt==4.1.98`)
 
for example (most likely suspect) here: https://github.com/ccxt/ccxt/pull/20802).


Comaring the raw logs for this (reduced pairlist for simplicity)- we get the following segments:
ccxt==4.1.98:

```
2024-02-22 07:01:54,311 - freqtrade.exchange.exchange - DEBUG - Fetching pair BTC/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:01:54,311 - freqtrade.exchange.exchange - DEBUG - Fetching pair SOL/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:01:54,311 - freqtrade.exchange.exchange - DEBUG - Fetching pair LTC/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:01:54,311 - freqtrade.exchange.exchange - DEBUG - Fetching pair XRP/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:01:54,311 - freqtrade.exchange.exchange - DEBUG - Fetching pair ETH/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:01:54,415 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=1Dutc&limit=300&before=1708127999999&after=1734047999999, Request: None None
2024-02-22 07:01:54,467 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=SOL-USDT&bar=1Dutc&limit=300&before=1708127999999&after=1734047999999, Request: None None
2024-02-22 07:01:54,518 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=LTC-USDT&bar=1Dutc&limit=300&before=1708127999999&after=1734047999999, Request: None None
2024-02-22 07:01:54,569 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=XRP-USDT&bar=1Dutc&limit=300&before=1708127999999&after=1734047999999, Request: None None
2024-02-22 07:01:54,618 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=1Dutc&limit=300&before=1708127999999&after=1734047999999, 
```


ccxt==4.1.25 (pinned version of 2024.1)
```
2024-02-22 07:03:01,631 - freqtrade.exchange.exchange - DEBUG - Fetching pair XRP/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:03:01,631 - freqtrade.exchange.exchange - DEBUG - Fetching pair ETH/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:03:01,631 - freqtrade.exchange.exchange - DEBUG - Fetching pair SOL/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:03:01,631 - freqtrade.exchange.exchange - DEBUG - Fetching pair BTC/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:03:01,631 - freqtrade.exchange.exchange - DEBUG - Fetching pair LTC/USDT, spot, interval 1d, since 1708128000000 (2024-02-17T00:00:00+00:00) ...
2024-02-22 07:03:01,734 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=XRP-USDT&bar=1Dutc&limit=300&before=1708128000000&after=1734048000000, Request: None None
2024-02-22 07:03:01,786 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=ETH-USDT&bar=1Dutc&limit=300&before=1708128000000&after=1734048000000, Request: None None
2024-02-22 07:03:01,838 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=SOL-USDT&bar=1Dutc&limit=300&before=1708128000000&after=1734048000000, Request: None None
2024-02-22 07:03:01,890 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=1Dutc&limit=300&before=1708128000000&after=1734048000000, Request: None None
2024-02-22 07:03:01,940 - ccxt.base.exchange - DEBUG - GET https://www.okx.com/api/v5/market/candles?instId=XRP-USDT&bar=1Dutc&limit=300&before=1708128000000&after=1734048000000, 
```

Now the important part are the URL's ccxt uses - which result in
`https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=1Dutc&limit=300&before=1708127999999&after=1734047999999`
and `https://www.okx.com/api/v5/market/candles?instId=BTC-USDT&bar=1Dutc&limit=300&before=1708128000000&after=1734048000000` respectively ... clearly having an offset of one (or missing one),  which is also leading to slightly different results.


![image](https://github.com/freqtrade/freqtrade/assets/5024695/07d54941-aaec-476b-b604-6060c4402746)
![image](https://github.com/freqtrade/freqtrade/assets/5024695/07d01e04-bd0f-4eab-a191-a15ce407f3b1)

**Comment by kennylbj** [comment] 2024-02-22 08:04
@xmatthias Thanks for your detailed reply. 

Can I assume that this issue is caused by the cctx library mistakenly having an offset of one when calling the okx API? 

I also wonder if it will be fixed by freqtrade in the next released version.

**Comment by LeCmnGend** [comment] 2024-02-22 10:03
> I am having this problem on binance, its not only okx problem. In my tests on pairlist filters, combination of Volatility and RangeFilter is the problem. Cause of the problem lies on the last week updates on freqtrade.

me have the same error

**Comment by xmatthias** [comment] 2024-02-22 16:16
I'd say we'll see ... I've just opened  https://github.com/ccxt/ccxt/issues/21333 - we'll see if we'll get a fix quickly.

I don't see us fixing this via workaround - at least not for now (might change based on the result of the ccxt issue) - as that'd have negative impacts to other exchanges - which obviously, we'd not want.

**Comment by xmatthias** [comment] 2024-02-23 05:35
@kennylbj would you mind testing the develop version? (make sure to update dependencies).

I cannot recreate the issue you're seeing on the last version ... so i think it was a temporary glitch in ccxt (in a few versions) - which has been fixed since.

**Comment by kennylbj** [comment] 2024-02-23 07:19
@xmatthias I have tested the `freqtradeorg/freqtrade:develop` on okx, and it is working fine.

**Comment by abbaselmas** [comment] 2024-02-23 07:28
With latest updates, no problem on binance too

**Comment by Alexwijn** [comment] 2024-02-23 07:29
I can also confirm it's working again on Bitvavo.

**Closed as completed** 2024-02-23 09:00 UTC
Labels: Question, Pairlist
