### ISSUE TITLE
Partially filled sell orders never get cancelled

### ISSUE THREAD

**Issue by AngryByte** [freqtrade/freqtrade#3802] opened 2020-09-25 14:58 UTC
* Operating system: docker image freqtradeorg/freqtrade:master 
  * Freqtrade Version: 2020.6
  

## Describe the problem:

When a sell signal is received and the order is partially filled, the bot will keep the unfilled part of the order open indefinitely with no enforcement of timeouts, or other sell signals.

The log will show "partially filled - keeping order open" 

### Steps to reproduce:

  1. an order is open for 0.1 BTC
  2. the order receives a sell signal and its created on the exchange
  3. only 0.01 gets filled

The only way around this issue is manually deleting the order on the exchange to avoid significant losses on market crashes
  
### Observed Results:

  1. after the sell order timeout, the log will show  "partially filled - keeping order open" 
  2. sending a "/stop" with "cancel_open_orders_on_exit = true" in config will not cancel the order contradicting the documentation that it should
  3. sending a "/forcesell" will not update the sell price on the exchange
  4. /status  becomes partially broken and stops updating the current rate

### Relevant code exceptions or logs

I believe the following code is responsible:
```
def handle_cancel_sell(self, trade: Trade, order: Dict, reason: str) -> str:
        """
        Sell cancel - cancel order and update trade
        :return: Reason for cancel
        """
        # if trade is not partially completed, just cancel the order
        if order['remaining'] == order['amount'] or order.get('filled') == 0.0:
            if not self.exchange.check_order_canceled_empty(order):
                try:
                    # if trade is not partially completed, just delete the order
                    self.exchange.cancel_order(trade.open_order_id, trade.pair)
                except InvalidOrderException:
                    logger.exception(f"Could not cancel sell order {trade.open_order_id}")
                    return 'error cancelling order'
                logger.info('Sell order %s for %s.', reason, trade)
            else:
                reason = constants.CANCEL_REASON['CANCELLED_ON_EXCHANGE']
                logger.info('Sell order %s for %s.', reason, trade)

            trade.close_rate = None
            trade.close_rate_requested = None
            trade.close_profit = None
            trade.close_profit_abs = None
            trade.close_date = None
            trade.is_open = True
            trade.open_order_id = None
        else:
            # TODO: figure out how to handle partially complete sell orders
            reason = constants.CANCEL_REASON['PARTIALLY_FILLED_KEEP_OPEN']
```

A possible solution would be to cancel the sell order even if parially filled and keep the trade open waiting for a new sell signal/roi/or stop_loss

**Comment by xmatthias** [comment] 2020-09-25 17:33
Please use the search to discover if certain points have already been raised before.

That's therfore a duplicate of #3009
Since that other issue includes extensive discuussion on how this could be handled and potentiall gotchas, i'm going to close this issue.

Please read through the other issue, and if you have comments, questions or additions to what was said there, or have ideas or would like to contribute to a solution, please let's discuss thiiss in that issue, thanks.

**Closed by xmatthias** 2020-09-25 17:33 UTC
Labels: Duplicate
