### ISSUE TITLE
1m strategy cycle time too slow

### ISSUE THREAD

**Issue by Alvised** [freqtrade/freqtrade#7247] opened 2022-08-17 23:23 UTC
hi everyone, i'm still learning from every strategy i've found and i'm tryiing to understand every part of the software.. now i'm testing live dryrun with different ema, 1m timerange, but i see my bot is extremely slow, it buy and sell like 3 minutes after the crossing,it's almost logic since i'm doing a check of the current cadle and the shift(1) one to find the crossing, but this is often too much to buy and sell on time and get a profit during a scalping.. is there a way to have the current price? i've seen i could maybe calculate it from the order book,and even in this case how often the order book is updated by freqtrade?..  i wonder what is the best way to have  the lesser delay.
i've seen there is 

ticker = self.dp.ticker(metadata['pair'])
 dataframe['last_price'] = ticker['last']

is this the correct one to use in this case or there is a better one?
I don't ask to have data of the last millisecond, but more or less as live as the one i see on the website of the exchange(a couple of seconds),or minimum 20 seconds.. is it possible?

**Comment by xmatthias** [comment] 2022-08-18 05:27
Transferred this to the main repository - as it's a question that fits here better.

---

Most likely, you've got too big a pairlist for 1m timeframe.

Freqtrade will need time to download the pairs. While this is done in an asyncronous way - we still need to respect the limits of the exchange - which vary greatly (kraken is the worst in that regard) - so it's not instant to get the candle data - so you can expect a few seconds from that.

it'll then walk through the pairlist, doing the indicator calculations (reduce this to only the ones you really use to speed things up).
Now if you're using a 50 pair whitelist - and it takes 1s to calculate the signals for this pair - then you'll most likely end up in the next candle with your calculations - so it's really no longer working.

To be perfectly honest, i think 1m is not a good timeframe to start with freqtrade (or trading in general). 
There'll be a lot of noise - and all calculations must be very quick and optimized to fit into the 1m timerange.

---

`self.dp.ticker(metadata['pair'])` and the corresponding orderbook method are active calls - so they reach out to the exchange, querying the data.
This will make your bot slower (a lot!) - not faster. I'd stay away from this unless you have very specific needs (like analyzing orderbook depth or something similar).

**Comment by stash86** [comment] 2022-08-18 05:27
the issue isn't about current price/ticker data. Your vps/cpu isn't capable of handling your demand. Reduce your pairlist and/or indicators, and/or use better cpu/vps

**Comment by Alvised** [comment] 2022-08-18 11:26
thank you for your answers i reduced the white list and indicators to just btc/usdt and see its anyway too slow.. i tried with the ticker and current price.. and now it's tuned with the binance website,i got the buy signal in the exaxt moment i see the line crossing... so i guess there are probably some errors in the way i calculate emas crossing..
@xmatthias: yes i agree, usually i use 15m or 1hour.. but i want to have data also on the noise, reaction time, orderbook and all the feature i cannot backtest,so 1m help me to get more trades to valuate.
@stash86 for sure i can reduce indicators, i was coding on top of SampleStrategy and i don't use many of thoose indicators at the moment.. For the faster cpu, i'm on a i7 6000something.. i tried on my newer laptop that i use as render machine and still slow, so i belive the problem are my low skills on coding with py..

**Comment by xmatthias** [comment] 2022-08-18 12:39
"too slow" is relative - the dataframe will always have the prices from the prior candle.

too slow should be measured in cycle time - that can also be caused by odd ratelimit settings for the exchange - where it'll wait X seconds before doing the next  request.

**Closed as completed** 2022-08-25 18:56 UTC
Labels: Question, Strategy assistance
