### ISSUE TITLE
One of the Bot keep restarting [Docker]

### ISSUE THREAD

**Issue by Ath3r** [freqtrade/freqtrade#9845] opened 2024-02-19 19:27 UTC
## Describe your environment

  * Operating system: Ubuntu 22.04.3 LTS 64 bit
  * Python Version: 3.11 
  * CCXT version: ccxt==4.2.25 
  * Freqtrade Version: freqtrade 2024.1 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Im running 2 Binance bots on docker with strategy NFIX4 (which updates every now and then). Everything was good with 2023.12 then after upgrading to the next stable version ie 2024.1 . Then one of the Binance bot starts restarting every 10mins to X hrs. 

Now as a temporary solution I have downgraded one of the offset bots to 2023.12 and it seems stable.

### Steps to reproduce:

  1. Docker setup with NFIX4 on Binance.
  2. Let the bot run for a few mins and it gets into a restart loop.

  
### Observed Results:

  * What happened?
>One of the bot keeps restarting until stopped.
  * What did you expect to happen?
  >Bot should not keep restarting over and over.

### Relevant code exceptions or logs

First Logs dump

  ```
Fatal Python error: Segmentation fault

Current thread 0x00007f69869fe6c0 (most recent call first):
  File "/home/ftuser/.local/lib/python3.11/site-packages/pydantic/type_[adapter.py](https://adapter.py/)", line 239 in validate_python
  File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/_[compat.py](https://compat.py/)", line 125 in validate
  File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_[asyncio.py](https://asyncio.py/)", line 851 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f6993fff6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f69932fe6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f69af0fe6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f69af9ff6c0 (most recent call first):
  File "/usr/local/lib/python3.11/[selectors.py](https://selectors.py/)", line 468 in select
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 1884 in _run_once
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 607 in run_forever
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 640 in run_until_complete
  File "/freqtrade/freqtrade/rpc/api_server/uvicorn_[threaded.py](https://threaded.py/)", line 54 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f69b48ca6c0 (most recent call first):
  File "/usr/local/lib/python3.11/[selectors.py](https://selectors.py/)", line 468 in select
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 1884 in _run_once
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 607 in run_forever
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 640 in run_until_complete
  File "/freqtrade/freqtrade/rpc/[telegram.py](https://telegram.py/)", line 274 in _init
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f69b792a6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f6a24d0eb80 (most recent call first):
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/[exchange.py](https://exchange.py/)", line 510 in throttle
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/[exchange.py](https://exchange.py/)", line 3344 in fetch2
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/[binance.py](https://binance.py/)", line 8177 in request
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/[types.py](https://types.py/)", line 34 in unbound_method
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/[binance.py](https://binance.py/)", line 3028 in fetch_ticker
  File "/freqtrade/freqtrade/exchange/[exchange.py](https://exchange.py/)", line 1579 in fetch_ticker
  File "/freqtrade/freqtrade/exchange/[common.py](https://common.py/)", line 168 in wrapper
  File "/freqtrade/freqtrade/data/[dataprovider.py](https://dataprovider.py/)", line 505 in ticker
  File "/freqtrade/user_data/strategies/[x3.py](https://x3.py/)", line 8555 in long_grind_adjust_trade_position
  File "/freqtrade/user_data/strategies/[x3.py](https://x3.py/)", line 8489 in adjust_trade_position
  File "/freqtrade/freqtrade/strategy/strategy_[wrapper.py](https://wrapper.py/)", line 27 in wrapper
  File "/freqtrade/freqtrade/[freqtradebot.py](https://freqtradebot.py/)", line 648 in check_and_call_adjust_trade_position
  File "/freqtrade/freqtrade/[freqtradebot.py](https://freqtradebot.py/)", line 622 in process_open_trade_positions
  File "/freqtrade/freqtrade/[freqtradebot.py](https://freqtradebot.py/)", line 244 in process
  File "/freqtrade/freqtrade/[worker.py](https://worker.py/)", line 180 in _process_running
  File "/freqtrade/freqtrade/[worker.py](https://worker.py/)", line 147 in _throttle
  File "/freqtrade/freqtrade/[worker.py](https://worker.py/)", line 116 in _worker
  File "/freqtrade/freqtrade/[worker.py](https://worker.py/)", line 75 in run
  File "/freqtrade/freqtrade/commands/trade_[commands.py](https://commands.py/)", line 25 in start_trading
  File "/freqtrade/freqtrade/[main.py](https://main.py/)", line 42 in main
  File "/home/ftuser/.local/bin/freqtrade", line 8 in <module>
  ```

Second dump

```
Fatal Python error: Segmentation fault

Current thread 0x00007f4a03bff6c0 (most recent call first):
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/[exchange.py](https://exchange.py/)", line 1159 in iso8601
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/[binance.py](https://binance.py/)", line 2954 in parse_ticker
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/base/[exchange.py](https://exchange.py/)", line 4384 in parse_tickers
  File "/home/ftuser/.local/lib/python3.11/site-packages/ccxt/[binance.py](https://binance.py/)", line 3199 in fetch_tickers
  File "/freqtrade/freqtrade/exchange/[exchange.py](https://exchange.py/)", line 1549 in get_tickers
  File "/freqtrade/freqtrade/exchange/[common.py](https://common.py/)", line 168 in wrapper
  File "/freqtrade/freqtrade/exchange/[binance.py](https://binance.py/)", line 54 in get_tickers
  File "/freqtrade/freqtrade/rpc/[rpc.py](https://rpc.py/)", line 649 in _rpc_balance
  File "/freqtrade/freqtrade/rpc/api_server/api_[v1.py](https://v1.py/)", line 79 in balance
  File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_[asyncio.py](https://asyncio.py/)", line 851 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f4a01bfa6c0 (most recent call first):
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 327 in wait
  File "/usr/local/lib/python3.11/[queue.py](https://queue.py/)", line 171 in get
  File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_[asyncio.py](https://asyncio.py/)", line 840 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f4a21ffb6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f4a22ffd6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f4a31d9e6c0 (most recent call first):
  File "/usr/local/lib/python3.11/[selectors.py](https://selectors.py/)", line 468 in select
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 1884 in _run_once
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 607 in run_forever
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 640 in run_until_complete
  File "/freqtrade/freqtrade/rpc/api_server/uvicorn_[threaded.py](https://threaded.py/)", line 54 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f4a3269f6c0 (most recent call first):
  File "/usr/local/lib/python3.11/concurrent/futures/[thread.py](https://thread.py/)", line 81 in _worker
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap

Thread 0x00007f4a333a06c0 (most recent call first):
  File "/usr/local/lib/python3.11/[selectors.py](https://selectors.py/)", line 468 in select
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 1884 in _run_once
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 607 in run_forever
  File "/usr/local/lib/python3.11/asyncio/base_[events.py](https://events.py/)", line 640 in run_until_complete
  File "/freqtrade/freqtrade/rpc/[telegram.py](https://telegram.py/)", line 274 in _init
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 982 in run
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1045 in _bootstrap_inner
  File "/usr/local/lib/python3.11/[threading.py](https://threading.py/)", line 1002 in _bootstrap
```

**Comment by xmatthias** [comment] 2024-02-19 20:04
The error is a segmentation fault - which is a low-level error of python (you usually won't get a proper stacktrace).
The errors show all threads that are still up - but not what actually caused the segfault.

Most common cases of this include out of memory problems - or access violations (which is a level freqtrade won't go down to).
Now i do run several bots (live, dry) on the latest versions and don't encounter this problem - so i'm pretty confident that this is not a freqtrade problem - but a problem with your strategy.

Best verify how your memory looks like (it sounds like one bot is stable - which might suggest that the 2nd bot doesn't get sufficient memory ...?).


Please do a simple test-run of your setup with the provided `SampleStrategy` (should be auto-populated into your user_data directory when running `create-userdir`).
Assuming the bot is stable with that strategy - best remove parts of your strategy one by one to identify the faulty part - which could be with the calculation of an indicator - or with some other random logic.

**edit** you might also wanna look at the system level log (`journalctl`) - which often contains more info on segfaults.

**Comment by iterativv** [comment] 2024-02-24 09:19
To help identify the issue, is there any changes to API server from 2023.12 to 2024.1 that can cause this ? It should be multiple bots, maybe docker specific only. Maybe there is a shared resource ? Something else ? Or even a single bot, this is not definitive. There is a limitation to data size, maybe ?

I run many bots, but never encountered this. So, I can't debug and locate the issue. There is this case and someone else. That second case, after turned the api_server off, there are no segfaults anymore.

**Comment by xmatthias** [comment] 2024-02-24 11:57
Dependencies are updated all the time - though i'm not aware of any causing problems (neither did i encounter such problems on my bots).

Considering we didn't get further info, nor logs (journalctl often contains further information) - there's nothing we can do here.
The most likely cause is memory - which you can reduce by turning off things.

**Comment by hippocritical** [comment] 2024-02-24 12:05
it looks like it runs out of memory, does it?
please check memory usage - segmentation fault is usually the emergency break when you cannot run something on that machine tbh

**Comment by iterativv** [comment] 2024-02-24 17:06
> it looks like it runs out of memory, does it?
> please check memory usage - segmentation fault is usually the emergency break when you cannot run something on that machine tbh

It seems that it was a config issue after all. I think the server got 20G or more and is using less than 1G per bot. Mixed the ports, docker & CORS setup.

Edit: probably is real issue, that is affecting few setups. Not a configuration issue.

**Comment by xmatthias** [comment] 2024-02-25 12:07
>  probably is real issue, that is affecting few setups. Not a configuration issue.

If it **were** a real issue (not saying it isn't - but so far, i don't see any hint on that) - then people would
* report it - properly (this issue is fine as is per se - but didn't get further feedback - leading to the conclusion that the suggestions provided di fix the issue)
* answer after being asked for logs (in the above case, output of `journalctl`)
* Try the suggested approach (Does it happen with the SampleStrategy)?

If neither of these happens - then it's not a general issue.

it might very well be a problem with a missbehaving strategy - which is consuming more memory than it should (hence the question - does it reproduce with plain SampleStrategy setups?) - but that's not an issue we'll try to fix at the level of this repo.

From all i can tell so far - it's a single issue (the author reporting it here) - who didn't answer after the initial issue.
If we get no further details - then it's not something we can look at.

**Comment by rmtucker** [comment] 2024-02-25 13:47
docker compose log when the bot restarts for me
[docker compose log](https://github.com/freqtrade/freqtrade/files/14396519/docker.compose.log)

**Comment by xmatthias** [comment] 2024-02-25 13:53
well the error is a segmentation fault ... which effectively means - there is no error at python level - but it's usually a lower(ish) level access violation.

what does journalctl say about this ? 
how long has that bot been up ?

**Comment by rmtucker** [comment] 2024-02-25 13:58
That bot was only up minutes before it restarted as above
journalctl logs for around the same time below

[journalctl log](https://github.com/freqtrade/freqtrade/files/14396552/journalctl.log)

As soon as i turn off the API server on that bot the restarts stop happening

**Comment by xmatthias** [comment] 2024-02-25 14:08
Well journalctl logs are incomplete (truncated to the right) - but don't seem to contain much useful.

Problems can however just as well originate from other things - like excessive memory usage or from things done within the strategy.
Removing parts of the bot (like the API server) would then help - as that'll reduce the overall necessary memory footprint.

best try this with a combination of multiple SampleStrategies (on the problematic system, obviously - with a stop of the existing containers beforehand) - so we can rule out interferences from the strategy (ideally on a new userdir - which only really has your configurations).

---

I'm running a test with 3 paralell bots (all have their API enabled) since over an hour with 2024.1 now (no problems) - and just restarted them with the latest develop image - but so far - all just "idle along" as they should do - though one has an open trade (that's an old database ...) - so is slightly more verbose (though no restarts or issues).

**Comment by rmtucker** [comment] 2024-02-25 15:21
"best try this with a combination of multiple SampleStrategies (on the problematic system, obviously - with a stop of the existing containers beforehand) - so we can rule out interferences from the strategy (ideally on a new userdir - which only really has your configurations)."

I wish my knowledge extended that far but unfortunately i have 16 open trades across the open bots,and i really dont want to screw them up.
But i did try commenting the 2 well behaved bots out of docker-compose.yml then restarted so only the troublesome bot "kucoin" was running and the restarts were happening every 5 mins or so.
Sorry i can not be of much more help

**Comment by xmatthias** [comment] 2024-02-25 15:34
@rmtucker so the problem appears only if one of the bots is running against kucoin? (also if that bot is the only one??)

That'd explain why my 3 bots (combination of binance and bybit) are running perfectly fine ... and will probably continue to do so.

or are all bots against kucoin - and it's one particular bot which is triggering (independent of all other bots)?
in which case - i'd need you to figure out the difference (i assume it's either 3 different strategies - or 3 different exchanges ... ? )

**Comment by rmtucker** [comment] 2024-02-25 15:49
I have 3 bots binance/gateio/kucoin.
All using the same strategy.
And i can not be 100% certain but i would say that the kucoin bot is causing the problem.
99.9% of the restarts are on the kucoin bot,But 0.1% of the restarts have been Gateio,But that may be a consequence of the kucoin bot interacting somehow.
This never or very rarely happened when i was using the last stable 2023.12 but the last stable 2024.1 and recent develop,i have this problem.

**Comment by rmtucker** [comment] 2024-02-25 16:01
Maybe worthwhile mentioning that some of these trades that are open have hundreds of position adjustments or grinding entries and exits as we call them.
This maybe another reason the problem might not manifest in a simple test if you know what i mean.
just an example
  ID  Pair        Since     Profit      # Entries
----  ----------  --------  --------  -----------
229   XPR/USDT    8 months  11.24%             78
272   SHILL/USDT  6 months  -10.03%            94
288   TARA/USDT   6 months  -15.89%           107
336   SATS/USDT   1 month   -10.65%            30
337   APT/USDT    1 month   -2.13%             23
346   MYRO/USDT   3 weeks   -15.43%            22

**Comment by xmatthias** [comment] 2024-02-26 05:55
> Maybe worthwhile mentioning that some of these trades that are open have hundreds of position adjustments or grinding entries and exits as we call them.

which would support my previous suspicion that it's an out of memory problem (maybe not directly, but in one of the dependencies).
It's clearly not a good approach to do 100ds of position adjustments - as these orders will always be attached to the trade - and hence will also always float around in memory.

---

For the issue at hand - i can't reproduce it with regular / simple strategies - but i'm happy to look at this if we have a minimal reproduction for this. 
Otherwise, i'll assume this as out of memory problem - caused by a potentially missbehaving strategy (having 107 adjustment orders is not regular, nor recommended behavior).

**Comment by Ath3r** [comment] 2024-02-26 08:20
Hi,

i have been away lately due to work. I will share the journal logs, I will also try replicating the issue with the SimpleStrategy. 

Now Im on version version: docker-2024.2-dev-db83b0cd

now this version seems stable to me which suggests there is no issue with the strategy. 

Below is a list of positions for me.


ID  Pair           Since     Profit      # Entries
----  -------------  --------  --------  -----------
 93   STORJ/USDT     2 months  -1.90%             33
136   1000SATS/USDT  1 month   -8.42%             30
140   APT/USDT       1 month   -3.65%             27

**Comment by xmatthias** [comment] 2024-02-26 09:29
Well there's been no changes in this regards that should impact that - unless it's some random dependency causing it.
That's true for both 2023.12 -> 2024.1 - as well as 2024.1 -> develop ... 
The webserver components didn't change significantly recently - at least not to a degree which i could imagine causing such an issue.

well 30 adjustments is not "that" excessive - though I'd suggest to update your strategy to close out positions after a few adjustments.
all orders will be kept in memory for the duration of the trade - so closing / reopening a trade will probably help with both memory consumption, as well as with performance (though that'll probably be negligible if sufficient memory is available)

**Comment by rmtucker** [comment] 2024-02-26 10:51
I do not think it is a memory issue
CONTAINER ID   NAME                     CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
2e6e674211d5   freqtrade_binance_usdt   2.53%     771.7MiB / 23.43GiB   3.22%     981MB / 102MB     0B / 2.83MB   18
3336840a534b   freqtrade_gateio_usdt    3.47%     826.4MiB / 23.43GiB   3.45%     653MB / 135MB     0B / 3.4MB    17
fcde9a44af8c   freqtrade_kucoin_usdt    0.59%     806.5MiB / 23.43GiB   3.36%     1.09GB / 34.6MB   0B / 2.99MB   15

**Comment by xmatthias** [comment] 2024-02-27 05:46
@rmtucker best try the latest develop, too. 

While i don't really know what could cause this - dependencies update all the time - and based on the above feedback - this seems to fix it.

**Closed as completed by xmatthias** 2024-02-27 05:46 UTC
Labels: Question, Docker

**Comment by rmtucker** [comment] 2024-02-27 12:16
I know it does not help but I did prove that if I turn off the kucoin API server then do a docker compose up -d,
Then turn the API server back on in the config,and do a reload_config.
The bot then runs without restarts!!.
Until i do a docker compose restart.

**Comment by perkmeister** [comment] 2024-02-27 20:05
Can you explain what you mean by kucoin API server? Are you talking about freqtrade's API server with the kucoin bot, or do you mean the kucoin proxy server?

**Comment by rmtucker** [comment] 2024-02-27 21:51
As in this one

    "api_server": {
        "enabled": true,
        "listen_ip_address": "0.0.0.0",
        "listen_port": 8080,
        "verbosity": "error",
        "enable_openapi": false,
