### ISSUE TITLE
fiat convert does not support USDT

### ISSUE THREAD

**Issue by StephaneMangin** [freqtrade/freqtrade#6519] opened 2022-03-11 08:17 UTC
## Describe your environment

  * Operating system: Debian
  * Python Version: freqtrade standard
  * CCXT version: freqtrade standard
  * Freqtrade Version: latest at the date of thie issue
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*EUR could not be converted from USDT normaly*

### Steps to reproduce:

Unknown
  
### Observed Results:

  * What happened?
no more conversion to Fiat
  * What did you expect to happen?
obviously a conversion

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-03-11 08:15:50 - freqtrade.rpc.fiat_convert - WARNING - Found multiple mappings in goingekko for usdt.
2022-03-11 08:15:50 - freqtrade.rpc.fiat_convert - WARNING - unsupported crypto-symbol usdt - returning 0.0

  ```

**Comment by xmatthias** [comment] 2022-03-11 08:20
Next time, please fill out the issue template properly. `latest at the date of thie issue` is NOT a valid version - and does not tell us anything if you're using develop, stable - and will force us to go back and look at "which version wasthe latest at this point in time" .


This is a duplicate of #6518 - and is already fixed in develop.

**Closed as completed by xmatthias** 2022-03-11 08:20 UTC
Labels: Duplicate
