### ISSUE TITLE
Torch saving error in customized freqai model

### ISSUE THREAD

**Issue by b2r66sun** [freqtrade/freqtrade#10855] opened 2024-10-29 13:20 UTC
## Describe your environment

  * Operating system: __Ubuntu24.04__
  * Python Version: ___3.12__ (`python -V`)
  * CCXT version: ___4.4.6__ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2024.10-dev-52ae7c361__ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. Place the customized torch model in ```user_data/freqaimodels``` as in the docs
 ```python
from typing import Any

import torch

from freqtrade.freqai.base_models.BasePyTorchClassifier import BasePyTorchClassifier
from freqtrade.freqai.data_kitchen import FreqaiDataKitchen
from freqtrade.freqai.torch.PyTorchDataConvertor import (
    DefaultPyTorchDataConvertor,
    PyTorchDataConvertor,
)
from freqtrade.freqai.torch.PyTorchModelTrainer import PyTorchModelTrainer

import logging

import torch
from torch import nn


logger = logging.getLogger(__name__)


class MLPModel(nn.Module):

    def __init__(self, input_dim: int, output_dim: int, **kwargs):
        super().__init__()
        hidden_dim: int = kwargs.get("hidden_dim", 256)
        dropout_percent: int = kwargs.get("dropout_percent", 0.2)
        n_layer: int = kwargs.get("n_layer", 1)
        self.input_layer = nn.Linear(input_dim, hidden_dim)
        self.blocks = nn.Sequential(*[Block(hidden_dim, dropout_percent) for _ in range(n_layer)])
        self.output_layer = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=dropout_percent)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x: torch.Tensor = tensors[0]
        x = self.relu(self.input_layer(x))
        x = self.dropout(x)
        x = self.blocks(x)
        x = self.output_layer(x)
        return x

class Block(nn.Module):
    """
    A building block for a multi-layer perceptron (MLP).

    :param hidden_dim: The number of hidden units in the feedforward network.
    :param dropout_percent: The dropout rate for regularization.

    :returns: torch.Tensor. with shape (batch_size, hidden_dim)
    """

    def __init__(self, hidden_dim: int, dropout_percent: int):
        super().__init__()
        self.ff = FeedForward(hidden_dim)
        self.dropout = nn.Dropout(p=dropout_percent)
        self.ln = nn.LayerNorm(hidden_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.ff(self.ln(x))
        x = self.dropout(x)
        return x

class FeedForward(nn.Module):
    """
    A simple fully-connected feedforward neural network block.

    :param hidden_dim: The number of hidden units in the block.
    :return: torch.Tensor. with shape (batch_size, hidden_dim)
    """

    def __init__(self, hidden_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)
    
class MyClassifier(BasePyTorchClassifier):
    """
    This class implements the fit method of IFreqaiModel.
    in the fit method we initialize the model and trainer objects.
    the only requirement from the model is to be aligned to PyTorchClassifier
    predict method that expects the model to predict a tensor of type long.

    parameters are passed via `model_training_parameters` under the freqai
    section in the config file. e.g:
    {
        ...
        "freqai": {
            ...
            "model_training_parameters" : {
                "learning_rate": 3e-4,
                "trainer_kwargs": {
                    "n_steps": 5000,
                    "batch_size": 64,
                    "n_epochs": null,
                },
                "model_kwargs": {
                    "hidden_dim": 512,
                    "dropout_percent": 0.2,
                    "n_layer": 1,
                },
            }
        }
    }
    """

    @property
    def data_convertor(self) -> PyTorchDataConvertor:
        return DefaultPyTorchDataConvertor(
            target_tensor_type=torch.long, squeeze_target_tensor=True
        )

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        config = self.freqai_info.get("model_training_parameters", {})
        self.learning_rate: float = config.get("learning_rate", 3e-4)
        self.model_kwargs: dict[str, Any] = config.get("model_kwargs", {})
        self.trainer_kwargs: dict[str, Any] = config.get("trainer_kwargs", {})

    def fit(self, data_dictionary: dict, dk: FreqaiDataKitchen, **kwargs) -> Any:
        """
        User sets up the training and test data to fit their desired model here
        :param data_dictionary: the dictionary holding all data for train, test,
            labels, weights
        :param dk: The datakitchen object for the current coin/model
        :raises ValueError: If self.class_names is not defined in the parent class.
        """

        class_names = self.get_class_names()
        self.convert_label_column_to_int(data_dictionary, dk, class_names)
        n_features = data_dictionary["train_features"].shape[-1]
        model = MLPModel(
            input_dim=n_features, output_dim=len(class_names), **self.model_kwargs
        )
        model.to(self.device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=self.learning_rate)
        criterion = torch.nn.CrossEntropyLoss()
        # check if continual_learning is activated, and retrieve the model to continue training
        trainer = self.get_init_model(dk.pair)
        if trainer is None:
            trainer = PyTorchModelTrainer(
                model=model,
                optimizer=optimizer,
                criterion=criterion,
                model_meta_data={"class_names": class_names},
                device=self.device,
                data_convertor=self.data_convertor,
                tb_logger=self.tb_logger,
                **self.trainer_kwargs,
            )
        trainer.fit(data_dictionary, self.splits)
        return trainer

```
  2. Run the backtest
  ```bash
freqtrade backtesting --config user_data/config_freqai.json \
                      --strategy FreqaiStrategy \
                      --freqaimodel MyClassifier \
                      --timerange 20240601-20240801 \
                      --timeframe 15m \
                      --timeframe-detail 1m \
                      --breakdown month 
```
### Observed Results:

  * What happened?
  ```bash
_pickle.PicklingError: Can't pickle <class 'MyClassifier.MLPModel'>: import of module 'MyClassifier' failed
```
  * What did you expect to happen?
  This bug raises in the ```save()``` method in trainer. Inside the method, it called 
```python
torch.save(
            {
                "model_state_dict": self.model.state_dict(),
                "optimizer_state_dict": self.optimizer.state_dict(),
                "model_meta_data": self.model_meta_data,
                "pytrainer": self,
            },
            path,
        )
```
and it may be bug in saving the ```self```. When the model or trainer class is in the ```user_data/freqaimodels``` together with the user defined ```IFreqAIModel```, Seems that it cannot find the correct path.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
File "/home/user/workspace/Finance/freqtrade/freqtrade/freqai/freqai_interface.py", line 383, in start_backtesting
    self.dd.save_data(self.model, pair, dk)
  File "/home/user/workspace/Finance/freqtrade/freqtrade/freqai/data_drawer.py", line 521, in save_data
    model.save(save_path / f"{dk.model_filename}_model.zip")
  File "/home/user/workspace/Finance/freqtrade/freqtrade/freqai/torch/PyTorchModelTrainer.py", line 170, in save
    torch.save(
  File "/home/user/anaconda3/envs/freqtrade/lib/python3.12/site-packages/torch/serialization.py", line 850, in save
    _save(
  File "/home/user/anaconda3/envs/freqtrade/lib/python3.12/site-packages/torch/serialization.py", line 1088, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <class 'MyClassifier.MLPModel'>: import of module 'MyClassifier' failed
  ```

**Comment by xmatthias** [comment] 2024-11-01 14:52
> When the model or trainer class is in the user_data/freqaimodels together with the user defined IFreqAIModel, Seems that it cannot find the correct path.

well that's correct and kindof expected for all things (models, strategies) that are loaded dynamically the way we do.
It's lucky circumstance that it (may) work for internal models at all.

There's ways around this (specifically for pickle) - but these are not applied here.

That said - i'm not entirely certain why self is even saved. 
If we look at the loading code - then "pytrainer" is not used - so while we save it (triggering this problem) - we're not using it when loading again.


https://github.com/freqtrade/freqtrade/blob/67f26fa1ac7a759f301a483ba2b17a892ad2318c/freqtrade/freqai/torch/PyTorchModelTrainer.py#L180-L194

maybe @robcaulk can shed some light into this ? maybe it's just as simple as not saving the "self" reference (if you google for this particular error - it's quite a common occurance with torch if the model itself is (attempted) to be saved).

**Comment by robcaulk** [comment] 2024-11-01 15:40
This is a bug with continual_learning *in backtesting* (works fine in dry-run), it is already known: https://github.com/freqtrade/freqtrade/issues/10034.

Please deactivate `continual_learning` in your config. In general, we do not recommend using this feature, the documentation indicates the experimental nature of it, so I would say that means we do not guarantee support across the board for all 18 models.

Now, if someone wants to try to fix it, be my guest (I don't see the need for continual learning as a high priority, as it is destructive to the model and does not produce good results, as indicated explicitly in the documentation). But we cannot simply remove self as suggested by @xmatthias :

https://github.com/freqtrade/freqtrade/blob/67f26fa1ac7a759f301a483ba2b17a892ad2318c/freqtrade/freqai/data_drawer.py#L616

I am perfectly happy for someone else to come in and change it and tell me I did it poorly, but if you do, please ensure that it works. Personally, I worked on multiple torch projects outside of this one that required saving models like this - I remember trying to find an alternative avenue that didn't involve saving self, and did not find one. That means I wont be revisiting it unless it is broken.

The only suggestion I can make on dev side is to force deactivate `continual_learning` for anyone using Torch until the bug is solved. But I sense this won't bring much joy to Matthias. The alternative is to to deprecate `continual_learning` entirely, as we have observed precisely what has been posted in the documentation for multiple years - it is highly experimental and not good for random people to get involved with.

**Comment by xmatthias** [comment] 2024-11-01 16:26
> That means I wont be revisiting it unless it is broken.

well it **is** broken ... otherwise it wouldn't crash 😆 - though i don't understand the correlation with continual_learning - as i think this line will always trigger the problem - unless we're not saving if continual_learning is on?

> But I sense this won't bring much joy to Matthias.

I'd rather have things fail with a proper error if we know it's incompatible than leaving it to crash down the road if we don't intend to fix a known bug.

---

At any rate - i'll be closing this as duplicate of #10034 - good catch in spotting that it's the same problem.

**Closed as completed by xmatthias** 2024-11-01 16:26 UTC
Labels: Duplicate, freqAI
