### ISSUE TITLE
Freqtrade does not "see" liquidation on exchange (gateio futures)

### ISSUE THREAD

**Issue by medenlin** [freqtrade/freqtrade#7107] opened 2022-07-19 19:54 UTC
## Describe your environment

  * Operating system: Docker
  * Freqtrade Version: docker-99d5fbc9
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When liquidation on exchange occurs, Freqtrade does not see it and continues to serve non-existent trade.

### Steps to reproduce:

  1. Run Freqtrade in Live mode on gateio futures
  2. Wait for trade liquidation on exchange
  
### Observed Results:

  * What happened?
  Trying to continue serving non-existent trade
  * What did you expect to happen?
  Close trade with corresponding losses and reason

### Relevant code exceptions or logs

  ```
2022-07-19 18:33:09,155 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'
2022-07-19 18:34:09,162 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'

// Around this time the ACH/USDT:USDT Trade was liquidated on exchange

2022-07-19 18:35:22,601 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'
2022-07-19 18:36:24,164 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'
2022-07-19 18:37:24,171 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'
2022-07-19 18:38:24,179 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'
2022-07-19 18:39:24,192 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='docker-99d5fbc9', state='RUNNING'
2022-07-19 18:39:45,956 - freqtrade.freqtradebot - INFO - Exit for ACH/USDT:USDT detected. Reason: stop_loss
2022-07-19 18:39:46,960 - freqtrade.wallets - INFO - Wallets synced.
2022-07-19 18:39:47,278 - freqtrade.freqtradebot - WARNING - Unable to exit trade ACH/USDT:USDT: Could not place buy order due to ExchangeError. Message: gateio {"label":"REDUCE_EXCEEDED","detail":"empty position"}
2022-07-19 18:39:51,199 - freqtrade.freqtradebot - INFO - Exit for ACH/USDT:USDT detected. Reason: stop_loss
2022-07-19 18:39:52,201 - freqtrade.wallets - INFO - Wallets synced.
2022-07-19 18:39:52,495 - freqtrade.freqtradebot - WARNING - Unable to exit trade ACH/USDT:USDT: Could not place buy order due to ExchangeError. Message: gateio {"label":"REDUCE_EXCEEDED","detail":"empty position"}
2022-07-19 18:40:01,403 - freqtrade.freqtradebot - INFO - Exit for ACH/USDT:USDT detected. Reason: stop_loss
2022-07-19 18:40:02,427 - freqtrade.wallets - INFO - Wallets synced.
2022-07-19 18:40:02,737 - freqtrade.freqtradebot - WARNING - Unable to exit trade ACH/USDT:USDT: Could not place buy order due to ExchangeError. Message: gateio {"label":"REDUCE_EXCEEDED","detail":"empty position"}
2022-07-19 18:40:25,828 - freqtrade.freqtradebot - INFO - Exit for ACH/USDT:USDT detected. Reason: stop_loss
2022-07-19 18:40:26,831 - freqtrade.wallets - INFO - Wallets synced.
[...]
// repeated attempts to exit by stop loss
  ```

**Comment by xmatthias** [comment] 2022-07-20 04:47
We're aware of this - but it should be protected by having the stoploss above the liquidation price at all times (there's an offset of ~5% iirc) - so the trade should have stopped out before the liquidation happens.

So the interesting part is not around here in the logs necessarily - but before the actual liquidation happened.
Was the bot down for some time before the liquidation? 

Also - what's the prices around this? (Liquidation price, stoploss price, ...)
we'll also need the output of `freqtrade show-trades --db-url x --trade-ids <tradeid> --print-json` to further investigate this.

**Comment by medenlin** [comment] 2022-07-20 09:59
This is a rather rare case. The price immediately jumped over the stop loss and reached liquidation. But I would like the Freqtrade to process such moments.
freqtrade show-trades output about this trade:
_Note: After liquidation, Freqtrade open adjustment order 183051649443 (under the same Trade ID), then close it by stop-loss 183051752074_
_Note2: In my strategy adjustment orders allowed only an hour after the previous order_
```
[
    {
        "trade_id": 1616,
        "pair": "ACH/USDT:USDT",
        "base_currency": "ACH",
        "quote_currency": "USDT",
        "is_open": false,
        "exchange": "gateio",
        "amount": 4290.0,
        "amount_requested": 2113.29848276,
        "stake_amount": 18.748928,
        "strategy": "MELFUTURESAUTO",
        "buy_tag": "S1_Short",
        "enter_tag": "S1_Short",
        "timeframe": 5,
        "fee_open": 0.000105,
        "fee_open_cost": 0.007382390400000001,
        "fee_open_currency": "USDT",
        "fee_close": 5.2685e-05,
        "fee_close_cost": 0.0045345465,
        "fee_close_currency": "USDT",
        "open_date": "2022-07-19 18:25:20",
        "open_timestamp": 1658255120788,
        "open_rate": 0.01638892307692308,
        "open_rate_requested": 0.01792,
        "open_trade_value": 70.30109761,
        "close_date": "2022-07-19 19:25:58",
        "close_timestamp": 1658258758429,
        "close_rate": 0.01814,
        "close_rate_requested": 0.01814,
        "close_profit": -0.40132387,
        "close_profit_pct": -40.13,
        "close_profit_abs": -7.52360237,
        "trade_duration_s": 3637,
        "trade_duration": 60,
        "profit_ratio": -0.40132387,
        "profit_pct": -40.13,
        "profit_abs": -7.52360237,
        "sell_reason": "stop_loss",
        "exit_reason": "stop_loss",
        "exit_order_status": "closed",
        "stop_loss_abs": 0.0181255,
        "stop_loss_ratio": -0.95,
        "stop_loss_pct": -95.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2022-07-19 18:25:34",
        "stoploss_last_update_timestamp": 1658255134641,
        "initial_stop_loss_abs": 0.0181255,
        "initial_stop_loss_ratio": -0.95,
        "initial_stop_loss_pct": -95.0,
        "min_rate": 0.01481,
        "max_rate": 0.01999,
        "leverage": 3.75,
        "interest_rate": 0.0,
        "liquidation_price": 0.021852446153846156,
        "is_short": true,
        "trading_mode": "futures",
        "funding_fees": 0.0,
        "open_order_id": null,
        "orders": [
            {
                "amount": 2112.0,
                "safe_price": 0.01481,
                "ft_order_side": "sell",
                "order_filled_timestamp": 1658255133626,
                "ft_is_entry": true,
                "pair": "ACH/USDT:USDT",
                "order_id": "183036177318",
                "status": "closed",
                "average": 0.01481,
                "cost": 31.27872,
                "filled": 2112.0,
                "is_open": false,
                "order_date": "2022-07-19 18:25:21",
                "order_timestamp": 1658255121590,
                "order_filled_date": "2022-07-19 18:25:33",
                "order_type": "limit",
                "price": 0.01481,
                "remaining": 0.0
            },
            {
                "amount": 2178.0,
                "safe_price": 0.01792,
                "ft_order_side": "sell",
                "order_filled_timestamp": 1658258742868,
                "ft_is_entry": true,
                "pair": "ACH/USDT:USDT",
                "order_id": "183051649443",
                "status": "closed",
                "average": 0.01792,
                "cost": 39.02976,
                "filled": 2178.0,
                "is_open": false,
                "order_date": "2022-07-19 19:25:36",
                "order_timestamp": 1658258736261,
                "order_filled_date": "2022-07-19 19:25:42",
                "order_type": "limit",
                "price": 0.01792,
                "remaining": 0.0
            },
            {
                "amount": 2178.0,
                "safe_price": 0.01814,
                "ft_order_side": "buy",
                "order_filled_timestamp": 1658258758082,
                "ft_is_entry": false,
                "pair": "ACH/USDT:USDT",
                "order_id": "183051752074",
                "status": "closed",
                "average": 0.01814,
                "cost": 39.50892,
                "filled": 2178.0,
                "is_open": false,
                "order_date": "2022-07-19 19:25:56",
                "order_timestamp": 1658258756013,
                "order_filled_date": "2022-07-19 19:25:58",
                "order_type": "limit",
                "price": 0.01814,
                "remaining": 0.0
            }
        ]
    }
]

```

**Comment by medenlin** [comment] 2022-07-20 10:31
UPD: Liquidation price was 0.0183

**Comment by xmatthias** [comment] 2022-07-21 17:52
This is a bit more complex than it looks. CCXT doesn't seem to unify liquidations - and there's no real easy way to get that through orders or positions (at least not as far as i could find).

I'll think of something - but don't expect a very quick solution to this.

**Comment by medenlin** [comment] 2022-07-23 11:35
Yes, probably this can only be done directly through the exchange API, without using CCXT. Or ask the CCXT developers to do it. Although, on the other hand, there are not so many exchangers that support futures trade...

**Comment by medenlin** [comment] 2022-08-19 00:30
Wow! I began to detect `liquidation` as `exit_reason` in the `backtest` mode 👍 👍 👍 on latest develop builds
How it works?

**Comment by xmatthias** [comment] 2022-08-19 04:22
that's a change that's not really related to this issue, sorry.

It's because i split liquidation and stoploss handling - as liquidations can move up and down when scaling out - but stoplosses can't.
it's therefore wrong to force a stoploss up through liquidation price - if it can't go lower again.

**Comment by xmatthias** [comment] 2023-04-27 05:00
@medenlin sorry for the late action here

#8560 should hopefully fix this - though under the assumption that liquidations are showing in the `fetch_trades`  or `fetch_closed_trades` endpoint for that pair.

we should be able to determine this with the following query after a liquidation - but so far, the regular stop logic has always prevented me from running into an actual liquidation.

``` python
import ccxt
exchange = ccxt.gate({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>', 
    'options': {'defaultType': 'swap'} 
    })
since_ms = 1658255120788   # your trade open timestamp
res = exchange.fetch_orders(pair, since=since_ms)
# alternatively
# res = exchange.fetch_closed_orders(pair)
print(res)
```

I have this data for bybit, so i know it will work there - but other exchanges are not confirmed yet.
Hints in the Api documentation suggest that gate works similarily, though the documentation is not 100% clear on that

**Comment by medenlin** [comment] 2023-04-27 11:07
Ok, thank you! I upgrade my freqtrade to latest dev build and try to test it on gate.io futures.

**Comment by xmatthias** [comment] 2023-04-27 11:20
Well it's not merged yet- so the latest dev will not really help all that much 😆

**Comment by medenlin** [comment] 2023-04-27 11:23
Okay, I'll wait for the merge and docker build 😀

**Closed as completed** 2023-05-13 14:35 UTC
Labels: Enhancement, Non-spot
