### ISSUE TITLE
No trades in dryrun - hundreds in backtest

### ISSUE THREAD

**Issue by mvbrouw** [freqtrade/freqtrade#1198] opened 2018-09-08 10:55 UTC
This issue relates to issue #1190

I have a script that turns 15m candles into 1h and 4h candles on all BTC pairs using the method described in strategy MultiRSI.
It has been dry-running for a week with no trades while the backtester shows >100 trades a day in the same week. 

The script uses the same indicators on all timeframes and checks to see which direction those indicators are going (up or down) using:
`dataframe['indicator'] > dataframe['indicator'].shift(1)`
For the resampled candles I use: 
`(dataframe['resample_{}_indicator'.format(self.get_ticker_indicator()*4)] > dataframe['resample_{}_indicator'.format(self.get_ticker_indicator()*4)].shift(1)) `

The idea is to generate a buy signal when all indicators are headed in the same direction indicating a trend. 
It does this for mulitple equations and candles in the populate_buy_trend and populate_sell_trend functions.

For some reason, the backtester sees hundreds of buy and sell signals and the dry run version sees none. 

I have done multiple things to figure this out:
	- Print the dataframe to a csv and check the raw data to see if all desired indicator values are present - They are.
	- I have tried shifting the resampled candles with .shift(4) and .shift(16) as those are the numbers of rows they span in the printed csv file - Still no trades
	- Switch to ccxt-async - It significantly improved looptime but still no trades
	- Experiment with different ticker_interval values and candle sizes - All encounter the same issue
        - Transform a range of negative indicator values to a range of positive indicator values - Still no trades

The only thing I can think of is that the backtester handles the logic or dataframe in a different manner than the dry run, but my skills are far too limited to figure this out. 

I would be most gratefull for any input that helps me solve this issue as I really want this strategie to work out.

**Comment by mvbrouw** [comment] 2018-09-08 11:48
Thank you for the reply.
I am sure I have not been backpainting, but it would be a nice feature to add to the bot :laughing: 

> To analyze if buy-signals are generated correctly in dry-mode, you need to look at the last (few?) rows of the dataframe (after / within populate_buy_trend) - as only this buy-signal "really" matters, the others earlier won't be acted on.

Does this indicate there is a way to export the dataframe from a dryrun other than my makeshift *.csv way?

I will examine the `scripts/plot_dataframe.py` and figure out how to use this.

**Comment by xmatthias** [comment] 2018-09-09 06:37
not really, no - but you mentioned printing the dataframe already, so adding a `print(df.tail(2)` ... should do the trick i guess ...

**Comment by Axel-CH** [comment] 2018-09-10 15:49
Hi @mvbrouw are you forced to use resempling? Did you tried to simply multiply the input period in you indicators? Exemple:  In my point of view **SMA(10) 1min TF is equivalent to SMA(2) 5min TF**

**Comment by mvbrouw** [comment] 2018-09-10 23:58
Hi Axel,

I think I am forced to use resampling. I am using oscilators like RSI and I use the ADX. 
I am not comparing them to eachother, but rather to themselfes in their previous candle value. 
To show you what it might look like I've added this:
#### Example Strategy
      

>     # Optimal ticker interval for the strategy
>     ticker_interval = '5m'
> 
>     def get_ticker_indicator(self):
>         return int(self.ticker_interval[:-1])
> 
>     def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>         from technical.util import resample_to_interval
>         from technical.util import resampled_merge
> 
>         # Resample our dataframes
>         dataframe_hour = resample_to_interval(dataframe, self.get_ticker_indicator() * 12)
>         dataframe_4hour = resample_to_interval(dataframe, self.get_ticker_indicator() * 48)
> 
>         # ADX
>         dataframe['plus_dm'] = ta.PLUS_DM(dataframe, timeperiod=8)
>         dataframe_hour['plus_dm'] = ta.PLUS_DM(dataframe_hour, timeperiod=8)
>         dataframe_4hour['plus_dm'] = ta.PLUS_DM(dataframe_4hour, timeperiod=8)
> 
>         # RSI
>         dataframe['rsi'] = ta.RSI(dataframe, timeperiod=7)
>         dataframe_hour['rsi'] = ta.RSI(dataframe_hour, timeperiod=7)
>         dataframe_4hour['rsi'] = ta.RSI(dataframe_4hour, timeperiod=7)
> 
>         # Merge dataframe back together
>         dataframe = resampled_merge(dataframe, dataframe_hour)
>         dataframe = resampled_merge(dataframe, dataframe_4hour)
> 
>         # Fill empty cells forward
>         dataframe.fillna(method='ffill', inplace=True)
> 
>         return dataframe
> 
>     def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
>         """
>         The refactored cells are shifted by the number of rows they take up in the dataframe, so the signal stays
>         true for the entire duration of that candles timeframe. I also just filled in the refactored column names,
>         to keep the code universal I'd use: dataframe{'resample_{}_plus_dm'.format(self.get_ticker_indicator() * 12)]
>         but this looks more clean.
>         """
>         dataframe.loc[
>             (
>                 #If ADX_plus_DM and RSI all go in the same direction (up/down) in 3 different timeframes
>                 (dataframe['plus_dm'] > dataframe['plus_di'].shift(1)) &
>                 (dataframe['resample_60_plus_dm'] > dataframe['resample_60_plus_dm'].shift(12)) &
>                 (dataframe['resample_240_plus_dm'] > dataframe['resample_240_plus_dm'].shift(48)) &
>                 (dataframe['rsi'] > dataframe['rsi'].shift(1)) &
>                 (dataframe['resample_60_rsi'] > dataframe['resample_60_rsi'].shift(12)) &
>                 (dataframe['resample_240_rsi'] >= dataframe['resample_240_rsi'].shift(48))
>             ),
>             'buy'] = 1
> 
>         return dataframe
> 
>     def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
> 
>         dataframe.loc[
>             (
>                 (dataframe['resample_60_plus_dm'] < dataframe['resample_60_plus_dm'].shift(12)) &
>                 (dataframe['resample_60_rsi'] < dataframe['resample_60_rsi'].shift(12))
>             ),
>             'sell'] = 1
>         return dataframe

So what this code basically does is take 5m candles and create 1hour and 4hour candles out of them. Then it calculates the indicators over those new candles, mashes the dataframes together and I've got all my data in the same dataframe. Backtesting was doing just fine using these signal conditions, but no trades in dry-run.

Because of what @xmatthias said I've delved into the debug-mode a little deeper and I noticed that my sell signals came through just fine. My buy orders were the problem. 
I tried to solve the .shift() issue by shifting before the populate_buy_trend function. This would put all shifted values into the final row. And it looked like this:

>         dataframe['shifted_plus_dm'] = dataframe['plus_dm'].shift(1)
>         dataframe['shifted_rsi'] = dataframe['rsi'].shift(1)
>         dataframe['shifted_1h_plus_dm'] = dataframe['resample_60_plus_dm'].shift(12)
>         dataframe['shifted_1h_rsi'] = dataframe['resample_60_rsi'].shift(12)
>         dataframe['shifted_4h_plus_dm'] = dataframe['resample_240_plus_dm'].shift(48)
>         dataframe['shifted_4h_rsi'] = dataframe['resample_240_rsi'].shift(48)
> 
>         return dataframe
> 
>     def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
> 
>         dataframe.loc[
>             (
>                 #If ADX, ADX_plus_DM and RSI all go in the same direction (up/down) in 3 different timeframes
>                 (dataframe['plus_dm'] > dataframe['shifted_plus_dm']) &
>                 (dataframe['resample_60_plus_dm'] > dataframe['shifted_1h_plus_dm']) &
>                 (dataframe['resample_240_plus_dm'] > dataframe['shifted_4h_plus_dm']) &
>                 (dataframe['rsi'] > dataframe['shifted_rsi']) &
>                 (dataframe['resample_60_rsi'] > dataframe['shifted_1h_rsi']) &
>                 (dataframe['resample_240_rsi'] > dataframe['shifted_4h_rsi'])
>             ),
>             'buy'] = 1
> 
>         return dataframe

Unfortunatly, this resulted in no trades, but and error. __It suddenly told me 'dataframe['plus_dm'] ' did not exist.__  After rechecking why the shift in the MultiRSI strategy DID work I noticed that multiRSI only shifts a resampled cell.  So I edited out all my indicators that needed to shift on the base ticker interval and suddenly, buys came through. Meaning I only shifted resampled columns.
To further test this I used this method on a similar strategy that was having the same issue. I recreated  5 minute candles and 1 hour candles by resampling 1 minute candles, then shifting the resampled indicator values opposed to the indicator value based on candles in the base interval time. This other strategy is now buying and selling like it should.

Unfortunatly this is not possible for above mentioned strategy as the amount of rows it would take to populate all indicator values exceed the 500 row limit the dataframe currently exists of. Changing the _LIMIT=500 to _LIMIT=1000 in './exhange/__init__.py' didn't do anything to add more rows to this database. 

As this method is a severely limited solution due to the scale of the resampling, and also that the 'process_only_new_candles": true' setting in the config is now rendered useless, I would very much like to figure out how to utilize the shift() or a similar function so I can compare base-ticker-value indicators to themselves in a past iteration. 

I sincerely hope this made my issue a little more clear and that  you will be able to help with ths.

**Comment by xmatthias** [comment] 2018-09-11 05:04
`_LIMIT=500` is not for "regular" use at the moment, but for ticker downloading. It will (currently) have 0 effect on dry-run or live-run.

you could get 1000 candles by extending line 456 - but i'm not sure it works against all exchanges (i've seen some exchanges return less than 1000 candles on some timeframes).
```python
data = await self._api_async.fetch_ohlcv(pair, timeframe=tick_interval,
                                                         since=since_ms, limit=1000)
```

your strategy has another, problem though - 1000 candles in 1m minutes are ~16 hours (1000 / 60). (~83 hours in 5m candles).

Your shifting a resampled 4h candle by 48 - which requires data for over a week - which will not be available with 1000 candles unless you use a longer time-period - so this chunk of code is not going to work on 1m candles (neither on 5m candles, where 1000 candles give you about 3 days).

So even using 1000 candles will not work for the above strategy... sorry to say that.

**Comment by mvbrouw** [comment] 2018-09-11 08:13
@xmatthias Thank you for the timeframe indication. I will certainly experiment with this.
I'm sorry but I would have to disagree with you about the calculation. It would be correct if I was actually shifting inside the resampled 4hr dataframe, instead I am shifting in the original 5m dataframe. After merging, only closed candle values are added in the original dataframe and the 'ffill' copies them into every new 5m row untill a new 4hour candle can be formed using the resample tool. 
At least, that is what it shows me in the printed dataframe as 1hr values span for 12 rows and 4hr values span for 48 rows, as 4 hours / 5min = 48 rows. 
I only care about the last 12hrs or so. 
I could just assign a column in the original database containing the shifted 4hr value, but that would have the same effect as merging combined with the 'ffill'.

Having said that, I agree that it still are not enough candles as I need at least 7 4hr candles to populate my indicators and be able to shift. In a 1 minute dataframe this would resemble 1680 rows. 

This is why I truly want to find a way, perhaps other than '.shift()' that I don't know of. 
It still strikes me as odd that trying to shift the base-ticker-interval would result in a faulty strategy, but only in dry/live trading. Maybe this is first-row related, as it has nothing to shift to?

**Comment by xmatthias** [comment] 2018-09-11 11:40
you're right - i didn't think about the 'ffill' - it came to me while i was driving to work that i'm actually incorrect, sorry for that.

`.shift()` is not a problem per se as long as it's shifting in the right direction (uses historic data). 
Your code seems to be doing just that - so I'm not sure what is causing your issue.

It also shouldn't be a problem for missing data (unless you shift more than you have) - the evaluated tick is the last row in the dataframe.

Are you sure these indicators would lead to a buy-signal for your pairs in the dry-run / tested interval? It seems to be looking for a strong positive trend - if i read this correctly - so even if you see lots of trades over a month - maybe there are days in between (also during backtesting) which don't have any trades?

**Comment by mvbrouw** [comment] 2018-09-11 11:58
Yes it does look for a strong positive trend. It's a go with the flow kind of idea. 
You're right, somedays there are no trades, like when BTC is on the rise and all btc-traded pairs go in the red. The dry-run was running on a digital ocean server for a week, after no trade signals I decided to backtest that same week an it found and average of 100 trades a day. I like having a day without trades better than having a day with stop losses :smile:

The strategy I provided is not my exact strategy but contains all the elements. I backtested the example strategy yesterday and even though it is a lot less frequent than my original, it does also seem to provide trade signals in backtest. 

The error I got when I pre-shifted the indicator values did seem to imply that the 5m indicator had nothing to shift to, as it told me there was no such thing as the value.  I will recreate the error once I get home tonight and post it here.

**Comment by jblestang** [comment] 2018-09-12 04:59
This is more likely a problem in how you handle resampling. Add a new column « merge_date », then you fill this with the open date of the expected resampled candle. Then merge the resampled in the unaltered dataframe using the « merge_date » column and the « date » column of the resampled dataframe. So on a each row you will have both the 5m candle and the previously closed resampled candle.

**Comment by mvbrouw** [comment] 2018-09-12 07:17
@jblestang I suppose there would be multiple solutions for this. I am not quite sure what you mean though, could you show me an example on how you would do this?

**Comment by mishaker** [comment] 2018-09-12 09:09
@mvbrouw great analysis ! but I agree with @jblestang that it is more a problem of the strategy than backtesting. we should find a way to avoid constructing partial candles when resampling. I am not sure how as I didn't read `resample_to_interval()` code but I think it is worth looking into it. 
Also I am sure @berlinguyinca opinion on this would be really helpful. 
If we are sure that the problem is coming from resampling I think we should open an issue specifically on that.

**Comment by berlinguyinca** [comment] 2018-09-12 17:42
Good to know and thanks for finding this. could you submit a pr please?

**Comment by mvbrouw** [comment] 2018-09-12 17:48
@xmatthias @berlinguyinca 
Ok so I may be out of my league here, but if the date label right is used to avoid using a incomplete candle, why is it exactly the same as the date label to the left? Shouldn't it be a different date/time?


date | open | high | low | close | volume | date
-- | -- | -- | -- | -- | -- | --
2018-09-10 00:00:00+00:00 | 2.29e-06 | 2.3e-06 | 2.27e-06 | 2.28e-06 | 4700197.0 | 2018-09-10 00:00:00+00:00
2018-09-10 04:00:00+00:00 | 2.28e-06 | 2.3e-06 | 2.24e-06 | 2.29e-06 | 12047922.0 | 2018-09-10 04:00:00+00:00
2018-09-10 08:00:00+00:00 | 2.29e-06 | 2.44e-06 | 2.23e-06 | 2.4e-06 | 17182183.0 | 2018-09-10 08:00:00+00:00
2018-09-10 12:00:00+00:00 | 2.4e-06 | 2.43e-06 | 2.35e-06 | 2.37e-06 | 7939975.0 | 2018-09-10 12:00:00+00:00
2018-09-10 16:00:00+00:00 | 2.37e-06 | 2.41e-06 | 2.33e-06 | 2.38e-06 | 11340717.0 | 2018-09-10 16:00:00+00:00
2018-09-10 20:00:00+00:00 | 2.38e-06 | 2.42e-06 | 2.33e-06 | 2.41e-06 | 10850925.0 | 2018-09-10 20:00:00+00:00
2018-09-11 00:00:00+00:00 | 2.41e-06 | 2.5e-06 | 2.4e-06 | 2.43e-06 | 11765252.0 | 2018-09-11 00:00:00+00:00
2018-09-11 04:00:00+00:00 | 2.44e-06 | 2.63e-06 | 2.42e-06 | 2.54e-06 | 12038004.0 | 2018-09-11 04:00:00+00:00
2018-09-11 08:00:00+00:00 | 2.54e-06 | 2.55e-06 | 2.32e-06 | 2.34e-06 | 11161422.0 | 2018-09-11 08:00:00+00:00
2018-09-11 12:00:00+00:00 | 2.35e-06 | 2.36e-06 | 2.23e-06 | 2.25e-06 | 10149318.0 | 2018-09-11 12:00:00+00:00
2018-09-11 16:00:00+00:00 | 2.25e-06 | 2.28e-06 | 2.14e-06 | 2.2e-06 | 10967507.0 | 2018-09-11 16:00:00+00:00
2018-09-11 20:00:00+00:00 | 2.2e-06 | 2.25e-06 | 2.2e-06 | 2.24e-06 | 510670.0 | 2018-09-11 20:00:00+00:00

**Comment by xmatthias** [comment] 2018-09-12 18:18
i'm not sure about what your code does / how it works precisely... 

Using the following sample data (5min ticker data i had laying around - ending on 2018-06-18 20:25:00): (sorry for screenshots - i'm to lazy to format a github-table right now)
![2018-09-12-201137_910x362_scrot](https://user-images.githubusercontent.com/5024695/45444580-21b49f80-b6c8-11e8-9bfa-634275e579b0.png)

i resample using the default (`label="left"`):

![2018-09-12-201141_648x372_scrot](https://user-images.githubusercontent.com/5024695/45444581-21b49f80-b6c8-11e8-9c20-f740a606efce.png)

then resample using `label="right"`
![2018-09-12-201145_688x381_scrot](https://user-images.githubusercontent.com/5024695/45444582-224d3600-b6c8-11e8-87cf-5c0d2378e4ca.png)

The data ends on `2018-06-18 20:25:00` - however  the "right" resampling moves the timestamp to the `2018-06-19 00:00:00` - basically into the future from a data point of view. 
By doing this, the "remerge" you'll need to do in the strategy should not find anything to merge to (it's future) - and therefore this datapoint will be dropped in real mode (i know it's not June).

@berlinguyinca I'll do a PR once we're sure this is the right solution.

**Comment by xmatthias** [comment] 2018-09-13 04:15
I'll be honest - the merge-stuff is in the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html) for merging  (scroll down all the way - `value` in both frames converts to `value_x` and `value_y`.

I would not know how the technical "merge" function could fix this without dropping one or the other (or preferring one over the other) - i prefer not having the column there afterwards - so at least you see it error out and need to investigate which of the 2 column you're currently working with...

**Comment by mvbrouw** [comment] 2018-09-14 10:51
Whoops - my bad. I didn't realise that the merge function was actually a part of pandas.

My issue has been sufficiently solved by applying above mentioned fixes. 

Thank you all very much for your help in this.

I'll leave this thread open in case you want to follow up on the resample bug. If not, feel free to close it.

**Comment by xmatthias** [comment] 2018-09-14 17:49
good point, thanks for reminding me!

created the Pr - will therefore close this -> https://github.com/berlinguyinca/technical/pull/6

**Closed by xmatthias** 2018-09-14 17:49 UTC
Labels: backtest
