### ISSUE TITLE
Issue with partial exits the coin amount not same as requested by the Strat.

### ISSUE THREAD

**Issue by Mandark-droid** [freqtrade/freqtrade#10065] opened 2024-04-11 05:07 UTC
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
using docker on RHEL 8.8 with image version as docker-2024.4-dev-859dd6b7

Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

I have a trade open for which we have a feature called grinding which does partial entry/exit but the amount request by the strat is not what FT is reporting and there is some mismatch in the sells as the sell are for less amount then bought. For example I have a trade open for REQ with below order history

(#1) 2024-03-27 09:55:50 (UTC)buy for 0.1883 | 493 | 47
(#2) 2024-03-27 17:10:18 (UTC)buy for 0.174 | 57 | g5
(#3) 2024-03-27 21:07:53 (UTC)sell for 0.1825 | 55 | g5 1403
(#4) 2024-03-28 02:54:39 (UTC)buy for 0.1766 | 56 | g5
(#5) 2024-04-08 14:20:18 (UTC)buy for 0.1676 | 110 | g1
(#6) 2024-04-08 23:01:45 (UTC)sell for 0.1708 | 102 | g1 1474
(#7) 2024-04-11 02:05:18 (UTC)buy for 0.1648 | 112 | g1
(#8) 2024-04-11 02:49:30 (UTC)sell for 0.1678 | 104 | g1 1487

*Explain the problem you have encountered*
As you see above for order id 5 the coin amount bought is 110 but sold is only 102 similarly for order id 7 the coin amount bought is 112 but sold is only 104.

![image](https://github.com/freqtrade/freqtrade/assets/89932595/d59a1ccb-d49d-4439-a81a-ca4b6dfbe321)

Also as you see from the exchange side the amount sold is less while based on the logs the strat is trying to make a sell for 112 coins but for some reason FT has placed a wrong coin amount order on the exchange for sell. 

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  Wrong amount of coins getting sold.
  * What did you expect to happen?
Ideally would expect it to place a sell order for the same amount as bought which the strat is requesting for but FT has placed a wrong order.

### Relevant code exceptions or logs
I think this issue could be due to the recent commits in FT. https://github.com/freqtrade/freqtrade/commit/8000f94295c090fb6b5a3cfd6f05ac0e93c17447

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 2024-04-08 08:55:19,973 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 09:46:03,232 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 10:36:47,404 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 10:57:23,056 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 11:57:58,468 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 12:38:32,734 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 14:20:18,853 - NostalgiaForInfinityX4 - INFO - Grinding entry (g1) [2024-04-08 14:20:18.828922+00:00] [REQ/USDT] | Rate: 0.1676 | Stake amount: 18.566380000000002 | Profit (stake): -10.691801999999981 | Profit: -9.48% | Grind profit: 0.00% (0.0 USDT)
2024-04-08 14:20:18,854 - freqtrade.freqtradebot - INFO - Position adjust: about to create a new order for REQ/USDT with stake_amount: 18.566380000000002 for Trade(id=247, pair=REQ/USDT, amount=550.00000000, is_short=False, leverage=1.0, open_rate=0.18577941, open_since=2024-03-27 09:55:50)
2024-04-08 14:20:19,046 - freqtrade.freqtradebot - INFO - Order 182594975 was created for REQ/USDT and status is closed.
2024-04-08 14:20:19,251 - freqtrade.freqtradebot - INFO - DCA order closed, trade should be up to date: Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275131, open_since=2024-03-27 09:55:50)
2024-04-08 14:20:19,253 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275131, open_since=2024-03-27 09:55:50)
2024-04-08 14:20:19,259 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275131, open_since=2024-03-27 09:55:50) [buy]: 0.11 REQ - rate: 0.001
2024-04-08 14:20:19,492 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275131, open_since=2024-03-27 09:55:50), fee=0.11.
2024-04-08 14:20:19,492 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=247, pair=REQ/USDT, amount=109.89000000, is_short=False, leverage=1.0, open_rate=0.16760000, open_since=2024-03-27 09:55:50).
2024-04-08 15:39:29,517 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-08 19:20:29,342 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-08 19:41:02,304 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-08 23:01:45,139 - NostalgiaForInfinityX4 - INFO - Grinding exit (g1) [2024-04-08 23:01:45.116022+00:00] [REQ/USDT] | Rate: 0.1708 | Stake amount: 18.788 | Coin amount: 110.0 | Profit (stake): -8.563840999999982 | Profit: -6.53% | Grind profit: 1.91% (0.3587207637231513 USDT)
2024-04-08 23:01:46,985 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-08 23:01:47,013 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=247, pair=REQ/USDT, amount=660.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50).
2024-04-09 06:42:43,684 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-09 11:44:29,753 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-09 14:55:18,940 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-09 15:56:03,464 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-09 16:56:47,790 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-09 19:48:22,048 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 05:14:23,161 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 06:19:53,076 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 06:20:08,016 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 06:40:26,653 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 06:41:45,044 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 07:11:00,714 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 07:11:59,258 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 07:51:34,545 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 07:51:47,846 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 08:02:07,282 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 08:02:16,310 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 10:12:43,744 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 10:13:08,233 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 10:33:17,367 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 10:33:23,230 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 11:23:51,128 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 11:24:14,580 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 12:14:26,822 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 12:17:06,284 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 14:15:04,114 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 14:15:11,593 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 16:15:40,614 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 16:16:26,166 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 17:16:17,105 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 17:16:39,090 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 18:26:53,426 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 18:27:41,795 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 18:48:23,617 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 18:48:46,911 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 18:50:04,167 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-10 20:19:22,495 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-10 20:20:02,828 - NostalgiaForInfinityX4 - WARNING - The trade Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50) is configured to HOLD until the profit ratio of 0.1% is met
2024-04-11 02:05:18,250 - NostalgiaForInfinityX4 - INFO - Grinding entry (g1) [2024-04-11 02:05:18.226042+00:00] [REQ/USDT] | Rate: 0.1648 | Stake amount: 18.566380000000002 | Profit (stake): -11.85554599999999 | Profit: -9.04% | Grind profit: 0.00% (0.0 USDT)
2024-04-11 02:05:18,251 - freqtrade.freqtradebot - INFO - Position adjust: about to create a new order for REQ/USDT with stake_amount: 18.566380000000002 for Trade(id=247, pair=REQ/USDT, amount=558.00000000, is_short=False, leverage=1.0, open_rate=0.18275384, open_since=2024-03-27 09:55:50)
2024-04-11 02:05:18,461 - freqtrade.freqtradebot - INFO - Order 183206549 was created for REQ/USDT and status is closed.
2024-04-11 02:05:18,651 - freqtrade.freqtradebot - INFO - DCA order closed, trade should be up to date: Trade(id=247, pair=REQ/USDT, amount=670.00000000, is_short=False, leverage=1.0, open_rate=0.17975387, open_since=2024-03-27 09:55:50)
2024-04-11 02:05:18,652 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=247, pair=REQ/USDT, amount=670.00000000, is_short=False, leverage=1.0, open_rate=0.17975387, open_since=2024-03-27 09:55:50)
2024-04-11 02:05:18,656 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=247, pair=REQ/USDT, amount=670.00000000, is_short=False, leverage=1.0, open_rate=0.17975387, open_since=2024-03-27 09:55:50) [buy]: 0.112 REQ - rate: 0.001
2024-04-11 02:05:18,884 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=247, pair=REQ/USDT, amount=670.00000000, is_short=False, leverage=1.0, open_rate=0.17975387, open_since=2024-03-27 09:55:50), fee=0.112.
2024-04-11 02:05:18,885 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=247, pair=REQ/USDT, amount=111.88800000, is_short=False, leverage=1.0, open_rate=0.16480000, open_since=2024-03-27 09:55:50).
2024-04-11 02:49:29,829 - NostalgiaForInfinityX4 - INFO - Grinding exit (g1) [2024-04-11 02:49:29.804786+00:00] [REQ/USDT] | Rate: 0.1678 | Stake amount: 18.7936 | Coin amount: 112.0 | Profit (stake): -9.769785999999954 | Profit: -6.53% | Grind profit: 1.82% (0.3421165048543693 USDT)
2024-04-11 02:49:30,508 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=247, pair=REQ/USDT, amount=670.00000000, is_short=False, leverage=1.0, open_rate=0.17975637, open_since=2024-03-27 09:55:50)
2024-04-11 02:49:30,525 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=247, pair=REQ/USDT, amount=670.00000000, is_short=False, leverage=1.0, open_rate=0.17975637, open_since=2024-03-27 09:55:50).
0.22722
  ```

**Comment by Mandark-droid** [comment] 2024-04-11 05:08
Having similar observations for some other trades as well. And can provide more examples if needed.

**Comment by iterativv** [comment] 2024-04-11 05:43
For clarification, an example.

1) We buy 1 coin at 100.
2) We buy another coin at 150, so the strat should return +150 here.
3) At 200, we want to sell 200, 1 coin. Should we return here -200 ... if yes, it's going  to exit 200 in stake, 1 coin ?

**Comment by xmatthias** [comment] 2024-04-11 16:33
@iterativv your sample doesn't really make sense (the coin part, mostly).

[`adjust_trade_position()`](https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position) always returns an amount in stake currency. 
The amount of coins you own is irrelevant.

so if you buy coins (the the amount of coin's doesn't actually matter for the adjust-position callback and will depend on the price you're buying the coins ) for 100$ - and more coins for 150$ - your total stake is now 250$ (you might own 2 coins based on that - or 2000 ... that's irrelevant, and determined by the price of the coins at the time of purchase).

(so far, your sequence is:
* initial buy, 100$
* additional entry for 150$
)
if the strategy now returns -200$ - then it'll be left with a remaining stake of 50$.

As the [`adjust_trade_position()` docs for position decrease](https://www.freqtrade.io/en/stable/strategy-callbacks/#decrease-position) explains, returning `-trade.stake_amount` will result in 100% of the position being sold.
So returning `-trade.stake_amount / 2` will sell 50% of the position (in the above sample, that'd be 250$ / 2 - so the return value would be 125$). For freqtrade, that will mean that it will sell half  of the position (which could be 1 coin, or 1000 coinds - depending on the purchase price).

Behavior of this slightly changed with the [last release](https://github.com/freqtrade/freqtrade/releases/tag/2024.3) - and was highlighed as potentially breaking change.

---

now for the actual issue: 
I fail to correlate the trade history with the actual orders (a screenshot of order history would be better usually).
Logs stop on 2024-04-11 02:xx - the first trade fill is on 2024-04-11 07:35 ... so i'm tempted to assume that the screenshot is simply from something else - not related to the logs (which makes the whole thing a lot more confusing).
I also doubt it's timezone problems - as the difference between logs and screenshot doesn't appear to be a full hour.

What the strategy output's is actually irrelevant. it can surely be useful to debug your strategy - but it's not something we'll consider in any analysis.


From the logs - it seems like everything works as expected (at least i can't find any reason to believe that something went wrong from these logs, and the seemingly non-corresponding ) - but order sizes are not the way you expect them - which makes this a strategy problem - at least until i see something different.

Most likely - caused by not properly reading the release log - which i'd strongly recommend to do on every update to avoid issues (that's the channel to be informed about potentially breaking updates / changes).

**Comment by iterativv** [comment] 2024-04-11 17:24
The coin amount in order to highlight it, it's the only one that stays stable regardless of the current price.

So, at 200, if we exit completely we get 400 total in stake. If the strategy requests partial -200 here, we will sell 320, right ?

There will be 320 here: `INFO - Position adjust: about to create a new order for PAIR with stake_amount: 320`

I see the release logs too and also the new code changes, I wanted to confirm that is intentional. Thanks.

**Comment by xmatthias** [comment] 2024-04-11 17:30
> So, at 200, if we exit completely we get 400 total in stake. 

This sentence doesn't make sense. "at 200" ... price is really irrelevant here (i assume this refers to price).

If you enter a position with a stake of 200$ - then `-trade.stake_amount` returns -200 - which will be a full exit.
This is independent of price movement - if price moved up 20% or down 20% - you'll still have an initial stake amount that was 200$.

returning -100 in this case (half of the stake_amount) results in a partial exit of ~50% of the available position (it's a "roughly 50%" as the exchange usually does need rounding).

**Comment by iterativv** [comment] 2024-04-11 17:35
Based on the example above, 1 coin at 100 and 1 at 150, so we paid 250 in total. Now we are at 200, if we return -200, it's going to exit 1.6 coins, 320 in current stake. Then the trade.amount should be 0.4 and the trade.stake_amount 80 ?

There is no issue, simply have to account for the recent changes.

Thanks.

**Comment by Mandark-droid** [comment] 2024-04-11 17:54
@xmatthias

I have already copied and pasted the order history from frequi in the description section and the screen shot in the description is from the exchange(Binance) where it confirms that the coin amount in the order is different from what ft is reporting. If you checked the logs the strategy is trying to sell the proper amount as the buy but on exchange the order placed is with a different amount and based on what is placed on the exchange frequi is showing in the UI but it is not what the strategy is asking FT to sell. 

So in my opinion it's an issue with freqtrade and not the strategy. Here is a screenshot from frequi order history and the order history from the exchange for your reference.  And regarding your concern on the timezone the screenshot from the exchange is taken through mobile app which is running on IST timezone while the logs and FT timezone is in GMT. ![IMG_20240411_231535.jpg](https://github.com/freqtrade/freqtrade/assets/89932595/5cea2b00-4685-4803-b088-b266a392ce7d)

![Screenshot_2024-04-11-23-12-51-61.jpg](https://github.com/freqtrade/freqtrade/assets/89932595/ba6dcaa3-605d-47ff-a33f-00f2fd01fa7e)

Hope this gives you more clarity on the issue and you can help resolve it.

**Comment by Mandark-droid** [comment] 2024-04-11 18:00
For example the last sell order 2024-04-11 02:49:29,829 - NostalgiaForInfinityX4 - INFO - Grinding exit (g1) [2024-04-11 02:49:29.804786+00:00] [REQ/USDT] | Rate: 0.1678 | Stake amount: 18.7936 | Coin amount: 112.0 | Profit (stake): -9.769785999999954 | Profit: -6.53% | Grind profit: 1.82% (0.3421165048543693 USDT)

The strategy is trying to sell the same amount of coins that it bought but eventually the order is placed by FT on the exchange and as you see the order placed on the exchange is with a different amount than what the strategy has requested.

**Comment by xmatthias** [comment] 2024-04-11 18:33
comparing your 2 screenshots - i do see that freqUI is perfectly aligned with the exchange (though the sorting is reversed - so read one from top to bottom, and the other one from bottom to top).

Now the output from the strategy is certainly confusing you - as it's suggesting something that's irrelevant to freqtrade - and hence also irrelevant to me.
A strategy can output whatever it want's - what does actually count is what is returned from the callback function - with the logic being explained in [the docs](https://www.freqtrade.io/en/stable/strategy-callbacks/#decrease-position) - as well as here.


---

@iterativv sounds roughly correct - effectively, the calculation will be `200 * 2 / 250` - boiling down to `stake-returned * trade.amount / trade.stake_amount`.

this logic is  simplified over what we had [before (link to older docs)](https://www.freqtrade.io/en/2024.2/strategy-callbacks/#decrease-position) - where for a full exit, the strategy needed to do `-(trade.amount / trade.leverage) * current_exit_rate` - just to get to (roughly) the correct full stake.
it's a breaking change - and has been mentioned as breaking in the release - as well as having been explained in the docs.

**Comment by iterativv** [comment] 2024-04-11 19:18
So, before if we wanted to exit that 200 stake (1 coin at 200 price), we return -(1 * exit_rate) / trade.leverage = -200

Now it should be -(1 * (trade.stake_amount / trade.amount) = -125 ... this is going to report that is going to create a sell order with 200 in stake - that in fact is the 1 coin. It just not as orthogonal, but not the end of the world.

Thanks.

**Comment by abdozoon** [comment] 2024-04-12 10:57
Yes, new version broke my dry-run spot strategy, the strategy would calculate a specific stake, but once executed, I see a discrepancy on the executed partial sell order, leaving more dust than desired for each order. I had to restore the freqtradebot.py manually from the previous version to get back to the previous versions' behavior.

Example:
sell_stake = 5.64
return -sell_stake

What I see executed on the FreqUI is $5.47

**Comment by stash86** [comment] 2024-04-12 13:30
> Yes, new version broke my dry-run spot strategy, the strategy would calculate a specific stake, but once executed, I see a discrepancy on the executed partial sell order, leaving more dust than desired for each order. I had to restore the freqtradebot.py manually from the previous version to get back to the previous versions' behavior.
> 
> Example: sell_stake = 5.64 return -sell_stake
> 
> What I see executed on the FreqUI is $5.47

We switched to the simpler implementation to make it easier for users. For current logic, when you return 5.64, you are actually asking the bot to sell (5.64/full stake) portion of the coin, so depending on the full stake amount, the real $ value will differ.

Maybe if you want us to help you migrate to the new logic, you can share your old code here

**Comment by abdozoon** [comment] 2024-04-12 14:14
> > Yes, new version broke my dry-run spot strategy, the strategy would calculate a specific stake, but once executed, I see a discrepancy on the executed partial sell order, leaving more dust than desired for each order. I had to restore the freqtradebot.py manually from the previous version to get back to the previous versions' behavior.
> > Example: sell_stake = 5.64 return -sell_stake
> > What I see executed on the FreqUI is $5.47
> 
> We switched to the simpler implementation to make it easier for users. For current logic, when you return 5.64, you are actually asking the bot to sell (5.64/full stake) portion of the coin, so depending on the full stake amount, the real $ value will differ.
> 
> Maybe if you want us to help you migrate to the new logic, you can share your old code here

Thanks, Stefano, for your response.

My logic is that if I open a new adjust position with 10 ADA's, depending on the price movement, it makes xx% profit, I want to partially sell the same 10 ADA's, so I calculate 10 ADA's multiplied by current_rate, then the output (I expect it to be the real $ value) will be the sell_stake that I explained in the previous comment.

Why in the new logic it has to depend on the full stake amount of the current parent trade when executing a partial sell? I know this was explained in the PR referenced in the new version's changelog, but it makes less sense for precise strategies?
How to make it independent from the full stake without going back to the previous version as I've done?
If the above is not possible, is it possible to return specific quantity instead? Just return the negative 10 ADA's as in the above example.

Thank you.

**Comment by perkmeister** [comment] 2024-04-12 21:48
In the previous code the `adjust_trade_position()` value `stake_amount` returned was converted to a base amount to sell with the following equation, which adjusted the position of the current quote value:
`amount = (stake_amount * trade.leverage) / current_rate`.
So rearranging, this is what you had to return to adjust it by `amount`:
`stake_amount = (amount * current_rate)/trade.leverage`.

The code has changed to adjust the position by reducing the total staked, i.e. `trade.stake_amount`, by `stake_amount`. The new equation for this is:
`amount = (stake_amount * trade.amount) / trade.stake_amount`
rearranging gives what you would need to return to adjust it by `amount`:
`stake_amount = (amount * trade.stake_amount)/trade.amount`

So in your case if you want to sell 10 ADA's you would return
`(-10 * trade.stake_amount)/trade.amount`
Hopefully that will fix your problem by being able to sell a given amount of base.
(Note that if you were to return `trade.stake_amount` the equation above reduces to `trade.amount` for the amount sold, i.e. it would sell all you hold and close the trade).

**Comment by abdozoon** [comment] 2024-04-12 23:44
> In the previous code the `adjust_trade_position()` value `stake_amount` returned was converted to a base amount to sell with the following equation, which adjusted the position of the current quote value: `amount = (stake_amount * trade.leverage) / current_rate`. So rearranging, this is what you had to return to adjust it by `amount`: `stake_amount = (amount * current_rate)/trade.leverage`.
> 
> The code has changed to adjust the position by reducing the total staked, i.e. `trade.stake_amount`, by `stake_amount`. The new equation for this is: `amount = (stake_amount * trade.amount) / trade.stake_amount` rearranging gives what you would need to return to adjust it by `amount`: `stake_amount = (amount * trade.stake_amount)/trade.amount`
> 
> So in your case if you want to sell 10 ADA's you would return `(-10 * trade.stake_amount)/trade.amount` Hopefully that will fix your problem by being able to sell a given amount of base. (Note that if you were to return `trade.stake_amount` the equation above reduces to `trade.amount` for the amount sold, i.e. it would sell all you hold and close the trade).

Thanks, perk, for your time elaborating on the new logic.

I will test it on the release of the new version and see how it goes with my strategy.

**Comment by xmatthias** [comment] 2024-04-20 07:02
Closing this - as it's a simple adaptation from the strategy's side.

**Closed as completed** 2024-04-20 07:02 UTC
Labels: Question, Strategy assistance
