### ISSUE TITLE
Dynamic stake_amount for selling

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#6819] opened 2022-05-13 12:31 UTC
Hello, 

Is it possible from code set stake_amount for selling?  I don't want sell all bought amount in one transaction, but I wan't to split it on the parts.  Bellow I described an example which I would like to support using freqtrade:

1 April - XRP cost 1$. bot bought 1xrp. Balance: 1 xrp
2 April - XRP cost 0.5$. bot bought 1xrp. Balance: 2 xrp  
3 April - XRP cost 0.6$. bot sold 1 xrp.  Balance: 1 xrp 
4 April - XRP cost 0.7$ bot bought 1 xrp.  Balance: 2 xrp
5 April - XRP cost 1.2$. bot sold 2 xrp.  Balance: 0 xrp

**Comment by stash86** [comment] 2022-05-13 13:30
Not possible for now

**Comment by xmatthias** [comment] 2022-05-13 14:06
This is actually a duplicate of #1519.

it MAY be introduced in #6545 (assuming that PR is brought to a mergable state at some point) - but cooperation there is slow and tedious - so don't expect a solution to that soon.

**Closed as completed by xmatthias** 2022-05-13 14:06 UTC
Labels: Duplicate
