### ISSUE TITLE
[Doc re-organization] - [About-> feature section] - [Task]

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2497] opened 2019-11-08 09:09 UTC
The about -> feature documentation mix functional and technical concerns. The end user is mostly concern by what i can do with this bot not the how ?

[Click here](https://via.hypothes.is/https://www.freqtrade.io/en/latest/#annotations:group:__world__) to see the beginning of the list of examples that have to be completed (only the first two points have been analysed).

All the points can be reviewed with this kind of questions : why is it useful for the end user ? Is it really a feature or a technical explanation ?

**Comment by xmatthias** [comment] 2019-11-09 15:00
Well i agree on all points ... 

> sqlite stuff in features:

i wouldn't keep this here at all ... 

I would maybe add an additional point: (?)
> Download historical data for backtesting and hyperopt.

> Blacklist crypto-currencies: Select which crypto-currency you want to avoid.

Rephrase to " Blacklist crypto-currencies: disable which crypto- ..."

> Display profit/loss in fiat: Display your profit/loss in any of 33 fiat currencies supported.

change to "Display profit/loss in fiat: Display your profit/loss"
The amount of fiat currencies is not relevant here (and probably not correct anymore since we can also use some cryptos now.


Maybe we can also add a 2nd link to slack - it's under "here" ... maybe we can add it again at the end as "Get Your Invite Link" ... 


side note: i'll register on that page sooner or later ...

**Comment by hroff-1902** [comment] 2019-11-28 20:57
I have not looked before at it with appropriate drive, thanks for the annotations set you wrote on hypothesis,io, I like this approach! 👍

**Comment by gaugau3000** [comment] 2019-11-29 08:42
continue discussion in  #2583 so can be closed.

**Comment by hroff-1902** [comment] 2019-11-30 10:16
opening it -- the issue is assumed to be resolved by #2583 so it should stay open till the merge of that PR.

That's the normal workflow between issues and pull requests at github. The issue is open till it's resolved (if this is not a question but a bug report/enhancement suggestion and assumes it's have to be resolved by the changes in the code/docs, if it's not a simple question)

**Comment by gaugau3000** [comment] 2019-12-01 19:37
> normal workflow between issues and pull requests at github 

Are you sure ? or normal worflow for freqtrade (i don't have the response) ;-) ?

But it is ok for me :-) just i have the habits to not represent the same thing open in project management twice (difficult to have an overview).

Have a nice day.

**Comment by hroff-1902** [comment] 2019-12-01 20:12
yes, it's normal for github in the whole -- if you place the mark 'Solves #issue' in a PR, the issue #issue will be closed automatically when the PR closing it merges into develop/master. This assumes the the issue describing the problem is open all the time till resolution -- till the PR closing it is complete with development and verification.

How can this be opposite? An issue describes the problem, the PR contains resolution, the issue is not be treated as closed till resolution successfully applied...

**Comment by xmatthias** [comment] 2019-12-02 07:24
> This assumes that the issue describing the problem is open all the time till resolution -- till the PR closing it is complete with development and verification.

You need to consider 2 points (not from a project management standpoint):
* Users will (hopefully) search through issues if they have problems, not through PR's - so it keeps the issue open until it's really fixed.
* we could have an attempted fix via PR - which is rejected (for whatever reason - maybe it does not work as expected) - we'd have the issue closed, and it's very dangerous to forget to reopen it (not really relevant for documentation issues, but ...)

**Comment by hroff-1902** [comment] 2019-12-02 07:39
Me? Or this comment is for @gaugau3000 ? 🤔 
I guess we both established an efficient way to communicate via the comments at github (as github workflow assumes) while working together on issues/prs with no disagreements on the statuses of the issues/prs...

**Comment by xmatthias** [comment] 2019-12-02 07:45
@hroff-1902 I "enriched" your points with a reason as to why we're doing this (and many many other open source projects do, too). It's good to know the why - not just the "this way" 😄

**Comment by xmatthias** [comment] 2020-02-24 19:22
Closing this as the attached PR #2583 has been merged.

**Closed by xmatthias** 2020-02-24 19:22 UTC
Labels: Documentation
