### ISSUE TITLE
can not rebuild the trade

### ISSUE THREAD

**Issue by stanley86yelnats** [freqtrade/freqtrade#7805] opened 2022-11-27 10:54 UTC
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by froggleston** [comment] 2022-11-27 10:56
You've provided no information as to what the problem is. Please fill out the issue guidelines - they're there to help us solve your problem.

**Comment by stanley86yelnats** [comment] 2022-11-27 10:58
Operating system: _ubuntu___
Python Version: __3.10.7___ (python -V)
CCXT version: __ccxt==2.0.58___ (pip freeze | grep ccxt)
Freqtrade Version: __freqtrade 2022.10__ (freqtrade -V or docker-compose run --rm freqtrade -V for Freqtrade running in docker)

**Comment by stanley86yelnats** [comment] 2022-11-27 10:59
```
freqtrade    | 2022-11-27 10:47:17,433 - freqtrade.wallets - INFO - Adjusted stake amount for pair BAND/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
freqtrade    | 2022-11-27 10:47:17,828 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-11-27 10:47:17,943 - freqtrade.wallets - INFO - Stake amount for pair UNFI/USDT is too small (1.1806410828666667 < 5.32994923857868), adjusting to 5.32994923857868.
freqtrade    | 2022-11-27 10:47:17,944 - freqtrade.wallets - INFO - Adjusted stake amount for pair UNFI/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
freqtrade    | 2022-11-27 10:47:18,373 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-11-27 10:47:18,491 - freqtrade.wallets - INFO - Stake amount for pair ENJ/USDT is too small (1.1806410828666667 < 5.32994923857868), adjusting to 5.32994923857868.
freqtrade    | 2022-11-27 10:47:18,492 - freqtrade.wallets - INFO - Adjusted stake amount for pair ENJ/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
freqtrade    | 2022-11-27 10:47:18,896 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-11-27 10:47:19,012 - freqtrade.wallets - INFO - Stake amount for pair CHR/USDT is too small (1.1806410828666667 < 5.32994923857868), adjusting to 5.32994923857868.
freqtrade    | 2022-11-27 10:47:19,013 - freqtrade.wallets - INFO - Adjusted stake amount for pair CHR/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
freqtrade    | 2022-11-27 10:47:19,413 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-11-27 10:47:19,528 - freqtrade.wallets - INFO - Stake amount for pair BEL/USDT is too small (1.1806410828666667 < 5.32994923857868), adjusting to 5.32994923857868.
freqtrade    | 2022-11-27 10:47:19,529 - freqtrade.wallets - INFO - Adjusted stake amount for pair BEL/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
freqtrade    | 2022-11-27 10:47:20,746 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-11-27 10:47:20,863 - freqtrade.wallets - INFO - Stake amount for pair KLAY/USDT is too small (1.1806410828666667 < 5.32994923857868), adjusting to 5.32994923857868.
freqtrade    | 2022-11-27 10:47:20,864 - freqtrade.wallets - INFO - Adjusted stake amount for pair KLAY/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
freqtrade    | 2022-11-27 10:47:21,265 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-11-27 10:47:21,379 - freqtrade.wallets - INFO - Stake amount for pair IMX/USDT is too small (1.1806410828666667 < 5.32994923857868), adjusting to 5.32994923857868.
freqtrade    | 2022-11-27 10:47:21,380 - freqtrade.wallets - INFO - Adjusted stake amount for pair IMX/USDT is more than 30% bigger than the desired stake amount of (1.18064108 * 1.3 = 1.53483341) < 5.32994923857868), ignoring trade.
```

**Comment by froggleston** [comment] 2022-11-27 11:00
The error is pretty clear - `Stake amount for pair UNFI/USDT is too small `. You need to make sure your stake is large enough for the exchange to accept.

**Comment by stanley86yelnats** [comment] 2022-11-27 11:00
I re install the soft by docker, but the old trades are out of control, what can I do?

**Comment by froggleston** [comment] 2022-11-27 11:03
Is this live?

You'll have to close the orders on the exchange and delete the trade from the freqtrade sqlite database (or start fresh with a new database - check the docs how to do this).

**Comment by stanley86yelnats** [comment] 2022-11-27 11:05
@froggleston,these trades are hold by the binance api ,how can I change the config.json?

**Comment by stanley86yelnats** [comment] 2022-11-27 11:05
yes, they are live.

**Comment by froggleston** [comment] 2022-11-27 11:07
You have to manually close the order on the exchange, or increase the stake amount in your config and reload. However, as your adjusted stake is a percentage of your original entry position amount, I doubt this will work.

**Comment by xmatthias** [comment] 2022-11-27 13:45
the above log doesn't look like it's from new orders - but from existing orders.

the "out of control" is most likely your DCA algo [`adjust_trade_position()`](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position) - which is issuing way too small stakes.

That method does provide you with an argument, `min_stake` - which you cannot go below for each pair - otherwise you risk the above problem (which is not a problem - just a fact of life that exchanges won't allow very small orders).

**Comment by stanley86yelnats** [comment] 2022-11-28 07:28
freqtrade.exceptions.OperationalException: Could not load markets, therefore cannot start. Please investigate the above error for more details

does this log mean the network between my server and finance?

**Comment by xmatthias** [comment] 2022-11-28 07:32
could be that, could be a binance (maybe regional) outage, or could be a temporary hickup from binance (they had that yesterday morning) ...

**Comment by stanley86yelnats** [comment] 2022-11-28 08:23
and now....

**Comment by xmatthias** [comment] 2022-11-28 15:27
CI shows that it might either be (attempted) blocks against US based IP addresses (they seem to be removed in the European afternoon), or some other problem at the binance site.

According to CI, it should be working again (at least for now).

**Comment by xmatthias** [comment] 2022-12-08 07:34
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.

**Closed as completed by xmatthias** 2022-12-08 07:34 UTC
Labels: Question, Strategy assistance
