### ISSUE TITLE
failed to run freqtrade in pycharm debug mode 

### ISSUE THREAD

**Issue by CryptoRahino** [freqtrade/freqtrade#8895] opened 2023-07-11 10:54 UTC
## Describe your environment

  * Operating system: ubuntu 22
  * Python Version: 3.10 (`python -V`)
  * CCXT version: ccxt==4.0.17: (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.6 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Describe the problem:

when running any command of freqtrade in debug mode on pycharm. it fails with the error:
```
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/rahino/freqtrade/freqtrade/types/__init__.py)
```
i'm using conda with fresh installed freqtrade on the latest stable version. tested with venv too. same result.
### Steps to reproduce:

  1. follow instructions here to install conda env and git clone
  2. open pycharm and runn debug mode
  
### Observed Results:
debug failed to start. this doesn't happens when running it via cli or in pycharm.
going back to revision from 28/05/2023 solves the issue!

### Relevant code exceptions or logs

  ```
/home/rahino/anaconda3/envs/freqtrade/bin/python /snap/pycharm-community/336/plugins/python-ce/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 46589 --file /home/rahino/freqtrade/freqtrade/main.py 
Traceback (most recent call last):
  File "/snap/pycharm-community/336/plugins/python-ce/helpers/pydev/pydevd.py", line 8, in <module>
    from contextlib import contextmanager
  File "/home/rahino/anaconda3/envs/freqtrade/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/home/rahino/anaconda3/envs/freqtrade/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/home/rahino/freqtrade/freqtrade/types/__init__.py", line 1, in <module>
    from freqtrade.types.valid_exchanges_type import ValidExchangesType  # noqa: F401
  File "/home/rahino/freqtrade/freqtrade/types/__init__.py", line 1, in <module>
    from freqtrade.types.valid_exchanges_type import ValidExchangesType  # noqa: F401
  File "/home/rahino/freqtrade/freqtrade/types/valid_exchanges_type.py", line 2, in <module>
    from typing import List
  File "/home/rahino/anaconda3/envs/freqtrade/lib/python3.10/typing.py", line 28, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "/home/rahino/anaconda3/envs/freqtrade/lib/python3.10/re.py", line 124, in <module>
    import enum
  File "/home/rahino/anaconda3/envs/freqtrade/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/rahino/freqtrade/freqtrade/types/__init__.py)
  ```

**Comment by xmatthias** [comment] 2023-07-11 12:34
Without looking into the details of this:
can you reproduce this without the pycharm context (running the same command that you run for the execution of freqtrade).

if not, then it's most likely a pycharm bug - which should be fixed there, even though using a different codebase can obviously result in a problem to be not triggered.

**Comment by xmatthias** [comment] 2023-07-11 20:16
Testing this further, i can't reproduce this with vscode, which makes it quite likely that it's a problem with pycharm (or their debugging support, anyway).
It also seems like you're starting main.py directly - which is not what we recommend in our [debugging guideline](https://www.freqtrade.io/en/stable/developer/#debug-configuration).
instead, you should be using the module configuration (simply use "freqtrade" there).

With that setting (as recommended in the documentation), i can also debug perfectly fine with pycharm.

For now, i don't see anything to do on our side.

**Comment by xmatthias** [comment] 2023-07-17 05:02
Closing this - as i can neither reproduce this, nor did we have any further feedback on the suggested improvements to the startup mode.

**Closed as completed by xmatthias** 2023-07-17 05:02 UTC
Labels: Question

**Comment by ihopethiswillfi** [comment] 2023-10-19 19:30
For those coming after me and facing this same issue, I got everything running smoothly in PyCharm after doing the following:

- rename the freqtrade/freqtrade/types folder to something else.  I called it `typess`.  Obviously use PyCharm's refactoring tools which applies the name change in the entire project.

- in debug configuration for `freqtrade/freqtrade/__main__.py` , make sure you set the working directory to `.../freqtrade/` instead of `.../freqtrade/freqtrade`
 
Tadaa you're done!

**Comment by xmatthias** [comment] 2023-10-19 19:56
@ihopethiswillfi you could also just follow the instructions to setup pycharm.

I've tried to recreate this multiple times - but i can't if i follow the instructions when setting up the pycharm environment.
Also, the OP never bothered to provide details on how his pycharm is configured, so we can either reproduce the error, or tell him how to fix it on his side.

I'm happy to look at this if someone tells me HOW to configure pycharm to reproduce this - you're clearly not using the recommended configuration (which you can find [here](https://www.freqtrade.io/en/latest/developer/#pycharm)) - otherwise you'd not be hitting this (though i also didn't find another configuration that has me hit this).

**Comment by ihopethiswillfi** [comment] 2023-10-20 05:55
@xmatthias I had followed the [conda installation instructions](https://www.freqtrade.io/en/latest/installation/#installation-with-conda) to the letter and then ran into this issue.  From searching the issues here, it looked to me like I'm not the only one and I thought I'd be helpful.  

I had not read the link you added in your reply, the `contributors guide`, because at the moment I'm just looking at getting things up and running.

Perhaps inserting a link to the `PyCharm debugging setup` inside the `installation instructions page` would bring new user's attention to it.

**Comment by xmatthias** [comment] 2023-10-21 07:45
@ihopethiswillfi the key point is the pycharm debugging setup though - can you share how you have set that up (ignore contributors guide - how YOU had it by yourself)? 
I think / hope that this will help with the reproduction.

**Comment by ihopethiswillfi** [comment] 2023-10-21 11:27
The results of doing a few experiments:

The 'default' way to debug in Pycharm is to right-click on `main.py` or `__main__.py` and then click debug (this is what I did).  I'd say in the far majority of projects this 'just works' without creating any kind of debugging config (which is often required in vscode).  However with freqtrade, this results in the `ImportError: cannot import name 'MappingProxyType'` error.

If I then go to manually edit the debug settings and simply change the working directory from `.../freqtrade/freqtrade/` to `.../freqtrade` then everything works as it should.

To bring things more in line with the debugging settings from the freqtrade docs, in the debug config I then also change `script` to `module`.  But I don't see a difference when making this change.

The one thing I can't figure out is the renaming of the `types` directory.  It isn't needed apparently.  But I swear that yesterday I was not able to get it to work without renaming that folder.  Oh well, I guess it's a good thing that it works now. :)  Thanks a lot xmatthias.  I'm up and running.

**Comment by xmatthias** [comment] 2023-10-21 12:26
> However with freqtrade, this results in the `ImportError: cannot import name 'MappingProxyType'` error.

Which is odd in it's own - as  `MappingProxyType`  is not part of the freqtrade repository.

---

That said - it's also not really a problem - freqtrade won't work with the "debug file" run - as there's no case where you simply execute `freqtrade` - you'll always have to have one or the other command line argument.

the same is true for the directory - CWD should be at the root of the repository, not in some random directory.
