### ISSUE TITLE
Edge positioning not working 

### ISSUE THREAD

**Issue by alipoursanati** [freqtrade/freqtrade#3410] opened 2020-05-31 17:38 UTC
**Environment**
Operating system: ubutnu 20.04 (uname: 5.4.0-33-generic #37-Ubuntu x86_64 x86_64 x86_64 GNU/Linux)
Python Version: No python is installed; using freqtrade with docker
CCXT version: using freqtrade with docker
Freqtrade Version: docker-b1e6662c

**Problem:**
I am trying to run the bot with the edge mode; but it returns a panda error as below.

**Steps to reproduce:**
docker run --rm -v `pwd`/config.json:/freqtrade/config.json -v /home/ali/freqtrade/user_data/:/freqtrade/user_data -it freqtrade edge --strategy ARPS2

**Observed Results:**
**Relevant code exceptions or logs**
```
2020-06-02 17:52:05,438 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 107, in start_edge
    edge_cli.start()
  File "/freqtrade/freqtrade/optimize/edge_cli.py", line 47, in start
    result = self.edge.calculate()
  File "/freqtrade/freqtrade/edge/edge_positioning.py", line 107, in calculate
    data = load_data(
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 88, in load_data
    hist = load_pair_history(pair=pair, timeframe=timeframe,
  File "/freqtrade/freqtrade/data/history/history_utils.py", line 50, in load_pair_history
    return data_handler.ohlcv_load(pair=pair,
  File "/freqtrade/freqtrade/data/history/idatahandler.py", line 164, in ohlcv_load
    pairdf = self._ohlcv_load(pair, timeframe,
  File "/freqtrade/freqtrade/data/history/jsondatahandler.py", line 77, in _ohlcv_load
    pairdata.columns = self._columns
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 661, in _set_axis
    self._data.set_axis(axis, labels)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 177, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 6 elements
```

Please help me to solve the issue.
Thank you in advance.

**Comment by xmatthias** [comment] 2020-05-31 17:48
Please fill out the issue template requesting versions, otherwise we'll close this as invalid.

Thanks for your understanding.

**Comment by alipoursanati** [comment] 2020-05-31 21:57
> Please fill out the issue template requesting versions, otherwise we'll close this as invalid.
> 
> Thanks for your understanding.

sure, I am new to github, would you please send me a link for the template so I can fill it out?
Thank you in advance.

**Comment by Theagainmen** [comment] 2020-05-31 22:01
When you created the issue, you should automatically start with the template. I think you removed the template yourself. But here it is anyway:



## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by hroff-1902** [comment] 2020-06-01 08:47
And I would cite it:

> Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

**Comment by alipoursanati** [comment] 2020-06-02 17:58
Dear hroff-1902 , Theagainmen, and xmatthias,
I have updated the issue based on the template you provided. Please let me know if any further changes are required. I appreciate your help.

**Comment by xmatthias** [comment] 2020-06-04 04:36
well it seems like you've got no data downloaded.

Edge requires (identical to backtesting and hyperopt) historic data, it can run on.

Now i'm not sure why it crashes (never seen it like this before).
if i run edge (or backtesting) without data, the errors are as follows (for every pair, obviously)

```
2020-06-04 06:34:57,860 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "EOS/ETH", timeframe: 5m. Use `freqtrade download-data` to download the data
```

have you got data in your user directory? (`/home/ali/freqtrade/user_data/data/<exchange>/` ?)

**Comment by hroff-1902** [comment] 2020-06-04 18:06
@xmatthias this may be caused by an update from the older version: Edge saves historical data, new updated version expects it be in the new format, and data saved by the Edge before update is in the old format... no format transformation is called in this case, I guess (at least, this case should be tested)

**Comment by xmatthias** [comment] 2020-06-04 18:25
I don't see why this should be a problem - edge uses ohlcv data - which is a format we did not change (the change we did affected only trades data).

**Comment by hroff-1902** [comment] 2020-06-04 18:35
ah, only trades, you are right, shame on me...

**Comment by alipoursanati** [comment] 2020-06-08 11:14
hi,
thank you for your help. I erased all of the previously downloaded data and redownloaded them again but the problem still exists. what do you suggest? thank you in advance

**Comment by xmatthias** [comment] 2020-06-08 11:43
best by making sure that the data is in the correct folder - is accessible to the docker container (basically that you downloaded it via the docker container).

since you're not using the docker-compose setup, there's a lot of things that can be done wrongly when downloading data - so best provide us with the  command you're using to download the data.

**Comment by hroff-1902** [comment] 2020-06-08 15:07
as far as I understood, he runs freqtrade in the container using our prebuilt image and downloads data  using the freqtrade installation installed locally on the host machine. Can it be that the image is new and the local installation is old, using older data format?

**Comment by xmatthias** [comment] 2020-06-08 15:13
@hroff-1902 letme repeat what I said above - the data format for OHLCV data has not been changed in more than 2 years. 

If it's really the case that data-download uses a different installation than running freqtrade, then i suspect there are some directory mixups - but i see no reference to that anywhere in the users comments that one command is running outside of the docker container.

**Comment by orehunt** [comment] 2020-06-09 10:53
``` Expected axis has 0 elements``` means that pandas read an empty json file `[]`, so it infers 0 columns, and when you ovveride the columns, the number must match, if you use `reindex(columns)` it should avoid this
The datahandler doesn't check for emptyness on `ohlcv_load` and history_utils despite logging empty downloads still calls `ohlcv_store` so I think it's possible that an empty json file might get written

**Comment by alipoursanati** [comment] 2020-06-21 21:15
hello,
after struggling for days I think I have found the problem. at first, I used 200 pairs as my whitelist input, but when I reduced it to half the edge works but it returns an empty table with the following error for almost every pairs:

`freqtrade.strategy.interface - WARNING - Unable to analyze candle (OHLCV) data for pair STEEM/BTC: Dataframe returned from strategy has mismatching last close price.`

I am using Heikinashi chart type in the indicator section of my strategy as follow, which I think might be the problem:

`# Heikin Ashi
        heikinashi = qtpylib.heikinashi(dataframe)
        dataframe['ha_open'] = heikinashi['open']
        dataframe['ha_close'] = heikinashi['close']
        dataframe['ha_high'] = heikinashi['high']
        dataframe['ha_low'] = heikinashi['low']

 # Assigning dataframes to HeikinAshi ones
        dataframe['open'] = dataframe['ha_open']
        dataframe['close'] = dataframe['ha_close']
        dataframe['high'] = dataframe['ha_high']
        dataframe['low'] = dataframe['ha_low']`

any more help is appreciated.

**Comment by hroff-1902** [comment] 2020-06-21 22:28
you are changing the dataframe 'close' prices for reasons unknown for me:
```
dataframe['close'] = dataframe['ha_close']
```
(also all others, 'open', 'high' and 'low').

The warning you see tells you about this, that you are doing something strange and something wrong with the dataframe.

It's not related at all with the Edge module.

**Comment by alipoursanati** [comment] 2020-06-21 23:50
Hi,
I just want to use heikinashi chart type in my strategy and I thought assinging the datafarmes might be the correct way to use the chart. So how should I implement heinkinashi in my strategy?
Also, i will check the edge without heikinashi as soon as I get home from work and will let you know about the results.
Thank you for your help.

**Comment by hroff-1902** [comment] 2020-06-22 02:44
simply assign in the `populate_indicators()` method:
```
    heikinashi = qtpylib.heikinashi(dataframe)
    dataframe['ha_open'] = heikinashi['open']
    dataframe['ha_close'] = heikinashi['close']
    dataframe['ha_high'] = heikinashi['high']
    dataframe['ha_low'] = heikinashi['low']
```
and then use those columns in `populate_buy_trend()`/`populate_sell_trend()` methods.

And, as I said, it's not related with the Edge module at all.

**Comment by xmatthias** [comment] 2020-07-17 14:24
I'll close this as the question was answered and @hroff-1902 gave some insights how to use heikinashi without running into problems with the strategy validation.

Feel free to comment / reopen if the issue still persists.

**Closed by xmatthias** 2020-07-17 14:24 UTC
Labels: Triage Needed

**Comment by bahler5** [comment] 2020-11-30 21:19
I had the same issue. All I needed to do was identify the files in my data folder that were empty and delete them.
