### ISSUE TITLE
insufficient balance on Binance

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3513] opened 2020-06-23 08:29 UTC
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.3
  * CCXT version: 1.29.52
  * Freqtrade Version: freqtrade develop-f80b5f94
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

FT was not able to place a sell order, which has been triggered by an ROI in strategy file

### Steps to reproduce:

all orders being placed as limit orders, stop-loss as stop-loss on exchange, fees in BNB

after cancelling the last stop-loss order (on exchange) manually at Binance, FT was successfully placing the sell order triggered by the ROI
  
### Observed Results:

all balances and placed limit orders look ok, see screenshots
![Bildschirmfoto vom 2020-06-23 08-07-22](https://user-images.githubusercontent.com/46339082/85379589-3a5c1580-b53c-11ea-8019-85c7053c2b39.png)
![Bildschirmfoto vom 2020-06-23 08-10-04](https://user-images.githubusercontent.com/46339082/85379590-3af4ac00-b53c-11ea-940e-4f86376776dc.png)

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=rate, params=params)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1223, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 452, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1954, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 471, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 580, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/binance.py", line 1935, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/root/freqtrade/.env/lib/python3.7/site-packages/ccxt/base/exchange.py", line 489, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.
  ```

**Comment by xmatthias** [comment] 2020-06-23 08:46
we'll definitely need more logs ...

ideally starting with 23:19 (when the last stoploss order was placed) ... 
but just the stacktrace will not tell us enough to properly investigate.

**Comment by Prossi79** [comment] 2020-06-24 05:37
mmmh same problem as last time, my logs are not going back til 23:19 just to 4:00, although I got 10 lof files of each bot

how can I extend the time period logs being saved? I am starting the bot with following cmd:

freqtrade trade --config config_binance.json --logfile=/var/log/freqtrade-service-4.log

Already asked google how to do, but did not find a good hint ...

**Comment by xmatthias** [comment] 2020-06-24 05:55
well you can't - it's in loggers.py - specifying size (1Mb) and count (10 files) ...

Normally this will be enough - never had a case where it's not going back far enough except with you ...

i mean - my logs (even on very active bots) go back for weeks ...

**Comment by xmatthias** [comment] 2020-06-24 18:56
without logs - i'll have to assume this is a duplicate of #3499 and #3116.

Now in case of #3499 i got a "full" log - which does cover the issue - however i'm not certain how this should be handled, as it seems like a stoploss is placed - and the `fetch_order()` call to the exchange just a few subseconds later does receive a "order does not exist" response from the exchange (even though the order with this ID exists when checking manually later). 

In the upper 2 issues, it's happening when (re)placing a stoploss order, but the same can happen with any other type of sell-order as well (basically where cancelling of the stoploss fails).

most likely - the first error your bot encounters is the same as #3499 - where it tries to "replace" the stoploss - which fails until ROI is reached - and then that fails with the ROI order (obviously again for quite some time).

**Closed** 2020-06-30 04:53 UTC
Labels: Duplicate, Triage Needed

**Comment by hroff-1902** [comment] 2020-06-30 04:55
the fix merged into develop, pls verify
