### ISSUE TITLE
naming : difference between percent and ratio in the documentation

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2971] opened 2020-02-24 20:52 UTC
Hi,

Seems like ratio and percent are both used but i think represent a percentage in all cases (a ratio is like x/y ).

tradable_balance_ratio could be tradable_balance_percent ?
last_stake_amount_min_ratio could be last_stake_amount_min_percent ?

Maybe i missed something.

Have a nice day.

**Comment by xmatthias** [comment] 2020-02-25 05:42
well the (intended) difference between percent and ratio is a `*100`.


to pick up on one of your examples: 
`last_stake_amount_min_ratio=0.99` would be `last_stake_amount_min_percent=99` .

While using percent would be a possibility - when talking about percent, i'd assume a number between 0 and 100 - while we expect a number between 0 and 1. 
using the term Percent here would be misleading i think.

I don't know any value we use (even though they may be called `_percent` historically) which we expect between 0 and 100.
If you know a better term than ratio (i'm not certain it's correct) - i'm happy for suggestions - but percent is too misleading i think.

The only reference i found (this is difficult to google) is [this](https://english.stackexchange.com/questions/140120/a-better-expression-for-percentage-divided-by-100).
There's quite some discussion around this topic there ... one point is made in a comment to the first item:

> No, you would need to call it a fraction of the length. Percentages go from 0 to 100. Or, rewrite the function to use a percentage; or maybe even both (x < 1, it's a fraction; 1 < x < 100, it's a percentage)


maybe a better name would be fraction - but another comment says:

> In similar circumstances, the term I usually see is 'proportion', or sometimes 'ratio'. [...]

**Comment by gaugau3000** [comment] 2020-02-25 10:47
> well the (intended) difference between percent and ratio is a *100.

I am not sure a ratio is when you compare [two things](https://wikidiff.com/ratio/percentage]). You trade a percentage/fraction of a balance with is a sub-part of the balance there is no ratio as the balance is the sole variable.

> to pick up on one of your examples:
> last_stake_amount_min_ratio=0.99 would be last_stake_amount_min_percent=99 .

You are true (my bad)

I think fraction is the good term (the explanation in this  [link](https://stackoverflow.com/questions/8646521/term-for-percent-percentage-fraction-scale-factor) seems quite convincing).

Because we have in the doc `amount_reserve_percent `(witch is represented by a fraction in the doc : `Defaults to 0.05`) and in the another hand `tradable_balance_ratio` but it could be amount_reserve_fraction and tradable_balance_fraction (both are fractions) same thing for `last_stake_amount_min_ratio`.

I remember when i read the doc i don't understand the difference between percent and ratio but seems like both could be renames fraction ?

Have a nice day.

**Comment by xmatthias** [comment] 2020-02-25 11:25
yes they should be.

Changing the documentation is one thing ... changing the settings is a different thing though - that's something i really don't like to do as it'll lead to 

a) breaking users configs
or 
b) cause unexpected behaviour as the setting is now going into the void.

And honestly, i personally hate projects / software which causes problems and requires interaction after every update, so i try to make very sure that doesn't happen with projects i'm involved in (when possible).

**Comment by gaugau3000** [comment] 2020-02-25 13:25
I pretty well understand your point of view (I remember we have already discuss about) but :
 - It is a technical debt and the next developer or the next reader will have the same question again and again and refactoring can be more difficult.
 - Yes it require interaction but : it takes hours and maybe days to develop a winning strategy so the user experience is a concern but it takes 1 minute to rename a json key (with the deprecated workflow it work pretty well and the last time i have to do that in freqtrade it was ok).

The most representative in freqtrade is the `roi` and `ticker_interval` witch is not intuitive and 'it is due to historical reasons' is funny one time but more with stay with this semantic aberration more it cost at the end (it is a kind of habit to use not the good words and newcomers don't have this habits : they are virgins or tainted by trading knowledge).

I am sorry to be a pain about that but it will sure increase quality at the end.

**Comment by gaugau3000** [comment] 2020-02-25 13:28
@hroff-1902 @xmatthias i change the labels hope this is fine for you and match with current discussion.

**Comment by xmatthias** [comment] 2020-02-25 13:35
I'd leave documentation as it'll affect documentation just as well ...

ticker_interval will be changed  (see #2318)  - but `roi` - i don't see what that should be changed to - and i don't see any problem or questions raising from it's naming.
I know you're not happy that it's using minutes - but i'm not happy would it be using candles.

Using minutes is fine - and the issue does contain the method to convert it from candles to minutes (here: https://github.com/freqtrade/freqtrade/issues/2463#issuecomment-549025766).

**Comment by gaugau3000** [comment] 2020-02-25 14:25
> I'd leave documentation as it'll affect documentation just as well ...

in fine it impacts doc but the root cause is the code base. It is why i have remove documentation but is it fine.

> ticker_interval will be changed (see #2318)

Good. My memory is broken because i put a like on it. 

> - but roi - i don't see what that should be changed to - and i don't see any problem or questions raising from it's naming.

i think `roi` should be named `take_profit` because roi is not really that good word for the life of a trade. It is good for an investment (i put 1000 dollar in trading i win 100 dollar at the end of the year : roi is  10%).


> I know you're not happy that it's using minutes - but i'm not happy would it be using candles.

i' am not talking about minutes just the naming of roi :-) i think it is fine to use minutes (or another human easy understanding thing like hours, days... for humans) because candle mean is relative (depending on timeframe) . I like the candle approach because i can test multi-timeframes easily and reduce mistakes on long timeframes during development process and use roi = -1, that's all.

> Using minutes is fine - and the issue does contain the method to convert it from candles to minutes (here: #2463 (comment)).

I know i use it many tks !

**Comment by xmatthias** [comment] 2020-02-25 15:30
i dislike `take_profit` - it suggests scaling out of the trade - which it's not - it's selling the whole position - so that's a totally misleading name in my opinion.

**Comment by xmatthias** [comment] 2020-02-25 18:25
honestly, renaming `roi` "just because" is out of the question to me.

If we're honest, should we rather spend time changing `roi` to another name (Keep in mind, this is not something that is broken, it's not even something that's created many questions, neither on slack, nor in issues here) - or try and spend that time working on bugs / or enhancements / new functions which will bring real benefit to users?

**Comment by gaugau3000** [comment] 2020-02-25 18:41
Of course roi naming is not a big deal. Just try to push that a common langage is a common understanding of the things and easier to built then on top of it. that's all.

**Comment by hroff-1902** [comment] 2020-02-28 07:58
I would not use the term 'fraction' in the code/names of the settings and, therefore, in the user docs: in python fractions are those that represented with numerator and denominator (P/Q), so this can be confusing for developers. The term 'ratio' is okay for me, and the usages of percentage, where this term is still used in the places where it actually represents ratio (due to historical reasons) should be eliminated, with renaming and deprecation old names of the settings (slow process).

**Comment by hroff-1902** [comment] 2020-02-28 08:49
@xmatthias is not it time to remove deprecated 'capital_available_percentage' in edge section of settings?

**Comment by xmatthias** [comment] 2021-04-05 12:55
Going to close this as we removed most occurances of percentage - and i currently don't intend to rename parameters because of this, as that will always cause unnecessary upgrade pain - even if we have a grace-period of a few versions.

**Closed by xmatthias** 2021-04-05 12:55 UTC
Labels: Documentation, Tech debt
