### ISSUE TITLE
Insufficient funds to create limit sell order 

### ISSUE THREAD

**Issue by Tekpre012** [freqtrade/freqtrade#2530] opened 2019-11-14 08:28 UTC
## Step 2: Describe your environment

  * Operating system: Unbuntu 18.04 VirtBoxed on W10
  * Python Version: 3.6.8 (
  * CCXT version: 1.19.25
  * Branch: Master | Develop

## Step 3: Describe the problem:

The system crashed during the night, 3 orders remained open. When I tried again to start the bot it gave me this error:
```
- freqtrade.persistence - INFO - Found open trade: Trade(id=1, pair=MTH/BTC, amount=320.00000000, open_rate=0.00000156, open_since=2019-11-13 23:17:40)
- freqtrade.persistence - INFO - Found open trade: Trade(id=2, pair=TNT/BTC, amount=58.00000000, open_rate=0.00000861, open_since=2019-11-13 23:32:17)
- freqtrade.persistence - INFO - Found open trade: Trade(id=3, pair=NCASH/BTC, amount=4166.00000000, open_rate=0.00000012, open_since=2019-11-14 00:05:43)

- freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market TNT/BTC.Tried to sell amount 58.0 at rate 9.03e-06.Message: binance Account has insufficient balance for requested action.
- freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create market sell order on market NCASH/BTC.Tried to sell amount 4166.0 at rate None.Message: binance Account has insufficient balance for requested action.
- freqtrade.freqtradebot - INFO - Bot heartbeat. PID=4570
- freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market TNT/BTC.Tried to sell amount 58.0 at rate 9.03e-06.Message: binance Account has insufficient balance for requested action.
- freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create market sell order on market NCASH/BTC.Tried to sell amount 4166.0 at rate None.Message: binance Account has insufficient balance for requested action.
```

keep repeating this and it doesn't work.
Now I have sold manually but the problem persists.

Here the Config code:
 --------------------------------------

> 
```
{
    "max_open_trades": 3,
    "stake_currency": "BTC",
    "stake_amount": 0.0005,
    "fiat_display_currency": "USD",
    "dry_run": false,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "use_order_book": false,
        "ask_last_balance": 0.0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "exchange": {
        "name": "binance",
        "key": 
        "secret": 
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit ": 200
        },

> 

 --------------------------------------
     
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false

 --------------------------------------

    },
    "db_url": "sqlite:///tradesv3.sqlite",
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5,
        "heartbeat_interval": 60
-----------
```

I solved deleting file "tradesv3.sqlite" in freqtrade folder.
I'ts normal?

**Comment by hroff-1902** [comment] 2019-11-14 12:17
formatted it a bit...

**Comment by xmatthias** [comment] 2019-11-14 18:36
you'll need to be carefull with orders vs. Trades.

you say 3 orders remained open - but i think it's trades.
Usually, this should be handled by the database - so once it comes back up, it's in the "correct" state.

Now it'll depend what the reason for the crash was - if the disc was full (or something else that caused the database not to update) - then it is possible that the bot sold the trades before it crashed - but wasn't able to update the database correctly.

Question:
* did you sell (or touch) the amounts shown above on the exchange?
* if not - what are / were the amounts you have/had? (it says `pair=TNT/BTC, amount=58.0` - how many TNT do you actually have)?

**Comment by Tekpre012** [comment] 2019-11-14 22:18
Yes trades non orders sorry. System crash for other program, non for bot. Before restarting bot i sell "manualy" the leften open trades.

**Comment by xmatthias** [comment] 2019-11-15 05:24
well in this case, you can consult the [SQL cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange)  to close the trades manually.

from the id's, i think there were only 3 trades done - but if it'd run for longer, you'd lose the trade history by deleting the database.

**Comment by nhads18** [comment] 2019-11-15 10:51
I am experiencing the same issue, has anyone fixed this?

**Comment by xmatthias** [comment] 2019-11-15 11:01
As mentioned above - since the trades have been sold manually, you'll need to use the queries from the SQL Cheatsheet to close the trades in the database manually.

**Comment by xmatthias** [comment] 2019-11-16 09:14
I'll close this since the explanation for the issue is simple - the trades were sold "on-exchange" - so the bot needs to be told about that.

**Closed** 2019-11-16 09:13 UTC
Labels: Question
