### ISSUE TITLE
/stats command in Telegram returns N/A for Avg duration

### ISSUE THREAD

**Issue by vicks316** [freqtrade/freqtrade#8591] opened 2023-05-02 21:03 UTC
## Describe your environment

  * Operating system: Raspbian
  * Python Version: 3.10.11
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.4
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
/stats command in Telegram returns N/A for Avg duration for version 2023.4 but returns the correct value in freqtrade version 2023.1

### Steps to reproduce:

  1. Run the bot in any mode with Telegram setup in the config file
  2. type command /stats in Telegram
 
  
### Observed Results:

  * What happened?
  I got the following result
Reason      Exits    Wins    Losses
-------------  -------  ------  --------
Trail. Stop         27      27         0
Stoploss            16       0        16
Avg. Duration
------  ---------------
Wins    N/A
Losses  N/A
  * What did you expect to happen?
I expected the following result as per freqtrade version 2023.1

Reason      Exits    Wins    Losses
-------------  -------  ------  --------
Trail. Stop         27      27         0
Stoploss            16       0        16
Avg. Duration
------  ----------------------
Wins    3 days, 5:51:27.990559
Losses  4 days, 1:14:03.501307

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
 I got the following result
Reason      Exits    Wins    Losses
-------------  -------  ------  --------
Trail. Stop         27      27         0
Stoploss            16       0        16
Avg. Duration
------  ---------------
Wins    N/A
Losses  N/A

I expected the following result as per freqtrade version 2023.1

Reason      Exits    Wins    Losses
-------------  -------  ------  --------
Trail. Stop         27      27         0
Stoploss            16       0        16
Avg. Duration
------  ----------------------
Wins    3 days, 5:51:27.990559
Losses  4 days, 1:14:03.501307
  ```

**Comment by xmatthias** [comment] 2023-05-03 04:59
Nice catch - will be fixed shortly.

**Closed as completed** 2023-05-03 05:03 UTC
Labels: Bug, RPC

**Comment by vicks316** [comment] 2023-05-03 11:40
Thank you @xmatthias , you're a legend :)

**Comment by vicks316** [comment] 2023-05-10 14:20
Hi @xmatthias,

This issue still persists, will this be fixed in the next stable release?

**Comment by xmatthias** [comment] 2023-05-10 14:42
The issue is fixed in the develop version.
If it's not fixed, then you're not on develop - and hence didn't receive a new version.

Stable releases usually are done once per month and should be considered as a snapshot (with changelog).
If you want this fix earlier, please switch to the develop version.
