### ISSUE TITLE
Partially close trade - question

### ISSUE THREAD

**Issue by sagrafio** [freqtrade/freqtrade#6853] opened 2022-05-17 09:46 UTC
Hello there, is there any way to partially close an open trade? E.g. sell 50% of an asset if winning x%, leave the other 50% running. Thanks.

**Comment by xmatthias** [comment] 2022-05-17 09:51
There is currently not, although incentives are currently running in this direction.

duplicate of #1519

**Closed as completed by xmatthias** 2022-05-17 09:51 UTC
Labels: Duplicate
