### ISSUE TITLE
volume pair filter - whitelist discrepancies

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3166] opened 2020-04-14 08:02 UTC
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04 LTS
  * Python Version: 3.7.3
  * CCXT version: ccxt==1.25.81
  * Branch: Develop
  * Last Commit ID: e33371663526352ba6a16bc9908b4201cf4a0b1e

  
## Step 3: Describe the problem:

I have set up different pair filters in my config for FTX, main focus being volume filter. Using the test-pair list cmd in the terminal, it works - I am getting the top5 volume USDT pairs. Using the telegram cmd /whitelist it still show more then 5 pairs.

### Steps to reproduce:

  1.  result test-pairlist cmd
```

freqtrade test-pairlist --config config_lever_FTX_Bblow_slow1.json --quote USDT
['ETHBEAR/USDT', 'ETHBULL/USDT', 'BEAR/USDT', 'BULL/USDT', 'LINKBEAR/USDT']
```

  2.  /whitelist on telegram show 8 pairs, not 5 

```
Using whitelist ['StaticPairList', 'PrecisionFilter', 'PriceFilter', 'SpreadFilter', 'VolumePairList'] with 8 pairs
BEAR/USDT, BULL/USDT, EOSBEAR/USDT, ETHBEAR/USDT, ETHBULL/USDT, XRPBEAR/USDT, XRPBULL/USDT, LINKBEAR/USDT
```

  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

my config

  ```

    "pairlists": [

        {"method": "StaticPairList"},
        {"method": "PrecisionFilter"},
        {"method": "PriceFilter", "low_price_ratio": 0.175},
        {"method": "SpreadFilter", "max_spread_ratio": 0.0075},
        {
            "method": "VolumePairList",
            "number_assets": 5,
            "sort_key": "quoteVolume",
            "refresh_period": 600
        }


  ```

**Comment by xmatthias** [comment] 2020-04-14 08:08
What do your logs say?

also, do you have open trades? 
The most likely reason: open trades are ALWAYS added to the whitelist (and shown with `/whitelist` commands)  as long as they are open - but these pairs may fall out of the whitelist once the trade is sold / closed.

**Comment by Prossi79** [comment] 2020-04-14 08:14
nope, no open trades ... still showing 8 pairs on telegram

logs seems to be okay, showing the "filter process" 

example:

```
2020-04-14 10:13:11,477 - SpreadFilter - INFO - Removed BCHBULL/USDT from whitelist, because spread 0.800% >0.75%
2020-04-14 10:13:11,477 - SpreadFilter - INFO - Removed BCHBEAR/USDT from whitelist, because spread 0.807% >0.75%
2020-04-14 10:13:11,478 - SpreadFilter - INFO - Removed BNBBULL/USDT from whitelist, because spread 0.785% >0.75%
2020-04-14 10:13:11,478 - SpreadFilter - INFO - Removed BNBBEAR/USDT from whitelist, because spread 0.774% >0.75%
2020-04-14 10:13:11,478 - SpreadFilter - INFO - Removed LINKBEAR/USDT from whitelist, because spread 0.762% >0.75%
2020-04-14 10:13:16,481 - PriceFilter - INFO - Removed EOSBULL/USDT from whitelist, because 1 unit is 22.305%
2020-04-14 10:13:16,482 - PriceFilter - INFO - Removed BSVBULL/USDT from whitelist, because 1 unit is 51.001%
2020-04-14 10:13:16,482 - PriceFilter - INFO - Removed BSVBEAR/USDT from whitelist, because 1 unit is 101.982%
2020-04-14 10:13:16,483 - SpreadFilter - INFO - Removed BCHBULL/USDT from whitelist, because spread 0.800% >0.75%
2020-04-14 10:13:16,484 - SpreadFilter - INFO - Removed BCHBEAR/USDT from whitelist, because spread 0.807% >0.75%
2020-04-14 10:13:16,484 - SpreadFilter - INFO - Removed BNBBULL/USDT from whitelist, because spread 0.785% >0.75%
2020-04-14 10:13:16,484 - SpreadFilter - INFO - Removed BNBBEAR/USDT from whitelist, because spread 0.774% >0.75%
2020-04-14 10:13:16,485 - SpreadFilter - INFO - Removed LINKBEAR/USDT from whitelist, because spread 0.762% >0.75%
2020-04-14 10:13:21,478 - freqtrade.worker - INFO - Bot heartbeat. PID=841, version='develop-29159176', state='RUNNING'
```

**Comment by xmatthias** [comment] 2020-04-14 08:22
what's your pair_whitelist look like? just so i got something to copy/paste against ?

**Comment by Prossi79** [comment] 2020-04-14 09:10
here we go:

```
       "pair_whitelist": [
         
        "BEAR/USDT",
        "BULL/USDT",
        "EOSBEAR/USDT",
        "EOSBULL/USDT",
        "ETHBEAR/USDT",
        "ETHBULL/USDT",
        "XRPBEAR/USDT",
        "XRPBULL/USDT",
        "BCHBULL/USDT",
        "BCHBEAR/USDT",
        "BNBBULL/USDT",
        "BNBBEAR/USDT",
        "BSVBULL/USDT",
        "BSVBEAR/USDT",
        "LINKBULL/USDT",
        "LINKBEAR/USDT"


        ],

        "pair_blacklist": [


        ]


    }, 

```

**Comment by Prossi79** [comment] 2020-04-14 09:29
PS: just set up another similar bot ... same problem - in the FT log it properly filters, but /whitelist on telegram shows 7 pairs, not just 5

the FT log:

```
2020-04-14 11:26:45,726 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/root/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-04-14 11:26:45,727 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/root/freqtrade/freqtrade/pairlist/PrecisionFilter.py'...
2020-04-14 11:26:45,731 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PriceFilter from '/root/freqtrade/freqtrade/pairlist/PriceFilter.py'...
2020-04-14 11:26:45,735 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist SpreadFilter from '/root/freqtrade/freqtrade/pairlist/SpreadFilter.py'...
2020-04-14 11:26:45,736 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist VolumePairList from '/root/freqtrade/freqtrade/pairlist/VolumePairList.py'...
2020-04-14 11:26:45,775 - PriceFilter - INFO - Removed EOSBULL/USDT from whitelist, because 1 unit is 22.122%
2020-04-14 11:26:45,775 - PriceFilter - INFO - Removed BSVBULL/USDT from whitelist, because 1 unit is 51.053%
2020-04-14 11:26:45,776 - PriceFilter - INFO - Removed BSVBEAR/USDT from whitelist, because 1 unit is 102.716%
2020-04-14 11:26:45,776 - SpreadFilter - INFO - Removed BCHBULL/USDT from whitelist, because spread 0.813% >0.75%
2020-04-14 11:26:45,776 - SpreadFilter - INFO - Removed BCHBEAR/USDT from whitelist, because spread 0.897% >0.75%
2020-04-14 11:26:45,776 - SpreadFilter - INFO - Removed BNBBULL/USDT from whitelist, because spread 0.763% >0.75%
2020-04-14 11:26:45,776 - SpreadFilter - INFO - Removed BNBBEAR/USDT from whitelist, because spread 0.840% >0.75%
2020-04-14 11:26:45,777 - SpreadFilter - INFO - Removed LINKBULL/USDT from whitelist, because spread 0.959% >0.75%
2020-04-14 11:26:45,777 - SpreadFilter - INFO - Removed LINKBEAR/USDT from whitelist, because spread 0.917% >0.75%
2020-04-14 11:26:45,777 - VolumePairList - INFO - Searching 5 pairs: ['ETHBEAR/USDT', 'ETHBULL/USDT', 'BEAR/USDT', 'BULL/USDT', 'XRPBULL/USDT']
```

**Comment by xmatthias** [comment] 2020-04-14 09:53
For this test - best ensure that you're not using any database ....

The below is my log output (and telegram response) - when using a clean database (no trades whatsoever) - on the latest develop branch.


```
2020-04-14 11:49:38,422 - PriceFilter - INFO - Removed EOSBULL/USDT from whitelist, because 1 unit is 21.932%
2020-04-14 11:49:38,422 - PriceFilter - INFO - Removed BSVBULL/USDT from whitelist, because 1 unit is 51.053%
2020-04-14 11:49:38,422 - PriceFilter - INFO - Removed BSVBEAR/USDT from whitelist, because 1 unit is 102.716%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed ETHBEAR/USDT from whitelist, because spread 0.809% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed XRPBEAR/USDT from whitelist, because spread 0.842% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed BCHBULL/USDT from whitelist, because spread 1.118% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed BCHBEAR/USDT from whitelist, because spread 1.128% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed BNBBULL/USDT from whitelist, because spread 1.217% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed BNBBEAR/USDT from whitelist, because spread 1.036% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed LINKBULL/USDT from whitelist, because spread 1.365% >0.75%
2020-04-14 11:49:38,422 - SpreadFilter - INFO - Removed LINKBEAR/USDT from whitelist, because spread 1.073% >0.75%
2020-04-14 11:49:38,423 - VolumePairList - INFO - Searching 5 pairs: ['ETHBULL/USDT', 'BEAR/USDT', 'BULL/USDT', 'XRPBULL/USDT', 'EOSBEAR/USDT']

```

![2020-04-14-115027_507x617_scrot](https://user-images.githubusercontent.com/5024695/79211160-24e4b400-7e46-11ea-9d3a-87c23188f06a.png)


As you can see - the outputs are aligned ... and correspond to what we would expect.

Best run /status table - maybe it's using a database and you don't know about it ... :) that's the only reasonable explanation i can think for this behaviour.

**Comment by Prossi79** [comment] 2020-04-14 14:39
mmmh thats really strange, I used a fresh and clean database too ... for the new bot I started just today. you mean the sqlite DB, correct?

**Comment by xmatthias** [comment] 2020-04-14 15:00
for now i seem unable to reproduce this (see above).

does it only happen after the bot is running for some time? 

also, make sure to upgrade ccxt - i don't see how that could be related (and i don't think it'll change anything) - but the current version of ccxt is 1.26.x - but the initial post suggests you're having 1.25.x ...

**Comment by Prossi79** [comment] 2020-04-14 15:02
yep, I have updated CCXT too, same problem ... anyway :)  as long as the bot is respecting the filters all is okay, that seems to be case

**Comment by Prossi79** [comment] 2020-04-14 16:11
update: seems not to work, bot just bought XRPBULL which is definitely not in the FTX top5 USDT pairs volume wise

**Comment by xmatthias** [comment] 2020-04-14 17:17
I was very doubtful that it would be working if `/telegram` shows it wrongly... 

I do still think it's something to do with your setup / configuration though - not sure what else i should test as it does show the correct whitelist for me (as shown above).

**Comment by Prossi79** [comment] 2020-04-14 17:26
:) give me some indication where to look in my config / setup pls ... if test-pairlist works and telegram / live not, where would you look 1st?

**Comment by xmatthias** [comment] 2020-04-14 17:32
as said - database - and if you're really using the same config (but let's assume you do).

The problem is - how would you want me to test it if it is not happening for me ... ?
That makes the problem non-reproducible - which means i've got no chance at investigating / fixing it without a huge investment of time. 

In all cases, the following must be met to verify and eventually fix a problem:
* The bug must be obvious 
* The bug must be recreatable (as shown above - it is not).

both are not the case here - so i'll have to assume some kind of misconfiguration of some sort... 

FTX volume is reporting fine for regular pairs (iirc) - it's 0 for pairs which use underlying futures (all leveraged pairs, basically).

**Comment by xmatthias** [comment] 2020-04-14 18:28
Ok i've finally been able to recreate your issue.

VolumePairlist is correctly sorting / removing the pairs - HOWEVER - it's only doing this once - subsequent calls run into the caching - returning the pairlist as is. This works perfectly fine if VolumePairlist is first in line (the first pairlist used) - but is problematic if StaticPairlist is used, as that will always force it's "full" list.

I've always argued that using StaticPairlist before Volumepairlist does not make much sense ... and i'm still of this opinion.

**Comment by Prossi79** [comment] 2020-04-14 19:30
thanks for your efforts! What I wanted to solve with the StaticPairlist first and the VolumePair list after, is to list only spot and leveraged pairs, not the futures and other derivatives.

how to solve this without using static pair list? would you recommend using the blacklist instead?

**Comment by xmatthias** [comment] 2020-04-15 05:36
I'm not sure i understand what you mean.

`freqtrade list-pairs --exchange ftx --quote USDT` lists all assets which have USDT as quote currency.

Now i don't know what you're looking at - so i got no idea what you think is missing ... but to me it looks quite complete ... ?

**Comment by Prossi79** [comment] 2020-04-15 07:52
sorry for confusing you, my fault - I mixed USD and USDT as stake currency  :) let me explain again:

**target -> I want to trade only the top5  3xleveraged tokens on FTX along volume, no derivatives**

you are perfectly right, this is working with USDT at the moment because FTX does not quote derivatives against USDT yet. If they change this, same issue as with USD will appear.

If you change the stake currency to USD (thats where I am coming from), then the approach of just using the volume filter and an empty black or whitelist does not work anymore, as you will find some derivatives in the top5 volume list which cannot be traded with FT currently. An example::

```
2020-04-15 09:43:50,868 - VolumePairList - INFO - Searching 5 pairs: ['BTC-PERP', 'ETH-PERP', 'LINK-PERP', 'BTC-0626', 'BNB-PERP']
2020-04-15 09:43:50,869 - PriceFilter - INFO - Removed LINK-PERP from whitelist, because 1 unit is 30.663%
```
Thats why I started to use 1st) the whitelist to list only 3x leveraged tokens and 2nd) the volume list to select the top5 volume pairs out of the 20 or so 3x leveraged tokens I wanted to trade.

Hope my application issue is clearer now :)

**Comment by hroff-1902** [comment] 2020-04-16 15:36
Same here -- I want to control which subset of pairs is to be used, and then select some of them using VolumeFilter (VolumePairList) and others.

If you select the subset of pair by adding others into blacklist -- this will fail when exchange added new pairs. This can also result in a long blacklist, if exchange contains 200 pairs and I only want 50 (and then select 5. 10 or 20 of them with VolumeFilter (VolumePairList)).

Thus, sometimes it's more convenient, more straight and easier to select pairs by defining the subset in the whitelist, instead of defining blacklist.

The StaticPairList is not really needed -- when it was initially introduced, my opinion was to always fetch whitelist if it's defined (or non-empty). If it's not defined -- the whole list of pairs can be taken and then passed to the chain of filters. Thus, VolumeList (VolumePairList) will in this case also not fetch the list of pairs, when it in the first position -- it will only get the list of pairs passed, either taken from whitelist, or the whole list of pairs, depending on the value of the whitelist attribute, so it will behave exactly as other Filters (and can be renamed to VolumeFilter). StaticPairList is completely redundant with this approach.

**Comment by hroff-1902** [comment] 2020-04-16 15:39
@Prossi79 the fix was merged into develop, pls verify

**Closed** 2020-04-16 15:39 UTC
Labels: Bug
