### ISSUE TITLE
SSL issue with binance

### ISSUE THREAD

**Issue by Spindirac** [freqtrade/freqtrade#3178] opened 2020-04-17 09:39 UTC
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: MACOS X
  * Python Version: 3.7.4
  * CCXT version: 1.24.83
  * Branch: Master
  * Last Commit ID: 9abfdaaaa240dcab2fbd105982ed6eed025d8936
  
  
## Step 3: Describe the problem:

i'm suddenly getting below error when trying to backtest, or refresh pairs history from Binance
GET https://api.binance.com/api/v3/exchangeInfo HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  // paste your log here
(.env) (base) MacBook-Pro-de-Pablo:freqtrade pablo$ freqtrade download-data --exchange binance --days 5 -c config2.json --timeframes 1m 5m 15m 30m 1h
2020-04-17 11:23:40,863 - freqtrade.loggers - INFO - Verbosity set to 0
2020-04-17 11:23:40,863 - freqtrade.configuration.configuration - INFO - Using exchange binance
2020-04-17 11:23:40,863 - freqtrade.configuration.configuration - INFO - Using user-data directory: /Users/pablo/opt/anaconda3/envs/FreqBot1/freqtrade/user_data ...
2020-04-17 11:23:40,863 - freqtrade.configuration.configuration - INFO - Using data directory: /Users/pablo/opt/anaconda3/envs/FreqBot1/freqtrade/user_data/data/binance ...
2020-04-17 11:23:40,863 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m', '15m', '30m', '1h']
2020-04-17 11:23:40,863 - freqtrade.configuration.configuration - INFO - Detected --days: 5
2020-04-17 11:23:40,863 - freqtrade.configuration.configuration - INFO - Using "json" to store OHLCV data.
2020-04-17 11:23:40,864 - freqtrade.configuration.configuration - INFO - Using "jsongz" to store trades data.
2020-04-17 11:23:40,864 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-04-17 11:23:40,864 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-04-17 11:23:40,864 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-04-17 11:23:40,864 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-04-17 11:23:40,867 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ETH/BTC', 'BCH/BTC', 'XRP/BTC', 'EOS/BTC', 'LTC/BTC', 'ETC/BTC', 'DASH/BTC', 'LINK/BTC', 'ADA/BTC', 'XMR/BTC', 'AION/BTC', 'PERL/BTC', 'ENJ/BTC', 'MATIC/BTC', 'XTZ/BTC', 'WAVES/BTC', 'REP/BTC', 'XLM/BTC', 'TRX/BTC', 'ZEC/BTC', 'LSK/BTC', 'BTG/BTC', 'NEO/BTC', 'FET/BTC', 'WAN/BTC', 'GO/BTC', 'ALGO/BTC', 'BAT/BTC', 'LUN/BTC', 'INS/BTC', 'AST/BTC', 'AMB/BTC', 'CHZ/BTC', 'RVN/BTC', 'ATOM/BTC', 'VIBE/BTC', 'SKY/BTC', 'BCPT/BTC', 'OGN/BTC', 'ONT/BTC', 'NKN/BTC', 'XEM/BTC', 'QTUM/BTC', 'TOMO/BTC', 'LEND/BTC', 'ARN/BTC', 'HBAR/BTC', 'IOTA/BTC', 'VIB/BTC', 'THETA/BTC', 'BEAM/BTC', 'BCD/BTC', 'NULS/BTC', 'NEBL/BTC', 'WTC/BTC', 'ICX/BTC', 'MTL/BTC', 'NANO/BTC', 'KMD/BTC', 'MANA/BTC', 'DATA/BTC', 'BQX/BTC', 'MCO/BTC', 'OMG/BTC', 'ZRX/BTC', 'GNT/BTC', 'RLC/BTC', 'BAND/BTC', 'MDA/BTC', 'REN/BTC', 'GXS/BTC', 'KNC/BTC', 'FTT/BTC', 'APPC/BTC', 'STEEM/BTC', 'KAVA/BTC', 'WABI/BTC', 'REQ/BTC', 'PIVX/BTC', 'CVC/BTC', 'PPT/BTC', 'GVT/BTC', 'DUSK/BTC', 'LOOM/BTC', 'ZEN/BTC', 'ARPA/BTC', 'WPR/BTC', 'EVX/BTC', 'XZC/BTC', 'DCR/BTC', 'MTH/BTC', 'HC/BTC', 'ENG/BTC', 'STRAT/BTC', 'DGD/BTC', 'ELF/BTC', 'SNM/BTC', 'STX/BTC', 'CMT/BTC', 'NAS/BTC', 'LRC/BTC', 'DLT/BTC', 'AE/BTC', 'TNT/BTC', 'ARK/BTC', 'SNT/BTC', 'POLY/BTC', 'BLZ/BTC', 'GRS/BTC', 'VITE/BTC', 'QSP/BTC', 'ONG/BTC', 'OAX/BTC', 'POA/BTC', 'STORJ/BTC', 'EDO/BTC', 'BTS/BTC', 'GAS/BTC', 'RDN/BTC', 'BRD/BTC', 'AGI/BTC', 'SYS/BTC', 'VIA/BTC', 'OST/BTC', 'POWR/BTC', 'BNT/BTC', 'RCN/BTC', 'ADX/BTC', 'NAV/BTC', 'ARDR/BTC', 'NXS/BTC', 'QLC/BTC', 'CTXC/BTC'], intervals: ['1m', '5m', '15m', '30m', '1h'] to /Users/pablo/opt/anaconda3/envs/FreqBot1/freqtrade/user_data/data/binance
2020-04-17 11:23:40,867 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-04-17 11:23:40,867 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-04-17 11:23:40,870 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 9000}
2020-04-17 11:23:40,872 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-04-17 11:23:40,873 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-04-17 11:23:40,873 - freqtrade.exchange.exchange - WARNING - Markets were not loaded. Loading them now..
2020-04-17 11:23:40,952 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: GET https://api.binance.com/api/v3/exchangeInfo HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1076)')))
2020-04-17 11:23:40,954 - freqtrade.exchange.exchange - WARNING - Unable to validate pairs (assuming they are correct).
2020-04-17 11:23:40,954 - freqtrade.exchange.exchange - WARNING - Markets were not loaded. Loading them now..
2020-04-17 11:23:41,452 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: GET https://api.binance.com/api/v3/exchangeInfo HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1076)')))

**Comment by xmatthias** [comment] 2020-04-17 09:54
There's only a few possibilities why this can happen:
* exchange downtime
* exchange certificate problem
* installation problem

best go to the URL yourself to verify if it's working from your location.

If it is - then i suspect there is something wrong with your environment / setup - as this does work for me perfectly fine.
if the url does not work in the browser - well - then best try to check your connection - as it is currently working for me.

**Comment by Spindirac** [comment] 2020-04-17 10:05
Hi, URL is working fine. After a few trials, the pair history refresh is working. Without any specific manipulation on my side

**Comment by hroff-1902** [comment] 2020-04-17 14:40
I'm closing this for now since no new input is expected while the problem gone.

Feel free to post here if the problem repeats, we'll reopen it to dig into.

**Closed by hroff-1902** 2020-04-17 14:40 UTC
Labels: CCXT, Question

**Comment by mikahoy045** [comment] 2021-09-16 04:12
Step 2: Describe your environment
Operating system: UBUNTU 20.04
Python Version: 3.8.10
CCXT version: 1.24.83
Branch: Stable
Last Commit ID: 
Step 3: Describe the problem:
Getting error while running docker-compose up -d :
[SSL CERTIFICATE VERIFIED FAILED]

Explain the problem you have encountered

Steps to reproduce:
Observed Results:
What happened?
What did you expect to happen?
Relevant code exceptions or logs:

2021-09-16 03:41:56,670 - freqtrade.worker - INFO - Starting worker 2021.8
2021-09-16 03:41:56,670 - freqtrade.configuration.configuration - INFO - Using config: /freqtrade/user_data/config.json ...
2021-09-16 03:41:56,670 - freqtrade.loggers - INFO - Verbosity set to 0
2021-09-16 03:41:56,672 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
2021-09-16 03:41:56,672 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2021-09-16 03:41:56,672 - freqtrade.configuration.configuration - INFO - Dry run is enabled
2021-09-16 03:41:56,672 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2021-09-16 03:41:56,672 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2021-09-16 03:41:56,688 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-09-16 03:41:56,689 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-09-16 03:41:56,689 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-09-16 03:41:56,702 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-09-16 03:41:56,702 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-09-16 03:41:56,702 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.8
2021-09-16 03:41:56,720 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy SampleStrategy from '/freqtrade/user_data/strategies/sample_strategy.py'...
2021-09-16 03:41:56,721 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2021-09-16 03:41:56,721 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2021-09-16 03:41:56,721 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): buy_rsi = 30
2021-09-16 03:41:56,721 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2021-09-16 03:41:56,722 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): sell_rsi = 70
2021-09-16 03:41:56,722 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2021-09-16 03:41:56,722 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 5m.
2021-09-16 03:41:56,722 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
2021-09-16 03:41:56,722 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 0.01.
2021-09-16 03:41:56,722 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
2021-09-16 03:41:56,722 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'60': 0.01, '30': 0.02, '0': 0.04}
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 0.01
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
2021-09-16 03:41:56,723 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-09-16 03:41:56,724 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-09-16 03:41:56,724 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-09-16 03:41:56,724 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
2021-09-16 03:41:56,724 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-09-16 03:41:56,724 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2021-09-16 03:41:56,724 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-09-16 03:41:56,726 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-09-16 03:41:56,726 - freqtrade.exchange.exchange - INFO - Using CCXT 1.55.28
2021-09-16 03:41:56,726 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-09-16 03:41:56,733 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-09-16 03:41:56,739 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-09-16 03:41:56,923 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 587, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 330, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1383, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 987, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo
2021-09-16 03:41:56,926 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2021-09-16 03:41:57,385 - freqtrade.exchange.exchange - ERROR - Unable to initialize markets.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ftuser/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 587, in fetch
    response = self.session.request(
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/exchange/exchange.py", line 330, in _load_markets
    self._markets = self._api.load_markets()
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 1383, in load_markets
    markets = self.fetch_markets(params)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 987, in fetch_markets
    response = getattr(self, method)(query)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 457, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/binance.py", line 4154, in request
    response = self.fetch2(path, api, method, params, headers, body, config, context)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 502, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 639, in fetch
    raise NetworkError(details) from e
ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/exchangeInfo
2021-09-16 03:41:57,385 - freqtrade.commands.trade_commands - ERROR - BTC is not available as stake on Binance. Available currencies are:
2021-09-16 03:41:57,385 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 65, in __init__
    self.exchange = ExchangeResolver.load_exchange(self.config['exchange']['name'], self.config)
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 32, in load_exchange
    exchange = ExchangeResolver._load_exchange(exchange_name,
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 54, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 148, in __init__
    self.validate_stakecurrency(config['stake_currency'])
  File "/freqtrade/freqtrade/exchange/exchange.py", line 360, in validate_stakecurrency
    raise OperationalException(
freqtrade.exceptions.OperationalException: BTC is not available as stake on Binance. Available currencies are:


already tried with freshly installed os and still no luck, what should I do? (Binance)

**Comment by xmatthias** [comment] 2021-09-16 04:34
Best open a new issue (and fill the issue template out correctly - the log suggests that the versions you inserted are not correct). 
I strongly doubt that it's related to an issue that's over a year old
