### ISSUE TITLE
Unable to use /forcebuy <pair> through Telegram

### ISSUE THREAD

**Issue by captain-nut** [freqtrade/freqtrade#2169] opened 2019-08-21 14:33 UTC
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: 
Container:  Linux 71d68df53e4e 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 GNU/Linux  (Official Freqtrade Docker Image)
Host: Linux docker02 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  * Python Version: 3.7.4
  * CCXT version: 1.18.1068
  * Branch: Master | Develop  <-- Happens on Both Branches
  
## Step 3: Describe the problem:

Unable to use /forcebuy through telegram

### Steps to reproduce:

  1. Start Docker Container
  2. Start Bot
  3. type /forcebuy BTC/USDT on telegram Bot
  
### Observed Results:

  * What happened? Order is not placed
  * What did you expect to happen? Order is placed

It correctly works in dry mode (both with fixed or unlimited stake)
The API seems ok: communication with Binance is ok

### Relevant code exceptions or logs:

**logs**
  ```
  

2019-08-21 14:13:22,290 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:14:12,344 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:14:07,337 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:14:02,331 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:13:57,362 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:13:53,216 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f642f153450>, 'Connect timed out. (connect timeout=5.0)')': /bot882478358:AAFFSAdt99neSwQC7mCoUcLXwY8_rC4O8Lw/getUpdates,
2019-08-21 14:13:52,320 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:13:47,319 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:13:42,310 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:13:37,307 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
freqtrade.TemporaryError: Could not place buy order due to DDoSProtection. Message: binance temporary banned: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."},
    f'Could not place {side} order due to {e.__class__.__name__}. Message: {e}') from e,
2019-08-21 14:13:32,305 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
  File "/freqtrade/freqtrade/exchange/exchange.py", line 420, in create_order,
  File "/freqtrade/freqtrade/exchange/exchange.py", line 435, in buy,
    return self.create_order(pair, ordertype, 'buy', amount, rate, params),
    time_in_force=time_in_force),
  File "/freqtrade/freqtrade/freqtradebot.py", line 363, in execute_buy,
    if self._freqtrade.execute_buy(pair, stakeamount, price):,
    self._rpc_forcebuy(pair, price),
  File "/freqtrade/freqtrade/rpc/rpc.py", line 434, in _rpc_forcebuy,
  File "/freqtrade/freqtrade/rpc/telegram.py", line 434, in _forcebuy,
    return command_handler(self, *args, **kwargs),
  File "/freqtrade/freqtrade/rpc/telegram.py", line 52, in wrapper,
Traceback (most recent call last):,
,
The above exception was the direct cause of the following exception:,
ccxt.base.errors.DDoSProtection: binance temporary banned: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."},
    raise DDoSProtection(self.id + ' temporary banned: ' + body),
  File "/usr/local/lib/python3.7/site-packages/ccxt/binance.py", line 1211, in handle_errors,
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response),
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 550, in fetch,
    return self.fetch(request['url'], request['method'], request['headers'], request['body']),
    response = self.fetch2(path, api, method, params, headers, body),
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 454, in fetch2,
  File "/usr/local/lib/python3.7/site-packages/ccxt/binance.py", line 1219, in request,
    return entry(_self, **inner_kwargs),
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 435, in inner,
    response = getattr(self, method)(self.extend(request, params)),
  File "/usr/local/lib/python3.7/site-packages/ccxt/binance.py", line 702, in create_order,
    amount, rate, params),
  File "/freqtrade/freqtrade/exchange/exchange.py", line 406, in create_order,
During handling of the above exception, another exception occurred:,
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/order,
    raise HTTPError(http_error_msg, response=self),
    response.raise_for_status(),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status,
  File "/usr/local/lib/python3.7/site-packages/ccxt/base/exchange.py", line 538, in fetch,
2019-08-21 14:13:27,295 - freqtrade.freqtradebot - INFO - Found no buy signals for whitelisted currencies. Trying again...,
2019-08-21 14:13:32,040 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module,
2019-08-21 14:13:26,573 - freqtrade.freqtradebot - INFO - Using Last Ask / Last Price,
2019-08-21 14:13:26,569 - freqtrade.rpc.telegram - INFO - Executing handler: _forcebuy for chat_id: 137208388,
2019-08-21 14:13:26,089 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f642f153450>, 'Connect timed out. (connect timeout=5.0)')': /bot882478358:AAFFSAdt99neSwQC7mCoUcLXwY8_rC4O8Lw/getUpdates

  ```

**Config.json**

  ```

{
    "max_open_trades": 10,
    "stake_currency": "USDT",
    "stake_amount": 50.00,

    "fiat_display_currency": "USD",
    "ticker_interval" : "1h",
    "dry_run": false,
    "trailing_stop": true,
    "trailing_stop_positive": 0.02,
    "trailing_stop_positive_offset": 0.04,
    "trailing_only_offset_is_Reached": true,
    "process_only_new_candles": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "use_order_book": false,
        "ask_last_balance": 0.0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 9
    },
    "exchange": {
        "name": "binance",
        "key": "xxxxxxxxxxxxxx",
        "secret": "xxxxxxxxxxxxx",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200
        },
        "pair_whitelist": [
            "BTC/USDT",
            "ETH/USDT",
            "XRP/USDT",
            "BNB/USDT",
            "LTC/USDT",
            "EOS/USDT",
            "NEO/USDT",
            "TRX/USDT",
            "MATIC/USDT",
            "ADA/USDT",
            "PAX/USDT",
            "BTT/USDT",
            "FET/USDT",
            "ONT/USDT",
            "XLM/USDT",
            "ETC/USDT",
            "LINK/USDT",
            "ONE/USDT",
            "VET/USDT",
            "IOTA/USDT",
            "HOT/USDT",
            "ICX/USDT",
            "ZEC/USDT",
            "QTUM/USDT",
            "ATOM/USDT",
            "ZIL/USDT",
            "BAT/USDT",
            "CELR/USDT",
            "XMR/USDT",
            "FTM/USDT",
            "MITH/USDT",
            "DASH/USDT",
            "NULS/USDT",
            "WAVES/USDT",
            "NANO/USDT",
            "IOST/USDT",

            "OMG/USDT",
            "THETA/USDT",
            "ENJ/USDT",
            "ONG/USDT"

        ],
        "pair_blacklist": [
            "ALGO/USDT"
        ]
    },
    "experimental": {
        "use_sell_signal": false,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false
    },
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "capital_available_percentage": 0.5,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "xxxxxxxx",
        "chat_id": "xxxxxxxxxx"
    },
    "initial_state": "stopped",
    "forcebuy_enable": true,
    "internals": {
        "process_throttle_secs": 5
    }
}

  ```

**Comment by xmatthias** [comment] 2019-08-21 15:20
well apparently your API key is invalid to create orders.


```
ccxt.base.errors.DDoSProtection: binance temporary banned: {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."},
  raise DDoSProtection(self.id + ' temporary banned: ' + body),
```

It may be a copy/paste error, or the keys have been generated as Read only.

best try with `/balance` ... it should give the same errormessage, if it doesn't check the binance portal if it's "read-only" or not.

Fix your API keys so `/balance` works - then `/forcebuy` should also work (unless you generated the keys with Read Only).

**Comment by xmatthias** [comment] 2019-08-31 17:17
Closing this since the problem is not with /forcebuy, but with the API keys.

Feel free to reopen if you have additional questions

**Closed by xmatthias** 2019-08-31 17:17 UTC
Labels: ccxt, question
