### ISSUE TITLE
Possibility to reverse marginal positions (long/short) at a single candle

### ISSUE THREAD

**Issue by a18** [freqtrade/freqtrade#9183] opened 2023-09-14 01:23 UTC
## Describe your environment
(if applicable)

  * Operating system: Windows10
  * Python Version: 3.10
  * CCXT version: 4.0.89
  * Freqtrade Version: 2023.6

## Describe the enhancement

Currently, Freqtrade does not seem to support a rather convenient feature: the ability to reverse a marginal position (e.g., futures) from long to short (or vice versa) within the same candle. For example, in the Binance GUI, this functionality is implemented in a single click of "Reverse" button.

The absence of this feature can be quite disappointing, as it may lead to unnecessary delays and, in some cases, financial losses when a strategy needs to wait for the next candle to open the second half of a reverse transaction. This is particularly impactful on longer timeframes, such as 1h and longer.
As a workaround some people even suggest to launch two FreqTrade instances simalteneously(!)

Additionally, this limitation can lead to confusion during backtesting, as Freqtrade, without issuing any warning in the log, will ignore "Enter long" signal that is placed in the same candle with "Exit short" signal, despite the documentation suggesting that such cases are not [forbidden](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals):

> The following rules apply, and entry signals will be ignored if more than one of the 3 signals is set:
> - enter_long -> exit_long, enter_short
> - enter_short -> exit_short, enter_long

(according to this, enter_long should not conflict with exit_short)

Anyway, thanks for the great product!!

**Comment by xmatthias** [comment] 2023-09-14 05:14
in live, it's an artificial limitation (to some degree) - which could be fixed with 1-2 lines.

In backtesting, this is however built into the execution logic, which automatically locks pairs for the duration of the candle (since we check for entries before exits).
Reversing this logic will introduce other limitations (you could no longer exit on the entry candle).

This leaves the possibility to check for "entries -> exits -> entries" - but then the 2nd entry will no longer be able to exit within this candle - so the 2nd entry behaves different to the initial entry (so we'd need to check "entries -> exits -> entries -> exits" - but even here it's limited, as you could have more than 2 entries per candle i guess).

This would introduce semi-infinite loops to backtesting - with a performance impact that in my opinion doesn't justify the usefulnes.

If you have some ideas on HOW this can be implemented in backtesting - share your ideas and i'm happy to look at it (ideally to review a PR for it).

Otherwise, i don't see this as something we'll look at anytime soon (most likely never).

**Comment by a18** [comment] 2023-09-14 08:28
Thanks for the very informative comment! I feel, this question is being discussed for a long time.

Could you, please, elaborate the phrase "you could have more than 2 entries per candle i guess"?
I thought that in a strategy we just append to the "dataframe" these 4 columns: "enter_long", "enter_short", "exit_long", "exit_short", that could have only 0 and 1 values, resulting in 16 combinations, with most of them treated as conflicting according to the current quite reasonable documentation [rules](https://www.freqtrade.io/en/latest/strategy-customization/#colliding-signals).

**Comment by xmatthias** [comment] 2023-09-14 09:01
That's for static / dataframe based signals - yes - though the 16 combinations are not really relevant, as most would conflict.

but for all other (usually more common) exit methods (stoploss, roi, custom_exit, ...) - there's no such thing as collisions, they're always enacted (There's exceptions to this, irrelevant for this issue).
so while you can't have the case of "entry, exit, enter short" on the same candle (conflicting signals, the initial entry would be ignored) - it still doesn't change the problematic.

* we must check for entries first, followed by exits (this ensures we are able to exit within that candle on a non-dataframe based exit).
* To facilitate an entry AFTER the exit within the same candle, we must check for entries again - followed by checking for exits again.

Assuming 1h candles, we're on the 11h candle (stoploss is taken as sample, all above mentioned non-DF exit methods are treated equally).

The min. scenarios you'd aim to cover are
* Trade opened at 11, stays open
* Trade opened at 11, exits on stop within that same candle
* trade opened at 9, exits on stoploss at 11, entry in other direction in same candle (stays open)
* trade opened at 9, exits on stoploss at 11, entry in other direction in same candle (stays open), another stop on same candle
* trade opened at 9, exits on stoploss at 11, entry in other direction in same candle - but is ignored because another pair was ahead in the pairlist and filled this trade slot (just because you have a close with entry signal doesn't mean this entry is the next one to look at)

Scenarios to ignore due to conflicts (that's the easy part)
* Trade opened at 11, exits on stop within that candle,  entry in other direction in same candle

That's at minimum 2 iterations you'd have for each candle, each containing
* loop through ALL pairs (respecting pairlist sequence)
* full entry logic
* full exit logic
* all order handling, in cases where orders don't immediately fill
* splits into detail timeframe eventually (not sure how this needs to be handled)

You could also have 5 trades (on different pairs) exiting at the same candle, with 5 new trades entering, 3 on the same pair reversing position, 2 on new pairs - and one of the "reverse position" signals being ignored, as the new pairs are further in front  in the pairlist.

All of the above logic currently assumes that it's executed exactly once per candle - where executing it twice will have
* severe, negative implications on performance
* avoid calling the same callback twice for no reason (not just for performance reasons, but also because people tend to have side-effects in their callbacks)
* ...


As this will only benefit a rather small percentage of users, all of this needs to be implemented in a way that's not impacting performance negatively for users that don't need this. 
Good luck :)

**Comment by a18** [comment] 2023-09-14 09:24
Aha, as I supposed, I just have not thought about "non-DF" exits. You are right, the things seem rather complex.

Currently I don't have enough expertise to suggest working concept/PR, but here's a table of these 16 combinations with corresponding actions, that could seem reasonable (maybe, for future implementations/fixes). Please, feel free to edit/copy it, etc.
Terminology:
SC (Soft collision) - the combination is strange, but do NOT result in missing a trade.
HC (Hard collision) - the combination is strange, and could result in missing of a trade.
CurPos - current position

|id| enter_long | enter_short | exit_long | exit_short | Action for the next candle |
|--------|--------|--------|--------|--------|--------|
|1| 0 | 0 | 0 | 0 | None |
|2| 0 | 0 | 0 | 1 | CurPos is None -> Log SC<br>CurPos is Long -> Log HC<br>CurPos is Short -> Close short |
|3| 0 | 0 | 1 | 0 | CurPos is None -> Log SC<br>CurPos is Long -> Exit long<br>CurPos is Short -> Log HC |
|4| 0 | 0 | 1 | 1 | CurPos is None -> Log SC<br>CurPos is Long -> Exit long and log SC<br>CurPos is Short -> Exit short and log SC |
|5| 0 | 1 | 0 | 0 | CurPos is None -> Enter short<br>CurPos is Long -> Log HC<br>CurPos is Short -> Log SC |
|6| 0 | 1 | 0 | 1 | Log HC |
|7| 0 | 1 | 1 | 0 | CurPos is None -> Enter short + log SC<br>CurPos is Long -> Exit long + enter short<br>CurPos is Short -> Log SC |
|8| 0 | 1 | 1 | 1 | Log HC |
|9| 1 | 0 | 0 | 0 | CurPos is None -> Enter long<br>CurPos is Long -> Log SC<br>CurPos is Short -> Log HC |
|10| 1 | 0 | 0 | 1 | CurPos is None -> Enter long + log SC<br>CurPos is Long -> Log SC<br>CurPos is Short -> Exit short + enter long |
|11| 1 | 0 | 1 | 0 | Log HC |
|12| 1 | 0 | 1 | 1 | Log HC |
|13| 1 | 1 | 0 | 0 | Log HC |
|14| 1 | 1 | 0 | 1 | Log HC |
|15| 1 | 1 | 1 | 0 | Log HC |
|16| 1 | 1 | 0 | 1 | Log HC |

EDIT: as there are "non-DF" exits, the word "strange" is not too good, as the case could be quite normal.

**Comment by xmatthias** [comment] 2023-09-14 09:29
Unfortunately that table is mostly useless (at least for this issue implementation) - as it ignores non-dataframe behavior (which is where most of the complexity is introduced, as you can no longer predict where a trade is going to exit).
It's essentially just "exploding" the collision rules.

as long as we stick to "dataframe only" behaviors - behavior is clear - but we can't.

One thing to note: 
Backtesting will not write logs for random actions within the simulation. Rendering Terminal output is rather slow - so adding "logging" here would be quite bad for performance.

**Comment by a18** [comment] 2023-09-14 09:41
Yes, logging of SC (soft-collisions) could be reasonable only on -v (or -vv) versbosity levels or just skipped. But logging of HC (hard collisions) as warnings - in my opinion, is vital as they report principal strategy inconsistencies to the user.

**Comment by a18** [comment] 2023-09-14 09:57
Here's the version 2 of the table - now including "non-DF" exits.

Terminology:
SC (Soft collision) - the combination is strange, but do NOT result in missing a trade.
HC (Hard collision) - the combination is strange, and could result in missing of a trade.
CurPos - current position ("Exited" means that the position was closed by stop loss, etc.)

|id| enter_long | enter_short | exit_long | exit_short | Action for the next candle |
|--------|--------|--------|--------|--------|--------|
|1| 0 | 0 | 0 | 0 | None |
|2| 0 | 0 | 0 | 1 | CurPos is Exited -> ok<br>CurPos is None -> Log SC<br>CurPos is Long -> Log HC<br>CurPos is Short -> Close short |
|3| 0 | 0 | 1 | 0 | CurPos is Exited -> ok<br>CurPos is None -> Log SC<br>CurPos is Long -> Exit long<br>CurPos is Short -> Log HC |
|4| 0 | 0 | 1 | 1 | CurPos is Exited or None -> Log SC<br>CurPos is Long -> Exit long and log SC<br>CurPos is Short -> Exit short and log SC |
|5| 0 | 1 | 0 | 0 | CurPos is Exited or None -> Enter short<br>CurPos is Long -> Log HC<br>CurPos is Short -> Log SC |
|6| 0 | 1 | 0 | 1 | Log HC |
|7| 0 | 1 | 1 | 0 | CurPos is Exited -> Enter short<br>CurPos is None -> Enter short + log SC<br>CurPos is Long -> Exit long + enter short<br>CurPos is Short -> Log SC |
|8| 0 | 1 | 1 | 1 | Log HC |
|9| 1 | 0 | 0 | 0 | CurPos is Exited or None -> Enter long<br>CurPos is Long -> Log SC<br>CurPos is Short -> Log HC |
|10| 1 | 0 | 0 | 1 | CurPos is Exited ->Enter long<br> CurPos is None -> Enter long + log SC<br>CurPos is Long -> Log SC<br>CurPos is Short -> Exit short + enter long |
|11| 1 | 0 | 1 | 0 | Log HC |
|12| 1 | 0 | 1 | 1 | Log HC |
|13| 1 | 1 | 0 | 0 | Log HC |
|14| 1 | 1 | 0 | 1 | Log HC |
|15| 1 | 1 | 1 | 0 | Log HC |
|16| 1 | 1 | 0 | 1 | Log HC |


Hope this could be useful for further discussions sometimes in the future.

**Comment by maddrid** [comment] 2024-01-21 09:51
my  2  cents  here : the ability to reverse a marginal position (e.g., futures) from long to short (or vice versa) within the same candle  should  be  handled    from config  first .. 
    reverse_position = false ( default  for   99 % use cases) ..
   but in some  cases , let  the  user   decide  about  reverse_position  and  implement  his  "strategy reversion "   dependent  on the  exchange (  some  require  2  orders (  close  the current  position,  and  second  order  to  take  the opposite side ) other   manage  the  reversion on the  exchange  level
      reverse_position = true 
  no  more  hacking  the  core and  nasty inventions  to  do  a simple  reversion

**Comment by MF1B** [comment] 2024-02-05 21:22
Wouldn't it be a simple case of processing the exities first and then the entries?

**Comment by stash86** [comment] 2024-02-05 22:56
Dry/live, yes it's simple.

Backtest? Read the replies above. Ofc if you think you can make it work, please do open a PR

**Comment by MF1B** [comment] 2024-02-06 00:49
I'm sorry! I didn't know that backtesting was more important than dry/live. Could we consider the open candle, after the signal, as the closing/opening value, for backtest purposes only, not being as precise as necessary?

**Comment by stash86** [comment] 2024-02-06 01:03
once again, read above replies. Matthias already explained the issues. If you think you can provide the solution, please do open a PR.

If you only care about dry/live, you can manually unlock the pair. You can read the docs on how to do that

**Closed as completed** 2024-11-01 08:29 UTC
Labels: Enhancement, Non-spot

**Comment by koistya** [comment] 2024-12-19 21:48
@xmatthias it seems to be reversing positions in backtesting mode but not in live trading mode, producing very different results.

Is there a way to make Freqtrade reverse positions when entry and exit signals are on the same candle? It currently handles just the exit signal but ignores the entry signal.

![Image](https://github.com/user-attachments/assets/d043fff9-6081-465e-afd9-25b9169168bd)

```
freqtrade.freqtradebot - Exit for CORE/USDT:USDT detected. Reason: exit_signal Tag: 
```

**Comment by xmatthias** [comment] 2024-12-20 05:18
@koistya the only thing preventing a reversal in live/dry from a freqtrade point of view is the automatic auto-lock - which was removed in 2024.11. You could reverse positions before by manually deleting that lock again - which is a workaround that was used by some strategies in the past successfully.

However - that's not the only thing that can prevent an actual trade entry - and regular "doesn't enter" reasons still apply
a non-exhaustive list of these (there's probably more - it's still early):
* configured protections apply - and lock the pair in both trade directions (`only_per_side=False`) - you can backtest this - but it's opt-in.
* ignore_buying_expired_candle_after is configured and your exit happens after `ignore_buying_expired_candle_after` - so the entry is assumed as expired
* your signal has lookahead bias - so it's not actually there when the trade exits - only when looking at the charts later


Your log is pretty much pointless i'm afraid - it's an exit _signal-_ sure - but did the trade actually exit? a new entry would only apply once the order actually fills and the trade closes. (leaving aside the fact that you can have exits without an entry signal 😆 )

**Comment by koistya** [comment] 2024-12-20 13:28
@xmatthias 
- My strategy is straightforward (e.g. MA crossover, no room for errors)
- Lookahead analysis shows no basis
- In the logs, the entry signal is not mentioned anywhere even though it shows up on the chat
- I don't have protection rules set in my strategy

What do you think if we modify `handle_trade` method to check for an entry signal after executing an exit:

```python
if exit_:
    logger.info(f"Exit signal detected for {trade.pair}. Exiting trade.")
    self.execute_trade_exit(trade, trade.close_rate, exit_tag=exit_tag)
    # Check for entry signal after exit
    (signal, enter_tag) = self.strategy.get_entry_signal(
        trade.pair, self.strategy.timeframe, analyzed_df
    )
    if signal:
        logger.info(f"Entry signal detected for {trade.pair} after exit. Entering trade.")
        self.create_trade(trade.pair)
    return True
```

This way, the bot will check for an entry signal immediately after exiting a trade and create a new trade if an entry signal is detected.

--- OR ---

Maybe we should replace this part of the `process()` method:

```python
# First process current opened trades (positions)
self.exit_positions(trades)

# Then looking for entry opportunities
if self.get_free_open_trades():
    self.enter_positions()
```

With the following logic:

```python
# Handle trades with both exit and entry signals on the same candle
for trade in trades:
    analyzed_df, _ = self.dataprovider.get_analyzed_dataframe(trade.pair, self.strategy.timeframe)
    (entry_signal, exit_signal, exit_tag) = self.strategy.get_exit_signal(
        trade.pair, self.strategy.timeframe, analyzed_df, is_short=trade.is_short
    )
    
    if entry_signal and exit_signal:
        logger.info(f"Handling reverse position for {trade.pair} on the same candle.")
        exit_rate = self.exchange.get_rate(trade.pair, side="exit", is_short=trade.is_short)
        if self._check_and_execute_exit(trade, exit_rate, entry_signal, exit_signal, exit_tag):
            logger.info(f"Exited trade {trade.pair}, attempting reverse entry.")
            self.enter_positions()  # Attempt to open a reverse position immediately

# Handle remaining exit signals
self.exit_positions(trades)

# Handle remaining entry signals
if self.get_free_open_trades():
    self.enter_positions()
```

**Explanation**

1. **Sequential Processing**: The updated logic first checks for trades with both exit and entry signals on the same candle and processes them.
2. **Reverse Position Handling**: After exiting a trade, it attempts to open a reverse position by calling self.enter_positions().
3. **Separate Processing**: Remaining exit signals are handled separately to avoid conflicts. Finally, the bot processes any new entry opportunities.

**Comment by xmatthias** [comment] 2024-12-20 15:43
@koistya neither.

i don't see anything wrong for the moment - and i'll not implement random changes without proof of there being a problem.

**Comment by xmatthias** [comment] 2024-12-21 13:23
To reiterate what i said above, i did a few tests - with the following outcome (re-posting here from the PR for better re-findability).

It's not a problem of freqtrade - and the logic there works perfectly fine.
on a 5 min strategy (designed to explicitly test this) - i get the following trades.

As you can see - the exit / entry is within about a second - each time switching to the other direction.

![image](https://github.com/user-attachments/assets/90042086-8d2d-439a-983a-b635053cc827)

---

As such the conclusion above was correct - it's a bug in your strategy.
While we can surely help you with that - this is not the right place to analyze your personal strategy.

As such, please open a new issue, posting your versions, logs, and a (ideally reduced) strategy where you're experiencing this.

**Comment by koistya** [comment] 2024-12-21 22:52
@xmatthias in this strategy, do you have entry and exit signals on the same candle? Also, are you testing it in live mode?

Could you please paste the screenshot of how the reversal looks on the chart. On my end it looks like this:

![Image](https://github.com/user-attachments/assets/f4631b2c-576c-489e-98e2-fe762c6ff853)

There are both enter and exit signals on the last candle, and the bot just closes the existing position without opening a reversed one. I'd like to see how the normal operation looks like to compare with my results.

**Comment by xmatthias** [comment] 2024-12-22 07:20
@koistya i'm not sure what you're after.

My strategy is aimed towards trying to reproduce something you claim is a problem (spoiler: it's not) quickly.
I don't have time to run a strategy for days just to proof to you that things are working.

As such, it's neither a realistic strategy - nor something that would even be backtestable.

For the test yesterday, i've been populating both exit_long and enter_short (and viceversa) signals for the whole duration of the timeframe - aligned to each other (see `populate_exit_trend()`).
For this test, i used the 2nd part - so i force-enter the first trade in one direction, and the next candle will be auto-reversed.
On smaller candles, it's more difficult to see - and the chart won't work as it's changing for the whole duration.

The commented part (just switch what's commented in the entry function) is how i actually tested it initially over a longer period of time - but didn't want to waste my time on. 

With this - whenever the last exit order **fills** (this is important - it's not the signal that counts, but the actual closure) - the bot immediately opens a new position in the other direction.
I posted a few reasons above - pricing should be included in these reasons - as that can cause your order to fill at a later point.

<details><summary>Details</summary>
<p>

``` python
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # generate entry signals based on indicator values
        dataframe.loc[:, ["enter_short", "enter_tag"]] = (0, None)
        dataframe.loc[:, ["enter_long", "enter_tag"]] = (0, None)
        # dataframe.loc[
        #     qtpylib.crossed_below(dataframe["rsi"], 30), ["enter_long", "enter_tag"]
        # ] = (1, "long")
        # dataframe.loc[
        #     qtpylib.crossed_above(dataframe["rsi"], 70), ["enter_short", "enter_tag"]
        # ] = (1, "short")

        trades = Trade.get_trades_proxy(pair=metadata["pair"], is_open=True)
        if trades:
            trade = trades[-1]
            dataframe.loc[
                # qtpylib.crossed_below(dataframe["rsi"], 30),
                :,
                [
                    f"enter_{'long' if trade.trade_direction == 'short' else 'short'}",
                    "enter_tag",
                ],
            ] = (1, "reverse")

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # generate exit signals based on indicator values
        dataframe.loc[:, "exit_long"] = dataframe.loc[:, "enter_short"]
        dataframe.loc[(dataframe["exit_long"] == 1), "exit_tag"] = "switch_short"
        dataframe.loc[:, "exit_short"] = dataframe.loc[:, "enter_long"]
        dataframe.loc[(dataframe["exit_short"] == 1), "exit_tag"] = "switch_long"

        return dataframe

```

</p>
</details> 

---

For me - this topic / discussion with you is concluded. 
I've wasted a ton of time trying to proof to you that it's working - while you only claim "it's not working for me" - without even sharing logs or any detail. 
This is touching the line of trolling - please carefully consider what you're posting here next.

If you're still having problem, it's your config (or rather, a combination of your configuration and strategy).

As i said above - if you're still having problem please open a new issue, filling out the issue template, posting logs, config (no keys!) and a (eventually reduced) strategy where you're having problems with, so we can help you.

It's up to you to take up this offer or not (strategies can eventually also be shared in private) - however i'll not partecipate in random poking around. That's just wasting my time. 

Thanks for your understanding.

**Comment by rcpislr** [comment] 2024-12-26 17:15
> To reiterate what i said above, i did a few tests - with the following outcome (re-posting here from the PR for better re-findability).
> 
> It's not a problem of freqtrade - and the logic there works perfectly fine. on a 5 min strategy (designed to explicitly test this) - i get the following trades.
> 
> As you can see - the exit / entry is within about a second - each time switching to the other direction.
> 
> ![image](https://github.com/user-attachments/assets/90042086-8d2d-439a-983a-b635053cc827)
> 
> As such the conclusion above was correct - it's a bug in your strategy. While we can surely help you with that - this is not the right place to analyze your personal strategy.
> 
> As such, please open a new issue, posting your versions, logs, and a (ideally reduced) strategy where you're experiencing this.

Please please please may you share this switching strategy that you wrote it wistches positions according to profit (plus or minus) or any other condition. 
i wrote under another subject but you close it :( please i need this strategy... 
i wrote a custom script that switches position and it runs only one pair. i wanna appyl this logic in freqtrade . i am working on it days and days...

**Comment by xmatthias** [comment] 2024-12-26 19:15
@rcpislr i wrote in the pull request and i'll repeat it here - that's not how freqtrade position switching works.
My code reproduces the position switching independently - but it's not applicable to a realistic strategy.

please learn how freqtrade works, and you'll understand how position switching works. There's however no free lunch here - so please stop spamming here - or i'll have to prevent you from interacting with this repository.
