### ISSUE TITLE
DrawDown <-> Stake

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#5892] opened 2021-11-14 21:24 UTC
Hi!

the current drawdown calculation does not take into account, that the stake amount could be dynamic.
e.g. in backtesting either the col absolute or relative profit is taken. with dynamic stake 10 trades sum 10% relative profit, can be different to 10 other trades with 10% profit, it is a difference if 10 trades stake 1000 usd fail, or 10 trades stake 1 usd fail.

currently:
1% 10 USD
1% 10 USD
1% 1000 USD

generate the same drawdown as:
1% 10 USD
1% 10 USD
1% 10 USD

so currently using stake unlimited and 1 trades produces the same drawdown as stake fixed 1 trades, which is IMHO wrong and missleading.

greetings

**Comment by xmatthias** [comment] 2021-11-15 05:39
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

Please use the search before opening new issues to find if your question / topic has already been brought up.

This is a duplicate of #5167 - you can find explanations on how it's calculated there.
As mentioned there, i'm open to suggestion how to calculate this differently.

I'm going to close this as duplicate of #5167 - feel free to comment there if you have suggestions on a better way to calculate this drawdown.

**Closed as completed by xmatthias** 2021-11-15 05:39 UTC
Labels: Duplicate, Question
