### ISSUE TITLE
Don't cancel partial filled buy order if minimum order amount hasn't been reached.

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#3622] opened 2020-07-24 08:19 UTC
# Describe the enhancement

Don't cancel partial filled buy orders if the minimum exchange order amount hasn't been reached.
I use a stake amount of 15 USDT, which is close to the minimum order amount of 10 USDT on Binance. Whenever a buy order is partially fullfilled with less than < 10 USDT, the bot can not only sell this pair anymore, but the user will have to manually take care of it, sell it on the exchange itself and delete it from the database.

Of course the discussion point would be then: there would be cases where it doesn't get fulfilled, because the price has gone too far up/or down, do you just leave it open for days? I don't think that's the best solution, but maybe for a couple of hours, before cancelling it?

**Comment by xmatthias** [comment] 2020-07-24 08:27
This is a duplicate of #2877.

the problem with "ever" cancelling these is that they leave you with binance dust - unsellable assets you can only create to BNB.

Now there are options to convert to BNB - but that's binance-specific - but the problem exists on other exchanges (kraken, Ftx) just in the same way - which don't have a way to handle these assets correctly.

**Comment by Theagainmen** [comment] 2020-07-24 10:28
`Please use the search function to find related / similar issues before opening new ones.` Yes, but the one you linked is more of described as a bug, and I didn't really see anything there about keeping these orders open until MIN_NOTIONAL has been reached (only the last comment, but no one has ever responded to that). 

Also I tried the workaround, but that's no solution for me, it always takes around 5 seconds to 2 minutes before most of my orders gets fulfilled, I haven't had 1 FOK order that got fulfilled. 

`the problem with "ever" cancelling these is that they leave you with binance dust - unsellable assets you can only create to BNB.` I'm not sure what this has to do with my enhancement, I'm proposing the exact opposite, to NOT cancel them. I'm also not saying to convert it to BNB. Because this is the current behaviour of the bot, it cancels them, which leaves you with dust, with this enhancement it will try to prevent this.

**Comment by yagmot** [comment] 2021-04-22 07:32
@xmatthias Has this "enhancement" been incorporated into a recent commit? I updated to `develop-9f6f3e0` this morning and saw this just now:

```
2021-04-22 16:18:11,822 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for ETH/USDT with stake_amount: 268.42753567072805 ...
2021-04-22 16:18:12,350 - freqtrade.freqtradebot - INFO - Buy price from orderbook Ask side - top 1 order book buy rate 2453.25000000
2021-04-22 16:18:12,857 - freqtrade.wallets - INFO - Wallets synced.
2021-04-22 16:18:12,859 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 3329, 'type': buy, 'exchange': 'Kucoin', 'pair': 'ETH/USDT', 'limit': 2453.25, 'order_type': 'limit', 'stake_amount': 268.42753567072805, 'stake_currency': 'USDT', 'fiat_currency': 'JPY', 'amount': 0.1094171, 'open_date': datetime.datetime(2021, 4, 22, 7, 18, 12, 503984), 'current_rate': 2453.25}
2021-04-22 16:18:15,818 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3329, pair=ETH/USDT, amount=0.10941710, open_rate=2453.25000000, open_since=2021-04-22 07:18:12)
2021-04-22 16:18:19,294 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3329, pair=ETH/USDT, amount=0.10941710, open_rate=2453.25000000, open_since=2021-04-22 07:18:12)
2021-04-22 16:18:24,173 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3329, pair=ETH/USDT, amount=0.10941710, open_rate=2453.25000000, open_since=2021-04-22 07:18:12)
2021-04-22 16:18:24,174 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=3329, pair=ETH/USDT, amount=0.10941710, open_rate=2453.25000000, open_since=2021-04-22 07:18:12) [buy]: 0.2684275 USDT - rate: 0.001
2021-04-22 16:18:24,174 - freqtrade.persistence.models - INFO - Updating trade (id=3329) ...
2021-04-22 16:18:24,175 - freqtrade.persistence.models - INFO - LIMIT_BUY has been fulfilled for Trade(id=3329, pair=ETH/USDT, amount=0.10941710, open_rate=2453.25000000, open_since=2021-04-22 07:18:12).
2021-04-22 16:18:24,184 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 3329, 'type': buy_fill, 'exchange': 'Kucoin', 'pair': 'ETH/USDT', 'open_rate': 2453.25, 'stake_amount': 268.42753567072805, 'stake_currency': 'USDT', 'fiat_currency': 'JPY', 'amount': 0.1094171, 'open_date': datetime.datetime(2021, 4, 22, 7, 18, 12, 503984)}
```

But /balance shows this:
```
ETH:
 Available: 0.03634860
 Balance: 0.03634860
 Pending: 0.00000000
 Est. USDT: 89.052
```

I figured I should be seeing a message that the buy was partially filled, but the bot seems to think it was completely filled.

**Closed** 2021-05-22 08:17 UTC
Labels: Enhancement

**Comment by abdellahaski** [comment] 2023-02-08 03:05
I'm not sure what happened to this trade is related to this or not.
I trade was partially closed and the remaining amount is less than the minimum (MIN_NOTIONAL) so it failed trying to close that too
here are the logs:
```

2023-02-07 17:51:21,264 - freqtrade.freqtradebot - INFO - Exit for ASTR/BUSD detected. Reason: trailing_stop_loss
2023-02-07 17:51:21,781 - freqtrade.wallets - INFO - Wallets synced.
2023-02-07 17:51:22,054 - freqtrade.exchange.exchange - INFO - API create_order: {'info': {'symbol': 'ASTRBUSD', 'orderId': '33070791', 'orderListId': '-1', 'clientOrderId': 'x-R4BD3S82e84f82bd3182150399a77f', 'transactTime': '1675792281923', 'price': '0.06330000', 'origQty': '488.50000000', 'executedQty': '359.70000000', 'cummulativeQuoteQty': '22.76901000', 'status': 'EXPIRED', 'timeInForce': 'IOC', 'type': 'LIMIT', 'side': 'SELL', 'workingTime': '1675792281923', 'fills': [{'price': '0.06330000', 'qty': '359.70000000', 'commission': '0.00005166', 'commissionAsset': 'BNB', 'tradeId': '2276807'}], 'selfTradePreventionMode': 'NONE'}, 'id': '33070791', 'clientOrderId': 'x-R4BD3S82e84f82bd3182150399a77f', 'timestamp': 1675792281923, 'datetime': '2023-02-07T17:51:21.923Z', 'lastTradeTimestamp': 1675792281923, 'symbol': 'ASTR/BUSD', 'type': 'limit', 'timeInForce': 'IOC', 'postOnly': False, 'reduceOnly': None, 'side': 'sell', 'price': 0.0633, 'triggerPrice': None, 'amount': 488.5, 'cost': 22.76901, 'average': 0.0633, 'filled': 359.7, 'remaining': 128.8, 'status': 'expired', 'fee': {'currency': 'BNB', 'cost': 5.166e-05}, 'trades': [{'info': {'price': '0.06330000', 'qty': '359.70000000', 'commission': '0.00005166', 'commissionAsset': 'BNB', 'tradeId': '2276807'}, 'timestamp': None, 'datetime': None, 'symbol': 'ASTR/BUSD', 'id': '2276807', 'order': None, 'type': None, 'side': None, 'takerOrMaker': None, 'price': 0.0633, 'amount': 359.7, 'cost': 22.76901, 'fee': {'cost': 5.166e-05, 'currency': 'BNB'}, 'fees': [{'cost': 5.166e-05, 'currency': 'BNB'}]}], 'fees': [{'currency': 'BNB', 'cost': 5.166e-05}], 'stopPrice': None}
2023-02-07 17:51:22,055 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 37, 'exchange': 'Binance', 'pair': 'ASTR/BUSD', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.0633, 'order_rate': 0.0633, 'order_type': 'limit', 'amount': 488.5, 'open_rate': 0.0614, 'close_rate': 0.0633, 'current_rate': 0.0633, 'profit_amount': 0.92815, 'profit_ratio': 0.03094463, 'buy_tag': 'ewo1', 'enter_tag': 'ewo1', 'sell_reason': 'trailing_stop_loss', 'exit_reason': 'trailing_stop_loss', 'open_date': datetime.datetime(2023, 2, 7, 16, 55, 22, 218694), 'close_date': datetime.datetime(2023, 2, 7, 17, 51, 22, 55844), 'stake_amount': 29.9939, 'stake_currency': 'BUSD', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2023-02-07 17:51:22,464 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=37, pair=ASTR/BUSD, amount=488.50000000, is_short=False, leverage=1.0, open_rate=0.06140000, open_since=2023-02-07 16:55:22)
2023-02-07 17:51:22,753 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=37, pair=ASTR/BUSD, amount=488.50000000, is_short=False, leverage=1.0, open_rate=0.06140000, open_since=2023-02-07 16:55:22) [sell]: 5.166e-05 BNB - rate: 0.000751
2023-02-07 17:51:22,754 - freqtrade.persistence.trade_model - INFO - Updating trade (id=37) ...
2023-02-07 17:51:22,754 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=37, pair=ASTR/BUSD, amount=488.50000000, is_short=False, leverage=1.0, open_rate=0.06140000, open_since=2023-02-07 16:55:22).
2023-02-07 17:51:23,273 - freqtrade.wallets - INFO - Wallets synced.
2023-02-07 17:51:23,276 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 37, 'exchange': 'Binance', 'pair': 'ASTR/BUSD', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.0633, 'order_rate': 0.0633, 'order_type': '', 'amount': 359.7, 'open_rate': 0.0614, 'close_rate': 0.0633, 'current_rate': None, 'profit_amount': 0.66633047, 'profit_ratio': 0.03017039, 'buy_tag': 'ewo1', 'enter_tag': 'ewo1', 'sell_reason': 'trailing_stop_loss', 'exit_reason': 'trailing_stop_loss', 'open_date': datetime.datetime(2023, 2, 7, 16, 55, 22, 218694), 'close_date': datetime.datetime(2023, 2, 7, 17, 51, 23, 276201), 'stake_amount': 7.90832, 'stake_currency': 'BUSD', 'fiat_currency': 'USD', 'sub_trade': True, 'cumulative_profit': 0.66633047}
2023-02-07 17:51:24,272 - freqtrade.wallets - INFO - Wallets synced.
2023-02-07 17:51:24,537 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2023.1', state='RUNNING'
2023-02-07 17:51:26,672 - freqtrade.freqtradebot - INFO - Exit for ASTR/BUSD detected. Reason: trailing_stop_loss
2023-02-07 17:51:27,190 - freqtrade.wallets - INFO - Wallets synced.
2023-02-07 17:51:27,461 - freqtrade.freqtradebot - WARNING - Unable to exit trade ASTR/BUSD: Could not create limit sell order on market ASTR/BUSD. Tried to sell amount 128.8 at rate 0.0632. Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
2023-02-07 17:51:31,710 - freqtrade.freqtradebot - INFO - Exit for ASTR/BUSD detected. Reason: trailing_stop_loss
2023-02-07 17:51:32,225 - freqtrade.wallets - INFO - Wallets synced.
2023-02-07 17:51:32,491 - freqtrade.freqtradebot - WARNING - Unable to exit trade ASTR/BUSD: Could not create limit sell order on market ASTR/BUSD. Tried to sell amount 128.8 at rate 0.0632. Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
2023-02-07 17:51:36,716 - freqtrade.freqtradebot - INFO - Exit for ASTR/BUSD detected. Reason: trailing_stop_loss
2023-02-07 17:51:37,233 - freqtrade.wallets - INFO - Wallets synced.
2023-02-07 17:51:37,502 - freqtrade.freqtradebot - WARNING - Unable to exit trade ASTR/BUSD: Could not create limit sell order on market ASTR/BUSD. Tried to sell amount 128.8 at rate 0.0632. Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
2023-02-07 17:51:41,712 - freqtrade.freqtradebot - INFO - Exit for ASTR/BUSD detected. Reason: trailing_stop_loss
2023-02-07 17:51:42,225 - freqtrade.wallets - INFO - Wallets synced.


```

**Comment by xmatthias** [comment] 2023-02-08 05:31
It's not related. 
We can't control fill size on orders which are using exotic time-in-force settings - which cause the exchange to cancel the order "at will".
There's no automatic handling for this - and there probably never will be - as depending on the amount left, the better option is either to "buy some small stake again, to make it fully sellable" - or "forget about it and convert to BNB.


You can probably get out of this trade by manually buying a bit through forcebuy on the same pair (which will cause a DCA order - if the pair still has an open trade).

**Comment by abdellahaski** [comment] 2023-02-08 13:29
Thanks @xmatthias for the information
