### ISSUE TITLE
OSX Quickstart does not work

### ISSUE THREAD

**Issue by rti-admin** [freqtrade/freqtrade#4785] opened 2021-04-22 17:13 UTC
I get the following error:

 ERROR: Command errored out with exit status 1:
     command: /Users/...../freqtrade/freqtrade/.env/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zl/d5ylw0zj66548j2gcssw8z4r0000gn/T/pip-install-sb9c7fy0/tables_80abb5dbae9f43f4ba9e3a9529f8eef3/setup.py'"'"'; __file__='"'"'/private/var/folders/zl/d5ylw0zj66548j2gcssw8z4r0000gn/T/pip-install-sb9c7fy0/tables_80abb5dbae9f43f4ba9e3a9529f8eef3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zl/d5ylw0zj66548j2gcssw8z4r0000gn/T/pip-pip-egg-info-5e2lmket
         cwd: /private/var/folders/zl/d5ylw0zj66548j2gcssw8z4r0000gn/T/pip-install-sb9c7fy0/tables_80abb5dbae9f43f4ba9e3a9529f8eef3/
    Complete output (7 lines):
    clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
    * Using Python 3.9.2 (default, Mar 26 2021, 23:22:38)
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1
ERROR: No matching distribution found for tables==3.6.1

**Comment by xmatthias** [comment] 2021-04-22 17:16
This is not a problem with freqtrade itself, but with the fact that some dependencies (tables) do not provide wheels for macos with python 3.9.

best use python 3.8 for the time being until tables catches on (https://github.com/PyTables/PyTables)  - or better yet, use the docker images from the [docker quickstart](https://www.freqtrade.io/en/stable/docker_quickstart/) guide to work around this.

It's technically also a duplicate of #4495 ...

It's also mentioned in the troubleshooting docs at the bottom of the install page [here](https://www.freqtrade.io/en/stable/installation/#macos-installation-error-with-python-39).

**Comment by rti-admin** [comment] 2021-04-22 19:31
sorry bro.. couldn't find a solution to the issue. trying out your solution right now

**Comment by rti-admin** [comment] 2021-04-22 19:50
**there seems to be a problem with the docker image:**

2021-04-22 19:47:53,946 - freqtrade.worker - INFO - Starting worker docker-0d2457cd

2021-04-22 19:47:53,946 - freqtrade.configuration.configuration - INFO - Using config: config.json ...

2021-04-22 19:47:53,946 - freqtrade.commands.trade_commands - ERROR - Config file "config.json" not found! Please create a config file or check whether it exists.

2021-04-22 19:47:53,947 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Traceback (most recent call last):

File "/freqtrade/freqtrade/configuration/load_config.py", line 58, in load_config_file

with open(path) if path != '-' else sys.stdin as file:

FileNotFoundError: [Errno 2] No such file or directory: 'config.json'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading

worker = Worker(args)

File "/freqtrade/freqtrade/worker.py", line 35, in __init__

self._init(False)

File "/freqtrade/freqtrade/worker.py", line 49, in _init

self._config = Configuration(self._args, None).get_config()

File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config

self.config = self.load_config()

File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config

config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))

File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files

config = deep_merge_dicts(load_config_file(path), config)

File "/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file

raise OperationalException(

freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.

2021-04-22 19:48:22,390 - freqtrade.worker - INFO - Starting worker docker-0d2457cd

2021-04-22 19:48:22,390 - freqtrade.configuration.configuration - INFO - Using config: config.json ...

2021-04-22 19:48:22,390 - freqtrade.commands.trade_commands - ERROR - Config file "config.json" not found! Please create a config file or check whether it exists.

2021-04-22 19:48:22,391 - freqtrade.commands.trade_commands - ERROR - Fatal exception!

Traceback (most recent call last):

File "/freqtrade/freqtrade/configuration/load_config.py", line 58, in load_config_file

with open(path) if path != '-' else sys.stdin as file:

FileNotFoundError: [Errno 2] No such file or directory: 'config.json'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading

worker = Worker(args)

File "/freqtrade/freqtrade/worker.py", line 35, in __init__

self._init(False)

File "/freqtrade/freqtrade/worker.py", line 49, in _init

self._config = Configuration(self._args, None).get_config()

File "/freqtrade/freqtrade/configuration/configuration.py", line 41, in get_config

self.config = self.load_config()

File "/freqtrade/freqtrade/configuration/configuration.py", line 94, in load_config

config: Dict[str, Any] = self.load_from_files(self.args.get("config", []))

File "/freqtrade/freqtrade/configuration/configuration.py", line 73, in load_from_files

config = deep_merge_dicts(load_config_file(path), config)

File "/freqtrade/freqtrade/configuration/load_config.py", line 61, in load_config_file

raise OperationalException(

freqtrade.exceptions.OperationalException: Config file "config.json" not found! Please create a config file or check whether it exists.

**Comment by rti-admin** [comment] 2021-04-22 19:51
where do i edit the config file?

**Comment by xmatthias** [comment] 2021-04-23 04:31
Simply follow the [docker quickstart guide](https://www.freqtrade.io/en/stable/docker_quickstart/).

one of the commands will be to run the `new-config` command (make sure to use the parameters from the documentation).
The configuration will then be in `user_data/config.json`.

**Comment by Aierus** [comment] 2021-05-01 19:54
Had the same issue. 

Needed to run 
`brew install c-blosc`
`pip3 install tables`

Install now works on my machine

**Comment by xmatthias** [comment] 2021-05-02 06:34
well yeah - as documented in the [macos python 3.9 section](https://www.freqtrade.io/en/latest/installation/#macos-installation-error-with-python-39) :smile: 

I think as we have this covered by the docs now, i'll close this.

**Closed as completed by xmatthias** 2021-05-02 06:34 UTC
Labels: Question, Install
