### ISSUE TITLE
[Feature Request] add margin as trading mode

### ISSUE THREAD

**Issue by heynando** [freqtrade/freqtrade#8422] opened 2023-03-31 06:13 UTC
Trading inside the margin account allows us to pay the spot fee which are SUBSTANTIALLY LOWER than on FUTURES. This is the main reason trading on margin mode is a must have. 

I’ve spent one full week searching for a bot that can trade isolated margin inside the margin account and so far I have found NONE. 

 please add support for margin account, specially on Binance, specifically isolated margin.

Respectfully
Thank you

**Comment by xmatthias** [comment] 2023-03-31 08:22
Please get used to filling out the issue template.  Those who frequently omit the template may have their issues closed without comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions.

Filling out the template helps reduce our workload, and we greatly appreciate that.

---

Also - please use the search to find already existing issues (this is a duplicate of #2312 ).

We're currently not actively working on integrating margin mode, but parts for that would already be prepared.
PR's adding support for this (or moving in that direction) are obviously welcome (it's however not a beginner task, so best start with some simpler PR's if you're interested in this.).

to be updated on progress of margin mode - please subscribe to #2312. 
Going to close this as duplicate.

**Closed as completed by xmatthias** 2023-03-31 08:22 UTC
Labels: Duplicate
