### ISSUE TITLE
Incorrect Est. Balance for the pair BTCST

### ISSUE THREAD

**Issue by varunrai** [freqtrade/freqtrade#4345] opened 2021-02-10 02:31 UTC
* Operating system: Ubuntu
  * Python Version: 3.7
  * CCXT version: 1.41.63
  * Freqtrade Version: 2021.1

The balance displayed in the telegram bot for the pair BTCST/BTC is incorrect. 

### Steps to reproduce:

  1. Configuration - Stake Currency set to BTC and the pair BTCST/BTC is whitelisted or any other pair name that starts with BTC..
  2. Configure the telegram bot
  3. Start the trade bot and request for the balance via telegram
  
### Observed Results:

  * The balance display for the Est. Balance under the currency and the final Estimated Value are incorrect (see the attached screenshot).

### Relevant code exceptions or logs

the code in rpc.py in the function _rpc_balance [(Link)] (https://github.com/freqtrade/freqtrade/blob/766c786d9088730ab617948625bd573b2641249f/freqtrade/rpc/rpc.py#L453) assumes the pair name starts with stake_currency (in my case BTC) and the pair name is BTCST/BTC which will result in the incorrect calculation being applied to the Est. Balance.

```
if pair.startswith(stake_currency):
   rate = 1.0 / rate
   est_stake = rate * balance.total  

```

![Telegram_h7BDSfttae](https://user-images.githubusercontent.com/1327311/107456323-f3826500-6b8a-11eb-8f25-f557ee2aae46.jpg)

Once of the possible ways to fix would be to use the following code:
```
if pair.startswith(stake_currency + "/"):
   rate = 1.0 / rate
   est_stake = rate * balance.total  

```

**Comment by xmatthias** [comment] 2021-02-10 05:48
I'm going to close this as it's a duplicate of #4307 (i'm sorry for your efforts with the PR ...).

It's fixed in develop since 5 days now ... and will "age" into the release around the end of the month.

**Closed as completed by xmatthias** 2021-02-10 05:48 UTC
Labels: Duplicate

**Comment by varunrai** [comment] 2021-02-10 06:17
> I'm going to close this as it's a duplicate of #4307 (i'm sorry for your efforts with the PR ...).
> 
> It's fixed in develop since 5 days now ... and will "age" into the release around the end of the month.

No worries. I should have checked the other issue :)
