### ISSUE TITLE
Backtesting: Add Sharpe/Sortino ratio to strategy summary / comparison

### ISSUE THREAD

**Issue by striderZA** [freqtrade/freqtrade#5483] opened 2021-08-26 17:07 UTC
Having access to Sharpe/Sortino ratios provides additional useful insight during backtesting, above profit / W/L / drawdown, etc. metrics already provided.

E.g.:

```
=============== SUMMARY METRICS ================
| Metric                 | Value               |
|------------------------+---------------------|
| Backtesting from       | 2021-08-01 00:00:00 |
| Backtesting to         | 2021-08-25 19:25:00 |
| Max open trades        | 5                   |
|                        |                     |
| Total/Daily Avg Trades | 214 / 8.92          |
| Starting balance       | 1500.000 USDT       |
| Final balance          | 2116.732 USDT       |
| Absolute profit        | 616.732 USDT        |
| Total profit %         | 41.12%              |
| Avg. stake amount      | 300.000 USDT        |
| Total trade volume     | 64200.000 USDT      |
|                        |                     |
| Best Pair              | TRU/USDT 31.8%      |
| Worst Pair             | NMR/USDT -4.87%     |
| Best trade             | FIS/USDT 21.48%     |
| Worst trade            | FIS/USDT -12.71%    |
| Best day               | 198.932 USDT        |
| Worst day              | -30.188 USDT        |
| Days win/draw/lose     | 21 / 0 / 4          |
| Avg. Duration Winners  | 0:44:00             |
| Avg. Duration Loser    | 2:34:00             |
| Rejected Buy signals   | 4497                |
|                        |                     |
| Min balance            | 1505.599 USDT       |
| Max balance            | 2137.186 USDT       |
| Drawdown               | 28.03%              |
| Drawdown               | 84.179 USDT         |
| Drawdown high          | 335.612 USDT        |
| Drawdown low           | 251.433 USDT        |
| Drawdown Start         | 2021-08-06 19:20:00 |
| Drawdown End           | 2021-08-07 10:45:00 |
| Market change          | 63.36%              |
| Sharpe Ratio           | 55.02               |
| Sortino Ratio          | 91.7                |
================================================
```

Possible implementation (optimize_reports.py):

1. Re-use calculations from hyperopt loss modules and perform calculations in ``generate_strategy_stats``
2. Add printing of ratios to ``text_table_add_metrics``

Not sure how to add these to the strategy comparison printout.

**Comment by moinonin** [comment] 2021-08-26 17:18
Totally agree. We all agree that max drawdown is the only other factor after the profit percent and absolute BTC amount. Besides, MDD as is has problems as it assumes you are opening one position at a time if I understood correctly.

**Comment by xmatthias** [comment] 2021-08-26 17:23
this is a duplicate of #1907.

If you think it's important - i would welcome a PR / contribution that will add this to the Freqtrade output.

**Closed as completed** 2021-08-26 17:36 UTC
Labels: Duplicate
