### ISSUE TITLE
BNB as stake currency

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#2394] opened 2019-10-19 20:42 UTC
is it possible to use BNB as stake currency ? On develop branch get jsonschema.exceptions.ValidationError: 'BNB' is not one of ['BTC', 'XBT', 'ETH', 'USDT', 'EUR', 'USD']

**Comment by hroff-1902** [comment] 2019-10-19 21:19
pls wait for #1861 -- a generic solution will be implemented.

**Comment by hroff-1902** [comment] 2019-10-19 21:24
@xmatthias I mean here the dynamic pair whitelists for any quote (stake) currency, available at the exchange.

Or adding a currency to this list (['BTC', 'XBT', 'ETH', 'USDT', 'EUR', 'USD']) also has other pitfalls like fetching the exchange rates for stake/fiat translation?

**Comment by xmatthias** [comment] 2019-10-20 06:54
Since this is a duplicate of #1861 (a solution for that should be applicable to all possible stake currencies for that exchange - this answers your question @hroff-1902) i'll close this so we have one issue to discuss the approach.

**Closed by xmatthias** 2019-10-20 06:54 UTC
Labels: duplicate
