### ISSUE TITLE
TypeError: 'USDT01Strategy' object is not subscriptable

### ISSUE THREAD

**Issue by YuriyTigiev** [freqtrade/freqtrade#4216] opened 2021-01-14 19:38 UTC
## Describe your environment

  * Operating system: Microsoft Windows [Version 10.0.19042.746] 64 bit
  * Docker: image: freqtradeorg/freqtrade:develop_plot
  * CCXT version: CCXT 1.40.25
  * Freqtrade Version: freqtrade docker-5102dfd6 
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

The backtest returns an error: freqtrade - ERROR - Fatal exception! The full description below. 
I have copied and paste function from hyperopt EmptyHyperopt and parameters from a result of work hyperopt into USDT01strategies.py.   
The sample_strategy.py with default config.json work properly with the same dock image. 
I first time used hyperopt.

functions  
```
def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
```
params 
```
buy_params 
sell_params

```
docker-compose run --rm freqtrade new-hyperopt --hyperopt EmptyHyperopt
docker-compose run --rm freqtrade hyperopt --hyperopt EmptyHyperopt --hyperopt-loss OnlyProfitHyperOptLoss --strategy SampleStrategy --config user_data/config.json -e 500 --timerange 20210101-20210113 -i 3m 

### Steps to reproduce:

1)   Download data 
`docker-compose run --rm freqtrade download-data --exchange binance --timerange 20201201-20210113  --timeframes 1m 3m 5m 15m 30m 1h 4h 8h 12h 1d`

2) Run backtest 
`docker-compose run --rm freqtrade backtesting --export trades --config user_data/USDT01_config.json --strategy USDT01Strategy --timerange 20210101-20210113 -i 3m `

USDT01Strategy.py file

```
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy.interface import IStrategy

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib


# This class is a sample. Feel free to customize it.
class USDT01Strategy(IStrategy):
    """
    This is a sample strategy to inspire you.
    More information in https://github.com/freqtrade/freqtrade/blob/develop/docs/bot-optimization.md

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the prototype for the methods: minimal_roi, stoploss, populate_indicators, populate_buy_trend,
    populate_sell_trend, hyperopt_space, buy_strategy_generator
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = { 
	  "0": 0.1128, 
	  "22": 0.05443, 
	  "54": 0.02719, 
	  "114": 0 
	  } 

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.26025

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal ticker interval for the strategy.
    timeframe = '3m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'tema': {},
            'sar': {'color': 'white'},
        },
        'subplots': {
            "MACD": {
                'macd': {'color': 'blue'},
                'macdsignal': {'color': 'orange'},
            },
            "RSI": {
                'rsi': {'color': 'red'},
            }
        }
    }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        # Momentum Indicators
        # ------------------------------------

        # ADX
        dataframe['adx'] = ta.ADX(dataframe)

        # # Plus Directional Indicator / Movement
        # dataframe['plus_dm'] = ta.PLUS_DM(dataframe)
        # dataframe['plus_di'] = ta.PLUS_DI(dataframe)

        # # Minus Directional Indicator / Movement
        # dataframe['minus_dm'] = ta.MINUS_DM(dataframe)
        # dataframe['minus_di'] = ta.MINUS_DI(dataframe)

        # # Aroon, Aroon Oscillator
        # aroon = ta.AROON(dataframe)
        # dataframe['aroonup'] = aroon['aroonup']
        # dataframe['aroondown'] = aroon['aroondown']
        # dataframe['aroonosc'] = ta.AROONOSC(dataframe)

        # # Awesome Oscillator
        # dataframe['ao'] = qtpylib.awesome_oscillator(dataframe)

        # # Keltner Channel
        # keltner = qtpylib.keltner_channel(dataframe)
        # dataframe["kc_upperband"] = keltner["upper"]
        # dataframe["kc_lowerband"] = keltner["lower"]
        # dataframe["kc_middleband"] = keltner["mid"]
        # dataframe["kc_percent"] = (
        #     (dataframe["close"] - dataframe["kc_lowerband"]) /
        #     (dataframe["kc_upperband"] - dataframe["kc_lowerband"])
        # )
        # dataframe["kc_width"] = (
        #     (dataframe["kc_upperband"] - dataframe["kc_lowerband"]) / dataframe["kc_middleband"]
        # )

        # # Ultimate Oscillator
        # dataframe['uo'] = ta.ULTOSC(dataframe)

        # # Commodity Channel Index: values [Oversold:-100, Overbought:100]
        # dataframe['cci'] = ta.CCI(dataframe)

        # RSI
        dataframe['rsi'] = ta.RSI(dataframe)

        # # Inverse Fisher transform on RSI: values [-1.0, 1.0] (https://goo.gl/2JGGoy)
        # rsi = 0.1 * (dataframe['rsi'] - 50)
        # dataframe['fisher_rsi'] = (np.exp(2 * rsi) - 1) / (np.exp(2 * rsi) + 1)

        # # Inverse Fisher transform on RSI normalized: values [0.0, 100.0] (https://goo.gl/2JGGoy)
        # dataframe['fisher_rsi_norma'] = 50 * (dataframe['fisher_rsi'] + 1)

        # # Stochastic Slow
        # stoch = ta.STOCH(dataframe)
        # dataframe['slowd'] = stoch['slowd']
        # dataframe['slowk'] = stoch['slowk']

        # Stochastic Fast
        stoch_fast = ta.STOCHF(dataframe)
        dataframe['fastd'] = stoch_fast['fastd']
        dataframe['fastk'] = stoch_fast['fastk']

        # # Stochastic RSI
        # Please read https://github.com/freqtrade/freqtrade/issues/2961 before using this.
        # STOCHRSI is NOT aligned with tradingview, which may result in non-expected results.
        # stoch_rsi = ta.STOCHRSI(dataframe)
        # dataframe['fastd_rsi'] = stoch_rsi['fastd']
        # dataframe['fastk_rsi'] = stoch_rsi['fastk']

        # MACD
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        # MFI
        dataframe['mfi'] = ta.MFI(dataframe)

        # # ROC
        # dataframe['roc'] = ta.ROC(dataframe)

        # Overlap Studies
        # ------------------------------------

        # Bollinger Bands
        bollinger = qtpylib.bollinger_bands(qtpylib.typical_price(dataframe), window=20, stds=2)
        dataframe['bb_lowerband'] = bollinger['lower']
        dataframe['bb_middleband'] = bollinger['mid']
        dataframe['bb_upperband'] = bollinger['upper']
        dataframe["bb_percent"] = (
            (dataframe["close"] - dataframe["bb_lowerband"]) /
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"])
        )
        dataframe["bb_width"] = (
            (dataframe["bb_upperband"] - dataframe["bb_lowerband"]) / dataframe["bb_middleband"]
        )

        # Bollinger Bands - Weighted (EMA based instead of SMA)
        # weighted_bollinger = qtpylib.weighted_bollinger_bands(
        #     qtpylib.typical_price(dataframe), window=20, stds=2
        # )
        # dataframe["wbb_upperband"] = weighted_bollinger["upper"]
        # dataframe["wbb_lowerband"] = weighted_bollinger["lower"]
        # dataframe["wbb_middleband"] = weighted_bollinger["mid"]
        # dataframe["wbb_percent"] = (
        #     (dataframe["close"] - dataframe["wbb_lowerband"]) /
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"])
        # )
        # dataframe["wbb_width"] = (
        #     (dataframe["wbb_upperband"] - dataframe["wbb_lowerband"]) /
        #     dataframe["wbb_middleband"]
        # )

        # # EMA - Exponential Moving Average
        # dataframe['ema3'] = ta.EMA(dataframe, timeperiod=3)
        # dataframe['ema5'] = ta.EMA(dataframe, timeperiod=5)
        # dataframe['ema10'] = ta.EMA(dataframe, timeperiod=10)
        # dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        # dataframe['ema50'] = ta.EMA(dataframe, timeperiod=50)
        # dataframe['ema100'] = ta.EMA(dataframe, timeperiod=100)

        # # SMA - Simple Moving Average
        # dataframe['sma3'] = ta.SMA(dataframe, timeperiod=3)
        # dataframe['sma5'] = ta.SMA(dataframe, timeperiod=5)
        # dataframe['sma10'] = ta.SMA(dataframe, timeperiod=10)
        # dataframe['sma21'] = ta.SMA(dataframe, timeperiod=21)
        # dataframe['sma50'] = ta.SMA(dataframe, timeperiod=50)
        # dataframe['sma100'] = ta.SMA(dataframe, timeperiod=100)

        # Parabolic SAR
        dataframe['sar'] = ta.SAR(dataframe)

        # TEMA - Triple Exponential Moving Average
        dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)

        # Cycle Indicator
        # ------------------------------------
        # Hilbert Transform Indicator - SineWave
        hilbert = ta.HT_SINE(dataframe)
        dataframe['htsine'] = hilbert['sine']
        dataframe['htleadsine'] = hilbert['leadsine']

        # Pattern Recognition - Bullish candlestick patterns
        # ------------------------------------
        # # Hammer: values [0, 100]
        # dataframe['CDLHAMMER'] = ta.CDLHAMMER(dataframe)
        # # Inverted Hammer: values [0, 100]
        # dataframe['CDLINVERTEDHAMMER'] = ta.CDLINVERTEDHAMMER(dataframe)
        # # Dragonfly Doji: values [0, 100]
        # dataframe['CDLDRAGONFLYDOJI'] = ta.CDLDRAGONFLYDOJI(dataframe)
        # # Piercing Line: values [0, 100]
        # dataframe['CDLPIERCING'] = ta.CDLPIERCING(dataframe) # values [0, 100]
        # # Morningstar: values [0, 100]
        # dataframe['CDLMORNINGSTAR'] = ta.CDLMORNINGSTAR(dataframe) # values [0, 100]
        # # Three White Soldiers: values [0, 100]
        # dataframe['CDL3WHITESOLDIERS'] = ta.CDL3WHITESOLDIERS(dataframe) # values [0, 100]

        # Pattern Recognition - Bearish candlestick patterns
        # ------------------------------------
        # # Hanging Man: values [0, 100]
        # dataframe['CDLHANGINGMAN'] = ta.CDLHANGINGMAN(dataframe)
        # # Shooting Star: values [0, 100]
        # dataframe['CDLSHOOTINGSTAR'] = ta.CDLSHOOTINGSTAR(dataframe)
        # # Gravestone Doji: values [0, 100]
        # dataframe['CDLGRAVESTONEDOJI'] = ta.CDLGRAVESTONEDOJI(dataframe)
        # # Dark Cloud Cover: values [0, 100]
        # dataframe['CDLDARKCLOUDCOVER'] = ta.CDLDARKCLOUDCOVER(dataframe)
        # # Evening Doji Star: values [0, 100]
        # dataframe['CDLEVENINGDOJISTAR'] = ta.CDLEVENINGDOJISTAR(dataframe)
        # # Evening Star: values [0, 100]
        # dataframe['CDLEVENINGSTAR'] = ta.CDLEVENINGSTAR(dataframe)

        # Pattern Recognition - Bullish/Bearish candlestick patterns
        # ------------------------------------
        # # Three Line Strike: values [0, -100, 100]
        # dataframe['CDL3LINESTRIKE'] = ta.CDL3LINESTRIKE(dataframe)
        # # Spinning Top: values [0, -100, 100]
        # dataframe['CDLSPINNINGTOP'] = ta.CDLSPINNINGTOP(dataframe) # values [0, -100, 100]
        # # Engulfing: values [0, -100, 100]
        # dataframe['CDLENGULFING'] = ta.CDLENGULFING(dataframe) # values [0, -100, 100]
        # # Harami: values [0, -100, 100]
        # dataframe['CDLHARAMI'] = ta.CDLHARAMI(dataframe) # values [0, -100, 100]
        # # Three Outside Up/Down: values [0, -100, 100]
        # dataframe['CDL3OUTSIDE'] = ta.CDL3OUTSIDE(dataframe) # values [0, -100, 100]
        # # Three Inside Up/Down: values [0, -100, 100]
        # dataframe['CDL3INSIDE'] = ta.CDL3INSIDE(dataframe) # values [0, -100, 100]

        # # Chart type
        # # ------------------------------------
        # # Heikin Ashi Strategy
        # heikinashi = qtpylib.heikinashi(dataframe)
        # dataframe['ha_open'] = heikinashi['open']
        # dataframe['ha_close'] = heikinashi['close']
        # dataframe['ha_high'] = heikinashi['high']
        # dataframe['ha_low'] = heikinashi['low']

        # Retrieve best bid and best ask from the orderbook
        # ------------------------------------
        """
        # first check if dataprovider is available
        if self.dp:
            if self.dp.runmode in ('live', 'dry_run'):
                ob = self.dp.orderbook(metadata['pair'], 1)
                dataframe['best_bid'] = ob['bids'][0][0]
                dataframe['best_ask'] = ob['asks'][0][0]
        """

        return dataframe


    def populate_buy_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Buy strategy Hyperopt will build and use.
        """
        conditions = []

        params = {
            'adx-enabled': False,
            'adx-value': 45,
            'fastd-enabled': False,
            'fastd-value': 42,
            'mfi-enabled': False,	
            'mfi-value': 16,
            'rsi-enabled': False,	
            'rsi-value': 27,
            'trigger': 'sar_reversal'	
         }		

        # GUARDS AND TRENDS
        if params.get('mfi-enabled'):
            conditions.append(dataframe['mfi'] < params['mfi-value'])
        if params.get('fastd-enabled'):
            conditions.append(dataframe['fastd'] < params['fastd-value'])
        if params.get('adx-enabled'):
            conditions.append(dataframe['adx'] > params['adx-value'])
        if params.get('rsi-enabled'):
            conditions.append(dataframe['rsi'] < params['rsi-value'])

        # TRIGGERS
        if 'trigger' in params:
            if params['trigger'] == 'bb_lower':
                conditions.append(dataframe['close'] < dataframe['bb_lowerband'])
            if params['trigger'] == 'macd_cross_signal':
                conditions.append(qtpylib.crossed_above(
                    dataframe['macd'], dataframe['macdsignal']
                ))
            if params['trigger'] == 'sar_reversal':
                conditions.append(qtpylib.crossed_above(
                    dataframe['close'], dataframe['sar']
                ))

        # Check that the candle had volume
        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'buy'] = 1

        return dataframe


    def populate_sell_trend(dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Sell strategy Hyperopt will build and use.
        """
        conditions = []

        params = {		
            'sell-adx-enabled': True,
            'sell-adx-value': 98,	
            'sell-fastd-enabled': False,	
            'sell-fastd-value': 57,			
            'sell-mfi-enabled': True,
            'sell-mfi-value': 100,	
            'sell-rsi-enabled': True,
            'sell-rsi-value': 80,	
            'sell-trigger': 'sell-macd_cross_signal'
            }			

        # GUARDS AND TRENDS
        if params.get('sell-mfi-enabled'):
            conditions.append(dataframe['mfi'] > params['sell-mfi-value'])
        if params.get('sell-fastd-enabled'):
            conditions.append(dataframe['fastd'] > params['sell-fastd-value'])
        if params.get('sell-adx-enabled'):
            conditions.append(dataframe['adx'] < params['sell-adx-value'])
        if params.get('sell-rsi-enabled'):
            conditions.append(dataframe['rsi'] > params['sell-rsi-value'])

        # TRIGGERS
        if 'sell-trigger' in params:
            if params['sell-trigger'] == 'sell-bb_upper':
                conditions.append(dataframe['close'] > dataframe['bb_upperband'])
            if params['sell-trigger'] == 'sell-macd_cross_signal':
                conditions.append(qtpylib.crossed_above(
                    dataframe['macdsignal'], dataframe['macd']
                ))
            if params['sell-trigger'] == 'sell-sar_reversal':
                conditions.append(qtpylib.crossed_above(
                    dataframe['sar'], dataframe['close']
                ))

        # Check that the candle had volume
        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'sell'] = 1

        return dataframe

  
```

USDT01_config.json

```
{
  "max_open_trades": -1,
  "stake_currency": "USDT",
  "stake_amount": 15,
  "tradable_balance_ratio": 0.95,
  "fiat_display_currency": "USD",
  "timeframe": "3m",
  "dry_run": true,
  "dry_run_wallet": 50,
  "cancel_open_orders_on_exit": false,
  "unfilledtimeout": {
    "buy": 10,
    "sell": 30
  },
  "bid_strategy": {
    "price_side": "bid",
    "ask_last_balance": 0.0,
    "use_order_book": false,
    "order_book_top": 1,
    "check_depth_of_market": {
      "enabled": false,
      "bids_to_ask_delta": 1
    }
  },
  "ask_strategy": {
    "price_side": "ask",
    "use_order_book": false,
    "order_book_min": 1,
    "order_book_max": 1,
    "use_sell_signal": true,
    "sell_profit_only": false,
    "ignore_roi_if_buy_signal": false
  },
  "exchange": {
    "name": "binance",
    "key": "key",
    "secret": "secret",
    "ccxt_config": { "enableRateLimit": true },
    "ccxt_async_config": {
      "enableRateLimit": true,
      "rateLimit": 200
    },
    "pair_whitelist": [
      "BTC/USDT",
      "ADA/USDT",
      "ETH/USDT",
      "LINK/USDT",
      "MKR/USDT",
      "UNI/USDT",
      "COMP/USDT",
      "YFI/USDT",
      "SNX/USDT",
      "REP/USDT",
      "XLM/USDT",
      "IOST/USDT",
      "FUN/USDT",
      "HBAR/USDT",
      "LTC/USDT",
      "BCH/USDT",
      "DOT/USDT",
      "EOS/USDT",
      "XMR/USDT",
      "DASH/USDT",
      "ETC/USDT",
      "SUSHI/USDT",
      "ATOM/USDT"
    ],
    "pair_blacklist": [
      "BNB/USDT"
    ]
  },
  "pairlists": [
    { "method": "StaticPairList" }
  ],
  "edge": {
    "enabled": false,
    "process_throttle_secs": 3600,
    "calculate_since_number_of_days": 7,
    "allowed_risk": 0.01,
    "stoploss_range_min": -0.01,
    "stoploss_range_max": -0.26025,
    "stoploss_range_step": -0.002,
    "minimum_winrate": 0.60,
    "minimum_expectancy": 0.20,
    "min_trade_number": 10,
    "max_trade_duration_minute": 1440,
    "remove_pumps": false
  },
  "telegram": {
    "enabled": false,
    "token": "token",
    "chat_id": "chat_id"
  },
  "api_server": {
    "enabled": false,
    "listen_ip_address": "127.0.0.1",
    "listen_port": 8080,
    "verbosity": "info",
    "jwt_secret_key": "somethingrandom",
    "CORS_origins": [],
    "username": "",
    "password": ""
  },
  "initial_state": "running",
  "forcebuy_enable": false,
  "internals": {
    "process_throttle_secs": 5
  }
}

```
### Observed Results:

  * What happened?
The freqtrade returned the error. The text message bellow
  * What did you expect to happen?
Get the result of backtesting. 

### Relevant code exceptions or logs

```
C:\ft_userdata>docker-compose run --rm freqtrade backtesting --export trades --config user_data/USDT01_config.json --strategy USDT01Strategy --timerange 20210101-20210113 -i 3m  
2021-01-14 19:12:58,393 - freqtrade.configuration.configuration - INFO - Using config: user_data/USDT01_config.json ...
2021-01-14 19:12:58,396 - freqtrade.loggers - INFO - Verbosity set to 0
2021-01-14 19:12:58,397 - freqtrade.configuration.configuration - INFO - Parameter -i/--timeframe detected ... Using timeframe: 3m ...
2021-01-14 19:12:58,397 - freqtrade.configuration.configuration - INFO - Using max_open_trades: inf ...
2021-01-14 19:12:58,397 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20210101-20210113 ...
2021-01-14 19:12:58,402 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2021-01-14 19:12:58,403 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
2021-01-14 19:12:58,403 - freqtrade.configuration.configuration - INFO - Overriding timeframe with Command line argument
2021-01-14 19:12:58,403 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2021-01-14 19:12:58,403 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2021-01-14 19:12:58,403 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2021-01-14 19:12:58,403 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2021-01-14 19:12:58,404 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-14 19:12:58,406 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2021-01-14 19:12:58,406 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2021-01-14 19:12:58,406 - freqtrade.exchange.exchange - INFO - Using CCXT 1.40.25
2021-01-14 19:12:58,406 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2021-01-14 19:12:58,414 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2021-01-14 19:12:58,420 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2021-01-14 19:12:59,661 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-01-14 19:12:59,694 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy USDT01Strategy from '/freqtrade/user_data/strategies/USDT01_strategy.py'...
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'timeframe' with value in config file: 3m.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 15.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.1128, '22': 0.05443, '54': 0.02719, '114': 0}
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 3m
2021-01-14 19:12:59,695 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.26025
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'market', 'stoploss_on_exchange': False}
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 15
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 30
2021-01-14 19:12:59,696 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2021-01-14 19:12:59,697 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2021-01-14 19:12:59,697 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2021-01-14 19:12:59,697 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2021-01-14 19:12:59,697 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2021-01-14 19:12:59,697 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2021-01-14 19:12:59,702 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2021-01-14 19:12:59,704 - freqtrade.optimize.backtesting - INFO - Using stake_currency: USDT ...
2021-01-14 19:12:59,704 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 15 ...
2021-01-14 19:12:59,707 - freqtrade.data.history.history_utils - INFO - Using indicator startup period: 30 ...
2021-01-14 19:12:59,748 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2021-01-14 19:13:01,334 - freqtrade.optimize.backtesting - INFO - Loading data from 2020-12-31 22:30:00 up to 2021-01-13 00:00:00 (12 days)..
2021-01-14 19:13:01,334 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy USDT01Strategy
2021-01-14 19:13:01,720 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-01-01 00:00:00 up to 2021-01-13 00:00:00 (12 days)..
2021-01-14 19:13:01,721 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 50, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 466, in start
    results = self.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 348, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 205, in _get_ohlcv_as_lists
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 681, in advise_buy
    return self.populate_buy_trend(dataframe)  # type: ignore
  File "/freqtrade/user_data/strategies/USDT01_strategy.py", line 373, in populate_buy_trend
    dataframe['close'], dataframe['sar']
TypeError: 'USDT01Strategy' object is not subscriptable
```

**Comment by xmatthias** [comment] 2021-01-15 05:27
This error usually suggests an error with parenteses / a missing sign.
```
# For example, the following 
dataframe.loc[(dataframe['rsi'] > 0) 
                       (dataframe['volume'] > 0), 'buy'] = 1
#correct version:
dataframe.loc[(dataframe['rsi'] > 0) & 
                       (dataframe['volume'] > 0), 'buy'] = 1
```

I'll however leave it up to you to determine what the precise error is - but it'll be around line 373 (not necessarily exactly on this line though).

**Comment by YuriyTigiev** [comment] 2021-01-15 07:27
I have replaced the necessary code from templates and results of hyperopes. What is wrong with them? Could you write exactly where the problem? I provided the full information for analysis.

**Comment by xmatthias** [comment] 2021-01-15 07:59
Finding the exact spot of the problem is left to you - as this can take a while.
If you can't figure it out, try removing the parts one by one to try and identify where the problem comes from.

I  also suggest to use an editor with syntax highlighting (like vscode with the python plugin).
This will highlight obvious syntax errors, and can help you identify problems.

---

Please understand that this is an open source project, so it's taking people's free time to support and develop further.
While we do give support for general questions, we will not fix your strategy for you.

I have given you the pointer as to what the problem is / might be. But i will not spend hours trying to fix your strategy.

Thanks for your understanding.

**Comment by YuriyTigiev** [comment] 2021-01-15 08:26
I investigated the issue and found the solution


1) add the string `from functools import reduce` to the strategy file 
2) The `self`  should be the first parameter the methods/functions  
```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

```
In the hyperopt templates, those functions defined without parameters `self`

**Comment by xmatthias** [comment] 2021-01-15 10:17
Hyperopt methods are not made to be copy-pasted 1:1 to the strategy.

By following the [hyperopt](https://www.freqtrade.io/en/latest/hyperopt/) documentation, you'll never even hit this problem.

I'll close this as you figured it out.

**Closed as completed by xmatthias** 2021-01-15 10:17 UTC
Labels: Question

**Comment by agustin9014** [comment] 2021-09-23 01:51
xmatthias 
How can I contact you? I am interested in this strategy.
Thanks

**Comment by Zamalazamala** [comment] 2021-09-23 04:44
You can contact me by phone or email
(Kalush)

**Comment by agustin9014** [comment] 2021-09-26 23:10
phone is +541132407857 thx
