### ISSUE TITLE
Edge, stake amount

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#1869] opened 2019-05-20 22:43 UTC
I am not sure whether edge is enabled in backtesting or hyper opts. It appears to be using strategy with stake currency, so I do not know if edge enabled is working in the tests.

**Comment by xmatthias** [comment] 2019-05-21 04:09
Edge is not active during backtesting / hyperopt, but there is a special "edge" command (similar syntax than backtesting) to evaluate edge strategies.

Make sure to familiarize yourself with the docs on Edge - it has some limits (e.g. no ROI during "edging" ...)

**Comment by gitgitgat** [comment] 2019-05-21 19:34
`freqtrade -s TestStrategy --datadir user_data/data/binance edge --stoplosses=-0.01,-0.1,-0.001`

 is being run but there is no output: 

> | pair   | stoploss   | win rate   | risk reward ratio   | required risk reward   | expectancy   | total number of trades   | average duration (min)   |
> ||

**Comment by hroff-1902** [comment] 2019-05-21 19:42
Do you see
```
freqtrade.edge - CRITICAL - No data found. Edge is stopped ...
```
in the log just above this empty table?

@xmatthias The table should not be printed in this case...

**Comment by gitgitgat** [comment] 2019-05-21 19:44
nope, these are the last three lines:

```
2019-05-21 14:33:01,108 - freqtrade.edge - INFO - Using stake_currency: BTC ...
2019-05-21 14:33:01,108 - freqtrade.edge - INFO - Using local backtesting data (using whitelist in given config) ...
2019-05-21 14:33:05,744 - freqtrade.edge - INFO - Measuring data from 2019-04-16T00:00:00+00:00 up to 2019-05-21T18:00:00+00:00 (35 days) ...
```

**Comment by hroff-1902** [comment] 2019-05-21 20:06
I've got this empty table when I removed the user_data/data/binance directory before... In this case that CRITICAL error message is issued...

**Comment by hroff-1902** [comment] 2019-05-21 20:09
In case the datadir is filled with some data, however, the TestStrategy produces the table with nans and infs:
```
| pair     |   stoploss |   win rate |   risk reward ratio |   required risk reward |   expectancy |   total number of trades |   average duration (min) |
|:---------|-----------:|-----------:|--------------------:|-----------------------:|-------------:|-------------------------:|-------------------------:|
| DASH/BTC |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       21 |                      388 |
| ETC/BTC  |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       19 |                      356 |
| ETH/BTC  |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       18 |                      475 |
| LTC/BTC  |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       24 |                      300 |
| XLM/BTC  |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       24 |                      284 |
| XMR/BTC  |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       31 |                      249 |
| ZEC/BTC  |      -0.01 |       0.00 |                 nan |                    inf |          nan |                       32 |                      263 |
```

The DefaultStrategy prints some 'normal' data...

**Comment by gitgitgat** [comment] 2019-05-21 20:14
okay, so the datadir would be only for backtesting? and would it matter if edge is tested with the default strategy instead. I used to get an error there, something to do with values.

**Comment by hroff-1902** [comment] 2019-05-21 20:16
@gitgitgat, that was additional input for @xmatthias mostly... Sorry, I did not specified that explicitely above...

**Comment by hroff-1902** [comment] 2019-05-21 20:22
@gitgitgat 
Could you:
* make a backup copy of the binance data_dir and remove the binance datadir
(or simply execute the `mv user_data/data/binance user_data/data/binance,SAV` command)
* run the edge with -r option to fetch the data again
```
freqtrade -s TestStrategy --datadir user_data/data/binance edge --stoplosses=-0.01,-0.1,-0.001 -r
```

**Comment by hroff-1902** [comment] 2019-05-21 20:27
> okay, so the datadir would be only for backtesting?

Nope, edge cannot also run without the data in the exchange datadir. You can see it if you delete the `user_data/data/binance` directory and run freqtrade edge without the `-r` option (i.e., without data in the exchange datadir).

**Comment by gitgitgat** [comment] 2019-05-21 20:35
> @gitgitgat
> Could you:
> 
> * make a backup copy of the binance datadir and remove the binance datadir
>   (or simply execute the `mv user_data/data/binance user_data/data/binance.SAV` command)
> * run the edge with -r option to fetch the data again
> 
> ```
> freqtrade -s TestStrategy --datadir user_data/data/binance edge --stoplosses=-0.01,-0.1,-0.001 -r
> ```

okay, I am going to try that once the downloads finish

**Comment by gitgitgat** [comment] 2019-05-21 22:09
> > @gitgitgat
> > Could you:
> > 
> > * make a backup copy of the binance datadir and remove the binance datadir
> >   (or simply execute the `mv user_data/data/binance user_data/data/binance.SAV` command)
> > * run the edge with -r option to fetch the data again
> > 
> > ```
> > freqtrade -s TestStrategy --datadir user_data/data/binance edge --stoplosses=-0.01,-0.1,-0.001 -r
> > ```
> 
> okay, I am going to try that once the downloads finish

exactly the same

**Comment by gitgitgat** [comment] 2019-05-21 22:19
backtesting is also empty

**Comment by xmatthias** [comment] 2019-05-22 04:43
edge will need and use the same data than backtesting, so if that data-dir has data for backtesting, it'll also work for edge.

The problem with no output from edge is most likely a bad or no sell signal. Since edge does not use ROI, it is possible that a strategy produces several profitable trades in backtesting, but does not work in edge.
If you run backtesting - check the "middle" table for "sell_signal":

sample from the documentation:
```
| Sell Reason        |   Count |
|:-------------------|--------:|
| stop_loss          |     166 |
| sell_signal        |      56 |
| force_sell         |       2 |
```

**Comment by hroff-1902** [comment] 2019-05-22 07:22
I'm able to reproduce this behavior. 
Set  `"ticker_interval" : "1d"` in the config. Run freqtrade with TestStrategy and default timerange (30 days or a few days more). The second table in the backtesting is also empty in this case.

@gitgitgat  This is not a bug in general. The timerange is too short to generate any trades,

However, output of edge should be clarified here. This can be considered as a bug. Will probably refactor it later. Assigning to myself for a while.

**Comment by gitgitgat** [comment] 2019-05-22 13:35
okay, the bug seems to be present due to the timeframe. hyper opts stalls after the sklearn warning. I haven't tried the above, but will check it out.

**Comment by gitgitgat** [comment] 2019-05-22 13:39
It also works down to 1h, 4h also working, anything below 1h and hyper opts stalls, I am assuming it is the same in this case.

**Comment by hroff-1902** [comment] 2019-05-22 14:12
> okay, the bug seems to be present due to the timeframe.

No bug "due to timeframe". There is an (a bit) incorrect behaviour resulting in printing empty table in case when no trades measured in the desired timerange (which itself is completely correct). The reason for empty trades list can be any.

**Comment by xmatthias** [comment] 2019-05-23 17:32
with #1871 merged, i think this should be explained sufficiently now.

Feel free to reopen if you think differently.

**Closed by xmatthias** 2019-05-23 17:32 UTC
Labels: question
