### ISSUE TITLE
Multiple buy on same pair

### ISSUE THREAD

**Issue by yohplala** [freqtrade/freqtrade#4755] opened 2021-04-18 16:36 UTC
## Describe the enhancement

Hi,
I have read in the doc (but not finding again) and through the discord channel: Freqtrade is not able to conduct several buy on a same pair when a position is already open. (it was again discussed recently in the discord)

I could not find a ticket where this feature is requested. I am sorry if the ticket already exsit.
Please, can multiple buy be allowed, despite a position is already existing, in Freqtrade?

The use case is:
- if buy_condition:
    - open a limit buy order with size S1

- if buy order filled:
     - open in OCO TP for size S1 + 2nd limit buy order with size S2

- if 2nd buy order is filled:
     - update TP for size S1 + S2
     - open a SL for size S1 + S2, OCO with TP order

There could possibly be several intermediat buy orders before finally opening the SL.

Please, is this feasible?
Thanks in advance for your help.
Bests,

keywords: grid trading, DCA, scalp, multiple buy

**Comment by xmatthias** [comment] 2021-04-18 17:12
it's actually a duplicate of #1519 - but depending on what you name / how you call it it it can be difficult to find.

It's unfortunately not as easy as you think it is (not without breaking many people's strategies).
Best read in the linked issue about the concerns / possibilities / decisions that need to be taken for this.

Also, OCO orders are currently not possible with freqtrade (it's a concept only known to binance, freqtrade however supports many different exchanges).

To answer "is it feasible" - yes - given enough time and will to implement this - sure.
Will i implement this myself anytime soon - most likely not - but Pull requests are always welcome ... :smile:

**Closed as completed by xmatthias** 2021-04-18 17:12 UTC
Labels: Duplicate

**Comment by yohplala** [comment] 2021-04-18 19:28
Thanks @xmatthias  for the answer. Will follow this ticket, thanks a lot!
