### ISSUE TITLE
Change to forceenter API Syntax - Enable Stake Position Size Option in Command Parameters

### ISSUE THREAD

**Issue by Fatman2142** [freqtrade/freqtrade#7267] opened 2022-08-21 04:07 UTC
Hi Guys,

Feature Request :

Can we add an override for 'forceenter' API call to be able to specify Stake amount? Ignoring '"stake_amount"' in the config file. Since it is an API call, it would be assuming the person making the call accepts this is the trade the want to make. 

Background : 

Looking to make Freqtrade open positions for a Strategy in TradingView. I am using WebhookRelay.Com, and a custom Python Script to communicate with Freqtrade API. Using WebhookRelay.com, I am able to make this process secure, as they have a local app that can be installed and communicates securely with WebhookRelay.Com. Preventing the need for anything other than 127.0.0.1 (0.0.0.0 for Docker Container) for the local instance of Freqtrade. Webhooks also require passing a correct authentication key before this external service will relay the data.

How this Feature request would work : 

Here is the command I would like to use :

python rest_client.py --config rest_config.json forceenter ETH/USDT long Default 500

Where '500', would be the amount in  Fiat Currency (Specified Currency as defined in config file) to purchase of Trading pair ETH/USDT

Current Command Syntax for quick reference :

forceenter
Force entering a trade

    :param pair: Pair to buy (ETH/BTC)
    :param side: 'long' or 'short'
    :param price: Optional - price to buy ( Meaning price per coin )

Suggestion:  

forceenter
Force entering a trade

    :param pair: Pair to buy (ETH/BTC)
    :param side: 'long' or 'short'
    :param price: Optional - price to buy - 'Default' to honor Config File
    :param Stake:Optional - Stake Amount - 'Default' to honor Config File

Thanks!
Regardless, Great work!! All the hours and effort put into this is much appreciated!

**Comment by xmatthias** [comment] 2022-08-21 06:13
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---
That said - i'll be closing this as duplicate of #7265 - which basically requests the same thing.

**Closed as completed by xmatthias** 2022-08-21 06:13 UTC
Labels: Duplicate
