### ISSUE TITLE
freqtrade crashed on order(take_profit_market) having amount 0.0 from exchange(binance)

### ISSUE THREAD

**Issue by canewsin** [freqtrade/freqtrade#10676] opened 2024-09-18 15:29 UTC
## Describe your environment

  * Operating system: docker image > freqtrade:stable
  * Freqtrade Version: 2024.8
  
## Describe the problem:

freqtrade crashed on order having amount 0.0 from exchange(binance)

### Steps to reproduce:

  1. Once a trade is created on freqtrade's side, create Take Profit market sell on Binance 
  2. close position on binance, take profit order auto cancelled
  3. freqtrade failed load above order to DB & crashed
  
### Observed Results:

  * Freqtrade crashed due order amt is null(0.0)

### Relevant code exceptions or logs
  ```rust
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: orders.ft_amount

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/freqtrade/freqtrade/freqtradebot.py", line 525, in handle_onexchange_order
    Trade.commit()
  File "/freqtrade/freqtrade/persistence/trade_model.py", line 1752, in commit
    Trade.session.commit()
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ftuser/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: orders.ft_amount
[SQL: INSERT INTO orders (ft_trade_id, ft_order_side, ft_pair, ft_is_open, ft_amount, ft_price, ft_cancel_reason, order_id, status, symbol, order_type, side, price, average, amount, filled, remaining, cost, stop_price, order_date, order_filled_date, order_update_date, funding_fee, ft_fee_base, ft_order_tag) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: (22, 'sell', 'ETH/USDT:USDT', 0, None, None, None, '8389765733593205099', 'canceled', 'ETH/USDT:USDT', 'take_profit_market', 'sell', None, None, None, 0.0, None, 0.0, 2350.0, '2024-09-18 07:51:40.718000', '2024-09-18 07:51:40.000000', '2024-09-18 12:58:54.228276', None, None, None)]  
```

**Comment by xmatthias** [comment] 2024-09-18 16:15
Please provide more logs.

this is just the actual exception - which doesn't include mentions or hints on how you got there - which is necessary information to look at this further.
hence, please provide at least 10 (ideally more) logs leading up to the error / exception.

**Comment by canewsin** [comment] 2024-09-18 17:29
only useful previous log is
```rust
2024-09-18 12:58:26,153 - freqtrade.freqtradebot - INFO - Found previously unknown order 8389765733593205099 for ETH/USDT:USDT.
2024-09-18 12:58:26,156 - freqtrade.freqtradebot - WARNING - Error finding onexchange order
```

**Comment by xmatthias** [comment] 2024-09-18 17:40
I'd apreciate uncensored (like - no removed lines) logs that lead to it.

While logs MAY seem to not be relevant - they can tell us good information about what the bot was trying to do.

> Once a trade is created on freqtrade's side, create Take Profit market sell on Binance

Just noticed this line ...
this is not a supported way to run the bot, actually.
The bot assumes to "own" the account (at least the assets it bought). If you manually mess with the bot's positions - it can no longer properly track these.
While we try to recover these - that'll only work for supported order types (take-profit is not one of these).

Having "amount=0" (or rather, amount=None) in the order response seems wrong (for any order type) - but is most likely a ccxt problem.

Please enable `"log_responses" : true` in the `exchange` section of your configuration and provide us with the logs once the error repeates.

**Comment by canewsin** [comment] 2024-09-18 18:14
https://github.com/freqtrade/freqtrade/blob/f50a633f8759437e5fc9e55b693cbb7a258cf326/freqtrade/freqtradebot.py#L521

https://github.com/freqtrade/freqtrade/blob/f50a633f8759437e5fc9e55b693cbb7a258cf326/freqtrade/persistence/trade_model.py#L327-L335

getting `'amount': None` for particular order, while parsing with parse_from_ccxt_object this still None due to default None param value

below might fix this issue?
```python
order_obj = Order.parse_from_ccxt_object(order, trade.pair, order["side"], 0.0) 
```

**Comment by xmatthias** [comment] 2024-09-18 18:33
No. doing that will break more things than you think - as it'll force the value to 0 for all orders.

As mentioned above:
> Please enable "log_responses" : true in the exchange section of your configuration and provide us with the logs once the error repeates.


Knowing the actual ccxt response will provide the information necessary to look at the issue.

Without that information - further looking at this issue is pointless. 
thanks for your understanding

**edit** with the assumption that the trade is still open, this should be pretty easy to recreate by starting the affected bot again, and should reproduce in a few minutes max.

**Comment by canewsin** [comment] 2024-09-20 00:27
> as it'll force the value to 0 for all orders.

No, I mean while got into this below else case & got amount as None at line 521, replacing None with 0.0 will prevent crashing, at least for non supported order types or we can completely skip this step for non supported order.

https://github.com/freqtrade/freqtrade/blob/f50a633f8759437e5fc9e55b693cbb7a258cf326/freqtrade/freqtradebot.py#L518-L528

**Comment by xmatthias** [comment] 2024-09-20 04:36
As mentioned above:

> Please enable "log_responses" : true in the exchange section of your configuration and provide us with the logs once the error repeates.

Knowing the actual ccxt response will provide the information necessary to look at the issue.

Without that information - further looking at this issue is pointless.
thanks for your understanding

with the assumption that the trade is still open, this should be pretty easy to recreate by starting the affected bot again, and should reproduce in a few minutes max.

---

Please **stop wasting my time** by having me repeat the same question for necessary information to properly look at an issue.
With the current information, there's nothing to look at other than unfounded speculation.
My current assumption is - this is an issue that needs fixing in ccxt - the requested logs will either confirm - or reject this - paving the way forward.

I hence will not repeat myself again here. 
I've asked for this information now for the 3rd time - there will be no 4th time.
If you have problems in understanding what to do - feel free to ask. But you're completely ignoring this request - which i interpret as you're not really looking for help.

If this information is not provided in the next message, i'll close this issue as "not a bug". Thanks for your understanding.

**Comment by canewsin** [comment] 2024-09-21 09:52
reason for not providing logs is due to usage in live account, ill try to solve it on my side and push a pr if solved.

> Having "amount=0" (or rather, amount=None) in the order response seems wrong (for any order type) - but is most likely a ccxt problem.

No this is the actual response (certain fields are redacted)
```rust
{'info': {'orderId': '8389765733593205099', 'symbol': 'ETHUSDT', 'status': 'CANCELED', ...
 'price': '0', 
'type': 'TAKE_PROFIT_MARKET', 'reduceOnly': True, 'closePosition': True, 'side': 'SELL', 'positionSide': 'BOTH', 'stopPrice': '2350', 'workingType': 'MARK_PRICE', ...
}, 'id': '8389765733593205099', 
... 
'amount': None, 'cost': 0.0, 
'average': None, 'filled': 0.0, 'remaining': None, 'status': 'canceled', 'fee': None, 
'trades': [], 'fees': [], 'stopPrice': 2350.0, 
'takeProfitPrice': None, 'stopLossPrice': None
 }
```
as you said this might be ccxt issue, haven't looked the codebase fully

> edit with the assumption that the trade is still open, this should be pretty easy to recreate by starting the affected bot again, and should reproduce in a few minutes max.

no, trade is closed even before i post this issue, incl all the other trades in this bot scope

crash happens while loading past orders on start up.

This is context i currently had, if this is still not enough to solve I don't mind you closing this issue.

**Comment by xmatthias** [comment] 2024-09-21 13:57
>  (certain fields are redacted)

Are they redacted - or removed? (which is a difference, especially in the "info" section).
The order (as presented) doesn't make sense (as a response from binance) - as it doesn't contain any amount - so it's saying "there was anorder selling ... nothing?

**Comment by canewsin** [comment] 2024-09-21 14:07
> Are they redacted - or removed?

I meant removed

> as it doesn't contain any amount

Except removing fields, I made no modifications to presented data, amount val is received as `None` from Binance

More context:
1. Bot started trading, 
2. after some time I put Take Profit for a trade on Binance
3. clicked close all positions on Binance
4. Bot started crashing when I restarted docker

**Comment by canewsin** [comment] 2024-09-21 14:12
![Screenshot_20240921-194148.png](https://github.com/user-attachments/assets/e437a263-3d52-4571-967c-2f0a57235e6c)

**Comment by canewsin** [comment] 2024-09-21 14:29
Full Response for particular order
```json
{
  "info": {
      "orderId": "8389765733593205099",
      "symbol": "ETHUSDT",
      "status": "CANCELED",
      "clientOrderId": "redacted",
      "price": "0",
      "avgPrice": "0.00000",
      "origQty": "0",
      "executedQty": "0",
      "cumQuote": "0",
      "timeInForce": "GTE_GTC",
      "type": "TAKE_PROFIT_MARKET",
      "reduceOnly": True,
      "closePosition": True,
      "side": "SELL",
      "positionSide": "BOTH",
      "stopPrice": "2350",
      "workingType": "MARK_PRICE",
      "priceMatch": "NONE",
      "selfTradePreventionMode": "NONE",
      "goodTillDate": "0",
      "priceProtect": True,
      "origType": "TAKE_PROFIT_MARKET",
      "time": "1726645900718",
      "updateTime": "1726656548702"
  },
  "id": "8389765733593205099",
  "clientOrderId": "redacted",
  "timestamp": 1726645900718,
  "datetime": "2024-09-18T07:51:40.718Z",
  "lastTradeTimestamp": None,
  "lastUpdateTimestamp": 1726656548702,
  "symbol": "ETH/USDT:USDT",
  "type": "take_profit_market",
  "timeInForce": "GTE_GTC",
  "postOnly": False,
  "reduceOnly": True,
  "side": "sell",
  "price": None,
  "triggerPrice": 2350.0,
  "amount": None,
  "cost": 0.0,
  "average": None,
  "filled": 0.0,
  "remaining": None,
  "status": "canceled",
  "fee": None,
  "trades": [],
  "fees": [],
  "stopPrice": 2350.0,
  "takeProfitPrice": None,
  "stopLossPrice": None
}
```

**Comment by xmatthias** [comment] 2024-09-21 14:31
this appears to be a different order ? i doubt this can cause a crash - as it's a regular market order.

it filled - and the ID is different from the one above, too (and amount is filled in this case).

**Comment by canewsin** [comment] 2024-09-21 14:40
my bad, posted wrong order, updated with correct response

**Closed as completed** 2024-09-22 06:40 UTC

**Comment by xmatthias** [comment] 2024-09-22 06:46
while the linked commit will _probably_ fix this exception - i'd want to point out that this is not a scenario we're currently supporting.

Freqtrade assumes that trades are executed by freqtrade, and the position is controlled by freqtrade (and freqtrade alone).
manual trades on the exchange are not supported - and while recovery functionality is there to some degree so it'll usually recover eventually - we cannot guarantee that it'll work for all scenarios / all order types.

If you want to close all positions - best use `/forceexit all` - which will essentially do the same thing - but in a supported way.
Obviously this assumes that there's no manual orders -  unknown to freqtrade - open which tie up the capital freqtrade thinks it controls - otherwise this can again lead to problems again.

If you'd like to do manual trading - please use subaccounts (either for your manual trading, or better yet - for freqtrade ). This will also simplify the statistics - as your manual "messing" won't interfere with the expectation of the strategy.

To manually control freqtrade positions - there's commands (telegram, freqUI) - which should be used to avoid problems.


---

I also am of the opinion that ccxt parses your order wrongly (`"origQty": "0",      "executedQty": "0",` - which they parse as None for both remaining and amount) - so this will most likely create additional problems when using such order types - but that's something you'd need to take up with ccxt (the order object you provided above should suffice for ccxt to investigate). As this is however not an order type freqtrade supports - it's not something i'll go reporting there.
