### ISSUE TITLE
Dependency version conflict. 

### ISSUE THREAD

**Issue by THETCR** [freqtrade/freqtrade#3858] opened 2020-10-13 07:39 UTC
ccxt verison 1.36.2 requires aiohttp 3.6.2 which is now added to the manifest with aiohttp==3.6.3

This breaks with a ContextualVersionConflict error.

**Comment by xmatthias** [comment] 2020-10-13 08:18
Freqtrade is using the newer version.

Feel free to open this issue against CCXT. 
I'm more than happy to bump ccxt to the version that uses the latest version of aiohttp.

**Comment by THETCR** [comment] 2020-10-13 08:26
@xmatthias 

You are absolutely right that hard pinning a dependency is bad practice. CCXT needs to have that fixed.

But either way Freqtrade depends on CCXT, so your development branch is currently broken.

**Comment by THETCR** [comment] 2020-10-13 08:34
It seems aiohttp version 3.6.3 was released 20 hours ago. So that they haven't bumped it yet seems logical.

Maybe Freqtrade would benefit from having dependency tests?

**Comment by xmatthias** [comment] 2020-10-13 08:50
Feel free to contribute these.



To me, the only issue here is the way ccxt pins dependencies, which forces all dependent libraries to use exactly that version. 

In Python, dependencies should be pinned in requirements files (used by CI / build processes to create reproducible environments).
Freqtrade does NOT pin dependencies in `setup.py` (unless there's a incompatible change, which will require a minimum version of a certain package).

Therefore, installing freqtrade (either via `pip install -e .` or `pip install .[all]`, or `python setup.py install` (or whatever other combination) will correctly install dependencies (not upgrading aiohttp to 3.6.3).

If you're running into the problem you mention above, then simply running either of the above commands will resolve it (by downgrading aiohttp).

While it's not ideal, i don't see a point in investing hours to write tests and whatnot to fix a problem that is not really there.

**Comment by Pascal66** [comment] 2020-10-13 09:19
The complete error message is : 

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

ccxt 1.36.2 requires aiohttp==3.6.2; python_version >= "3.5.2", but you'll have aiohttp 3.6.3 which is incompatible.
```

**Comment by THETCR** [comment] 2020-10-13 09:19
I understand your point and I know how this works. 

Regarding the dependency tests, I am willing to make them. 

For now i offered a simple MR to CCXT for bumping aiohttp to version 3.6.3.

**Comment by xmatthias** [comment] 2020-10-13 09:21
@THETCR i've noticed this - i think it's the wrong approach though - as it'll introduce the same problem we had here for all other applications using ccxt that have aiohttp hardpinned to the previous version (and did not upgrade yet).

**Comment by xmatthias** [comment] 2020-10-13 09:45
I'd wait for kroitor's response ... it's his decision in the end ...

**Comment by THETCR** [comment] 2020-10-13 10:05
Fair enough. 
It seems that CCXT 1.36.2 has a coding mistake with Kraken, calling items() on a List.
I bumped the version to 1.36.10 and everything seems to be working fine now.

**Comment by xmatthias** [comment] 2020-10-13 13:20
seen - there WAS reasoning behind having versions pinned...

Either way, this was closed in #3864 (by updating ccxt).

**Closed by xmatthias** 2020-10-13 13:20 UTC
Labels: CCXT, Triage Needed

**Comment by Pascal66** [comment] 2020-10-13 13:35
2020-10-13 15:30:02,740 - freqtrade.wallets - INFO - Wallets synced.
2020-10-13 15:30:02,743 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 12.9020555466 ...
2020-10-13 15:30:02,744 - freqtrade.freqtradebot - INFO - Checking depth of market for LTC/USDT ...
2020-10-13 15:30:02,744 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:30:02,744 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 4 times
2020-10-13 15:30:02,744 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:30:02,745 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 3 times
2020-10-13 15:30:02,745 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:30:02,745 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 2 times
2020-10-13 15:30:02,745 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:30:02,746 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 1 times
2020-10-13 15:30:02,746 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:30:02,746 - freqtrade.exchange.common - WARNING - Giving up retrying: fetch_l2_order_book()
2020-10-13 15:30:02,746 - freqtrade.freqtradebot - WARNING - Unable to create trade for LTC/USDT: Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25

**Comment by Pascal66** [comment] 2020-10-13 13:37
Fix doesnt resolve error
