### ISSUE TITLE
How to Seamlessly Transition from a Long Position to a Short Position in Freqtrade?

### ISSUE THREAD

**Issue by thanatchon36** [freqtrade/freqtrade#9190] opened 2023-09-17 05:41 UTC
## Describe your environment

  * Operating system: MAC OS
  * Python Version: 3.9.7
  * CCXT version: 4.0.88
  * Freqtrade Version: freqtrade 2023.8
  
## Your question

I'm currently using Freqtrade for my trading strategies, and I'm trying to figure out how to smoothly transition from holding a long position to closing that position and then taking a short position immediately.

Is there a recommended approach or strategy configuration in Freqtrade that can help achieve this transition without any unwanted gaps or delays in the trading process?

I appreciate any insights or guidance on how to implement this effectively within the Freqtrade framework.

Please consider my code here:
`

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        condition = (dataframe['sma_fast'] > dataframe['sma_slow']) & (dataframe['sma_fast'].shift(1) < dataframe['sma_slow'].shift(1))
        dataframe.loc[condition, ['enter_long', 'enter_tag']] = (1, 'enter_long')
        
        condition = (dataframe['sma_fast'] < dataframe['sma_slow']) & (dataframe['sma_fast'].shift(1) > dataframe['sma_slow'].shift(1))
        dataframe.loc[condition, ['enter_short', 'enter_tag']] = (1, 'enter_short')

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        condition = (dataframe['sma_fast'] > dataframe['sma_slow']) & (dataframe['sma_fast'].shift(1) < dataframe['sma_slow'].shift(1))
        dataframe.loc[condition, ['exit_short', 'exit_tag']] = (1, 'cross_exit_short')

        condition = (dataframe['sma_fast'] < dataframe['sma_slow']) & (dataframe['sma_fast'].shift(1) > dataframe['sma_slow'].shift(1))
        dataframe.loc[condition, ['exit_long', 'exit_tag']] = (1, 'cross_exit_long')

        return dataframe
`
The backtesting result indicates that when the signal exit_short or exit_long equals 1, Freqtrade does not trigger an enter_long or enter_short in the opposite direction. I would like to configure Freqtrade to automatically close the current open position and then initiate the opposite position immediately when these conditions occur.

**Comment by xmatthias** [comment] 2023-09-17 06:36
This is not supported at the moment - and probably wont' be for quite some time (see #9183 for reasons / complications in this).

You currently can't reverse positions within the same candle - but you can usually enter a new position (in either direction) in the next candle - assuming you don't use protections.

While there are some workarounds for this in live trading - this behavior is not backtestable, and therefore not a supported approach.

duplicate of #9183.

**Closed as completed by xmatthias** 2023-09-17 06:36 UTC
Labels: Duplicate, Question

**Comment by thanatchon36** [comment] 2023-09-17 06:38
Thank you for your response and clarification! I appreciate your assistance in addressing my question regarding reversing positions within the same candle in Freqtrade. Your explanation is clear and helpful. I'll take a look at issue #9183 for more details on the reasons and complications surrounding this feature. Thanks again for your support!
