### ISSUE TITLE
bitvavo: error message TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by Basbosbaas** [freqtrade/freqtrade#6166] opened 2022-01-04 19:31 UTC
## Describe your environment

  * Operating system: Linux Armbian 21.08.2 Docker
  * Python Version: 2.7 / 3.9
  * CCXT version: 1.66.20 (Docker)
  * Freqtrade Version: 2021.12

## Describe the problem:

*Problem since updating from V2021.11 to 2021.12. When making a order. I get folowing log message:

*freqtrade    | TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

### Steps to reproduce:

  1. Trading with Bitvavo
  2. Do a /forcebuy
  
### Observed Results:

  * When in live mode the bot gets died and restarts, when in dry_run mode it keeps running with error. There are in both situations no trades at the bot, but I can see trades in my exchange.

### Relevant code exceptions or logs

When starting up:
 ```
freqtrade    | 2022-01-04 19:45:06,458 - freqtrade.freqtradebot - INFO - Starting freqtrade 2021.12
freqtrade    | 2022-01-04 19:45:16,473 - BinHV45 - INFO - pandas_ta successfully imported
freqtrade    | 2022-01-04 19:45:17,058 - BinHV45 - INFO - pandas_ta successfully imported
freqtrade    | 2022-01-04 19:45:17,078 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BinHV45 from '/freqtrade/user_data/strategies/BinHV45.py'...
freqtrade    | 2022-01-04 19:45:17,080 - freqtrade.strategy.hyper - INFO - Found no parameter file.
freqtrade    | 2022-01-04 19:45:17,081 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
freqtrade    | 2022-01-04 19:45:17,085 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
freqtrade    | 2022-01-04 19:45:17,087 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
freqtrade    | 2022-01-04 19:45:17,092 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: EUR.
freqtrade    | 2022-01-04 19:45:17,094 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 10.
freqtrade    | 2022-01-04 19:45:17,095 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'unit': 'minutes'}.
freqtrade    | 2022-01-04 19:45:17,096 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.0125}
freqtrade    | 2022-01-04 19:45:17,098 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 1m
freqtrade    | 2022-01-04 19:45:17,099 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.05
freqtrade    | 2022-01-04 19:45:17,100 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
freqtrade    | 2022-01-04 19:45:17,101 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.00175
freqtrade    | 2022-01-04 19:45:17,102 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.00375
freqtrade    | 2022-01-04 19:45:17,103 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
freqtrade    | 2022-01-04 19:45:17,104 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
freqtrade    | 2022-01-04 19:45:17,106 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
freqtrade    | 2022-01-04 19:45:17,107 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
freqtrade    | 2022-01-04 19:45:17,108 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
freqtrade    | 2022-01-04 19:45:17,109 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: EUR
freqtrade    | 2022-01-04 19:45:17,110 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 10
freqtrade    | 2022-01-04 19:45:17,111 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
freqtrade    | 2022-01-04 19:45:17,112 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 0
freqtrade    | 2022-01-04 19:45:17,114 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'unit': 'minutes'}
freqtrade    | 2022-01-04 19:45:17,115 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
freqtrade    | 2022-01-04 19:45:17,116 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
freqtrade    | 2022-01-04 19:45:17,117 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
freqtrade    | 2022-01-04 19:45:17,118 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.0
freqtrade    | 2022-01-04 19:45:17,119 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
freqtrade    | 2022-01-04 19:45:17,120 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
freqtrade    | 2022-01-04 19:45:17,122 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
freqtrade    | 2022-01-04 19:45:17,163 - freqtrade.resolvers.exchange_resolver - INFO - No Bitvavo specific subclass found. Using the generic class instead.
freqtrade    | 2022-01-04 19:45:17,165 - freqtrade.exchange.exchange - INFO - Using CCXT 1.65.25
freqtrade    | 2022-01-04 19:45:17,218 - freqtrade.exchange.exchange - INFO - Using Exchange "Bitvavo"
freqtrade    | 2022-01-04 19:45:18,244 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-01-04 19:45:18,246 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
freqtrade    | 2022-01-04 19:45:18,641 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
 ```
When error message:
  ```
freqtrade    | 2022-01-04 19:46:33,304 - freqtrade.wallets - INFO - Wallets synced.
freqtrade    | 2022-01-04 19:46:33,319 - freqtrade.data.converter - INFO - Missing data fillup for LINA/EUR: before: 499 - after: 1170 - 134.47%
freqtrade    | 2022-01-04 19:46:33,508 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade for BAT/EUR with stake_amount: 10 ...
freqtrade    | 2022-01-04 19:46:33,564 - freqtrade.data.converter - INFO - Missing data fillup for AVAX/EUR: before: 499 - after: 522 - 4.61%
freqtrade    | 2022-01-04 19:46:33,622 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
freqtrade    | Traceback (most recent call last):
freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 71, in wrapper
freqtrade    |     return command_handler(self, *args, **kwargs)
freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 880, in _forcebuy
freqtrade    |     self._forcebuy_action(pair, price)
freqtrade    |   File "/freqtrade/freqtrade/rpc/telegram.py", line 851, in _forcebuy_action
freqtrade    |     self._rpc._rpc_forcebuy(pair, price)
freqtrade    |   File "/freqtrade/freqtrade/rpc/rpc.py", line 733, in _rpc_forcebuy
freqtrade    |     if self._freqtrade.execute_entry(pair, stakeamount, price, ordertype=order_type):
freqtrade    |   File "/freqtrade/freqtrade/freqtradebot.py", line 562, in execute_entry
freqtrade    |     fee = self.exchange.get_fee(symbol=pair, taker_or_maker='maker')
freqtrade    |   File "/freqtrade/freqtrade/exchange/common.py", line 107, in wrapper
freqtrade    |     return f(*args, **kwargs)
freqtrade    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 1148, in get_fee
freqtrade    |     return self._api.calculate_fee(symbol=symbol, type=type, side=side, amount=amount,
freqtrade    |   File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2099, in calculate_fee
freqtrade    |     cost *= rate
freqtrade    | TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
  ```

**Comment by xmatthias** [comment] 2022-01-04 19:42
in theory, you should be able to work around this by updating ccxt. 

Please try this on the latest develop (simply change the docker tag from `:stable` to `:develop`, i think it will be fixed there.
this should also be possible by simply reusing the existing database, as i assume this error will pop up on every restart.

**Comment by Basbosbaas** [comment] 2022-01-04 19:53
> in theory, you should be able to work around this by updating ccxt.
> 
> Please try this on the latest develop (simply change the docker tag from `:stable` to `:develop`, i think it will be fixed there. this should also be possible by simply reusing the existing database, as i assume this error will pop up on every restart.

Thankyou for your quick reply!
I've changed "image: freqtradeorg/freqtrade:stable" to "image: freqtradeorg/freqtrade:develop" in the docker-compose.yml file.
After that I've done sudo docker-compose pull and he pulled the new freqtrade docker image. but this has not maked sense.

The error message is not on restart but only when I force a buy or when the strategy places a buy order. Those order are not in my overview but are executed because I can see them in my exchange when in live mode.

The CCXT version is used is 1.66.20, the newest is 1.66.23

**Comment by xmatthias** [comment] 2022-01-04 20:54
You're right, i was misled as there was another issue with fee calculation in ccxt last week which was fixed in the meantime.

I've opened an issue for this in ccxt. it seems to be an internal method in ccxt that's failing now (https://github.com/ccxt/ccxt/issues/11124).

**Comment by hdkbouma** [comment] 2022-01-05 07:07
Operating system: Linux Ubuntu
    Python Version: 2.7 / 3.9
    CCXT version: 1.66.20. Trading Bitvavo
    Freqtrade Version: 2021.12

Backtesting crash: freqtrade - ERROR - Fatal exception!
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
freqtrade.exchange.exchange - INFO - Closing async ccxt session.

**Comment by hdkbouma** [comment] 2022-01-05 08:42
2022-01-05 08:19:26,560 - freqtrade.configuration.configuration - INFO - Using config: backtestOffsetIsAug21.json ...
2022-01-05 08:19:26,562 - freqtrade.loggers - INFO - Verbosity set to 0
2022-01-05 08:19:26,562 - freqtrade.configuration.configuration - INFO - Using max_open_trades: -1 ...
2022-01-05 08:19:26,562 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20211228-20220104 ...
2022-01-05 08:19:26,562 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/hdk/freqtrade/user_data ...
2022-01-05 08:19:26,562 - freqtrade.configuration.configuration - INFO - Using data directory: /home/hdk/freqtrade/user_data/data/bitvavo ...
2022-01-05 08:19:26,562 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2022-01-05 08:19:26,565 - freqtrade.configuration.check_exchange - WARNING - Exchange "bitvavo" is known to the the ccxt library, available for the bot, but not officially supported by the Freqtrade development team. It may work flawlessly (please report back) or have serious issues. Use it at your own discretion.
2022-01-05 08:19:26,565 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2022-01-05 08:19:26,565 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-05 08:19:26,568 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2022-01-05 08:19:26,568 - freqtrade.resolvers.exchange_resolver - INFO - No Bitvavo specific subclass found. Using the generic class instead.
2022-01-05 08:19:26,568 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2022-01-05 08:19:26,568 - freqtrade.exchange.exchange - INFO - Using CCXT 1.66.20
2022-01-05 08:19:26,568 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2022-01-05 08:19:26,570 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 200}
2022-01-05 08:19:26,572 - freqtrade.exchange.exchange - INFO - Using Exchange "Bitvavo"
2022-01-05 08:19:27,174 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy OffsetIsAug21 from '/home/hdk/freqtrade/user_data/strategies/OffsetIsAug21.py'...
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - No params for buy found, using default values.
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): base_nb_candles_buy = 24
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): ewo_high = 2.029
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): ewo_high_2 = -3.35
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): ewo_low = -10.04
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): low_offset = 0.99
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): low_offset_2 = 0.972
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): rsi_buy = 63
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): base_nb_candles_sell = 50
2022-01-05 08:19:27,175 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): high_offset = 1.092
2022-01-05 08:19:27,176 - freqtrade.strategy.hyper - INFO - Strategy Parameter(default): high_offset_2 = 1.006
2022-01-05 08:19:27,176 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: EUR.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 500.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: False.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_offset' with value in config file: 0.01.
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.064, '10': 0.029, '38': 0.016, '64': 0}
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.18
2022-01-05 08:19:27,176 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: True
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.061
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.084
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: EUR
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 500
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30, 'exit_timeout_count': 0, 'unit': 'minutes'}
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: False
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_offset: 0.01
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2022-01-05 08:19:27,177 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2022-01-05 08:19:27,177 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-01-05 08:19:27,181 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/hdk/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2022-01-05 08:19:27,183 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/hdk/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/hdk/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting = Backtesting(config)
  File "/home/hdk/freqtrade/freqtrade/optimize/backtesting.py", line 111, in __init__
    self.fee = self.exchange.get_fee(symbol=self.pairlists.whitelist[0])
  File "/home/hdk/freqtrade/freqtrade/exchange/common.py", line 123, in wrapper
    return f(*args, **kwargs)
  File "/home/hdk/freqtrade/freqtrade/exchange/exchange.py", line 1152, in get_fee
    return self._api.calculate_fee(symbol=symbol, type=type, side=side, amount=amount,
  File "/home/hdk/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2101, in calculate_fee
    cost *= rate
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'

**Comment by Basbosbaas** [comment] 2022-01-06 07:22
> You're right, i was misled as there was another issue with fee calculation in ccxt last week which was fixed in the meantime.
> 
> I've opened an issue for this in ccxt. it seems to be an internal method in ccxt that's failing now (https://github.com/ccxt/ccxt/issues/11124).

OK, thank you! Is anyone doing something about this then? Because I can't use my bot right now. Or can I pull another version from docker? Like 2021.11?

**Comment by xmatthias** [comment] 2022-01-06 07:36
> Is anyone doing something about this then

The issue is open in ccxt. You're obviously free to ask there for an update - but from a freqtrade perspective, there's little we can do at this point (while i could attempt to fix the issue in ccxt - i'm unclear on the reason for the changes that caused this - so an attempted fix will most likely move in the wrong direction).

---

you can obviously downgrade (simply use `:2021.11` as tag) - or install an known working ccxt version (like 1.64.1) version in a [custom docker image](https://www.freqtrade.io/en/stable/docker_quickstart/#additional-dependencies-with-docker-compose) - if you want to remain on an uptodate freqtrade version.

**Comment by hdkbouma** [comment] 2022-01-06 10:57
How do you install ccxt-1.64.1? I only know: pip install -U ccxt.

**Comment by Basbosbaas** [comment] 2022-01-06 11:10
I can confirm that my bot is working again with freqtrade 2021.11. So till we get a fix for this bug, I will use this one.

**Comment by xmatthias** [comment] 2022-01-06 12:30
`pip install -U ccxt==1.64.1` ...

**Comment by hdkbouma** [comment] 2022-01-06 20:00
My bot is working again with ccxt 1.64.1

**Comment by xmatthias** [comment] 2022-01-07 06:55
with the latest ccxt version (1.66.32) this is working again.
i've just bumped the version on the develop branch.

**Closed as completed** 2022-01-07 06:55 UTC
Labels: Bug, CCXT

**Comment by hdkbouma** [comment] 2022-01-07 08:54
Freqtrade is working again with ccxt 1.66.32.
Thank you.

**Comment by hdkbouma** [comment] 2022-01-22 10:17
Found existing installation: ccxt 1.66.32
  File "/home/hdk/freqtrade/.env/lib/python3.9/site-packages/ccxt/base/exchange.py", line 2101, in calculate_fee cost *= rate
TypeError: unsupported operand type(s) for *=: 'int' and 'NoneType'
