### ISSUE TITLE
ERROR - unsupported operand type(s) for +: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by myNextCoder** [freqtrade/freqtrade#7333] opened 2022-09-02 08:39 UTC
## Describe your environment

  * Operating system: Windows Server 2022
  * Python Version: _____ (`python -V`)
  * CCXT version: CCXT 1.92.45 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2022.8.dev  (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

With Freqtrade 2022.8.dev the bot stops like this:

2022-09-02 02:11:08,592 - freqtrade.worker - INFO - Bot heartbeat. PID=8272, version='2022.8.dev, strategy_version: v11.2.13', state='RUNNING'
2022-09-02 02:11:26,795 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:11:26,795 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:11:26,810 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:12:20,779 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:12:20,779 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:12:20,795 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:12:21,607 - freqtrade.worker - INFO - Bot heartbeat. PID=8272, version='2022.8.dev, strategy_version: v11.2.13', state='RUNNING'
2022-09-02 02:13:56,295 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:13:56,295 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:13:56,295 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:13:58,107 - freqtrade.worker - INFO - Bot heartbeat. PID=8272, version='2022.8.dev, strategy_version: v11.2.13', state='RUNNING'
2022-09-02 02:13:58,779 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:13:58,779 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:13:58,779 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:03,795 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:03,795 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:03,795 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:08,795 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:08,795 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:08,795 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:13,810 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:13,810 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:13,810 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:18,842 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:18,842 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:18,842 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:23,857 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:23,857 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:23,857 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:28,873 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:28,873 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:28,873 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:33,857 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:33,857 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:33,873 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:38,888 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:38,888 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:38,888 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:43,888 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:43,888 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:43,888 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:48,904 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:48,904 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:48,920 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:53,920 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:53,935 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:53,935 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:14:58,295 - freqtrade.worker - INFO - Bot heartbeat. PID=8272, version='2022.8.dev, strategy_version: v11.2.13', state='RUNNING'
2022-09-02 02:14:58,998 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:14:58,998 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:14:59,013 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:15:19,654 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:15:19,654 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:15:19,654 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:15:36,873 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:15:36,873 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:15:36,873 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:15:54,232 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:15:54,232 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:15:54,232 - freqtrade.freqtradebot - INFO - User denied exit for UNN/USDT.
2022-09-02 02:16:11,404 - freqtrade.freqtradebot - INFO - Exit for UNN/USDT detected. Reason: roi
2022-09-02 02:16:11,404 - freqtrade.wallets - INFO - Wallets synced.
2022-09-02 02:16:11,717 - freqtrade.commands.trade_commands - ERROR - unsupported operand type(s) for +: 'float' and 'NoneType'
2022-09-02 02:16:11,717 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "C:\Users\a5\Freqtrade\freqtrade\commands\trade_commands.py", line 19, in start_trading
    worker.run()
  File "C:\Users\a5\Freqtrade\freqtrade\worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "C:\Users\a5\Freqtrade\freqtrade\worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "C:\Users\a5\Freqtrade\freqtrade\worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "C:\Users\a5\Freqtrade\freqtrade\worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "C:\Users\a5\Freqtrade\freqtrade\freqtradebot.py", line 207, in process
    self.exit_positions(trades)
  File "C:\Users\a5\Freqtrade\freqtrade\freqtradebot.py", line 967, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "C:\Users\a5\Freqtrade\freqtrade\freqtradebot.py", line 1008, in handle_trade
    if self._check_and_execute_exit(trade, exit_rate, enter, exit_, exit_tag):
  File "C:\Users\a5\Freqtrade\freqtrade\freqtradebot.py", line 1032, in _check_and_execute_exit
    exited = self.execute_trade_exit(trade, exit_rate, should_exit, exit_tag=exit_tag1)
  File "C:\Users\a5\Freqtrade\freqtrade\freqtradebot.py", line 1558, in execute_trade_exit
    self._notify_exit(trade, order_type, sub_trade=bool(sub_trade_amt), order=order_obj)
  File "C:\Users\a5\Freqtrade\freqtrade\freqtradebot.py", line 1584, in _notify_exit
    profit = trade.calc_profit(rate=profit_rate) + (0.0 if fill else trade.realized_profit)
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
2022-09-02 02:16:11,748 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-09-02 02:16:11,748 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-09-02 02:16:12,138 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-09-02 02:16:12,138 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "4 open trades active.\n\nHandle these trades manually on Gate.io, or '/start' the bot again and use '/stopbuy' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
2022-09-02 02:16:12,326 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2022-09-02 02:16:12,326 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2022-09-02 02:16:12,326 - apscheduler.scheduler - INFO - Scheduler has been shut down
2022-09-02 02:16:16,888 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.

End of code.

'/status table' after re-starting the bot:

ID     Pair        Since    Profit (USD)
-----  ----------  -------  ---------------
5      UNN/USDT**  6 d      1.95% (0.49)
11     FIN/USDT    4 d      -15.74% (-3.94)
12     DMS/USDT    4 d      -16.76% (-4.20)
13     ZSC/USDT    3 d      0.37% (0.09)
-----  ----------  -------  ---------------
Total                       -7.56 USD

The bot stops again.

Then, after putting the database to Freqtrade 2022.5.1 (CCXT 1.84.63) a few moments later UNN/USDT exits with 1.95% profit. The bot keeps on running under this version.

The same issue happened at the same time on a different bot: After the fatal exception, I move the db to an old Freqtrade version, the pair in question is sold in profit a few moments later, the bot keeps on running.

*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment] 2022-09-02 09:44
2022.8.dev is unfortunately not the complete version. - it's a version range of almost a month.
We'll need the commit to act on this (which should be added to the version at the end in all default install methods) - otherwise we'll have to assume it's because of an outdated version - or rather something that was fixed in the meantime.

Please note that downgrading (especially to versions that are 3 months old) is not supported, and may lead to problems and database corruptions.

**Comment by myNextCoder** [comment] 2022-09-02 11:53
I thank you. Can you post me the version, which I should work with just now? Is this always the latest dev version, as usual?

**Comment by xmatthias** [comment] 2022-09-02 12:15
Well if you're using a dev version - I'd always recommend the latest one (it may update once or multiple times per day).
Alternatively the stable version should be the "go-to" version - if you prefer fewer updates.

While we try to keep the develop version stable at all times - it's not guaranteed, and sometimes there will be changes that are experimental, to have more people help test these changes.

i know 2022.8.dev is not the latest one (it's now 2022.9.dev) - but the version itself is a range of roughly a month - a month where a lot of things changed.
For bug reports, the precise version  (basically the commit) is important for us - as it'll help us determine if we touched the code surrounding this problem since or not.

**Comment by myNextCoder** [comment] 2022-09-02 12:47
I thank you very much. In that case we won't waste our time with any information from my side with 2022.8.dev. I switch to the current version first. If the bug remains, I post any details you need, including the precise version. By the way: This "ROI" error, which stops the bot before selling, happened the first time only very few days ago. Let's hope it is gone after my update.

**Comment by xmatthias** [comment] 2022-09-02 18:07
The only path i can see to this error is having `trade.realized_profit = None`.

Migrations do set this to 0.0 - the value has a default value of 0.0 - and is explicitly initialized to 0.0 - so this is technically impossible - unless you're switching back and forth between versions (which you did - as confirmed above) - which means the trade was created with an older version - but on a database that already was migrated to a new version.

As mentioned above - downgrades are not supported - and can lead to database corruption.

You MAY try to fix this by manually setting the realized_profit values to 0.0 if they're null in the database - but i'm not sure what other parts of the migration may have been missed.

**Comment by dservais** [comment] 2022-09-03 11:48
Following last version installation 2022.8 I have the same error message
 File "/home/didier/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/didier/freqtrade/freqtrade/worker.py", line 74, in run
    state = self._worker(old_state=state)
  File "/home/didier/freqtrade/freqtrade/worker.py", line 114, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs)
  File "/home/didier/freqtrade/freqtrade/worker.py", line 139, in _throttle
    result = func(*args, **kwargs)
  File "/home/didier/freqtrade/freqtrade/worker.py", line 152, in _process_running
    self.freqtrade.process()
  File "/home/didier/freqtrade/freqtrade/freqtradebot.py", line 206, in process
    self.exit_positions(trades)
  File "/home/didier/freqtrade/freqtrade/freqtradebot.py", line 968, in exit_positions
    if trade.open_order_id is None and trade.is_open and self.handle_trade(trade):
  File "/home/didier/freqtrade/freqtrade/freqtradebot.py", line 1009, in handle_trade
    if self._check_and_execute_exit(trade, exit_rate, enter, exit_, exit_tag):
  File "/home/didier/freqtrade/freqtrade/freqtradebot.py", line 1020, in _check_and_execute_exit
    exits: List[ExitCheckTuple] = self.strategy.should_exit(
  File "/home/didier/freqtrade/freqtrade/strategy/interface.py", line 945, in should_exit
    current_profit = trade.calc_profit_ratio(current_rate)
  File "/home/didier/freqtrade/freqtrade/persistence/trade_model.py", line 817, in calc_profit_ratio
    close_trade_value = self.calc_close_trade_value(rate, amount)
  File "/home/didier/freqtrade/freqtrade/persistence/trade_model.py", line 763, in calc_close_trade_value
    return float(self._calc_base_close(amount1, rate, self.fee_close))
TypeError: float() argument must be a string or a number, not 'Precise'

I'm NOT using docker but alocal installation on a Raspberry Pi 4

Can you please help me?
Best regards

**Comment by myNextCoder** [comment] 2022-09-05 10:31
Sorry, for my late answer. Please still not close the ticket. I have to look up your advice. Currently I don't find trade.realized_profit in config_full.example.json nor in the complex strategy NostalgiaForIninityX, which is used by the bot. I won't ever swich again between the Freqtrade versions again, since you told me, not to do it. Isn't trade.realized_profit = None important anymore, if I work on the current stable versions? Currently I work with 2022.8 stable. As soon as I have catched the error within a log file, I post it here.

**Comment by xmatthias** [comment] 2022-09-05 11:21
`realized_profit` is a database column - it's got nothing to do with configuration or the strategy (although the strategy could use it in theory).

**Comment by myNextCoder** [comment] 2022-09-05 21:36
Now I understand. Due to IT-related reasons, I put the bot into a different VM, if needed. Now I have to take care, that there won't be a version downgrade anymore. Very important detail.

**Closed as completed** 2022-09-06 04:18 UTC
Labels: Question

**Comment by hdkbouma** [comment] 2023-03-21 13:46
freqtrade 2023.2
Data: Bitvavo
freqtrade hyperopt -s ElliotV8 -c backtest.json --hyperopt-loss OnlyProfitHyperOptLoss --spaces buy -e 500 --timerange 20230314-20230321
result: 2023-03-21 14:29:30,281 - freqtrade - ERROR - Fatal exception!
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'

**Comment by xmatthias** [comment] 2023-03-21 18:38
@hdkbouma clearly not enough information

but i also don't see this as related to this issue - therefore please open a new issue (make sure to include the full exception - and most likely, logs leading up to that exception).
