### ISSUE TITLE
Backtest missing some trades related to unfilledtimeout - clarification on unfilledtimeout use in Backtest

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#7573] opened 2022-10-11 11:41 UTC
## Describe your environment

  * Operating system: Mac OS Monterey
  * Python Version: 3.9
  * CCXT version:  1.95.30
  * Freqtrade Version: docker-8f2a887a

## Describe the problem:

I have spotted that the backtest misses some of my trades that I expect to open. I have a fairly simple strategy. On investigation I can see that candles & entry signals are populated just fine in the dataframe, and there is no difference between the ones that open and the ones that don't in terms of entry tags, so no issues there.

I tried altering/removing protections, changing config, removing parts of the strategy to simplify, etc to get the trades to open, then when I increased the unfilledtimeout from 6 seconds (running a minute strategy) to 100 secs a few more expected trades executed. I changed it to 1,000 secs and they all did.

Do you have some clarification on how the unfilled timeout affects the backtest?

As per the docs I have no custom pricing elements, although I do have a custom_exit.

`Entry/Exit Timeouts: Entry/exit orders which did not fill (only applicable if custom pricing is used).`

**Comment by xmatthias** [comment] 2022-10-11 13:29
Timeouts can happen either through `unfilledtimeout`, or through the `check_*_timeout()` methods.
if price is not modified (no custom pricing implemented) - then freqtrade will take the candle open price.

Timeouts are always measured against the candle open time.
 `unfilledtimeout` should have no effect if no custom pricing is used.

If you experience something different, then it's most likely a bug.

in which case, please provide a minimum reproduction - which is basically reducing your strategy until it barely reproduces this scenario - together with a timerange and the pairs used that will be necessary to reproduce this - as it's clearly not desired behavior (but i currently can't imagine how it'd be possible, either).

**Comment by alisalama** [comment] 2022-10-11 14:21
Ok I think it is a bug then... (apologies if you've read a slightly different version, I've managed to delete the first half of it so have retyped it).

------
**Evidence**
I've ran the below repro (a simplified part of my strategy) using both 6 seconds unfilled timeout and 10,000 seconds unfilled timeout, and they product different results, specifically some trades are missing from the 6 second version (see screengrab).

```
 "unfilledtimeout": {
        "entry": 6,
        "exit": 6,
        "exit_timeout_count": 0,
        "unit": "seconds"
    },
```

For the 6 seconds version the log says:
`Entry/Exit Timeouts         | 6 / 3`

Different output
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/7068759/195114368-211bc091-de11-4081-9d41-79d4ee225470.png">


------
**Execution Script**

```
docker-compose run --rm freqtrade backtesting --strategy StrategyNotWorking --breakdown day month -p DOGE/USD --fee 0.0000 --timeframe 1m  --timerange=20220114-20220116 --cache none
```
------
**Config Script**

```
{
    "max_open_trades": 1,
    "stake_currency": "USD",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.9999,
    "fiat_display_currency": "USD",
    "timeframe": "1m",
    "dry_run": false,
    "dry_run_wallet": 10000,
    "cancel_open_orders_on_exit": false,
    "trading_mode": "spot",
    "margin_mode": "",
    "fee": 0.000,
    "unfilledtimeout": {
        "entry": 10000,
        "exit": 10000,
        "exit_timeout_count": 0,
        "unit": "seconds"
    },
    "entry_pricing": {
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1,
        "price_last_balance": 0.0,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "exit_pricing":{
        "price_side": "same",
        "use_order_book": true,
        "order_book_top": 1
    },
    "exchange": {
        "name": "ftx",
        "ccxt_config": {},
        "ccxt_async_config": {},
        "pair_whitelist": [
            "DOGE/USD",
        ],
        "pair_blacklist": [
            "ETH/BTC"
        ]
    },
    "pairlists": [
        { "method": "StaticPairList" },
        
    ],    
   ...
    "bot_name": "freqtradev3",
    "initial_state": "running",
    "force_entry_enable": false,
    "internals": {
        "process_throttle_secs": 4
    }
}

```


------
**Strategy File**
Super simple. Buys at 38 mins past the hour and just sells after 55 mins.

```
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter, informative)
from freqtrade.exchange import timeframe_to_prev_date
from freqtrade.persistence import Trade

import freqtrade.vendor.qtpylib.indicators as qtpylib
from os.path import exists
from datetime import datetime, timedelta
import logging
logger = logging.getLogger(__name__);


class StrategyNotWorking(IStrategy):
    """
    This is a sample strategy to inspire you.
    More information in https://www.freqtrade.io/en/latest/strategy-customization/

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the methods: populate_indicators, populate_entry_trend, populate_exit_trend
    You should keep:
    - timeframe, minimal_roi, stoploss, trailing_*
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 3
    
    # Can this strategy go short?
    can_short: bool = False

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "0": 0.99,
        "999": -1,
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.09

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal timeframe for the strategy.
    timeframe = '1m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = True

    # These values can be overridden in the config.
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 1

    # Optional order type mapping.
    order_types = {
        'entry': 'limit',
        'exit': 'limit',
        'stoploss_on_exchange': True,
        'stoploss': 'limit',
    }

    # Optional order time in force.
    order_time_in_force = {
        'entry': 'po',
        'exit': 'po'
    }
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """
        
        # lookup which coin to use for this date
        pair = metadata['pair'].replace("/USD", "");
        dataframe['pair'] = pair;
        
        # add in some dates
        dataframe['datetime'] = pd.to_datetime(dataframe['date'], unit='ms');

        # just buy all coins
        dataframe['buy_coin'] = True; 
        
        # set buy times
        # ------------------------------------
        dataframe['buy_time'] = dataframe['datetime'].dt.minute == 37; # the backtest assumes that all trades get filled immediately

        # print out the latest dataframe
        if self.config['runmode'].value == 'backtest':
            logger.info(f'Finished Populating Indicators - {pair}');
        
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with entry columns populated
        """
        
        # tag up the long entry
        dataframe['enter_long'] = np.where((dataframe['buy_time'] == True ) & (dataframe['buy_coin'] == True ), 1, 0);
        dataframe['enter_tag'] =  np.where((dataframe['buy_time'] == True ) & (dataframe['buy_coin'] == True ), 'bought_here', '');
        
        # print out the latest dataframe
        # if pair == "FTM": dataframe.to_csv(f'./user_data/data/weights/dataframes/dataframe - {self.config["runmode"].value} - {pair}.csv');           
        
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        :param dataframe: DataFrame
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with exit columns populated
        """
        return dataframe
    
    
    def custom_exit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, **kwargs) -> 'Optional[Union[str, bool]]':
        """
        Custom sell signal logic indicating that specified position should be sold. Returning a
        string or True from this method is equal to setting sell signal on a candle at specified
        time. This method is not called when sell signal is set.

        This method should be overridden to create sell signals that depend on trade parameters. For
        example you could implement a sell relative to the candle when the trade was opened,
        or a custom 1:2 risk-reward ROI.

        Custom sell reason max length is 64. Exceeding characters will be removed.

        :param pair: Pair that's currently analyzed
        :param trade: trade object.
        :param current_time: datetime object, containing the current datetime
        :param current_rate: Rate, calculated based on pricing settings in ask_strategy.
        :param current_profit: Current profit (as ratio), calculated based on current_rate.
        :param **kwargs: Ensure to keep this here so updates to this won't break your strategy.
        :return: To execute sell, return a string with custom sell reason or True. Otherwise return
        None or False.
        """
    
        # Get the dataframe and take a filtered copy since the trade opened
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe);
        trade_date = timeframe_to_prev_date(self.timeframe, trade.open_date_utc);
        # logger.info(f'Row Count is : {len(dataframe.index)}');
        
        # get the trade candle
        trade_candle = dataframe.loc[dataframe['date'] == trade_date];
        # turn into object
        trade_candle = trade_candle.squeeze()
            
        # grab a copy of the price history
        price_history = dataframe[dataframe.date >= trade.open_date_utc].copy().reset_index(drop=True);
        
        # if we have some data
        if len(price_history.index) > 0:
            
            # if we have nearly overshot our time, close the trade (this is here so we can have the full data for the trade)
            if ((trade_candle.date + pd.to_timedelta(55, 'minutes')) < current_time):
                # print out trade history in live
                # if self.config['runmode'].value == 'live': price_history.to_csv(f'./user_data/data/trades/Trade {str(trade.id)} - Timed Out Early Trade - {trade.open_date_utc.strftime("%Y-%m-%d %HH-%MM")}.csv');
                return 'Timed Out Trade';
            
        # return maximum stoploss value, keeping current stoploss price unchanged
        return False
```

**Comment by xmatthias** [comment] 2022-10-11 18:21
It's an interesting problem for sure - caused by the way FTX deals with roundings in this case.


the rate one affected trade should be closed is 0.1885455 - with current tick-sizes (0.000005 - [source](https://help.ftx.com/hc/en-us/articles/9821094535700-Updates-to-tick-sizes) - which is an article from 6 days ago) - this will "round" to 0.18855 - which is over the candle's high of 0.188546 - so the price is effectively outside of this candle, having the same effect than using custom pricing - and in the end, resulting in an unfilled order.


now the problem is - the tick-size data is from today (history of that is not available as far as i know) - set by the exchange based on "today's" price (it's not actually updated daily - but i think you get the point) - and tick-sizes are adjusted as prices move - so it could've been completely different in january (when price was 3x the current price).

The base problem of this is described in [this backtest doc section](https://www.freqtrade.io/en/latest/backtesting/#trading-precision-limits).

---

I'm not entirely sure we can (or should) fix that - as it'd effectively mean that we'd be trading on different candles (candles rounded to current price precision).
even if we'd apply the same rounding to the candle's high - we'd end up opening (or closing) the trade outside of the candle - which is clearly wrong.

**Comment by alisalama** [comment] 2022-10-12 10:03
I see the problem, tricky one... It is problematic as it really calls in to question the "accuracy" of the backtest once the tick size reduces. Anything before the change over at a higher decimal count is effectively compromised. The reality is that those trades would have executed given that strategy at that time, and the rounding changes obviously don't matter to the history.

On the random two days I picked and sent it has 9 timeouts. This seems like a large margin of error to me.

-----------

**Investigation**
If you look at the distribution of decimals for historical DOGE prices on FTX on the 1m you can see that for it's entire history it has been mostly at the 6 or 7 decimals level. I have ignored some float rounding at > 10 decimals level on the export to csv.

Decimal place history
![image](https://user-images.githubusercontent.com/7068759/195308548-323eecf7-6279-42d6-9f22-21fad8c8603b.png)

If you look at just October 2022, as of a few days ago it moved to the 5 or 6 decimals level and the 7 decimals disappeared, which means any historical price at a >=7 level is now compromised.

I think effectively we are now placing the last two days distribution on the entire history of prices >=7 decimals, they will disappear and be changed to 5 or 6 decimals. That as it is is ~50% of the historical pricing that we are changing.

![image](https://user-images.githubusercontent.com/7068759/195308682-56b5a813-94c6-444f-a7ea-4181ba25a569.png)

-----------

**Solutions**
Forgive me if this is a naive view, but it seems to me like the historical tick sizes are essentially "baked in" to the historical prices so why the need to round them on the backtest? The candles themselves contain the historical rounding for the price ticks anyway, I guess unless they are generated timeperiods, but you could tackle that on the generation of the candles.

It seems for a backtest it is far more important that the entrys/exits execute at the appropriate time, than that historical prices line up to the current rounding measure that they had to knowledge of at the time.

Otherwise is there a way to trick this into working with custom prices?

I actually have my own backtester which does no rounding on historical candles and that is how I found this issue as they for once didn't line up. I like to use the two to validate the results of each other.

**Comment by xmatthias** [comment] 2022-10-12 11:15
well the rounding is clearly there for a reason (but was only added recently).
There's 2 roundings in place - one for price - and one for amount.

for amount - i see that as critical (especially for futures) - as (some) exchanges limit trading to only full contracts (for example) - so you can't buy 0.5 contract. 
This can make people assume that a low stake-amount will work, while it really doesn't.

for price - it's similar - especially with custom pricing. the moment you use any calculation, you'll (potentially) end up with a price with 16 decimals.
you can't expect any coin to fill  at 0.185010123125123 - every decent exchange will cut the remaining prices - either truncating the price - or rounding that price (slightly different logics per exchange).

obviously changes in these limits are difficult to trace over time - as we only have the "current" information, but not history.
Taking all use cases into account (e.g. leverage) - i don't see us "not trimming" as the correct approach.

---

We'd allow you to enter a trade with 0.18857 - but the FTX rounding defines a step-size of 0.00005 - so you can either use 0.18855 or 0.18860 - but nothing in between. while this seems marginal now - it can have quite a significant impact depending on the actual trade size.

**Comment by alisalama** [comment] 2022-10-12 18:29
I think that all makes sense for a forward looking "actuals" scenario, but I'm not sure it stands up for a backtest. That should really somehow consider or account for the fact that the rounding has changed in order to be "correct".

The backtest candles are now compromised and can effectively be _ignored_ by the rounding. Meaning the strategy does not behave as it would have, or indeed how it would going forward either, because on a go forward basis the trades wouldn't be ignored. Essentially we are rounding trades out of backtesting when they would have in reality executed at that time.

--------------
 
I just tried on a longer term frame (01-13-2021 to now) using the simple strategy above and on XRP 7% of trades are knocked out by the rounding issue, which seems high to me, and on DOGE it is up at 22%! I feel that is too high to be able to trust the backtest anymore.

The strategy is simple but assuming the rounding "issue" are somewhat randomly distributed, then the 7% and 22% rates actually apply to any strategy because we can't open trades on those candles in the backtest.

**Evidence of DOGE**

Using the simple hourly strategy above returns these results. There are no missing candles. I did a clean download just before this, and have checked in another way and came to the same result.

**_Long Term Test_**
```
================== SUMMARY METRICS ==================
| Metric                      | Value               |
|-----------------------------+---------------------|
| Backtesting from            | 2021-01-13 04:07:00 |
| Backtesting to              | 2022-10-12 18:01:00 |
| Max open trades             | 1                   |
|                             |                     |
| Total/Daily Avg Trades      | 11866 / 18.63       |
```

**Missing Trades**
1 - (18.63 / 24) =  22.4%


**_Short Term Test_** - it even occurs on the short time frame. This will obviously be phased out over time as time since the tick size change increases, but it still means the backtest is missing lots of trades as it works now.
```
================== SUMMARY METRICS ==================
| Metric                      | Value               |
|-----------------------------+---------------------|
| Backtesting from            | 2022-09-01 00:00:00 |
| Backtesting to              | 2022-10-12 18:01:00 |
| Max open trades             | 1                   |
|                             |                     |
| Total/Daily Avg Trades      | 788 / 19.22         |
```

**Missing Trades**
1 - (19.22 / 24) =  19.9%

**Comment by alisalama** [comment] 2022-10-12 18:54
Live/Dry Run I think is fine as you've described as we don't care about the historical tick sizes.

**Backtest**

I don't know the full exact logic, so these may not be appropriate, just laying down ideas:

- Round the high / low prices of the candle by the current tick size at the capping price to candle stage so at least the trade will execute. This will have effect of changing the candles for those trades, but we are effectively doing that anyway, so perhaps not a problem.

- Round the entry/exit prices on backtest to an extra decimal place (or two) than advertised. This will allow the vast majority of trades to execute and will keep the price within the candle. A few entries/exits may still be ignored but at a much less vigorous rate. You would still have a problem if the tick size changes by more than 1 decimal place over time, which they obviously will at some point, but that problem will occur over years rather than an immediate switch like it is currently.

- More complicated solution in estimating the decimal places allowed at a time by iterating through the candles. Something like calculate the mode/max of characters post decimal place in the previous x candles and then apply that as the rounding to decimal on the the next x candles. Sounds simple, perhaps could be difficult to implement cleanly.

**Comment by xmatthias** [comment] 2022-10-13 17:48
your strategy above is for 1m, not for 1h.
The moment you move away from 1m, this will be a lot less impactfull -  (and i slightly doubt the value of a backtest from january on 1m candles ...).

I'm also not really sure how you get to your numbers - 24 seems to be taken from "whatever" - pretty much unclear how you're testing here.

There's little point in exaggerating a problem the way you did above (can't trust it anymore) - it's an edge-case that affected ftx/DOGE (and maybe a few selected others).
if you implement an additional filter to avoid 0 volume candles (which you should, especially on very short timeframes), you'll most likely get a different numbers - as that's effectively orders that would probably never fill in live (there's noone home on the other side).

---

i don't think either of your proposal is appropriate.

Rounding price is really only necessary if the strategy messed with the price (otherwise it'll be open in most cases) - so we'll simply move the place of rounding around a bit - which will fix this for your case. 

if the strategy is however changing the price - then we WILL apply rounding based on current metrics. It's obviously at the user's digression to work around this within the strategy if necessary.

**Closed as completed** 2022-10-13 17:54 UTC
Labels: Question, Backtest

**Comment by alisalama** [comment] 2022-10-13 19:18
So essentially the 1min backtest on FTX is not fully supported?

----

I disagree on the value of 1m strategy at a different time period. Running out of time samples is a critical component of building/testing effective models. At least that is what I have been trained in. But either way the 2nd test I provided was for the last 6 weeks and that misses 20% of trades too, so it doesn't work for recent time periods either.

The test I did is just using the simple sample strategy I provided above on the 1m timeframe. It is purely illustrative of the point, obviously not a "real" strategy. It buys once an hour at an arbitrary minute (38) and sells 55 mins later, therefore you would expect it to always trade 24 times a day everyday. It is only trading 19.2 times a day, so ~20% drop off.

I have checked the zero volume candles and they are 2% of the time for the same time period (2022-09-01 to 2022-10-12). So the other 18% are not zero empty volume candles.

If you want me to provide full details I can.

--------------------

I take your point on edge case, and fully understand that moving away from 1m really helps the problem, but it could still occur on any timeframe on any exchange. For example, if the candle high is equal to the open and the high is above 5 at the rounding decimal place it can happen on any time frame. Plenty of candles hit these criteria.

I don't quite follow your point because the strategy I provided, which has the 20% drop off rate on DOGE, is not changing the price, but the rounding is still being applied?

**Comment by alisalama** [comment] 2022-10-13 22:05
Thanks for discussion Matthias. For clarification do you mean that the Freqtrade Backtester doesn't enter/exit trades on candles with zero volume?

**Comment by xmatthias** [comment] 2022-10-14 05:19
> So essentially the 1min backtest on FTX is not fully supported?

i never said that. - it's an edge-case as it's happening on a particular combination of FTX/pair due to some adjustments they made.

if you use the last develop you'll notice that it's no longer happening - unless you modify price yourself - at which point you're however also taking this into your own hands.


> For clarification do you mean that the Freqtrade Backtester doesn't enter/exit trades on candles with zero volume?

Backtesting ignores volume (which in my opinion is the right thing to do). Your trade could be the trade that starts volume - so not filling these orders would be wrong.

**Comment by alisalama** [comment] 2022-10-14 13:47
Thanks for the fix Matthias. Fix seems to work well.

-----------------

The issue was not exclusive to FTX, nor Doge. I tried Bitrex and Binance, and multiple coins. Nor was it exclusive to 1m timeframes, it was having an effect on 5m/30m timeframes too. A few short term test over the last 7 weeks (2022-09-01 to 2022-10-13) below.

I believe it affected any coin under $1 or many decimals on any exchange at any timeframe.

----------------

**BTC on Binance** - to show a complete example that the test was valid and typically executes 24 per day as expected. Similar results on all exchanges for many coins. 
```
================== SUMMARY METRICS ==================
| Metric                      | Value               |
|-----------------------------+---------------------|
| Backtesting from            | 2022-09-01 00:01:00 |
| Backtesting to              | 2022-10-13 20:40:00 |
| Max open trades             | 1                   |
|                             |                     |
| Total/Daily Avg Trades      | 1028 / 24.48        |
```

But for coins with many decimals, mostly under a dollar, the results were not the same. I'm sure there are many more examples.

**Pre Changes** - number denotes trades per day using same test as above
```
DOGE on Binance 1m - 20.5 
DOGE on Binance on 5m candles - 21.5
DOGE on Binance on 30m candles - 22.98
TRX on Binance - 20.20
TRX on Binance on 5m candles - 20.05
XRP on Bittrex - 20.11
Doge on Bittrex 5m candles - 20.05
MATIC on Bittrex - 11.0(!)
```

**Post Changes** - number denotes trades per day - now all seem to be fixed.
```
DOGE on Binance  - 24.52
DOGE on Binance on 5m candles - 24.52
DOGE on Binance on 30m candles - 24.48
TRX on Binance - 24.52
TRX on Binance on 5m candles - 24.5
XRP on Bittrex - 24.52
Doge on Bittrex 5m candles - 24.52
MATIC on Bittrex - 24.52
```

**Comment by xmatthias** [comment] 2022-10-14 13:55
> now all seem to be fixed.

Great, Thanks for confirming - and thanks for  doing an extended test on this! 💯
