### ISSUE TITLE
code":-2010,"msg":"This action disabled is on this account

### ISSUE THREAD

**Issue by 7kOz** [freqtrade/freqtrade#3945] opened 2020-11-14 08:37 UTC
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*
![Screenshot from 2020-11-14 11-06-50](https://user-images.githubusercontent.com/73803569/99143336-9f401580-266d-11eb-8234-8dd7b53422fb.png)
Hello everything is working fine i just have a question some coins only are getting this message tho i enabled margin from api maybe any of you guys has an idea of what the issue is. thanks in advance

**Comment by xmatthias** [comment] 2020-11-14 08:45
duplicate of #3765 (although slightly difficult to find).

*UP and *DOWN pairs are NOT margin pairs, but leveraged pairs in SPOT markets.

You need to visit the page / market view of the coin pair while beeing logged into binance and acknowledge that you understand the risk.
As far as i know, there's no way to do this via the API - so you'll need to do this for every leveraged coin (basically all *UP and *DOWN coins) you want to trade.


The [binance API documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/0bdf8f9f83d1e588b33449958c7584b42f7aaf53/errors.md#messages-for--1010-error_msg_received--2010-new_order_rejected-and--2011-cancel_rejected) even states to connect support - but i don't think that's necessary.

**Comment by 7kOz** [comment] 2020-11-14 08:51
got you thank you so much

**Closed** 2020-11-14 11:37 UTC
Labels: Duplicate, Question

**Comment by testing189** [comment] 2025-04-13 20:45
Bonjour, j'ai un message comme celle ci ( ❌ Erreur lors de l'achat sur Binance : binance {"code":-2010,"msg":"This symbol is not permitted for this account."} lorsque que j'essai de faire un trading d'un pair de crypto via API, comment puisse je résoudre ce problème?

Merci.

**Comment by stash86** [comment] 2025-04-13 21:39
Please open new issue and please use english. Thanks
