### ISSUE TITLE
Huobi Old ticker data

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/freqtrade#1912] opened 2019-06-06 03:53 UTC
## Step 1: Have you search for this issue before posting it?

Related to issue with bitfinex to #1889 

## Step 2: Describe your environment

Python Version: python3.7
CCXT version: 1.18.551
Branch: Master | Develop
  
## Step 3: Describe the problem:

I keep getting "old ticker data" when in reality last ticker data just happened a few seconds ago or minutes.

### Steps to reproduce:

  1. Spin up huobipro
  2. load UC/BTC pair for example
  3. Wait until freqtrade starts looking for signals
  
### Observed Results:

  * What happened?
Kept saying outdated history.
  * What did you expect to happen?
To keep finding opportunities without issues
### Relevant code exceptions or logs:

  ```
 19-06-06 03:51:31,260 - freqtrade.strategy.interface - WARNING - Outdated history for pair BKBT/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,271 - freqtrade.strategy.interface - WARNING - Outdated history for pair QUN/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,285 - freqtrade.strategy.interface - WARNING - Outdated history for pair CVCOIN/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,298 - freqtrade.strategy.interface - WARNING - Outdated history for pair PAY/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,312 - freqtrade.strategy.interface - WARNING - Outdated history for pair ITC/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,325 - freqtrade.strategy.interface - WARNING - Outdated history for pair ZIL/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,338 - freqtrade.strategy.interface - WARNING - Outdated history for pair WTC/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,347 - freqtrade.strategy.interface - WARNING - Outdated history for pair MAN/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,354 - freqtrade.strategy.interface - WARNING - Outdated history for pair ATOM/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,363 - freqtrade.strategy.interface - WARNING - Outdated history for pair EVX/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,371 - freqtrade.strategy.interface - WARNING - Outdated history for pair DBC/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,380 - freqtrade.strategy.interface - WARNING - Outdated history for pair SNT/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,389 - freqtrade.strategy.interface - WARNING - Outdated history for pair GAS/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,397 - freqtrade.strategy.interface - WARNING - Outdated history for pair LSK/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,405 - freqtrade.strategy.interface - WARNING - Outdated history for pair PNT/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,413 - freqtrade.strategy.interface - WARNING - Outdated history for pair BIFI/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,421 - freqtrade.strategy.interface - WARNING - Outdated history for pair XLM/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,429 - freqtrade.strategy.interface - WARNING - Outdated history for pair QSP/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,437 - freqtrade.strategy.interface - WARNING - Outdated history for pair KNC/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,446 - freqtrade.strategy.interface - WARNING - Outdated history for pair GNX/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,454 - freqtrade.strategy.interface - WARNING - Outdated history for pair SWFTC/BTC. Last tick is 231 minutes old
2019-06-06 03:51:31,463 - freqtrade.strategy.interface - WARNING - Outdated history for pair BCD/BTC. Last tick is 231 minutes old
  ```

**Comment by Dante2333** [comment] 2019-06-06 04:48
It's not that it's outdated but since I'm using ta_on_candle and its 1d candle i get this message. Probably should use another message to avoid confusion?

**Comment by xmatthias** [comment] 2019-06-08 18:17
I don't understand why you're getting this (and i'm therefore reopening the issue as i'd like to investigate).

The relevant code shows that we multiply the minutes times 2, adding an offset (5 minutes, by default, but that can be adjusted).

https://github.com/freqtrade/freqtrade/blob/71b7b2482fab1c7b3f90c0e2f28f40552e87ba7e/freqtrade/strategy/interface.py#L225-L233

Testing the ccxt method, i get the correct result of 1440 minutes.
```
import ccxt
ccxt.Exchange.parse_timeframe("1d") // 60
```

**Comment by Dante2333** [comment] 2019-06-09 05:23
It might have nothing to do it ta_on_candle and I dont have a reason to think it does, sorry.
Have you tried pulling it your self from huobi? i'm available through the day so I can provide more information if required.

**Comment by xmatthias** [comment] 2019-06-09 11:05
i did now ... and it's quite simple and the cause is #1715 - so the last candle is assumed to be incomplete and therefore removed (which is wrong for Huobi, but correct for binance).

I've got an idea for a generally applicable fix for this...

**Comment by Dante2333** [comment] 2019-06-09 13:00
Thanks! hopefully this will improve huobi and we can make it an "verified" exchange.

**Comment by xmatthias** [comment] 2019-06-09 13:06
to test this no API keys are necesary - (see the PR #1915) ... OHLCV data is usually publicly accessible ... see the script in the PR (developer.md) on how to test for this (use any timeframe you can think of ...)

**Closed** 2019-06-10 12:58 UTC
Labels: bug
