### ISSUE TITLE
Nonce problem

### ISSUE THREAD

**Issue by elestranobaron** [freqtrade/freqtrade#6526] opened 2022-03-12 18:55 UTC
Hello i have docker on raspberry pi version since one week and a half installed, there were no problems until today nonce error.

So i see you suggest to change the timezone and indded i ssaw the hour in docker is an hour less than in the host system.

But i can't use sudo as i don't know the password for ftuser. Is there a root password ?

Many thanks in advance

**Comment by xmatthias** [comment] 2022-03-12 19:12
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

A nonce error is "usually" a sign of a non-syncronized clock. 
Make sure that you're using some system to syncronize to the global clock system (usually ntpd or chronyd) - and that it's running frequently (ccxt recommends at least every 10 minutes).

The "timezone-missmatch" will not matter as much. the time itself will align - but docker will display the time in UTC, while the raspberry may use a different timezone. 
While there are ways to fix this at a docker level - it's not the cause for this issue.

**Comment by elestranobaron** [comment] 2022-03-12 22:23
here a few logs , but i still dont get it i cant start docker anymore and the logs give way too much lines (still running since 5 min)

```
  File "/freqtrade/freqtrade/exchange/exchange.py", line 824, in fetch_order
    raise TemporaryError(
freqtrade.exceptions.TemporaryError: Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}
2022-03-12 06:44:54,133 - urllib3.connectionpool - WARNING - Connection pool is full, discarding connection: api.kraken.com. Connection pool size: 10
2022-03-12 06:44:54,148 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}". Retrying still for 5 times.
2022-03-12 06:44:56,933 - freqtrade.exchange.common - WARNING - get_balances() returned exception: "kraken {"error":["EAPI:Rate limit exceeded"]}". Giving up.
2022-03-12 06:44:56,934 - freqtrade.freqtradebot - WARNING - Unable to sell trade LTC/EUR: kraken {"error":["EAPI:Rate limit exceeded"]}
```

**Comment by elestranobaron** [comment] 2022-03-12 22:48
finally i could start docker but this problem occurs when it wants i dont get it

**Comment by xmatthias** [comment] 2022-03-13 06:00
> Make sure that you're using some system to syncronize to the global clock system (usually ntpd or chronyd) - and that it's running frequently (ccxt recommends at least every 10 minutes).

The error means that your clock is out of sync. 
exchanges usually check the timestamp of the system that's calling it vs. their own clock - and if your clock is wrong, they refuse your request (due to security measures).

**Comment by elestranobaron** [comment] 2022-03-13 06:54
is there a root password or password for ftuser in the docker ? i can't apt install shit

**Comment by hariombansiwa** [comment] 2022-03-13 08:10
what's the root password for docker container?

**Comment by hariombansiwa** [comment] 2022-03-13 08:13
I also have a clock mismatch issue in live trading mode and i am not able to sync clock, timezone is also utc and local time again would be different, running docker on windows.

**Comment by hariombansiwa** [comment] 2022-03-13 08:20
@xmatthias : I am new to this, i am not able to find out the template, however my issue is same as time sync problem on docker, would it be possible for you to provide the **root password** of the container.

Issue:  ccxt.base.errors.InvalidNonce: binance {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}

**Comment by xmatthias** [comment] 2022-03-13 12:58
you cannot technically fix this WITHIN the docker container - but you must fix it on the host system.

Docker receives the time from the host system - and modifying the time from within the docker container is not possible (by default) due to security measures in the linux kernel.

As such - the root password in the container is irrelevant - but it's empty iirc - we're at least not setting it explicitly in our docker files.

**Comment by elestranobaron** [comment] 2022-03-13 18:14
Ok so i have the same problem with pihole also

I didnt find any better option than to destroy the container and recreate it with -v /etc/localtime:/etc/localtime:ro

**Comment by elestranobaron** [comment] 2022-03-13 18:19
which gives me:

``` sudo docker-compose run --rm --service-ports -v /etc/localtime:/etc/localtime:ro --name freqtrade -d freqtrade trade --config user_data/config.json --strategy ok```

service ports is because i don't use compose up - also don't forget that it overrides compose file settings with what is passed afterwards

**Comment by xmatthias** [comment] 2022-03-13 19:09
if you're using `docker-compose run` - i think the container will stop once you logout from your box - so make sure that you use tmux or screen or similar ways to keep it running anyway.

**Comment by elestranobaron** [comment] 2022-03-13 19:32
not as long as you use -d

**Comment by xmatthias** [comment] 2022-03-13 22:10
i don't understand the benefit of not using "up".
You'd have the full command "persisted" in the compose file - wheres with this, there's little benefits over plain docker - you'll still have to remember the full command (or have it stored somewhere)

**Comment by elestranobaron** [comment] 2022-03-13 23:42
talked too quick time is ok now but i stille got the error 

2022-03-14 00:40:24 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair FEE.
2022-03-14 00:40:28 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}". Retrying still for 5 times.
2022-03-14 00:40:29 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}". Retrying still for 5 times.
2022-03-14 00:40:32 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}". Retrying still for 4 times.
2022-03-14 00:40:35 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}". Retrying still for 3 times.

**Comment by elestranobaron** [comment] 2022-03-14 00:01
at first it seemed to be ok

2022-03-14 00:39:08 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2022.2.1', state='RUNNING'
2022-03-14 00:39:11 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=ATOM/EUR, amount=0.20842712, open_rate=23.98920000, open_since=2022-03-13 23:30:04)
2022-03-14 00:39:21 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=ATOM/EUR, amount=0.20842712, open_rate=23.98920000, open_since=2022-03-13 23:30:04)
2022-03-14 00:39:31 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=ATOM/EUR, amount=0.20842712, open_rate=23.98920000, open_since=2022-03-13 23:30:04)
2022-03-14 00:39:41 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=ATOM/EUR, amount=0.20842712, open_rate=23.98920000, open_since=2022-03-13 23:30:04)
2022-03-14 00:39:51 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=ATOM/EUR, amount=0.20842712, open_rate=23.98920000, open_since=2022-03-13 23:30:04)
2022-03-14 00:40:00 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=ATOM/EUR, amount=0.20842712, open_rate=23.98920000, open_since=2022-03-13 23:30:04)
2022-03-14 00:40:24 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair FEE.
2022-03-14 00:40:24 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair FEE.
2022-03-14 00:40:24 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair FEE.
2022-03-14 00:40:28 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Could not get order due to InvalidNonce. Message: kraken {"error":["EAPI:Invalid nonce"]}". Retrying still for 5 times.

**Comment by elestranobaron** [comment] 2022-03-14 00:03
I know i use wsl2 but im connecting via ssh on raspberry pi so it should be ok

**Comment by elestranobaron** [comment] 2022-03-14 04:32
BUT, after rthat, it could sell normally

```

2022-03-14 05:13:31 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': sell_fill, 'trade_id': 3, 'exchange': 'Kraken', 'pair': 'LINK/EUR', 'gain': 'profit', 'limit': 11.83627, 'order_type': '', 'amount': 0.42998694, 'open_rate': 11.62826, 'close_rate': 11.83627, 'current_rate': None, 'profit_amount': 0.06820858, 'profit_ratio': 0.01361992, 'buy_tag': None, 'sell_reason': 'roi', 'open_date': datetime.datetime(2022, 3, 13, 23, 50, 50, 82648), 'close_date': datetime.datetime(2022, 3, 14, 4, 13, 25, 27114), 'stake_currency': 'EUR', 'fiat_currency': 'EUR'}
2022-03-14 05:13:31 - freqtrade.rpc.telegram - INFO - Notification 'sell_fill' not sent.
2022-03-14 05:13:34 - freqtrade.freqtradebot - INFO - Pair LINK/EUR is still locked until 2022-03-14 04:15:00 due to Auto lock.
2022-03-14 05:14:13 - freqtrade.rpc.rpc - WARNING -  Could not get rate for pair FEE.
```

That happens every once in a while one d say

**Comment by xmatthias** [comment] 2022-03-14 05:36
let me link to my very first response https://github.com/freqtrade/freqtrade/issues/6526#issuecomment-1065945836 - and repeat what i said there.

> Make sure that you're using some system to syncronize to the global clock system (usually ntpd or chronyd) - and that it's running frequently (ccxt recommends at least every 10 minutes).

You need to make sure that the time sync on your raspberry (not in docker, but on the raspberry pi!) is running regularily, against reliable time servers.

The way you describe it, it sounds like the ntp sync is only running every few hours (maybe less) - so it'll stop working for a few hours (it's called time drift) - "syncs the time again" so it's working again, only to lose sync again a while later.

Raspberries don't have a proper hardware clock iirc - so they're extra prone to this and need careful configuration.

**Comment by elestranobaron** [comment] 2022-03-14 18:25
Ok so i installed ntp and finally i'm not sure docker needed to be put on same date than host as that was not the cause apparently

**Comment by elestranobaron** [comment] 2022-03-14 18:28
i'm already at six wins to zero with this strategy by the way minimal_roi = {
        "120": 0.013,
        "60": 0.02,
        "30": 0.03,
        "0": 0.04
    }

**Comment by elestranobaron** [comment] 2022-03-15 20:38
(don't forget to blacklist stablecoins)

**Comment by xmatthias** [comment] 2022-03-16 05:35
Closing this as i think your problem has now been fixed.

**Closed as completed by xmatthias** 2022-03-16 05:35 UTC
Labels: Question
