### ISSUE TITLE
bibox fetchcurrencies error

### ISSUE THREAD

**Issue by sanitariu** [freqtrade/freqtrade#2474] opened 2019-11-05 10:34 UTC
Hello,
I am testing other exchanges and saw the following error:

2019-11-05 12:32:07,463 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: bibox fetchCurrencies is an authenticated endpoint, therefore it requires 'apiKey' and 'secret' credentials. If you don't need currency details, set exchange.has['fetchCurrencies'] = False before calling its methods.
2019-11-05 12:32:07,463 - freqtrade - ERROR - Fatal exception!

Seems like bibox requires auth via API before fetching currencies.
Can we add an option in config file like requireauth (true/false) so code can pass it ?

**Comment by xmatthias** [comment] 2019-11-05 11:25
What's the command you use?

For Utils (and backtesting), we (intentionally) remove the credentials.
this will protect your API keys - since they'll not be exposed to the network without need.

For dry / live runs - keys are not removed so you should be able to use that mode.

**Comment by xmatthias** [comment] 2019-11-05 11:43
#2476 will introduce one method where this is done - so to do tests with unsupported exchanges, one simple return-statement will suffice.

Since this is an edge-case on a unsupported exchange - i don't think it makes sense to expose it via a configuration setting - since only users with experience in the freqtrade code should try to implement new exchanges.

**Comment by sanitariu** [comment] 2019-11-05 12:29
Ok i will wait for 2476. I already put my credentials in my config-bibox.json but nobody reads them.
Seems like for any tests (job)  on that exchange need to pass credentials.

**Comment by xmatthias** [comment] 2019-11-05 13:03
that's possible - but honestly, if it fails "this early" there are high hopes that it'll fail later down the road too...

you can look at [the new exchange docs](https://www.freqtrade.io/en/latest/developer/#implement-a-new-exchange-wip)  in the meantime to verify if ohlcv data is available or not ... (and with enough candles per call).

**Comment by sanitariu** [comment] 2019-11-05 13:06
Ok then leave it. I was trying to test as much as possible exchanges which can work with freqtrade.
At least most of high volume ones.
Seems like bibox is too complicated.
Lets close the ticket for now.

**Comment by xmatthias** [comment] 2019-11-05 13:08
well that's not said - maybe the auth is the only thing that's blocking it - and if it is, we can find ways around it (but i wouldn't implement these if it won't work in the future anyway).

Just pointed out the checks i did before deciding if an exchange has good hopes to work ... ;)

**Comment by hroff-1902** [comment] 2019-11-05 16:26
I have a solution in my stashes... (got to it when was testing `list-pairs` for all available exchanges)

**Comment by hroff-1902** [comment] 2019-11-05 18:42
#2476 does not close it

**Comment by xmatthias** [comment] 2019-11-05 18:44
from #2476:

> It does not say that it will work without credentials, it says that it needs credentials for fetchCurrencies()...

yes - but fetchCurrencies() is part of load_markets() - which IS a requirement for everything we use (including list-markets)...

>#2476 does not close it

i disgree for 2 reasons:
* the user closed it, not me nor the PR
* it enables testing of this exchange. I would not invest any time in trying to make something configurable where we're not sure it'll work in the end ...

**Comment by hroff-1902** [comment] 2019-11-05 18:55
The reason for this issue is the following in ccxt:

https://github.com/ccxt/ccxt/blob/be6786335454db25171ed8d742605309abe47215/python/ccxt/base/exchange.py#L1252-L1254

for bibox, the ccxt exchange implementation does not contain exchange-specific fetch_markets, so this one is called. However, it does contain fetch_currencies(), as you can see from the code above, `load_markets()` calls `fetch_currencies()`.

Actually, `fetch_currencies()` is not really needed here (it's useful, provides many details on currencies, but this info is not really needed in the generic `load_markets()`). This API entry on bibox exchange is private and causes this error.

As you can see, if `self.has['fetchCurrencies']` is False, the generic implementation will gracefully fallback to calling the generic `set_markets()`. That's what is needed for this exchange: simple set `ft_has['fetchCurrencies'] = False` for bibox.

**Comment by xmatthias** [comment] 2019-11-05 19:17
The solution to this is simpler than we thought it is.
Please put the following in your config (the key is the line with "has") - the rest should be in the default-configuration already.

```
        "ccxt_config": {
            "enableRateLimit": true,
            "has": {"fetchCurrencies": false}
        },
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 500,
            "has": {"fetchCurrencies": false}
        },

```

You'll then need to use `freqtrade --config ThisConfig.json list-pairs` (and other commands). 
Please let us know if the exchange shows other problems.

**Comment by hroff-1902** [comment] 2019-11-05 19:21
This should in this case be in a `config_bibox.json.example` than.

**Comment by xmatthias** [comment] 2019-11-05 19:23
Should the exchange be confirmed working - and all other operations work, then yes (or it'll be subclassed to make this easier).

However for now it's for testing by @sanitariu only, since noone of us has an account on this exchange.

**Comment by sanitariu** [comment] 2019-11-06 08:30
Yes thank you for the fixes. I am going to test it now by downloading data and other commands....

**Comment by sanitariu** [comment] 2019-11-06 08:36
I confirm that after adding "has": {"fetchCurrencies": false} the following commands at bibox are working: 'list-timeframes', 'list-markets', 'list-pairs', 'download-data'
I may try real trading now if i find good pairs.
Thank you for the fixes !!! Very good support from you people :)

**Comment by xmatthias** [comment] 2019-11-06 09:12
Let us know if the "rest" works, so we can add this "fetchCurrencies:false" fix permanently for this exchange - removing this "circumstance", thanks.

**Comment by hroff-1902** [comment] 2019-11-06 09:26
Opened the issue back till the reporting results for the 'rest', so it's still open...

**Closed** 2019-11-13 18:52 UTC
Labels: Question

**Comment by hroff-1902** [comment] 2019-11-13 18:57
@sanitariu pls verify the solution (it should now work without that "has" item in the config)

**Comment by sanitariu** [comment] 2019-11-13 21:47
I confirm it is working without has in main config json file.
