### ISSUE TITLE
Error: stat: cannot statx '/freqtrade/user_data/data/bitvavo/*': No such file or directory

### ISSUE THREAD

**Issue by Johan1974** [freqtrade/freqtrade#9044] opened 2023-08-13 21:43 UTC
## Describe your environment

- **Operating system:** Ubuntu 22.04 LTS
- **Python Version:**   3.11.4
- **CCXT version:**  4.0.36
- **Freqtrade Version:** 2023.7
  
## Your question

I am encountering an issue where my Freqtrade bot running within a Docker container is unable to access a specific directory despite the fact that the directory is present. I am receiving the error message: "Error: stat: cannot statx '/freqtrade/user_data/data/bitvavo/*': No such file or directory."

**Problem Details:**
- I have set up a Freqtrade bot within a Docker container using a Docker Compose configuration.
- I have a directory named `bitvavo` within the `/freqtrade/user_data/data/` directory within the container.
- The program is configured to access files or directories within the `bitvavo` directory.
- The program is able to log information that indicates it is aware of the `bitvavo` directory's path.
- Despite the logs indicating the correct path, I am still encountering the "No such file or directory" error.
- The path I am using is verified to be accurate and free of typos.
- I have checked the permissions and ownership of the `bitvavo` directory and its contents to ensure they are appropriate.

**Troubleshooting Steps Taken:**
- I have confirmed the existence of the `bitvavo` directory within the container.
- I have reviewed the program's configuration and code to ensure that the correct path is being used.
- I have attempted to navigate to the `bitvavo` directory and list its contents from within the container's command line, this is where i get to see the error
- I have verified that I am using absolute paths and not wildcards in my code.
- I have examined the program's log files for additional information about the error, but the logs indicate that the program is aware of the `bitvavo` directory's path.

**Request for Assistance:**
I am seeking assistance in diagnosing and resolving this issue. Despite the program being aware of the directory's path and the directory's verified existence, I am consistently encountering the "No such file or directory" error. I am looking for guidance on further steps to troubleshoot and resolve this issue.

**Additional Information:**
- I am using the latest stable version of the Freqtrade image.
- My Docker Compose configuration is correctly mounting volumes, and other aspects of the bot are functioning as expected.
- The issue seems to be specific to accessing this directory within the container.

Thank you for your assistance in helping me resolve this problem.

**Comment by xmatthias** [comment] 2023-08-14 05:30
While you've provided a quite extensive description - the most important thing is missing - logs.

You can describe many things - but logs will tell at what point there's an actual problem, what the bot is actually trying to do.

It's also quite difficult to trust in "all permissions are correct, all mounts are correct" - if this were the case, you'd not be having a problem in the first place.

**Comment by xmatthias** [comment] 2023-08-15 17:58
A quick google search for your issue shows some (older) issues with system compatibility (https://github.com/debuerreotype/docker-debian-artifacts/issues/97).

while i don't believe that you're running into the exactly same issue (the issue is pretty old, and 22.04 LTS shouldn't have these libraries) - it's something to check for sure.

Best check if you're on the required system libraries (this is the host system we're talking about) - you can also check if system access works on a random image. 

---

The issue linked above points in another direction as well though (between the lines, really) - which is system calls, or systems preventing system calls.
You may run into such issues if you're on a locked-down / hardened system, which is preventing docker filesystem access in general.
The way it looks for now is though that it's not something that's freqtrade related, but an issue that's related to the docker configuration of the host / the host configuration in general.

Please do the "file system access" test on a non-freqtrade docker image - my suspicion is that you'll encounter the same problems - in which case, you're best bet is to follow docker support channels - as that's an issue that would go way beyond what we can reasonably support you with.

**Comment by xmatthias** [comment] 2023-08-20 06:55
Closing this as i think your question has been answered.

Feel free to comment below if it's still unclear, or if the above doesn't help/fix your problem.

**Closed as completed by xmatthias** 2023-08-20 06:55 UTC
Labels: Question, Docker
