### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by raftersvk** [freqtrade/freqtrade#7660] opened 2022-10-30 06:50 UTC
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: Python 3.9.12
  * CCXT version: 2.0.58
  * Freqtrade Version: 2022.10
  
## Describe the problem:
Running hyperhopt with the following command crashes :
freqtrade hyperopt -s MGMomentumV3 -c user_data/mgm-config.json -c user_data/mgm-config-private.json --timerange 20210701-20220416 --spaces buy sell -e 15 -j 10 --hyperopt-loss MGM_WeightedMultiParameterHyperOptLoss

### Steps to reproduce:
Let me know if you need the complete custom : config / strat  / hyperhopt files

### Observed Results:
  ```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 735, in reducer_override
    return _class_reduce(obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 445, in _class_reduce
    return _dynamic_class_reduce(obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 429, in _dynamic_class_reduce
    _make_skeleton_class, _class_getnewargs(obj), _class_getstate(obj),
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 122, in _class_getnewargs
    _get_or_create_tracker_id(obj), None)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 107, in _get_or_create_tracker_id
    class_tracker_id = _DYNAMIC_CLASS_TRACKER_BY_CLASS.get(class_def)
  File "/usr/lib/python3.9/weakref.py", line 453, in get
    return self.data.get(ref(key),default)
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/loky/backend/queues.py", line 125, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/loky/backend/reduction.py", line 211, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/loky/backend/reduction.py", line 204, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 15, in __reduce__
    _pickled_object = dumps(self._obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 639, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Freqtrade-MGM/freqtrade/main.py", line 39, in main
    return_code = args['func'](args)
  File "/root/Freqtrade-MGM/freqtrade/commands/optimize_commands.py", line 107, in start_hyperopt
    hyperopt.start()
  File "/root/Freqtrade-MGM/freqtrade/optimize/hyperopt.py", line 606, in start
    f_val = self.run_optimizer_parallel(parallel, asked)
  File "/root/Freqtrade-MGM/freqtrade/optimize/hyperopt.py", line 416, in run_optimizer_parallel
    return parallel(delayed(
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/root/Freqtrade-MGM/.env/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.

  ```

**Comment by xmatthias** [comment] 2022-10-30 07:19
i know this doesn't happen with the sample strategy (that would break CI) - therefore we'll for sure need the full data (strategy, config) to even attempt to look at this.

if your strategy is pretty complex, please reduce it to the necessary part to reproduce this issue.

**Comment by raftersvk** [comment] 2022-10-30 07:39
you're right it is a complex strat, so I am not sure where to start to reduce the complexity.
I can also try to debug on my own... if you give me some hints on where to look at ?

**Comment by xmatthias** [comment] 2022-10-30 08:25
not really, no. the strategy seems to be using some object that cannot be pickled (an open socket, Queue, open file, ...) ...

Debugging such a thing is always difficult - simply start by removing things one by one (or start from a plain strategy and go the other way, adding things one after the other).

**Comment by xmatthias** [comment] 2022-11-05 10:15
Did you find something? or is there something we can still help you with? Otherwise i'd close this issue - as i don't really see anything actionable from our side.

**Comment by raftersvk** [comment] 2022-11-06 17:22
so far I haven't been able to find out the reason behind my problem.
What I can add is :
 - hyperopt is working fine if I launch on a single thread
 - the same strategy was working/hyperopting fine before : update to interface version 3 and update of freqtrade with its requirements

**Comment by xmatthias** [comment] 2022-11-06 18:33
the problem is that there's "something" that makes your strategy no longer picklable (it can be pickled, but not unpickled).

As other strategies work fine, it must be something in your strategy. Without the strategy though - impossible to assist you further.

**Comment by raftersvk** [comment] 2022-11-07 20:45
here is a zip file with the strat and the config file.
i have started to comment parts of the code to try and figure out where the problem lies, but without luck so far.
[MGMomentumv3.zip](https://github.com/freqtrade/freqtrade/files/9955264/MGMomentumv3.zip)

**Comment by xmatthias** [comment] 2022-11-08 06:01
Quite honestly - you're using a strategy that imports from a symlink (so the zipfile doesn't even include the whole strategy). That symlinked file could also be creating a circular import, or whatever else - but it's clearly something that should be looked at with eagle eyes.
It's modifying path (which is unnecessary and potentially problematic, which could lead to problematic imports again - depending on other content in the directory).

The strategy then uses a class-decorator (never tried that - potentially problematic depending on it's content?)


Your best bet is to try the sample strategy freqtrade provide. If that hyperopts, it's clearly the strategy's fault.

The provided data is incomplete (so the above is all i can provide) - but provides enough info to know where to direct you to.

The strategy seems to come from  [MoniGoMani](https://github.com/Rikj000/MoniGoMani). 
They're the experts with that strategy so best ask for help in their support channels.
honestly, i'll not even try to look at a strategy for problems that's >1000 lines long.

**Closed as completed by xmatthias** 2022-11-08 06:01 UTC
Labels: Hyperopt, Strategy assistance

**Comment by raftersvk** [comment] 2022-11-09 07:17
thank for your answer.
just as info : 
the symlink problem you mentioned is actually just something that happened while I retrieved from the server where the hyperopt runs to my local storage but on the server the strategy file is present directly in the strat folder. so sadly this isn't the real cause.

i will now look into the rest you pointed out (since I am also part of the MonigoMani dev team :p ).
