### ISSUE TITLE
Option for Binance futures 

### ISSUE THREAD

**Issue by Jacksparrowoo1** [freqtrade/freqtrade#5173] opened 2021-06-22 14:22 UTC
Is is possible to trade in Binance futures ,may be in future update. 
If it is possible then it would be great because not every time market is in uptrend or a bull run.
Trend following strategies perform better in up trending market situation. and full 24hrs of a day can be utilized by the Bot

**Comment by xmatthias** [comment] 2021-06-22 17:19
Please use the search to find duplicate issues before posting new ones.

Duplicate of #2312, #902 and partially #2183.

**Closed as completed by xmatthias** 2021-06-22 17:19 UTC
Labels: Duplicate

**Comment by samgermain** [comment] 2021-07-20 19:28
Working on it, #5157 

If you would like to contribute to the implementation, message me on discord samwow#2769
