### ISSUE TITLE
Liquidation price set to `None`

### ISSUE THREAD

**Issue by raphaelstar** [freqtrade/freqtrade#8090] opened 2023-02-01 11:26 UTC
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10
  * CCXT version: 2.5.39
  * Freqtrade Version: 2023.1
  
## Describe the problem:
The condition `if isolated_liq:` is `False` when `isolated_liq == 0.0` and the function wrongly returns `None` here:
https://github.com/freqtrade/freqtrade/blob/fb742361e9cabaf49eddffb8ce5c2864ac85a96f/freqtrade/exchange/exchange.py#L2734

### Observations:
 1 - The exchange returns a liquidation price of 0.0
 2 - The liquidation price is set to `None` instead of a `float` number.

**Comment by xmatthias** [comment] 2023-02-01 11:29
is this causing some problem (then please provide a stacktrace of an error) - or is it just some observation which has no real impact?

I'm not aware of any exchange/pair combination which would return a liquidation price of 0 either - so is this something you really observed? (if yes, please provide the details to actually reproduce this).

**Comment by raphaelstar** [comment] 2023-02-01 11:46
Okx is returning a liquidation price of 0.0 when a long position with no leverage is opened.
I don't know the impact of having an unset liquidation price when it should be set to `buffer_amount` instead.
I am reporting this as a potential cause of downstream issues.

**Comment by raphaelstar** [comment] 2023-02-02 10:17
Side note:
I found this by tracking a another bug. I noticed that a trade had a liquidation price of `None`. I initially though that it may be related to the bug I was tracking. Found out it was not the case, but it made me lose time to explore this path.
So even if the impact/consequence/problem is not apparent for the end-user, it is definitely impact-full for the developers.
Yet, the solution to this is trivial: simply change the test to `if isolated_liq is not None`.
I don't understand why it is being debated, the current code doesn't satisfy the coding best practice, this alone should be a sufficient reason to fix it.

**Comment by xmatthias** [comment] 2023-02-02 11:20
> I don't understand why it is being debated, the current code doesn't satisfy the coding best practice, this alone should be a sufficient reason to fix it.

I don't understand either.

---

Please keep in mind that this is an open source project.

freqtrade is not a product you paid for, and are now paying a subscription to get continuous support from people being paid to fix non-relevant issues as "it's not best practice" in your opinion, but it's people trying to help and improve the project in their free time.
Coming here and demanding "this needs to be changed because i think it should, and had me lose time" is not good community behavior.

You think it must be changed (apparently with urgency - as you'll notice i did NOT close the issue) - submit a Pull request.
A guide for the github PR workflow can be found [here](https://guides.github.com/introduction/flow/).

I will look at it eventually - but this has 0 priority for me - so it could be in a week, or in a year - whenever i have time. 
It's not a bug (nothing is broken because of it) - so all other issues - which actually contain problematic behavior - will have higher priority.

**Comment by raphaelstar** [comment] 2023-02-02 12:06
> I will look at it eventually - but this has 0 priority for me. It's not a bug (nothing is broken because of it).

This is a bug. Having a liquidation price set to `None` is not the expected behavior of the software. The fact that the end user is not impacted doesn't make it less a bug (!!!).

> it's people trying to help and improve the project in their free time.

Yes, and I am one of those people.

> Coming here and demanding "this needs to be changed because i think it should, and had me lose time" is not good community behavior.

You are implying that I am having egoistic motivations. It cost me resources to report those issues. I could continue working on my own fork, fix the issues for myself, and not lose time making reports here. Besides, I am not expressing my own opinion, it is common knowledge that implicit comparisons are bad:  https://rickardlindberg.me/writing/python-danger-implicit-if/

> You think it must be changed (apparently with urgency - as you'll notice i did NOT close the issue) - submit a Pull request.

There is no urgency. I am just trying to understand why I need to put such effort into trying to convince you that this issue is an actual problem.

**Comment by xmatthias** [comment] 2023-02-02 12:29
You look for the line - and suggest the fix.
Why exactly not make a PR? it'd cost you much less time/effort than to convince someone else to actually implement your fix - and it'd help the project more.

I'm not arguing that reporting issues is helping the project - it clearly is. 
But the way you report them (sometimes by including the fix) - a PR is time better spent - and would also give you appropriate credit (github counts commits as contribution to a project - but issue reporting "not really").

>  I could continue working on my own fork, fix the issues for myself, and not lose time making reports here.

This already implies that you do have the knowlege to implement the fix - so why not make the final step - and do the actual contribution?

**Comment by raphaelstar** [comment] 2023-02-02 12:42
> Why exactly not make a PR?

Simply because, given the interactions we had so far, you give the impression that you would make the review process a painful experience.

**Comment by xmatthias** [comment] 2023-02-02 12:46
For a fix like this - surely not. 

It's different if we get a whole function dumped in an issue comment with "this would fix it" - which completely obfuscates what actually changed (maybe it's a minor change of 2 lines, or the whole function is different). 

having that as a PR helps - as it clearly shows what changed - and allows to comment by line.
Now depending on the case - i'd obviously still want a "why" - especially if it's a functional change - but having it available as "i'd propose it this way - which would change these 3 lines" makes the whole process much simpler - as we both know what we're talking about precisely - without mentioning (potentially changing) line numbers.

**Closed as completed** 2023-02-02 13:53 UTC
Labels: Question, Non-spot
