### ISSUE TITLE
unable to use hyperopt

### ISSUE THREAD

**Issue by Orbazz** [freqtrade/freqtrade#6904] opened 2022-05-30 15:47 UTC
## Describe your environment

  * Operating system: window 10 ____
  * Python Version: ___3.10__ (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _3___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:
unable oto user hyperopt
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.
2022-05-30 15:42:52,790 - freqtrade.configuration.config_validation - WARNING - DEPRECATED: Using 'buy' and 'sell' for time_in_force is deprecated.Please migrate your time_in_force settings to use 'entry' and 'exit'.
2022-05-30 15:42:52,790 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_time_in_force.buy` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `order_time_in_force.entry` setting in your configuration instead.
2022-05-30 15:42:52,790 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_time_in_force.sell` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `order_time_in_force.exit` setting in your configuration instead.
2022-05-30 15:42:52,791 - freqtrade.configuration.config_validation - WARNING - DEPRECATED: Using 'buy' and 'sell' for order_types is deprecated.Please migrate your order_types settings to use 'entry' and 'exit' wording.
2022-05-30 15:42:52,791 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_types.buy` setting is deprecated 
and will be removed in the next versions of Freqtrade. Please use the `order_types.entry` setting in your configuration instead.
2022-05-30 15:42:52,791 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `order_types.sell` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `order_types.exit` setting in your configuration instead.
2022-05-30 15:42:52,792 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2022-05-30 15:42:52,838 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2022-05-30 15:42:53,012 - freqtrade - ERROR - Using separate Hyperopt files has been removed in 2021.9. Please convert your existing Hyperopt file to the new Hyperoptable strategy interface
2022-05-30 15:42:53,465 - freqtrade.exchange.exchange - INFO - Closing async ccxt session.
ERROR: 2
PS C:\myfreqbot\freq1> 
  ```
  // paste your log here
  ```

**Comment by xmatthias** [comment] 2022-05-30 15:56
Gonna close this as duplicate of #6903.

**Closed by xmatthias** 2022-05-30 15:56 UTC
Labels: Duplicate

**Comment by Orbazz** [comment] 2022-05-30 15:59
> Gonna close this as duplicate of #6903.

okay
