### ISSUE TITLE
Freqtrade "hyperopt-show -n" prints wrong epoc

### ISSUE THREAD

**Issue by qkum** [freqtrade/freqtrade#3349] opened 2020-05-20 18:48 UTC
## Step 1: Have you search for this issue before posting it? Nope, I was asked to report this issue by the developers on slack. 

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubunto 18.04
  * Python Version: 3.6.9 (`python -V`)
  * CCXT version: ccxt==1.27.1 (`pip freeze | grep ccxt`)
  * Branch: _Master_ 
  * Last Commit ID: 2a9653cd4e75819e22ff66b3d2ce3c7c5a4ca842 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
When I write freqtrade hyperopt-show -n 332 or whatever epoc I want to view from the pickle file it prints the wrong epoc. 

*Explain the problem you have encountered*
Had to write freqtrade hyperopt-show -n 470 to get the settings/details for epoc 332. ( within the .env virtual envirnoment ) 

### Steps to reproduce:

  1. linking screenshots
  2. _____
  3. _____
  
### Observed Results:

  * What happened? Had to write freqtrade hyperopt-show -n 470 to get the settings/details for epoc 332. ( within the .env virtual envirnoment ) 
  * What did you expect to happen? Print epoc 332 as it should

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```

**Comment by qkum** [comment] 2020-05-20 18:49
![hyperopt-list](https://user-images.githubusercontent.com/40965179/82485184-5868cd00-9adb-11ea-84bc-a5e543f2cb77.png)
![hyperopt-show -n 332](https://user-images.githubusercontent.com/40965179/82485187-59016380-9adb-11ea-8b78-306e58494503.png)
![hyperopt-show -n 470](https://user-images.githubusercontent.com/40965179/82485188-5999fa00-9adb-11ea-8721-4246db6e0cca.png)
![hyperopt-show](https://user-images.githubusercontent.com/40965179/82485189-5999fa00-9adb-11ea-9dd4-7e36eca42bb3.png)
![freqtrade version](https://user-images.githubusercontent.com/40965179/82485192-5a329080-9adb-11ea-81c6-0091d67c95de.png)

**Comment by qkum** [comment] 2020-05-20 18:57
Found out that freqtrade hyperopt-show -n 100 prints the correct epoc (100)

If I write -n 200 it prints like epoc 68 

and found out I ahve to write -n 139 to print epoc 1

![freqtrade hyperopt-show -n 139](https://user-images.githubusercontent.com/40965179/82486007-8b5f9080-9adc-11ea-9dc3-3b06852ebb8f.png)

**Comment by hroff-1902** [comment] 2020-05-21 23:49
Cannot reproduce it, give me (in an archive in the PM on Slack, for example) the file with hyperopt results, for which this can be reproduced (that `user_data/hyperopt_results/hyperopt_results.pickle`)

**Comment by xmatthias** [comment] 2020-06-03 04:44
@hroff-1902 did you receive the file? otherwise i don't see much reason to keep this open, as i'm not able to verify this either (which suggests it's something to do with the created file itself).

**Comment by hroff-1902** [comment] 2020-06-03 17:44
no, I did not get it

**Comment by xmatthias** [comment] 2020-06-03 17:56
In which case i'll close this Issue.

Feel free to comment so we can reopen it if you're able to provide us with the file - otherwise we're unable to reproduce the issue you're experiencing.

**Closed by xmatthias** 2020-06-03 17:56 UTC
Labels: Hyperopt, Triage Needed
