### ISSUE TITLE
I think I pushed freqtrade web UI to the limit

### ISSUE THREAD

**Issue by duquel** [freqtrade/freqtrade#5341] opened 2021-07-30 00:30 UTC
I think I reached the limit of web UI.
I have more than 100 trades open right now on a daily candle strategy and it seems as though the UI is not showing me any open trades anymore.
Yesterday it worked fine when I had less than a 100 open.
I can see the trades in the database with show-trades and I saw them open so its not an issue with the trading engine. It seems to be a web UI issue.

## Describe your environment

  * Operating system: linux
  * Python Version: 3.9.6 (`python -V`)
  * CCXT version: 1.43.55 (`pip freeze | grep ccxt`)
  * Freqtrade Version:   develop-f1cf56cc   (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by duquel** [comment] 2021-07-30 00:32
ok. well, web UI just sprung back to life again.
perhaps its under pressure.
I will open the issue if I encounter the problem again but it seems fine for now.
I can live with that.

**Comment by xmatthias** [comment] 2021-07-30 04:39
Please make sure that the UI shows that it's online (top right corner).
also, make sure to press the "refresh" button manually in such cases - this will run an extended sync downloading everything (also pretty much static data that's usually only downloaded rarely).

**Comment by duquel** [comment] 2021-07-30 16:48
well. to be honest its not working very well at all.
it was working 100% of the times a few days ago.
as soon as number of positions became too many (i guess that is the problem),
it now works 10% of the time.
basically this: no trades visible, nothing in "pairs combined pane", no balance, nada.

EDIT: also, each time I restart the bot, it works about one time out of two.
each time afterwards is like 1/10 chance that it works.


EDIT 2: for now, I set verbosity to info on the api_server section,
also raised the rate limit for the exchange to the maximum of 200 (instead of 170 which I set before)

anyways, it really did not behave like this before.
I run multiple sessions with multiple api keys. The only session which has these problems is the one with over a 100 trades.

**Comment by xmatthias** [comment] 2021-07-30 17:29
it's pretty difficult to help you based on the above - as it's not listing a problem with evidence how to reproduce it - but it's only complaining "oh it doesn't work anymore" - without any real details.

You didn't fill out the issue template (please do so - you can use the edit button, or i'll close this issue) It includes important information (like, which version are you using).

You should also open the browser tools and investigate the browser console output (maybe keep it open until the problem appears).

100 trades should be fine (i test it with 1000/3000 trades) without any issues.

**Comment by duquel** [comment] 2021-07-30 17:39
I did what you asked me to.

went to the debugger inside the browser (firefox) on the problematic session and got this:
```
Error: timeout of 5000ms exceeded                       apiService.ts:32:14
    exports createError.js:16
    ontimeout xhr.js:96
```

I do not get the same errors on the working sessions.

tried again, I get these too:
maybe I should raise the timeout somewhere to try?

`Error: timeout of 5000ms exceeded
    exports http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:17
    ontimeout http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:40
    exports http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:40
    exports http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:40
    exports http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:28
    promise callback*0a06/c.prototype.request http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:1
    t http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:1
    exports http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:1
    ping http://127.0.0.1:8080/js/app.f9ae2284.js:1
    C http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:23
    dispatch http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:23
    dispatch http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:23
    dispatch http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:23
    r http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:23
    value http://127.0.0.1:8080/js/app.f9ae2284.js:1
    ne http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    Mn http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    insert http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    $ http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    Di http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    _update http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    r http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    get http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    nr http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    Bn http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    $mount http://127.0.0.1:8080/js/chunk-vendors.483841b8.js:7
    cd49 http://127.0.0.1:8080/js/app.f9ae2284.js:1
    i http://127.0.0.1:8080/js/app.f9ae2284.js:1
    0 http://127.0.0.1:8080/js/app.f9ae2284.js:1
    i http://127.0.0.1:8080/js/app.f9ae2284.js:1
    r http://127.0.0.1:8080/js/app.f9ae2284.js:1
    <anonymous> http://127.0.0.1:8080/js/app.f9ae2284.js:1
    <anonymous> http://127.0.0.1:8080/js/app.f9ae2284.js:1`

**Comment by xmatthias** [comment] 2021-07-30 17:44
great :+1: 

best use an uptodate version ... your version is from April - and things (including how trades api is handled) has changed a lot.
It  most likely also means you're using an older version of freqUI (it usually is installed at the time of installation unless explicitly updated).
Updating freqUI itself however means that the 2 versions (updated FreqUI, old freqtrade) will most likely not collaborate nicely.

**Comment by duquel** [comment] 2021-07-30 17:46
> great +1
> 
> best use an uptodate version ... your version is from April - and things (including how trades api is handled) has changed a lot.
> It most likely also means you're using an older version of freqUI (it usually is installed at the time of installation unless explicitly updated).
> Updating freqUI itself however means that the 2 versions (updated FreqUI, old freqtrade) will most likely not collaborate nicely.

thanks. I guess I will have to update.
I am a bit hesitant to do updates when things work. (dont break what already working, you know)
well now it doesnt seem to work so I guess I should update...

**Comment by xmatthias** [comment] 2021-07-30 17:51
it's not up to me to decide if you should update - but i'm only supporting develop and the latest release version due to time/ressource constraints.

**Comment by duquel** [comment] 2021-07-30 18:04
> it's not up to me to decide if you should update - but i'm only supporting develop and the latest release version due to time/ressource constraints.


I appreciate all the work you do. its golden!
no worries, I will just make a backup of the installation and get to the update. brb

**Comment by duquel** [comment] 2021-07-30 18:26
the installation update without any problems but the issue with the trades not showing up is still here.
I tried it in Chromium browser and went to have a look in the console.
Here is a screenshot.
![Screenshot_2021-07-30_20-24-36](https://user-images.githubusercontent.com/46638210/127696148-c7ec6219-65f9-4d61-828e-e6b8b1c1cda0.png)

**Comment by xmatthias** [comment] 2021-07-30 18:36
Please switch to the "network" tab - it'll show which of the calls do time out.

**Comment by duquel** [comment] 2021-07-30 18:38
![Screenshot_2021-07-30_20-38-34](https://user-images.githubusercontent.com/46638210/127697445-909d605a-2a75-4eee-9bf9-6077d0a4b13f.png)

**Comment by duquel** [comment] 2021-07-30 18:42
another screenshot in case it helps.


![Screenshot_2021-07-30_20-41-52](https://user-images.githubusercontent.com/46638210/127697795-ab039a39-9b6b-4802-b846-1c8823e185dd.png)

**Comment by xmatthias** [comment] 2021-07-30 18:47
That's quite unusual - as basically everything times out.
That can only have very limited reasons:
* your system is maxed out, and it got no core / ressources to spare to answer to the API
* have you got 100 open trades - in which case the UI is probably your least problem
* the database is on a very slow disk (slow read/write) - or it's remote and does not perform well.

**Comment by duquel** [comment] 2021-07-30 18:53
> That's quite unusual - as basically everything times out.
> That can only have very limited reasons:
> 
>     * your system is maxed out, and it got no core / ressources to spare to answer to the API
> 
>     * have you got 100 open trades - in which case the UI is probably your least problem
> 
>     * the database is on a very slow disk (slow read/write) - or it's remote and does not perform well.

well, the system is definitely not maxed out. I have plenty of cpu left, plenty of ram,
the database is running on an ssd and I already tried accessing the database with the freqtrade command line and it works flawlessly. showing all open trades and all.

and the 105 currently open trades, well. what can I say about that one? its my strategy. its not scalping or anything. it uses 1D candlesticks and opens/closes trade at the end of the day 00.00 UTC. the strategy is definitely not going to change. hmm.... is it not supposed to work with more than 100 open at the same time?

EDIT: anyhow, its obviously a webUI problem since the bot itself is running perfectly so I guess I will access the database directly or just using the Binance web interface to have a UI. 
the point was to have something that opens/close trades automatically which freqtrade does without any problems.
not having a webUI is not a deal breaker

**Comment by xmatthias** [comment] 2021-07-30 19:09
The API is pulling one of 2 things - eihter a cached price (if the price was updated within the last 1800 seconds).

This means, right after startup, it'll be a problem.
It might also be a problem if you heavily reduced `process_throttle_secs` - or if your loop time is above this timeout - as then the api will try to fetch uptodate prices for every open trade as part of the api call.
for open orders (unfilled orders, not open Trades!) it'll also fetch that order to give you an uptodate status.

As that will apply api-ratelimits, for 100 pairs you'll be around >20 seconds (assuming the bot is doing no other call against the exchange at that time.

You'll have the same problem with `/status table` when using telegram - although that will not timeout, just take a long time to answer.

**Comment by duquel** [comment] 2021-07-30 19:22
> The API is pulling one of 2 things - eihter a cached price (if the price was updated within the last 1800 seconds).
> 
> This means, right after startup, it'll be a problem.
> It might also be a problem if you heavily reduced `process_throttle_secs` - or if your loop time is above this timeout - as then the api will try to fetch uptodate prices for every open trade as part of the api call.
> for open orders (unfilled orders, not open Trades!) it'll also fetch that order to give you an uptodate status.
> 
> As that will apply api-ratelimits, for 100 pairs you'll be around >20 seconds (assuming the bot is doing no other call against the exchange at that time.
> 
> You'll have the same problem with `/status table` when using telegram - although that will not timeout, just take a long time to answer.

I got it that it takes time and I have already noticed that while trading. Its not really a problem though if the trades get executed 00.02 or 00.03 utc.

is there any way to increase the timeout for the webui from 5 seconds? I've tried grepping the whole installation for references for 5000 or timeout but have had no luck yet.

**Comment by xmatthias** [comment] 2021-07-30 19:24
not at the moment, no.

that's an edge-usecase, in which i'd simply say the UI is currently not made for. 
While we can increase the timeout in the UI - the max I'm willing to go is 10s for the /status call (it's a local call), and that's not going to do it for your case.

**Comment by duquel** [comment] 2021-07-30 19:27
> not at the moment, no.
> 
> that's an edge-usecase, in which i'd simply say the UI is currently not made for.
> While we can increase the timeout in the UI - the max I'm willing to go is 10s for the /status call (it's a local call), and that's not going to do it for your case.

can I try it for my own installation at least? 
which file do I edit?
pleeease!?

**Comment by xmatthias** [comment] 2021-07-30 19:35
you cannot install it on the installation (the one served by freqtrade), but you'll need to download and install [freqUI](https://github.com/freqtrade/frequi) in develop mode.

I'll however not be providing support on this installation - it's strightforward if you've some experience with javascript / web development - but it'll potentially be difficult otherwise.

**Comment by duquel** [comment] 2021-07-30 19:35
A little update.
I made two dry-run configs
one with 99 max_open_trades
and another one with 101 max_open_trades.

the 99 one works as expected and the 101 one behaves like my live config with 105 open trades.

there is definitely something to the 100 trade threshold.

EDIT: I made a bogus strategy that buys if price is above 0 + market ordered everything just to fill in the whole rooster so to say asap.

**Closed as completed by xmatthias** 2021-07-30 19:35 UTC
Labels: Triage Needed, freqUI

**Comment by xmatthias** [comment] 2021-07-30 19:37
just make sure to never run this in prod accidentally :laughing:

**Comment by duquel** [comment] 2021-07-30 19:38
> just make sure to never run this in prod accidentally laughing

haha, for sure.
but anyway, whats up with the 100 trades? this is weird. 99 works and 101 doesnt.

**Comment by duquel** [comment] 2021-07-30 19:43
> just make sure to never run this in prod accidentally laughing

I kid you not... 99 works flawlessly, 
I boot it up, it fetches the trades in the database, then it fetches prices, I get a heartbeat, then I log in to the webUI and they are all there.
