### ISSUE TITLE
Backtesting crashes when timerange is ~8 months+

### ISSUE THREAD

**Issue by Theagainmen** [freqtrade/freqtrade#2358] opened 2019-10-09 18:36 UTC
## Step 1: Describe your environment

  * Operating system: Windows
  * Python Version: Python 3.7.4
  * Branch: freqtrade develop-7d1f66cc
  
## Step 2: Describe the problem:

When going around 8+ months back into history the backtesting will crash. Sometimes when backtesting with multiple strategies it will work for the first few one but crash later on. If you try to use the crashes strategy but with a shorter timerange it won't crash. Here is the error.

```
2019-10-09 20:29:58,602 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\user\freqtrade\freqtrade\main.py", line 39, in main
    args['func'](args)
  File "c:\users\user\freqtrade\freqtrade\optimize\__init__.py", line 44, in start_backtesting
    backtesting.start()
  File "c:\users\user\freqtrade\freqtrade\optimize\backtesting.py", line 458, in start
    'end_date': max_date,
  File "c:\users\user\freqtrade\freqtrade\optimize\backtesting.py", line 344, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "c:\users\user\freqtrade\freqtrade\optimize\backtesting.py", line 224, in _get_ticker_list
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "c:\users\user\freqtrade\freqtrade\strategy\interface.py", line 461, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "C:\Users\Niels\freqtrade\user_data\strategies\awesome_strat.py", line 80, in populate_buy_trend
    ] = 1
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 322, in _setitem_with_indexer
    take_split_path = self.obj._is_mixed_type
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5279, in _is_mixed_type
    return self._protect_consolidate(f)
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5241, in _protect_consolidate
    result = f()
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5278, in <lambda>
    f = lambda: self._data.is_mixed_type
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 662, in is_mixed_type
    self._consolidate_inplace()
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 937, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 1913, in _consolidate
    list(group_blocks), dtype=dtype, _can_consolidate=_can_consolidate
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\blocks.py", line 3323, in _merge_blocks
    new_values = new_values[argsort]
MemoryError: Unable to allocate array with shape (13, 34699) and data type float64
```

### Steps to reproduce:

  1. Download backtest data for over a year back with timeframe 5m, exchange binance.
  2. Run a backtest for 1 year on multiple strategies.
  3. Watch it crash.
  
Looks like it's crashing because there's too much data being passed into that float64 array.

**Comment by xmatthias** [comment] 2019-10-10 04:44
We'll need some more, detailed information about your environment.

* How much memory does your system have?
* which precise version of python (64bit / 32bit) 
* how many pairs are you backtesting


Trying to recreate this in my environment

I've just tested this on a linux system, with 16G of ram and 6 strategies.
While taking a while (some strategies are not very optimized i guess...) it did not crash (i took almost 2 years of data - with `--timeframe 20180101-` and never took more memory than chrome with ~15 windows open did.

**Comment by hroff-1902** [comment] 2019-10-10 07:59
It crashes in your custom code:
```
File "C:\Users\Niels\freqtrade\user_data\strategies\awesome_strat.py", line 80, in populate_buy_trend
```

I guess we need this file to reproduce.

**Comment by Theagainmen** [comment] 2019-10-10 08:28
I have 8GB RAM - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz - Python 32-bit.
Doesn't seem to matter how many pairs I'm using, could be 1 or 12, crashes at 1st or 2nd one anyways.

It doesn't matter which strategy I'm using, usually the first or second strategy in the list crashes, even the DefaultStrategy crashes:
```2019-10-10 10:25:20,233 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "c:\users\user\freqtrade\freqtrade\main.py", line 39, in main
    args['func'](args)
  File "c:\users\user\freqtrade\freqtrade\optimize\__init__.py", line 44, in start_backtesting
    backtesting.start()
  File "c:\users\user\freqtrade\freqtrade\optimize\backtesting.py", line 458, in start
    'end_date': max_date,
  File "c:\users\user\freqtrade\freqtrade\optimize\backtesting.py", line 344, in backtest
    ticker: Dict = self._get_ticker_list(processed)
  File "c:\users\user\freqtrade\freqtrade\optimize\backtesting.py", line 224, in _get_ticker_list
    self.strategy.advise_buy(pair_data, {'pair': pair}), {'pair': pair})[headers].copy()
  File "c:\users\user\freqtrade\freqtrade\strategy\interface.py", line 461, in advise_buy
    return self.populate_buy_trend(dataframe, metadata)
  File "C:\Users\user\freqtrade\freqtrade\strategy\default_strategy.py", line 131, in populate_buy_trend
    'buy'] = 1
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\indexing.py", line 322, in _setitem_with_indexer
    take_split_path = self.obj._is_mixed_type
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5279, in _is_mixed_type
    return self._protect_consolidate(f)
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5241, in _protect_consolidate
    result = f()
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\generic.py", line 5278, in <lambda>
    f = lambda: self._data.is_mixed_type
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 662, in is_mixed_type
    self._consolidate_inplace()
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 937, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\managers.py", line 1913, in _consolidate
    list(group_blocks), dtype=dtype, _can_consolidate=_can_consolidate
  File "c:\users\user\freqtrade\.env\lib\site-packages\pandas\core\internals\blocks.py", line 3320, in _merge_blocks
    new_values = np.vstack([b.values for b in blocks])
  File "<__array_function__ internals>", line 6, in vstack
  File "c:\users\user\freqtrade\.env\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate array with shape (19, 106364) and data type float64```

This is the command I ran: `freqtrade backtesting --strategy-list DefaultStrategy BbandRsi AwesomeMacd AdxSmas BinHV27 CofiBitStrategy`, with 369 days of data.

**Comment by hroff-1902** [comment] 2019-10-10 08:33
what `freqtrade -V` says?

**Comment by xmatthias** [comment] 2019-10-10 09:22
I think the issue is the python version (32bit).

Based on [this stackoverflow question](https://stackoverflow.com/questions/18282867/python-32-bit-memory-limits-on-64bit-windows):

python 32bit get's 2Gb of Memory for 300 days i assume that you'll approach this limit soonish (data is kept twice in memory when using strategy-list - + all libraries + waiting for GC to happen once objects move out of scope ...).

Please retry with python 64bit - this will give python access to more memory. (you'll need to reinstall all python dependencies to fit 64bit python).

This is not a problem on linux, since 32bit processes on linux get 3.5Gb of memory by default (However most linux-systems nowadays use 64bit only).

**Comment by hroff-1902** [comment] 2019-10-10 09:27
It's not even a problem on a 64-bit Windows, to set up and run 64-bit python...

I also this this is related to the 32-bit python used.

**Comment by hroff-1902** [comment] 2019-10-10 16:24
@xmatthias 

Starting from some time, the joblib deprecation message appear not only when freqtrade run as hyperopt, but also in the backtesting and even in dry/live run. AND the joblib workers are also spawned. At least on linux -- use ps / htop, which shows the process hierarchy. May on Windows as well. This all exhausts free memory... Maybe this is also a reason for this error.

**Comment by xmatthias** [comment] 2019-10-10 17:20
@hroff-1902 can you pinpoint that to something specific? maybe a strategy importing "something" from the hyperopt file ... ? 

We're very carefull where we import hyperopt, and checking again just now it's only imported within hyperopt* files ...

**Comment by hroff-1902** [comment] 2019-10-10 17:32
I guess that's after I moved the optimizer object (which is from skopt and uses joblib from sklearn) from the module globals into the class attribute. So it's imported somehow into main freqtrade as well as into backtesting... Probably it can be fixed with '__slots__'...

**Comment by xmatthias** [comment] 2019-10-10 17:48
but no file called "hyperopt*" should be loaded for backtesting, so you could have 1000 syntax errors there.

no definitely not - if it's imported, using `__slots__` will throw an error, so it'll help you identify the error - but will not prevent it from happening.
This would also be breaking if hyperopt dependencies are not installed at all - which i tested and know is working fine.

I can not recreate this either - i've just "broken" the hyperopt class (syntaxerror `cl11111ass Hyperopt:`)  - and it's definitely not loaded during backtesting, since my backtesting did run just fine. (hyperopt does somehow not work now anymore - do i need to log an issue? :sweat_smile:  )

Maybe it's a `__pycache__` problem ... ?

**Comment by hroff-1902** [comment] 2019-10-10 17:55
* run htop in a diff. terminal session (or a ps with process hierarchy)
* run freqtrade in dry-run with config_binance.json.example
* you'll see the joblib/sklearn deprecation warning somewhere at the beginning
* htop will show you the main freqtrade process under bash and 4 (in my case) workers

**Comment by hroff-1902** [comment] 2019-10-10 18:02
In linux it's forked and uses same memory pages. On Windows it spawns new processes (and consumes much more memory)...
I guess...

**Comment by hroff-1902** [comment] 2019-10-10 18:33
forget it (anything about hyperopt), it was loaded in the modified strategy where I forgotten to change the class name from DefaultHyperopt, so that was loaded instead of standard one and loads hyperopt parts...

**Comment by hroff-1902** [comment] 2019-10-10 18:48
So, @Theagainmen , try to install 64-bit python instead of 32-bit one and reproduce the issue...

**Comment by hroff-1902** [comment] 2019-10-20 20:18
@Theagainmen have you tried to install 64-bit python? Can this issue be closed?

**Comment by hroff-1902** [comment] 2019-10-22 20:04
Closing this since no further input received, in assumption that moving to 64-bit python resolves the problem.

Feel free to reopen.

**Closed by hroff-1902** 2019-10-22 20:04 UTC
Labels: Triage Needed, backtest, question
