### ISSUE TITLE
Installing on raspberry pi 4: [Errno 2] No such file or directory: 'requirements-dev.txt'

### ISSUE THREAD

**Issue by KarimHP** [freqtrade/freqtrade#5734] opened 2021-10-17 16:28 UTC
## Describe your environment

  * Operating system: ubuntu on raspberry pi 4
  * Python Version: Python 3.9.7

  
## Your question

So im trying to install freqtrade on a raspberry pi 4. I did exactly as said in the manual with: 

```
sudo apt-get install python3-venv libatlas-base-dev cmake
# Use pywheels.org to speed up installation
sudo echo "[global]\nextra-index-url=https://www.piwheels.org/simple" > tee /etc/pip.conf

git clone https://github.com/freqtrade/freqtrade.git
cd freqtrade

bash setup.sh -i
```

yet in the middle of the installation when im asked about installing hyperopt dependencies(y/n) i get this ERROR: 

```
Updating your virtual env
-------------------------
pip install in-progress. Please wait...
Requirement already satisfied: pip in ./.env/lib/python3.9/site-packages (20.3.4)
Collecting pip
  Using cached pip-21.3-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.4
    Uninstalling pip-20.3.4:
      Successfully uninstalled pip-20.3.4
Successfully installed pip-21.3
Do you want to install dependencies for dev [y/N]? y
Do you want to install plotting dependencies (plotly) [y/N]? y
Do you want to install hyperopt dependencies [y/N]? y
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'

```

is this a mistake or is this as it is supposed to be because hyperopting shouldnt be used with raspberry pi?

**Comment by KarimHP** [comment] 2021-10-17 16:30
> is this a mistake or is this as it is supposed to be because hyperopting shouldnt be used with raspberry pi?


i thought this may be it. but even when i chose "N" on installing hyperopt he gives me the same error. So it seems to have nothing to do with hyperopt.

**Comment by xmatthias** [comment] 2021-10-17 17:23
it's the dev-dependencies, not hyperopt ... 

that said - i think the error happens before this point (while installing ta-lib).
I've just noticed that the install-script continues if ta-lib fails to build - but without switching back to the root directory - so the dir is wrong (it would not install anyway - as there is another error before)

**Comment by KarimHP** [comment] 2021-10-17 21:40
Ok nice thank you for the commit! It seems to be an issue with ubuntu running on arm64 and ta lib. Im sure the workaround with commit wouldve worked but i just solved it by switching to raspian os, where the installation worked perfectly fine :)

**Comment by xmatthias** [comment] 2021-10-18 05:50
with arm64, the problem is that there's basically no pre-built wheels for that, so all python packages will be installed by compiling them, which requires all build dependencies (which we neither document, nor support).

It should still be possible - but you'll need to go "error by error" - checking the failing package install dependencies, and install these manually - so usually, simply using the pre-built docker-image will be the faster route.

**Closed as completed by xmatthias** 2021-10-18 05:50 UTC
Labels: Question, Install
