### ISSUE TITLE
Bot bug: Unable to sell trade: Insufficient funds to create limit sell order

### ISSUE THREAD

**Issue by djacky** [freqtrade/freqtrade#2817] opened 2020-01-28 16:31 UTC
## Step 1: Have you search for this issue before posting it?

Yes I have searched for this issue...no solutions worked.

## Step 2: Describe your environment

  * Operating system: Mac 10.14.6 (Mojave)
  * Python Version: 3.7.5 (`python -V`)
  * CCXT version: ccxt==1.20.46 (`pip freeze | grep ccxt`)
  * Branch: Master 
  * Last Commit ID: 7c53dcb0afd2ad663faad4bc03406f0575c87f6b (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
During real trading (`dry_run": false`), a selling bug occurs in the bot. Everything starts working fine, buy orders are filled and some are sold fine, but randomly, an error occurs and the bot informs me that it cannot sell an order because of insufficient funds. But I definitely have sufficient funds in my account,  so this seems to be a bug. The error keeps repeating itself. Please see the logs below.

### Steps to reproduce:

The error occurs randomly...no pattern can be established to reproduce the bug.

On Binance, I see that the Max Sell amount is 48.45, but the bot is trying to sell at 49.25.
My ask_strategy uses `use_order_book": false`, so a market sell order should be placed, no?

  
### Observed Results:
The sell order of the pair did not take place when the strategy condition was satisfied. 

### Relevant code exceptions or logs:

  ```
2020-01-28 16:57:21,914 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=27500
2020-01-28 16:58:26,594 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=27500
2020-01-28 16:59:29,999 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=27500
2020-01-28 17:00:19,058 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/BTC.Tried to sell amount 49.25 at rate 0.0019577.Message: binance Account has insufficient balance for requested action.
2020-01-28 17:00:30,737 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/BTC.Tried to sell amount 49.25 at rate 0.0019581.Message: binance Account has insufficient balance for requested action.
2020-01-28 17:00:37,185 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=27500
2020-01-28 17:00:38,185 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/BTC.Tried to sell amount 49.25 at rate 0.0019583.Message: binance Account has insufficient balance for requested action.
  ```

**Comment by hroff-1902** [comment] 2020-01-28 17:08
this should probably be fixed in the develop branch

**Comment by djacky** [comment] 2020-01-28 17:12
@hroff-1902 So I should `git checkout develop` and run the bot again?

**Comment by hroff-1902** [comment] 2020-01-28 17:20
yes, pls try to reproduce with the current develop branch

**Comment by djacky** [comment] 2020-01-28 17:21
Ok, I'll try it and keep you updated.

**Comment by djacky** [comment] 2020-01-28 20:20
Ok, after changing to develop, the error still occurs:

```2020-01-28 19:54:09,260 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 19:55:16,633 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 19:56:19,242 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 19:57:21,463 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 19:58:23,010 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 19:59:25,328 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 20:00:24,661 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/BTC.Tried to sell amount 49.25 at rate 0.0019576.Message: binance Account has insufficient balance for requested action.
2020-01-28 20:00:30,983 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=34662
2020-01-28 20:00:31,965 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/BTC.Tried to sell amount 49.25 at rate 0.001957.Message: binance Account has insufficient balance for requested action.```

**Comment by hroff-1902** [comment] 2020-01-28 21:46
> Should I have closed all the trades before starting the bot in develop?

yes, please try this. And start with a new fresh database as well

**Comment by djacky** [comment] 2020-01-28 21:47
@hroff-1902 What do you mean by "fresh database"? Do you mean to delete the `tradesv3.sqlite` file?

**Comment by hroff-1902** [comment] 2020-01-28 21:53
yes, delete the file
however, after closing the positions it's not necessary I guess

**Comment by djacky** [comment] 2020-01-28 21:56
@hroff-1902 Well, the thing is that I can't `/forcesell` BNB/BTC because it gives that error `WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market BNB/BTC`...

So I will have to sell it on the Binance exchange itself, close the bot, delete the `tradesv3.sqlite` file, and then restart the bot...

**Comment by xmatthias** [comment] 2020-01-29 05:38
@djacky one important note:

when using binance - do NOT use any BNB pairs to trade. 
The logs show you're having the problem with BNB/BTC ...

So the folowing happens:
the bot buys BNB/BTC - and then buys XRP/BTC (Or any other random pair). 

Fees on binance are by default subtracted from BNB - so now instead of owning 49.29, you only own 48.37 - the difference is made of the fees from that 2nd trade.

In the end, every subsequent trade will eat away at the amount for BNB - while we do have some safeguards for this in place, the reduction on BNB pairs is too huge to adjust to safely
Also - it's impossible to make a profit from this trade this way... how would profits be calculated?
you bought 49.29 BNB - but assuming that trade stays open for a few days - maybe only 25 BNB are left as the rest is eaten by fees deduced from other pairs ...

Side note: we've also covered this in the [documentation](https://www.freqtrade.io/en/latest/exchanges/#blacklists) about Binance ...

**Comment by hroff-1902** [comment] 2020-01-29 07:58
Ah, yeah, did not notice it's for BNB/BTC pair, that may be the reason...

**Comment by djacky** [comment] 2020-01-29 09:59
@xmatthias I see...So how do I avoid trading BNB/BTC? Do I simply add it as `"pair_blacklist": ["BNB/BTC"]`? My pair list is currently set as `"method": "VolumePairList"`

**Comment by xmatthias** [comment] 2020-01-29 10:53
yes - you'll need to add this (it's also in the binance default configuration ...)

**Comment by djacky** [comment] 2020-01-29 11:04
Thanks (once again) @xmatthias ...I'll test this now (on the develop branch) and update soon to see if everything works.

**Comment by hroff-1902** [comment] 2020-02-04 21:45
hi @djacky , any updates on this?

**Comment by djacky** [comment] 2020-02-04 22:02
Looks like it's been working fine...I'll close for now.

**Closed** 2020-02-04 22:02 UTC
Labels: Triage Needed
