### ISSUE TITLE
binance futures trading

### ISSUE THREAD

**Issue by lahirumaya12** [freqtrade/freqtrade#5603] opened 2021-09-21 17:33 UTC
Hello there,

This bot can be use to binance futures trading?

**Comment by xmatthias** [comment] 2021-09-21 18:04
Please use the search to find similar issues before opening new issues (duplicate of #5173, #2312, #902 and partially #2183).

It's currently not possible, but work on it is being done.

**Closed as completed by xmatthias** 2021-09-21 18:04 UTC
Labels: Duplicate, Question
