### ISSUE TITLE
How to make bot to short selling not only buy / long

### ISSUE THREAD

**Issue by NilanjanaBala** [freqtrade/freqtrade#3972] opened 2020-11-21 14:17 UTC
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`) : Python 3.7.7
  * CCXT version: _____ (`pip freeze | grep ccxt`) ccxt==1.37.69
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
freqtrade 2020.10
  
## Your question

1. Exchange support both buy and sell
2. Let's a use case i have 100 USDT and i want use that for placing order for buy as well as short selling too

Is there any configuration which can help to do it?

Thanks

*Ask the question you have not been able to find an answer in our [Documentation](https://www.freqtrade.io/en/latest/)*

**Comment by xmatthias** [comment] 2020-11-21 14:20
This is a duplicate of #892.

Please use the search to look for open issues that answer your question already.

Freqtrade is currently long only. 
Supporting short trading may come eventually sometime in the future - but it's still quite a long way to get there.

**Closed by xmatthias** 2020-11-21 14:20 UTC
Labels: Duplicate, Question
