### ISSUE TITLE
Feat/short issues for binance futures

### ISSUE THREAD

**Issue by fridary** [freqtrade/freqtrade#6224] opened 2022-01-14 09:38 UTC
* Operating system: Mac os 11.6.1
  * Python Version: 3.8.12
  * CCXT version: 1.67.31
  * Freqtrade Version: 2021.12
  
@samgermain
Well, I have just downloaded `feat/short` branch and wonder how you use that as there are many fixes need to make. On what exchange do you trade?
I will start sequentially after the launch of the fresh project, user_dir and config: `python -m freqtrade trade -c config.json`. Config added:
```
"trading_mode": "futures",
"collateral": "isolated",
```

1) `freqtrade.exceptions.OperationalException: Freqtrade does not support isolated futures on Binance`
I suppose we can uncomment lines in `exchange/binance.py`:
```
_supported_trading_mode_collateral_pairs: List[Tuple[TradingMode, Collateral]] = [
        # TradingMode.SPOT always supported and not required in this list
        # TODO-lev: Uncomment once supported
        # (TradingMode.MARGIN, Collateral.CROSS),
        (TradingMode.FUTURES, Collateral.CROSS),
        (TradingMode.FUTURES, Collateral.ISOLATED)
    ]
```
2) `freqtrade.freqtradebot - WARNING - Unable to create trade for ETH/USDT: Could not set margin mode due to BadRequest. Message: binance marginType must be either isolated or crossed`
In `exchange.py set_margin_mode()` change `self._api.set_margin_mode(pair, collateral.value, params)` to `self._api.set_margin_mode(collateral.value, pair, params)`

3)
```
2022-01-13 17:11:35 DEBUG urllib3.connectionpool._make_request() https://fapi.binance.com:443 "POST /fapi/v1/marginType HTTP/1.1" 400 53
2022-01-13 17:11:35 WARNING freqtrade.exchange.common.wrapper() set_margin_mode() returned exception: "Could not set margin mode due to AuthenticationError. Message: binance {"code":-4046,"msg":"No need to change margin type."}". Giving up.
2022-01-13 17:11:35 WARNING freqtrade.freqtradebot.enter_positions() Unable to create trade for ETH/USDT: Could not set margin mode due to AuthenticationError. Message: binance {"code":-4046,"msg":"No need to change margin type."}
```
in `exchange.py set_margin_mode()` quick fix replace
```
except (ccxt.NetworkError, ccxt.ExchangeError) as e:
            raise TemporaryError(
                f'Could not set margin mode due to {e.__class__.__name__}. Message: {e}') from e
```
to
```
except (ccxt.NetworkError, ccxt.ExchangeError) as e:
            if 'No need to change margin type' not in str(e):
                raise TemporaryError(
                    f'Could not set margin mode due to {e.__class__.__name__}. Message: {e}') from e
```
There should be not sending this request every time, because API limits.
4) 
```
funding_history = self._api.fetch_funding_history(
TypeError: fetch_funding_history() got an unexpected keyword argument 'pair'
```
in `exchange.py _get_funding_fees_from_exchange()` change
```
funding_history = self._api.fetch_funding_history(
                # pair=pair, <- removed
                symbol=pair # added
                since=since
            )
```
5) freqtrade made order by strategy and when exit it says
```
2022-01-13 18:26:53 DEBUG freqtrade.freqtradebot._safe_exit_amount() ETH/USDT - Wallet: 0 - Trade-amount: 0.004
2022-01-13 18:26:53 WARNING freqtrade.freqtradebot.exit_positions() Unable to exit trade ETH/USDT: Not enough amount to exit trade. Trade-amount: 0.004, Wallet: 0
```
Although I bought 13.23 USDT of ETH with 0.004 amount, so I removed checking from `freqtradebot.py _safe_exit_amount()`:
```
if self.trading_mode == TradingMode.FUTURES:
            amount = trade.amount
        else:
            amount = self._safe_exit_amount(trade.pair, trade.amount)
```
6) now I set `def leverage()` `return 2` in strategy.
![Снимок экрана 2022-01-13 в 18 39 50](https://user-images.githubusercontent.com/3791864/149361180-a9fced27-a03e-44e2-a24a-c207841889ac.png)
I got error:
```
2022-01-13 18:39:30 WARNING freqtrade.exchange.common.wrapper() _set_leverage() returned exception: "Could not set leverage due to BadRequest. Message: binance {"code":-1102,"msg":"Mandatory parameter 'leverage' was not sent, was empty/null, or malformed."}". Giving up.
2022-01-13 18:39:30 WARNING freqtrade.freqtradebot.exit_positions() Unable to exit trade ETH/USDT: Could not set leverage due to BadRequest. Message: binance {"code":-1102,"msg":"Mandatory parameter 'leverage' was not sent, was empty/null, or malformed."}
```
Database:
![Снимок экрана 2022-01-13 в 18 42 12](https://user-images.githubusercontent.com/3791864/149361540-5048ad00-f733-4a71-aad6-fe9d6fbf2355.png)
![Снимок экрана 2022-01-13 в 18 42 48](https://user-images.githubusercontent.com/3791864/149361639-18e2f3b8-d64b-4a47-ae0e-d00efb274bd5.png)
Quick fix is wrap `int()` in `binance.py`: `self._api.set_leverage(symbol=pair, leverage=int(leverage))`
But is it correct value 1.0 in `orders` table instead `2.0`?
Then I got:
`2022-01-13 18:47:01 WARNING freqtrade.freqtradebot.exit_positions() Unable to exit trade ETH/USDT: Could not set leverage due to ExchangeError. Message: binance {"code":-4161,"msg":"Leverage reduction is not supported in Isolated Margin Mode with open positions."}`
Quick fix disable checking `self._lev_prep(pair, leverage)` for exit in `exchange.py create_order()`, but it seems we need change db saving, because leverage I guess can be changed during holding (?).

7) profit calculation during real time in freq UI when long position with leverage is lower than binance web interface, but anyway when closing trade profit calculates perfect accurately. Shorting positions works good too.

8) in strategy `stoploss_on_exchange` not working:
```
order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': True,
        'stoploss_on_exchange_interval': 60,
        'stoploss_on_exchange_limit_ratio': 0.99
    }
```
```
2022-01-13 23:37:02 ERROR freqtrade.freqtradebot.create_stoploss_order() Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market ETH/USDT. Tried to sell amount 0.006 at rate 3212.59. Message: binance stop_loss_limit is not a valid order type in market ETH/USDT
2022-01-13 23:37:02 WARNING freqtrade.freqtradebot.create_stoploss_order() Exiting the trade forcefully
```
I tested the same code on `dev` branch and stoploss worked correctly. This bug I don't know how to fix.

9) @xmatthias there are some extremely necessary functions that are not in freqtrade like take profit orders. For example, I have strategy roi 0.2-0.3% and sometimes I see rate has been reached for some seconds, but freqtrade didn't get to sell it (process_throttle_secs=5), while testing take profit did. We can add function like below:

```
def custom_take_profit(self, pair: str, trade: 'Trade', current_time: 'datetime', current_rate: float,
                    current_profit: float, current_roi: float, **kwargs):
        # when there is left 0.1% to profit that is pretty close, we send order
        exit_signal_before_rate = 0.1 # %
        if current_profit + exit_signal_before_rate / 100 >= current_roi:
            return trade.open_rate * (1 + current_roi)
```

9) `python -m freqtrade download-data -c 'config.json' -d '/data_crypto' -t 3m -p ETH/USDT --days 60`
it created `/data_crypto/futures` folder and ETH_USDT-3m-futures.json, ETH_USDT-8h-funding_rate.json, ETH_USDT-8h-mark.json
when I make python -m freqtrade backtesting -c 'config.json' -d '/data_crypto --timeframe 3m -p ETH/USDT' it works, buy `plot-dataframe` says `WARNING freqtrade.data.history.idatahandler._check_empty_df() No history data for pair: "ETH/USDT", timeframe: 3m.`, although `Using data directory:` log shows correct path. 
The problem is incorrect `candle_type` param passed to `ohlcv_load()` in `idatahandler.py`, someone forgot add `candle_type=config.get('candle_type_def', CandleType.SPOT)` in `load_data()` to `init_plotscript()`.

10) I set when backtesting on `3m` `ETH/USD` 11-13 Jan 2022
```
minimal_roi = {
        "0": 0.002,
    }
```
and it works correct when long:
![Снимок экрана 2022-01-14 в 12 03 21](https://user-images.githubusercontent.com/3791864/149488510-9a536080-cc29-4fbd-b3fd-6604f69f3277.png)

but when short it seems it does not calculate in current candle:
![Снимок экрана 2022-01-14 в 12 01 08](https://user-images.githubusercontent.com/3791864/149488328-af1297b7-61d0-4c26-8def-9b1fad169951.png)
another weird thing:
![Снимок экрана 2022-01-14 в 12 13 33](https://user-images.githubusercontent.com/3791864/149490001-e9a69894-98f8-4ad6-8e14-d77069968419.png)

Also there are no buy triangles when shorting on plot.

11) No sell signal is triggered (sell/exit_long), while I tested the same strategy code on `dev` freqtrade and it worked.
```
    minimal_roi = {
        "0": 1
    }
    stoploss = -1

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                # Signal: RSI crosses above 30
                (qtpylib.crossed_above(dataframe['rsi'], self.buy_rsi.value)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_long'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                # Signal: RSI crosses above 70
                (qtpylib.crossed_above(dataframe['rsi'], self.sell_rsi.value)) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'exit_long'] = 1
        return dataframe
```

**Comment by samgermain** [comment] 2022-01-14 10:40
@fridary 

I haven't started using it live yet. I expect there to be many fixes that need to be made, that is why is isn't merged into develop yet. I'm currently working on adding liquidation price, after that I plan to add fixes so that you don't exceed the max borrowable amount. After that, I plan to move on to the `TODO-lev` comments, as well as miscellaneous fixes.

--------------

> freqtrade.exceptions.OperationalException: Freqtrade does not support isolated futures on Binance
I suppose we can uncomment lines in exchange/binance.py:

Yeah sure uncomment the line, once the isolated-liq branch gets merged in this should be uncommented by default

> freqtrade.freqtradebot - WARNING - Unable to create trade for ETH/USDT: Could not set margin mode due to BadRequest. Message: binance marginType must be either isolated or crossed

I believe in config you need to set `"collateral: "isolated"` or `"collateral_type: "isolated"`. This name will change within a month or so to `margin_mode` or `margin_type`

---------------

For the rest of the issues, do you think you would be able to create a PR? It sounds like you have it figured out more than I do, and it would probably be easier for you to do it than me.

**Comment by xmatthias** [comment] 2022-01-14 12:28
Regarding points 10 - i'm not sure these will be fixed/implemented.

I consider the `plot-dataframe` functionality as legacy/silently deprecated - since it has performance problems and a better alternative in freqUI is available - so fixes for this will most likely only be implemented into freqUI, but not to plot-dataframe.

Point 9 is something that's not related to future/short trading - and will therefore also not be treated in that context (it can be a separate enhancement), but has some severe downsides when it comes to risk management, so this will not be something we'll be adding/implementing quickly.

**Comment by fridary** [comment] 2022-01-16 07:31
@samgermain 
I am still struggling how to manage git commits and pulls. Is it possible to make pull requests just only for some pieces of code, but no files? I work on vscode. Example:
![Снимок экрана 2022-01-16 в 10 22 03](https://user-images.githubusercontent.com/3791864/149651157-0302b3e5-b1b9-4f8c-aca5-448f2712395e.png)

The problem there are many codes I added for myself (it hits in the same files), but no need to add this to main repo.
What about points above - **11)** and then **8)** are the most critical, I don't know how to fix.

**Comment by samgermain** [comment] 2022-01-16 08:46
> @samgermain I am still struggling how to manage git commits and pulls. Is it possible to make pull requests just only for some pieces of code, but no files? I work on vscode. Example: ![Снимок экрана 2022-01-16 в 10 22 03](https://user-images.githubusercontent.com/3791864/149651157-0302b3e5-b1b9-4f8c-aca5-448f2712395e.png)
> 
> The problem there are many codes I added for myself (it hits in the same files), but no need to add this to main repo. What about points above - **11)** and then **8)** are the most critical, I don't know how to fix.

You'll need to pull all of it if you're going to make updates, otherwise you'll be removing the updates when your branch gets merged in, if you have changes that you made yourself then they'll get merged in when you pull, but you'll have to manually resolve any conflicts

Gitlens is a helpful git tool for VSCode, it's an extension

**Comment by fridary** [comment] 2022-01-16 09:41
@samgermain 
Ok I'll try.
I found bug for **11.** point. The problem you store `entry_long/entry_short/exit_long/exit_short` as `np.Nan` or `1.0` float values, while freqtrade `stable` stores `0/1` integers. That's why `if` conditions are not being done.
Fix:

```
def _get_sell_trade_entry_for_candle(self, trade: LocalTrade,
                                         sell_row: Tuple) -> Optional[LocalTrade]:
        # TODO-lev: add interest / funding fees to trade object ->
        # Must be done either here, or one level higher ->
        # (if we don't want to do it at "detail" level)

        sell_candle_time = sell_row[DATE_IDX].to_pydatetime()
        enter = sell_row[SHORT_IDX] if trade.is_short else sell_row[LONG_IDX]
        exit_ = sell_row[ESHORT_IDX] if trade.is_short else sell_row[ELONG_IDX]

       # adding:
        enter = 0 if np.isnan(enter) else int(enter)
        exit_ = 0 if np.isnan(exit_) else int(exit_)
```

**Comment by xmatthias** [comment] 2022-01-16 12:06
@fridary are you talking about backtesting, or live mode?

i've been aware of this somehow - but i don't think this is the correct fix (this will crash if i assign with `dataframe.loc[..., 'enter_long'] = "1"` (because it's a string, and `isnan` won't handle strings).

for point 8) - it's good to capture this - you can work around this by simply setting `stoploss_on_exchange` to false.

**Comment by fridary** [comment] 2022-01-16 12:19
@xmatthias I was talking about backtesting. Sell signals never executes, because there are conditions in `should_exit()` like `if exit_`, but for `exit_=np.NaN` we have incorrect results.
For **8.** I fount there is no `stop_loss_limit` order for futures on binance, so to fix that we need simply change `ordertype = "stop_loss_limit"` to `ordertype = "stop"` in `binance.py`. (https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info)

**Comment by xmatthias** [comment] 2022-01-16 12:57
backtesting integration is not done yet (it's also missing funding fees, ...) ... so it's expected to eventually encounter bug.

For stop-orders - i think that's too early to look at this in detail yet - so far, that branch has not made any (verified) regular buy/sell cycle in futures markets (not long, not short) - so on exchange stop orders are quite some range off from a "we get to it" point.

**Comment by xmatthias** [comment] 2022-01-16 13:51
Point 11 is now fixed in the latest feat/short branch.

**Comment by fridary** [comment] 2022-01-16 14:58
One more bug: custom functions from strategy callbacks do not get dataframe (for futures) when backtesting. Example:
```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: 'datetime',
                        current_rate: float, current_profit: float, **kwargs) -> float:
        # dataframe will be empty
        dataframe, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
```
Error in `_get_ohlcv_as_lists()`: `self.dataprovider._set_cached_df(pair, self.timeframe, df_analyzed, CandleType.SPOT) <---`

**Comment by xmatthias** [comment] 2022-01-16 18:16
As you seem to be tracking down the problems yourself (which is great, don't get me wrong), i'd encourage you to create Pull requests implementing (or proposing) a fix for the problematic segments.

It's quite little work once you've tracked the problem down - and will help us as we don't have to investigate / fix it ourselfs, only to review the proposal.

**Comment by botzill** [comment] 2022-01-31 13:05
Hi.

Is this feature near to test or still in development? I would like to give it a try

Thanks.

**Comment by samgermain** [comment] 2022-02-01 19:41
@fridary Hows it going? Have you figured out the rest of the issues that you pointed out?

**Comment by richardjozsa** [comment] 2022-02-01 19:57
Hi guys,
I've tried in live mode what @fridary wrote with the latest updates and merges with feat/short and isolated/liq(before the merge). However I tried it when he commented it in some days ago and I just wanted to let you know my experiences, which might help.  
So the 2. 3. 4. problem is still there wit the the latest commits and merges. I've repaired it with the description and 10 days ago it worked, when I put the leverage in the strategy, the entry was good, with the right leverage, but I couldn't make it to sell it whenever I tried. Btw, today when I tried with the latest commits, and I also repared the 2. 3. and 4.th problem what he mentioned, but it couldn't enter any position, because it couldn't set the leverage while I used the same setup as 10 days ago. I haven't had time to go deeper in the problems unfortunately. I used Binance USD-T futures. 
I can repair and push the 2. 3. and 4.th problem it is a child game with the description if you need it. 

Thank you for the nice work guys, it is still the best tool out there. :) 
Cheers.

**Comment by samgermain** [comment] 2022-02-02 03:51
> Hi guys, I've tried in live mode what @fridary wrote with the latest updates and merges with feat/short and isolated/liq(before the merge). However I tried it when he commented it in some days ago and I just wanted to let you know my experiences, which might help. So the 2. 3. 4. problem is still there wit the the latest commits and merges. I've repaired it with the description and 10 days ago it worked, when I put the leverage in the strategy, the entry was good, with the right leverage, but I couldn't make it to sell it whenever I tried. Btw, today when I tried with the latest commits, and I also repared the 2. 3. and 4.th problem what he mentioned, but it couldn't enter any position, because it couldn't set the leverage while I used the same setup as 10 days ago. I haven't had time to go deeper in the problems unfortunately. I used Binance USD-T futures. I can repair and push the 2. 3. and 4.th problem it is a child game with the description if you need it.
> 
> Thank you for the nice work guys, it is still the best tool out there. :) Cheers.

Yeah if you could push a PR for the 3rd that would be great

**Comment by samgermain** [comment] 2022-02-02 03:54
#2 is a CCXT issue, I'll fix it

**Comment by samgermain** [comment] 2022-02-02 04:48
@xmatthias I made a PR for issues 3-6 https://github.com/freqtrade/freqtrade/pull/6346, #2 is a CCXT issue that I'm going to fix

Could you take a look at issues 8-11, they involve parts that you worked on, some of them you might have fixed already

**Comment by xmatthias** [comment] 2022-02-02 05:53
regarding 8 - i don't see stoploss-on-exchange to be relevant at the moment. feat/short is not in a state yet where we can actually test THIS part (it fails to sell regular trades).
While we should aim to support this before merging to develop - i don't see this as "next step" - not unless the remaining trading logic (buying, selling, calculations) works correctly for the exchanges we aim to support.
Worst case will be to temporarily disable support for stoploss-on-exchange for futures mode for the initial release.

9 - i've already stated here that freqUI should be used to plot data. We'll not be adding support for futures to `plot-dataframe` at this point (i've now added this to the documentation). 
`plot-profit` on the other hand should work fine.

11: this code will not work on develop (Wrong column names) - and it's incomplete, which means cannot reproduce (it's also unclear which mode was used).
using `enter_long` and `exit_long` does however work just fine in my tests - so maybe exit-signal is disabled or whatever.

**Comment by fridary** [comment] 2022-02-02 07:51
Problem 8. I already texted how to fix and for me it works (binance futures):

> For **8.** I fount there is no `stop_loss_limit` order for futures on binance, so to fix that we need simply change `ordertype = "stop_loss_limit"` to `ordertype = "stop"` in `binance.py`. (https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info)

For 9. fix is also texted:

> The problem is incorrect candle_type param passed to ohlcv_load() in idatahandler.py, someone forgot add candle_type=config.get('candle_type_def', CandleType.SPOT) in load_data() to init_plotscript()

For me `feat/short` basics functions works for live trading if fix what I wrote.

@richardjozsa for selling it's 6. problem. I didn't go in details, perhaps problem with database leverage value saving, but:
> Quick fix disable checking self._lev_prep(pair, leverage) for exit in exchange.py create_order()

As I remember in `def execute_entry()` I added `type_='enter'` param to `order = self.exchange.create_order(...)` and `type_='exit'` same in `def execute_trade_exit()`, then in `create_order(... type_=str)` in `exchange.py` wrap:
```
if type_ == 'enter':
    self._lev_prep(pair, leverage)
```

p.s. there is also major bug `@informative` in strategy don't receive data for futures. Bug is in `informative_decorator.py`:
`informative_pairs.append(InformativeData(_asset, _timeframe, _fmt, _ffill, CandleType.SPOT)) <-- need to change config value`

**Comment by xmatthias** [comment] 2022-02-02 15:55
@fridary If you've fixed things already - please create a PR adding these changes to the feat/short branch. 

Having to piece together information from issue comments is just wasting time (both ours and yours).

> p.s. there is also major bug @informative in strategy don't receive data for futures

You're clearly not on the latest feat/short branch - as this was fixed roughly a week ago.

**Comment by fridary** [comment] 2022-02-02 16:23
@xmatthias I would love to add PR, but I don't know how to do that when I made a lot of custom changes in code, so I don't know how to separate fixes and custom changes as I described above:

> @samgermain I am still struggling how to manage git commits and pulls. Is it possible to make pull requests just only for some pieces of code, but no files? I work on vscode. Example: ![Снимок экрана 2022-01-16 в 10 22 03](https://user-images.githubusercontent.com/3791864/149651157-0302b3e5-b1b9-4f8c-aca5-448f2712395e.png)
> 
> The problem there are many codes I added for myself (it hits in the same files), but no need to add this to main repo. What about points above - **11)** and then **8)** are the most critical, I don't know how to fix.

**Comment by xmatthias** [comment] 2022-02-02 16:29
if you use visual studio code - you can add (or not add) individual lines to a commit.

in general, i'd suggest to use the [github git flow](https://docs.github.com/en/get-started/quickstart/github-flow) for creating a PR - which basically means - you start from feat/short (the branch you target) - and add the changes you'd like to add to the new branch - and make a PR out of that).

If you've already got the changes commited in a "mixed" form - you might need to either cherry-pick individual commits - or copy/paste individual lines.
that said - the example above has been changed today - so that particular instance would no longer be necessary (others might be ... i assume the image is just a sample).

**Comment by samgermain** [comment] 2022-02-03 08:19
> @xmatthias I would love to add PR, but I don't know how to do that when I made a lot of custom changes in code, so I don't know how to separate fixes and custom changes as I described above:
> 
> > @samgermain I am still struggling how to manage git commits and pulls. Is it possible to make pull requests just only for some pieces of code, but no files? I work on vscode. Example: ![Снимок экрана 2022-01-16 в 10 22 03](https://user-images.githubusercontent.com/3791864/149651157-0302b3e5-b1b9-4f8c-aca5-448f2712395e.png)
> > The problem there are many codes I added for myself (it hits in the same files), but no need to add this to main repo. What about points above - **11)** and then **8)** are the most critical, I don't know how to fix.

Use VSCode, and use an Extension called Gitlens, it makes it really easy, I made a video on how to get only the changes you want and create a PR from them

[Part 1](https://i.imgur.com/ItBsBVd.mp4)
[Part 2](https://i.imgur.com/uw2NYb8.mp4)

**Comment by samgermain** [comment] 2022-02-26 13:07
@xmatthias Are issues **7**,**8**,**9**,**10**, and **11** all still relevant? And Issue **5** will be fixed with https://github.com/freqtrade/freqtrade/pull/6423 ?

**Comment by xmatthias** [comment] 2022-02-26 13:58
I don't think they are - but issues that raise multiple problems are very difficult to track.

I'll assume they're all closed - should that not be the case, please raise them as separte issues (one issue per problem).

**Comment by samgermain** [comment] 2022-02-26 14:11
> I don't think they are - but issues that raise multiple problems are very difficult to track.
> 
> I'll assume they're all closed - should that not be the case, please raise them as separte issues (one issue per problem).

I'm certain that issue **10** is still relevant, because we didn't fix the plotting issues, I don't think this issue should be closed without opening a new one with the problems that are still relevant

I can create a new issue, but I want to know if any of those other ones are solved

**Comment by xmatthias** [comment] 2022-02-26 14:16
I've mentioned multiple times above that the plotting point is not relevant and will probably not be fixed as we have freqUI now, so issue **10** is a _won't fix_ in my eyes.

That doesn't mean you can't fix it if you want to (it's also tracked as "nice to have" in the trello board) - but keeping an issue like this one open (one that mixes 10 different problems) is problematic as it wastes people's time just **trying** to understand what is solved and what isn't.

**Closed as completed** 2022-02-26 14:20 UTC
Labels: Non-spot

**Comment by samgermain** [comment] 2022-02-26 22:52
> I've mentioned multiple times above that the plotting point is not relevant and will probably not be fixed as we have freqUI now, so issue **10** is a _won't fix_ in my eyes.
> 
> That doesn't mean you can't fix it if you want to (it's also tracked as "nice to have" in the trello board) - but keeping an issue like this one open (one that mixes 10 different problems) is problematic as it wastes people's time just **trying** to understand what is solved and what isn't.

Then relevant wasn't the correct word to use in this context.

----------------

Do you have an opinion on issue 7? I don't see it mentioned anywhere except in the top issue

> 7. profit calculation during real time in freq UI when long position with leverage is lower than binance web interface, but anyway when closing trade profit calculates perfect accurately. Shorting positions works good too.

**Comment by xmatthias** [comment] 2022-02-27 06:41
Freqtrade profit includes fees (both open and closed, even though closed are not yet applied).
so the information is not quite sufficient to determine if it's a problem or not (i assume it's not - profit on other platforms i tested on already was as expected).

Platforms tend to  either show profit without profit at all (so they hide fees) - or without the close-fee (freqtrade takes an educated guess about it - assuming they're as high as the open ones).

**Comment by samgermain** [comment] 2022-02-27 17:36
Ok, I'm just going to leave a note for future reference to check what issues were solved

----------------

**[Point 7 was seen as not an issue](https://github.com/freqtrade/freqtrade/issues/6224#issuecomment-1053241333)**

> 7. profit calculation during real time in freq UI when long position with leverage is lower than binance web interface, but anyway when closing trade profit calculates perfect accurately. Shorting positions works good too.


**[Point 9 was seen as not a futures issue](https://github.com/freqtrade/freqtrade/issues/6224#issuecomment-1013077312)**

> 9. python -m freqtrade download-data -c 'config.json' -d '/data_crypto' -t 3m -p ETH/USDT --days 60
it created /data_crypto/futures folder and ETH_USDT-3m-futures.json, ETH_USDT-8h-funding_rate.json, ETH_USDT-8h-mark.json
> when I make python -m freqtrade backtesting -c 'config.json' -d '/data_crypto --timeframe 3m -p ETH/USDT' it works, buy plot-dataframe says WARNING freqtrade.data.history.idatahandler._check_empty_df() No history data for pair: "ETH/USDT", timeframe: 3m., although Using data directory: log shows correct path.
The problem is incorrect candle_type param passed to ohlcv_load() in idatahandler.py, someone forgot add candle_type=config.get('candle_type_def', CandleType.SPOT) in load_data() to init_plotscript().

**[Point 10 was seen as unnecessary to fix, because it's legacy software now that freqUI is available](https://github.com/freqtrade/freqtrade/issues/6224#issuecomment-1013077312)**

>  10. I set when backtesting on 3m ETH/USD 11-13 Jan 2022

```
minimal_roi = {
        "0": 0.002,
    }
```

> and it works correct when long but when short it seems it does not calculate in current candle. Another weird thing, also there are no buy triangles when shorting on plot.

------------

All the other issues should be fixed
