### ISSUE TITLE
WARNING - Unable to create trade for -/EUR: Available balance (0.0 EUR)

### ISSUE THREAD

**Issue by LightDelphin** [freqtrade/freqtrade#3293] opened 2020-05-12 14:13 UTC
## Step 1: Have you search for this issue before posting it?

Searched, but could not solve the problem.

## Step 2: Describe your environment

  * Operating system: ____Ubuntu 18.04.4 LTS
  * Python Version: _____ (`python -V`)  2.7.17
  * CCXT version: _____ (`pip freeze | grep ccxt`) 1.26.53
  
## Step 3: Describe the problem:

There were deals in dry-run mode, everything works. I bought a BTC kraken and run the bot in live mode. How to configure config correctly so that it works as in dry mode?

### Steps to reproduce:

 1. Configured from scratch config
 2. Inserted tokens
 3. Launched the bot freatrade trade --strategy stratege1
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs:

  ```
  {
    "max_open_trades": 5,
    "stake_currency": "EUR",
    "stake_amount": 0.40,
    "tradable_balance_ratio": 0.99,
    "fiat_display_currency": "EUR",
    "ticker_interval": "5m",
    "dry_run": false,
    "trailing_stop": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "use_order_book": false,
        "ask_last_balance": 0.0,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": false,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy":{
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1,
        "use_sell_signal": true,
        "sell_profit_only": false,
        "ignore_roi_if_buy_signal": false

    },
    "exchange": {
        "name": "kraken",
        "key": "---",
        "secret": "---",
        "ccxt_config": {"enableRateLimit": true},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 1000
        },
        "pair_whitelist": [
            "ADA/EUR",
            "ATOM/EUR",
            "BAT/EUR",
            "BCH/EUR",
            "BTC/EUR",
            "DAI/EUR",
            "DASH/EUR",
            "EOS/EUR",
            "ETC/EUR",
            "ETH/EUR",
            "LINK/EUR",
            "LTC/EUR",
            "QTUM/EUR",
            "REP/EUR",
            "WAVES/EUR",
            "XLM/EUR",
            "XMR/EUR",
            "XRP/EUR",
            "XTZ/EUR",
            "ZEC/EUR"
        ],
        "pair_blacklist": [

        ]
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "telegram": {
        "enabled": true,
        "token": "---",
        "chat_id": "---"
    },
    "initial_state": "running",
    "forcebuy_enable": false,
    "internals": {
        "process_throttle_secs": 5
    },
    "download_trades": true
}
  ```
```
2020-05-12 17:05:38,939 - freqtrade.wallets - INFO - Wallets synced.
2020-05-12 17:05:38,943 - freqtrade.freqtradebot - WARNING - Unable to create trade for LINK/EUR: Available balance (0.0 EUR) is lower than stake amount (0.4 EUR)
2020-05-12 17:05:44,813 - freqtrade.wallets - INFO - Wallets synced.
2020-05-12 17:05:44,817 - freqtrade.freqtradebot - WARNING - Unable to create trade for XRP/EUR: Available balance (0.0 EUR) is lower than stake amount (0.4 EUR)
2020-05-12 17:05:50,818 - freqtrade.wallets - INFO - Wallets synced.
2020-05-12 17:05:50,822 - freqtrade.freqtradebot - WARNING - Unable to create trade for LINK/EUR: Available balance (0.0 EUR) is lower than stake amount (0.4 EUR)
```

I want to trade my balance on the kraken, there are 31 eur. Maybe the minimum bid is different in the kraken? Or what is the problem?

**Comment by xmatthias** [comment] 2020-05-12 14:18
the minimum tradable amount on kraken depends on the pair, but is usually around 20 EUR.
This limit is also respected in dry-mode - so you definitely did not run the bot with this configuration in dry-mode - as it would create no trade in that scenario either.


You've set your amount 0.4 - so you're trading 0.4 EUR instead of 20.

After fixing this - best run `/balance` via telegram to verify that the bot is correctly seing your 31 EUR.

Note:
Obviously, as you increase the stake-amount, to 20 EUR, only one trade can be opened at a time.

**Comment by LightDelphin** [comment] 2020-05-12 14:30
In dry mode, writes so freqtrade.freqtradebot - ATTENTION - I can not open a new transaction for BTC / EUR: the amount of the bet is too small (3 <19.258352941176472)

Why in real mode writes that the balance is 0? Or is it so necessary? I just got a little confused.

**Comment by LightDelphin** [comment] 2020-05-12 14:34
If I bet 20, will it work?

**Comment by hroff-1902** [comment] 2020-05-12 14:47
> Why in real mode writes that the balance is 0? Or is it so necessary? I just got a little confused.

https://support.kraken.com/hc/en-us/articles/360022634112-Transferring-funds-to-your-Trading-Wallet

**Comment by LightDelphin** [comment] 2020-05-13 12:32
If I am from Ukraine, then you can’t trade. I understand it does not work out?

**Comment by xmatthias** [comment] 2020-05-13 14:10
I'm not sure i understand why you shouldn't be able to trade.

kraken seems to be only blocked from a [few countries](https://support.kraken.com/hc/en-us/articles/360001368823-Geographic-Restrictions-Can-I-use-Kraken-if-I-m-from-) - Ukraine is not on that list.

**Comment by LightDelphin** [comment] 2020-05-13 15:11
> Я не уверен, что понимаю, почему вы не должны иметь возможность торговать.
> 
> Кракен, кажется, заблокирован только из [нескольких стран](https://support.kraken.com/hc/en-us/articles/360001368823-Geographic-Restrictions-Can-I-use-Kraken-if-I-m-from-) - Украины нет в этом списке.

As far as I understand, trading is possible only on futures. Here is a list of countries blocked https://support.kraken.com/hc/en-us/articles/360023786632-Kraken-Futures-eligibility-and-availability

**Comment by hroff-1902** [comment] 2020-05-13 15:39
actually no, Kraken futures is a different story, the bot (and the ccxt library below) normally trades Kraken margin markets...

So it should be okay for Ukraine since you have established account and passed KYU checks they perform. Also, there is no any geo restrictions for marging trading in this table in their support page:
https://support.kraken.com/hc/en-us/articles/360001395743-Verification-levels-explained

**Comment by LightDelphin** [comment] 2020-05-13 17:12
yes, but why does the bot write that the balance is 0. And then you need to somehow throw your ctry btc to the trading floor? I can not understand.

**Comment by xmatthias** [comment] 2020-05-13 17:26
well - best make sure that you disabled dry-run mode - and inserted the API keys correctly. 
Then start the bot and run `/balance` on telegram - which should show you your balance.
If that's not the case, look at the logs for errors - and look at the API key permissions (you can create keys with almost no permissions iirc).

**Comment by hroff-1902** [comment] 2020-05-13 17:29
yeah, my bad -- there is no separate spot and margin wallets on Kraken as for futures...

**Comment by hroff-1902** [comment] 2020-05-13 17:58
I have a deposit on Kraken, just shown with REST client `balance` command with freqtrade running live -- anything is okay...

(@xmatthias is not it the issue about Kraken balances which are not exposed by Kraken via API till one trade (spot, for example) is made on the currency, even if the currency were deposited, but not traded yet...? And I've done a few spot trades manually so the balances are shown here...)

**Comment by LightDelphin** [comment] 2020-05-13 18:03
> хорошо - лучше всего убедиться, что вы отключили режим пробного запуска - и правильно вставили ключи API.
> Затем запустите бота и запустите `/balance`телеграмму, которая покажет вам ваш баланс.
> Если это не так, посмотрите в журналах на наличие ошибок - и посмотрите на разрешения ключа API (вы можете создавать ключи практически без полномочий iirc).


Dry mode turned off. I inserted the keys correctly and the balance shows, but when trading, it says that the balance is 0

**Comment by hroff-1902** [comment] 2020-05-13 18:04
try to trade some amount of USD (that's your currency, you said) on spot and repeat then...

**Comment by LightDelphin** [comment] 2020-05-13 19:41
> try to trade some amount of USDEUR (that's your currency, you said) on spot manually and repeat then...
> 
> (if you translate English text with a translator -- write to me on Slack in Russian 😉 , in a private message...)


You have a lead, on the kraken account itself, make an exchange and then start the bot and it should work?

**Comment by hroff-1902** [comment] 2020-05-13 19:47
> You have a lead, on the kraken account itself, make an exchange and then start the bot and it should work?

I hope; at least I cannot reproduce the issue -- I see all of my balances on Kraken
However, in the same time, I see a set of issues at the ccxt library repo, reporting similar: no balance data are returned by Kraken. I did not get yet particular conditions, but it seems to be related somehow how Kraken handles balances for new deposits. So try to make a small spot trade with that currency manually on Kraken and see the balance reported by freqtrade again.
It seems to be some strange "feature" of Kraken, neither a bug in freqtrade nor in ccxt lib.
So trade manually EUR to BTC and then back to EUR, for example.

**Comment by xmatthias** [comment] 2020-05-14 04:17
well - kraken does have "special" treatment in freqtrade to have a complete balance result ...

either way - if `/balance` shows the correct result, then trades should work as well - assuming the minimum stake-size (`stake_amount`) is > 10 EUR (which is the minimum tradable size on kraken).

**Comment by hroff-1902** [comment] 2020-05-14 10:18
have you tried the recipe above? is it okay now?

**Comment by LightDelphin** [comment] 2020-05-14 16:23
Thank you so much. You are the best. I managed to make the first deal with the bot. He bought ether, but the next currency failed, you need to replenish the exchange for more euros. Who will tell you where it is better to replenish, so that there would be less commission? And then I replenished through exmo and the commission is big.

**Comment by xmatthias** [comment] 2020-05-14 16:28
Thanks for the feedback.

These questions (how to replenish / at what cost / whatever) are best asked to the Kraken support - and are WAY beyond what we can and will provide support for here.

Thanks for your understanding - and have fun with the bot! :smile:

**Closed by xmatthias** 2020-05-14 16:28 UTC
Labels: Question
