### ISSUE TITLE
Unrealistically high CPU usage of the freqtrade process when frequi is run with a large database on sqlite3 instead of postgresql

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#6791] opened 2022-05-08 03:54 UTC
## Describe your environment

  * Operating system: ubuntu LTS
  * Python Version: 3.8.10
  * CCXT version: 1.81.43
  * Freqtrade Version: c9498d0117d411a544e7381551fad418d2546577
  
## Describe the problem:

This is related to frequi but it's practically a freqtrade issue because it's the freqtrade process that goes on high CPU usage. Basically there is an extremely high CPU usage of freqtrade **for several minutes** when first connecting to frequi's dashboard (before it is able to show the all graphs) which goes away if you migrate it to a postgresql database. I can't imagine any scenario that this would be normal because we're talking about a responsiveness of **less than 5 seconds** on postgres while the sqlite db can easily fit into RAM.

### Steps to reproduce:

I realize you might not know how to migrate it to postgres so here's what I learned in order to do it very easily

1: First just make a postgres db with a basic tutorial (e.g. https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-20-04) and make a user and make a dbase
2: Just run freqtrade once with the relevant `--db-url` of the docs so that the dbase gets the relevant freqtrade tables (it makes the next step much faster because sqlite lacks a lot of the basic datatypes etc.)
3: a) using sqlite3: drop all freqtrade tables that end with "_bakX" and dump the db with `sqlite3 db_file .dump > dump.sql` and delete all lines in the dump which are not 'insert' lines 
    b) since `booleans` do not exist in sqlite3 and our inserts have integers: do this before and after the next step: https://dba.stackexchange.com/a/46199
    c) finally insert the entries to postgres with `psql < dump.sql`

### Observed Results:

  * What happened?

Extremely fast frequi response even with a large dbase (all the graphs at the dashboard appear in less than 5 seconds).

  * What did you expect to happen?

Frequi on sqlite3 is unfathomably slow (minutes on high CPU usage of the freqtrade process before it is able to show all dashboard graphs instead of being done almost instantly) which can't be explained by sqlite3 inefficiencies compared to server databases.

**Comment by epigramx** [comment] 2022-05-08 04:17
By the way: the nature of the problem might be worse than just being related to performance. Because of the slowness (even when tested on a fast PC), it appears to not be able to show the relevant graphs at the dashboard at all sometimes (possibly because it triggers certain timeouts).

---

I see that at the moment of load/reload, postgres has some cpu usage at several processes 
![image](https://user-images.githubusercontent.com/2960257/167281684-060cf238-b370-47d8-9c5f-f4a7af840fb2.png)

but it's very low so I guess if it is sqlite3 being inefficient compared to it and freqtrade did nothing wrong: I can only imagine sqlite being terrible for the purpose but it's hard to say that.

**Comment by epigramx** [comment] 2022-05-08 04:26
I see that at the moment of load/reload, postgres has some cpu usage at several processes 
![image](https://user-images.githubusercontent.com/2960257/167281684-060cf238-b370-47d8-9c5f-f4a7af840fb2.png)

but it's very low so I guess if it is sqlite3 being inefficient compared to it and freqtrade did nothing wrong: I can only imagine sqlite being terrible for the purpose but it's hard to say that.

**Comment by samgermain** [comment] 2022-05-08 05:27
I think if you use clang as a compiler instead of g++, it might help. I wrote how to install TA-LIB using clang in [these instructions](https://github.com/samgermain/freqtrade-ec2-instructions#12a-optionl-kinda-youll-probably-run-into-less-problems-if-you-use-clang-as-your-compiler-and-install-ta-lib-with-it-instead-of-using-gcc). I didn't really know what I was doing though so I can't help you more than that.

**Comment by xmatthias** [comment] 2022-05-08 06:09
I don't really see how clang would change behavior here - sqlite is not compiled on the user system but is builtin to python - so unless you expect users to compile python themselfs (and with a different compiler) - that's not really going to help this cause.

---

@epigramx what's the definition of "large database"? is that 100 trades? 1000 trades? what's the limit when you see this behavior start?

To be honest - currently i don't really see this as something freqtrade causes. We use SQLAlchemy as ORM - which handles the differences between sqlite and postgres. 
As such, if we assume there's a different behaviour in the two - then it'll be caused by an SQL Alchemy oddity (or bug).

I don't think the fact that sqlite fits in memory is relevant - as the database won't be in memory - but on disk.
Sqlite supports in-memory databases - but they're volatile and will disappear once the process is killed.

This may be different in postgres - as PG will potentially cache tables - which is clearly a mechanism sqlite does not have.

**Comment by epigramx** [comment] 2022-05-08 08:33
Yeah I also suspect it's out of your hands in which case it would need to take it to either sqlalchemy devs or sqlite devs but that would need good understanding of how freqtrade operates. @xmatthias the problem appears even on less than 4k trades so it should happen in the ~10k test dbase you usually mention if you compare a sqlite3 version vs a dump of itself on a new postgres. I guess if we end up thinking it's inevitable: we should not be using sqlite at all after a certain number of trades.

---

See here https://stackoverflow.com/a/11769768/277716 (the official docs appear to go into more detail https://docs.sqlalchemy.org/en/14/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow). SQLAlchemy apparently has 2 versions (ORM and Core) and ORM is extremely slower for certain operations than regular SQLite and I see Freqtrade imports from the ORM version (slow for certain operations).

Not sure why that would make SQLite specifically to be even slower (and not all DBs) but I guess it's possible if it causes a side effect.

**Comment by epigramx** [comment] 2022-05-08 09:42
See here https://stackoverflow.com/a/11769768/277716 . SqlA apparently has 2 versions (orm and core) and orm is extremely slower than regular sqlite.

I see sqlite imports from the orm version (slow).

**Comment by xmatthias** [comment] 2022-05-08 13:36
an ORM is always slightly slower - as it provides more convenience features (and as such - needs more code to support the different usecases).
That's expected - but would slow down postgres just as much as sqlite.

we'll definitely not be switching to the core version (that would require writing all queries manually - which in itself is problematic (and a maintenance nightmare at that).

The scenario you're talking about (startup of freqtrade) is however a read only scenario - neither of which would be covered by the above links (both talk about bulk inserts - which freqtrade does not do except for migrations (where we use raw sql, anyway).

> that would need good understanding of how freqtrade operates.

I'm not sure what precisely you'd be looking for - we use the implicitly provided `query_property()`  from the session - which is based on the sqlalchemy documentaiton.

**Comment by epigramx** [comment] 2022-05-08 13:50
I would only be able to say "sqlite slow but postgres fast" which is hard to debug or prove it's a bug. It could be normal that postgres itself is massively faster but the difference is so vast that it feels like freqtrade or its libraries are busy-waiting somewhere. 
This is related to documentation because if after a few thousand trades this happens to everyone then it should be suggested to not use sqlite at all (for the ui at least) unless it's deleted/recreated or trimmed.

---

https://github.com/sqlalchemy/sqlalchemy/discussions/7997

![image](https://user-images.githubusercontent.com/2960257/167321537-7decb609-e180-4504-94c9-742b463897e2.png)

**Comment by epigramx** [comment] 2022-05-09 00:09
https://github.com/sqlalchemy/sqlalchemy/discussions/7997

![image](https://user-images.githubusercontent.com/2960257/167321537-7decb609-e180-4504-94c9-742b463897e2.png)

**Comment by xmatthias** [comment] 2022-05-09 18:34
using the same 7000+ database, postgres is (in total) slightly slower (especially early on).

sqlite has the first few requests (up to trade 3000) below 500ms.

![image](https://user-images.githubusercontent.com/5024695/167473209-e5629087-15aa-467f-a795-64751ff31d2d.png)


with postgres, all requests are around 500ms (especially the first few). As such - postgres can clearly not be recommended for regular database sizes - here sqlite clearly has some advantages.

![image](https://user-images.githubusercontent.com/5024695/167473086-f7759392-da66-421a-ae09-1097d60a3325.png)

While it's spaced out evenly in this attempt - that's not the case always. It's however clearly visible that performance improves - as postgres does have some in-memory caching.

The problem is clearly the performance of `offset` in sqlite, but there's little ways around that, really.

using `offset <= id offset + limit` would be an option - but pagination based on an ID field that's not necessarily sequential (you'll have missing orders in the middle) will lead to "limit" not returning "limit" trades - which is clearly a bad option.

**edit** i guess this link about sqlite describes it best: https://sqlite-users.sqlite.narkive.com/QSYr6y55/sqlite-sqlite-select-query-slowing-down-while-fetching-from-higher-offset

> Performance of a query with OFFSET N is roughly equivalent to that without OFFSET clause, where you retrieve and discard first N rows. SQLite has no means to jump directly to row N.

**Comment by epigramx** [comment] 2022-05-09 20:26
Taking 2.3 seconds to take 500 entries from a table of this (low-ish) complexity sounds pretty suspect. Here it's almost unusable because it may take so long at the dashboard ui page in some attempts that something appears to timeout and the page may show no data in graphs at all other than the daily. 

I also suspect it might be related to local libraries compiled from other languages that are different from OS to OS (e.g. sqlite itself).

---

btw 
![image](https://user-images.githubusercontent.com/2960257/167492882-b77662d5-7214-4de1-8bb5-bcab80746fe9.png)

---

I'm looking at the solutions that call to have a column that indexes the records, so that to use e.g. `SELECT * FROM a_table WHERE id>=10000 AND id<10500` instead of offsetting, but I notice in this case we can have deleted entries so we don't actually have an enumeration index in the database itself at all.

Does that mean if a new enumeration-index column is (re)populated every time a record changes it would make it super fast after replacing `OFFSET` queries with `WHERE` queries or is there something in the relational nature of the 3 tables that would prevent it?

**Comment by epigramx** [comment] 2022-05-09 20:33
btw 
![image](https://user-images.githubusercontent.com/2960257/167492882-b77662d5-7214-4de1-8bb5-bcab80746fe9.png)

**Comment by epigramx** [comment] 2022-05-10 07:17
I'm looking at the solutions that call to have a column that indexes the records, so that to use e.g. `SELECT * FROM myTable WHERE id>=95000 AND id<95100` instead, but I notice in this case we can have deleted entries so we don't actually have an enumeration index in the database itself at all.

Does that mean if one is (re)created every time a record changes it would make it super fast by replacing `OFFSET` queries with `WHERE` queries or is there something in the relational nature of the 3 tables that would prevent it?

**Comment by xmatthias** [comment] 2022-05-10 08:02
i've tried the above as i've found that myself - but found it not improving performance.

there is actually in index on the [id column](https://stackoverflow.com/questions/3379292/is-an-index-needed-for-a-primary-key-in-sqlite) as it's the primary key. adding an explicit index doesn't change performance

**Comment by epigramx** [comment] 2022-05-10 08:14
There is an index but it can not be used to replace offsetting because if an entry is deleted: that index remains at its original value, so a new column would have to be used and repopulated every time a new record changes which holds the exact number of rows on the table.
I don't know why you say it didn't improve performance since you said sqlite took 2.3 seconds for 500 entries in some cases and it makes sense that it would be faster because a `WHERE` goes exactly where it needs to be instead of `OFFSET` getting old unrelated records.

**Comment by xmatthias** [comment] 2022-05-10 17:36
Using pagination based on ID (as well as using an inner join) does not help performance (it's seemingly making it worse).

![image](https://user-images.githubusercontent.com/5024695/167688545-e5a8463c-b1e3-463d-8422-1189f5319c14.png)

**Comment by epigramx** [comment] 2022-05-10 22:10
I'm half-following your conversation with the sqlalchemy devs and `lazy="select"` is indeed ludicrously faster here (we're talking about a total response of only 3 to 5 seconds now without changing anything else in the code (on sqlite (postgres seems unphased)). The other two you mentioned aren't that fast here though (maybe only `selectin` seems usable but still noticeably slower).

Would combining what's best there with avoiding the usage of `OFFSET` the fastest possible (especially since postgres seems unphased by the lazy flag and it might also be able to use optimizations)?

**Comment by xmatthias** [comment] 2022-05-11 04:20
using select will break other things - so that's one we cannot be using.

**Comment by epigramx** [comment] 2022-05-11 04:54
They seem certain `OFFSET` should be avoided one way or another. I noticed their page for situations like this <https://github.com/sqlalchemy/sqlalchemy/wiki/RangeQuery-and-WindowedRangeQuery>.

I guess at least the final method is applicable which is tracking the last id fetched which sounds clearly faster than scanning through thousands of useless records from the previous pages instead.

**Comment by xmatthias** [comment] 2022-05-11 05:08
i don't disagree that it _sounds faster_ (it does so to me, too) - but it isn't once you actually try it out.

That would make that change a blind change - which is pointless and will not help the cause.

**Comment by epigramx** [comment] 2022-05-11 05:10
It's design-wise correct even on the same performance, because it's clearly inefficient to scan through thousands of record you don't need instead of a single reference that fits into a few bytes.

The main reason I thought about it though is that if you set up an efficient pagination method: then it's probably clearer what's the rest of the code will be for the most efficient solution.

**Comment by epigramx** [comment] 2022-05-12 09:07
It's design-wise correct even on - seemingly - the same performance, because it's clearly inefficient to scan through thousands of records you don't need instead of holding a single reference of a few bytes.

The main reason I think about it in that context is that once you set up an efficient pagination method: then it's probably clearer what **the rest of the code** needs to be for the most efficient solution.

---

@xmatthias I just deleted `.limit(limit).offset(offset)` from https://github.com/freqtrade/freqtrade/blob/891900c186a75d537a79c3adbf82ed17afaa379e/freqtrade/rpc/rpc.py#L418, **and everything in the dashboard rendered almost instantly**(!) so what do I miss?

I also saw some unexplained high CPU usage (of the freqtrade process) after I started navigating around the ui but that's a separate issue I guess.

---

Not sure how was this justified (highlighted comment at frequi https://github.com/freqtrade/frequi/blob/ccfa81b05152c1154aeb56494a32738bebd061f4/src/stores/ftbot.ts#L253)

![image](https://user-images.githubusercontent.com/2960257/168388993-ba1c15db-530c-46b1-8865-c93a7b3a2106.png)

, considering I see no issues with the change of the previous reply here. 
Why would sqlite itself have problems?

---

Wait,  was someone trying to workaround the sqlite-related crashes during the usage of the UI and they tried to slow it down with limit.offset, while those problems are now properly fixed with the recent `PRAGMA journal_mode=wal` patch?

---

If you are convinced pagination is slow whatever method you use: then that leaves the problem that a modern PC responds almost instantly without pagination and it grinds to a halt with it.

If certain things break without it (such as json serialization you mentioned) then it appears it's prudent to identify what those limitations are because it doesn't seem logical to have a modern PC that has no such limitations grind to a halt in order to paginate when it doesn't need to paginate at all.

**Comment by epigramx** [comment] 2022-05-13 21:03
Not sure how was this justified (highlighted comment at https://github.com/freqtrade/frequi/blob/ccfa81b05152c1154aeb56494a32738bebd061f4/src/stores/ftbot.ts#L253)

![image](https://user-images.githubusercontent.com/2960257/168388993-ba1c15db-530c-46b1-8865-c93a7b3a2106.png)

, considering I see no issues with the above change. How would sqlite itself have problems?

**Comment by epigramx** [comment] 2022-05-13 21:35
Wait,  was someone trying to workaround the crashes during usage of the UI and they tried to slow it down with limit.offset, while those problems are now properly fixed with the recent `PRAGMA journal_mode=wal` patch?

**Comment by epigramx** [comment] 2022-05-14 10:27
@xmatthias Let's leave that sqlalchemy thread because it appears they are not interested in looking at your code and they already said their general opinions. 

If you are convinced pagination is slow whatever method you use: then that leaves the problem that a modern PC responds almost instantly without pagination and it grinds to a halt with it.

If certain things break without it (such as json serialization you mentioned) then it appears it's prudent to identify what those limits are because it doesn't seem logical to have a modern PC that has no such limits grind to a halt in order to paginate when it doesn't need to paginate at all.

**Comment by xmatthias** [comment] 2022-11-12 15:51
Running a simple test with the latest version (the one that will close this issue) - i get to the following:

on a 7000+ trade database, running without limit (or in my case, limit 10000) is slightly slower than doing requests a 500.

It's also irresponsible to think we can pull "all" of the database in one request. That may work for you - but effectively means that the whole database is pulled into memory (as python objects, and subsequently as dictionaries) - and is therefore no solution that will be accepted or implemented.

We will for sure chip away at this further in the future - but i don't see anything actionable here - as i think 3s for 7000 trades is okish, considering the size of the object that's returned.

It'll further be improved by #7735 - which brings this down to <3s (again, for 7000 trades).

**Closed as completed** 2022-11-12 15:52 UTC
Labels: RPC
