### ISSUE TITLE
Impossible to backtest on Bybit futures

### ISSUE THREAD

**Issue by macsim26** [freqtrade/freqtrade#10196] opened 2024-05-09 09:49 UTC
* Operating system: ____ubuntu 22.04
  * Python Version: _____ 3.10
  * CCXT version: _____ 4.3.11
  * Freqtrade Version: ____2024.4
  
Hello since this morning i can't do any backtesting on Bybit futures.
Yesterday it was working perfectly...
I have only this message : "2024-05-09 11:44:01,481 - freqtrade - ERROR - Pairs BTC/USDT:USDT got no leverage tiers available. It is therefore impossible to backtest with this pair at the moment."
Is there anything i can do?
Thanks

**Comment by stash86** [comment] 2024-05-09 10:30
Seems like a common issue. Some users have reported that their dry/live trades were all suddenly became 1x lev.

Please wait while we try to see what is the cause

**Comment by boiydiego777** [comment] 2024-05-09 11:48
also this on bybit today.. 

freqtrade - ERROR - Pairs AVAX/USDT:USDT, BCH/USDT:USDT, DOT/USDT:USDT, LINK/USDT:USDT, ICP/USDT:USDT, LTC/USDT:USDT, NEAR/USDT:USDT, UNI/USDT:USDT, APT/USDT:USDT, ETC/USDT:USDT, STX/USDT:USDT, FIL/USDT:USDT, ATOM/USDT:USDT, RNDR/USDT:USDT, TAO/USDT:USDT, IMX/USDT:USDT, ARB/USDT:USDT, MKR/USDT:USDT, INJ/USDT:USDT, OP/USDT:USDT, FET/USDT:USDT, THETA/USDT:USDT, TIA/USDT:USDT, RUNE/USDT:USDT, LDO/USDT:USDT, AR/USDT:USDT, SUI/USDT:USDT, QNT/USDT:USDT, JUP/USDT:USDT, ENA/USDT:USDT, NEO/USDT:USDT, DYDX/USDT:USDT, EGLD/USDT:USDT, AXS/USDT:USDT, SNX/USDT:USDT, ORDI/USDT:USDT, STRK/USDT:USDT, APE/USDT:USDT, CAKE/USDT:USDT, DYM/USDT:USDT, ILV/USDT:USDT, PENDLE/USDT:USDT, SUPER/USDT:USDT, TWT/USDT:USDT, MANTA/USDT:USDT, RPL/USDT:USDT, ENS/USDT:USDT, JTO/USDT:USDT, ETHFI/USDT:USDT, LPT/USDT:USDT, FXS/USDT:USDT, COMP/USDT:USDT, ARKM/USDT:USDT, DASH/USDT:USDT, METIS/USDT:USDT, ZEC/USDT:USDT, MASK/USDT:USDT, KSM/USDT:USDT, API3/USDT:USDT, GMX/USDT:USDT, OMNI/USDT:USDT, SSV/USDT:USDT, LSK/USDT:USDT, WAVES/USDT:USDT, YFI/USDT:USDT, BAL/USDT:USDT, UMA/USDT:USDT, BAND/USDT:USDT, CVX/USDT:USDT, RLC/USDT:USDT, PROM/USDT:USDT, PORTAL/USDT:USDT, NMR/USDT:USDT, TRB/USDT:USDT, XNO/USDT:USDT, ZEN/USDT:USDT, AUCTION/USDT:USDT, MOVR/USDT:USDT, ALICE/USDT:USDT, MTL/USDT:USDT, CYBER/USDT:USDT, LQTY/USDT:USDT, PERP/USDT:USDT, GTC/USDT:USDT, LIT/USDT:USDT, ORN/USDT:USDT, FORTH/USDT:USDT, UNFI/USDT:USDT, BOND/USDT:USDT got no leverage tiers available. It is therefore impossible to backtest with this pair at the moment

kind regards

**Comment by andrasmining** [comment] 2024-05-09 12:55
> also this on bybit today..
> 
> freqtrade - ERROR - Pairs AVAX/USDT:USDT, BCH/USDT:USDT, DOT/USDT:USDT, LINK/USDT:USDT, ICP/USDT:USDT, LTC/USDT:USDT, NEAR/USDT:USDT, UNI/USDT:USDT, APT/USDT:USDT, ETC/USDT:USDT, STX/USDT:USDT, FIL/USDT:USDT, ATOM/USDT:USDT, RNDR/USDT:USDT, TAO/USDT:USDT, IMX/USDT:USDT, ARB/USDT:USDT, MKR/USDT:USDT, INJ/USDT:USDT, OP/USDT:USDT, FET/USDT:USDT, THETA/USDT:USDT, TIA/USDT:USDT, RUNE/USDT:USDT, LDO/USDT:USDT, AR/USDT:USDT, SUI/USDT:USDT, QNT/USDT:USDT, JUP/USDT:USDT, ENA/USDT:USDT, NEO/USDT:USDT, DYDX/USDT:USDT, EGLD/USDT:USDT, AXS/USDT:USDT, SNX/USDT:USDT, ORDI/USDT:USDT, STRK/USDT:USDT, APE/USDT:USDT, CAKE/USDT:USDT, DYM/USDT:USDT, ILV/USDT:USDT, PENDLE/USDT:USDT, SUPER/USDT:USDT, TWT/USDT:USDT, MANTA/USDT:USDT, RPL/USDT:USDT, ENS/USDT:USDT, JTO/USDT:USDT, ETHFI/USDT:USDT, LPT/USDT:USDT, FXS/USDT:USDT, COMP/USDT:USDT, ARKM/USDT:USDT, DASH/USDT:USDT, METIS/USDT:USDT, ZEC/USDT:USDT, MASK/USDT:USDT, KSM/USDT:USDT, API3/USDT:USDT, GMX/USDT:USDT, OMNI/USDT:USDT, SSV/USDT:USDT, LSK/USDT:USDT, WAVES/USDT:USDT, YFI/USDT:USDT, BAL/USDT:USDT, UMA/USDT:USDT, BAND/USDT:USDT, CVX/USDT:USDT, RLC/USDT:USDT, PROM/USDT:USDT, PORTAL/USDT:USDT, NMR/USDT:USDT, TRB/USDT:USDT, XNO/USDT:USDT, ZEN/USDT:USDT, AUCTION/USDT:USDT, MOVR/USDT:USDT, ALICE/USDT:USDT, MTL/USDT:USDT, CYBER/USDT:USDT, LQTY/USDT:USDT, PERP/USDT:USDT, GTC/USDT:USDT, LIT/USDT:USDT, ORN/USDT:USDT, FORTH/USDT:USDT, UNFI/USDT:USDT, BOND/USDT:USDT got no leverage tiers available. It is therefore impossible to backtest with this pair at the moment
> 
> kind regards

I tested it and not only these, but all of the pairs are affected from bybit (349).

Regards,
andras

**Comment by xmatthias** [comment] 2024-05-09 14:35
CI failing shows it as well - it seems like the bybit API changed that's causing this - either an endpoint, or the response from that endpoint may have changed.

**Comment by JustAMamont** [comment] 2024-05-09 14:54
The reason is that starting today, when requesting leverage tiers, Bybit only returns data for 30 symbols per request.

**Comment by xmatthias** [comment] 2024-05-09 15:01
Seems to be a change in the api made [today](https://bybit-exchange.github.io/docs/changelog/v5#2024-05-09).

I don't think ccxt supports pagination for this request though - so most likely, it's something that requires an update in ccxt (though i didn't look at this in detail just yet).

**Comment by xmatthias** [comment] 2024-05-09 15:44
Opened https://github.com/ccxt/ccxt/issues/22448 for this - considering how that ccxt method works at this moment, it's currently not possible to get this list in it's entirety.

I assume it'll be fixed by an update of ccxt - until then, it's a topic of patience (also because i don't want to rush some hacky workaround for no good reason).

**Closed as completed** 2024-05-09 18:04 UTC
Labels: CCXT

**Comment by xmatthias** [comment] 2024-05-09 19:26
A workaround for it is available on develop. Will be reverted or updated once we have a proper fix upstream.

**Comment by DenisHTrading** [comment] 2024-05-24 17:46
Hi @xmatthias, I've uploaded my git repository but I still have the issue. Are you still able to reproduce? Thanks!

**Comment by xmatthias** [comment] 2024-05-24 17:48
no, bybit is working fine again.

If you're still encountering this issue - then you've most likely not updated [according to the docs](https://www.freqtrade.io/en/stable/updating/).

**Comment by DenisHTrading** [comment] 2024-05-24 17:55
I have updated my version using the script but I may have something else
wrong then, as I just configured my Bybit account to start working on
futures.

Thanks!
