### ISSUE TITLE
FTX Perpetuals

### ISSUE THREAD

**Issue by alisalama** [freqtrade/freqtrade#7681] opened 2022-10-31 14:05 UTC
## Describe your environment

  * Operating system: MacOS Monteret
  * Python Version: 3.9.1
  * CCXT version: CCXT 2.0.58
  * Freqtrade Version: docker-2022.11.dev-54c7122c
  

## Describe the enhancement

Would it be possible to implement FTX Perpetuals Futures?

It can be tricky closing full larger positions on some coins on FTX spot due to lower levels of liquidity. Overall the FTX futures market has over 5 times the volume of the spot market, however this is heavily skewed to BTC and ETH, so if you move to "smaller" coins the volume disparity is much much greater.

For example today, SUSHI has $132m daily volume on Futures, healthy enough volume, but only $6m on Spot, which is much more limiting. That is 22 times the volume. I'm sure there are larger volume differences between Spot and Futures that is just the first I chose.

For example if you are trading $10k, there would only be enough room for 600 of those trades on any given day on spot, so not a lot of market depth.

FTX spot has only 10 coins with £10m daily liquidity per day, but 49 on Futures.

This limits growth on FTX spot.

----

Is there a fundamental reason this hasn't been done? If it is implementable, I am a JS programmer by trade, but if you provide some guidance on required functions I will happily have a go at a PR to extend the [FTX Exchange](https://github.com/freqtrade/freqtrade/blob/develop/freqtrade/exchange/ftx.py) class to allow for Futures.

**Comment by xmatthias** [comment] 2022-10-31 14:35
The main reason is that ftx futures are cross futures. Currently supported exchanges (for futures) are limited to isolated futures - so this would be the first cross futures exchange.

This complicates matters a bit, as cross futures need some more logic as positions will influence each other (for example /mainly when it comes to the liquidation price.

**Comment by alisalama** [comment] 2022-10-31 15:07
Ah ok now I see the difference.

----------------

Forgive my possible ignorance, but is it not possible to just grab the liquidation price per position from the api/CCXT?

https://docs.ftx.com/#get-positions ([the CCXT equivalent](https://github.com/ccxt/ccxt/issues/6860#issuecomment-830504843)) seems to return an estimated liquidation price per position plus margin requirements, which seems to have the cross futures element baked in.

----------------

Otherwise, if we wanted to derive the liquidation prices ourselves for each position, I guess we need this for dry run purposes, we could use https://docs.ftx.com/#get-account-information (CCXT equivalent), which returns the necessary parts of the below formulae plus some position data which we will already have:

Estimated Liquidation Price = Mark Price * ( 1 + Maintenance margin requirement - Total Collateral / Total Notional Size ) _if you are long_

Estimated Liquidation Price = Mark Price * ( 1 - Maintenance margin requirement + Total Collateral / Total Notional Size ) _if you are short_

[FTX Liquidation Docs ](https://help.ftx.com/hc/en-us/articles/360027668712-Liquidations)

**Comment by xmatthias** [comment] 2022-10-31 16:16
it's mainly for dry, (but not only).

on isolated futures, you know that the liquidation price will only change if you mess with the position. on cross futures, we'll basically need to check for this on each iteration - as it'll be changing at "semi random" (it's predictable, but potentially not directly caused by trading actions).


---

oh for sure it's possible, and I've implemented most parts of it already - but it's still a rather big step compared to adding another isolated futures exchange - and i currently lack the time to finish that implementation.

As such - it's on our radar - but i'd consider it medium priority at best.

**Comment by alisalama** [comment] 2022-10-31 18:42
Thanks Matthias. I will wait for the those updates.

FTX is a great exchange where you can trade for zero fees with Limit orders and staking 25 FTT, so seems perfect for algo trading, just the volume on spot lacks any real depth.

**Comment by xmatthias** [comment] 2022-11-12 17:09
Considering current developments - FTX can no longer be considered a great exchange.

As such - i'll close this for now. Feel free to reopen should the situation around FTX turn out to be a late (or early?) aprils fool joke.

**Closed as not planned by xmatthias** 2022-11-12 17:09 UTC
Labels: Enhancement, Non-spot

**Comment by alisalama** [comment] 2022-11-15 22:20
> FTX is a great exchange where you can trade for zero fees with Limit orders and staking 25 FTT, so seems perfect for algo trading, just the volume on spot lacks any real depth.

This aged like sour milk.
