### ISSUE TITLE
Futures "Could not load leverage tiers for GLMR/USDT:USDT

### ISSUE THREAD

**Issue by TonyStarks22** [freqtrade/freqtrade#8514] opened 2023-04-17 14:45 UTC
Change exchange.py leverage tiers from Spot ( default) to FUTURES

# Converts the interval provided in minutes in config to seconds
        self.markets_refresh_interval: int = exchange_config.get(
            "markets_refresh_interval", 60) * 60

        if self.trading_mode != TradingMode.FUTURES and load_leverage_tiers:
            self.fill_leverage_tiers()
        self.additional_exchange_init()

#####

config.json 

},
   "pairlists": [{ "method": "StaticPairList" }],
    "edge": {
     "enabled": false,
     "process_throttle_secs": 3600,
     "calculate_since_number_of_days": 7,
     "allowed_risk": 0.01,
     "stoploss_range_min": -0.01,
     "stoploss_range_max": -0.1,
     "stoploss_range_step": -0.01,
     "minimum_winrate": 0.6,
     "minimum_expectancy": 0.2,
     "min_trade_number": 10,
     "max_trade_duration_minute": 1440,
     "remove_pumps": false
  },

**Comment by xmatthias** [comment] 2023-04-17 14:52
I don't really see what you're trying to accomplish with this issue.

it doesn't seem to contain a message - and the content posted is simply wrong.

**Comment by xmatthias** [comment] 2023-04-17 14:55
Assume this is a duplicate of #8512 - but whatever you're modifying is unclear - and wrong (see comment posted in that issue).

**Closed as completed by xmatthias** 2023-04-17 14:55 UTC
Labels: Duplicate
