### ISSUE TITLE
Dry Run Issue

### ISSUE THREAD

**Issue by Kaidokuni** [freqtrade/freqtrade#2741] opened 2020-01-03 15:27 UTC
Hi guys,
So I noticed something strange with the bot when running in dry run mode, it's seems that has appeared when the dry_run_wallet had been introduced.
When I /reload_conf or /stop then /start the bot and immediately want to show /profit I can see pairs from the previous config. It seems that the bot still has some of the previous trades in memory. To check this, I tried a configuration in BTC and then another one in USDT (both in dry run that I rechecked) but some BTC pairs of the first configuration still remain somehow in memory of the bot and can be visible in /profit, /performance... By the way, I have the last update of freqtrade.

/profit  (I just reloaded the bot but the first transaction was opened a week ago) 
```
TheBotName, [03.01.20 15:58]
ROI: Close trades
∙ -7.81586090 USDT (-0.34%)
∙ -7.027 EUR
ROI: All trades
∙ -7.81586090 USDT (-0.34%)
∙ -7.027 EUR
Total Trade Count: 212
First Trade opened: a week ago
Latest Trade opened: 6 hours ago
Avg. Duration: 4:17:46
Best Performing: ADA/USDT: 0.82%
```
/statut table (BTC pair among USDT config pair)
```
  ID  Pair       Since    Profit (EUR)
----  ---------  -------  --------------
115  NCASH/BTC  2 d      -2.16% (-0.00)
 137  TRX/USDT   7 h      -2.76% (-0.30)
 139  ETH/USDT   7 h      -2.61% (-0.28)
 149  BTC/USDT   1 h      -2.41% (-0.26)
```

**Comment by xmatthias** [comment] 2020-01-03 18:38
this has nothing to do with dry-run wallet, but with having a database which stores the trades (persists) them so you could reboot the server and it would be able to continue where it left of.
It also allows you to analyze dry-run trades afterwards, either in a jupyter notebook, vai SQL statements, or by using the plot methods. 


By using `/reload_conf` or `/stop` and `/start` you're simply changing the configuration - but not resetting the database - so the bot will know previous trades - and will also handle still open trades (if you think about it, a real trade will also need to be closed / handled correctly, even though you've changed a few settings).


Obviously, if you're stopping / starting the bot and would like to start fresh, you'll need to change the name of the database (`--db-url` / `db_url` in the configuration) - or alternatively delete this manually.

`--db-url` used to default to `sqlite://` for dry-runs before - so it would not persist trades to disk - so by using `--db-url sqlite://` the previous behaviour (not persisting trades) should be restored.

However - i don't think it was possible to reset the database by using /rpc methods (neither do i think it should be possible) - you'd have had to stop the bot (ctrl+c / docker stop) and restart the whole process for the database to reset.

So to me - this is intended behaviour and works as expected.

**Comment by Kaidokuni** [comment] 2020-01-04 14:53
Hi @xmatthias
Oh ok if that's how it's supposed to work I understand but I still find it weird to collect data from different configuration files in the same database, each remaining trade impacts the next configuration and so on... isn't it a problem to analyze this correctly? 

So to have an empty database, I have to use `freqtrade trade -s StrategyName --db-url sqlite://` every time I want to try another configuration? so the `/reload` telegram is useless? :/ 
Maybe adding another /rpc to reset the whole thing can be a good idea, a kind of /reset_config.

> (if you think about it, a real trade will also have to be closed / managed correctly, even if you changed some settings) 

-Yes but when the bot is in dry mode and all trades are simulated I expect to delete all fictitious trades by restarting a new config (or at least be sold (forcesell) when the config changes) and so not impact the next config.

**Comment by xmatthias** [comment] 2020-01-04 15:15
> So to have an empty database, I have to use freqtrade trade -s StrategyName --db-url sqlite:// every time I want to try another configuration

if you don't want to analyze what the bot has done with that configuration, then yes, you can use the in-memory database.
However, i see that as odd usecase - since i assume you're tuning / improving a strategy - so i usually want to look at the previous trades / plot previous trades to see why it bought the stoploss trade, and to see if there is a general way to prevent several of these. all analytical possibilities are taken away by removing the database...

as pointed out above - 

> However - i don't think it was possible to reset the database by using /rpc methods 

I've not tested if it would reset the database ...


> Maybe adding another /rpc to reset the whole thing can be a good idea, a kind of /reset_config.

i don't see the need for that. 
It's just a danger to users to delete the records accidentally.
The usage of `/reload_conf` depends on what you're changing. For many parameters it makes sense to change them without removing previous results. (max_open_trades, whitelist, blacklist, ...).

Think about it another way - you're on the server / machine anyway when you change the configuration since you can't change it via telegram - so you can as well run a `systemctl restart freqtrade` - or `docker restart freqtrade`.

> -Yes but when the bot is in dry mode and all trades are simulated I expect to delete all fictitious trades by restarting a new config (or at least be sold (forcesell) when the config changes) and so not impact the next config.

Well, this depends a lot on what you expect.
For me, i do long-term tests of strategies (once they've proven themselfs short-term), running them sometimes for months at a time without modification - however i do patch my servers, too, so i do need to restart the server every now and then, and expect the bot to continue where it left of - just as it would in real trading, and not restart every time from scratch - removing all results i had previously.

**Comment by hroff-1902** [comment] 2020-01-16 00:40
closing it as the question was answered
feel free to reopen

**Closed by hroff-1902** 2020-01-16 00:40 UTC
Labels: Question
