### ISSUE TITLE
FreqUI visualize result - object is not iterable

### ISSUE THREAD

**Issue by jansmets** [freqtrade/freqtrade#8944] opened 2023-07-23 10:15 UTC
My strategy calls out to a class of an imported library. 
When I use the frequi to 1) 'run backtest' and 2) 'visualize result' then below trace occurs. 

Backtesting using `freqtrade backtesting` work fine. 

  * Operating system: WSL Win10
  * Python Version:  3.10
  * CCXT version: 4.0.17
  * Freqtrade Version: devel

```
2023-07-23 11:46:12,152 - freqtrade.strategy.interface - DEBUG - Populating exit signals for pair BTC/USDT:USDT.
2023-07-23 11:46:12,167 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
    raise exc from None
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    content = await serialize_response(
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/routing.py", line 169, in serialize_response
    return jsonable_encoder(
      File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/encoders.py", line 143, in jsonable_encoder
    return jsonable_encoder(
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/encoders.py", line 195, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/encoders.py", line 209, in jsonable_encoder
    jsonable_encoder(
  File "/home/jasmets/ft/freqtrade/.env/lib/python3.10/site-packages/fastapi/encoders.py", line 238, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'numpy.bool_' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

The dataframe.to_string() looks like this:
```
                        date     open     high      low    close      volume  isEmaUptrend  isEmaDowntrend  isSmaUptrend  isSmaDowntrend  prediction  signal  barsHeld isEar
lySignalFlip isLastSignalBuy isLastSignalSell isNewBuySignal isNewSellSignal  startLongTrade  startShortTrade  endLongTrade  endShortTrade
0  2023-06-01 00:00:00+00:00  27199.0  27343.4  26584.6  26809.5  115697.383          True            True          True            True           0       0         1             False           False            False          False           False           False            False         False          False
```

A second issue is that 'visualize result' page seems to re-run the strategy on the first page load (which would, I believe, only should re-run when the 'refresh' button is pressen). Here it does not provide the additional startup candles. It also seems to somehow re-use the previous instance of the external class I called out to - including all the data it had before - very strange - I'm still trying to figure out that part and will try and file another bug report once I understand the issue.

**Comment by xmatthias** [comment] 2023-07-23 15:32
first off - devel is not a version, but a moving target. please use `freqtrade -V` to get the proper version number.

---

I don't think that the "calling out" is the problem - rather it seems to be a problem with the datatypes in your dataframe.
It's working fine with all strategies i've tested over the years - and your dataframe isn't really special (though a `to_string()` won't really show much if it's using some odd types).

Please provide us with a minimal strategy that's causing this problem - so we can look at it further.
you'll most likely not need to backtest that strategy - a simple call from "Charts" in freqUI should suffice, too.

**Comment by xmatthias** [comment] 2023-07-23 17:33
Tried recreating this - but a regular bool is serialized just fine.

As such - we'll have to have the minimal reproduction strategy / code - otherwise we'll not be able to verify this.

**Comment by jansmets** [comment] 2023-07-23 20:29
exact working version is `freqtrade 2023.7.dev-52ec2324d`

Take the sample_strategy.py, then in  `populate_indicators()` add:
```
        for i in range(len(dataframe.index)):
            dataframe.loc[dataframe.index[i], "signal"] = 1
        
        change = lambda col, i: dataframe[col].iloc[i] != dataframe[col].shift(1, fill_value=dataframe[col].iloc[0]).iloc[i]
        for i in range(len(dataframe.index)):
            # OK 
            # dataframe.loc[dataframe.index[i], "isEarlySignalFlip"] = True
            # NOK
            dataframe.loc[dataframe.index[i], "isEarlySignalFlip"] = change("signal",i)   

```

**Comment by xmatthias** [comment] 2023-07-24 04:55
well the assignment is problematic in several ways. 
It's clearly not efficient - and i'd strongly encourage you to learn how pandas vectorization works - as this way will be very slow to work with - and potentially cause problems in live, too (assuming the calculation you're actually doing is even slightly more complex).

The problem your assignment causes is that the datatype the column has is object, while the content is really bool (not object).
That's most likely caused by the odd assignment through a loop - which means pandas can't rely on all values to have the same type, and therefore defaults to object.

in your case, you can pretty easily fix the type with by explicitly converting it to bool via `dataframe['isEarlySignalFlip'] = dataframe['isEarlySignalFlip'].astype('bool')`.

You can also init the column appropriately first with `dataframe['isEarlySignalFlip'] = False`  - which should also work and tells pandas the datatype beforehand.


I don't currently see a fix for us to do here  as it's simply a type mismatch created by the strategy which can be easily fixed - and every workaround i can currently think of would either have negative consequences for all other strategies, either in performance, or in changed serialization.

If you find a realistic case where the above doesn't work let me know.

**Comment by perkmeister** [comment] 2023-07-24 11:25
This is interesting, I see no data type mismatch there. Inefficient as it is (as you rightly say) I don't quite see why it wouldn't work.

**Comment by xmatthias** [comment] 2023-07-28 16:29
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.

**Closed as completed by xmatthias** 2023-07-28 16:29 UTC
Labels: Question, Strategy assistance
