### ISSUE TITLE
Bittrex problems with fetch_l2_order_book / ccxt==1.36.12

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/freqtrade#3865] opened 2020-10-13 13:38 UTC
2020-10-13 15:36:26,811 - freqtrade.freqtradebot - INFO - Checking depth of market for LTC/USDT ...
2020-10-13 15:36:26,811 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:36:26,811 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 4 times
2020-10-13 15:36:26,812 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:36:26,812 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 3 times
2020-10-13 15:36:26,812 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:36:26,812 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 2 times
2020-10-13 15:36:26,813 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:36:26,813 - freqtrade.exchange.common - WARNING - retrying fetch_l2_order_book() still for 1 times
2020-10-13 15:36:26,813 - freqtrade.exchange.common - WARNING - fetch_l2_order_book() returned exception: "Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25"
2020-10-13 15:36:26,813 - freqtrade.exchange.common - WARNING - Giving up retrying: fetch_l2_order_book()
2020-10-13 15:36:26,813 - freqtrade.freqtradebot - WARNING - Unable to create trade for LTC/USDT: Could not get order book due to BadRequest. Message: bittrex fetchOrderBook() limit argument must be None, 1, 25 or 100, default is 25

**Comment by Pascal66** [comment] 2020-10-13 13:39
Collecting ccxt==1.36.12
  Downloading ccxt-1.36.12-py2.py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 1.4 MB/s

**Comment by xmatthias** [comment] 2020-10-13 14:40
I've renamed the Issue as it has nothing to do with the update of ccxt directly (although it may be caused by updating ccxt).

Please fill out the issue template. it's not there for fun, and sooner or later i'll really start closing issues without further comment if it ain't filled out.

**Comment by Pascal66** [comment] 2020-10-13 14:44
Ok @xmatthias i'll fill the template.
But this is related to many PR, so I not think this was necessary for you.
To understand what happen.
Btw, freqtrade doesnt work anymore

**Comment by xmatthias** [comment] 2020-10-13 14:46
it's not necessary for THIS issue accidentally (as i found the culprit commit) ... (that's why i changed the above comment to "get acustomed to for next time" .... :)

**Comment by xmatthias** [comment] 2020-10-13 18:35
@Pascal66 what's your config look like (especially for ask_strategy and bid_strategy)?

Also - are you doing something "extra" with the orderbook in your strategy?
In the default configuration (also with orderbook enabled) - bittrex works just fine without any problem or error for both  buying and selling.

**Comment by Pascal66** [comment] 2020-10-14 05:49
I do nothing special since some month, the only thing I do is to update freqtrade wich upgraded ccxt
And then downgrade it  when the fix was resolved.

```
    "bid_strategy": {
        "price_side": "bid",
        "ask_last_balance": 0.0,
        "use_order_book": false,
        "order_book_top": 1,
        "check_depth_of_market": {
            "enabled": true,
            "bids_to_ask_delta": 1
        }
    },
    "ask_strategy": {
        "price_side": "ask",
        "use_order_book": false,
        "order_book_min": 1,
        "order_book_max": 1
    },
    "order_types": {
        "buy": "limit",
        "sell": "limit",
        "emergencysell": "market",
        "stoploss": "market",
        "stoploss_on_exchange": false,
        "stoploss_on_exchange_interval": 60
    },
    "exchange": {
        "name": "bittrex",
```

**Comment by xmatthias** [comment] 2020-10-14 18:20
as suspected, it's caused by a change to the bittrex API - which now only supports 1, 25 and 500 as limit arguments to fetch_orderbook - while before it supported any random argument.

#3868 will fix this, so your configuration should work again.

**Closed** 2020-10-14 18:28 UTC
Labels: Bug, CCXT

**Comment by Pascal66** [comment] 2020-10-15 07:45
Seems to work. Waiting for a complete trade.
Thank you
