### ISSUE TITLE
Cache 'on' cause backtesting error

### ISSUE THREAD

**Issue by LeCmnGend** [freqtrade/freqtrade#8145] opened 2023-02-10 03:46 UTC
## Describe your environment

  * Operating system: wsl2 w10
  * Python Version: 3.10
  * CCXT version: 2.7.66
  * Freqtrade Version: 2023.dev2
  
## Your question
first run on new time frame, bot takes 252 trade
after edit strategy (only **dataframe['rsi_3m'] < 75**  to **dataframe['rsi_3m'] < 70**, no other thing change), If i run
```
freqtrade backtesting --userdir=tData -c=tData/config.json -s=tScalp --cache=none --timerange=20220209-20230210
```
then when edit stra, it works (with total **250** trade on)

but if i run with no **--cache = none**:
```
freqtrade backtesting --userdir=tData -c=tData/config.json -s=tScalp  --timerange=20220209-20230210
```
it still show **252** trade
*Ask the question you have not been able to find an answer in the [Documentation](https://www.freqtrade.io/en/latest/)*
What wrong with my command to use cache  function correctly? many thank

**Comment by xmatthias** [comment] 2023-02-10 05:57
If backtesting doesn't have the intended effect, then it's usually a sign of one of  a few mistakes (based on experience of several previous issues of this kind).

* you edited the wrong file (strategy loaded != strategy edited) (you can check the logs for this)
* or forgot to safe the file
* the change you made has no effect.

Running with `--cache none`  will ALWAYS rerun the backtest based on how the strategy is currently stored on disk.

**Comment by LeCmnGend** [comment] 2023-02-10 06:29
can  you give me your telegram then i can send you my config and strategy

**Comment by xmatthias** [comment] 2023-02-10 07:09
I don't see why that should be necessary.
Freqtrade detects changes to both config and strategy (and strategy parameter file). 

cache is only used if neither of the 2 did change - which based on your description, means it's a usage error (not going to repeat reasons here - see comment above for common reasons).

All users using freqtrade will be using the **same** logic with 100ds of different strategies - if cache behavior would be buggy - then this would've been found a long time ago.
The logs also contain a note if cache was used or not - making it clear when cache is used (if you use `--cache none` - you'll never see `result reused from cache` messages).

If you still suspect a bug, then please provide a minimal strategy (I'm not going to dig through 100ds of lines of custom strategy code) that reproduces the issue.  
Otherwise, i'll continue to assume that it's a usage error - which (if you dig deep enough in issues) - is what issues of this kind almost always turn out to be.

**Comment by LeCmnGend** [comment] 2023-02-10 08:04
my old strategy command
```
def global_check(dataframe):
    return ( 
            (    #Mức trung bình
                (dataframe['rsi_3m'] < 75) #Check rsi BTC
```
my new
```
def global_check(dataframe):
    return ( 
            (    #Mức trung bình
                (dataframe['rsi_3m'] < 70) #Check rsi BTC
```

"A lower RSI leading to a lower number of orders (from 252 to 250), if I don't turn off the cache, freqtrade will run very fast (using cache) and produce a result of 252 orders (if cache is turned off, it will run correctly with 250 orders).

**Comment by xmatthias** [comment] 2023-02-10 08:22
Freqtrade will determine if you ran a backtest with the same settings (config, strategy, ...) again and if  possible, reuse a file from cache.
this may be the prior run - or a run from several hours ago (the log will contain the actual run date).

You can change anything in the file (also a comment) - and cache will be disabled automatically.

If that's not the case, then your strategy is not loaded from the file you're changing.
you can find duplicate strategy-classes in your strategy search path with `freqtrade list-strategies`.


As mentioned before - if you suspect there is a bug, please provide full logs as well as a reproduction for this behavior. For me, this is working perfectly fine without explicitly specifying the `--cache` attribute.

**Comment by xmatthias** [comment] 2023-02-10 08:44
Testing this explicitly for you on a new strategy (never backtested on this system):

* First run - no cache.
* 2nd run -> `2023-02-10 08:40:15,942 - freqtrade.data.btanalysis - INFO - Loading backtest result from /data/freq_userdata/backtest_results/backtest-result-2023-02-10_08-40-02.json `
* modify a comment in the strategy file that's listed in the "load" logs (every small change is enough to cause the hash to change)
* 3rd run (now with modified strategy file) -> No cache.
* 4th run (no new change): `2023-02-10 08:43:09,733 - freqtrade.data.btanalysis - INFO - Loading backtest result from /data/freq_userdata/backtest_results/backtest-result-2023-02-10_08-42-09.json` <-- this is a different file than the one used above) - reusing the result from run3.
* Revert the Change done to the comment - save file
* 5th run (original strategy file): `2023-02-10 08:44:03,282 - freqtrade.data.btanalysis - INFO - Loading backtest result from /data/freq_userdata/backtest_results/backtest-result-2023-02-10_08-40-02.json` <-- This is now again the same backtest file we had on the 2nd run.


As such - i can't detect any faulty behavior - therefore the error must be on your side. As mentioned above - it's most likely either a "forgot to safe" - or a "duplicate strategy" problem.

**Comment by LeCmnGend** [comment] 2023-02-16 02:10
Sorry about my late respond: It still run but please take a look at **total trade number**
My sequense:
```
1 run (cache none, stra 1) : 252
2 run (cache, stra 1): 252
3 run (cache, stra 2): 252
4 run (cache none, stra 2): 250
5 run (cache, stra 1): 250
6 run (cache none, stra 1): 252
```
I use git folder to sync progress, so it should not have duplicate file (git will notification about file change),
already delete my default user_data folder for sure,
all of my file in tData folder.

**Comment by xmatthias** [comment] 2023-02-16 05:30
git will not notify you about 2 files with duplicate classes, only about which file was actually changed.

you also seem to run 2 different strategies (stra1, stra2) - - with stra2 starting with cache - so with a result that's who knows how old.

If you expect us to look at this in detail, please provide a **full, reproducible example** (including minimal the strategy (including a 2nd file with the modification) used where this is happening).

I've tried to reproduce it, and cache is working perfectly fine in all cases i tried (not just for this issue, but also while using it in the last few months).
So my best assumption is that it's something in your environment (duplicate strategy names) - or that your strategy is having some kind of "randomness" builtin (most likely accidentally) - which is causing different results whenever it's running.

**Comment by xmatthias** [comment] 2023-03-01 05:29
Closing this as i think your question has been answered.

Feel free to comment below / reopen if it's still unclear.

**Closed as completed by xmatthias** 2023-03-01 05:29 UTC
Labels: Question, Backtest

**Comment by LeCmnGend** [comment] 2023-03-02 07:55
> Closing this as i think your question has been answered.
> 
> Feel free to comment below / reopen if it's still unclear.

still checking on my site sir.
