### ISSUE TITLE
0 Plots Generated / No History Data for pair [plotting issue]

### ISSUE THREAD

**Issue by ChatsChoiceGaming** [freqtrade/freqtrade#2252] opened 2019-09-09 19:10 UTC
## Step 1: Have you search for this issue before posting it?

Yes

## Step 2: Describe your environment

  * Operating system: Ubuntu x64
  * Python Version: Python3
  * CCXT Version: 1.18.1115
  * Branch: Develop
  * Last Commit ID: 74578b87522d2bfc5716c7e68365810a1e3e93f3
  
## Step 3: Describe the problem:

When attempting to plot results of a backtest, `freqtrade --strategy DefaultStrategy plot-dataframe --pairs XVG/BTC`, the terminal attempts to plot then says `WARNING - No history data for pair: "XVG/BTC"`.  I have already tried running `--refresh-pairs-cached` as well as `freqtrade download-data`, but the same error always occurs, and shows `0 plots generated`.

I have also tried exporting the backtest results to `backtest-result.json` and then referencing the file in the plot creation, but the same errors happen: `no history data for pair` and `0 plots generated`.

### Observed Results:

`No History data for pair`
`0 plots generated`

**Comment by hroff-1902** [comment] 2019-09-09 19:13
Please fill the fields:

>   * CCXT version: _____ (`pip freeze | grep ccxt`)
>  * Branch: Master | Develop
>  * Last Commit ID: _____ (`git log --format="%H" -n 1`)

**Comment by xmatthias** [comment] 2019-09-09 19:59
Also, please post the full log of the command you are having problems with.

In this case, also include the log for the backtest you ran, so we can identify eventual problems.

**Comment by hroff-1902** [comment] 2019-09-28 01:08
I'm closing this issue since no requested data that would allow us to identify and localize the problem were provided.

Please free to reopen it.

**Closed by hroff-1902** 2019-09-28 01:08 UTC
Labels: Triage Needed

**Comment by serguzz** [comment] 2023-08-20 20:54
Not sure if it's a bug, but it looks like `image: freqtradeorg/freqtrade:develop_plot` does not recognize data downloaded from an exchange  in `.json` format.

To reproduce:

1. Download data from exchange with stable image: `image: freqtradeorg/freqtrade:stable`. The data will be in `json` format.
2. Switch to develop_plot image: `image: freqtradeorg/freqtrade:develop_plot`
3. Try running backtest on the data you have (`json`)
4. See the warning:
`2023-08-20 20:51:13,294 - freqtrade.data.history.idatahandler - WARNING - No history for SOL/USDT:USDT, futures, 1h found. Use `freqtrade download-data` to download the data`
5. Download new data, it will be in `.feather` format.
6. Successfully run backtesting

**Comment by xmatthias** [comment] 2023-08-21 04:31
@serguzz Please don't revive issues that are more than 4(!) years old.

If you encounter an issue today (with a newer version) - please open a new issue - which will also contain the full version information.
