### ISSUE TITLE
Web UI actions don`t work

### ISSUE THREAD

**Issue by maxkrukov** [freqtrade/freqtrade#8139] opened 2023-02-08 13:15 UTC
When I try to delete or to sell trade nothing happened. Docker image: 2023.1

**Comment by xmatthias** [comment] 2023-02-08 15:19
That's a bit ... sparse information ... 

Is the bot showing up as online when you perform these actions?
does the freqtrade logs show something?

If the logs show nothing, best open the developertools (F12) in your browser and look for failed requests - as well as for  errors in the browser console.

**Comment by maxkrukov** [comment] 2023-02-08 16:46
![image](https://user-images.githubusercontent.com/23353953/217595527-676f0a35-55f7-47f6-8743-144edb6cb03d.png)
I see nothing when I push this button

**Comment by maxkrukov** [comment] 2023-02-08 16:50
![image](https://user-images.githubusercontent.com/23353953/217596853-39b738b0-b129-4883-8731-fbca940307bf.png)
I see no api request regarding deleting

**Comment by xmatthias** [comment] 2023-02-08 19:01
From afar, it looks like you're not confirming on the popup.

When i delete a trade from this part of the UI, i get the "delete" popup - if i confirm that, THEN it'll make the "delete" request.

![Peek 2023-02-08 19-59](https://user-images.githubusercontent.com/5024695/217626439-d3e6c1b4-fcba-4506-a14d-26ff05c08c82.gif)

**Comment by maxkrukov** [comment] 2023-02-08 19:39
I use dockerhub image with kubernetes. I don`t have pop up window 2022.12, 2023.1, develop versions. 

2022.11 and less work fine as you`ve shown.

Os linux, firefox and chrome latest version. 

![image](https://user-images.githubusercontent.com/23353953/217635341-56131ef2-8a2f-4d1d-8aa0-7f5af2287ca5.png)

**Comment by xmatthias** [comment] 2023-02-08 19:50
Well that's the problem - no popup -> no fun
best attempt to do a full reload (ctrl+f5).

Also, you might wanna look at the console (similar section than the network tab - but different information).

**Comment by maxkrukov** [comment] 2023-02-08 20:30
I reloaded page with F5, wiped out browser(firefox and chrome) cache and no pup-up after pushing action. Console without errors too. Rolled back to 2022.11 version and it works fine. 

Maybe someone approved the same issue later. Thank you=)

**Comment by xmatthias** [comment] 2023-02-09 05:22
Please note that freqtrade does NOT support database downgrades - running a database that was touched by a later version of freqtrade can lead to unexpected errors when running that database in older versions.

You can in theory manually roll back the database through the _bak tables - but that's not something freqtrade will do automatically.

---

The gif above was made with the version from the current stable image (UI version 0.6.5) - and it's working as expected for me in chromium and firefox.

As such - i suspect this is something to do with your client settings / setup.
without the information requested above (console log from the browser) - there will be little / nothing we can do for you.

**Comment by VanessaE** [comment] 2023-02-15 10:00
This happens for me, and at least one other person, as well.  No related messages in the browser F12/dev tools sidebar, nor in freqtrade's log/console output, let alone any errors.

The four-button popup always shows up when summoned by an "actions" button, and it always disappears when a "force exit..." or "delete..." button therein is clicked, but the final confirmation dialog that should pop-up after clicking one of those buttons, only appears sometimes, not always .  When this glitch rears its head, it takes around 3 tries on average to get the confirmation dialog to show up.

It started for me some time before 0.6.5, and I'm 100% certain it was working fine before the vue3 update.

I have only used these buttons in the "Trade" page, but not in the "Dashboard" page.

Using Google Chrome on Linux.

**Comment by xmatthias** [comment] 2023-02-15 19:02
I've just tried to reproduce this for 20 minutes straight (on different browsers), with the popup opening every single time.

If you're encountering this - i'll either need reliable (!) reproduction steps - or a pr submitting a fix for this.

**Comment by xmatthias** [comment] 2023-02-23 19:29
Should be fixed in UI version 0.6.7. let me know if you still see this happening with that version.

**Closed as completed by xmatthias** 2023-02-23 19:29 UTC
Labels: freqUI
