### ISSUE TITLE
adjust_trade_position() and max_stake when no trades happen between its calls

### ISSUE THREAD

**Issue by epigramx** [freqtrade/freqtrade#8998] opened 2023-08-01 11:12 UTC
Does it update the balance each time it is called? I suspect not because there was new stake added on the exchange, and at a later date the function caused an erroneous `WARNING - Minimum stake amount > available balance` (by "erroneous" I mean with erroneous available balance printed since I checked on the exchange and there was stake there added between the initial trade and the `adjust_trade_position()`'s attempt to add to the trade) .

Question? Bug? You decide.

## Describe your environment

  * Operating system: Ubuntu 22.04.2 LTS
  * Python Version: Python 3.10.12
  * CCXT version: 4.0.29
  * Freqtrade Version: 9c39fd6e926aa875d9bc82102242ecdbe5cf1d00

**Comment by xmatthias** [comment] 2023-08-01 11:50
Balance/wallets is updated whenever "action" happens (an order is placed or filled or cancelled), or at least once per hour.

As such, it's expected for added stake to take at maximum an hour to be visible (assuming no trade/order activity happens in between).

If timing for what you've seen doesn't align (you deposited way earlier, outside of the 1h window) - then we'll need the logs (including the time when the deposit was made) to have a look at it in more detail.

**Comment by epigramx** [comment] 2023-08-01 12:30
> Balance/wallets is updated whenever "action" happens (an order is placed or filled or cancelled), or at least once per hour.
> 
> As such, it's expected for added stake to take at maximum an hour to be visible (assuming no trade/order activity happens in between).
> 
> If timing for what you've seen doesn't align (you deposited way earlier, outside of the 1h window) - then we'll need the logs (including the time when the deposit was made) to have a look at it in more detail.

It happened many days after the deposit. The logs are practically empty because they report nothing other than the ping and at the point `adjust_trade_position()` returns a positive they have` freqtrade.wallets - WARNING - Minimum stake amount > available balance. xxx > xxx` and the available balance there is clearly wrong compared to the exchange (I also manually print the `max_stake` in there with `logger.info()` and it's the same as the 'available balance' of the default warning).

Where exactly in the code does it trigger the 1h update to run it for a while on a debugger to see if it breaks to it?

**Comment by xmatthias** [comment] 2023-08-01 14:05
Did the balance update in the meantime? (if you check in the UI / telegram)? 

Balance updates can also be ignored when `available_capital ` is configured - which would limit the bot to "whatever" is configured there, even if more than that is available.

**Comment by perkmeister** [comment] 2023-08-01 14:41
How about calling `self.wallets.update()` just prior to calculating the stake?

**Comment by epigramx** [comment] 2023-08-01 18:11
> `self.wallets.update()`

ok if that's the one that should be doing it, I see it called on init and entry and exit and cancel-all and `_safe_exit_amount()` (which appears to be part of the default exit (???)) and status update (???) and `apply_fee_conditional()` which is unclear because that branches a lot.

where is the update every 1h thing?

**Comment by xmatthias** [comment] 2023-08-01 18:15
> How about calling `self.wallets.update()` just prior to calculating the stake?

well for now, i'm considering this as question.
A bug report would have
* a proper version number
* logs that show what happened - as well as eventually additional info (in this case, an exact date as to when the deposit happened, and what the config around stake looks like

I'll not start adding random lines just because "this might fix it" without understanding (or being able to replicate) the actual cause or problem.

**Comment by epigramx** [comment] 2023-08-01 18:17
I posted it as a question myself. Where is the update every 1h thing so I can see if the code breaks there? The logs say practically nothing because as I said it's just pings and the warning I posted.

**Comment by xmatthias** [comment] 2023-08-01 18:21
> I posted it as a question myself.

wasn't really directed to you - sorry if it came round that way.

---

the "Minimum" update of 1h comes from the RPC module - so users can't "spam" the exchange by repeatedly calling `/balance` (`update()` called with `require_update=False`).

Freqtrade itself calls wallets.update() whenever trade activity happens (as mentioned above).
It's obviously possible that there's places where it's missing - but i certainly haven't observed that so far - and i doubt you're the first to actually deposit more funds (though i prefer bots that make money on their own :laughing: )

**Comment by epigramx** [comment] 2023-08-01 18:27
> > I posted it as a question myself.
> 
> wasn't really directed to you - sorry if it came round that way.
> 
> the "Minimum" update of 1h comes from the RPC module - so users can't "spam" the exchange by repeatedly calling `/balance` (`update()` called with `require_update=False`).
> 
> Freqtrade itself calls wallets.update() whenever trade activity happens (as mentioned above). It's obviously possible that there's places where it's missing - but i certainly haven't observed that so far - and i doubt you're the first to actually deposit more funds (though i prefer bots that make money on their own 😆 )

is that rpc module enabled if there is no web and telegram? it has all those things disabled.

I've put a break on the first code line of `update()` to see if it's ever hit (after init).

**Comment by xmatthias** [comment] 2023-08-01 18:38
> is that rpc module enabled if there is no web and telegram? it has all those things disabled.

it depends on a call to `/balance` (api or telegram). 
even with the modules enabled, if you're not calling it, it's irrelevant.

**Comment by epigramx** [comment] 2023-08-01 18:44
> > is that rpc module enabled if there is no web and telegram? it has all those things disabled.
> 
> it depends on a call to `/balance` (api or telegram). even with the modules enabled, if you're not calling it, it's irrelevant.

so does it mean it doesn't actually update the balance every 1h? if yes it should do something about it one way or another, because obviously `adjust_trade_position()` is dysfunctional if it doesn't have the correct balance.

**Comment by xmatthias** [comment] 2023-08-01 18:52
> because obviously adjust_trade_position() is dysfunctional if it doesn't have the correct balance.

Now the above applies.
This issue is a question so far - containing a tale of what _possibly happened_, not anything that can be analyzed or actioned about. I'll not go chasing down ghosts without actual, proper information.

To actually look at this - i will need actual logs - including the timing of deposit, and the config related to stake - best the full config without the sensitive info.
This could just as well be a misunderstanding due to usable stake constraints.

**Comment by epigramx** [comment] 2023-08-01 19:08
> > because obviously adjust_trade_position() is dysfunctional if it doesn't have the correct balance.
> 
> Now the above applies. This issue is a question so far - containing a tale of what _possibly happened_, not anything that can be analyzed or actioned about. I'll not go chasing down ghosts without actual, proper information.
> 
> To actually look at this - i will need actual logs - including the timing of deposit, and the config related to stake - best the full config without the sensitive info. This could just as well be a misunderstanding due to usable stake constraints.

well it's not a possibility, if you know the code doesn't update the balance if there are no new trades or exited trades or manual calls to balance.

I don't have more data to give but I've put a dry-run to break at the first code line of `update()` and it doesn't seem to hit it after init.

**Comment by perkmeister** [comment] 2023-08-01 19:35
> wasn't really directed to you - sorry if it came round that way.

Well my comment was aimed at the OP, at no point did I ever suggest there was anything wrong with the code or that you should add 'random lines' to fix it. It was posed as a suggestion to see if adding a call to `self.wallets.update()` in `custom_stake_amount()` or `adjust_trade_position()` in the strategy just prior to calculating the stake might resolve the issue of miscalculating the available stake, it would be entirely up to you to decide if there is or isn't an issue with the code and if or how it's fixed.

**Comment by epigramx** [comment] 2023-08-01 20:40
> > wasn't really directed to you - sorry if it came round that way.
> 
> Well my comment was aimed at the OP, at no point did I ever suggest there was anything wrong with the code or that you should add 'random lines' to fix it. It was posed as a suggestion to see if adding a call to `self.wallets.update()` in `custom_stake_amount()` or `adjust_trade_position()` in the strategy just prior to calculating the stake might resolve the issue of miscalculating the available stake, it would be entirely up to you to decide if there is or isn't an issue with the code and if or how it's fixed.

I doubt it can be called in `IStrategy` at all, because `max_stake` is an input of `adjust_trade_position()` passed to it, but correct me if I'm wrong [well maybe if it's called beforehand on previous calls to that function but that's a hacky workaround].

**Comment by perkmeister** [comment] 2023-08-01 21:32
> I doubt it can be called in `IStrategy` at all, because `max_stake` is an input of `adjust_trade_position()` passed to it, but correct me if I'm wrong [well maybe if it's called beforehand on previous calls to that function but that's a hacky workaround].

I'm only guessing here, but `max_stake` is only an input to that function. You can do things like call `self.wallets.get_available_stake_amount()` yourself, and that I think ultimately calls wallet functions like `get_free()` which you've already updated. I may be wrong of course, but strategies do call that function.

**Comment by epigramx** [comment] 2023-08-02 17:09
> 

the only mention of `adjust_trade_position()` in `freqtradebot.py`, is already calling functions like `get_available_stake_amount()` before calling it, so I suspect those functions don't trigger a balance update from the exchange.

**Comment by epigramx** [comment] 2023-08-02 17:09
> > I doubt it can be called in `IStrategy` at all, because `max_stake` is an input of `adjust_trade_position()` passed to it, but correct me if I'm wrong [well maybe if it's called beforehand on previous calls to that function but that's a hacky workaround].
> 
> I'm only guessing here, but `max_stake` is only an input to that function. You can do things like call `self.wallets.get_available_stake_amount()` yourself, and that I think ultimately calls wallet functions like `get_free()` which you've already updated. I may be wrong of course, but strategies do call that function.

the only mention of `adjust_trade_position()` in `freqtradebot.py`, is already calling functions like `get_available_stake_amount()` before calling it, so I suspect those functions don't trigger a balance update from the exchange.

**Comment by perkmeister** [comment] 2023-08-02 17:53
I see what you're saying.

**Comment by perkmeister** [comment] 2023-08-03 00:33
Edit: Well, it would appear stake is validated once the trade is attempted to be executed later, so it looks (to me) like `get_available_stake_amount()` and other stuff being called before `adjust_trade_position()` is just to provide parameters to the function, and they're called again during trade execution when the stake is validated. So maybe calling `self.wallets.update()` just prior to calculating the stake to return would actually work (?).

**Comment by epigramx** [comment] 2023-08-03 06:51
If that is true, and if the current code mainly tries to save resources, the function shouldn't have `max_stake` etc. at all and the docs should instruct the user to use `Wallets` functions directly on their own or if backwards compatibility is needed then the docs should cover it at least.

**Comment by epigramx** [comment] 2023-08-05 22:29
> So maybe calling `self.wallets.update()` just prior to calculating the stake to return would actually work (?)

this appears problematic btw in practice, because unlike the `Wallets` class: the `Exchange` class appears to not be exposed to `IStrategy` and functions of `Exchange` appear to be required to end up to the inputs of `adjust_trade_position()`.

we end up basically requiring users to either restart the software in that case or replicate a large part of the exchange code in their strategy or have a new subsystem that does it automatically.

--

PS Well unless you are content with the hacky workaround of just having an `update()` once in a while but that can be very broken in practice on long timeframes.

**Comment by perkmeister** [comment] 2023-08-05 23:07
Why would the `Exchange` class need to be exposed to the strategy? It's used in the `Wallets` class to access the exchange, and the strategy can call `self.wallets.x()` functions. Also those are just inputs to `adjust_trade_position()` as parameters, there's no reason any of those need to be used to return a stake (as far as I can see). 

So `check_and_call_adjust_trade_position()` calls `adjust_trade_position()`, which returns a stake, and that stake is used in `self.execute_entry()` which then validates the stake by reading the wallet. If you update the wallet before returning the stake that should result in correct validation. At least that's how I read the code.

Have you tried it?

**Comment by epigramx** [comment] 2023-08-05 23:29
> Why would the `Exchange` class need to be exposed to the strategy? It's used in the `Wallets` class to access the exchange, and the strategy can call `self.wallets.x()` functions.

because before calling `adjust_trade_position()` in there, it uses `Exchange` functions to get variables needed as inputs to `adjust_trade_position()`, and those functions are not exposed in `Wallets` the strategy has access to.

**Comment by epigramx** [comment] 2023-08-06 12:07
@xmatthias I figured out that the logs print `freqtrade.wallets - INFO - Wallets synced.` whenever a `Wallets.update()` is run "manually" by a strategy (and that message is never found in the logs when I had the initial problem), and that appears to update the real balance of the exchange correctly at that point exactly (I checked by printing `max_stake` and finding it correct at the _next_ candle).

I personally currently have my workaround (I just run an `update()` in the strategy (if I don't just re-run the software entirely)) but this thread of posts can serve as food for thought I guess.

**Comment by xmatthias** [comment] 2023-08-06 12:56
I don't see why this should be a problem for now, at least not based on what's been posted here.
The bot requests a wallets update "when necessary" as far as i can tell.

It will NOT issue this request at random points in time - and it shouldn't - as it's really irrelevant what the balance is unless there's some activity (like order placement) going on.

I've asked a few questions above - i don't see these answered.
I don't need "food for thought" - i need conclusive information - which so far wasn't provided.

If you think this is an issue that needs fixing, please provide the information i requested above.

To reiterate:
* What actually happened 
* The version you're using (develop from a few weeks ago is NOT a valid version number)
* the configuration you've used (the bot having "no balance" is very likely caused by configuration).


if you're unable / unwilling to provide this - then it's apparently NOT an issue you'd like me to look at, which means i can close this issue - as it's not an issue with freqtrade, but with your strategy.

**Comment by epigramx** [comment] 2023-08-06 13:58
@xmatthias I don't think there's more clarity needed. It's only a question of "should the software support the use case of **adding stake to the exchange** between calls to `adjust_trade_position()` when no other trades happen between the calls to it?".

Don't we already know that it doesn't update the balance automatically in that use case?

**Comment by epigramx** [comment] 2023-08-06 14:03
the version is 9c39fd6e926aa875d9bc82102242ecdbe5cf1d00 btw

**Comment by xmatthias** [comment] 2023-08-06 14:09
> I don't think there's more clarity needed. 

I've quite clearly stated WHAT information is needed to look at this.

I don't think you should need more information on what to provide (i've asked for the same 2 times now).

---

That is a supported usecase, and is one that is working in my tests, too.

I've seen no proof of the countrary - this issue is not showing anything other than an initial, partial log line of "WARNING - Minimum stake amount > available balance" (which can be caused by many things, including wrong configuration).
It's not even clear if it's really happening after a call to `adjust_trade_position` - or from some other path. 

You focus on ".update()" calls in subsequent comments - but that's really not relevant to investigate the root cause.

it MAY be the fix to call `.update()` "someplace"  - but i think i've been quite clear above that i'll not be adding random calls unless i'm able to investigate the cause / replicate the issue - for which the circumstances are currently not given.


You seem keen on providing as little information as possible - but please understand that this makes looking at his issue impossible.
I've requested information above (including logs and partial confiuration) - unless that's provided, i see no reason to discuss this topic further, as then it's clear that you're unwilling to provide the information necessary to replicate your issue.

**Comment by epigramx** [comment] 2023-08-06 14:12
@xmatthias forgive me if I'm wrong, but you didn't provide clarity on where exactly it's supposed to update the `Wallets` in the case of not entering and exiting trades and it just goes through `adjust_trade_position`. 

I mean it's pretty clear that the log does not print `freqtrade.wallets - INFO - Wallets synced` (and the main reason "I don't provide logs" is that they simply don't exist (it's just pings of the date on their own)).

**Comment by xmatthias** [comment] 2023-08-06 14:13
Logs is not the only information requested - but you DID provide one log line - there'll be more around that line - which has also not been provided.

You've now ignored my requests 3 times - seems like there is no problem, and you're simply trying to troll.

I'm happy to reopen this in case you are willing to provide the info - but for now, it seems like you're unwilling to - so there's little point in this issue, and my conclusion is - there's not enough information to look at this.

**Closed as completed by xmatthias** 2023-08-06 14:13 UTC
Labels: Question

**Comment by epigramx** [comment] 2023-08-06 14:16
>you're simply trying to troll.

You are being aggressive for little reason. Meet people half way at least and help with understanding the code,

where exactly is a `Wallets`/balance update supposed to happen if there is no new trade or a trade exit?

**Comment by perkmeister** [comment] 2023-08-06 14:20
Well, the following statement is a logical one regardless of what the code does:

IF the exchange balance changes, and IF the wallets are not synced because it's deemed not 'necessary' to do so, THEN max_stake sent to `adjust_trade_position()` could be out of date and `get_available_stake_amount()` could, if called, return the wrong value and that could lead to incorrect stake amounts being requested and a failure in validation.

Obviously it's not a good idea to spam the exchange with balance requests one every bot loop, so continually syncing the wallet in say `check_and_call_adjust_trade_position()` is not a solution (IF the above logical condition exists).

My suggestion (FWIW) would be provide a function in `Wallets` callable by the strategy that returns `max_stake` and `min_stake`. The strategy has all the information needed after calling `self.wallets.update()` to set the correctly bounded stake. That would only happen when a trade is about to be entered (i.e. not returning `None`) which will keep the exchange balance requests to a minimum. It's also a backwards compatible solution with no effect on others.

**Comment by xmatthias** [comment] 2023-08-06 14:20
I'm sorry if you feel offended - but this issue is just wasting time for no reason.

How often exactly am i supposed accept ignoring requests for information until it's considered trolling?

---


There's no reason to update balance when there's no activity.
If you have a bot that doesn't trade - why should it be aware of the balance on exchange?

It'll update if you request it (via RPC) - or if the bot is doing activity (like creating an order).

I've mentioned that in https://github.com/freqtrade/freqtrade/issues/8998#issuecomment-1660856274 already.

---

> IF the exchange balance changes, and IF the wallets are not synced because it's deemed not 'necessary' to do so, THEN max_stake sent to adjust_trade_position() could be out of date and get_available_stake_amount() would, if called, return the wrong value and that could lead to incorrect stake amounts being requested and a failure in validation.


This is an _assumption_ - but this issue contains **no** information or proof that that's actually happening, except for a partial log-line (logs without context are worth nothing, sorry).

**Comment by perkmeister** [comment] 2023-08-06 14:23
No Matthias, it's a logical statement.

**Comment by epigramx** [comment] 2023-08-06 14:27
> There's no reason to update balance when there's no activity.

That's why I'm saying all this time that we have a misunderstanding and we have already answered what is needed. The software simply does not support **a user going manually to the exchange and adding stake** between calls to `adjust_trade_position()` (that have no other trading activity between them).

So it was only a question of "should that kind of thing be supported in case the user wants to add stake that is only handled by `adjust_trade_position()`?; **I'm not saying it should happen that way**; just that it's a potential thing for someone to think that is needed (I'd personally use it but I don't mind either way).

--

PS by way and to see it in practice, calls to that `update()` are pretty slow (almost 1 second!),  so even if someone adds a polling for that it definitely can't be spammed.

**Comment by xmatthias** [comment] 2023-08-06 14:34
The pure fact that you could get `WARNING - Minimum stake amount > available balance` from `adjust_trade_position()` means that your strategy ignores min_stake / max_stake.


The [documentation](https://www.freqtrade.io/en/latest/strategy-callbacks/#adjust-trade-position) is quite clear - that the value should be between these 2:

> The strategy is expected to return a stake_amount (in stake currency) between min_stake and max_stake if and when an additional buy order should be made (position is increased). If there are not enough funds in the wallet (the return value is above max_stake) then the signal will be ignored.

---

As i've mentioned above (multiple times) - `available_balance` can be limited by (multiple) settings in the configuration.

you seem focused in on "balance was wrong" - but that's an assumption i see little to no proof for - hence i asked for
* configuration sections
* logs


did you verify what balance the bot "knew about"? 

---

On my bots - balance updates roughly once per hour - which i think is more than sufficient.
I'm aware that that's from RPC - but normally people will check "did my bot see the balance" - which will auto-update the balance at least once per hour.

**Comment by epigramx** [comment] 2023-08-06 14:47
@xmatthias yes it was clear what happened. Here is the course of events: 1) the bot sees initially X amount of stake 2) It uses 99% of that amount of stake on a new entry of a new trade 3) The user adds Y extra amount on the exchange manually and then `adjust_trade_position()` fails to see any extra stake (it still saw what it had after the initial trade (which was practically no stake left)) when it had a signal to add stake because there was never an update of balance because no other trade happened after the initial.

It's still unclear to me what other thing could have updated the balance: since a) there was never a manual call to /balance b) in fact telegram and web were turned off for that bot entirely c) no other trade happened and the log never printed `Wallets synced`.

**Comment by perkmeister** [comment] 2023-08-06 15:00
In other words, you could miss trading opportunities for up to an hour, and by the time the wallet is synced those opportunities may have gone away. Not a particularly nice scenario IMO (if that's what is really happening).

**Comment by xmatthias** [comment] 2023-08-06 15:02
It may've been **clear to you** - but it took you 5 days to actually explain this in an understandable way, without combining info from 6 different messages.

---

I think having no way to control the bot (all RPC methods disabled) is pretty much an edge-case - as that'll also effectively mean you'll not really know how the bot is doing.

I still think other things can cause the same behavior (like a limit to `available_balance`) - and effectively the message also means that your strategy will need updating.

there can be other reasons to be outside of the `min_stake`/ `max_stake` range - and the docs are pretty clear that all values outside of that range will be ignored (which IS correct and expected behavior).

---

> In other words, you could miss trading opportunities for up to an hour, and by the time the wallet is synced those opportunities may have gone away

Yes that's correct - but i don't see it as a problem, really.
I'll be adding an explicit call for this - which ensures refreshes happen once an hour even with RPC disabled.

it'll ONLY affect trade adjustments - and even then you can pretty much work around it by reloading the config - which will force a balance update right away.

**Comment by epigramx** [comment] 2023-08-06 15:07
@xmatthias it was a secondary bot of a special use case, but I can see it affecting a "real" strategy e.g. if they use `adjust_trade_position` a lot and no other trades happen between its calls.

@perkmeister apparently in my case not even every 1 hour there was an update because I had RPC turned off as I understand it from what I read from xmatthias.

**Comment by xmatthias** [comment] 2023-08-06 15:12
See linked commits - one adding an explanation, the other adding a call once per hour to wallets (when necessary - so if there's actually a trade eligible for trade adjustments).

**Comment by epigramx** [comment] 2023-08-06 15:14
yep thanks, the rate limit seems smart, because I was measuring it yesterday and it's about 0.7 seconds to do one update (!).

**Comment by xmatthias** [comment] 2023-08-06 16:18
it's not so much the duration than the actual frequency that's the problem why it needs rate-limiting.

it's a call that's made every iteration - we don't WANT to refresh wallets every 5 seconds - that's just not reasonable - a "depost" event on a running bot (that's running out of money, AND will be adjusting stake on an open trade without doing other trades) is a very rare condition.

**Comment by epigramx** [comment] 2023-08-06 17:42
yep, realistically it would be an once in days event, if they don't just reload.
