### ISSUE TITLE
Freqtrade does not find stoploss order in binance - telegram message mismatch

### ISSUE THREAD

**Issue by ziegi** [freqtrade/freqtrade#3640] opened 2020-07-28 08:22 UTC
Maybe this is related to my previous bug report #3639

## Describe your environment

  * Operating system: Ubuntu 16.04.6 LTS
  * Python Version:  3.6.11
  * CCXT version: 1.30.48
  * Freqtrade Version: 2020.6
  
## Describe the problem:

This is happening on binance.
After buying and setting an initial stoploss on exchange updating this stoploss fails
as the order could not be found
But the telegram shows its updated value
the bot does not trade any more

### Observed Results:

  * What happened?
Stoploss did not get updated, but telegramm shows the stoploss to be updated.
Sell is not working until i cancel the stoploss on exchange manually
  * What did you expect to happen?
1. The stoploss should be updated on the exchange
2. Selling should work -> I thought that emergency sell will kick on this 
3. telegram should show correct stoploss

### Relevant code exceptions or logs
  * On exchange:
  ```
Date | Pair | Type | Side | Average | Price | Executed | Amount | Total | Trigger Conditions | Status |  
2020-07-28 10:02:49 | TOMO/BTC | Stop-Limit | Sell | 0 | 0.00007652 | 0 | 13 | 0.00000000 BTC | <= 0.00007729 | Canceled |  <- this one was cancelled manually by me
2020-07-28 04:13:24 | TOMO/BTC | Stop-Limit | Sell | 0 | 0.00007724 | 0 | 13 | 0.00000000 BTC | <= 0.00007802 | Canceled |  
2020-07-28 04:06:24 | TOMO/BTC | Stop-Limit | Sell | 0 | 0.00007664 | 0 | 13 | 0.00000000 BTC | <= 0.00007742 | Canceled |  
2020-07-28 04:05:20 | TOMO/BTC | Stop-Limit | Sell | 0 | 0.00007652 | 0 | 13 | 0.00000000 BTC | <= 0.00007729 | Canceled |  
2020-07-28 04:05:16 | TOMO/BTC | Limit | Buy | 0.00008030 | 0.00008030 | 13 | 13 | 0.00104383 BTC | _ | Filled |  
  ```

  * Telegram shows:
  ```
Trade ID: 3 (since 5 hours ago)
Current Pair: TOMO/BTC
Amount: 13.0 (0.00104383 BTC)
Open Rate: 0.00008030
Current Rate: 0.00008660
Current Profit: 7.69%
Initial Stoploss: 0.00007729 (-3.75%)
Stoploss: 0.00008893 (-0.30%)
  ```
  * Freqtrade logs:
  ```
2020-07-27 22:05:14,751 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 0.0011 ...
2020-07-27 22:05:14,751 - freqtrade.freqtradebot - INFO - Executing Buy for TOMO/BTC
2020-07-27 22:05:14,751 - freqtrade.freqtradebot - INFO - Getting price from order book Ask side.
2020-07-27 22:05:15,715 - freqtrade.freqtradebot - INFO - ...top 1 order book buy rate 0.00008030
2020-07-27 22:05:16,483 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=None, pair=TOMO/BTC, amount=13.00000000, open_rate=0.00008030, open_since=closed)
2020-07-27 22:05:18,278 - freqtrade.persistence - INFO - Updating trade (id=None) ...
2020-07-27 22:05:18,278 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=None, pair=TOMO/BTC, amount=13.00000000, open_rate=0.00008030, open_since=closed).
2020-07-27 22:05:18,796 - freqtrade.wallets - INFO - Wallets synced.

....

2020-07-27 22:06:23,240 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{45223565}) in order to add another one ...
2020-07-27 22:06:24,235 - freqtrade.exchange.binance - INFO - stoploss limit order added for TOMO/BTC. stop price: 7.742e-05. limit: 7.664e-05

....

2020-07-27 22:13:22,988 - freqtrade.freqtradebot - INFO - Trailing stoploss: cancelling current stoploss on exchange (id:{45223876}) in order to add another one ...
2020-07-27 22:13:24,490 - freqtrade.exchange.binance - INFO - stoploss limit order added for TOMO/BTC. stop price: 7.802e-05. limit: 7.724e-05
2020-07-27 22:13:28,491 - freqtrade.freqtradebot - WARNING - Unable to fetch stoploss order: Tried to get an invalid order (id: 45225914). Message: binance {"code":-2013,"msg":"Order does not exist."}
2020-07-27 22:13:28,999 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ziegi/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=rate, params=params)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1258, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1989, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 593, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1970, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ziegi/freqtrade/freqtrade/freqtradebot.py", line 749, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/home/ziegi/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market TOMO/BTC.Tried to sell amount 13.0 at rate 7.652e-05. Message: binance Account has insufficient balance for requested action.
2020-07-27 22:13:32,724 - freqtrade.exchange.exchange - INFO - Downloaded data for IRIS/BTC with length 8.
2020-07-27 22:13:32,996 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 581, in fetch
    response.raise_for_status()
  File "/home/ziegi/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

... this goes on forever
  ```

**Comment by xmatthias** [comment] 2020-07-28 13:36
well - the problem is that freqtrade does not find the order on the exchange anymore.
What should it display in your opinion?

also keep in mind that the bug you've experienced is fixed in the latest develop branch.

**Comment by ziegi** [comment] 2020-07-28 18:26
freqtrade does internally still increase the trailing stoploss
and shows this in the telegram message

last successful stoploss: 0.00007652
and telegram showing: 0.00008893

So i would expect that freqtrade shows me the last successful stoploss 0.00007652
so i could see from the difference from actual value to stoploss that something is not working
or even better a message that the stoploss order failed

**Comment by xmatthias** [comment] 2020-07-29 04:57
well the fix is available already by switching to the develop branch.

If you're not comfortable with that - we're releasing a new version soon...

**Comment by ziegi** [comment] 2020-07-29 06:24
Thank you
I have been running the develop branch the last 8 hours.
I hit the Error on updating the stoploss twice and your fix did work, 
the bot did run on, one time the stoploss on exchange did trigger, 
the other time the bot did sell.

**Closed** 2020-07-29 11:17 UTC
Labels: Question
