### ISSUE TITLE
hyperopt problem

### ISSUE THREAD

**Issue by M4DF135H** [freqtrade/freqtrade#1465] opened 2019-01-04 19:55 UTC
## Step 1: did you look for this issue before publishing?

If you find a bug in the bot, please [search in our tracker] (https://github.com/freetrade/freetrade/issues?q=is%3Aissue). 
If this is not reported, create a new problem.

## Step 2: describe your environment

  * Python Version: Python 3.7.2
  * Version CCXT: 
aiodns= = 1.1.1
aiohttp==3.5.1
arrows==0.12.1
asn1crypto==0.24.0
asynchronous-timeout= = 3.0.1
attrs==18.2.0
cachetools==3.0.0
ccxt= = 1.18.95
serti= = 2018.11.29
in Korean==1.11.5
chardet==3.0.4
coinmarketcap==5.0.3
cryptography= = 2.4.2
- e git+https://github.com/freqtrade/freqtrade.git@24e1de91eb403bf6a5738307db071e64426fecee#egg=freqtrade
future==0.17.1
idna= = 2.8
joblib==0.13.0
jsonschema= = 2.6.0
multidict==4.5.2
numpy libraries= = 1.15.4
Panda= = 0.23.4
ru-find-1 th= = 1.1.3
pycares= = 2.4.0
pycparser==2.19
in Python-dateutil==2.7.5
python-telegram-bot==11.1.0
pytz= = 2018.7
requests= = 2.21.0
requests-cache==0.4.13
package scikit-learn==0.20.2
scikit-optimize==0.5.2
scipy= = 1.2.0
six= = 1.12.0
With SQLAlchemy= = 1.2.15
Ta-Lib==0.4.17
tabulate==0.8.2
ujson= = 1.35
urllib3= = 1.24.1
wrapt==1.10.11
Earl= = 1.1.0

  * Branch: Master
  * The ID of the last commit: 24e1de91eb403bf6a5738307db071e64426fecee
  
## Step 3: describe the problem:

* Explain the problems you face*

### Steps to play:

  1. connect your strategy and your hyperopt
  2. trying to run a selection of parameters Python3. / freqtrade/main.py --customhyperopt BB -c config.JSON hyperopt -e 1000
  3. get error https://imgur.com/a/cteXF66
  4. added option strategies Python3. / freqtrade/main.py --strategy BB --customhyperopt BB -c config.json hyperopt -e 1000
  5. get error https://imgur.com/a/N0gxIg6
  
### observed results:

  * What happened?
     Nothing worked.
  * What did you expect?
    Cool strategy

**Comment by xmatthias** [comment] 2019-01-06 09:39
step 1 can be solved temporarily by adding the following parameters to your hyperopts `populate_indicators`:
rsi, fastd, adx, minus_di (eventually empty ...)
These are used in the sell-signal of the defaultStrategy and are therefore (currently) required.

for step 4 - the documentation is wrong - --strategy is not supported anymore.
The problem is the parallelization, which uses pickle and to "unpickle" - the strategy / class needs to be available.

I'll work on a fix for this (but it'll probably be more like copy/pasting the `populate_sell` to the hyperopt configuration) ... we'll see

**Comment by xmatthias** [comment] 2019-01-09 14:17
Hi @M4DF135H , 
with #1475 merged, the problems you faced should have disappeared. 

Please note that the process also slightly changed, so best go over the documentation to verify that buy/sell functions are in the hyperopt-file as well.

I'll close this for now - feel free to reopen if the problem isn't solved.

**Closed by xmatthias** 2019-01-09 14:17 UTC
Labels: bug, hyperopt
