### ISSUE TITLE
FIP - Add Buy & Hold metric

### ISSUE THREAD

**Issue by Corfucinas** [freqtrade/freqtrade#3518] opened 2020-06-24 06:34 UTC
It would be of great improvement to add this metric as an RPC option and include it on the backtesting report, that way once can always compare against market fluctuations and not an un-optimized vs optimized strategy when it comes to Hyperopt (sometimes the way to beat the market is not by having a profit, but by incurring in significant lesser losses. 

What do you think?

**Comment by xmatthias** [comment] 2020-06-24 07:02
have you got any resources on this (how to calculate it, where to get it from ...) ? 

Also - you're talking about RPC on one side - but about backtesting on the other.
RPC methods do not apply for backtesting .... so to me, this whole request doesn't make a whole lot of sense.

**Comment by Corfucinas** [comment] 2020-06-24 07:24
Hi @xmatthias 

To clarify:
1) When I meant RPC, I was refering to having the option available on Telegram, either included under "profit"  or "balance", this way we can know the performance against this benchmark. 
2) This idea can also be extended to be incorporated into the backtest (ie, profit vs Buy & Hold

In regards of how to calculate it, in theory we would need to know what would be the first incoming data points vs the "last" data point, this might as well be the asset price over the passage of time calculated by the period on the `config.json` file. 

This calculation can be done by **simulating** a single trade at the start of the bot on which the whole `/balance` is bought per the configuration into the static whitelist of pairs (I'm not certain how to transpose this logic to volume pairs, unless we keep track of everything...even when it's no longer under the scope of the "volume pairs").

It would be required keep track of this `simulated trade` similar to the way we Freqtrade tracks open trades, w_ith the exception that it will never "close"_, but rather combine the percentage change as the output of `B&H`

**Comment by xmatthias** [comment] 2020-06-24 07:46
I'm not a huge fan of Buy&hold comparisons, as you can play them very easily - and they don't really tell you much.

Assuming the market goes down for 2 consecutive months - you start the bot in February - and in April the market as a whole is 10% down - you can beat that benchmark very easily by simply not trading (which also avoids fees ...) 😆 

For backtesting, this is worse as it's an unfair comparison since you know what happened - you can modify the entry date by a day  and get a completely different result.

Also, it assumes that you'd stick to all these trades - assume you bought equal stakes in all pairs - the whole market goes down 50% - and then back up and creates 110% profit (so market is up 10% in the end).
This sounds great in theory - and now your strategy tries to beat it to these 10%.

You'll however have to consider that you'd most likely have sold the trade after -40% loss to avoid further losses - so realistically - you're not in that trade any longer.

---

The calculation for real mode (dry / live) does not make much sense to me.
It'll also create a huge, possibly complicated set of code which we'd have to maintain - but with limited resources we have i don't see that as realistic.
so for RPC / live modes, I'd definitely not want it as it'll create a huge code maintenance burden (especially once you think about Volumepairlist).

Also, you're ignoring the fact that you might have `max_open_trades` set - so if i have 10 pairs in the pairlist, but `max_open_trades` set to 3 - how would you determine WHICH pair should bought at entry?
It'd be a game of luck (buying all would be comparing apples to bananas, as the bot is only allowed 3 parallel trades- but  the comparison buys 10 - possibly with a higher stake).


For backtesting, it might be a possibility - although i really don't like it as a metric (see above for reasons).
We do however have a issue for this already in #2524 - which also explains it in a better way FIP is not really used for market change - even after searching the internet i'm not sure what that should mean.

**Comment by Corfucinas** [comment] 2020-06-24 08:08
I partly agree with you on the first statement, it is easier to play yourself by having a bias in regards of B&H.

For example, a -10% loss will require an +11% to recuperate loss...but a -25% needs a +33% gain and a -80% would need a +500%, so it is easy to trick yourself by going "oh, yeah, I din't started trading on this day..." but this is a way to circumnavigate a non-robust strategy since it would be more prudent to assume that you entered the market on the worst moment than on the best moment.

When you mention what would happen if the market goes down -50% then up to 110% to create a 10% profit, I don't think that seeking alpha would be wise, since they are other metrics to take into consideration- again, my observation here is that in reality people can easily loss focus by having this metric and then not understanding it and just going "oh yeah, I beat the market on X period", but by having a longer exposure the strategy itself would not be proven as good.

I believe they are different ways to calculate for risk tolerance, for example, somebody who has good liquidity and is not interested in short-momentum approaches may take the -40% loss scenario you mention and just apply a dollar cost average and continue onward.

---

Thank you for the observations on the second part of your answer. I think considering limited resources and code maintenance, the simplest way to introduce this would by on the backtest report (users may simply measure against that in accordance to the discussion on issue #2524 ). 
Another possible solution to bypass the `max_open_trades` is to create another section on the `config.json` on which the user specifies which currency to take into consideration, but it would be the task of the end-user to select according to his criteria which pairs represent a valuable representation (echoing your observation about creating a simple Hodl Strategy)...actually, in turn that might solve this issue, by including an simple class of Hodl on which it will just buy in accordance to the strategy selected, but will never sell until it is forced by the backtest process to `force close`

**Comment by xmatthias** [comment] 2020-06-24 09:27
I don't understand why everyone is so focused on "simulating a buy" ... all you really want is the % difference between the first open, and the last close of the backtest period.

But - as (probably) mentioned in the other issue - it's a question of time - and not having a place for "general" metrics at the moment.
i am however working on that as part of a bigger backtesting change ... so just hold in there - it'll be there eventually :)

**Comment by xmatthias** [comment] 2020-06-25 18:47
I'll close this as duplicate of #2524 - however as said above - i'm working on this as part of a bigger change to backtesting output - so stay tuned and eventually subscribe to that other issue for updates.

**Closed by xmatthias** 2020-06-25 18:47 UTC
Labels: Duplicate, Question

**Comment by Corfucinas** [comment] 2020-06-26 05:15
@xmatthias 

Sounds good to me! Looking forward 😎

**Comment by hroff-1902** [comment] 2020-06-26 20:06
the only question: what is "FIP"?

**Comment by Corfucinas** [comment] 2020-06-27 05:40
> the only question: what is "FIP"?
> 

Freqtrade Improvement Proposal !

**Comment by hroff-1902** [comment] 2020-06-27 07:14
ghm... I would call it FEP (Freqtrade Enhancement Proposal) in this case...

**Comment by xmatthias** [comment] 2020-06-27 07:36
I guess labing them as enhancement (speak, selecting the right issue template) will suffice - no need to invent new  names i'll struggle to remember :D
