### ISSUE TITLE
hyperopt with informative pair?

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3263] opened 2020-05-05 19:23 UTC
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04.4 LTS
  * Python Version: 3.7.4
  * CCXT version: ccxt==1.27.20
  * Branch: Develop
  * Last Commit ID: 77d889beffa60fafc382cf027b8522e58f608399

  
## Step 3: Describe the problem:

Problem to run hyperopt with informative pair 

### Steps to reproduce:

  1. hyperopt call in cli, with EmptyHyperopt from repo (no changes here)

`freqtrade hyperopt --hyperopt EmptyHyperopt --spaces roi stoploss trailing --strategy MACDStrategy_FTX12 --config config_test3.json -e 1000 --hyperopt-loss SortinoHyperOptLossDaily --timerange=20190815-20200301 --ticker-interval 15m`

  2. Strategy with informative pair (backtests are okay, no error msg)

```
    def informative_pairs(self):
        """
       
        BTC/USDT to inform about market direction
                            
        """
        return [("BTC/USD", "1h")]


    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        if self.dp:
            inf_pair, inf_timeframe = self.informative_pairs()[0]
            informative = self.dp.get_pair_dataframe(pair=inf_pair,timeframe=inf_timeframe)

        
        dataframe['BTC_USD_close'] = informative['close']
        dataframe['rsi_informative'] = ta.RSI(informative)

        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']
     
        print(dataframe.columns)

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                qtpylib.crossed_above(dataframe['macd'], dataframe['macdsignal']) &
                (dataframe['rsi_informative'] < 50) 
                
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame
        :return: DataFrame with buy column
        """
        dataframe.loc[
            (
                qtpylib.crossed_below(dataframe['macd'], dataframe['macdsignal']) 
               
            ),
            'sell'] = 1

        return dataframe


```
### Observed Results:

See error msg below

### Relevant code exceptions or logs:

  ```
2020-05-05 21:14:37,154 - freqtrade.optimize.backtesting - INFO - Loading data from 2019-08-15T00:00:00+00:00 up to 2020-03-01T00:00:00+00:00 (199 days)..
2020-05-05 21:14:37,154 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/andreas/freqtrade/freqtrade/optimize/hyperopt.py", line 598, in start
    preprocessed = self.backtesting.strategy.ohlcvdata_to_dataframe(data)
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 501, in ohlcvdata_to_dataframe
    for pair, pair_data in data.items()}
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 501, in <dictcomp>
    for pair, pair_data in data.items()}
  File "/home/andreas/freqtrade/freqtrade/strategy/interface.py", line 517, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/home/andreas/freqtrade/user_data/strategies/MACDStrategy_FTX12.py", line 63, in populate_indicators
    dataframe['BTC_USD_close'] = informative['close']
UnboundLocalError: local variable 'informative' referenced before assignment

  ```

**Comment by xmatthias** [comment] 2020-05-05 19:25
it's a duplicate of #2608 .

DataProvider is currently not available in hyperopt due to some restraints in pickling that class.

I'll close this one as it's a duplicate ... please move further discussion to #2608.

**Closed by xmatthias** 2020-05-05 19:25 UTC
