### ISSUE TITLE
Kraken crypto balance not matching decimals with Freq

### ISSUE THREAD

**Issue by Thrallix** [freqtrade/freqtrade#10002] opened 2024-03-25 11:58 UTC
## Describe your environment

  * Operating system: Ubuntu latest
  * Python Version: 3.11.8
  * CCXT version: ccxt==4.2.51
  * Freqtrade Version: freqtrade 2024.2
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

freqtrade.freqtradebot - WARNING - Not enough ADA in wallet to exit Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15). Trying to recover.

### Steps to reproduce:

  1. Use kraken to trade with
  
### Observed Results:

  * What happened?

I use LIMIT_BUY orders according to my logs, what happens is that when the bot buys crypto, the decimals don't seem to match with Kraken, causing the error started above, somehow i feel like this most frequently happened with ADA, LUNA and ALGO, but i'm sure it happens with all crypto's eventually.

For example my Freqtrade says that i have 41.77109440 ALGO right now, my Kraken app however says that i have 41.77109, cutting off the 440 part.

  * What did you expect to happen?

For it to just be able to place orders and for Freq to match Kraken's decimal count.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
aggroth  | 2024-03-25 11:57:06,955 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-25 11:57:06,959 - freqtrade.freqtradebot - INFO - handled order OUQ724-ZULRU-6WFFF4
aggroth  | 2024-03-25 11:57:15,966 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-25 11:57:15,966 - freqtrade.freqtradebot - WARNING - Not enough ADA in wallet to exit Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15). Trying to recover.
aggroth  | 2024-03-25 11:57:22,036 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15)
aggroth  | 2024-03-25 11:57:22,040 - freqtrade.persistence.trade_model - INFO - Updating trade (id=38) ...
aggroth  | 2024-03-25 11:57:22,040 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15).
aggroth  | 2024-03-25 11:57:27,952 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-25 11:57:27,956 - freqtrade.freqtradebot - INFO - handled order OYEDTI-GWEFJ-4HCO2T
aggroth  | 2024-03-25 11:57:36,957 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-25 11:57:36,957 - freqtrade.freqtradebot - WARNING - Not enough ALGO in wallet to exit Trade(id=37, pair=ALGO/EUR, amount=41.77109440, is_short=False, leverage=1.0, open_rate=0.23940000, open_since=2024-03-25 10:00:59). Trying to recover.
aggroth  | 2024-03-25 11:57:43,005 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=37, pair=ALGO/EUR, amount=41.77109440, is_short=False, leverage=1.0, open_rate=0.23940000, open_since=2024-03-25 10:00:59)
aggroth  | 2024-03-25 11:57:43,011 - freqtrade.persistence.trade_model - INFO - Updating trade (id=37) ...
aggroth  | 2024-03-25 11:57:43,011 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=37, pair=ALGO/EUR, amount=41.77109440, is_short=False, leverage=1.0, open_rate=0.23940000, open_since=2024-03-25 10:00:59).
aggroth  | 2024-03-25 11:57:48,958 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-25 11:57:48,961 - freqtrade.freqtradebot - INFO - handled order OUQ724-ZULRU-6WFFF4
aggroth  | 2024-03-25 11:57:57,967 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-25 11:57:57,968 - freqtrade.freqtradebot - WARNING - Not enough ADA in wallet to exit Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15). Trying to recover.
aggroth  | 2024-03-25 11:58:03,969 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15)
aggroth  | 2024-03-25 11:58:03,975 - freqtrade.persistence.trade_model - INFO - Updating trade (id=38) ...
aggroth  | 2024-03-25 11:58:03,976 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=38, pair=ADA/EUR, amount=16.65559069, is_short=False, leverage=1.0, open_rate=0.60039500, open_since=2024-03-25 10:16:15).
aggroth  | 2024-03-25 11:58:10,066 - freqtrade.wallets - INFO - Wallets synced.

  ```

**Comment by xmatthias** [comment] 2024-03-25 13:55
i suspect this is a duplicate of #9880.

Unfortunately, that user never got back to us letting us know if he ever got in touch with Kraken support (and subsequently, what their response was) - as this is first and foremost an issue that needs to be picked up with them - at least for confirmation.

Essentially, the way it looks like - you buy a coin with X decimals - and the wallet then cuts part of it.
per se, that's nothing uncommon - except for the fact that kraken reports the "bigger" precision as being valid - and allows you to place (buy) orders for these amounts.

From what i could tell - the precision itself is correct - they simply apply some form of rounding somewhere between what you bought, vs. what's in your wallet - which i personally consider stealing from that wallet.

Up to some degree - we COULD fall back to what's in the wallet - but in reality kraken is removing these assets from your account (you paid for them - if you do price / cost).
That linked issue has a full analysis and calculations .. which I'm not replicating here.


---

I'm happy to look at this in detail if you think it's something different  (i don't think it is) - but it'll need more data (and the outcome will most likely still be - bring this information to kraken support).

What we (and effectively, kraken support) will need is logs with `exchange.log_responses` turned on (these will include details for each order - as well as the "wallets" endpoint.

**Comment by Thrallix** [comment] 2024-03-25 14:34
> i suspect this is a duplicate of #9880.
> 
> Unfortunately, that user never got back to us letting us know if he ever got in touch with Kraken support (and subsequently, what their response was) - as this is first and foremost an issue that needs to be picked up with them - at least for confirmation.
> 
> Essentially, the way it looks like - you buy a coin with X decimals - and the wallet then cuts part of it. per se, that's nothing uncommon - except for the fact that kraken reports the "bigger" precision as being valid - and allows you to place (buy) orders for these amounts.
> 
> From what i could tell - the precision itself is correct - they simply apply some form of rounding somewhere between what you bought, vs. what's in your wallet - which i personally consider stealing from that wallet.
> 
> Up to some degree - we COULD fall back to what's in the wallet - but in reality kraken is removing these assets from your account (you paid for them - if you do price / cost). That linked issue has a full analysis and calculations .. which I'm not replicating here.
> 
> I'm happy to look at this in detail if you think it's something different (i don't think it is) - but it'll need more data (and the outcome will most likely still be - bring this information to kraken support).
> 
> What we (and effectively, kraken support) will need is logs with `exchange.log_responses` turned on (these will include details for each order - as well as the "wallets" endpoint.


I've sent them an e-mail asking what happened to the rest of the decimals and i blatantly just told them that i kind of felt like i was being robbed, i will update you about their response. Also linked them to this and the other ticket.

Thank you for explaining further.
Is there any way we could implement a temporary fix for this though? Or should i just move exchanges, which is what i'm honestly considering at this point since their fees are already crazy high and they held my money for 72 hours before i could move it.

It's starting to feel more and more like a scam platform.

**Comment by xmatthias** [comment] 2024-03-25 15:28
well kraken felt like the most legit platform for quite some time to me - though i don't actively use it for much as their ratelimits are insanely high (for non-auth endpoints) - as well as their fees.

Now in my understanding - you won't really encounter a problem once it comes to a sell - as we do have "adjustment" code there to drop balance if only a fraction is missing.

**Comment by Thrallix** [comment] 2024-03-25 15:54
> well kraken felt like the most legit platform for quite some time to me - though i don't actively use it for much as their ratelimits are insanely high (for non-auth endpoints) - as well as their fees.
> 
> Now in my understanding - you won't really encounter a problem once it comes to a sell - as we do have "adjustment" code there to drop balance if only a fraction is missing.

```
aggroth  | 2024-03-22 19:04:11,800 - freqtrade.wallets - INFO - Wallets synced.
aggroth  | 2024-03-22 19:04:11,802 - uvicorn.error - ERROR - Exception in ASGI application
aggroth  | Traceback (most recent call last):
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
aggroth  |     result = await app(  # type: ignore[func-returns-value]
aggroth  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
aggroth  |     return await self.app(scope, receive, send)
aggroth  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
aggroth  |     await super().__call__(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
aggroth  |     await self.middleware_stack(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
aggroth  |     raise exc
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
aggroth  |     await self.app(scope, receive, _send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
aggroth  |     await self.simple_response(scope, receive, send, request_headers=headers)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
aggroth  |     await self.app(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
aggroth  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
aggroth  |     raise exc
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
aggroth  |     await app(scope, receive, sender)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
aggroth  |     await self.middleware_stack(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
aggroth  |     await route.handle(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
aggroth  |     await self.app(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
aggroth  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
aggroth  |     raise exc
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
aggroth  |     await app(scope, receive, sender)
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
aggroth  |     response = await func(request)
aggroth  |                ^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
aggroth  |     raw_response = await run_endpoint_function(
aggroth  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
aggroth  |     return await run_in_threadpool(dependant.call, **values)
aggroth  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
aggroth  |     return await anyio.to_thread.run_sync(func, *args)
aggroth  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
aggroth  |     return await get_async_backend().run_sync_in_worker_thread(
aggroth  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
aggroth  |     return await future
aggroth  |            ^^^^^^^^^^^^
aggroth  |   File "/home/ftuser/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
aggroth  |     result = context.run(func, *args)
aggroth  |              ^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/freqtrade/freqtrade/rpc/api_server/api_v1.py", line 218, in forceexit
aggroth  |     return rpc._rpc_force_exit(str(payload.tradeid), ordertype, amount=payload.amount)
aggroth  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/freqtrade/freqtrade/rpc/rpc.py", line 861, in _rpc_force_exit
aggroth  |     result = self.__exec_force_exit(trade, ordertype, amount)
aggroth  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/freqtrade/freqtrade/rpc/rpc.py", line 827, in __exec_force_exit
aggroth  |     self._freqtrade.execute_trade_exit(
aggroth  |   File "/freqtrade/freqtrade/freqtradebot.py", line 1731, in execute_trade_exit
aggroth  |     amount = self._safe_exit_amount(trade, trade.pair, sub_trade_amt or trade.amount)
aggroth  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aggroth  |   File "/freqtrade/freqtrade/freqtradebot.py", line 1677, in _safe_exit_amount
aggroth  |     raise DependencyException(
aggroth  | freqtrade.exceptions.DependencyException: Not enough amount to exit trade. Trade-amount: 47.79599646, Wallet: 0
```

[message.txt](https://github.com/freqtrade/freqtrade/files/14746279/message.txt)

Actually it gave me a big error saying that my wallet was 0 when i tried to force sell the order using a market limit order, it also didn't manage to sell any of my crypto whilst it gave me the "not enough ... in wallet" error.

**Comment by xmatthias** [comment] 2024-03-25 16:51
This sounds like a different problem though - your wallet says "0".

The error prior to that points to this being a trade that's already been sold / you never owned.
it's however also lacking context (other loglines prior to this), and is based on a force-exit - which is not doing the "full" logic it'd do on a regular sell.

**Comment by xmatthias** [comment] 2024-03-30 13:00
@Thrallix any update from kraken support ?

**Comment by Thrallix** [comment] 2024-03-30 16:45
> @Thrallix any update from kraken support ?

Not yet, no reply so far.

**Comment by xmatthias** [comment] 2024-04-02 05:10
Assuming you're still encountering this problem / in this trade - maybe you can provide the following informations (open a python shell in the freqtrade environment, then the below should run just fine).

``` python
import ccxt
exchange = ccxt.kraken({
    'apiKey': '<yourApiKey>', 
    'secret': '<yoursecret>',
    })
res = exchange.fetch_order('<orderid>', '<pair>')
print(res)
bal = exchange.fetch_balance()
print(bal)
```

Obviously, replacing the order_id with the order id from the logs - and `pair` with the corresponding pair.

**Closed as completed** 2024-04-25 11:45 UTC

**Comment by xmatthias** [comment] 2024-04-25 11:46
We'll implement a workaround for this for now - which will adjust the wallet amount is < the trade amount.

I'm still not certain why the exchange would behave this way - and it's not happening on test-trades with kraken for me (same pair ... very similar precision).
