### ISSUE TITLE
Trading with USDC as stake currency, staticPairList/whitelist BTC/USDC

### ISSUE THREAD

**Issue by fernandobender** [freqtrade/freqtrade#2745] opened 2020-01-05 18:28 UTC
## Step 1: Have you search for this issue before posting it?
yes, specially **Support USDC as a stake #1861**
but that relates mostly to DynamicPairList, as i understood.

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu 19.04
  * Python Version: 3.7.3 (`python -V`)
  * CCXT version: 1.21.23 (`pip freeze | grep ccxt`)
  * Branch: Develop
  * Last Commit ID: d1cda3991c87d66b13de7e1fa797615c033fb179 (`git log --format="%H" -n 1`)
  
## Step 3: Describe the problem:
i get the following error message.

freqtrade.configuration.config_validation - CRITICAL - Invalid configuration. See config.json.example. Reason: 'USDC' is not one of ['BTC', 'XBT', 'ETH', 'USDT', 'EUR', 'USD']
 
*Explain the problem you have encountered*
i can't trade using USDC as stake currency.
i'm using StaticPairList / pairwhitelist = ["BTC/USDC", "ETH/USDC"]

### Steps to reproduce:

  1. cd ~/freqtrade
  2. $ source .env/bin/activate
  3. $ freqtrade trade -c config.json -s myStrategy
  
### Observed Results:

  * What happened?
it resulted in the error message posted above.

  * What did you expect to happen?
normal operation in trading mode, as if using USDT as stake_currency / quote currency 

### Relevant code exceptions or logs:

  ```
  // paste your log here
  ```
i've checked **Support USDC as a stake #1861**
as i understood it refers to dynamic pair listing, while i prefer to have control over what the bot can trade.
from the comments on that issue, perhaps editing correspondent string at ~/freqtrade/freqtrade/constants.py would work it around. however i don't feel comfortable editing core files, for it might unleash unforseen behaviour later on.

1. if ongoing developments will fix it, kindly specify how i can monitor its progress.
2. if not, please consider including it in your changes.
3. if meanwhile replacing USDT by USDC is safe, please do let me know.
thank you.

**Comment by xmatthias** [comment] 2020-01-06 11:49
I think you've misred #1861 slightly.
It is not about dynamic pairlist, but about generating the list of supported stake-currencies dynamically (basically not using a list, but validate on the exchange, if this is a possible stake currency) from the exchange data. 

The main reason is that each exchange supports different currencies (USDC is not a valid stake on Kraken, for example, but works on binance) - so a static list will always have huge limitations, and will (almost) never be correct for new exchanges.

I think we're almost there - most "base" functions to implement #1861 (as lined out by @hroff-1902) are there, so now it's just a question of implementing this.

2) and 1): best monitor #1861 (you can use the subscribe button within the issue to get emails / github notifications about the process).
3) yes, but i would add it as additional option, not replace USDT (that will remove the possibility to trade USDT as stake) .


I'll close this as duplicate of #1861 - as mentioned in 1 and 2 - please subscribe to that original issue. We should have some progress on that soon.

**Closed** 2020-01-06 12:14 UTC
Labels: duplicate

**Comment by hroff-1902** [comment] 2020-01-12 19:25
@xmatthias says in #1861 :
> "Good news - USDC (and other previously unsupported stake currencies) will now work from the develop branch (and starting with the next release, with the stable branch)."
