### ISSUE TITLE
optimizing the timeperiod of an indicator in Ta-Lib

### ISSUE THREAD

**Issue by Corfucinas** [freqtrade/freqtrade#3796] opened 2020-09-22 08:37 UTC
Hi,

I'm currently working on a strategy that I wish to optimize, but I been getting stucked on the hyperopt.

The current `strategy`  has a number of indicators which I have configured, an example of this would be

`period_1 = a_int`
`period_2 = a_int`

`populate_indicators():`
`linear_regression_a = ta.LINEARREG(dataframe, timeperiod=period_1) + (`
            `ta.LINEARREG_SLOPE(dataframe, timeperiod=period_1)`
       ` )`

`linear_regression_b = ta.LINEARREG(dataframe, timeperiod=period_2) + (`
           `ta.LINEARREG_SLOPE(dataframe, timeperiod=period_2)`
        `)`

`def populate_buy_trend():`
     `dataframe.loc[`
            `(`
               `condition1 & condition2 & (dataframe["linear_regression_a"] > dataframe["linear_regression_b"])`
            `),`
            `"buy",`
        `] = 1`

When it comes to optimizing, I wish to optimize the `timeperiod` of the indicator (ie, the `timeperiod` of the RSI would be `25` instead of the default `14`), so it's `value` will be different since it is measuring a different period. How can I optimize this?

**Comment by xmatthias** [comment] 2020-09-22 10:02
you should be able to draw inspiration from the [AverageHyperopt](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py) sample.


What you're trying to do is not really different to that Hyperopt, except that you're using a different indicator.

**Comment by Corfucinas** [comment] 2020-09-22 10:07
I came across that file about 10 mins ago and currently trying to implement the same logic.

Dealing with the nested loops since the buy and sell sell_trends() depend on 3 conditions, and 2 of those indicators have different periods..

**Comment by Corfucinas** [comment] 2020-09-22 16:22
@xmatthias 

Well....I think I got the code working, but...
`MemoryError: Unable to allocate 47.7 GiB for an array with shape (10000, 640000) and data type int64`

Do you have an advice in regards to this?

I think it's getting generated by this loop:

        `for linear1 in range(linear1_begin, linear1_end):
            for linear2 in range(linear2_begin, linear2_end):
                for rsi in range(rsi1_begin, rsi1_end):
                    for rsip1 in range(rsip1_begin, rsip1_end):
                        tigger.append((lr1, lr2, rsi, rsip1))`

**Comment by xmatthias** [comment] 2020-09-22 17:31
how about - using smaller search spaces?
i mean - you're optimizing for timeperiod (how many candles it shall look back) - so your search space is <500 per combination.
if you don't optimize them all at once - it should be ok.

**Comment by Corfucinas** [comment] 2020-09-22 17:42
Is there's a way to feed a smaller batch than 500? I tried closing down the space, but I got that write just by using buy and sell in --spaces

**Comment by xmatthias** [comment] 2020-09-22 17:45
batch size is not relevant (that would be `-e`).
The problem is the difference of your variables - say `linear1_begin` and `linear1_end`.
Assuming this represents the timeframe (how many candles it should look back) - then nothing > 499 will work in dry/live - as you only have that many candles to work with.

**Comment by Corfucinas** [comment] 2020-09-22 17:49
Thanks for the feedback, I'll do some more adjustments

**Comment by Corfucinas** [comment] 2020-09-23 07:38
@xmatthias 

Has this happened to you?

`020-09-23 07:36:45,270 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/downloads/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/ubuntu/downloads/freqtrade/freqtrade/commands/optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "/home/ubuntu/downloads/freqtrade/freqtrade/optimize/hyperopt.py", line 710, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 395, in ask
    x = opt.ask()
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 446, in _ask
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 446, in <listcomp>
    min_delta_x = min([self.space.distance(next_x, xi)
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/space/space.py", line 1132, in distance
    distance += dim.distance(a, b)
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/space/space.py", line 737, in distance
    if not (a in self and b in self):
  File "/home/ubuntu/downloads/freqtrade/.env/lib/python3.8/site-packages/skopt/space/space.py", line 714, in __contains__
    return point in self.categories
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

If it is possible, I can attach my Hyperopt file, since you are more experienced maybe you'll be able to immediately spot the error..

**Comment by Corfucinas** [comment] 2020-09-27 11:28
@xmatthias 

I tried to troubleshoot around it but could not get passed the error `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

So decided to just run the .py you shared on [AverageHyperopt](https://github.com/freqtrade/freqtrade-strategies/blob/master/user_data/hyperopts/AverageHyperopt.py), but interesting enough it did raised the same error.

 [Epoch 24 of 20000 (  0%)] |\                                                                                                                                 | [ETA:  19:10:15, Elapsed Time: 0:01:22] 
| * Best |    27/20000 |     2064 |    582    5 1477 |       -0.04% | -905.66799686 USDT  (-90.48%) |        756.1 m |     1.24223 |
2020-09-27 19:24:37,625 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "d:\github\freqtrade\freqtrade\main.py", line 36, in main
    return_code = args['func'](args)
  File "d:\github\freqtrade\freqtrade\commands\optimize_commands.py", line 81, in start_hyperopt
    hyperopt.start()
  File "d:\github\freqtrade\freqtrade\optimize\hyperopt.py", line 710, in start
    asked = self.opt.ask(n_points=current_jobs)
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\optimizer\optimizer.py", line 395, in ask
    x = opt.ask()
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\optimizer\optimizer.py", line 367, in ask
    return self._ask()
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\optimizer\optimizer.py", line 446, in _ask
    min_delta_x = min([self.space.distance(next_x, xi)
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\optimizer\optimizer.py", line 446, in <listcomp>
    min_delta_x = min([self.space.distance(next_x, xi)
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\space\space.py", line 1132, in distance
    distance += dim.distance(a, b)
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\space\space.py", line 737, in distance
    if not (a in self and b in self):
  File "D:\Github\freqtrade\.env\lib\site-packages\skopt\space\space.py", line 714, in __contains__
    return point in self.categories
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "D:\Programming languages\Python\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)



Any ideas to what might be causing this? Even with a reduced timeperiod (let's say, 60 days) it still doesnt seem to work.

**Comment by caudurodev** [comment] 2020-10-05 11:13
I have the same issue with hyperopts that include iterating the indicators. The strange thing is that the hyperopt works for the first 100 or so epochs and then throws the same error:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by Corfucinas** [comment] 2020-10-05 11:16
Same thing as me, I managed to get a few dozens interactions and then it raised the error....could you share your hyperopt here? Maybe that will help identify and fix the issue more quickly

**Comment by xmatthias** [comment] 2020-10-05 11:40
To me, it's an issue (or maybe intentional change) in the last version of scikit-optimize.

The problem is that scikit-optimize isn't accepting tuples as first argument to `Categorical` anymore.
The changelog does not suggest any such change though, so maybe it was working "by accident" in the past, and isn't working now anymore.

It works for the first ~30 epochs (the ones that are randomly generated at first startup) - and usually fails with the first non-initial epoch.
There's a constant at the top of `hyperopt.py` you can lower to have it fail immediately...

You can workaround this by not using tuples, but instead using a string (use any separator you like) - and then splitting that string up again and using the separate parts - or by using a different method entirely.

It's not entirely clear to me why / what causes this to break within scikit-optimize, and if it's intentional or accidental (but i have to admit, i spent maybe 10 minutes at this problem in total).
There also doesn't seem to be an open issue for this - so it's either not noticed, or no one bothered to report it yet.

The problem to report it is that we'd need a "minimalistic" example - which removes all hyperopt code and uses only scikit-optimize - which i didn't have time to create yet (and probably won't have time in the next few weeks either).

**Comment by Corfucinas** [comment] 2020-10-07 02:30
Seems to be working, I managed to get it to run pass the 30 initial epochs, going to backtest and see if I can match the results or something is off. Just changed the .append(loop1,loop2) to .append(str(loop1,loop2) and the dataframe to this
`dataframe[f"indicator{int(params['sell-trigger'][1:3])}"]`

**Comment by xmatthias** [comment] 2020-10-07 05:37
well now i wouldn't split the string this way - it's rather risky and only works as long as your parameters are of the same length

I think a safer solution would be to use `.append(f"{loop1}.{loop2}")` - and then use `params['sell-trigger'].split(.)` to get the 2 elements back again.

**Comment by Corfucinas** [comment] 2020-10-07 10:43
@xmatthias 

Yeah, that works too! I ended up overthinking it. I'll leave it running tonight a few thousand epochs and hopefully everything will work fine tomorrow.

**Comment by Prossi79** [comment] 2020-10-18 15:48
@Corfucinas can you point me pls where I would need to adjust above code snippets? I was facing the same problem as you ..  I am trying to run AverageHyperopt from the repo

Thanks!

**Comment by Corfucinas** [comment] 2020-10-19 03:49
@Prossi79 

It won't work if you try to compare an array in np, follow this link for an explanation  => [ink](https://stackoverflow.com/questions/28899920/numpy-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous).

You can overcome this by having (instead of an array), represent the indicators by using strings. You need to write it yourself, F strings will help you there.

1) Use "for loops" to generate all possible indicators timeframes
2) Append these values and return them by Categorical
3) Append the condition and use the F strings to select the correct timeframe.

I'm still having some issues since I can't replicate the hyperopt to the backtests...but it is working correctly (no errors).

**Comment by Corfucinas** [comment] 2020-10-22 17:21
Anyone had any luck? I can't replicate the results from the hyperopt....not even close

**Comment by xmatthias** [comment] 2020-10-22 17:38
then you've got some parameters /indicators wrong.

Hyperopt is just running backtesting over and over.

Maybe some parameters are overwritten from the configuration (trailing stop is a good candidate for this) ... 
Also, make sure that nothing else changes (like open-end hyperopt (no end-date) - and you did download data again)) ...

**Comment by Corfucinas** [comment] 2020-10-23 02:29
@xmatthias

Yeah, that was the problem,  I had a start date `timerange=20200101-` but no end-data, and I thought it would run just until the last downloaded timeframe data...

**Comment by xmatthias** [comment] 2020-10-23 04:26
well yes it does - but assume you hyperopt (data available until 20201001), then download data again - then backtest - now you did hyperopt until 20201001 - but backtesting had data until 20201016 ... obviously results will differ ... as you had 16 more days to make trades.

**Comment by Corfucinas** [comment] 2020-10-23 05:40
@xmatthias 

I didn't download the data...I believe. I downloaded it to have it available under `/user_data/` , when I ran the Hyperopt, I would just specify an initial `time-period` (since I having so many permutations would go over my RAM).
I could not replicate any of the results. Let's say that Hyperopt would give me a result that the tot ROI is 500%, when I backtest it, it would give me -50% and so on. If it was close enough, I could understand, but the results seemed completely wrong. I managed to get some matching runs, boot up a server in AWS and going to let it run, and then try a few epochs in my local machine.

I think this issue can be closed, let me see if I can replicate them to make sure first.

**Comment by xmatthias** [comment] 2020-10-23 05:53
honestly, this issue is not about your hyperopt alignment struggles, but about hyperopting multi-value categories - which is still broken in the example.

I'd therefore like to keep this issue open (but with the original topic ...) if you don't mind

**Comment by Corfucinas** [comment] 2020-10-23 06:00
Yes, sure.

**Comment by xiedidan** [comment] 2020-12-23 06:50
OK, for anyone who want a detailed tutorial for AverageHyperopt modding, we have to update ```indicator_space``` like this:
```py
buyTriggerList.append(
    # (short, medium)
    '{}-{}'.format(short, medium)
)
```
then, we split trigger in ```populate_buy_trend```:
```py
if 'trigger' in params:
    trigger = [int(item) for item in params['trigger'].split('-')]
    
    conditions.append(qtpylib.crossed_above(
        dataframe[f"maShort({trigger[0]})"],
        dataframe[f"maMedium({trigger[1]})"])
        )
```
Do the same modding on sell space and populate functions. And we are done.

**Comment by xmatthias** [comment] 2021-03-12 05:16
I'm gonna close this as the samle has now been updated in https://github.com/freqtrade/freqtrade-strategies/pull/132

**Closed by xmatthias** 2021-03-12 05:16 UTC
Labels: Hyperopt, Triage Needed
