### ISSUE TITLE
Huobi: Trade telegram reports 99.99% loss after FT 2022.7 upgrade

### ISSUE THREAD

**Issue by MarcelRoozekrans** [freqtrade/freqtrade#7151] opened 2022-07-31 08:59 UTC
## Describe your environment

  * Operating system: Debian
  * Python Version: 3.9.2
  * CCXT version: 1.91.29
  * Freqtrade Version: 2022.7
 
## Describe the problem:

After update to 2022.7 Huobi reports a 99.99 losss in telegram after a trade.

### Relevant code exceptions or logs

Log of the trade: 
```2022-07-30 22:12:35,792 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for YFI/USDT with stake_amount: 152.2138521198781 ...
2022-07-30 22:12:35,825 - freqtrade.freqtradebot - INFO - Order # was created for YFI/USDT and status is None.
2022-07-30 22:12:35,877 - freqtrade.wallets - INFO - Wallets synced.
2022-07-30 22:12:35,885 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 78, 'type': entry, 'buy_tag': '8 15 ', 'enter_tag': '8 15 ', 'exchange': 'Huobi', 'pair': 'YFI/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 12490.19, 'open_rate': 12490.19, 'order_type': 'market', 'stake_amount': 152.2138521198781, 'stake_currency': 'USDT', 'fiat_currency': 'EUR', 'amount': 0.012186672269987734, 'open_date': datetime.datetime(2022, 7, 30, 20, 12, 35, 826041), 'current_rate': 12490.19}
2022-07-30 22:12:35,885 - freqtrade.rpc.telegram - INFO - Notification 'entry' not sent.
2022-07-30 22:12:36,088 - freqtrade.worker - INFO - Bot heartbeat. PID=55866, version='2022.7, strategy_version: v11.1.69', state='RUNNING'
2022-07-30 22:12:40,219 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=78, pair=YFI/USDT, amount=0.01218667, is_short=False, leverage=1.0, open_rate=12490.19000000, open_since=2022-07-30 20:12:35)
2022-07-30 22:12:40,226 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=78, pair=YFI/USDT, amount=0.01218667, is_short=False, leverage=1.0, open_rate=12490.19000000, open_since=2022-07-30 20:12:35) [buy]: 1.9497575e-05 YFI - rate: 0.0016
2022-07-30 22:12:40,261 - freqtrade.wallets - INFO - Wallets synced.
2022-07-30 22:12:40,262 - freqtrade.freqtradebot - INFO - Fee amount for Trade(id=78, pair=YFI/USDT, amount=0.01218667, is_short=False, leverage=1.0, open_rate=12490.19000000, open_since=2022-07-30 20:12:35) was in base currency - Eating Fee 1.9497574828306e-05 into dust.
2022-07-30 22:12:40,262 - freqtrade.persistence.trade_model - INFO - Updating trade (id=78) ...
2022-07-30 22:12:40,263 - freqtrade.persistence.trade_model - INFO - MARKET_BUY has been fulfilled for Trade(id=78, pair=YFI/USDT, amount=0.01218598, is_short=False, leverage=1.0, open_rate=12490.20612504, open_since=2022-07-30 20:12:35).
2022-07-30 22:12:40,305 - freqtrade.wallets - INFO - Wallets synced.
2022-07-30 22:12:40,306 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 78, 'type': entry_fill, 'buy_tag': '8 15 ', 'enter_tag': '8 15 ', 'exchange': 'Huobi', 'pair': 'YFI/USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 12490.206125043635, 'open_rate': 12490.206125043635, 'order_type': None, 'stake_amount': 152.20545534000001, 'stake_currency': 'USDT', 'fiat_currency': 'EUR', 'amount': 0.012185984267691042, 'open_date': datetime.datetime(2022, 7, 30, 20, 12, 35, 826041), 'current_rate': 12490.19}
2022-07-30 22:13:01,736 - freqtrade.freqtradebot - INFO - Exit for YFI/USDT detected. Reason: custom_exit
2022-07-30 22:13:01,802 - freqtrade.wallets - INFO - Wallets synced.
2022-07-30 22:13:01,840 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 78, 'exchange': 'Huobi', 'pair': 'YFI/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 12671.02, 'order_type': 'market', 'amount': 0.012185984267691042, 'open_rate': 12490.206125043635, 'close_rate': None, 'current_rate': 12671.02, 'profit_amount': 1.71281215, 'profit_ratio': 0.01123531, 'buy_tag': '8 15 ', 'enter_tag': '8 15 ', 'sell_reason': 'sell_profit_o_bull_1_1 ( 8 15 )', 'exit_reason': 'sell_profit_o_bull_1_1 ( 8 15 )', 'open_date': datetime.datetime(2022, 7, 30, 20, 12, 35, 826041), 'close_date': datetime.datetime(2022, 7, 30, 20, 13, 1, 840954), 'stake_currency': 'USDT', 'fiat_currency': 'EUR'}
2022-07-30 22:13:02,202 - freqtrade.wallets - INFO - Wallets synced.
```
Screenshot of the telegram message:

![image](https://user-images.githubusercontent.com/2911728/182018657-d6b9aa73-4bec-48cb-bae1-7cd3be43469e.png)

**Comment by xmatthias** [comment] 2022-07-31 09:13
purely from the numbers - the calculation is correct (so the problem is the price we got from the exchange).

Please enable exchange level logging (`"exchange.log_responses": true` in the configuration) so we can see what the exchange is sending providing you with. if the exchange is reporting a sell at 1$ - it'll be difficult for freqtrade to interpret it differently.
Unfortunately, freqtrade will consider this trade as closed - so you'll most likely have to wait for the next trade.

the exit is a market order - so if the orderbook is very thin, this is actually a possibility in theory that price is pushed this far down (chart should show this though). What was the actual value the order on the exchange filled?

---

You can also try the following query (with the orderid taken from the database's order table) - but it's questionable if the return result will be the same.

``` python
import ccxt
exchange = ccxt.huobi({'apiKey': '<yourApiKey>', 'secret': '<yoursecret>' })
res = exchange.fetch_order(order_id, pair)
print(res)
```

**Comment by MarcelRoozekrans** [comment] 2022-07-31 09:24
Thnx for the quick response, i have multiple trades that reported this loss, but unfortunatly I deleted them from the db :)

Will try and see if I can get an other one for you, enabled the extra lgging like you suggested.

**Comment by xmatthias** [comment] 2022-07-31 09:36
make sure to have the bot restarted after enabling this ... otherwise it'll not apply.
You'll however see the log with "response" messages pretty soon - at least for "private" requests like fetching balance or so

**Comment by xmatthias** [comment] 2022-08-01 04:46
The problem seems to be a combination of market orders with a ccxt update.

it's reported to ccxt now (https://github.com/ccxt/ccxt/issues/14553) - and should be fixed soonish (PR is available).

**Comment by MarcelRoozekrans** [comment] 2022-08-01 06:59
Thnx for the update will switch to limit for the time being then.

**Closed as completed** 2022-08-01 17:43 UTC
Labels: Bug, CCXT

**Comment by xmatthias** [comment] 2022-08-01 17:47
Updating to the latest develop (or rather updating ccxt to the latest version - for example with `pip install -U ccxt`) will fix this.
