### ISSUE TITLE
Stop-Loss in futures

### ISSUE THREAD

**Issue by mert-donmez** [freqtrade/freqtrade#6493] opened 2022-03-04 01:50 UTC
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: 3.9.5
  * CCXT version: 1.74.65
  * Freqtrade Version: Freqtrade develop (feat/short)
  
## Your question

Is the stop loss multiplied by the leverage? ie 0.01 or 0.2 should be adjusted to set a -20% loss with 20x leverage? 0.01 seems to be correct in long trade but should be 0.2 in short trade? Even though it was set to 0.01, it sold at a loss of 1.8% on the short trade

**Comment by xmatthias** [comment] 2022-03-04 05:32
Stoploss is adjusted for leverage - so a 10% stoploss with 5 x leverage will only cause a 5% loss of initial capital.

Not including leverage would cause a 50% loss of initial capital in the described sample.

It's unfortunately not clear what you're talking about / describing. what is 0.01/0.2 ... ? 
maybe you can also clarify this with some samples of where you think there is a problem.

You should also have a look at the values in the database - stoplosses are not guaranteed to fill at the stop price.
By default, we set a stop price - say at 1% - and have the limit order 1% below (or 1% above, in case of a short) - so the maximum slippage will be 1%.

This is explained [here](https://www.freqtrade.io/en/latest/stoploss/#stoploss_on_exchange-and-stoploss_on_exchange_limit_ratio) - and didn't really change with stoploss - other than that the direction is inversed.

**Comment by mert-donmez** [comment] 2022-03-04 19:47
> Stoploss is adjusted for leverage - so a 10% stoploss with 5 x leverage will only cause a 5% loss of initial capital.
> 
> Not including leverage would cause a 50% loss of initial capital in the described sample.
> 
> It's unfortunately not clear what you're talking about / describing. what is 0.01/0.2 ... ? maybe you can also clarify this with some samples of where you think there is a problem.
> 
> You should also have a look at the values in the database - stoplosses are not guaranteed to fill at the stop price. By default, we set a stop price - say at 1% - and have the limit order 1% below (or 1% above, in case of a short) - so the maximum slippage will be 1%.
> 
> This is explained [here](https://www.freqtrade.io/en/latest/stoploss/#stoploss_on_exchange-and-stoploss_on_exchange_limit_ratio) - and didn't really change with stoploss - other than that the direction is inversed.

When I set the stop loss ratio in the strategy file to -0.2, it sells with 20% loss in short trade (which is something I want), but in long trade it does not sell even though the loss is more than 20%.

If I set the stop loss part ratio -0.01, this time the stop loss sells at a loss of 20% on the long trade (which is what I want) but when there is a loss of 1% on the short trade, it sells immediately %1 loss but i want to expect 20% loss with 20x leverage both in long and short trade (leverage 20x in all cases).

Short trade (stop-loss -0.2) : 
![0 2_short](https://user-images.githubusercontent.com/83416622/156831249-734da05f-7634-432a-b218-78f3d7758be0.jpg)

Long trade (stop-loss -0.2) : 
![long_0 2](https://user-images.githubusercontent.com/83416622/156831412-47d17ac8-0e04-421e-a2fc-cba0110ef3a4.jpg)

Should I use custom stop loss for either short or long trade?
For example, should I set the stop loss rate to -0.2 and set the custom loss to -0.01 for long trades?

**Comment by xmatthias** [comment] 2022-03-05 14:31
If you use static or dynamic stoploss will not change the calculation.

The sell of trade no4 seems correct.
The long trade seems high - however it'll also depend on the values i think - using a leverage of 20, a small move has a pretty high % effect - so it might be a case of "didn't notice it yet" - as this 20% 20x leveraged move could very well be a "one tick" move

Please provide me with the output of `freqtrade show-trades --trade-ids 7 --print-json` - so we can have a closer look at this.

**Comment by mert-donmez** [comment] 2022-03-06 07:07
> If you use static or dynamic stoploss will not change the calculation.
> 
> The sell of trade no4 seems correct. The long trade seems high - however it'll also depend on the values i think - using a leverage of 20, a small move has a pretty high % effect - so it might be a case of "didn't notice it yet" - as this 20% 20x leveraged move could very well be a "one tick" move
> 
> Please provide me with the output of `freqtrade show-trades --trade-ids 7 --print-json` - so we can have a closer look at this.

Unfortunately i deleted some trades from database because i sold manually but i think it has nothing to do with leverage because short trade hasn't been a problem so far sold at -20%.

I'll pretend to say the same things over and over again but at 20x leverage, if I set the stoploss to -0.01, the long trades will work fine and sell with 20% loss as I want, but if I set the -0.2 it's the opposite and the short trade will work fine.

Is this problem only for me right now, haven't you encountered it before?

It is obvious that there is something strange with the stoploss distance in the /status part:
![photo_2022-03-06_09-56-11](https://user-images.githubusercontent.com/83416622/156912683-af0f0b37-3520-474f-a53a-6fe8ee959a18.jpg)

**Comment by xmatthias** [comment] 2022-03-06 07:18
For me, both directions did work fine.

While screenshots from telegram are nice - they don't show even half the picture.
maybe you have some code preventing the sell - or the sell encounters some other problem like not being filled. Logs would tell this - but screenshots will not.

Please understand that without proper information (data from the database, logs) - there is nothing actionable for us to do - so without logs / info from the database, i'll have to close this issue as "can't reproduce" - simply because of lack of information.

**Comment by mert-donmez** [comment] 2022-03-06 07:58
> For me, both directions did work fine.
> 
> While screenshots from telegram are nice - they don't show even half the picture. maybe you have some code preventing the sell - or the sell encounters some other problem like not being filled. Logs would tell this - but screenshots will not.
> 
> Please understand that without proper information (data from the database, logs) - there is nothing actionable for us to do - so without logs / info from the database, i'll have to close this issue as "can't reproduce" - simply because of lack of information.

Sorry you are right here is a log with short and long trade. And in long trade the stop loss looks Null

```
{
        "trade_id": 4,
        "pair": "TLM/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 3086.0,
        "amount_requested": 3086.34145087,
        "stake_amount": 315.0806,
        "strategy": "most_wt_strategy",
        "buy_tag": null,
        "enter_tag": null,
        "timeframe": 1,
        "fee_open": 0.0004,
        "fee_open_cost": 0.12603223,
        "fee_open_currency": "USDT",
        "fee_close": 0.0004,
        "fee_close_cost": 0.12739007,
        "fee_close_currency": "USDT",
        "open_date": "2022-03-04 05:02:05",
        "open_timestamp": 1646370125119,
        "open_rate": 0.1021,
        "open_rate_requested": 0.1021,
        "open_trade_value": 314.95456776,
        "close_date": "2022-03-04 08:06:47",
        "close_timestamp": 1646381207845,
        "close_rate": 0.1032,
        "close_rate_requested": 0.1032,
        "close_profit": -0.23040608,
        "close_profit_pct": -23.04,
        "close_profit_abs": -3.62837237,
        "trade_duration_s": 11082,
        "trade_duration": 184,
        "profit_ratio": -0.23040608,
        "profit_pct": -23.04,
        "profit_abs": -3.62837237,
        "sell_reason": "stop_loss",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.10312099999999999,
        "stop_loss_ratio": 0.2,
        "stop_loss_pct": 20.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2022-03-04 05:02:12",
        "stoploss_last_update_timestamp": 1646370132430,
        "initial_stop_loss_abs": 0.10312099999999999,
        "initial_stop_loss_ratio": 0.2,
        "initial_stop_loss_pct": 20.0,
        "min_rate": 0.1019,
        "max_rate": 0.1032,
        "leverage": 20.0,
        "interest_rate": 0.0,
        "isolated_liq": 0.1059501695,
        "is_short": true,
        "trading_mode": "futures",
        "funding_fees": 0.01964995,
        "open_order_id": null,
        "filled_entry_orders": [
            {
                "amount": 3086.0,
                "average": 0.1032,
                "cost": 318.4752,
                "filled": 3086.0,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-03-04 08:06:47",
                "order_timestamp": 1646381207282,
                "order_filled_date": "2022-03-04 08:06:47",
                "order_filled_timestamp": 1646381207569,
                "order_type": "market",
                "pair": "TLM/USDT",
                "price": 0.1032,
                "remaining": 0.0,
                "status": "closed"
            }
        ],
        "filled_exit_orders": [
            {
                "amount": 3086.0,
                "average": 0.1021,
                "cost": 315.0806,
                "filled": 3086.0,
                "ft_order_side": "sell",
                "is_open": false,
                "order_date": "2022-03-04 05:02:07",
                "order_timestamp": 1646370127345,
                "order_filled_date": "2022-03-04 05:02:07",
                "order_filled_timestamp": 1646370127996,
                "order_type": "limit",
                "pair": "TLM/USDT",
                "price": 0.1021,
                "remaining": 0.0,
                "status": "closed"
            }
        ]
    },
    {
        "trade_id": 5,
        "pair": "TLM/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 2314.0,
        "amount_requested": 2314.68781735,
        "stake_amount": 12.16368448,
        "strategy": "most_wt_strategy",
        "buy_tag": null,
        "enter_tag": null,
        "timeframe": 1,
        "fee_open": 0.0002,
        "fee_open_cost": 0.04864028,
        "fee_open_currency": "USDT",
        "fee_close": 0.0004,
        "fee_close_cost": 0.09635495,
        "fee_close_currency": "USDT",
        "open_date": "2022-03-04 11:20:07",
        "open_timestamp": 1646392807788,
        "open_rate": 0.1051,
        "open_rate_requested": 0.1051,
        "open_trade_value": 243.25004028,
        "close_date": "2022-03-04 12:54:09",
        "close_timestamp": 1646398449817,
        "close_rate": 0.1041,
        "close_rate_requested": 0.1041,
        "close_profit": -0.2021784,
        "close_profit_pct": -20.22,
        "close_profit_abs": -2.45899524,
        "trade_duration_s": 5642,
        "trade_duration": 94,
        "profit_ratio": -0.2021784,
        "profit_pct": -20.22,
        "profit_abs": -2.45899524,
        "sell_reason": "sell_signal",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.1010860315,
        "stop_loss_ratio": null,
        "stop_loss_pct": null,
        "stoploss_order_id": null,
        "stoploss_last_update": null,
        "stoploss_last_update_timestamp": null,
        "initial_stop_loss_abs": 0.0,
        "initial_stop_loss_ratio": null,
        "initial_stop_loss_pct": null,
        "min_rate": 0.1038,
        "max_rate": 0.1054,
        "leverage": 20.0,
        "interest_rate": 0.0,
        "isolated_liq": 0.1010860315,
        "is_short": false,
        "trading_mode": "futures",
        "funding_fees": 0.0,
        "open_order_id": null,
        "filled_entry_orders": [
            {
                "amount": 2314.0,
                "average": 0.1051,
                "cost": 243.2014,
                "filled": 2314.0,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-03-04 11:20:07",
                "order_timestamp": 1646392807372,
                "order_filled_date": "2022-03-04 11:20:32",
                "order_filled_timestamp": 1646392832013,
                "order_type": "limit",
                "pair": "TLM/USDT",
                "price": 0.1051,
                "remaining": 0.0,
                "status": "closed"
            }
        ],
        "filled_exit_orders": [
            {
                "amount": 2314.0,
                "average": 0.1041,
                "cost": 240.8874,
                "filled": 2314.0,
                "ft_order_side": "sell",
                "is_open": false,
                "order_date": "2022-03-04 12:54:09",
                "order_timestamp": 1646398449201,
                "order_filled_date": "2022-03-04 12:54:09",
                "order_filled_timestamp": 1646398449539,
                "order_type": "market",
                "pair": "TLM/USDT",
                "price": 0.1041,
                "remaining": 0.0,
                "status": "closed"
            }
        ]
    },

```

**Comment by xmatthias** [comment] 2022-03-06 15:33
The real difference is your market type - you're using market orders for one (shorts) and limit orders for the other (longs).

In combination with the limit entry order not filling immediately, this triggered a (previously unnoiced) bug where stoploss was not properly initialized.

i've now changed a few things around so this should be fixed once #6495 is merged.

**Comment by mert-donmez** [comment] 2022-03-07 05:13
> The real difference is your market type - you're using market orders for one (shorts) and limit orders for the other (longs).
> 
> In combination with the limit entry order not filling immediately, this triggered a (previously unnoiced) bug where stoploss was not properly initialized.
> 
> i've now changed a few things around so this should be fixed once #6495 is merged.

I set it as limit order for both and still the stop loss for long trade shows null. Should I set the stop loss as a limit order or should I use a stop loss on exchange?
```
{
        "trade_id": 19,
        "pair": "TLM/USDT",
        "is_open": false,
        "exchange": "binance",
        "amount": 2147.0,
        "amount_requested": 2147.43281569,
        "stake_amount": 10.30767752,
        "strategy": "most_wt_strategy",
        "buy_tag": null,
        "enter_tag": null,
        "timeframe": 1,
        "fee_open": 0.0002,
        "fee_open_cost": 0.0412224,
        "fee_open_currency": "USDT",
        "fee_close": 0.0004,
        "fee_close_cost": 0.08098484,
        "fee_close_currency": "USDT",
        "open_date": "2022-03-07 01:27:12",
        "open_timestamp": 1646616432248,
        "open_rate": 0.096,
        "open_rate_requested": 0.096,
        "open_trade_value": 206.0707776,
        "close_date": "2022-03-07 03:25:07",
        "close_timestamp": 1646623507556,
        "close_rate": 0.0943,
        "close_rate_requested": 0.0942,
        "close_profit": 0.34237681,
        "close_profit_pct": 34.24,
        "close_profit_abs": 3.52769276,
        "trade_duration_s": 7075,
        "trade_duration": 117,
        "profit_ratio": 0.34237681,
        "profit_pct": 34.24,
        "profit_abs": 3.52769276,
        "sell_reason": "sell_signal",
        "sell_order_status": "closed",
        "stop_loss_abs": 0.09696,
        "stop_loss_ratio": 0.2,
        "stop_loss_pct": 20.0,
        "stoploss_order_id": null,
        "stoploss_last_update": "2022-03-07 01:27:23",
        "stoploss_last_update_timestamp": 1646616443735,
        "initial_stop_loss_abs": 0.09696,
        "initial_stop_loss_ratio": 0.2,
        "initial_stop_loss_pct": 20.0,
        "min_rate": 0.0934,
        "max_rate": 0.0968,
        "leverage": 20.0,
        "interest_rate": 0.0,
        "isolated_liq": 0.09962705250000001,
        "is_short": true,
        "trading_mode": "futures",
        "funding_fees": 0.0,
        "open_order_id": null,
        "filled_entry_orders": [
            {
                "amount": 2147.0,
                "average": 0.0943,
                "cost": 202.4621,
                "filled": 2147.0,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-03-07 03:25:07",
                "order_timestamp": 1646623507153,
                "order_filled_date": "2022-03-07 03:25:07",
                "order_filled_timestamp": 1646623507266,
                "order_type": "limit",
                "pair": "TLM/USDT",
                "price": 0.0943,
                "remaining": 0.0,
                "status": "closed"
            }
        ],
        "filled_exit_orders": [
            {
                "amount": 2147.0,
                "average": 0.096,
                "cost": 206.112,
                "filled": 2147.0,
                "ft_order_side": "sell",
                "is_open": false,
                "order_date": "2022-03-07 01:27:11",
                "order_timestamp": 1646616431838,
                "order_filled_date": "2022-03-07 01:27:21",
                "order_filled_timestamp": 1646616441507,
                "order_type": "limit",
                "pair": "TLM/USDT",
                "price": 0.096,
                "remaining": 0.0,
                "status": "closed"
            }
        ]
    },
    {
        "trade_id": 20,
        "pair": "TLM/USDT",
        "is_open": true,
        "exchange": "binance",
        "amount": 2896.0,
        "amount_requested": 2896.13711389,
        "stake_amount": 13.80009335,
        "strategy": "most_wt_strategy",
        "buy_tag": null,
        "enter_tag": null,
        "timeframe": 1,
        "fee_open": 0.0002,
        "fee_open_cost": 0.05519776,
        "fee_open_currency": "USDT",
        "fee_close": 0.0002,
        "fee_close_cost": null,
        "fee_close_currency": null,
        "open_date": "2022-03-07 05:00:07",
        "open_timestamp": 1646629207835,
        "open_rate": 0.0953,
        "open_rate_requested": 0.0953,
        "open_trade_value": 276.04399776,
        "close_date": null,
        "close_timestamp": null,
        "close_rate": null,
        "close_rate_requested": null,
        "close_profit": null,
        "close_profit_pct": null,
        "close_profit_abs": null,
        "trade_duration_s": null,
        "trade_duration": null,
        "profit_ratio": null,
        "profit_pct": null,
        "profit_abs": null,
        "sell_reason": null,
        "sell_order_status": null,
        "stop_loss_abs": 0.09166031250000001,
        "stop_loss_ratio": null,
        "stop_loss_pct": null,
        "stoploss_order_id": null,
        "stoploss_last_update": null,
        "stoploss_last_update_timestamp": null,
        "initial_stop_loss_abs": 0.0,
        "initial_stop_loss_ratio": null,
        "initial_stop_loss_pct": null,
        "min_rate": 0.095,
        "max_rate": 0.0954,
        "leverage": 20.0,
        "interest_rate": 0.0,
        "isolated_liq": 0.09166031250000001,
        "is_short": false,
        "trading_mode": "futures",
        "funding_fees": 0.0,
        "open_order_id": null,
        "filled_entry_orders": [
            {
                "amount": 2896.0,
                "average": 0.0953,
                "cost": 275.9888,
                "filled": 2896.0,
                "ft_order_side": "buy",
                "is_open": false,
                "order_date": "2022-03-07 05:00:07",
                "order_timestamp": 1646629207418,
                "order_filled_date": "2022-03-07 05:00:15",
                "order_filled_timestamp": 1646629215204,
                "order_type": "limit",
                "pair": "TLM/USDT",
                "price": 0.0953,
                "remaining": 0.0,
                "status": "closed"
            }
        ],
        "filled_exit_orders": []
    }
]
```

**Comment by xmatthias** [comment] 2022-03-07 05:23
Without the fix, there is nothing for you to do. It's a question of luck (and how you price your orders) if it happens or not.

From the output, i can clearly see that you're not using the fix version - which begs the question which precise version you're using anyway - as feat/short is a branch that's constantly getting fixes at the moment.

**Comment by mert-donmez** [comment] 2022-03-07 06:12
> Without the fix, there is nothing for you to do. It's a question of luck (and how you price your orders) if it happens or not.
> 
> From the output, i can clearly see that you're not using the fix version - which begs the question which precise version you're using anyway - as feat/short is a branch that's constantly getting fixes at the moment.

I just downloaded the fix version and entered the long trade with /forcebuy. "stoploss distance" in "/status" looks correct for long trade

**Comment by xmatthias** [comment] 2022-03-07 06:39
Thanks for confirming. I've just merged that branch to feat/short - so it'll be available for everyone to benefit from.

**Closed as completed by xmatthias** 2022-03-07 06:39 UTC
Labels: Non-spot
