### ISSUE TITLE
A value is trying to be set on a copy of a slice from a DataFrame.

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#4649] opened 2021-04-02 16:49 UTC
`freqtrade backtesting --strategy-list ADXMomentum DoesNothingStrategy Scalp AdxSmas EMASkipPump Simple ASDTSRockwellTrading FixedRiskRewardLoss SmoothOperator AverageStrategy Freqtrade_backtest_validation_freqtrade1 SmoothScalp AwesomeMacd InformativeSample Strategy001 BbandRsi Low_BB  Strategy002 BinHV27 mabStra  Strategy003 BinHV45 MACDStrategy_crossed Strategy004 CCIStrategy MACDStrategy Strategy005 ClucMay72018 MultiRSI  SwingHighToSky CMCWinner Quickie  TDSequentialStrategy CofiBitStrategy ReinforcedAverageStrategy TechnicalExampleStrategy CombinedBinHAndCluc ReinforcedQuickie teStrategy CustomStoplossWithPSAR ReinforcedSmoothScalp `
In all strategys i have this error:
```
  self._setitem_single_column(loc, value, pi)
2021-04-02 21:20:20,706 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy Strategy003
2021-04-02 21:20:22,388 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-03-03 15:10:00 up to 2021-04-02 12:45:00 (29 days)..
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
2021-04-02 21:20:29,957 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy BinHV45
2021-04-02 21:20:30,713 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-03-03 15:10:00 up to 2021-04-02 12:45:00 (29 days)..
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
2021-04-02 21:20:37,908 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy MACDStrategy_crossed
2021-04-02 21:20:38,473 - freqtrade.optimize.backtesting - INFO - Backtesting with data from 2021-03-03 15:10:00 up to 2021-04-02 12:45:00 (29 days)..
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1597: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
/home/mab/freqtrade/.env/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
```

**Comment by xmatthias** [comment] 2021-04-02 17:55
Please use the search to see if others opened an issue about the same thing already.

Closing as duplicate of #3644

**Closed as completed by xmatthias** 2021-04-02 17:55 UTC
Labels: Duplicate

**Comment by mablue** [comment] 2021-04-02 19:45
I updated my kernel of linux and problem fixed!! :|
[https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/amd64/](https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/amd64/)

download all files and use this command to update and reboot:
`sudo dpkg -i *`
