### ISSUE TITLE
config_binance.example.json whitelist pairs aren't available on Binance

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7605] opened 2022-10-17 10:23 UTC
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: _____ (`python -V`)
  * CCXT version: 1.93.98 
  * Freqtrade Version: 2022.9.1
  * Strategy: config_binance.example.json
  
Note: All bug reports will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

None of the whitelist pairs in the example config seem to be on Binance so when you copy paste the whitelist into a config it errors out and makes trades it can't cancel.  

### Steps to reproduce:

  1. Pasted these pairs into a config.
  2. "ALGO/BTC",
            "ATOM/BTC",
            "BAT/BTC",
            "BCH/BTC",
            "BRD/BTC",
            "EOS/BTC",
            "ETH/BTC",
            "IOTA/BTC",
            "LINK/BTC",
            "LTC/BTC",
            "NEO/BTC",
            "NXS/BTC",
            "XMR/BTC",
            "XRP/BTC",
            "XTZ/BTC"

  
### Observed Results:

  * FT crashed and asked me to remove them.

### Relevant code exceptions or logs

This is a little bit of it, it errored out on every pair

  ```
 freqtrade1    | ValueError: Can't get market information for symbol NEO/BTC
freqtrade1    | 2022-10-16 18:36:27,011 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
freqtrade1    | 2022-10-16 18:36:27,011 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
freqtrade1    | 2022-10-16 18:36:27,012 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
freqtrade1    | 2022-10-16 18:36:27,013 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "2 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."} 
  ```

**Comment by xmatthias** [comment] 2022-10-17 11:42
Have transferred this to the main repo - as it's really not related to strategies.

---

running `freqtrade trade --config config_examples/config_binance.example.json -s <somestrategy>` works just fine - so the configuration (and all pairs within) are valid if the configuration is used "as a whole".

Now you mention that you copied this pairlist to a different configuration - which suggests that the problem is really with the rest of the configuration.

I suspect that the full startup log would provide more insights here - maybe you're running on futures markets.

to find supported pairs for an exchange, best use [`freqtrade list-pairs`](https://www.freqtrade.io/en/stable/utils/#list-pairslist-markets) - which also takes the market type (spot/futures) as an optional argument.

**Comment by tomjrtsmith** [comment] 2022-10-17 19:39
Here's some of the log output

``` freqtrade1    | 2022-10-17 19:25:01,166 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Cenderawasih_3 from '/freqtrade/user_data/strategies/cenderawasih_3.py'...
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.strategy.hyper - INFO - Found no parameter file.
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: BTC.
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 1000.
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}.
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 100.0}
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.1
freqtrade1    | 2022-10-17 19:25:01,167 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive: 0.001
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.01
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: True
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'limit', 'exit': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': False, 'stoploss_on_exchange_interval': 60}
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: BTC
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 1000
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 200
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 10, 'exit': 10, 'exit_timeout_count': 0, 'unit': 'minutes'}
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.01
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: False
freqtrade1    | 2022-10-17 19:25:01,168 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: -1
freqtrade1    | 2022-10-17 19:25:01,169 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
freqtrade1    | 2022-10-17 19:25:01,189 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
freqtrade1    | 2022-10-17 19:25:01,189 - freqtrade.exchange.exchange - INFO - Using CCXT 1.93.98
freqtrade1    | 2022-10-17 19:25:01,189 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
freqtrade1    | 2022-10-17 19:25:01,217 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'future'}}
freqtrade1    | 2022-10-17 19:25:01,246 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
freqtrade1    | 2022-10-17 19:25:01,993 - freqtrade.commands.trade_commands - ERROR - BTC is not available as stake on Binance. Available currencies are: BUSD, USDT
freqtrade1    | 2022-10-17 19:25:01,999 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
freqtrade1    | Traceback (most recent call last):
freqtrade1    |   File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
freqtrade1    |     worker = Worker(args)
freqtrade1    |   File "/freqtrade/freqtrade/worker.py", line 36, in __init__
freqtrade1    |     self._init(False)
freqtrade1    |   File "/freqtrade/freqtrade/worker.py", line 53, in _init
freqtrade1    |     self.freqtrade = FreqtradeBot(self._config)
freqtrade1    |   File "/freqtrade/freqtrade/freqtradebot.py", line 67, in __init__
freqtrade1    |     self.exchange = ExchangeResolver.load_exchange(
freqtrade1    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
freqtrade1    |     exchange = ExchangeResolver._load_exchange(
freqtrade1    |   File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
freqtrade1    |     exchange = ex_class(**kwargs)
freqtrade1    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 187, in __init__
freqtrade1    |     self.validate_config(config)
freqtrade1    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 217, in validate_config
freqtrade1    |     self.validate_stakecurrency(config['stake_currency'])
freqtrade1    |   File "/freqtrade/freqtrade/exchange/exchange.py", line 523, in validate_stakecurrency
freqtrade1    |     raise OperationalException(
freqtrade1    | freqtrade.exceptions.OperationalException: BTC is not available as stake on Binance. Available currencies are: BUSD, USDT ```

It was set to futures isolated mode

**Comment by xmatthias** [comment] 2022-10-18 10:31
this confirms my suspicion.

You've used the sample pairlist (contianing only /BTC pairs) on futures markets (which only support `/USDT` pairs).
Freqtrade currently doesn't support Coin based futures - so the only valid Futures pairs on binance are `/USDT` (and /BUSDT) pairs.
Obviously such a change will also require a change of stake-currency.

You can find a list of all valid pairs with the following command:

```
freqtrade list-pairs--exchange binance --trading-mode futures
```

In general, i'd advise to use `freqtrade new-config` to generate a config matching your needs - instead of copy/pasting segments of configurations which then don't align.

**Closed as completed by xmatthias** 2022-10-18 10:31 UTC
Labels: Question
