### ISSUE TITLE
Bybit: Unable to place order Insufficient funds to create market sell order on market

### ISSUE THREAD

**Issue by kennylbj** [freqtrade/freqtrade#10833] opened 2024-10-24 01:05 UTC
## Describe your environment

  * Operating system: _ubuntu 22.04___
  * Python Version: _using docker____ (`python -V`)
  * CCXT version: __4.4.20___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __on both docker-2024.10-dev-46db0bc0(dev)_and 2024.9 (stable)_ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  * bybit unified main account
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
Got `WARNING - Unable to place order Insufficient funds to create market sell order on market SOL/USDT. Tried to sell amount 2.099 at rate 171.02.Message: bybit {"retCode":170131,"retMsg":"Insufficient balance.","result":{},"retExtInfo":{},"time":1729729221221}.` error when exit
when `order_types.exit = market`.
it works on limit order
 
### Steps to reproduce:

  1. __set order_types.exit = market ___
  2. _exit order____
  3. _get the error above____
  
### Observed Results:

  * What happened?
  market order does not work on bybit main unified account, but limit order works
  * What did you expect to happen?
  both market and limit work

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2024-10-24 00:20:21,179 - freqtrade.wallets - INFO - Wallets synced.
2024-10-24 00:20:21,256 - freqtrade.freqtradebot - WARNING - Unable to place order Insufficient funds to create market sell order on market SOL/USDT. Tried to sell amount 2.099 at rate 171.02.Message: bybit {"retCode":170131,"retMsg":"Insufficient balance.","result":{},"retExtInfo":{},"time":1729729221221}.
2024-10-24 00:20:21,256 - freqtrade.freqtradebot - INFO - Trying to refind lost order for Trade(id=1, pair=SOL/USDT, amount=2.09900000, is_short=False, leverage=1.0, open_rate=161.62000000, open_since=2024-10-21 13:55:01)
2024-10-24 00:20:21,257 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=1, trade=1, order_id=1801729565325008384, side=buy, filled=2.102, price=161.62, status=closed, date=2024-10-21 13:55:01)
2024-10-24 00:20:26,099 - freqtrade.freqtradebot - INFO - Exit for SOL/USDT detected. Reason: custom_exit
  ```

**Comment by xmatthias** [comment] 2024-10-24 04:13
I'm pretty certain it's not caused by the main account - though i'd suggest to use a subaccount nonetheless.
It'll give you more control - and allows you to eventually use multiple parallel bots (one per subaccount).

The error is pretty telling - as in "the exchange tells us - there's not enough money in the account".


To look into this further, please enable `"log_responses" : true` in the `exchange` section of your configuration and provide us with the logs once the error repeates.

It'll also be helpful to have more logs - the provided logs only really show the effect - not necessarily the cause.

**Comment by kennylbj** [comment] 2024-10-24 07:05
I've switched the order type to `limit` and the order has been processed correctly, so I can't repeat the error message again.

One thing I can make sure is that the account did have sufficient balance for trading.

I can provide the full logs of the previous bot

```
2024-10-16 12:58:27,567 - freqtrade.loggers - INFO - Verbosity set to 0
2024-10-16 12:58:27,567 - freqtrade.configuration.configuration - INFO - Runmode set to live.
2024-10-16 12:58:27,567 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
2024-10-16 12:58:27,567 - freqtrade.configuration.configuration - INFO - Dry run is disabled
2024-10-16 12:58:27,567 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/tradesv3.sqlite"
2024-10-16 12:58:27,567 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 1 ...
2024-10-16 12:58:27,573 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
2024-10-16 12:58:27,573 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/bybit ...
2024-10-16 12:58:27,574 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
2024-10-16 12:58:27,580 - freqtrade.exchange.check_exchange - INFO - Exchange "bybit" is officially supported by the Freqtrade development team.
2024-10-16 12:58:27,580 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2024-10-16 12:58:27,658 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy Buy_The_Dip from '/freqtrade/user_data/strategies/Buy_The_Dip.py'...
2024-10-16 12:58:27,659 - freqtrade.strategy.hyper - INFO - Found no parameter file.
2024-10-16 12:58:27,659 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'entry': 'market', 'exit': 'market', 'stoploss': 'limit', 'stoploss_on_exchange': False}.
2024-10-16 12:58:27,660 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2024-10-16 12:58:27,660 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: unlimited.
2024-10-16 12:58:27,660 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'entry': 5, 'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}.
2024-10-16 12:58:27,660 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'max_open_trades' with value in config file: 1.
2024-10-16 12:58:27,660 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'0': 0.2}
2024-10-16 12:58:27,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using timeframe: 5m
2024-10-16 12:58:27,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.99
2024-10-16 12:58:27,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2024-10-16 12:58:27,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2024-10-16 12:58:27,661 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2024-10-16 12:58:27,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_custom_stoploss: False
2024-10-16 12:58:27,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: True
2024-10-16 12:58:27,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'entry': 'market', 'exit': 'market', 'stoploss': 'limit', 'stoploss_on_exchange': False}
2024-10-16 12:58:27,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'entry': 'GTC', 'exit': 'GTC'}
2024-10-16 12:58:27,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2024-10-16 12:58:27,662 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: unlimited
2024-10-16 12:58:27,663 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using protections: []
2024-10-16 12:58:27,663 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 92
2024-10-16 12:58:27,663 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'entry': 5, 'exit': 5, 'exit_timeout_count': 0, 'unit': 'minutes'}
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_exit_signal: True
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_only: False
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_entry_signal: False
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using exit_profit_offset: 0.0
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using disable_dataframe_checks: False
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_buying_expired_candle_after: 0
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using position_adjustment_enable: True
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_entry_position_adjustment: 8
2024-10-16 12:58:27,664 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using max_open_trades: 1
2024-10-16 12:58:27,664 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2024-10-16 12:58:27,667 - freqtrade.exchange.exchange - INFO - Using CCXT 4.4.6
2024-10-16 12:58:27,667 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'spot'}}
2024-10-16 12:58:27,672 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'spot'}}
2024-10-16 12:58:27,678 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'spot'}}
2024-10-16 12:58:27,684 - freqtrade.exchange.exchange - INFO - Using Exchange "Bybit"
2024-10-16 12:58:30,125 - freqtrade.exchange.bybit - INFO - Bybit: Unified account. Assuming dedicated subaccount for this bot.
2024-10-16 12:58:30,126 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Bybit'...
2024-10-16 12:58:30,295 - freqtrade.wallets - INFO - Wallets synced.
2024-10-16 12:58:30,357 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2024-10-16 12:58:30,482 - freqtrade.rpc.telegram - INFO - using custom keyboard from config.json: [['/daily', '/profit', '/balance'], ['/status', '/status table', '/trades'], ['/whitelist', '/blacklist', '/logs', '/help']]
2024-10-16 12:58:30,482 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.api_server
2024-10-16 12:58:30,608 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forceexit', 'forcesell', 'fx'], ['forcebuy', 'forcelong'], ['forceshort'], ['reload_trade'], ['trades'], ['delete'], ['cancel_open_order', 'coo'], ['performance'], ['buys', 'entries'], ['exits', 'sells'], ['mix_tags'], ['stats'], ['daily'], ['weekly'], ['monthly'], ['count'], ['locks'], ['delete_locks', 'unlock'], ['reload_conf', 'reload_config'], ['show_conf', 'show_config'], ['stopbuy', 'stopentry'], ['whitelist'], ['blacklist'], ['bl_delete', 'blacklist_delete'], ['logs'], ['edge'], ['health'], ['help'], ['version'], ['marketdir'], ['order'], ['list_custom_data']]
2024-10-16 12:58:30,738 - freqtrade.rpc.api_server.webserver - INFO - Starting HTTP Server at 0.0.0.0:8081
2024-10-16 12:58:30,739 - freqtrade.rpc.api_server.webserver - INFO - Starting Local Rest Server.
2024-10-16 12:58:30,744 - uvicorn.error - INFO - Started server process [1]
2024-10-16 12:58:30,744 - uvicorn.error - INFO - Waiting for application startup.
2024-10-16 12:58:30,745 - uvicorn.error - INFO - Application startup complete.
2024-10-16 12:58:30,745 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
2024-10-16 12:58:30,753 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/freqtrade/freqtrade/plugins/pairlist/StaticPairList.py'...
2024-10-16 12:58:30,758 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 3 pairs: ['BTC/USDT', 'ETH/USDT', 'SOL/USDT']
2024-10-16 12:58:30,759 - freqtrade.strategy.hyper - INFO - Strategy Parameter: base_profit_deviation = 0.04
2024-10-16 12:58:30,759 - freqtrade.strategy.hyper - INFO - Strategy Parameter: profit_factor = 1.16
2024-10-16 12:58:30,759 - freqtrade.strategy.hyper - INFO - Strategy Parameter: stake_factor = 1.1
2024-10-16 12:58:30,759 - freqtrade.strategy.hyper - INFO - No params for sell found, using default values.
2024-10-16 12:58:30,759 - freqtrade.strategy.hyper - INFO - No params for protection found, using default values.
2024-10-16 12:58:30,760 - freqtrade.plugins.protectionmanager - INFO - No protection Handlers defined.
2024-10-16 12:58:30,760 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2024-10-16 12:58:30,760 - freqtrade.worker - INFO - Changing state to: RUNNING
2024-10-16 12:58:30,773 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `bybit`\n*Stake per trade:* `unlimited USDT`\n*Minimum ROI:* `{'0': 0.2}`\n*Stoploss:* `-0.99`\n*Position adjustment:* `On`\n*Timeframe:* `5m`\n*Strategy:* `Buy_The_Dip`"}
2024-10-16 12:58:30,775 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for USDT pairs to buy and sell based on [{'StaticPairList': 'StaticPairList'}]"}
2024-10-16 12:58:30,782 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2024-10-16 12:58:31,468 - telegram.ext.Application - INFO - Application started
2024-10-16 12:58:35,782 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.9', state='RUNNING'

... same logs here

2024-10-23 19:03:56,006 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.9', state='RUNNING'
2024-10-23 19:04:56,008 - freqtrade.worker - INFO - Bot heartbeat. PID=1, version='2024.9', state='RUNNING'
2024-10-23 19:05:01,238 - freqtrade.freqtradebot - INFO - Exit for SOL/USDT detected. Reason: custom_exit
2024-10-23 19:05:01,330 - freqtrade.wallets - INFO - Wallets synced.
2024-10-23 19:05:01,423 - freqtrade.freqtradebot - WARNING - Unable to place order Insufficient funds to create market sell order on market SOL/USDT. Tried to sell amount 2.099 at rate 171.13.Message: bybit {"retCode":170131,"retMsg":"Insufficient balance.","result":{},"retExtInfo":{},"time":1729710301388}.
2024-10-23 19:05:01,423 - freqtrade.freqtradebot - INFO - Trying to refind lost order for Trade(id=1, pair=SOL/USDT, amount=2.09900000, is_short=False, leverage=1.0, open_rate=161.62000000, open_since=2024-10-21 13:55:01)
2024-10-23 19:05:01,423 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=1, trade=1, order_id=1801729565325008384, side=buy, filled=2.102, price=161.62, status=closed, date=2024-10-21 13:55:01)
2024-10-23 19:05:06,107 - freqtrade.freqtradebot - INFO - Exit for SOL/USDT detected. Reason: custom_exit
2024-10-23 19:05:06,194 - freqtrade.wallets - INFO - Wallets synced.
2024-10-23 19:05:06,284 - freqtrade.freqtradebot - WARNING - Unable to place order Insufficient funds to create market sell order on market SOL/USDT. Tried to sell amount 2.099 at rate 171.18.Message: bybit {"retCode":170131,"retMsg":"Insufficient balance.","result":{},"retExtInfo":{},"time":1729710306249}.
2024-10-23 19:05:06,284 - freqtrade.freqtradebot - INFO - Trying to refind lost order for Trade(id=1, pair=SOL/USDT, amount=2.09900000, is_short=False, leverage=1.0, open_rate=161.62000000, open_since=2024-10-21 13:55:01)
2024-10-23 19:05:06,284 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=1, trade=1, order_id=1801729565325008384, side=buy, filled=2.102, price=161.62, status=closed, date=2024-10-21 13:55:01)
2024-10-23 19:05:11,111 - freqtrade.freqtradebot - INFO - Exit for SOL/USDT detected. Reason: custom_exit
2024-10-23 19:05:11,193 - freqtrade.wallets - INFO - Wallets synced.
2024-10-23 19:05:11,279 - freqtrade.freqtradebot - WARNING - Unable to place order Insufficient funds to create market sell order on market SOL/USDT. Tried to sell amount 2.099 at rate 171.05.Message: bybit {"retCode":170131,"retMsg":"Insufficient balance.","result":{},"retExtInfo":{},"time":1729710311244}.
2024-10-23 19:05:11,279 - freqtrade.freqtradebot - INFO - Trying to refind lost order for Trade(id=1, pair=SOL/USDT, amount=2.09900000, is_short=False, leverage=1.0, open_rate=161.62000000, open_since=2024-10-21 13:55:01)
2024-10-23 19:05:11,279 - freqtrade.freqtradebot - INFO - Trying to refind Order(id=1, trade=1, order_id=1801729565325008384, side=buy, filled=2.102, price=161.62, status=closed, date=2024-10-21 13:55:01)
2024-10-23 19:05:16,105 - freqtrade.freqtradebot - INFO - Exit for SOL/USDT detected. Reason: custom_exit

...repeat error forever
```

**Comment by xmatthias** [comment] 2024-10-27 12:57
Nice spot - i've been able to reproduce this and fix it - so starting with the linked commit (which will close this issue) - this will be fixed.

**Closed as completed** 2024-10-27 18:46 UTC
Labels: Bug

**Comment by vsebastiaan** [comment] 2024-11-01 18:24
2024-11-01 19:19:30 ERROR   uvicorn.error - Exception in ASGI application

Traceback (most recent call last):
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\freq7\freqtrade\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\freqtrade\rpc\api_server\api_v1.py", line 257, in forceexit
    return rpc._rpc_force_exit(str(payload.tradeid), ordertype, amount=payload.amount)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\freqtrade\rpc\rpc.py", line 934, in _rpc_force_exit
    result = self.__exec_force_exit(trade, ordertype, amount)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\freqtrade\rpc\rpc.py", line 896, in __exec_force_exit
    self._freqtrade.execute_trade_exit(
  File "C:\freq7\freqtrade\freqtrade\freqtradebot.py", line 1987, in execute_trade_exit
    amount = self._safe_exit_amount(trade, trade.pair, sub_trade_amt or trade.amount)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\freq7\freqtrade\freqtrade\freqtradebot.py", line 1924, in _safe_exit_amount
    raise DependencyException(
freqtrade.exceptions.DependencyException: Not enough amount to exit trade. Trade-amount: 9.91, Wallet: 0.00515


this happens after the fix is set in exchange.py

end seems to be triggert by forceexit market 
limit does not seem te work as well.
