### ISSUE TITLE
enter_long == 1 ,but no order has been placed, sometime work, sometimes not.

### ISSUE THREAD

**Issue by thunderwin** [freqtrade/freqtrade#8527] opened 2023-04-20 10:21 UTC
## Describe your environment

  * Operating system: ____ubuntu 20.1
  * Python Version: _____ Python 3.8.10
  * Freqtrade Version: ____ freqtrade 2023.3
  
## Your question

startup_candle_count will fetch a historical candle? 

"Because I need my bot to trade as soon as it gets the pair list, but at the same time, I also need to rely on the MACD indicator for trading, 
what should I do?"

**Comment by stash86** [comment] 2023-04-20 11:22
Title and content doesn't match. Content doesn't really explain what the issue is. No trade opened isn't an issue by itself.

**Comment by froggleston** [comment] 2023-04-20 12:08
Please fill out the issue template as provided. We cannot help without clear and precise information about what it is you're trying to do, what you expect, and what you see.

___

Yes, startup_candle_count fetches historical candles.

As for your other question, this is how freqtrade and strategies work. It gets candles for each pair, then processes indicators, then will open trades based on any conditions you set using those indicators, like MACD. Check the freqtrade strategy examples for how to do this.

**Comment by froggleston** [comment] 2023-04-20 12:11
In fact, you've been asked to fill out the template for at least [one previous issue](https://github.com/freqtrade/freqtrade/issues/8475), so am closing this until you provide information as per the issue template.

**Closed as completed by froggleston** 2023-04-20 12:11 UTC
Labels: Question
