### ISSUE TITLE
Telegram Service: What expectations should I have for availability and uptime?

### ISSUE THREAD

**Issue by willwillis** [freqtrade/freqtrade#3574] opened 2020-07-10 00:54 UTC
## Describe your environment

  * Operating system: Arch linux
  * Python Version: Python 3.8.3 
  * CCXT version: ccxt==1.30.48 
  * Freqtrade Version: freqtrade 2020.6 
  
## Your question

I downloaded and installed freqtrade yesterday and everything went relatively smoothly. Thanks to all those that contributed to the documentation :clap: 

Today around 5pm US/Central I noticed that my bot would not respond to /commands. I restarted freqtrade and same results. I restarted my laptop, same results. I've attached the logs here:  [freqtrade.stdout.txt](https://github.com/freqtrade/freqtrade/files/4900160/freqtrade.stdout.txt)

I attempted to connect to telegram websites as well, none of them worked, I tested both from my broadband connection at home as well as over mobile data from my phone and I couldn't access their websites from either device (admittedly both are AT&T FWIW so perhaps not the best test)

I VPN'd over to the UK and was able to start the bot and access Telegram websites with no issues.

**What are you experiences with the Telegram service in this stack? Is it reliable? What sort of up time should I expect? A some regions more prone to service outages than others?**

Thanks!

**Comment by Theagainmen** [comment] 2020-07-10 09:29
Looking at the logs the network is unreachable for you 
`telegram.error.NetworkError: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot1234567890:XXX-removed-XXX/getMe (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc31dc45c40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))`

I myself had never issues with the Telegram services, there was around a month ago an outage of a few hours, but that didn't cause my bot to crash.

Because you say this `I VPN'd over to the UK and was able to start the bot and access Telegram websites with no issues.` I assume you live in a country where Telegram is banned?

**Comment by xmatthias** [comment] 2020-07-10 16:58
wel - it's not about where you live, but where you run the bot. If it's a "monitored" network, it can be problematic.

Generally, i haven't seen many outages of telegram (though they do exist, as with every other service too).
I think the main point here is that it's neither blocking the bot from executing your strategy, nor crashing the bot - it simply limits your ability to control the bot / check it's status.
yes, that's a pain ... but as said, it could (and would) happen with every other provider, too.

"a few" telegram network errors i did see on my bots too, but only on one server - so i suspect that it's the VPS provider that has the problem. Other bots on other providers (and in other countries) work fine.

**Comment by willwillis** [comment] 2020-07-10 17:42
Thanks for the quick replies. 

To clarify, the bot was running from my home network, here in the US, and to my knowledge the network isn't "monitored". It's very possible there was some glitch on my end. Thanks again!

**Comment by willwillis** [comment] 2020-07-10 18:28
Perhaps I closed this prematurely.

I did a fresh install of freqtrade in a new folder, referencing the strategy and config from the previous install. The bot would not start up at first with the same issue, `Failed to establish a new connection: [Errno 101] Network is unreachable'`.

I attempted to start a second time, with identical arguments and it started just fine.

I copied over the old database to the new folder and everything is running smoothly for now.

What I've noticed is that I'm more prone to encounter the `Network is unreachable` error immediately after having shut down the bot (with Control-C from the command line). Is there a more graceful way to shut the bot down? should I issue a `/stop` first from Telegram?

**For future reference, if I have issues with Telegram rate limiting, where in the settings can I set a throttle, or rate limit for the Telegram API?**

Thanks again for the quick responses!

**Comment by xmatthias** [comment] 2020-07-10 19:04
I'm not sure about the "monitored" part (although the above reference was mostly meant for russia, which tried to block telegram in the past).

ISP's around the world are known to monitor traffic (at least DNS requests) - and the US is no exception to that.

----

well you can't set rate-limits for telegram - but `Network is unreachable` is not an error that would come from a rate-limit anyway, so it's not relevant either (and i've never heared of anyone who had problems with telegram rate-limits using freqtrade.

`Network is unreachable` is what it sounds like - telegram-client is unable to reach the telegram servers.

what exactly it is - that's difficult to tell - can be low bandwidth available (which would however also become a problem once you start running freqtrade on live).
Might be a slow DNS resolver - which causes an initial delay, and therefore causes telegram to time out.
- might be a DNS resolver from the ISP - which is pointing you to a telegram server in Australia - which makes everything slow ...


Freqtrade does pass a timeout of 30s to Telegram (default from the telegram library is 10 - so this works for most people) - so your network takes >30 seconds to establish a connection to the telegram servers. 
If you're having connection problems like this, then telegram is just the start, and errors connecting to the exchange will follow very soon (but these errors WILL impact trading / operations).


Either way, it's nothing we will be able to help you with - as it's your network.

the only thing that jumps my mind you might try (i don't think we can do more for this problem though):
* use different DNS settings - not the one provided by the ISP, as these are usually slow (and monitored) - 8.8.8.8 (google) or 1.1.1.1 (Cloudflare)

If that doesn't help - best try using a VPS (which is the recommended way to run the bot in production anyway - as home networks can go down / have problems, while VPS are usually in datacenters with redundant power supply (and other extras).
Cheap VPS servers can be found for 5$ a month (or even less) - and depending on the strategy, freqtrade works like a charm on these.

**Comment by xmatthias** [comment] 2020-07-20 18:00
Will close this as i think the problem you've experienced is tied to your network, not to freqtrade specifically, and there is not much we can do to help with that.

**Closed by xmatthias** 2020-07-20 18:00 UTC
Labels: Question
