### ISSUE TITLE
Create a complete order at once

### ISSUE THREAD

**Issue by bit-storm** [freqtrade/freqtrade#8715] opened 2023-05-31 14:06 UTC
Operating system: linux ubuntu 20
Python Version: 3.8
CCXT version: 2.5.12
Freqtrade Version: 2022.12

I want stop loss, target and order to be created at the same time when the condition is established.

For example, if the conditions are met. Create order at 50% candle price and stop loss and target at high, low price .

Is it possible ?

**Comment by xmatthias** [comment] 2023-05-31 14:57
What you're asking is
a) only partially possible (you can only place stoploss/target order once the initial order fills, before that, you don't own that stake - therefore can't create a sell order without the risk of going short - which regular markets won't allow).
b) duplicate of #7499  

Freqtrade will place a stoploss on exchange order once the initial entering order is filled.
If a target is hit (a regular sell-signal happens) - that stoploss order will be cancelled, and a regular exit order will be placed.

**Closed as completed by xmatthias** 2023-05-31 14:57 UTC
Labels: Duplicate, Question

**Comment by bit-storm** [comment] 2023-05-31 18:37
> What you're asking is a) only partially possible (you can only place stoploss/target order once the initial order fills, before that, you don't own that stake - therefore can't create a sell order without the risk of going short - which regular markets won't allow). b) duplicate of #7499
> 
> Freqtrade will place a stoploss on exchange order once the initial entering order is filled. If a target is hit (a regular sell-signal happens) - that stoploss order will be cancelled, and a regular exit order will be placed.

I have read all the functions in this link:
https://www.freqtrade.io/en/2021.2/strategy-advanced/

But I can't find anything that answers my question.

 I am trading on the lower time frame and need to create the opening price, stop loss and target in real time and accurately.

I have a code that gives me three outputs:

{
Opening price: 22.55
Stop loss: 22.30
Target: 22.77
}

Open an order in this way.
Is there a way for this?

thanks for your response.

**Comment by xmatthias** [comment] 2023-05-31 19:03
You're looking at documentation for a **2 year old** version. what you find there may or may not be accurate, but is almost certainly VERY outdated.

best use the stable version [https://www.freqtrade.io/en/stable/](https://www.freqtrade.io/en/stable/) of the documentation for up to date information - or (if for whatever reason, you don't want to update from your 6 months outdated version, the documentation corresponding to YOUR version).

---

Your question was quite differently stated previously.

With your info, you can probably use a combination of [callbacks](https://www.freqtrade.io/en/latest/strategy-callbacks/) to exit the trades once the desired targets are reached.
look for the `custom_entry_price()` callback - as well as the `custom_exit()` callback (potentially also the `custom_stoploss()` callback).
