### ISSUE TITLE
setup.sh failed to install dev dependencies on macOS Ventura M1 chip

### ISSUE THREAD

**Issue by strawberry-code** [freqtrade/freqtrade#7798] opened 2022-11-26 15:30 UTC
## Describe your environment

  * Operating system: macOS Ventura 13.0
  * Python Version: 3.10.8
  * CCXT version: `pip freeze | grep ccxt` gives me empty output
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When I run `./setup.sh -i` I encounter (the same) problem when I decide to install:

- dependencies for dev 
- plotting dependencies
- dependencies for freqai

### Without problems

Installation options where I get no errors:

```
./setup.sh -i
[...]
Successfully installed pip-22.3.1
Do you want to install dependencies for dev [y/N]? n
Do you want to install plotting dependencies (plotly) [y/N]? n
Do you want to install hyperopt dependencies [y/N]? n
Do you want to install dependencies for freqai [y/N]? n
```

``` 
./setup.sh -i
[...]
Successfully installed pip-22.3.1
Do you want to install dependencies for dev [y/N]? n
Do you want to install plotting dependencies (plotly) [y/N]? n
Do you want to install hyperopt dependencies [y/N]? y
Do you want to install dependencies for freqai [y/N]? n
``` 

### With problems

Installation options where I get the same error, indicated in **Observed Results** section:

```
./setup.sh -i
[...]
Successfully installed pip-22.3.1
Do you want to install dependencies for dev [y/N]? y
Do you want to install plotting dependencies (plotly) [y/N]? n
Do you want to install hyperopt dependencies [y/N]? n
Do you want to install dependencies for freqai [y/N]? n
```

```
./setup.sh -i
[...]
Successfully installed pip-22.3.1
Do you want to install dependencies for dev [y/N]? n
Do you want to install plotting dependencies (plotly) [y/N]? y
Do you want to install hyperopt dependencies [y/N]? n
Do you want to install dependencies for freqai [y/N]? n
```

```
./setup.sh -i
[...]
Successfully installed pip-22.3.1
Do you want to install dependencies for dev [y/N]? n
Do you want to install plotting dependencies (plotly) [y/N]? n
Do you want to install hyperopt dependencies [y/N]? n
Do you want to install dependencies for freqai [y/N]? y
```

### Observed Results:

  **What happened?** The installation with `./setup.sh -i` fails in the aforementioned cases.

  **What did you expect to happen?** The installation with `./setup.sh -i` succeed in all the aforementioned cases.

### Relevant code exceptions or logs

  ```
Collecting lightgbm==3.3.3
  Using cached lightgbm-3.3.3.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qf/7kpp7kws2bs9ljbxdl6vf9480000gn/T/pip-install-jafloyxv/lightgbm_98cd648c94c946e6afcebd1200be3667/setup.py", line 17, in <module>
          from wheel.bdist_wheel import bdist_wheel
      ModuleNotFoundError: No module named 'wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Failed installing dependencies
  ```

Tried by myselft to install `pip3 install lightgbm==3.3.3` and I get the following output:

```
Requirement already satisfied: lightgbm==3.3.3 in /opt/homebrew/lib/python3.10/site-packages (3.3.3)
Requirement already satisfied: scipy in /opt/homebrew/lib/python3.10/site-packages (from lightgbm==3.3.3) (1.9.3)
Requirement already satisfied: scikit-learn!=0.22.0 in /opt/homebrew/lib/python3.10/site-packages (from lightgbm==3.3.3) (1.1.3)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.10/site-packages (from lightgbm==3.3.3) (1.23.5)
Requirement already satisfied: wheel in /opt/homebrew/lib/python3.10/site-packages (from lightgbm==3.3.3) (0.37.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/homebrew/lib/python3.10/site-packages (from scikit-learn!=0.22.0->lightgbm==3.3.3) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in /opt/homebrew/lib/python3.10/site-packages (from scikit-learn!=0.22.0->lightgbm==3.3.3) (1.2.0)

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python3.10 -m pip install --upgrade pip
```

**Comment by xmatthias** [comment] 2022-11-26 16:14
The problem is a faulty installation configuration by lightgbm.

This should be fixed on the develop branch, can you try to switch to that for the installation?

**Comment by strawberry-code** [comment] 2022-11-26 19:03
Your hint solved my issue, thanks!

```
git clone https://github.com/freqtrade/freqtrade
mv freqtrade
git checkout develop
./setup.sh -i
```

Choosing all opts by 'y' now works fine.

**Closed as completed** 2022-11-27 07:04 UTC
Labels: Install, freqAI
