### ISSUE TITLE
running Freqtrade as a system service in Ubuntu

### ISSUE THREAD

**Issue by whatTHEh3ll** [freqtrade/freqtrade#2039] opened 2019-07-20 02:05 UTC
Can you go into a little more depth on how to run Freqtrade as a system service on Ubuntu 18?

**Comment by hroff-1902** [comment] 2019-07-20 07:18
See the description in https://github.com/freqtrade/freqtrade/pull/1648#issue-259776847

**Comment by hroff-1902** [comment] 2019-07-20 08:45
I implemented it several months ago and slightly documented in that pull request, but had no time to make a more wide description in the docs. You can help the project if you reproduce the deployment that uses the system service (and sd-notify) feature and write resulting notes on this that could be inserted into the docs.

**Comment by hroff-1902** [comment] 2019-07-21 00:54
btw, even without sd-notify, freqtrade can run as a systemd service.

This is already described in the docs in detail, see https://www.freqtrade.io/en/latest/installation/#7-optional-configure-freqtrade-as-a-systemd-service.

Have you read it?

**Comment by hroff-1902** [comment] 2019-07-25 23:54
Closing the issue since it was answered.
Feel free to reopen it.

**Closed by hroff-1902** 2019-07-25 23:55 UTC
Labels: install, question
