### ISSUE TITLE
partial fullfilled order and unable to place stop loss 

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2877] opened 2020-02-07 09:50 UTC
Closed to #2011 (but bot don't crash and currency is sold)

Workflow :
- place limit order
- partial fullfilled
- unable to place stop loss limit order
- The logs say : _could not market sell order_ but it seems he succeed to do it has i don't find the currency in the account.
- the bot  loop trying to place limit force sell
- ~~the pair is sold but the database consider trade has open.~~ (edited my error)

```
2020-01-19 01:30:31,701 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Binance', 'pair': 'RLC/USDT', 'limit': 0.5057, 'order_type': 'limit', 'stake_amount': 30, 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
2020-01-19 01:30:32,807 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=26, pair=RLC/USDT, amount=59.32370971, open_rate=0.50570000, open_since=2020-01-19 01:30:31)
2020-01-19 01:40:36,391 - freqtrade.freqtradebot - INFO - Partial buy order timeout for Trade(id=26, pair=RLC/USDT, amount=11.21000000, open_rate=0.50570000, open_since=2020-01-19 01:30:31).
2020-01-19 01:40:36,392 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'Remaining buy order for RLC/USDT cancelled due to timeout'}
2020-01-19 01:40:38,906 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange. Could not create stop_loss_limit sell order on market RLC/USDT. Tried to sell amount 11.21 at rate 0.3505. Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
2020-01-19 01:40:39,905 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Could not create market sell order on market RLC/USDT.Tried to sell amount 11.21 at rate None.Message: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}

```

Have a nice day.

**Comment by xmatthias** [comment] 2020-02-07 10:48
This seems simple at first, but it's not after thinking about it in detail.

The order was partially filled - and the filled amount was too low to be traded thereafter. 

Looking at your account, you should see the order the bot placed - and how much of it filled (11.21).
The amount must still be there (it's not sellable on the exchange, but would require conversation to BNB - assuming binance).

So defining how "correct" behaviour is here is difficult to me. 
Technically, it filled partially - freqtrade does accept that and try will to handle it as any other trade - which works if the amount filled is > min-tradable-amount (based on every limitation, price, cost and amount).

In your case, the amount is too low.
The problem is - simply closing the trade is wrong to me - as the 5 USDT spent are still in RLC (you still own this) - so assuming this happens frequently, you'd experience a "disappearing" stake-currency - without anything other than a few logs contained.

in theory, this is a 100% loss (unless you buy RLC again, and sell it "all" at once).

Your log confirms this in a way
* it seems like the bot bought 59.32370971.
* it then timed out with 11.21 filled (you should have this amount in your account).
* Freqtrade will try to create a stoploss order for the 11.21 (that's what freqtrade "owns").
  * this fails with MIN_NOTIONAL. For this pair, it seems to be cost (11.21 * 0.50xxx < 10) (`'cost': {'min': 10.0, 'max': None}},`)
  * Obviously, the subsequent emergency market sell also fails, because cost is < 10 .

**Comment by hroff-1902** [comment] 2020-02-07 13:07
Binance actually has two types of filterType for lot size: LOT_SIZE and MARKET_LOT_SIZE, which can differ. For some markets, MARKET_LOT_SIZE is 0, so the market order should only be actually checked against MIN_NOTIONAL boundary. Currently ccxt only provide us LOT_SIZE, which is to be considered as a deficiency in their universal API and should be improved.

Maybe this could help selling partially fulfilled positions with market orders, when ccxt will be able to provide us both values in their API.

**Comment by xmatthias** [comment] 2020-02-07 13:20
I'm not sure how that matters here - you can't sell 11 RLC against USDT. 
Not via API, not via web-UI.

CCXT does provide us with this information (minimum cost = 10).

You also can't buy these because the minimum order size is 10 USDT (~20 RLC).
The only way to get these is via unfilled orders - which in the end generate "binance dust".

The only way to sell these 11 RLC without converting to BNB is by buying more RLC - and then selling all at once.

**Comment by gaugau3000** [comment] 2020-02-07 14:19
@xmatthias sorry it not has been sold i don't have seen it because of 'hide low value coin' checked in binance interface.

**Comment by xmatthias** [comment] 2020-02-07 15:42
yeah - that's aligned with the logs / the expectation from the above.

As said - this is a very stupid constellation - and other than using FOC as time_in_force - i don't really know what to recommend / how to handle this.

We might cancel the trade in the database ... but the asset worth almost  5 USDT will remain in your account ... so if this repeats, your balance will slowly start to disappear without a trace (it's been removed from the database after all).

**Comment by gaugau3000** [comment] 2020-02-10 18:58
If i reduce unfilledtimeout to 1 minute then maybe there is more chances to be filled as the signal is still active during the candle it can lead to 15 limit orders and adapt more to market moves (my timeframe is 15 minutes) ?

The problem with fill or kill to with low volume it retry many times and i am pretty sure that i will exceed api cancel order/filled order ratio.

Maybe an another approach by using [dustlog-user_data ](https://binance-docs.github.io/apidocs/spot/en/#dustlog-user_data) is like trading dust to bnb.

Have a nice day.

**Comment by tarek-vader** [comment] 2020-04-19 12:03
i had the exact same problem , which is really annoying, since even if i bought after that manually more of that coint to have more than MIN_NOTIONAL and sell it to market price, freqtrade still keep it
in his database as open trade!

possible solutions:
- freqtrade buy atomatically more of that coin to have at least MIN_NOTIONAL then sell it to market, but it could loose money.
- there should be an feature for freqtrade to /remove_trade which able to remove that trade from db, after that user has handle it manually the way he wants. (optional feature, freqtrade can only remove trades when they are really less than MIN_NOTIONAL, disadvange: more manuall work for user.

**Comment by xmatthias** [comment] 2020-07-24 14:40
I'll close this in favor of #3622.
It's got a "better" title -  and this issue bears the risk to be treated as "bug" - at least if a reader is not reading the whole thread.

**Closed by xmatthias** 2020-07-24 14:40 UTC
Labels: Discussion
