### ISSUE TITLE
Async code raised an exception: CookieError

### ISSUE THREAD

**Issue by patoarvizu** [freqtrade/freqtrade#4356] opened 2021-02-12 05:30 UTC
## Describe your environment

  * Operating system: Ubuntu on Raspberry Pi
  * Python Version: Whatever is on the Docker container
  * CCXT version: Whatever is on the Docker container
  * Freqtrade Version: `freqtradeorg/freqtrade:develop_pi` (I've also tried `stable_pi` and `2021.1_pi`.)

## Describe the problem:

I'm trying to see if I can run freqtrade in a Raspberry Pi Kubernetes cluster. So far I've been able to execute the bot in dry-run mode, but I seem to be running into an issue that makes it basically useless. (I understand that deploying on Kubernetes might not be officially supported yet, but I'm not sure yet if this is a bug on the code, or some incompatibility with Raspberry Pi/Kubernetes that can be addressed later).

If I run with `api_server.enabled: true`, I see a bunch of this in the logs:

```
2021-02-12 04:54:24,590 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: CookieError
2021-02-12 04:54:24,591 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: CookieError
2021-02-12 04:54:24,591 - freqtrade.exchange.exchange - WARNING - Async code raised an exception: CookieError
2021-02-12 04:54:24,594 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair BCH/BTC
2021-02-12 04:54:24,598 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair ETH/BTC
2021-02-12 04:54:24,601 - freqtrade.strategy.interface - WARNING - Empty candle (OHLCV) data for pair XRP/BTC
```
But the warnings go away when I disable the API server.

I seem to have been able to narrow it down to an issue with the request to the exchange API, that looks like it's only happening on the image running on the RPi Kubernetes (I don't see this issue when I run it on a MacBook Pro.

If I turn on max verbosity (`-vvv`), I see for example this on my local machine:
```
ccxt.base.exchange - DEBUG - GET https://api.kraken.com/0/public/Ticker?pair=BCHXBT, Request: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None
```
But running on Kubernetes, I see for example:
```
ccxt.base.exchange - DEBUG - GET https://api.kraken.com/0/public/OHLC?pair=XETHXXBT&interval=5, Request: None None
```

It looks like the request on the Kubernetes container doesn't have a `User-Agent` header. (I don't know if that's the issue, but it's what I've been able to narrow it down to.)

Kubernetes is only the orchestrator around Docker and at the end of the day, the Docker image should run the same whether it was launched by Kubernetes or not, so I doubt this is being caused by Kubernetes, but I don't discard it either.

### Steps to reproduce:

  1. Have a Kubernetes cluster running on Raspberry Pi (or some other ARM board).
  2. Launch a pod with a container running `freqtrade trade`, using the image `freqtradeorg/freqtrade:develop_pi`.
  3. Follow the logs and notice the warnings.
  
### Observed Results:

  * The warnings seem to continue forever.
  * That the bot only logs its heartbeat or trade information.
  * Note that I am able to log in to the UI, but there is no data, and no trades have happened in about 1 hour (I don't know if that's expected or not).

### Relevant code exceptions or logs

I'm fairly new to the project, so I'm still trying to understand all the options, I hope I gave enough context but I'm happy to expand if needed to.

**Comment by xmatthias** [comment] 2021-02-12 06:59
I doubt kubernetes will have anything to do with - others have observed similar behaviour on a RPI (but i've been unable to recreate this issue).

However, so far, noone has tied it to having the API enabled - so maybe this is something.
Although i still cannot see why this should then behave differently between a raspberry and a regular pc.

**Comment by patoarvizu** [comment] 2021-02-12 15:06
From what I've been able to find out, it looks like this error is coming from `aiohttp`, maybe the ARM package of the library behaves differently from the AMD one?

**Comment by patoarvizu** [comment] 2021-02-13 12:24
Some additional information: I added the following line to get more information on the `CookieError`:
```
logger.warning("Error: %s", res)
```
And the logs show `Error: Attempt to set a reserved key 'SameSite'`.

**Comment by xmatthias** [comment] 2021-02-13 12:44
the problem is - it doesn't explain why it would work on a pc (x86 / x64), but not on a raspberry (arm).

**Comment by xmatthias** [comment] 2021-02-13 13:20
are you able to try this on a "non-docker" installation on a raspberry?

i've just tried without docker - and it seems to work fine there for me.... (make sure to use a 3.7 python, and add the piwheels repository from the docs before installing to avoid waiting until tomorrow...

**Comment by xmatthias** [comment] 2021-02-13 15:46
The most likely cause for this is the following part:

https://github.com/encode/starlette/blob/99b37781eb88cfc2f7064724975ac5d93d623ea7/starlette/responses.py#L17-L18


Since on a raspberry, we're currently using a version < 3.8 (due to piwheels.org not building wheels for 3.8 or 3.9), this might impact only the raspberry image (or people running on a python version < 3.8), but nothing else (at least according to the comment).

It's however strange, as the links used (e.g. https://api.kraken.com/0/public/OHLC?pair=BATEUR&interval=5) don't seem to set a cookie named "SameSite" - at least not when accessed via browser ...

the deeper you dig, the worse it gets it seems ...

in python 3.8:
``` python
In [1]: import aiohttp

In [2]: async with aiohttp.ClientSession() as session:
   ...:     x = await session.get('https://api.kraken.com/0/public/OHLC?pair=BATEUR&interval=5')

In [10]: x.cookies
Out[10]: <SimpleCookie: __cf_bm='257ec628c10bbbec89303ead653ab9935ffad94c-1613232045-1800-ASLopzDS/hveBniepUXG7ZQ6CRXnU+A5i2T6PlimcxViOjMRDlyMWHeAa88gOem7Rfp1LWMotBQfeqS7CpTUGCc=' __cfduid='d1e8a0a8c34e0ab1d2f860a8bcb302a5b1613232045'>

```

in python 3.7:

```
In [3]: import aiohttp

In [6]: async with aiohttp.ClientSession() as session:
   ...:     x = await session.get('https://api.kraken.com/0/public/OHLC?pair=BATEUR&interval=5')

In [8]: x.cookies
Out[8]: <SimpleCookie: SameSite='None' __cf_bm='07c103ddf03f45c24fb0140c108d9768cd431d7e-1613232003-1800-AQxqRPtcOnOwX16H51I4hDatSUjcxMsOA9zCHebJrbLuLiOwMqF42xCFKlujXthik0RuDkkc5faNbhyN5iNxt5g=' __cfduid='db0a9017a83910968938e77f5535a77dc1613232002'>

```

It seems like by simply using python 3.7, `SameSite` is recognized as a cookie, while with 3.8 it's not.

---

I would not know how to fix this from a freqtrade side at the moment - best use it without apiserver from a raspberry, use a proper VPS, or build an ARM image yourself with a newer python version (we can't, as CI will time out if we don't use piwheels).
The main problem is the installation of dependencies, which need to be compiled on the raspberry - compiling numpy and pandas from source can take multiple hours - and causes all CI providers to time out.

piwheels provides a great service for raspberries - but only for 3.7 at the moment - so there's currently no way to upgrade the raspberry image to 3.8 or 3.9.

**Comment by wolet-ft** [comment] 2021-02-13 16:13
I am fine with disabling the api server

**Comment by wolet-ft** [comment] 2021-02-13 16:17
Could this be fixed in ccxt?

**Comment by xmatthias** [comment] 2021-02-13 18:13
i'm not sure - probably not (it's not broken in 3.8 and 3.9).

to me it looks like a bug (or rather missing feature) in python3.7 - but it's rather unlikely to get that properly fixed ... 

I'll sleep about it a few days, maybe i have an inspiration on how this coudl be fixed ...

**Comment by wolet-ft** [comment] 2021-02-13 18:46
Thank you!

**Closed as completed** 2021-02-14 06:23 UTC
Labels: Triage Needed

**Comment by xmatthias** [comment] 2021-02-14 06:26
Found a fix by simply replicating the starlette fix in the exchange class.

since we load starlette / api server after the exchange, their fix is injected "too late" - where ccxt already created a (now unlinked) instance.
Simply copying the starlette code over seems to work just fine and cause no further problems.

**Comment by patoarvizu** [comment] 2021-02-15 02:08
Awesome! 👍
