### ISSUE TITLE
Exclude/Include tokens to be analysed/buy

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#3595] opened 2020-07-15 11:55 UTC
As a trader
I want to exclude/include leveraged token to be buy
So that i am sure my strategy don't mix markets with different volatility/behavior.

I don't know how it can be implemented.

Maybe allow regex in pair_whitelist, pair_blacklist and do smt like "*BULL*,*BEAR*,*UP*,*DOWN*"

When i ask the question in ccxt repo there was no unify way to filter that :
https://github.com/ccxt/ccxt/issues/6481

Have a nice day

**Comment by xmatthias** [comment] 2020-07-15 17:04
there ain't one here either - as the names will be different per exchange (just look at FTX- which also has a "Half" (without bear / bull / up / down though).

Best search for them on the exchange, and add each of the ones to your blacklist.
It' won't be too many as they'll usually be for BTC and ETH only (haven't seen many others, at least not on binance).


I do the same with the "FIAT/FIAT" pairs (like USDC/USDT) - as they have virtually no movement - so be "forever open" trades (obviously depending on the config).

**Comment by gaugau3000** [comment] 2020-07-16 17:58
Hi,

> Best search for them on the exchange, and add each of the ones to your blacklist.

The problem is that binance and ftx had new tokens and i used volumePairList :-) and i don't want to reload config. Yes in can list all crypto coins and make a blacklist but if there is new ones i have no solution.

-> it is why allow a wildcard (regex) can manage this like (*BULL, ...) (the asterisk has been removed by github in previous message) 

Have a nice day.

**Comment by xmatthias** [comment] 2020-07-16 19:29
You cant predict the name of new coins, and assuming all leveraged tokens will be called xxxBULL (or something else youre suspecting) is dangerous.

You could however use Agefilter, so you only have to deal with new tokens every few 100 days.

**Comment by gaugau3000** [comment] 2020-07-20 05:58
> You cant predict the name of new coins,
>  and assuming all leveraged tokens will be called xxxBULL (or something else youre suspecting) is dangerous amd will fail eventually.

I know binance use UP/DOWN so i put *UP/USDT and *DOWN/USDT in my backlist for binance. I know that FTX use *BULL/USD and */BEAR/USD so i put in my blacklist for ftx etc. that's all. So i don't make hypothesis :-).

> You could however use Agefilter, so you only have to deal with new tokens every few 100 days.

yes but it is a workaround from what i tried to achieve and i don't want to wait 100 days to trade a new market only not to introduce new leveraged token.

Have a nice day.

**Comment by hroff-1902** [comment] 2020-07-20 21:05
not achievable till ccxt will provide this info in a unified way (which is also not achievable I guess)

**Comment by xmatthias** [comment] 2020-07-25 17:33
well, ccxt will most likely not provide this info (as exchanges don't provide this info ...).

However, i think this can be solved by allowing wildcards (also in blacklist) - which somehow makes this a duplicate of #3240 - more specifically of https://github.com/freqtrade/freqtrade/issues/3240#issuecomment-629653991.

**Comment by hroff-1902** [comment] 2020-07-25 19:03
I'm working on it btw (allow wildchars in the pair names, including informative pairs)

**Closed** 2020-12-31 09:02 UTC
Labels: Pairlist

**Comment by gaugau3000** [comment] 2023-03-30 22:18
Coin be done using coingecko :

https://github.com/ccxt/ccxt/issues/6481#issuecomment-1491040022
