### ISSUE TITLE
Binance No market symbol VTHO/BTC

### ISSUE THREAD

**Issue by vpotap** [freqtrade/freqtrade#1111] opened 2018-08-01 21:03 UTC
Telegram /balance doesn't work after VTHO Airdrop for VET Holders

freqtrade/exchange/__init__.py", line 325, in get_ticker
    f'Could not load ticker history due to {e.__class__.__name__}. Message: {e}')
freqtrade.TemporaryError: Could not load ticker history due to ExchangeError. Message: binance No market symbol VTHO/BTC

**Comment by xmatthias** [comment] 2018-08-01 22:11
Has the bot been running for longer than a day? 
If so, please restart the bot and the new coin should be loaded in markets.

Please note that using a brandnew coin right away is dangerous as it has no history a strategy can be based on #1067, and depending on the indicators used having no/not enough history can lead to flucky buy signals

**Comment by vpotap** [comment] 2018-08-02 08:49
bot was restarted, altcoin not defined in whitelist at all (not for trading) , telegram rpc /balance cant' retrieve

**Comment by creslinux** [comment] 2018-08-02 09:59
The handy script below can be called as `python <script_name> <exchangename>` and will list all pairs the exchange has. 

as example `python get_market_pairs.py binance ` to see all markets on binance

This returns no VHTO, so either its not in binance api yet, or CCXT has a bug not returning it. 

```
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


def style(s, style):
    return style + s + '\033[0m'


def green(s):
    return style(s, '\033[92m')


def blue(s):
    return style(s, '\033[94m')


def yellow(s):
    return style(s, '\033[93m')


def red(s):
    return style(s, '\033[91m')


def pink(s):
    return style(s, '\033[95m')


def bold(s):
    return style(s, '\033[1m')


def underline(s):
    return style(s, '\033[4m')


def dump(*args):
    print(' '.join([str(arg) for arg in args]))


def print_supported_exchanges():
    dump('Supported exchanges:', green(', '.join(ccxt.exchanges)))


try:

    id = sys.argv[1]  # get exchange id from command line arguments


    # check if the exchange is supported by ccxt
    exchange_found = id in ccxt.exchanges

    if exchange_found:
        dump('Instantiating', green(id), 'exchange')

        # instantiate the exchange by id
        exchange = getattr(ccxt, id)({
            # 'proxy':'https://cors-anywhere.herokuapp.com/',
        })

        # load all markets from the exchange
        markets = exchange.load_markets()

        # output a list of all market symbols
        dump(green(id), 'has', len(exchange.symbols), 'symbols:', exchange.symbols)

        tuples = list(ccxt.Exchange.keysort(markets).items())

        # debug
        for (k, v) in tuples:
            print(v)

        # output a table of all markets
        dump(pink('{:<15} {:<15} {:<15} {:<15}'.format('id', 'symbol', 'base', 'quote')))

        for (k, v) in tuples:
            dump('{:<15} {:<15} {:<15} {:<15}'.format(v['id'], v['symbol'], v['base'], v['quote']))

    else:

        dump('Exchange ' + red(id) + ' not found')
        print_supported_exchanges()

except Exception as e:
    dump('[' + type(e).__name__ + ']', str(e))
    dump("Usage: python " + sys.argv[0], green('id'))
    print_supported_exchanges()
``

**Comment by creslinux** [comment] 2018-08-02 10:00
excessive output but for info
```
id              symbol          base            quote          
ADABNB          ADA/BNB         ADA             BNB            
ADABTC          ADA/BTC         ADA             BTC            
ADAETH          ADA/ETH         ADA             ETH            
ADAUSDT         ADA/USDT        ADA             USDT           
ADXBNB          ADX/BNB         ADX             BNB            
ADXBTC          ADX/BTC         ADX             BTC            
ADXETH          ADX/ETH         ADX             ETH            
AEBNB           AE/BNB          AE              BNB            
AEBTC           AE/BTC          AE              BTC            
AEETH           AE/ETH          AE              ETH            
AGIBNB          AGI/BNB         AGI             BNB            
AGIBTC          AGI/BTC         AGI             BTC            
AGIETH          AGI/ETH         AGI             ETH            
AIONBNB         AION/BNB        AION            BNB            
AIONBTC         AION/BTC        AION            BTC            
AIONETH         AION/ETH        AION            ETH            
AMBBNB          AMB/BNB         AMB             BNB            
AMBBTC          AMB/BTC         AMB             BTC            
AMBETH          AMB/ETH         AMB             ETH            
APPCBNB         APPC/BNB        APPC            BNB            
APPCBTC         APPC/BTC        APPC            BTC            
APPCETH         APPC/ETH        APPC            ETH            
ARDRBNB         ARDR/BNB        ARDR            BNB            
ARDRBTC         ARDR/BTC        ARDR            BTC            
ARDRETH         ARDR/ETH        ARDR            ETH            
ARKBTC          ARK/BTC         ARK             BTC            
ARKETH          ARK/ETH         ARK             ETH            
ARNBTC          ARN/BTC         ARN             BTC            
ARNETH          ARN/ETH         ARN             ETH            
ASTBTC          AST/BTC         AST             BTC            
ASTETH          AST/ETH         AST             ETH            
BATBNB          BAT/BNB         BAT             BNB            
BATBTC          BAT/BTC         BAT             BTC            
BATETH          BAT/ETH         BAT             ETH            
BCDBTC          BCD/BTC         BCD             BTC            
BCDETH          BCD/ETH         BCD             ETH            
BCCBNB          BCH/BNB         BCH             BNB            
BCCBTC          BCH/BTC         BCH             BTC            
BCCETH          BCH/ETH         BCH             ETH            
BCCUSDT         BCH/USDT        BCH             USDT           
BCNBNB          BCN/BNB         BCN             BNB            
BCNBTC          BCN/BTC         BCN             BTC            
BCNETH          BCN/ETH         BCN             ETH            
BCPTBNB         BCPT/BNB        BCPT            BNB            
BCPTBTC         BCPT/BTC        BCPT            BTC            
BCPTETH         BCPT/ETH        BCPT            ETH            
BLZBNB          BLZ/BNB         BLZ             BNB            
BLZBTC          BLZ/BTC         BLZ             BTC            
BLZETH          BLZ/ETH         BLZ             ETH            
BNBBTC          BNB/BTC         BNB             BTC            
BNBETH          BNB/ETH         BNB             ETH            
BNBUSDT         BNB/USDT        BNB             USDT           
BNTBTC          BNT/BTC         BNT             BTC            
BNTETH          BNT/ETH         BNT             ETH            
BQXBTC          BQX/BTC         BQX             BTC            
BQXETH          BQX/ETH         BQX             ETH            
BRDBNB          BRD/BNB         BRD             BNB            
BRDBTC          BRD/BTC         BRD             BTC            
BRDETH          BRD/ETH         BRD             ETH            
BTCUSDT         BTC/USDT        BTC             USDT           
BTGBTC          BTG/BTC         BTG             BTC            
BTGETH          BTG/ETH         BTG             ETH            
BTSBNB          BTS/BNB         BTS             BNB            
BTSBTC          BTS/BTC         BTS             BTC            
BTSETH          BTS/ETH         BTS             ETH            
CDTBTC          CDT/BTC         CDT             BTC            
CDTETH          CDT/ETH         CDT             ETH            
CHATBTC         CHAT/BTC        CHAT            BTC            
CHATETH         CHAT/ETH        CHAT            ETH            
CLOAKBTC        CLOAK/BTC       CLOAK           BTC            
CLOAKETH        CLOAK/ETH       CLOAK           ETH            
CMTBNB          CMT/BNB         CMT             BNB            
CMTBTC          CMT/BTC         CMT             BTC            
CMTETH          CMT/ETH         CMT             ETH            
CNDBNB          CND/BNB         CND             BNB            
CNDBTC          CND/BTC         CND             BTC            
CNDETH          CND/ETH         CND             ETH            
CVCBNB          CVC/BNB         CVC             BNB            
CVCBTC          CVC/BTC         CVC             BTC            
CVCETH          CVC/ETH         CVC             ETH            
DASHBTC         DASH/BTC        DASH            BTC            
DASHETH         DASH/ETH        DASH            ETH            
DATABTC         DATA/BTC        DATA            BTC            
DATAETH         DATA/ETH        DATA            ETH            
DENTBTC         DENT/BTC        DENT            BTC            
DENTETH         DENT/ETH        DENT            ETH            
DGDBTC          DGD/BTC         DGD             BTC            
DGDETH          DGD/ETH         DGD             ETH            
DLTBNB          DLT/BNB         DLT             BNB            
DLTBTC          DLT/BTC         DLT             BTC            
DLTETH          DLT/ETH         DLT             ETH            
DNTBTC          DNT/BTC         DNT             BTC            
DNTETH          DNT/ETH         DNT             ETH            
DOCKBTC         DOCK/BTC        DOCK            BTC            
DOCKETH         DOCK/ETH        DOCK            ETH            
EDOBTC          EDO/BTC         EDO             BTC            
EDOETH          EDO/ETH         EDO             ETH            
ELFBTC          ELF/BTC         ELF             BTC            
ELFETH          ELF/ETH         ELF             ETH            
ENGBTC          ENG/BTC         ENG             BTC            
ENGETH          ENG/ETH         ENG             ETH            
ENJBNB          ENJ/BNB         ENJ             BNB            
ENJBTC          ENJ/BTC         ENJ             BTC            
ENJETH          ENJ/ETH         ENJ             ETH            
EOSBNB          EOS/BNB         EOS             BNB            
EOSBTC          EOS/BTC         EOS             BTC            
EOSETH          EOS/ETH         EOS             ETH            
EOSUSDT         EOS/USDT        EOS             USDT           
ETCBNB          ETC/BNB         ETC             BNB            
ETCBTC          ETC/BTC         ETC             BTC            
ETCETH          ETC/ETH         ETC             ETH            
ETCUSDT         ETC/USDT        ETC             USDT           
ETHBTC          ETH/BTC         ETH             BTC            
ETHUSDT         ETH/USDT        ETH             USDT           
EVXBTC          EVX/BTC         EVX             BTC            
EVXETH          EVX/ETH         EVX             ETH            
FUELBTC         FUEL/BTC        FUEL            BTC            
FUELETH         FUEL/ETH        FUEL            ETH            
FUNBTC          FUN/BTC         FUN             BTC            
FUNETH          FUN/ETH         FUN             ETH            
GASBTC          GAS/BTC         GAS             BTC            
GNTBNB          GNT/BNB         GNT             BNB            
GNTBTC          GNT/BTC         GNT             BTC            
GNTETH          GNT/ETH         GNT             ETH            
GRSBTC          GRS/BTC         GRS             BTC            
GRSETH          GRS/ETH         GRS             ETH            
GTOBNB          GTO/BNB         GTO             BNB            
GTOBTC          GTO/BTC         GTO             BTC            
GTOETH          GTO/ETH         GTO             ETH            
GVTBTC          GVT/BTC         GVT             BTC            
GVTETH          GVT/ETH         GVT             ETH            
GXSBTC          GXS/BTC         GXS             BTC            
GXSETH          GXS/ETH         GXS             ETH            
HOTBTC          HOT/BTC         HOT             BTC            
HOTETH          HOT/ETH         HOT             ETH            
HSRBTC          HSR/BTC         HSR             BTC            
HSRETH          HSR/ETH         HSR             ETH            
ICNBTC          ICN/BTC         ICN             BTC            
ICNETH          ICN/ETH         ICN             ETH            
ICXBNB          ICX/BNB         ICX             BNB            
ICXBTC          ICX/BTC         ICX             BTC            
ICXETH          ICX/ETH         ICX             ETH            
ICXUSDT         ICX/USDT        ICX             USDT           
INSBTC          INS/BTC         INS             BTC            
INSETH          INS/ETH         INS             ETH            
IOSTBTC         IOST/BTC        IOST            BTC            
IOSTETH         IOST/ETH        IOST            ETH            
IOTABNB         IOTA/BNB        IOTA            BNB            
IOTABTC         IOTA/BTC        IOTA            BTC            
IOTAETH         IOTA/ETH        IOTA            ETH            
IOTAUSDT        IOTA/USDT       IOTA            USDT           
IOTXBTC         IOTX/BTC        IOTX            BTC            
IOTXETH         IOTX/ETH        IOTX            ETH            
KEYBTC          KEY/BTC         KEY             BTC            
KEYETH          KEY/ETH         KEY             ETH            
KMDBTC          KMD/BTC         KMD             BTC            
KMDETH          KMD/ETH         KMD             ETH            
KNCBTC          KNC/BTC         KNC             BTC            
KNCETH          KNC/ETH         KNC             ETH            
LENDBTC         LEND/BTC        LEND            BTC            
LENDETH         LEND/ETH        LEND            ETH            
LINKBTC         LINK/BTC        LINK            BTC            
LINKETH         LINK/ETH        LINK            ETH            
LOOMBNB         LOOM/BNB        LOOM            BNB            
LOOMBTC         LOOM/BTC        LOOM            BTC            
LOOMETH         LOOM/ETH        LOOM            ETH            
LRCBTC          LRC/BTC         LRC             BTC            
LRCETH          LRC/ETH         LRC             ETH            
LSKBNB          LSK/BNB         LSK             BNB            
LSKBTC          LSK/BTC         LSK             BTC            
LSKETH          LSK/ETH         LSK             ETH            
LTCBNB          LTC/BNB         LTC             BNB            
LTCBTC          LTC/BTC         LTC             BTC            
LTCETH          LTC/ETH         LTC             ETH            
LTCUSDT         LTC/USDT        LTC             USDT           
LUNBTC          LUN/BTC         LUN             BTC            
LUNETH          LUN/ETH         LUN             ETH            
MANABTC         MANA/BTC        MANA            BTC            
MANAETH         MANA/ETH        MANA            ETH            
MCOBNB          MCO/BNB         MCO             BNB            
MCOBTC          MCO/BTC         MCO             BTC            
MCOETH          MCO/ETH         MCO             ETH            
MDABTC          MDA/BTC         MDA             BTC            
MDAETH          MDA/ETH         MDA             ETH            
MFTBNB          MFT/BNB         MFT             BNB            
MFTBTC          MFT/BTC         MFT             BTC            
MFTETH          MFT/ETH         MFT             ETH            
MODBTC          MOD/BTC         MOD             BTC            
MODETH          MOD/ETH         MOD             ETH            
MTHBTC          MTH/BTC         MTH             BTC            
MTHETH          MTH/ETH         MTH             ETH            
MTLBTC          MTL/BTC         MTL             BTC            
MTLETH          MTL/ETH         MTL             ETH            
NANOBNB         NANO/BNB        NANO            BNB            
NANOBTC         NANO/BTC        NANO            BTC            
NANOETH         NANO/ETH        NANO            ETH            
NASBNB          NAS/BNB         NAS             BNB            
NASBTC          NAS/BTC         NAS             BTC            
NASETH          NAS/ETH         NAS             ETH            
NAVBNB          NAV/BNB         NAV             BNB            
NAVBTC          NAV/BTC         NAV             BTC            
NAVETH          NAV/ETH         NAV             ETH            
NCASHBNB        NCASH/BNB       NCASH           BNB            
NCASHBTC        NCASH/BTC       NCASH           BTC            
NCASHETH        NCASH/ETH       NCASH           ETH            
NEBLBNB         NEBL/BNB        NEBL            BNB            
NEBLBTC         NEBL/BTC        NEBL            BTC            
NEBLETH         NEBL/ETH        NEBL            ETH            
NEOBNB          NEO/BNB         NEO             BNB            
NEOBTC          NEO/BTC         NEO             BTC            
NEOETH          NEO/ETH         NEO             ETH            
NEOUSDT         NEO/USDT        NEO             USDT           
NPXSBTC         NPXS/BTC        NPXS            BTC            
NPXSETH         NPXS/ETH        NPXS            ETH            
NULSBNB         NULS/BNB        NULS            BNB            
NULSBTC         NULS/BTC        NULS            BTC            
NULSETH         NULS/ETH        NULS            ETH            
NULSUSDT        NULS/USDT       NULS            USDT           
NXSBNB          NXS/BNB         NXS             BNB            
NXSBTC          NXS/BTC         NXS             BTC            
NXSETH          NXS/ETH         NXS             ETH            
OAXBTC          OAX/BTC         OAX             BTC            
OAXETH          OAX/ETH         OAX             ETH            
OMGBTC          OMG/BTC         OMG             BTC            
OMGETH          OMG/ETH         OMG             ETH            
ONTBNB          ONT/BNB         ONT             BNB            
ONTBTC          ONT/BTC         ONT             BTC            
ONTETH          ONT/ETH         ONT             ETH            
ONTUSDT         ONT/USDT        ONT             USDT           
OSTBNB          OST/BNB         OST             BNB            
OSTBTC          OST/BTC         OST             BTC            
OSTETH          OST/ETH         OST             ETH            
PIVXBNB         PIVX/BNB        PIVX            BNB            
PIVXBTC         PIVX/BTC        PIVX            BTC            
PIVXETH         PIVX/ETH        PIVX            ETH            
POABNB          POA/BNB         POA             BNB            
POABTC          POA/BTC         POA             BTC            
POAETH          POA/ETH         POA             ETH            
POEBTC          POE/BTC         POE             BTC            
POEETH          POE/ETH         POE             ETH            
POLYBNB         POLY/BNB        POLY            BNB            
POLYBTC         POLY/BTC        POLY            BTC            
POWRBNB         POWR/BNB        POWR            BNB            
POWRBTC         POWR/BTC        POWR            BTC            
POWRETH         POWR/ETH        POWR            ETH            
PPTBTC          PPT/BTC         PPT             BTC            
PPTETH          PPT/ETH         PPT             ETH            
QKCBTC          QKC/BTC         QKC             BTC            
QKCETH          QKC/ETH         QKC             ETH            
QLCBNB          QLC/BNB         QLC             BNB            
QLCBTC          QLC/BTC         QLC             BTC            
QLCETH          QLC/ETH         QLC             ETH            
QSPBNB          QSP/BNB         QSP             BNB            
QSPBTC          QSP/BTC         QSP             BTC            
QSPETH          QSP/ETH         QSP             ETH            
QTUMBNB         QTUM/BNB        QTUM            BNB            
QTUMBTC         QTUM/BTC        QTUM            BTC            
QTUMETH         QTUM/ETH        QTUM            ETH            
QTUMUSDT        QTUM/USDT       QTUM            USDT           
RCNBNB          RCN/BNB         RCN             BNB            
RCNBTC          RCN/BTC         RCN             BTC            
RCNETH          RCN/ETH         RCN             ETH            
RDNBNB          RDN/BNB         RDN             BNB            
RDNBTC          RDN/BTC         RDN             BTC            
RDNETH          RDN/ETH         RDN             ETH            
REPBNB          REP/BNB         REP             BNB            
REPBTC          REP/BTC         REP             BTC            
REPETH          REP/ETH         REP             ETH            
REQBTC          REQ/BTC         REQ             BTC            
REQETH          REQ/ETH         REQ             ETH            
RLCBNB          RLC/BNB         RLC             BNB            
RLCBTC          RLC/BTC         RLC             BTC            
RLCETH          RLC/ETH         RLC             ETH            
RPXBNB          RPX/BNB         RPX             BNB            
RPXBTC          RPX/BTC         RPX             BTC            
RPXETH          RPX/ETH         RPX             ETH            
SALTBTC         SALT/BTC        SALT            BTC            
SALTETH         SALT/ETH        SALT            ETH            
SCBNB           SC/BNB          SC              BNB            
SCBTC           SC/BTC          SC              BTC            
SCETH           SC/ETH          SC              ETH            
SKYBNB          SKY/BNB         SKY             BNB            
SKYBTC          SKY/BTC         SKY             BTC            
SKYETH          SKY/ETH         SKY             ETH            
SNGLSBTC        SNGLS/BTC       SNGLS           BTC            
SNGLSETH        SNGLS/ETH       SNGLS           ETH            
SNMBTC          SNM/BTC         SNM             BTC            
SNMETH          SNM/ETH         SNM             ETH            
SNTBTC          SNT/BTC         SNT             BTC            
SNTETH          SNT/ETH         SNT             ETH            
STEEMBNB        STEEM/BNB       STEEM           BNB            
STEEMBTC        STEEM/BTC       STEEM           BTC            
STEEMETH        STEEM/ETH       STEEM           ETH            
STORJBTC        STORJ/BTC       STORJ           BTC            
STORJETH        STORJ/ETH       STORJ           ETH            
STORMBNB        STORM/BNB       STORM           BNB            
STORMBTC        STORM/BTC       STORM           BTC            
STORMETH        STORM/ETH       STORM           ETH            
STRATBTC        STRAT/BTC       STRAT           BTC            
STRATETH        STRAT/ETH       STRAT           ETH            
SUBBTC          SUB/BTC         SUB             BTC            
SUBETH          SUB/ETH         SUB             ETH            
SYSBNB          SYS/BNB         SYS             BNB            
SYSBTC          SYS/BTC         SYS             BTC            
SYSETH          SYS/ETH         SYS             ETH            
THETABNB        THETA/BNB       THETA           BNB            
THETABTC        THETA/BTC       THETA           BTC            
THETAETH        THETA/ETH       THETA           ETH            
TNBBTC          TNB/BTC         TNB             BTC            
TNBETH          TNB/ETH         TNB             ETH            
TNTBTC          TNT/BTC         TNT             BTC            
TNTETH          TNT/ETH         TNT             ETH            
TRIGBNB         TRIG/BNB        TRIG            BNB            
TRIGBTC         TRIG/BTC        TRIG            BTC            
TRIGETH         TRIG/ETH        TRIG            ETH            
TRXBTC          TRX/BTC         TRX             BTC            
TRXETH          TRX/ETH         TRX             ETH            
TRXUSDT         TRX/USDT        TRX             USDT           
TUSDBNB         TUSD/BNB        TUSD            BNB            
TUSDBTC         TUSD/BTC        TUSD            BTC            
TUSDETH         TUSD/ETH        TUSD            ETH            
TUSDUSDT        TUSD/USDT       TUSD            USDT           
VENBNB          VEN/BNB         VEN             BNB            
VENBTC          VEN/BTC         VEN             BTC            
VENETH          VEN/ETH         VEN             ETH            
VENUSDT         VEN/USDT        VEN             USDT           
VETBNB          VET/BNB         VET             BNB            
VETBTC          VET/BTC         VET             BTC            
VETETH          VET/ETH         VET             ETH            
VETUSDT         VET/USDT        VET             USDT           
VIABNB          VIA/BNB         VIA             BNB            
VIABTC          VIA/BTC         VIA             BTC            
VIAETH          VIA/ETH         VIA             ETH            
VIBBTC          VIB/BTC         VIB             BTC            
VIBETH          VIB/ETH         VIB             ETH            
VIBEBTC         VIBE/BTC        VIBE            BTC            
VIBEETH         VIBE/ETH        VIBE            ETH            
WABIBNB         WABI/BNB        WABI            BNB            
WABIBTC         WABI/BTC        WABI            BTC            
WABIETH         WABI/ETH        WABI            ETH            
WANBNB          WAN/BNB         WAN             BNB            
WANBTC          WAN/BTC         WAN             BTC            
WANETH          WAN/ETH         WAN             ETH            
WAVESBNB        WAVES/BNB       WAVES           BNB            
WAVESBTC        WAVES/BTC       WAVES           BTC            
WAVESETH        WAVES/ETH       WAVES           ETH            
WINGSBTC        WINGS/BTC       WINGS           BTC            
WINGSETH        WINGS/ETH       WINGS           ETH            
WPRBTC          WPR/BTC         WPR             BTC            
WPRETH          WPR/ETH         WPR             ETH            
WTCBNB          WTC/BNB         WTC             BNB            
WTCBTC          WTC/BTC         WTC             BTC            
WTCETH          WTC/ETH         WTC             ETH            
XEMBNB          XEM/BNB         XEM             BNB            
XEMBTC          XEM/BTC         XEM             BTC            
XEMETH          XEM/ETH         XEM             ETH            
XLMBNB          XLM/BNB         XLM             BNB            
XLMBTC          XLM/BTC         XLM             BTC            
XLMETH          XLM/ETH         XLM             ETH            
XLMUSDT         XLM/USDT        XLM             USDT           
XMRBTC          XMR/BTC         XMR             BTC            
XMRETH          XMR/ETH         XMR             ETH            
XRPBNB          XRP/BNB         XRP             BNB            
XRPBTC          XRP/BTC         XRP             BTC            
XRPETH          XRP/ETH         XRP             ETH            
XRPUSDT         XRP/USDT        XRP             USDT           
XVGBTC          XVG/BTC         XVG             BTC            
XVGETH          XVG/ETH         XVG             ETH            
XZCBNB          XZC/BNB         XZC             BNB            
XZCBTC          XZC/BTC         XZC             BTC            
XZCETH          XZC/ETH         XZC             ETH            
YOYOBNB         YOYOW/BNB       YOYOW           BNB            
YOYOBTC         YOYOW/BTC       YOYOW           BTC            
YOYOETH         YOYOW/ETH       YOYOW           ETH            
ZECBTC          ZEC/BTC         ZEC             BTC            
ZECETH          ZEC/ETH         ZEC             ETH            
ZENBNB          ZEN/BNB         ZEN             BNB            
ZENBTC          ZEN/BTC         ZEN             BTC            
ZENETH          ZEN/ETH         ZEN             ETH            
ZILBNB          ZIL/BNB         ZIL             BNB            
ZILBTC          ZIL/BTC         ZIL             BTC            
ZILETH          ZIL/ETH         ZIL             ETH            
ZRXBTC          ZRX/BTC         ZRX             BTC            
ZRXETH          ZRX/ETH         ZRX             ETH         
```

**Comment by xmatthias** [comment] 2018-08-02 10:04
could we get that script (or a trimmed down version as i'm not clear what the colors do and if that can be usefull too) as a PR into the scripts directory?

**Comment by creslinux** [comment] 2018-08-02 10:05
I dont think this is a bug, the air drop does not complete till 5ht august

- VET balances under 1 VET (including those in trade orders) will not be eligible for the airdrop.
- Distribution of this airdrop will be completed prior to 2018/08/05.
- This airdrop is independent of the normal monthly VTHO distribution.

https://support.binance.com/hc/en-us/articles/360009187992-100-Million-VTHO-Airdrop-for-VET-Holders

**Comment by creslinux** [comment] 2018-08-02 11:26
Having a balance in a wallet is not the same as the exchange having the
market open

Please can you check you can trade VHTO in binace for other pairs.

**Comment by vpotap** [comment] 2018-08-02 11:28
can't trade VHTO at all, coin only is displayed in wallet

**Comment by creslinux** [comment] 2018-08-02 11:31
This is not a bug, freqtrade can only trade markets the exchange open.

**Comment by vpotap** [comment] 2018-08-02 11:36
for trading yes agree , what about telegram rpc /balance where are listed all altcoins currently in wallet (not obligatory for trading)?

**Comment by creslinux** [comment] 2018-08-02 11:41
This issue is labelled no market symbol for VHTO/BTC
As there is no market for this pair this is not an issue. 

The error messages are from adding VHTO/BTC into config.json as a market to trade, not for checking a balance.

**Comment by vpotap** [comment] 2018-08-02 11:49
as i already mentioned there aren't any reference in config/strategy to VHTO altcoin, looks like for /balance retrievement it's fallback msg about VHTO/BTC , interesting that in config  stake currency is ETH and dont have any reference to BTC

**Comment by creslinux** [comment] 2018-08-02 12:28
thats interesting, definitely a bug, thanks for the clarification to me.
Sadly i don't have telegram or VHTO  will be tricky for me to help debug

**Comment by xmatthias** [comment] 2018-08-08 20:04
Dear, 

i created a PR to solve issue with #1135. would you be so kind to test if `/balance` is working with this branch - unfortunately i don't have VHTO, so i can only try to simulate the behaviour you experience.

**Comment by xmatthias** [comment] 2018-08-22 04:32
Closing this now since #1135 was merged.

should you still encounter the issue feel free to reopen.

**Closed by xmatthias** 2018-08-22 04:32 UTC
Labels: bug
