### ISSUE TITLE
Sending the forceexit command via telegram failed

### ISSUE THREAD

**Issue by yili1992** [freqtrade/freqtrade#8849] opened 2023-07-01 12:26 UTC
## Describe your environment

  * Operating system: Ubuntu 20.04.4 LTS
  * Python Version: Python 3.10.10 (python -V)
  * CCXT version: ccxt==3.1.5 (pip freeze | grep ccxt)
  * Freqtrade Version: freqtrade 2023.5.1 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)
  

## Describe the problem:
Sending the forceexit command via telegram failed with the following error
```
2023-07-01 12:20:09 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/home/ftuser/.local/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/freqtrade/freqtrade/rpc/telegram.py", line 1136, in _force_exit_inline
    await self._force_exit_action(trade_id)
  File "/freqtrade/freqtrade/rpc/telegram.py", line 1117, in _force_exit_action
    self._rpc._rpc_force_exit(trade_id)
  File "/freqtrade/freqtrade/rpc/rpc.py", line 820, in _rpc_force_exit
    self.__exec_force_exit(trade, ordertype, amount)
  File "/freqtrade/freqtrade/rpc/rpc.py", line 789, in __exec_force_exit
    self._freqtrade.execute_trade_exit(
  File "/freqtrade/freqtrade/freqtradebot.py", line 1620, in execute_trade_exit
    trade.funding_fees = self.exchange.get_funding_fees(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2794, in get_funding_fees
    funding_fees = self._fetch_and_calculate_funding_fees(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2697, in _fetch_and_calculate_funding_fees
    candle_histories = self.refresh_latest_ohlcv(
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2075, in refresh_latest_ohlcv
    results = self.loop.run_until_complete(gather_stuff())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 586, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running```

**Comment by xmatthias** [comment] 2023-07-01 13:08
Duplicate of #8731, fixed in 317e0b5f2becb3b772c303556280c025f94c60ef, and available in the latest develop version (will be part of the next release).

Anyway, thanks for reporting :+1:

**Closed as completed** 2023-07-01 13:08 UTC
Labels: Bug, Duplicate
