### ISSUE TITLE
 population and stoploss effectiveness

### ISSUE THREAD

**Issue by mablue** [freqtrade/freqtrade#4629] opened 2021-03-29 20:52 UTC
*Describe the enhancement*
I don't know the population of strategy how much effected on trading.
yes we have win or loss but I don't know first player of my threading strategy.
maybe my sell population is not do any thing and a bloatware and sells happens just cuz of stop-loss.

*Explain the enhancement you would like*
show how much trade almost progressed by sell function , buy function , stop-loss value and etc.
win or loss or draw not good idea for helping to show how works the strategy

**Comment by xmatthias** [comment] 2021-03-30 04:20
it's VERY dificult to understand what you're actually asking - but i will assume it's a duplicate of #4276 , which would like to have the profit available in the populate_sell method.

As explained in that issue, this is not possible for now due to technical reasons (otherwise backtesting + hyperopt will become dead slow).

**Comment by mablue** [comment] 2021-03-30 08:54
No no its not duplicate of the#4278!
I want to know this simple thing:
How much of my sell orders progressed by sell function.
How much of them progressed by reaching to stop loss
How much of my buy orders progressed by buy function 
Its important cuz of checking my strategy functions how much effective 
Somthing like that
```
Print(len(pairs that bought by buy function)/len(all bought count))
Print(len(pairs that sold by sell function)/len(all sold count))
Print(len(pairs that sold by stoploss)/len(all sold count))
Print(len(pairs that xxx by xxx)/len(all xxx count))

```

**Comment by xmatthias** [comment] 2021-03-30 09:27
You can do this by using the [Trades](https://www.freqtrade.io/en/stable/strategy-customization/#additional-data-trades)   object during live / dry runs. 
It will not be possible during backtesting-hyperopt (see #4276 and [this documentation](https://www.freqtrade.io/en/stable/bot-basics/#backtesting-hyperopt-execution-logic) for reasons).


I would recommend to read the documentation at least once from top to bottom - even if you don't understand everything at the first try - it'll give you an idea on what's possible and will avoid asking a ton of questions that could be answered by the documentation, and are therefore taking away time that could be better spent on improving the bot, instead of pointing people to the documentation over and over again.

**Closed as completed by xmatthias** 2021-03-30 09:27 UTC
Labels: Duplicate

**Comment by mablue** [comment] 2021-03-30 10:38
Ok. Yes I will read more.
Tnx for help ;)
