### ISSUE TITLE
Can you add a Telegram command: /forceexit plus

### ISSUE THREAD

**Issue by WinPoss** [freqtrade/freqtrade#10005] opened 2024-03-26 01:39 UTC
## Describe your environment
(if applicable)

  * Operating system: ubuntu 20.04.6
  * Python Version: 3.8.10
  * CCXT version: 4.2.25
  * Freqtrade Version: 2024.2

## Describe the enhancement

*Explain the enhancement you would like*

Can you add a Telegram command: `/forceexit plus`

For example, if I have bought 20 assets and 15 of them are profitable, when I enter this command, sell all the profitable assets and keep the remaining 5 assets that haven't made a profit yet.

Thanks.

**Comment by xmatthias** [comment] 2024-03-26 05:31
I don't really see that as a neccessity - you can use `/forceexit <tradeid>` to exit the trades you'd **actually** want to sell.

I think the details of this will actually kill this as being useful. 
Everyone will need a different selection / criteria (only the ones with profit > 1%, only the ones that have been open for half a day, ...) - which is also why this was already rejected in #7696 (it's therefore a duplicate of that issue).

"profitable" in the most technical sense is everything that has "profit > 0". 
If however you sell a trade with 0.001% profit - it's profitable - but once it's order is placed (assume you're selling 15 trades, this is the last one) - price may have dropped slightly into the red. (even slippage or fees can draw you into the red here).

It's still profitable in the sense of "when it was selected" - but the end-result is no longer positive.


I don't really see why this should be added - you have /forceexit <tradeid> so you can pick according to YOUR criteria - not based on some random cutoff (you can't satisfy every usecase).

As such - it'll seem useful at first - but will end as a feature we need to maintain / keep alive - but really without being used (which is something we can't track - as we don't track user behavior).

For the moment, i'll treat this as a Duplicate to an already rejected feature request (which i aim to close in a few days) - unless there's compelling arguments which convince me on why this is a "must have" feature.

**Comment by froggleston** [comment] 2024-03-26 11:02
I'd agree - this can be fairly easily solved by using the REST API. I don't think the Telegram interface should include every command/combination that people might want to use, but rather a set of the most used by the most people.

**Comment by stash86** [comment] 2024-04-14 08:38
Closing this since there is no new input

**Closed as completed by stash86** 2024-04-14 08:38 UTC
Labels: Duplicate, Question
