### ISSUE TITLE
Kraken responses 414 while GETting the public endpoint

### ISSUE THREAD

**Issue by poweronoff** [freqtrade/freqtrade#6318] opened 2022-01-29 15:13 UTC
* Operating system: docker 17.05.0 on  debian 10
  * Python Version: from the official docker image
  * CCXT version: from the official docker image
  * Freqtrade Version: 2021.12
  

Since 2 days, without changing anything in a freqtrade configuration I am getting following error in a log

`ccxt.base.errors.ExchangeError: kraken GET https://api.kraken.com/0/public/Ticker?pair=1INCHEUR%2C1INCHUSD%2CAAVEAUD%2CAAVEXBT%2CAAVEETH%2CAAVEEUR%2CAAVEGBP%2CAAVEUSD%2CACAEUR%2CACAUSD%2CADAAUD%2CADAXBT%2CADAETH%2CADAEUR%2CADAGBP%2CADAUSD%2CADAUSDT%2CALGOXBT%2CALGOETH%2CALGOEUR%2CALGOGBP%2CALGOUSD%2CANKRXBT%2CANKREUR%2CANKRGBP%2CANKRUSD%2CANTXBT%2CANTETH%2CANTEUR%2CANTUSD%2CASTREUR%2CASTRUSD%2CATLASEUR%2CATLASUSD%2CATOMAUD%2CATOMXBT%2CATOMETH%2CATOMEUR%2CATOMGBP%2CATOMUSD%2CAUDJPY%2CAUDUSD%2CAVAXEUR%2CAVAXUSD%2CAXSEUR%2CAXSUSD%2CBADGEREUR%2CBADGERUSD%2CBALXBT%2CBALETH%2CBALEUR%2CBALUSD%2CBANDEUR%2CBANDUSD%2CBATXBT%2CBATETH%2CBATEUR%2CBATJPY%2CBATUSD%2CBCHAUD%2CBCHXBT%2CBCHETH%2CBCHEUR%2CBCHGBP%2CBCHJPY%2CBCHUSD%2CBCHUSDT%2CBNCEUR%2CBNCUSD%2CBNTXBT%2CBNTEUR%2CBNTGBP%2CBNTUSD%2CXBTAUD%2CXXBTZCAD%2CXBTCHF%2CXBTDAI%2CXXBTZEUR%2CXXBTZGBP%2CXXBTZJPY%2CXXBTZUSD%2CXBTUSDC%2CXBTUSDT%2CCHZEUR%2CCHZUSD%2CCOMPXBT%2CCOMPETH%2CCOMPEUR%2CCOMPUSD%2CCQTEUR%2CCQTUSD%2CCRVXBT%2CCRVETH%2CCRVEUR%2CCRVUSD%2CCTSIEUR%2CCTSIUSD%2CDAIEUR%2CDAIUSD%2CDAIUSDT%2CDASHXBT%2CDASHEUR%2CDASHUSD%2CXXDGXXBT%2CXDGEUR%2CXDGUSD%2CXDGUSDT%2CDOTAUD%2CDOTXBT%2CDOTETH%2CDOTEUR%2CDOTGBP%2CDOTUSD%2CDOTUSDT%2CDYDXEUR%2CDYDXUSD%2CENJXBT%2CENJEUR%2CENJGBP%2CENJUSD%2CEOSXBT%2CEOSETH%2CEOSEUR%2CEOSUSD%2CEOSUSDT%2CXETCXXBT%2CXETCXETH%2CXETCZEUR%2CXETCZUSD%2CETHAUD%2CXETHXXBT%2CXETHZCAD%2CETHCHF%2CETHDAI%2CXETHZEUR%2CXETHZGBP%2CXETHZJPY%2CXETHZUSD%2CETHUSDC%2CETHUSDT%2CETH2.SETH%2CEURAUD%2CEURCAD%2CEURCHF%2CEURGBP%2CEURJPY%2CZEURZUSD%2CEWTXBT%2CEWTEUR%2CEWTGBP%2CEWTUSD%2CFIDAEUR%2CFIDAUSD%2CFILAUD%2CFILXBT%2CFILETH%2CFILEUR%2CFILGBP%2CFILUSD%2CFLOWXBT%2CFLOWETH%2CFLOWEUR%2CFLOWGBP%2CFLOWUSD%2CZGBPZUSD%2CGHSTXBT%2CGHSTEUR%2CGHSTGBP%2CGHSTUSD%2CGLMREUR%2CGLMRUSD%2CGNOXBT%2CGNOETH%2CGNOEUR%2CGNOUSD%2CGRTAUD%2CGRTXBT%2CGRTETH%2CGRTEUR%2CGRTGBP%2CGRTUSD%2CICXXBT%2CICXETH%2CICXEUR%2CICXUSD%2CINJEUR%2CINJUSD%2CKAREUR%2CKARUSD%2CKAVAXBT%2CKAVAETH%2CKAVAEUR%2CKAVAUSD%2CKEEPXBT%2CKEEPETH%2CKEEPEUR%2CKEEPUSD%2CKILTEUR%2CKILTUSD%2CKINEUR%2CKINUSD%2CKINTEUR%2CKINTUSD%2CKNCXBT%2CKNCETH%2CKNCEUR%2CKNCUSD%2CKSMAUD%2CKSMXBT%2CKSMDOT%2CKSMETH%2CKSMEUR%2CKSMGBP%2CKSMUSD%2CLINKAUD%2CLINKXBT%2CLINKETH%2CLINKEUR%2CLINKGBP%2CLINKJPY%2CLINKUSD%2CLINKUSDT%2CLPTXBT%2CLPTEUR%2CLPTGBP%2CLPTUSD%2CLRCEUR%2CLRCUSD%2CLSKXBT%2CLSKETH%2CLSKEUR%2CLSKUSD%2CLTCAUD%2CXLTCXXBT%2CLTCETH%2CXLTCZEUR%2CLTCGBP%2CXLTCZJPY%2CXLTCZUSD%2CLTCUSDT%2CLUNAEUR%2CLUNAUSD%2CMANAXBT%2CMANAETH%2CMANAEUR%2CMANAUSD%2CMATICXBT%2CMATICEUR%2CMATICGBP%2CMATICUSD%2CMINAXBT%2CMINAEUR%2CMINAGBP%2CMINAUSD%2CMIREUR%2CMIRUSD%2CMKRXBT%2CMKREUR%2CMKRGBP%2CMKRUSD%2CXMLNXXBT%2CXMLNXETH%2CXMLNZEUR%2CXMLNZUSD%2CMNGOEUR%2CMNGOUSD%2CMOVREUR%2CMOVRUSD%2CNANOXBT%2CNANOETH%2CNANOEUR%2CNANOUSD%2COCEANXBT%2COCEANEUR%2COCEANGBP%2COCEANUSD%2COGNEUR%2COGNUSD%2COMGXBT%2COMGETH%2COMGEUR%2COMGJPY%2COMGUSD%2CORCAEUR%2CORCAUSD%2COXTXBT%2COXTETH%2COXTEUR%2COXTUSD%2COXYEUR%2COXYUSD%2CPAXGXBT%2CPAXGETH%2CPAXGEUR%2CPAXGUSD%2CPERPEUR%2CPERPUSD%2CPHAEUR%2CPHAUSD%2CPOLISEUR%2CPOLISUSD%2CQTUMXBT%2CQTUMETH%2CQTUMEUR%2CQTUMUSD%2CRARIXBT%2CRARIEUR%2CRARIGBP%2CRARIUSD%2CRAYEUR%2CRAYUSD%2CRENXBT%2CRENEUR%2CRENGBP%2CRENUSD%2CREPV2XBT%2CREPV2ETH%2CREPV2EUR%2CREPV2USD%2CXREPXXBT%2CXREPXETH%2CXREPZEUR%2CXREPZUSD%2CSANDXBT%2CSANDEUR%2CSANDGBP%2CSANDUSD%2CSBREUR%2CSBRUSD%2CSCXBT%2CSCETH%2CSCEUR%2CSCUSD%2CSDNEUR%2CSDNUSD%2CSHIBEUR%2CSHIBUSD%2CSNXAUD%2CSNXXBT%2CSNXETH%2CSNXEUR%2CSNXGBP%2CSNXUSD%2CSOLXBT%2CSOLEUR%2CSOLGBP%2CSOLUSD%2CSRMXBT%2CSRMEUR%2CSRMGBP%2CSRMUSD%2CSTEPEUR%2CSTEPUSD%2CSTORJXBT%2CSTORJETH%2CSTORJEUR%2CSTORJUSD%2CSUSHIXBT%2CSUSHIEUR%2CSUSHIGBP%2CSUSHIUSD%2CTBTCXBT%2CTBTCETH%2CTBTCEUR%2CTBTCUSD%2CTRXXBT%2CTRXETH%2CTRXEUR%2CTRXUSD%2CUNIXBT%2CUNIETH%2CUNIEUR%2CUNIUSD%2CZUSDZCAD%2CUSDCHF%2CZUSDZJPY%2CUSDCAUD%2CUSDCEUR%2CUSDCGBP%2CUSDCUSD%2CUSDCUSDT%2CUSDTAUD%2CUSDTCAD%2CUSDTCHF%2CUSDTEUR%2CUSDTGBP%2CUSDTJPY%2CUSDTZUSD%2CWAVESXBT%2CWAVESETH%2CWAVESEUR%2CWAVESUSD%2CWBTCXBT%2CWBTCEUR%2CWBTCUSD%2CXXLMZAUD%2CXXLMXXBT%2CXXLMZEUR%2CXXLMZGBP%2CXXLMZUSD%2CXXMRXXBT%2CXXMRZEUR%2CXXMRZUSD%2CXRPAUD%2CXXRPXXBT%2CXXRPZCAD%2CXRPETH%2CXXRPZEUR%2CXRPGBP%2CXXRPZJPY%2CXXRPZUSD%2CXRPUSDT%2CXTZAUD%2CXTZXBT%2CXTZETH%2CXTZEUR%2CXTZGBP%2CXTZUSD%2CYFIAUD%2CYFIXBT%2CYFIETH%2CYFIEUR%2CYFIGBP%2CYFIUSD%2CXZECXXBT%2CXZECZEUR%2CXZECZUSD%2CZRXXBT%2CZRXEUR%2CZRXGBP%2CZRXUSD`

`The above exception was the direct cause of the following exception:`

`Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 95, in __init__
    self.active_pair_whitelist = self._refresh_active_whitelist()
  File "/freqtrade/freqtrade/freqtradebot.py", line 219, in _refresh_active_whitelist
    self.pairlists.refresh_pairlist()
  File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 84, in refresh_pairlist
    tickers = self._get_cached_tickers()
  File "/home/ftuser/.local/lib/python3.9/site-packages/cachetools/decorators.py", line 26, in wrapper
    v = func(*args, **kwargs)
  File "/freqtrade/freqtrade/plugins/pairlistmanager.py", line 77, in _get_cached_tickers
    return self._exchange.get_tickers()
  File "/freqtrade/freqtrade/exchange/common.py", line 119, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 119, in wrapper
    return wrapper(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/common.py", line 119, in wrapper
    return wrapper(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/freqtrade/freqtrade/exchange/common.py", line 122, in wrapper
    raise ex
  File "/freqtrade/freqtrade/exchange/common.py", line 107, in wrapper
    return f(*args, **kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 967, in get_tickers
    raise TemporaryError(`

Doing a GET request from my local machine via Postman against the Kraken public API with the same request resulting in a 414 Request-URI Too Large. Seems, that Kraken has changed that behavior recently.

  
I am wondering why freqtrade is constructing that large URL and trying to get a ticker values for EUR, USD, AUD etc, while my fiat is EUR only. How valuable are all possible permutations for the application?

Seems, that we need a workaround or a fix for that issue.

Maybe it can be fixed in a configuration.

**Comment by xmatthias** [comment] 2022-01-29 16:10
Duplicate of #6311.

It's fixed in the develop branch.

**Closed as completed by xmatthias** 2022-01-29 16:10 UTC
Labels: Duplicate
