### ISSUE TITLE
Log levels and bot monitoring (Question)

### ISSUE THREAD

**Issue by gaugau3000** [freqtrade/freqtrade#2408] opened 2019-10-21 20:39 UTC
Hi,

As an algo trader
I want to monitore many bot instances easily
So that i can prevent losing money (bad behaviour) or make no trade

for example the message below comes every process_throttle_secs :
> - INFO - Found no buy signals for whitelisted currencies. Trying again...

This frequency is annoying when i try to read the logs. How you deal with   it ?

you use a log tool analyser like Kibana ?

Many tks.

**Comment by xmatthias** [comment] 2019-10-22 04:16
The easiest will be to change the log-level of that message to DEBUG ... and if i'm honest, i thought that we had the bot silenced completely some time ago.

the downside to this is that the bot will send no "i'm alive" anymore ... so looking at the logs of a rarely trading strategy will not tell you too much.

**Comment by hroff-1902** [comment] 2019-10-22 10:13
I also thought of it (verbosity levels) for long time.

Currently, the current verbosity level is 0. Verbosity level 1 adds DEBUG messages, verbosity level 3 adds printing content of network communication.

There is no difference between verbosity level 1 and 2. This can be utilized for this proposal, amongst probably other changes in logging:

* We can remove this info message at verbosity level 0
* Default verbosity level is to be set to 1 (i.e. keeping this message by default)
* Since selection of logging messages is performed on the logger (module) level, `throttle` method should be separated into different module, like freqtrade.worker.throttle, to control its logging easily.
* An additional `-q/--quiet` option be added, which decreases the verbosity level. Thus, `freqtrade -q` won't print this message
* Additionally, `-qq` (verbosity level -1, if we start counting from default verbosity level 1) may only allow WARNINGS and no INFO log messages, `-qqq` (verbosity level -2) -- only ERROR and CRITICAL
* Additionally, the values of the verbosity levels can be shifted to be like:

0 -- will stand for ERROR/CRITICAL, `-qqq`; 
1 -- WARNINGS, `-qq`; 
2 -- INFO without this noisy message (there can also be other differences in the future), `-q`; 
3 -- INFO (default); 
4 -- DEBUG, `-v`;
5 -- TBD reserved, `-vv`; may contain some extra messages, or vise versa level 4 may have some noisy DEBUG messages reduced
6 -- DEBUG plus network communication contents. `-vvv`

**Comment by hroff-1902** [comment] 2019-10-22 10:17
Plus for utilities the default level can be set to the decreased level, to print only WARNINGs or even ERRORs.

**Comment by xmatthias** [comment] 2019-10-22 10:18
i find this way too complicated ...

A sensible default should do it too.
The above message is not needed - and by switching that to Debug the bot will be silent unless it has no whitelist, or does an action (trading or similar).

**Comment by xmatthias** [comment] 2019-10-25 09:29
This is not a good solution / or rather - not a solution to this problem.

Assume you use freqtrade within Docker - then rsyslog from the system is not available, and you'd need to install that within docker. 
You can also have docker forward stdout/stderr to rsyslog (or syslog servers ...) - but that requires system-wide changes to the docker configuration iirc.

Using `docker logs <container>` does have advantages in simplicity here.
Now that does not mean that the flexibility of #2418 should not be there, just that it won't solve this particular issue.

I think the simplest solution to this issue is be to switch the log-level of `Found no buy signals for whitelisted currencies. Trying again...` to debug.
This will silence the bot in it's "regular" outputs ... but will still output important messages.

It's also bothersome to scroll through 20 pages of "nothing happened" to find the last trade ...

We've been there before (no output if no action occurs) (I think right after #1378).

having the bot silent per default (unless "action" occurs) will have operational benefits, especially since I've not had one case in the last year where the bot got stuck - it either crashes / stops -> Process is gone - or continues to run (running 2-3 bots in parallel within docker).

**Comment by hroff-1902** [comment] 2019-10-25 12:00
This all is not necessary. Simply mount host `/dev/log` into container as use it without any additional strange and heavy gestures. Both host journald and rsyslog will get the messages:
```
docker run ... -v /dev/log:/dev/log ...
```
Another possibility is syslog through UDP socket listening by the host rsyslog on a host network interface available to the container. I.e., run in the container
```
freqtrade --logfilename syslog:host_ip:port
```

**Comment by xmatthias** [comment] 2019-10-25 12:06
on a windows docker host there is no /dev/log.

**Comment by hroff-1902** [comment] 2019-10-25 12:09
on windows there is python standard logging module with SysLogHandler and an option to use UDP sockets, either from freqtrade running on the host Windows machine, or in a linux/windows container. It's just a network socket and the appropriate protocol, which is available in the standard python library.

We could also add Windows-specific logging later.

**Comment by hroff-1902** [comment] 2019-10-25 12:12
For macOS, ad I said in #2418, another address (unix domain socket) should be used, `/var/run/log` IIRC...

We should better discuss this in #2418, I guess, @gaugau3000 may be scared with all this stuff... 😆

**Comment by xmatthias** [comment] 2019-10-25 12:12
But all of this is over engineering a solution which is not even problem, and which probably noone will use it.

Noone asked for journald or syslog based logging - the issue is about removing *one single message*, which is repeated again and again without purpose. 
It's going to remain a problem no matter what logging system you are using, and in the end, we'll swap it to debug as i proposed 3 messages ago.

**Comment by hroff-1902** [comment] 2019-10-25 12:14
Why noone will use it if it's so simple as mounting /dev/log into container? And journald is a de-facto standard nowadays. Journalctl is nowadays the second command novice linux system administrators study from the systemd family. just after systemctl...

**Comment by hroff-1902** [comment] 2019-10-25 12:16
And why I particularly mentioned it here: this resolves (elegantly) the problem stated in this issue -- the rsyslogd daemon can automagically reduce all repeating noisy messages from the bot with no additional movements needed...

**Comment by xmatthias** [comment] 2019-10-25 12:18
i don't disagree with this - all system tools use journald.
docker does not by default - but uses json-based logging by default (when using docker logs).

Also, please carefully read what i said above - i'm not against adding logging to journald and i think #2418 will be good - it will just not solve *this issue*, which is about a repeated log-message which makes reading the logs hard.
Yes, rsyslogd probably can - but maybe 1% of our users are able to configure rsyslogd (probably less).

Remember, this is not about us getting it to work that way, but about users actually using this without much effort, which i don't see given with the rsyslog approach.

**Comment by hroff-1902** [comment] 2019-10-25 12:20
> which is repeated again and again without purpose.

It's needed. Let's change it to the 'ping' message "I'm alive, I'm alive" and move to some other place in the process() or _throttle() method... It's actually needed,

**Comment by xmatthias** [comment] 2019-10-25 12:20
what is it needed for?

**Comment by hroff-1902** [comment] 2019-10-25 12:36
Oh, man, that's not an issue nowadays, see rationale behind journald and why it's now so popular -- because filling disks with messages is not an issue anymore. It fills binary journals with many additional attributes for every log record, keeps history of all previous boots, keeps logs from all systemd units started, etc... For instance, journal is ~100 times bigger on my machine than syslog...

And this message -- it's now works as the 'ping still alive' message. I was not glad to see hundreds of them, so (see at the top of the issue) I thought that there should be an ability to suppress this message, for example by means of additional log levels I described above. But then I found that this can easily and effectively be achieved by rsyslog, reducing repeating messages. And I can still be sure that the bot is not hanging -- I can open the syslog viewer and see the *changing digits* (the count of repeating messages) at the last line, if no one else is happening... And now you tell me that now I should switch all those debug messages just to see that the bot is not hanging/looping somewhere in between its trading logic...

**Comment by xmatthias** [comment] 2019-10-25 12:47
as said, i don't argue against journald, neither against #2418

it'll just not work cross-platform (windows has no easy option - and yes, i know there are options- but they require a syslog server "somewhere" - and if you have that, you'd not be using windows ...)

So your solution will work, will reduce the amount of messages
* if journald is configured correctly 
* not on windows
* not when using `docker logs <container>` 
... only when using journald.

I also agree that journald is the standard now for almost linux system (devuan ... looking at you) - however if you look at our average user base, then almost none of them have linux Operational experience, most don't have much linux experience at all ... which makes all of the above a huge hurdle to climb - just to get rid of these messages.


I'll add one more thing to #2419 - and in combination with #2418 that should fix this logic.

> And now you tell me that now I should switch all those debug messages on just to see that the bot is not hanging/looping somewhere in between its trading logic...

I've not seen the bot hang between it's trading logic in over a year ... is this something you see more frequently?

**Comment by hroff-1902** [comment] 2019-10-25 12:49
The 'OS of misoriented slashes' (Windows), yes, has frequently no easy options... 😆

**Comment by xmatthias** [comment] 2019-10-25 13:01
I am not saying i like ~~Windoof~~ Windows ... but it's market share makes it hard to ignore ...

**Comment by hroff-1902** [comment] 2019-10-25 13:04
Sure.

**Comment by hroff-1902** [comment] 2019-10-26 08:11
Should be fixed in #2419 

@gaugau3000 pls verify.

**Closed by hroff-1902** 2019-10-26 08:11 UTC
Labels: question

**Comment by Nai-mul** [comment] 2020-07-20 13:55
This picture as a gift for @xmatthias finally freqtrade running in the Android Console.     
![Screenshot_2020-07-20-19-43-37-952_com termux](https://user-images.githubusercontent.com/64520358/87944805-b016bb00-cac1-11ea-89ba-bc2bd42c3b2b.jpg)

WARNING - Unable to create trade for KAVA/USDT: Available balance (990.0 USDT) is lower than stake amount (1000 USDT)
it’s happening in dry-run = true mode

 config-


    "max_open_trades": 2,
    "stake_currency": "USDT",
    "stake_amount": 1000,
    "fiat_display_currency": "USD",
    "timeframe": "5m",
    "dry_run": true,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },
    "bid_strategy": {
        "ask_last_balance": 0.0,

    },
    "exchange": {
        "name": "binance",
        "key": "",
        "secret": "",
        "pair_whitelist": [
            "BTC/USDT",           
            "ETH/USDT",
            "XRP/USDT",
            "EOS/USDT",
            "LTC/USDT",
            "BNB/USDT",
            "XLM/USDT",
            "ADA/USDT",
            "TRX/USDT",
            "XMR/USDT",
            "DASH/USDT",
            "ONT/USDT",
            "NEO/USDT",
            "ETC/USDT",
            "ZEC/USDT",
            "VET/USDT",
            "BAT/USDT",
            "OMG/USDT",
            "QTUM/USDT",
            "RVN/USDT",
            "ZRX/USDT",
            "LINK/USDT",
            "ZIL/USDT",
            "ICX/USDT",
            "NANO/USDT",
            "ENJ/USDT",
            "IOST/USDT",
            "THETA/USDT",
            "FET/USDT",
            "MTL/USDT",
            "REN/USDT",
            "DATA/USDT",
            "LEND/USDT",
            "HOT/USDT",
            "BTT/USDT",
            "KNC/USDT",
            "CELR/USDT",
            "ONG/USDT",
            "BCH/USDT",
            "ATOM/USDT",
            "XTZ/USDT",
            "IOTA/USDT",
            "NPXS/USDT",
            "IOTX/USDT",
            "DENT/USDT",
            "WIN/USDT",
            "KAVA/USDT",
            "WRX/USDT",
            "MFT/USDT",
            "KEY/USDT",
            "FUN/USDT",
            "MATIC/USDT",

        ],
        "pair_blacklist": [
            "BNB/BTC",
            
        ]
    },

        "edge": {
        "enabled": false,
        "process_throttle_secs": 3600,
        "calculate_since_number_of_days": 7,
        "allowed_risk": 0.01,
        "stoploss_range_min": -0.01,
        "stoploss_range_max": -0.1,
        "stoploss_range_step": -0.01,
        "minimum_winrate": 0.60,
        "minimum_expectancy": 0.20,
        "min_trade_number": 10,
        "max_trade_duration_minute": 1440,
        "remove_pumps": false
    },
    "pairlists": [
        {"method": "StaticPairList"}
    ],
    "telegram": {
        "enabled": true,
        "token": "",
        "chat_id": ""
    },
    "initial_state": "running",
    "internals": {
        "process_throttle_secs": 5
    }
}

**Comment by Nai-mul** [comment] 2020-07-20 13:59
![Screenshot_2020-07-20-19-57-52-447_com termux](https://user-images.githubusercontent.com/64520358/87946149-78a90e00-cac3-11ea-81e3-a4f9ce7c4c58.jpg)

**Comment by jedi108** [comment] 2024-03-06 12:25
> I also thought of it (verbosity levels) for long time.
> 
> Currently, the current verbosity level is 0. Verbosity level 1 adds DEBUG messages, verbosity level 3 adds printing content of network communication.
> 
> There is no difference between verbosity level 1 and 2. This can be utilized for this proposal, amongst probably other changes in logging:
> 
> * We can remove this info message at verbosity level 0
> * Default verbosity level is to be set to 1 (i.e. keeping this message by default)
> * DEBUG messages are switched on in verbosity level 2 instead of current 1
> * Since selection of logging messages is performed on the logger (module) level, `throttle` method should probably be separated into different module, like freqtrade.worker.throttle, to control its logging easily.
> * An additional `-q/--quiet` option be added, which decreases the verbosity level. Thus, `freqtrade -q` won't print this message
> * Additionally, `-qq` (verbosity level -1, if we start counting from default verbosity level 1) may only allow WARNINGS and no INFO log messages, `-qqq` (verbosity level -2) -- only ERROR and CRITICAL
> * Additionally, the values of the verbosity levels can be shifted to be like:
> 
> 0 -- will stand for ERROR/CRITICAL, `-qqq`; 1 -- WARNINGS, `-qq`; 2 -- INFO without this noisy message (there can also be other differences in the future), `-q`; 3 -- INFO (default); 4 -- DEBUG, `-v`; 5 -- TBD reserved, `-vv`; may contain some extra messages, or vise versa level 4 may have some noisy DEBUG messages reduced 6 -- DEBUG plus network communication contents. `-vvv`

please help:
unrecognized arguments: -qq
unrecognized arguments: --qq

**Comment by xmatthias** [comment] 2024-03-06 13:02
@jedi108 There is no `-q` or `-qq` argument. Please use the [documentation](https://freqtrade.io/) to get uptodate information.

Posting or searching in an issue that's 5 years old is clearly not the right way.

Locking to avoid further spam to past partecipants in this issue.
