### ISSUE TITLE
Could not load trade history due to DDoSProtection

### ISSUE THREAD

**Issue by LightDelphin** [freqtrade/freqtrade#3429] opened 2020-06-02 07:02 UTC
## Describe your environment

  * Operating system: ____Ubuntu
  * Python Version: _____ (`python -V`) 3.6.9
  * CCXT version: _____ (`pip freeze | grep ccxt`) 1.26.53
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) develop
  
## Your question

I try to load data with the command: freqtrade download-data --exchange kraken, but in the end result it writes the following to the console:
`(.env) 1@1-MS-7721:~/freq-final$ freqtrade download-data --exchange kraken
2020-06-02 09:48:25,840 - freqtrade.loggers - INFO - Verbosity set to 0
2020-06-02 09:48:25,841 - freqtrade.configuration.configuration - INFO - Using exchange kraken
2020-06-02 09:48:25,841 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/1/freq-final/user_data ...
2020-06-02 09:48:25,843 - freqtrade.configuration.configuration - INFO - Using data directory: /home/1/freq-final/user_data/data/kraken ...
2020-06-02 09:48:25,843 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1m', '5m']
2020-06-02 09:48:25,843 - freqtrade.configuration.configuration - INFO - Using "json" to store OHLCV data.
2020-06-02 09:48:25,843 - freqtrade.configuration.configuration - INFO - Using "jsongz" to store trades data.
2020-06-02 09:48:25,843 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-06-02 09:48:25,843 - freqtrade.configuration.check_exchange - INFO - Exchange "kraken" is officially supported by the Freqtrade development team.
2020-06-02 09:48:25,843 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-06-02 09:48:25,843 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-06-02 09:48:25,849 - freqtrade.commands.data_commands - INFO - About to download pairs: ['ADA/EUR', 'ATOM/EUR', 'BAT/EUR', 'BCH/EUR', 'BTC/EUR', 'DAI/EUR', 'DASH/EUR', 'EOS/EUR', 'ETC/EUR', 'ETH/EUR', 'LINK/EUR', 'LTC/EUR', 'QTUM/EUR', 'REP/EUR', 'WAVES/EUR', 'XLM/EUR', 'XMR/EUR', 'XRP/EUR', 'XTZ/EUR', 'ZEC/EUR'], intervals: ['1m', '5m'] to /home/1/freq-final/user_data/data/kraken
2020-06-02 09:48:25,849 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-06-02 09:48:25,849 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-06-02 09:48:25,856 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 100}
2020-06-02 09:48:25,861 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2020-06-02 09:48:25,863 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Kraken'...
2020-06-02 09:48:25,863 - freqtrade.exchange.exchange - WARNING - Markets were not loaded. Loading them now..
2020-06-02 09:48:32,845 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair ADA/EUR.
2020-06-02 09:48:46,504 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:48:46,505 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:48:46,743 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:48:46,743 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:48:46,985 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:48:46,985 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:48:47,220 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:48:47,221 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:48:47,458 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:48:47,458 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:48:47,458 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "ADA/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:48:47,458 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair ATOM/EUR.
2020-06-02 09:48:54,624 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/ATOM_EUR-trades.json.gz"
2020-06-02 09:48:55,697 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 45554
2020-06-02 09:48:55,746 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair BAT/EUR.
2020-06-02 09:49:04,020 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/BAT_EUR-trades.json.gz"
2020-06-02 09:49:05,550 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 63811
2020-06-02 09:49:05,622 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair BCH/EUR.
2020-06-02 09:49:18,123 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:18,124 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:49:18,367 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:18,367 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:49:19,289 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:19,289 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:49:19,528 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:19,528 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:49:19,770 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:19,770 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:49:19,770 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "BCH/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:49:19,771 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair BTC/EUR.
2020-06-02 09:49:34,293 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:34,294 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:49:34,531 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:34,531 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:49:34,773 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:34,773 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:49:35,018 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:35,018 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:49:35,262 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:49:35,262 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:49:35,262 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "BTC/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:49:35,263 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair DAI/EUR.
2020-06-02 09:49:42,742 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/DAI_EUR-trades.json.gz"
2020-06-02 09:49:44,050 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 55735
2020-06-02 09:49:44,128 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair DASH/EUR.
2020-06-02 09:49:53,596 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/DASH_EUR-trades.json.gz"
2020-06-02 09:49:55,659 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 86238
2020-06-02 09:49:55,762 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair EOS/EUR.
2020-06-02 09:50:04,245 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/EOS_EUR-trades.json.gz"
2020-06-02 09:50:06,094 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 78456
2020-06-02 09:50:06,192 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair ETC/EUR.
2020-06-02 09:50:18,835 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/ETC_EUR-trades.json.gz"
2020-06-02 09:50:21,047 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 87838
2020-06-02 09:50:21,154 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair ETH/EUR.
2020-06-02 09:50:34,075 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:50:34,075 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:50:34,326 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:50:34,326 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:50:34,578 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:50:34,578 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:50:34,823 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:50:34,823 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:50:35,061 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:50:35,061 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:50:35,061 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "ETH/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:50:35,062 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair LINK/EUR.
2020-06-02 09:50:47,228 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/LINK_EUR-trades.json.gz"
2020-06-02 09:50:49,380 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 88639
2020-06-02 09:50:49,472 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair LTC/EUR.
2020-06-02 09:51:03,520 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:03,520 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:51:03,768 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:03,768 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:51:04,070 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:04,070 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:51:04,315 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:04,315 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:51:04,555 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:04,555 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:51:04,555 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "LTC/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:51:04,555 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair QTUM/EUR.
2020-06-02 09:51:09,348 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/QTUM_EUR-trades.json.gz"
2020-06-02 09:51:10,315 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 39256
2020-06-02 09:51:10,358 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair REP/EUR.
2020-06-02 09:51:23,779 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/REP_EUR-trades.json.gz"
2020-06-02 09:51:25,748 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 85293
2020-06-02 09:51:25,835 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair WAVES/EUR.
2020-06-02 09:51:29,504 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/WAVES_EUR-trades.json.gz"
2020-06-02 09:51:30,134 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 26601
2020-06-02 09:51:30,168 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair XLM/EUR.
2020-06-02 09:51:45,474 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:45,474 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:51:45,719 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:45,720 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:51:46,611 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:46,611 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:51:46,851 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:46,851 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:51:47,094 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:51:47,094 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:51:47,095 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "XLM/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:51:47,095 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair XMR/EUR.
2020-06-02 09:52:01,309 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:01,309 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:52:01,554 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:01,555 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:52:02,470 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:02,470 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:52:02,727 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:02,727 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:52:02,972 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:02,972 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:52:02,973 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "XMR/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:52:02,973 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair XRP/EUR.
2020-06-02 09:52:17,552 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:17,552 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:52:17,793 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:17,793 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:52:18,038 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:18,038 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:52:18,284 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:18,285 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:52:18,533 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:18,533 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:52:18,533 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "XRP/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:52:18,533 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair XTZ/EUR.
2020-06-02 09:52:34,522 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:34,522 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:52:35,433 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:35,434 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:52:35,672 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:35,673 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:52:37,195 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:37,195 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 3 times
2020-06-02 09:52:37,444 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:37,444 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 2 times
2020-06-02 09:52:37,681 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:37,682 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 1 times
2020-06-02 09:52:37,922 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:37,923 - freqtrade.exchange.common - WARNING - retrying _async_fetch_trades() still for 0 times
2020-06-02 09:52:38,161 - freqtrade.exchange.common - WARNING - _async_fetch_trades() returned exception: "Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}"
2020-06-02 09:52:38,161 - freqtrade.exchange.common - WARNING - Giving up retrying: _async_fetch_trades()
2020-06-02 09:52:38,161 - freqtrade.data.history.history_utils - ERROR - Failed to download historic trades for pair: "XTZ/EUR". Error: Could not load trade history due to DDoSProtection. Message: kraken {"error":["EAPI:Rate limit exceeded"]}
2020-06-02 09:52:38,161 - freqtrade.data.history.history_utils - INFO - Downloading trades for pair ZEC/EUR.
2020-06-02 09:52:39,408 - freqtrade.misc - INFO - dumping json to "/home/1/freq-final/user_data/data/kraken/ZEC_EUR-trades.json.gz"
2020-06-02 09:52:40,500 - freqtrade.data.history.history_utils - INFO - New Amount of trades: 46446
2020-06-02 09:52:40,559 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/1/freq-final/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datetime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/1/freq-final/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/1/freq-final/freqtrade/commands/data_commands.py", line 61, in start_download_data
    data_format_trades=config['dataformat_trades'],
  File "/home/1/freq-final/freqtrade/data/history/history_utils.py", line 336, in convert_trades_to_ohlcv
    ohlcv = trades_to_ohlcv(trades, timeframe)
  File "/home/1/freq-final/freqtrade/data/converter.py", line 168, in trades_to_ohlcv
    df['datetime'] = pd.to_datetime(df['datetime'])
  File "/home/1/freq-final/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/1/freq-final/.env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'datetime'`

Then I want to run the command freqtrade backtesting -s myStrategy.

And then this one, if I'm not mistaken. freqtrade plot-dataframe --strategy myStrategy. I would like to look at ploting.

Thanks in advance.

**Comment by xmatthias** [comment] 2020-06-02 07:08
Kraken does very heavy rate limiting ...

therefore you MUST use a configuration (to allow setting the rate-limit correctly) - and change the following section:
Unfortunately, it'll be rather slow (1 request every 3 seconds) - but that's the only way to prevent kraken from blocking you. 


```json
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 3100
        },
```

In addition to that - Kraken does not provide the history correctly, but requires you to download raw trade data first (which is bigger, which slows the process down even more).

so your command will be:
```
freqtrade download-data --config configkraken.json --dl-trades 
```

You can also set `"download_trades": true` in the krakenconfig and can then omit the `--dl-trades` flg - this is also shown in the sample kraken configuration.

**Comment by hroff-1902** [comment] 2020-06-02 11:24
Duplicate of #3404 
(actually, this shows a way how #3404 can be reproduced)

**Closed** 2020-06-06 18:10 UTC
Labels: Data download, Duplicate, Question
