### ISSUE TITLE
Add support for Krakenfutures or at least Kraken Spot Margin

### ISSUE THREAD

**Issue by Schuck84** [freqtrade/freqtrade#10073] opened 2024-04-13 16:28 UTC
Hi,
after checking the cctx library it seems to be the case that different API calls are available for Krakenfutures.
I tried to figure out how the bot is connected to the cctx lib and the specific calls, but it's hard to understand how it works.

Could you maybe tell me where to start for adding support for Krakenfutures or Kraken spot market in margin mode?

Or will there be a support in the next time anyway?

Thanks

**Comment by stash86** [comment] 2024-04-13 16:33
Please search for past issues before opening a new one, especially for feature request.

Duplicate of #10051

**Closed as completed by stash86** 2024-04-13 16:33 UTC
Labels: Duplicate, Question

**Comment by xmatthias** [comment] 2024-04-13 18:07
aside from being a duplicate - spot markets are supported.
margin are not (for no exchange) - and futures are not supported for kraken.
