### ISSUE TITLE
bugs on calculation with DCA ON

### ISSUE THREAD

**Issue by AmirMassou94** [freqtrade/freqtrade#7235] opened 2022-08-16 07:49 UTC
I'm using the latest version for couple of days and face some bugs so I'm going to mention them right down here, before that I have to mention beside using latest version the other change is that I'm using DCA in my strategy (4 buy equally)

## Describe your environment

  * Operating system: Ubuntu 18.04.4 LTS
  * Python Version: 3.6.9 
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: docker-ed004236

## Describe the problem:

I'm using the latest version for couple of days and face some bugs which I noticed it might related to calculation bugs and/or updating database so I'm going to mention them right down here, before that I have to mention beside using latest version the other change is that I'm using DCA in my strategy (4 buy equally)
I wounder if it happens because of DCA or something else! the only change I made is updating and using latest freqtrade version and using DCA.
thanks

### Steps to reproduce:

  1. forcesell with having pending orders  result in freqtrade messed up with amount of coin and therfore couldnt handle the order anymore
  2. after forceselling with success I can see the trade wasnt close ,so I changed it at database
  3. after forcesell trigerd at confirm exit the open price had changed!!!! so profit and start balance... messed up with unreal numbers

**Comment by xmatthias** [comment] 2022-08-16 07:54
This is a duplicate of #7221 - and is being worked on.
what you describe seems to be most a consequence of this - so investigating this at this point (before a fix for the root problem is available) will not make sense.

best subscribe to that issue for updates on the fix.

Should other issues surface once the fix version is available, feel free to report them (they should appear with trades made with the fixed version only).

Please note (for an eventual future bug report):
The above will not really suffice to do any investigation.

We'll need logs of what's happening - as well as other information available (like messages / what orders were placed, ...) to reliably replicate the issue.

**Closed as completed** 2022-08-17 12:32 UTC
Labels: Duplicate
