### ISSUE TITLE
bybit unified account  - stoploss OrderNotFound

### ISSUE THREAD

**Issue by greg0071r** [freqtrade/freqtrade#9815] opened 2024-02-15 16:32 UTC
## Describe your environment

  * Operating system: Linux
  * Python Version: 3.10
  * CCXT version: CCXT 4.1.91
  * Freqtrade Version: 2024.2-dev-3d6079ae1
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Hello,
Thank you for the amazing freqtrade project.
I'm trading futures on bybit for a while but I'm suddenly getting the following recurring order not found warning in the log
It seems that Bybit has done some endpoint deprecation recently documented here :+1: 
https://github.com/ccxt/ccxt/issues/21167
They provide a workaround but not sure if it is applicable to freqtrade
The issue is happening only with the config stoploss_on_exchange = true

Thank you for your support

### Steps to reproduce:

Always
  
### Observed Results:

As a result, freqtrade is placing several times the same conditionnal order over and over to the same open trade.
After some time, it will lead to exchange temporary ban

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

WARNING - fetch_order() returned exception: "Order not found (pair: USTC/USDT:USDT id: 1ad32b5c-80d2-4ec7-b997-fa53e2ba4974). Message: Order 1ad32b5c-80d2-4ec7-b997-fa53e2ba4974 was not found.If you are trying to fetch SL/TP conditional order, you might try setting params["trigger"] = True". Retrying still for 1 times.
2024-02-15 17:22:18,087 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 17

**Comment by xmatthias** [comment] 2024-02-15 18:34
well based on your ccxt version - i'm not sure if your problem is not the other way around - like - your version is too old to be working against bybit.

The current, pinned ccxt version is 4.2.42 ... your's is 4.1.91 - which seems like 40 days behind (with the assumption that ccxt releases a new version roughly once every day lately).
Please use the [updating guide](https://www.freqtrade.io/en/latest/updating/) corresponding to your installation method to update your dependencies - and let me know if it still happens with the latest version (it does seem to work just fine for me, with both regular orders, as well as stop on exchange orders).

**Comment by greg0071r** [comment] 2024-02-15 19:04
Thank you for the reply
Indeed, I just updated all the required dependencies :-)

2024-02-15 19:52:58,079 - freqtrade.exchange.exchange - INFO - Using CCXT 4.2.42
2024-02-15 19:52:58,079 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-02-15 19:52:58,083 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'options': {'defaultType': 'swap'}}
2024-02-15 19:52:58,087 - freqtrade.exchange.exchange - INFO - Using Exchange "Bybit"

If I launch a trade then I get immediately the same warning :

2024-02-15 19:55:38,065 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: SLP/USDT:USDT id: fec21f56-4cd5-422a-b87c-3351774a2102). Message: Order fec21f56-4cd5-422a-b87c-3351774a2102 was not found.If you are trying to fetch SL/TP conditional order, you might try setting params["trigger"] = True". Retrying still for 5 times.
2024-02-15 19:55:38,065 - freqtrade.exchange.common - INFO - Applying DDosProtection backoff delay: 1

I think the issue is correlated to the recent bybit endpoint deprecation.
According to the comment in the https://github.com/ccxt/ccxt/issues/21167 we should opt for the fetch_open_orders method instead of the legacy fetch_order

**Comment by xmatthias** [comment] 2024-02-15 19:51
well i can't reproduce this - my (stop and regular) orders were found just well - which means it's most likely something to with your environment / setup.

I doubt the exchange will roll things out gradually - but i don't intend to fix things that can't be reproduced.

I'll do another test tomorrow - but if it doesn't reproduce, i'll close this as related to your environment (maybe your account/subaccount is unified - which is something we do not currently support).

**Comment by MariusB2-lab** [comment] 2024-02-15 20:08
Hello,
We are facing the same issue at my side trading on bybit when  stoploss_on_exchange = True

Thank you.

**Comment by xmatthias** [comment] 2024-02-16 06:18
Testing this with an unified sub-account - i can reproduce this - which explains what you're seeing.

I'd like to point out that freqtrade does **not** support unified accounts.
This is [clearly documented](https://www.freqtrade.io/en/stable/exchanges/#bybit) - and using unified accounts means that most likely, most calculations are slightly off (like liquidations, fees, ...) (freqtrade is not tested against unified subaccounts, and don't plan to add support for these at this point - although we're not actively checking for the account type, either - but might add a check for this in the future, should problems in this regards arrise).

To use freqtrade, please use a non-unified (aka standard) subaccount.

For non-unified (sub)accounts (the supported account type for bybit) this error is currently not present, fetching orders (both regular and stoploss orders) does work correctly - and trades are handled correctly and without problem (assuming the lastest develop version as of this morning - with uptodate dependencies).

When creating a sub-account, make sure to select the correct setting - as shown in the below screenshot.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/ab8172ee-8f86-47e4-abd5-22c00ed03f6f)



as we do not support unified accounts (and currently don't plan to) - i'm going to close this issue here.
Feel free to report should you encounter problems with a non-unified subaccount.

**Closed as not planned by xmatthias** 2024-02-16 06:18 UTC
Labels: Question - Outdated Version

**Comment by sandhuq** [comment] 2025-01-06 06:56
Bybit not allowing standard sub-account creation now ? will it work ?

**Comment by xmatthias** [comment] 2025-01-06 07:06
Yes it will (assuming you've got a recent freqtrade version). This issue is almost a year old now - things changed.
