### ISSUE TITLE
Issue when starting the bot 

### ISSUE THREAD

**Issue by iggyfrog** [freqtrade/freqtrade#4812] opened 2021-04-26 11:43 UTC
## Describe your environment

  * Operating system: Debian 10 64bit
  * Python Version: 2.7 
  * CCXT version: 1.48.76
  * Freqtrade Version: develop-e8555304
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

When starting bot I have error 

2021-04-26 14:42:26,807 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2021-04-26 14:42:27,221 - freqtrade.commands.trade_commands - ERROR - 'int' object has no attribute 'get'
2021-04-26 14:42:27,221 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/usr/local/freqtrade/freqtrade/commands/trade_commands.py", line 18, in start_trading
    worker = Worker(args)
  File "/usr/local/freqtrade/freqtrade/worker.py", line 35, in __init__
    self._init(False)
  File "/usr/local/freqtrade/freqtrade/worker.py", line 52, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/usr/local/freqtrade/freqtrade/freqtradebot.py", line 75, in __init__
    self.wallets = Wallets(self.config, self.exchange)
  File "/usr/local/freqtrade/freqtrade/wallets.py", line 37, in __init__
    self.update()
  File "/usr/local/freqtrade/freqtrade/wallets.py", line 123, in update
    self._update_live()
  File "/usr/local/freqtrade/freqtrade/wallets.py", line 104, in _update_live
    balances[currency].get('free', None),
AttributeError: 'int' object has no attribute 'get'

**Comment by xmatthias** [comment] 2021-04-26 11:53
Duplicate of #4810 ... 

please use the search before opening an issue to see if others reported the problem already.

**Closed as completed by xmatthias** 2021-04-26 11:53 UTC
Labels: Duplicate

**Comment by bjwie** [comment] 2021-04-26 15:13
deployment is not in place yet, how can I fix it on my own?

**Comment by xmatthias** [comment] 2021-04-26 16:45
Simply pull the latest image

**Comment by bjwie** [comment] 2021-04-26 16:56
works fine now, I think the MAC-OS build went wrong on first try. 
Thank you!
