### ISSUE TITLE
mexc: get_total_stake_amount() counting twice the amount in open orders

### ISSUE THREAD

**Issue by dnuno89** [freqtrade/freqtrade#10019] opened 2024-03-29 18:10 UTC
## Describe your environment

  * Operating system: Windows 11 and Ubuntu 23.10
  * Python Version: 3.11.8
  * CCXT version: 4.2.51
  * Freqtrade Version: 2024.2
  
## Describe the problem:

When there is an open order but it is not filled, wallets.get_total_stake_amount() returns a wrong value, counting twice the amount of the unfilled order. While right now I only have logs showing this behavior in exit orders, I think the first time I saw this happening was with entry orders.

### Steps to reproduce:

  1. print(self.wallets.get_total_stake_amount()) while having an open trade
  2. Create exit order at a price that won't be filled instantly
  3. print(self.wallets.get_total_stake_amount()) before exit order is filled.

Probably also happens with entry orders.
  
### Observed Results:

Total stake amount in steps 1. and 3. are different, should be the same value.

### Relevant code exceptions or logs
I have a custom logging function "logAndPrint" as shown in the code. Time difference in custom logs vs FT logs is due to UTC vs local time.

Code used to print total stake:
  ```
stake_in = Trade.total_open_trades_stakes()
moneyTotal = self.wallets.get_total_stake_amount()
freeUSDT = self.wallets.get_free('USDT')
usedUSDT = self.wallets.get_used('USDT')
totalUSDT = self.wallets.get_total('USDT')
self.logAndPrint(f'moneyTotal:{moneyTotal}, freeUSDT:{freeUSDT}, usedUSDT:{usedUSDT}, totalUSDT:{totalUSDT}, stake_in:{stake_in}')
  ```

Case 1:
  ```
2024-03-29 09:01:01,364 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
2024-03-29 09:02:01,366 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
2024-03-29 09:02:37,466 - freqtrade.freqtradebot - INFO - Exit for PMPY/USDT detected. Reason: roi
2024-03-29 09:02:37,943 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 09:02:38,255 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 134, 'exchange': 'Mexc', 'pair': 'PMPY/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.029929, 'order_rate': 0.029929, 'order_type': 'limit', 'amount': 935.6, 'open_rate': 0.030171, 'close_rate': 0.029929, 'current_rate': 0.029929, 'profit_amount': -0.28264476, 'profit_ratio': -0.01000292, 'buy_tag': 'lambo1 ', 'enter_tag': 'lambo1 ', 'exit_reason': 'roi', 'open_date': datetime.datetime(2024, 3, 29, 5, 0, 33, 978020, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 8, 2, 38, 255276, tzinfo=datetime.timezone.utc), 'stake_amount': 28.2279876, 'stake_currency': 'USDT', 'base_currency': 'PMPY', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0, 'final_profit_ratio': None, 'is_final_exit': False}
2024-03-29 09:02:39,377 - freqtrade.wallets - INFO - Wallets synced.

2024/03/29, 08:02:39 - moneyTotal:504.31265051932087, freeUSDT:323.2760140962837, usedUSDT:0, totalUSDT:323.2760140962837, stake_in:186.1307036

2024-03-29 09:02:42,174 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=134, pair=PMPY/USDT, amount=935.60000000, is_short=False, leverage=1.0, open_rate=0.03017100, open_since=2024-03-29 05:00:33)
2024-03-29 09:02:42,814 - freqtrade.persistence.trade_model - INFO - Updating trade (id=134) ...
2024-03-29 09:02:42,814 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=134, pair=PMPY/USDT, amount=935.60000000, is_short=False, leverage=1.0, open_rate=0.03017100, open_since=2024-03-29 05:00:33).
2024-03-29 09:02:42,815 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=134, pair=PMPY/USDT, amount=935.60000000, is_short=False, leverage=1.0, open_rate=0.03017100, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2024-03-29 09:02:43,177 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 09:02:43,259 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 134, 'exchange': 'Mexc', 'pair': 'PMPY/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.029983594858914064, 'order_rate': 0.029983594858914064, 'order_type': 'limit', 'amount': 935.6, 'open_rate': 0.030171, 'close_rate': 0.029983594858914064, 'current_rate': None, 'profit_amount': -0.23161689, 'profit_ratio': -0.00819702, 'buy_tag': 'lambo1 ', 'enter_tag': 'lambo1 ', 'exit_reason': 'roi', 'open_date': datetime.datetime(2024, 3, 29, 5, 0, 33, 978020, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 8, 2, 42, 174000, tzinfo=datetime.timezone.utc), 'stake_amount': 28.2279876, 'stake_currency': 'USDT', 'base_currency': 'PMPY', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': -0.23161689, 'final_profit_ratio': -0.008197024448724942, 'is_final_exit': True}
2024-03-29 09:02:43,259 - freqtrade.rpc.discord - INFO - Sending discord message: {'type': exit_fill, 'trade_id': 134, 'exchange': 'Mexc', 'pair': 'PMPY/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.029983594858914064, 'order_rate': 0.029983594858914064, 'order_type': 'limit', 'amount': 935.6, 'open_rate': 0.030171, 'close_rate': 0.029983594858914064, 'current_rate': None, 'profit_amount': -0.23161689, 'profit_ratio': -0.00819702, 'buy_tag': 'lambo1 ', 'enter_tag': 'lambo1 ', 'exit_reason': 'roi', 'open_date': datetime.datetime(2024, 3, 29, 5, 0, 33, 978020, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 8, 2, 42, 174000, tzinfo=datetime.timezone.utc), 'stake_amount': 28.2279876, 'stake_currency': 'USDT', 'base_currency': 'PMPY', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': -0.23161689, 'final_profit_ratio': -0.008197024448724942, 'is_final_exit': True}
2024-03-29 09:02:43,753 - cooldown_period - INFO - Cooldown for PMPY/USDT for 4 candles.
2024-03-29 09:02:43,757 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': protection_trigger, 'base_currency': 'PMPY', 'id': 267, 'pair': 'PMPY/USDT', 'lock_time': '2024-03-29 08:02:43', 'lock_timestamp': 1711699363752, 'lock_end_time': '2024-03-29 08:25:00', 'lock_end_timestamp': 1711700700000, 'reason': 'Cooldown period for 4 candles.', 'side': '*', 'active': True}

2024/03/29, 08:02:45 - moneyTotal:476.3669427953208, freeUSDT:323.2760140962837, usedUSDT:0, totalUSDT:323.2760140962837, stake_in:157.902716

2024-03-29 09:03:01,367 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
2024-03-29 09:04:08,171 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
  ```

Case 2:
  ```
2024-03-29 17:39:54,074 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 17:39:54,077 - freqtrade.freqtradebot - INFO - User denied exit for KREST/USDT.
2024-03-29 17:39:54,077 - freqtrade.freqtradebot - INFO - Exit for KREST/USDT detected. Reason: roi
2024-03-29 17:39:54,598 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 17:39:54,600 - freqtrade.freqtradebot - INFO - User denied exit for KREST/USDT.
2024-03-29 17:40:01,147 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 17:40:01,784 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for SCOTTY/USDT with stake_amount: 23.130088279059102 ...
2024-03-29 17:40:01,787 - freqtrade.freqtradebot - INFO - User denied entry for SCOTTY/USDT.
2024-03-29 17:40:29,331 - freqtrade.freqtradebot - INFO - Exit for KREST/USDT detected. Reason: custom_exit
2024-03-29 17:40:29,915 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 17:40:30,222 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 143, 'exchange': 'Mexc', 'pair': 'KREST/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.85723, 'order_rate': 0.85723, 'order_type': 'limit', 'amount': 96.55, 'open_rate': 0.83821, 'close_rate': 0.85723, 'current_rate': 0.85723, 'profit_amount': 1.67268627, 'profit_ratio': 0.02064787, 'buy_tag': 'clucHA ', 'enter_tag': 'clucHA ', 'exit_reason': 'Punct sell - stake_min:-103.55713941234775', 'open_date': datetime.datetime(2024, 3, 29, 14, 50, 21, 463362, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 16, 40, 30, 222727, tzinfo=datetime.timezone.utc), 'stake_amount': 80.9291755, 'stake_currency': 'USDT', 'base_currency': 'KREST', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0, 'final_profit_ratio': None, 'is_final_exit': False}
2024-03-29 17:40:31,990 - freqtrade.wallets - INFO - Wallets synced.

2024/03/29, 16:40:32 - moneyTotal:567.4555405020354, freeUSDT:330.4980641485207, usedUSDT:0, totalUSDT:330.4980641485207, stake_in:242.6893505

2024-03-29 17:40:34,927 - freqtrade.worker - INFO - Bot heartbeat. PID=984815, version='2024.2', state='RUNNING'
2024-03-29 17:40:36,672 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=143, pair=KREST/USDT, amount=96.55000000, is_short=False, leverage=1.0, open_rate=0.83821000, open_since=2024-03-29 14:50:21)
2024-03-29 17:40:37,188 - freqtrade.persistence.trade_model - INFO - Updating trade (id=143) ...
2024-03-29 17:40:37,188 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=143, pair=KREST/USDT, amount=96.55000000, is_short=False, leverage=1.0, open_rate=0.83821000, open_since=2024-03-29 14:50:21).
2024-03-29 17:40:37,189 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=143, pair=KREST/USDT, amount=96.55000000, is_short=False, leverage=1.0, open_rate=0.83821000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2024-03-29 17:40:37,688 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 17:40:37,692 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 143, 'exchange': 'Mexc', 'pair': 'KREST/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.85999, 'order_rate': 0.85999, 'order_type': 'limit', 'amount': 96.55, 'open_rate': 0.83821, 'close_rate': 0.85999, 'current_rate': None, 'profit_amount': 1.93889779, 'profit_ratio': 0.02393402, 'buy_tag': 'clucHA ', 'enter_tag': 'clucHA ', 'exit_reason': 'Punct sell - stake_min:-103.55713941234775', 'open_date': datetime.datetime(2024, 3, 29, 14, 50, 21, 463362, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 16, 40, 36, 672000, tzinfo=datetime.timezone.utc), 'stake_amount': 80.9291755, 'stake_currency': 'USDT', 'base_currency': 'KREST', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 1.93889779, 'final_profit_ratio': 0.023934024005605112, 'is_final_exit': True}
2024-03-29 17:40:37,692 - freqtrade.rpc.discord - INFO - Sending discord message: {'type': exit_fill, 'trade_id': 143, 'exchange': 'Mexc', 'pair': 'KREST/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.85999, 'order_rate': 0.85999, 'order_type': 'limit', 'amount': 96.55, 'open_rate': 0.83821, 'close_rate': 0.85999, 'current_rate': None, 'profit_amount': 1.93889779, 'profit_ratio': 0.02393402, 'buy_tag': 'clucHA ', 'enter_tag': 'clucHA ', 'exit_reason': 'Punct sell - stake_min:-103.55713941234775', 'open_date': datetime.datetime(2024, 3, 29, 14, 50, 21, 463362, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 16, 40, 36, 672000, tzinfo=datetime.timezone.utc), 'stake_amount': 80.9291755, 'stake_currency': 'USDT', 'base_currency': 'KREST', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 1.93889779, 'final_profit_ratio': 0.023934024005605112, 'is_final_exit': True}
2024-03-29 17:40:38,200 - cooldown_period - INFO - Cooldown for KREST/USDT for 4 candles.
2024-03-29 17:40:38,210 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': protection_trigger, 'base_currency': 'KREST', 'id': 282, 'pair': 'KREST/USDT', 'lock_time': '2024-03-29 16:40:38', 'lock_timestamp': 1711730438191, 'lock_end_time': '2024-03-29 17:05:00', 'lock_end_timestamp': 1711731900000, 'reason': 'Cooldown period for 4 candles.', 'side': '*', 'active': True}

2024/03/29, 16:40:40 - moneyTotal:487.3356567570355, freeUSDT:330.4980641485207, usedUSDT:0, totalUSDT:330.4980641485207, stake_in:161.760175

2024-03-29 17:41:40,010 - freqtrade.worker - INFO - Bot heartbeat. PID=984815, version='2024.2', state='RUNNING'
2024-03-29 17:42:43,170 - freqtrade.worker - INFO - Bot heartbeat. PID=984815, version='2024.2', state='RUNNING'
2024-03-29 17:43:46,245 - freqtrade.worker - INFO - Bot heartbeat. PID=984815, version='2024.2', state='RUNNING'
2024-03-29 17:44:48,815 - freqtrade.worker - INFO - Bot heartbeat. PID=984815, version='2024.2', state='RUNNING'

2024/03/29, 16:45:01 - moneyTotal:487.3356567570355, freeUSDT:330.4980641485207, usedUSDT:0, totalUSDT:330.4980641485207, stake_in:161.760175

2024-03-29 17:45:52,868 - freqtrade.worker - INFO - Bot heartbeat. PID=984815, version='2024.2', state='RUNNING'
  ```

Case 3:
  ```
2024-03-29 11:15:01,307 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
2024-03-29 11:15:23,718 - freqtrade.freqtradebot - INFO - Exit for TABOO/USDT detected. Reason: custom_exit
2024-03-29 11:15:24,022 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 11:15:24,347 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 138, 'exchange': 'Mexc', 'pair': 'TABOO/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.0024339, 'order_rate': 0.0024339, 'order_type': 'limit', 'amount': 22872.65, 'open_rate': 0.002483831189564829, 'close_rate': 0.0024339, 'current_rate': 0.0024339, 'profit_amount': -1.25454017, 'profit_ratio': -0.02206033, 'buy_tag': 'lambo1 ', 'enter_tag': 'lambo1 ', 'exit_reason': 'Punct sell - stake_min:-50.05650836526119', 'open_date': datetime.datetime(2024, 3, 29, 8, 50, 27, 169891, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 10, 15, 24, 347527, tzinfo=datetime.timezone.utc), 'stake_amount': 56.811801458, 'stake_currency': 'USDT', 'base_currency': 'TABOO', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0, 'final_profit_ratio': None, 'is_final_exit': False}
2024-03-29 11:15:26,123 - freqtrade.wallets - INFO - Wallets synced.

2024/03/29, 10:15:26 - moneyTotal:533.5024068714142, freeUSDT:389.2025816141357, usedUSDT:0, totalUSDT:389.2025816141357, stake_in:149.688738458

2024-03-29 11:15:32,345 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=138, pair=TABOO/USDT, amount=22872.65000000, is_short=False, leverage=1.0, open_rate=0.00248383, open_since=2024-03-29 08:50:27)
2024-03-29 11:15:32,886 - freqtrade.persistence.trade_model - INFO - Updating trade (id=138) ...
2024-03-29 11:15:32,886 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=138, pair=TABOO/USDT, amount=22872.65000000, is_short=False, leverage=1.0, open_rate=0.00248383, open_since=2024-03-29 08:50:27).
2024-03-29 11:15:32,887 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=138, pair=TABOO/USDT, amount=22872.65000000, is_short=False, leverage=1.0, open_rate=0.00248383, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2024-03-29 11:15:33,451 - freqtrade.wallets - INFO - Wallets synced.
2024-03-29 11:15:33,547 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 138, 'exchange': 'Mexc', 'pair': 'TABOO/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.0024346, 'order_rate': 0.0024346, 'order_type': 'limit', 'amount': 22872.65, 'open_rate': 0.002483831189564829, 'close_rate': 0.0024346, 'current_rate': None, 'profit_amount': -1.23854532, 'profit_ratio': -0.02177907, 'buy_tag': 'lambo1 ', 'enter_tag': 'lambo1 ', 'exit_reason': 'Punct sell - stake_min:-50.05650836526119', 'open_date': datetime.datetime(2024, 3, 29, 8, 50, 27, 169891, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 10, 15, 32, 345000, tzinfo=datetime.timezone.utc), 'stake_amount': 56.811801458, 'stake_currency': 'USDT', 'base_currency': 'TABOO', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': -1.23854532, 'final_profit_ratio': -0.021779066676889884, 'is_final_exit': True}
2024-03-29 11:15:33,552 - freqtrade.rpc.discord - INFO - Sending discord message: {'type': exit_fill, 'trade_id': 138, 'exchange': 'Mexc', 'pair': 'TABOO/USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'loss', 'limit': 0.0024346, 'order_rate': 0.0024346, 'order_type': 'limit', 'amount': 22872.65, 'open_rate': 0.002483831189564829, 'close_rate': 0.0024346, 'current_rate': None, 'profit_amount': -1.23854532, 'profit_ratio': -0.02177907, 'buy_tag': 'lambo1 ', 'enter_tag': 'lambo1 ', 'exit_reason': 'Punct sell - stake_min:-50.05650836526119', 'open_date': datetime.datetime(2024, 3, 29, 8, 50, 27, 169891, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2024, 3, 29, 10, 15, 32, 345000, tzinfo=datetime.timezone.utc), 'stake_amount': 56.811801458, 'stake_currency': 'USDT', 'base_currency': 'TABOO', 'quote_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': -1.23854532, 'final_profit_ratio': -0.021779066676889884, 'is_final_exit': True}
2024-03-29 11:15:33,978 - cooldown_period - INFO - Cooldown for TABOO/USDT for 4 candles.
2024-03-29 11:15:33,984 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': protection_trigger, 'base_currency': 'TABOO', 'id': 271, 'pair': 'TABOO/USDT', 'lock_time': '2024-03-29 10:15:33', 'lock_timestamp': 1711707333975, 'lock_end_time': '2024-03-29 10:40:00', 'lock_end_timestamp': 1711708800000, 'reason': 'Cooldown period for 4 candles.', 'side': '*', 'active': True}

2024/03/29, 10:15:35 - moneyTotal:477.2587234279943, freeUSDT:389.2025816141357, usedUSDT:0, totalUSDT:389.2025816141357, stake_in:92.876937

2024-03-29 11:16:03,254 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
2024-03-29 11:17:07,237 - freqtrade.worker - INFO - Bot heartbeat. PID=3033736, version='2024.2', state='RUNNING'
  ```

**Comment by xmatthias** [comment] 2024-03-29 18:19
Your report is missing probably the most important point - is this dry-run - or live?

**Comment by dnuno89** [comment] 2024-03-29 19:12
Sorry, this is live trading.

**Comment by xmatthias** [comment] 2024-03-29 20:12
mexc an unsupported exchange - and i haven't observed similar behavior with other, supported exchanges before (nor does it reproduce in dry-run, nor on binance live).
While freqtrade does in theory support all exchanges mexc supports - in detail there's often differences in the details.


As such, this is most likely related to how mexc returns values.

Please provide logs for this with `exchange.log_responses` - which will show what mexc is actually returning.

Now on a side note: Mexc is an exchange we do not support (not only because it's showing very suspicious behavior like disabling BTC/ETH pairs trading through the api for "regular" users) - and is one we don't aim to actively support, either.

**Comment by dnuno89** [comment] 2024-04-02 14:19
Thanks for the explanation. I've been checking my logs and I found this behavior happening in both Mexc and Kucoin (also not supported but confirmed to work by the community), and confirmed this issue does not happen in both Gate.io and Htx (both officially supported). 

I'll be gathering more logs with ```exchange.log_responses``` so I can provide a better report for those exchanges in the following days.

**Comment by xmatthias** [comment] 2024-04-07 12:19
Going to close this for now - as it seems to only apply to non-supported exchanges (there's a reason they're not supported).

Happy to look at this if it happens on one of the supported exchanges though ... but that doesn't seem to be the case.

**Closed as completed by xmatthias** 2024-04-07 12:19 UTC
Labels: unsupported exchange
