### ISSUE TITLE
WARNING - Can't open a new trade for KSM/EUR: stake amount is too small (41.69480436 < 66.464)

### ISSUE THREAD

**Issue by MrHumanRebel** [freqtrade/freqtrade#4578] opened 2021-03-19 15:09 UTC
Operating system: latest linux mint 64bit
Python Version: latest stable 2021.03.19.
Freqtrade Version: latest stable 2021.03.19.
  
Hi!

I want to disable stoploss and i set it to -200 as a read through previos issues like this, but for two days now i've been getting this error again and again, so the bot basically is not doing anything according to my strategy. I don't understand why this error is still present with stoploss disabled. (The strategy is very quick and does not need any stoploss, it could lose more money with stoploss enabled) 
Thanks in advance for any help!

Here is my config:
Account balance is currently 84 EUR!
The exchange is kraken and rate limit is correctly set to 3100.
Edge is disabled.
{
    "max_open_trades": 2,
    "stake_currency": "EUR",
    "stake_amount": "unlimited",
    "tradable_balance_ratio": 0.99,
    "amend_last_stake_amount": true,
    "fiat_display_currency": "EUR",
    "timeframe": "5m",
    "dry_run": false,
    "dry_run_wallet": 1000,
    "cancel_open_orders_on_exit": false,
    "unfilledtimeout": {
        "buy": 10,
        "sell": 30
    },

Here is the terminal error:
2021-03-19 14:45:32,651 - freqtrade.wallets - INFO - Wallets synced.
2021-03-19 14:45:32,659 - freqtrade.freqtradebot - INFO - Buy signal found: about create a new trade with stake_amount: 41.69480436 ...
2021-03-19 14:45:32,660 - freqtrade.freqtradebot - INFO - Executing Buy for KSM/EUR
2021-03-19 14:45:32,660 - freqtrade.freqtradebot - INFO - Using Last Bid / Last Price
2021-03-19 14:45:35,659 - freqtrade.freqtradebot - WARNING - Can't open a new trade for KSM/EUR: stake amount is too small (41.69480436 < 66.464)
2021-03-19 14:45:35,848 - freqtrade.worker - INFO - Bot heartbeat. PID=24443, version='develop-766c786d', state='RUNNING'

This messeage was the same for many other coins too, like XRP, BTC, UNI etc...

**Comment by dbeybia** [comment] 2021-03-19 18:36
84 (account balance) / max_open_trades (2) < 66 which is the value the bot has calculated for the trade. (LIMIT buy). You either reduce max_open_trades or add more balance to your account.

**Comment by xmatthias** [comment] 2021-03-19 19:55
it's the 2nd time i've seen this with kraken ... i don't think the 66 is justified.

according to the [kraken page](https://support.kraken.com/hc/en-us/articles/205893708-Minimum-order-size-volume-for-trading), the limit should be 0.1 KSM, or 5 EUR.
Now with the current price of KSM (around 326.54) - the minimum tradable limit for manual trades will be around 33€ (0.1 * 326.54).

---

freqtrade will not allow you to buy 0.1 KSM (or 5EUR) unless you use a very tight stoploss, but it'll require some room between the "minimum tradable" and the real value, to allow to place a stoploss below entry should the trade go south (even if you don't use stoploss but rely on sell-signals, you'll still need this room - as every trade has a certain risk of going south, and you'll not want to be stuck in a trade with "can't sell because you're below limit").

the Stoploss of -2 will be "kindof" ignored (this offset is capped at 0.5) - so the correct value should be around 33 + (33 * 0.5) - which will be 49€ (and is therewith still below your available limit).

**Comment by MrHumanRebel** [comment] 2021-03-19 21:33
So am I stuck with the only option to fund my kraken account with more stake money than 84 EUR? Do you have any other ideas? 
What do you guys recommend? 
By the way, thanks for the quick reply and help, this program is awesome though.

**Comment by xmatthias** [comment] 2021-03-20 05:41
the real limits depend on the pairs you trade.
so while for KSM, the limit kraken is 33E at the moment (+ 50% with a big stoploss), this is caused by the relatively high price.

I'd expect kraken to adjust the limit sometime in the future to the high price - but noone can tell when / if this will happen.

While there is a bug in the calculation causing the 65€ result - the new result (fixing atm) for KSM will be 49€.

Other pairs (e.g. ADA/EUR) would have this (new) limit at 39€ - so by simply picking other pairs you should be good for now (although one lost trade will drop you below the limit again).

You can limit the bot to 1 pair - so it'll have enough money left - but that may or may not play along with your strategy.


Personally, i find kraken's limits at the moment pretty inflated - especially considering that binance limits will be between 15$ and 17$ (including the 50% drop margin) already.

**Comment by MrHumanRebel** [comment] 2021-03-20 07:15
Thanks for the tip and the quick help, when the update will be available? (Estimated) And on which release channel?

**Comment by xmatthias** [comment] 2021-03-20 07:21
All changes will be in develop first (like - now) - and will usually land in the next stable release - which is basically a snapshot of develop from around the end of the month.

**Closed as completed** 2021-03-20 07:21 UTC
Labels: Bug
