### ISSUE TITLE
Feature request - replace TALib with bta-lib

### ISSUE THREAD

**Issue by magick93** [freqtrade/freqtrade#3063] opened 2020-03-14 22:14 UTC
## Step 1: Have you search for this issue before posting it?

Yes

## Feature Request details

- https://github.com/mementum/bta-lib is a drop in replacement for TALib.
- TALib hasnt been updated for a longtime, where bta-lib has a active community
- It allows for adding additional, custom indicators written in Python
- More info at https://btalib.backtrader.com/

**Comment by hroff-1902** [comment] 2020-03-14 22:41
Thanks for pointing to an alternative, but I do not think it can be used as the replacement in the current state:

* it's a new project, only 45 days old
* no references to other projects using it, the performance is unknown
* no open and closed issues/pr in the project, so the support level is unknown
* no data on how the return values for various indicators are close to ones returned by ta-lib and/or tradingview...

I do not see "active community" you mentioned.
Maybe in an year or so, if the project gets more mature by that time...

**Comment by hroff-1902** [comment] 2020-03-14 22:47
Just recalled: I also found it couple of weeks ago: https://github.com/freqtrade/freqtrade/issues/2509#issuecomment-592996415

I personally like the approach this lib is designed and implemented, but see the points above: it's now just one of the possible replacements, I guess it's not ready yet to be the winner of the "competition".

**Comment by xmatthias** [comment] 2020-03-15 08:18
I would propose to close this issue as it's technically a duplicate of #2509 ... 

I think it's clear that mid-term we'll try to replace ta-lib - but it's unclear with what. this might be one candidate, but it's certainly not the only one.

**Comment by hroff-1902** [comment] 2020-03-20 04:12
closing it as duplicate issue

**Closed by hroff-1902** 2020-03-20 04:12 UTC
Labels: Duplicate, Enhancement

**Comment by Fredrik81** [comment] 2020-03-20 15:03
Just want to throw in panda-ta into the mix. It has some good sides

**Comment by xmatthias** [comment] 2020-03-20 15:05
@Fredrik81 #2509  please ... ;)
