### ISSUE TITLE
bot "lost" order, cannot sell position

### ISSUE THREAD

**Issue by squat0001** [freqtrade/freqtrade#3650] opened 2020-08-02 09:48 UTC
## Describe your environment

current freqtrade checkout
```
root@trade:/srv/freqtrade# git describe --tags
2020.6

```

## Describe the problem:

i stopped the bot, changed in the config file the stake amount form 400 to 2000.
the bot had some open positions at the time of change, now he cannot sell.
  
### Observed Results:
```

Aug  2 11:08:37 trade python[15148]: 2020-08-02 11:08:37,889 - freqtrade.wallets - INFO - Wallets synced.
Aug  2 11:08:37 trade python[15148]: 2020-08-02 11:08:37,890 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 55.27, Wallet: 0.01506
Aug  2 11:08:42 trade python[15148]: 2020-08-02 11:08:42,401 - freqtrade.freqtradebot - INFO - Executing Sell for ETC/USDT. Reason: SellType.TRAILING_STOP_LOSS
Aug  2 11:08:43 trade python[15148]: 2020-08-02 11:08:43,404 - freqtrade.wallets - INFO - Wallets synced.
Aug  2 11:08:43 trade python[15148]: 2020-08-02 11:08:43,405 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 55.27, Wallet: 0.01506
Aug  2 11:08:47 trade python[15148]: 2020-08-02 11:08:47,881 - freqtrade.freqtradebot - INFO - Executing Sell for ETC/USDT. Reason: SellType.TRAILING_STOP_LOSS
Aug  2 11:08:48 trade python[15148]: 2020-08-02 11:08:48,155 - freqtrade.wallets - INFO - Wallets synced.
Aug  2 11:08:48 trade python[15148]: 2020-08-02 11:08:48,156 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 55.27, Wallet: 0.01506
Aug  2 11:08:52 trade python[15148]: 2020-08-02 11:08:52,404 - freqtrade.freqtradebot - INFO - Executing Sell for ETC/USDT. Reason: SellType.TRAILING_STOP_LOSS

```

forcesell.. results in:

```
Aug  2 11:29:36 trade python[15148]: 2020-08-02 11:29:36,880 - freqtrade.rpc.telegram - INFO - Executing handler: _forcesell for chat_id: 984997315
Aug  2 11:29:36 trade python[15148]: 2020-08-02 11:29:36,887 - freqtrade.freqtradebot - INFO - Using cached sell rate for ETC/USDT.
Aug  2 11:29:37 trade python[15148]: 2020-08-02 11:29:37,653 - freqtrade.wallets - INFO - Wallets synced.
Aug  2 11:29:37 trade python[15148]: 2020-08-02 11:29:37,654 - freqtrade.rpc.telegram - ERROR - Exception occurred within Telegram module
Aug  2 11:29:37 trade python[15148]: Traceback (most recent call last):
Aug  2 11:29:37 trade python[15148]:   File "/srv/freqtrade/freqtrade/rpc/telegram.py", line 53, in wrapper
Aug  2 11:29:37 trade python[15148]:     return command_handler(self, *args, **kwargs)
Aug  2 11:29:37 trade python[15148]:   File "/srv/freqtrade/freqtrade/rpc/telegram.py", line 474, in _forcesell
Aug  2 11:29:37 trade python[15148]:     msg = self._rpc_forcesell(trade_id)
Aug  2 11:29:37 trade python[15148]:   File "/srv/freqtrade/freqtrade/rpc/rpc.py", line 489, in _rpc_forcesell
Aug  2 11:29:37 trade python[15148]:     _exec_forcesell(trade)
Aug  2 11:29:37 trade python[15148]:   File "/srv/freqtrade/freqtrade/rpc/rpc.py", line 466, in _exec_forcesell
Aug  2 11:29:37 trade python[15148]:     self._freqtrade.execute_sell(trade, current_rate, SellType.FORCE_SELL)
Aug  2 11:29:37 trade python[15148]:   File "/srv/freqtrade/freqtrade/freqtradebot.py", line 1079, in execute_sell
Aug  2 11:29:37 trade python[15148]:     amount = self._safe_sell_amount(trade.pair, trade.amount)
Aug  2 11:29:37 trade python[15148]:   File "/srv/freqtrade/freqtrade/freqtradebot.py", line 1047, in _safe_sell_amount
Aug  2 11:29:37 trade python[15148]:     f"Not enough amount to sell. Trade-amount: {amount}, Wallet: {wallet_amount}")
Aug  2 11:29:37 trade python[15148]: freqtrade.exceptions.DependencyException: Not enough amount to sell. Trade-amount: 55.27, Wallet: 0.01506

```

**Comment by xmatthias** [comment] 2020-08-02 12:22
I don't think this has anything to do with changing the stake amount (stake-amount is not relevant for selling - there all values come from the trade object - which is created when buying).

The bot "thinks" it owns 55.27 ETC - while your wallet only shows 0.015 ETC.

This can have multiple reasons - maybe it was sold on the exchange - or something else happed (which however is not covered in the logs provided) - but most likely, whatever happened, did not happen in the restarted bot - but in the previous one - and should therefore be in these logs.

**Comment by xmatthias** [comment] 2020-08-11 07:03
@squat0001 have you still got the logs of the "old" / prior bot around? if not, i think we'll have to close this issue - as the log above is only showing the symtom, but not the cause of the problem.

**Comment by squat0001** [comment] 2020-08-23 17:24
is the API really that way broken, that orders are gone missing? even if the api returns an order id?
i don't think so (i read the link to the problem from slack).

so the states are:
- place order, get order id
STATE: order_submitted (which is not shown in the binance api)

- after some time you get the current state of the order which is:
in case the order is still alive:
STATE: order_submitted_successfully
in case the order never got submitted
STATE: could_not_submitted
in case the order got cancled
STATE: order_canceled
in case the order got fullfilled
STATE: order_fullfilled
.
.

so the only thing to do is just "remember" the order id
even things like.. a sell signal or cancel .. just submit the new order.

**Comment by xmatthias** [comment] 2020-08-23 17:33
Keep in mind that freqtrade is not a binance only bot.

Other exchanges completely remove the order from their store if it's cancelled (as if it's never been placed). 
So no, the problem is not that simple.

**Closed** 2020-09-19 15:12 UTC
Labels: Bug
