### ISSUE TITLE
Feature request, Make config class a dataclass or similar

### ISSUE THREAD

**Issue by PabloRuizCuevas** [freqtrade/freqtrade#9709] opened 2024-01-21 19:12 UTC
Pablo: we could also consider making configuration a dataclass instead of using a dictionary.

@xmatthias : No, dataclass is absolutely the wrong approach for this.
configuration can have arbitrary keys (we won't know what a user submits, could be stake_amountNOTAKTIVE) - which will have no effect in the current approach - but would fail when it's a dataclass, as this is not a known key.

While there are potential, other alternatives - i don't think they will provide much benefits over the current approach (at least not considering the time-invest - and that the time can be better spent in a way that actually improves bot behavior / functionality).

## Describe the enhancement

Hi, thanks again for your reply, just wanted to come back to this.

At the end you know much more from the codebase, so feel free to close the issue, but i was quickly checking it and the current way that Config operates makes the API hard to use, as many functions have their arguments obscured by layers of functions, therefore is also hard to do protocols for them.

Using dataclass (or similar, pydantic is also a good choice) ,  we can still let the user put his own arguments as long as we do something like this:

```python
@dataclass
class Config:
    pairlists: list[str] | None
    user_defined: dict[str, Any] | None  # the parser would put everything that is not used by the code,  here.

```

For compatibility we can also make it with string accessor:

```python
def __getitem__(self, key):
    return getattr(self, key)
```
        
The adventage of this is that i can for instance make a protocol for :
 

```python
class Subclass(Protocol):
    other: str

class ConfigDownload(Protocol):
    days: int
    pairs: list[str]
    other: Subclass

 def download_data_main(config: ConfigDownload) -> None:   # instead of Config
 
```

So if i call history_utils.download_data_main then i know exactly what arguments should I provide, even if i can just pass the config one.

Other very similar result could be obtained using typedict, which will need even less modifications, but i guess is not in use because is quite a new addition in python.

just to be clear, i understand that this may not be the priority, but I'm new in the codebase and wanted to share this thoughts. thanks

**Comment by xmatthias** [comment] 2024-01-22 05:47
Your "pydantic" approach fails as you assume "config.user_defined" can be used ... however - the strategy already exists and uses the keys at the lowest level (or a nested structure, or whatever). That'd be a breaking change - for no good reason.
To keep compatibility, your accessor would need to simulate that behavior - but what did you gain, then? 

---

This is actually a duplicate of the oldest still open issue (#36) (please use the search to look if issues about similar topics are already open).

As the age of that issue will tell you - this has no priority, and to be fair, i'm not sure it'll ACTUALLY give us benefits, so while it's still open - i'm not entirely sure it'll ever be implemented (it's also clearly not an issue suited for new contributors).

The only way i **eventually** see this happening is through a direct subclass of dict (or something that simulates behavior of the dict to almost 100%). That'll however not really give us benefits, at least not any i can see.

What i don't see
* replace all usages of config within the codebase to use a new approach (way too much effort / error prone)
* use multiple different classes for different functions (the maintenance effort for this would be WAY too high)

What's left then is a simple "we want `dict` to be named `Config` (or whatever name we give it)" ... but the codebase didn't necessarily gain anything other than a new class. 

It's also not really a "feature" in that sense (a user won't gain anything from this - most likely even a small performance penalty, as it's now doing more than a plain dict). 
It MIGHT improve maintainability slightly - but at the same time also increment the maintenance burden at the same time - so i think, time is better spent on other topics (there's quite a few enhancement requests open, waiting for someone to actually pick them up).

Closing as duplicate of #36

**Closed as completed by xmatthias** 2024-01-22 05:47 UTC
Labels: Duplicate
