### ISSUE TITLE
Allow custom entry price from strategy

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#5102] opened 2021-06-08 15:51 UTC
**Description**
Now in freqtrade the entry price used in a new buy limit order is defined by market price or prices already existing in the order book.

This entry strategy have goods but also downsides, it can provide a quick entry, but not at the cheapest price.
It's really hard to make profits in short time frames (1m/5m) using this entry style.

The issue is that using an entry price like that have disadvantages:
-There is good chance that the order will execute immediatly, so we pay more trading fees as we take volume from the order book.
-Entry is not made at a low price
-The entry price have no special signification (not a market structure support like bollinger band, moving average, fibonacci level...)
No bounce can be expected at this price level

Advantages of using a custom entry price:
-The order will be placed in the order book and won't be trigger immediatly, we will pay lower trading fees
-Entry is made at a cheaper price when there is a correction
-If set correctly the custom entry price can have a signification in the market structure and a bounce from this price can be expected

**Proposition**
The solution is to allow the user to set a custom entry price from his strategy
It can be in the form of a custom indicator with a fixed price something like "prefered entry price" or "pep"
The the price will be sent to the dataprovider like used for the custom stoploss.

**Backtesting**
It can be challenging to backtest that kind of behaviours, I came up with a simple idea:
If the entry candle low go below the "prefered entry price" entry is considered as successful at defined price.
If the entry candle low stay over the "pep" entry failed and if the buy signal is still present a retry will occur at the same or updated pep.

![pep](https://user-images.githubusercontent.com/7593404/121217297-b6379680-c84f-11eb-9a77-61304aa4863e.png)

**Comment by xmatthias** [comment] 2021-06-08 17:03
Please use the search before opening new issues - you can even take your pick if it's a duplicate of #848 or #909 (only maybe - with fantasy).

I'll leave this open for now anyway as it's kindof well scoped / defined ... and the other issue is kinda old :laughing: 

I've got my doubts about this feature though - reading on the community - a pretty big issue is unfilled orders. allowing the strategy to place a order far away from the current price will only make this worse.
If done carefully / with intend, sure it can give you benefits - i'm just a bit sceptical if the majority of users will put it to good use...

Either way - should you start working on this - it should be implemented for both buy and sell side (not just for one) ... although the "exit" side might prove to be slightly more challanging - as "not exiting" from a trade can cause pretty bad losses ...

**Comment by Axel-CH** [comment] 2021-06-08 17:37
My bad, I admit, I did not searched related issues as I was convinced that there where none yet 

Of course misused this feature can cause frustration, but if it's well implemented it can be a game changer.
We have to add in the documentation and explanation clear enough to give the community all required information and tips to use this feature.

As you said, being unable to close a trade can lead to huge losses, that why I only use market sell (for the moment)

I've already implemented this feature locally only for buy, it's working fine and i'm getting better results.
That's why I'm not totally agree with you when you say that it must be implemented on both sides in the same PR

**Comment by xmatthias** [comment] 2021-06-08 17:45
well the approach should be pretty similar i'd think (it's copy/paste of the templates - with reversed names?).

My problem with not doing that too is that it'll mean it probably will never be done...

Either way - we can give the buying a try if you have that already and want to create a PR for it.
Once i see how you built it - we'll probably have to have a look at the parameters provided (ideally, i'd want to use the "default" freqtrade logic to add a "proposed" price) - so it's easy to "just slightly" modify a price instead of comming up with the right price yourself.

**Comment by rylos** [comment] 2021-06-10 06:18
I'm really interested in this functionality too, for shorter timeframes. @Axel-CH can you share the diff or push a PR to see how did you done it in the code? Thank you in advance.

**Closed as completed** 2021-08-18 18:59 UTC
Labels: Enhancement
