### ISSUE TITLE
Feature: Strategy behavior related to market context

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#1105] opened 2018-08-01 02:48 UTC
**Problem**
As you all know the cryptocurency market is heavily driven by the Bitcoin price behaviour. So, when the bitcoin fall, almost everything fall, except some coin (USDT, DGD) considered as "refuge coin".
During a Bear market a lots of BUY signals could be triggered on correctives waves.
Basicaly it's mean that most of long strategies will loose money on thooses crash / uncertainty periods. .Now the user need to be aware of that kind of situation and eventually stop the bot.

**Solution**
A solution to that problem would be to associate the strategy behavior to a certain asset. It could be considered as a Pair Trading but instead of a "One to One" relation between two assets it will be "One to Many".

**Exemple**
BTC is Stable -> Allow to go long on all pair in WhiteList
BTC in Downtrend -> Prohibit long, short instead (when it will be available)

The situation of the BTC will be defined with normal strategy indicator (ma, ema etc...)

**Comment by berlinguyinca** [comment] 2018-08-01 05:29
i agree with creslins and this is directly related to #918 since this was the starting point to get the current pair in, to calculate correlations

**Comment by Axel-CH** [comment] 2018-08-03 03:26
Thank you for your responses guys, I will follow thoses PR

**Comment by xmatthias** [comment] 2018-09-26 20:59
this is actually a duplicate of #325

**Closed by xmatthias** 2018-09-26 20:59 UTC
