### ISSUE TITLE
Sqlite 'UNIQUE constraint failed', no order found on exchange

### ISSUE THREAD

**Issue by perkmeister** [freqtrade/freqtrade#8913] opened 2023-07-16 11:51 UTC
## Describe your environment
  
  *  Operating system: ____Ubuntu 20.04
  *  Python Version: _____ 3.8.10
  *  CCXT version: _____ 3.1.13
  *  Freqtrade Version: ____ 2023.6.dev-8f02050fd (native)

## Describe the problem:

My live bot on Kucoin cannot restart due to an Sqlite 'UNIQUE constraint failed` error, and freqtrade complains that the order
cannot be found on the exchange when restarting.

I've attached the sqlite database, trade 35 log, and the full freqtrade log. The issue appears (to me) to be that a position adjust buy (which can be searched for in the log by looking for the string `buy_2`  because I log when these buys are requested) is _not_ creating an order number for the buy, despite the rpc message seeming to confirm the buy request. The bot then continues until another buy when this error is thrown. The trade 35 log has a last entry with nulls in it.

The lines in the log are #60246 where no order number is created when it reports `Order #None was created for NAKA/USDT and status is open.` followed by an rpc message. You'll notice all other buy_2's have an order number created. The next buy on line #60398 throws the error.

Any idea what might be going on, and how I can recover this? The order is actually still open on the exchange. Thanks!

[PerkGrid_test14_live.zip](https://github.com/freqtrade/freqtrade/files/12063917/PerkGrid_test14_live.zip)
[PerkGrid_test14_live_error.log](https://github.com/freqtrade/freqtrade/files/12063918/PerkGrid_test14_live_error.log)
[trade_35_log_json.txt](https://github.com/freqtrade/freqtrade/files/12063919/trade_35_log_json.txt)

I did some searching first, couldn't find any issues on github relating to this, but there was one on Discord with a similar report which appears to have had no resolution:
https://discord.com/channels/700048804539400213/824719649417199646/968175611396911164

**Comment by xmatthias** [comment] 2023-07-16 14:42
> Any idea what might be going on, and how I can recover this? The order is actually still open on the exchange. Thanks!

kucoin seems to have returned no order id for your order. (which is obviously a problem, as you've already seen).
Unfortunately, kucoin is known for such API flakyness from time to time - which is the main (actually only) reason we cannot add kucoin to the list of officially supported exchanges.

If you had ran the bot with "log_responses" on, you'd have that part in the logs, too.

From a freqtrade perspective, there's little to do here. If the exchange doesn't give us the order number for the order it just created, there's little we can do.


The actual crash happens because apparently, you got 2 orders with "orderid None" - it'll fail on the latter as then it's a Unique key validation.

---

Now for the recovery:

you can remove the order 200 (where order_id) from the database - which should get rid of the error when restarting (freqtrade tries to fetch the order - but without orderid, or with orderid None).


you should be able to run an explicit `/reload_trade` for this trade (either via UI, or via telegram) - which should try and find all orders freqtrade has missed for this pair - and should find this order (independent if it filled in the meantime - but unless it's now canceled).


---

As mentioned above - from a freqtrade perspective, there's little to nothing we can do here (at least with the available info), as it's kucoin's API where the endpoint accepts and creates the order - but doesn't tell freqtrade (the caller) the actual id.

If you're running a (live) bot with tons of orders on kucoin, best run  it with log_responses = True.
While log verbosity will increase quite some - it'll then at least give us info needed to work around a bug in kucoin's api.

**Comment by perkmeister** [comment] 2023-07-16 17:01
Thank you for this! 

I assume I can either add `"log_responses": true` to the exchange part of the config, or `log_responses = True` to the strategy?

Also I'm not sure which order to remove from the database, does freqtrade put dummy `order_id` in there (200) if it doesn't get a proper one? And then if it gets another it uses the same 200 number again causing the uniqueness error? 

I guess I'd also need an sqlite editor to do this.

Thanks again.

**Comment by xmatthias** [comment] 2023-07-16 18:01
>  add "log_responses": true to the exchanges part of the config

Only this. only options relevant to the strategy are possible to be set by the strategy.


it's the order with id= 200 - or `order_id='None'` ifi remember correctly.

yes, sqlite3 (command line) or sqlitebrowser (ui) are simple options for this (or dbeaver if you're looking for something a bit fancier)

**Comment by perkmeister** [comment] 2023-07-16 18:30
Great, thanks Matthias!

**Comment by perkmeister** [comment] 2023-07-17 11:21
I'm still having issues with restarting unfortunately. I've deleted order 200, the orders in the database match the order history on Kucoin now, all of which are shown as completed. It's still complaining about not finding orders, the position on the exchange is still open though and trade 35 is marked as an open trade in the database. The trade history on Kucoin actually shows some of those filled orders were made up of partial fills if that's of any relevance. 

My bot immediately tries to buy again when restarting, and that's where the error is thrown so I've stopped the buys in the strategy so I can at least get the UI up to do a reload_trade, and the logs show the response to that which appears to have found all the orders from the exchange, with their correct IDs. 

Logs and the database attached. I'm not sure what to do next, any suggestions? Thanks.

[Restart_error.TXT](https://github.com/freqtrade/freqtrade/files/12068627/Restart_error.TXT)
[PerkGrid_test14_live.zip](https://github.com/freqtrade/freqtrade/files/12068633/PerkGrid_test14_live.zip)

**Comment by xmatthias** [comment] 2023-07-17 17:57
the database in this last comment does no longer contain the offending order - nor any other order with None
Are you sure THIS is the database that's used ?

**Comment by perkmeister** [comment] 2023-07-17 18:52
Here's the script I'm running (I've cat it just to be sure it was referencing that database), I copied that database from the VPS directly into an empty directory on my PC and browsed it. I can't see anything odd either, I had previously removed order 200 from it. I renamed that database to something else on the VPS and ran it again (all 3 .sqlite files), and it created a new empty database with obviously no errors, renamed the originals back after deleting the newly created ones and errors reappeared. Pretty sure that's the one.

BTW I use the Kucoin proxy but I disabled it and problem is still there.

![cat_command](https://github.com/freqtrade/freqtrade/assets/28675875/1a811d20-27c5-4ad3-9b37-dd92774d0d35)

**Comment by xmatthias** [comment] 2023-07-18 06:07
did you also download/copy all 3 files?

if i open the database with sqlitebrowser, it consolidates all 3 into one - which doesn't contain the "None" order.
that's my best bet for now - sorry.

---

you might wanna try to open the database on the vps directly, running `sqlite3 <database>` - and then running `select * from orders where order_id = 'None';` - and `select * from trades where open_order_id = 'None';` (neither should return a row).

That'll eliminate any doubt about "transfer" problems - as it'll happen where the problem is seen.

**Comment by perkmeister** [comment] 2023-07-19 12:56
I ran these commands and it found a None for the order_id. I think what happened is when my bot restarted it tried to buy and that None order was created in the database (no such order exists on the exchange). I can now browse the database on the PC consistently with what the VPS is saying. 

So I verified on the VPS the state of the database, and ran `delete from orders where order_id = "None";` and verified it had gone (both on the VPS and my browser). I also checked if there were any open orders on the VPS with `select * from orders where status = 'open';`, so theoretically freqtrade shouldn't find one.

I then ran my strategy with buys disabled, and this is the result, it found an open order, checked the exchange then immediately reported `MARKET_BUY has been fulfilled for Trade(id=35...`. It also reported `WARNING - Got different open_order_id None != 64b1e6319111660001d51716` which was closed in the database (and is completed on the exchange), and running `select * from orders where order_id = "64b1e6319111660001d51716"` shows the VPS also thinks it's closed.

So it looks odd to me, freqtrade appears to be detecting an open order even though the database says it's closed as does the exchange. A subsequent buy then created a None order in the database where no order exists on the exchange, and all hell breaks loose when it does another buy.

Here's the log, and the commands I ran on the VPS just prior to running it (with the commands after I had run it just to check nothing had changed), and the database files.

![sqlite3_commands](https://github.com/freqtrade/freqtrade/assets/28675875/c72fac95-fc10-43e5-bb3d-b3f5b6453b96)
[PerkGrid_test14_live.log](https://github.com/freqtrade/freqtrade/files/12095058/PerkGrid_test14_live.log)
[PerkGrid_test14_live.zip](https://github.com/freqtrade/freqtrade/files/12095064/PerkGrid_test14_live.zip)

**Comment by xmatthias** [comment] 2023-07-19 13:48
I'll just extract one of the log lines ...

```
2023-07-18 11:53:04,925 - freqtrade.exchange.exchange - INFO - API create_order: {'info': {}, 'id': None, 'clientOrderId': None, 'symbol': 'NAKA/USDT', 'type': None, 'timeInForce': None, 'postOnly': None, 'side': None, 'amount': None, 'price': None, 'stopPrice': None, 'triggerPrice': None, 'cost': None, 'filled': None, 'remaining': None, 'timestamp': None, 'datetime': None, 'fee': {'currency': None, 'cost': None}, 'status': 'closed', 'lastTradeTimestamp': None, 'average': None, 'trades': [], 'fees': [{'currency': None, 'cost': None}], 'reduceOnly': None}
```

The exchange returns **nothing**  - but places an order apparently.
`info` is filled with the original response as ccxt receives it.
If you ask me, then this looks like a bug (or change) in kucoins API (or in ccxt - though even if something changed there, info would always be filled correctly).

From the kucoin docs:

![image](https://github.com/freqtrade/freqtrade/assets/5024695/58040747-5af2-4351-974a-555256c94ca9)
Source: [API docs](https://docs.kucoin.com/#place-a-new-order).

As long as kucoin returns _nothing_, it'll not work (and there's nothing freqtrade can do against that).

I'll try to verify the problem tonight (i hope i still have some money on kucoin, and the corresponding time) - but if this confirms, we'll have to remove kucoin, and intentionally block this exchange (at least for now) - as it'll be a "known not working" exchange, then.

**Comment by perkmeister** [comment] 2023-07-19 14:12
OK. There's no order created on the exchange (or at least not showing in the orders tab). I'm confused though why freqtrade would detect an open order when the database has that order marked as closed and so does the exchange. That log was the full log from previous testing, the last entries are the relevant ones, here's that with previous logs removed:

[PerkGrid_test14_live.log](https://github.com/freqtrade/freqtrade/files/12095900/PerkGrid_test14_live.log)

I should note ` A subsequent buy then created a None order in the database where no order exists on the exchange, and all hell breaks loose when it does another buy.` is what seems to happen later on if I restart the bot with buys enabled. That should read `appears to create` not `created`.

**Comment by xmatthias** [comment] 2023-07-19 16:31
Well that "last" log seems fine - the bot stops on SIGINT - which is basically pressing `ctrl+c`.
It's got nothing in it that i'd find strange.

---

The prior log still has the following (from today) though:

```
2023-07-19 12:34:13,584 - freqtrade.exchange.exchange - INFO - API create_order: {'info': {}, 'id': None, 'clientOrderId': None, 'symbol': 'NAKA/USDT', 'type': None, 'timeInForce': None, 'postOnly': None, 'side': None, 'amount': None, 'price': None, 'stopPrice': None, 'triggerPrice': None, 'cost': None, 'filled': None, 'remaining': None, 'timestamp': None, 'datetime': None, 'fee': {'currency': None, 'cost': None}, 'status': 'closed', 'lastTradeTimestamp': None, 'average': None, 'trades': [], 'fees': [{'currency': None, 'cost': None}], 'reduceOnly': None}
2023-07-19 12:34:13,584 - freqtrade.freqtradebot - INFO - Order #None was created for NAKA/USDT and status is open.

```

if it's not creating an order - then ccxt will have to raise a "InvalidOrder" exception.
if it returns without exception, then the assumption (also based on ccxt's docs) is that placing the order did work.

Testing this with plain ccxt (and NAKA/USDT) - i also do get a proper order response.

![image](https://github.com/freqtrade/freqtrade/assets/5024695/28b340a9-d482-4e9b-ba79-4709c0cd5ebc)

Seems like yours is returning empty - which doesn't make sense. You might wanna test this independent of freqtrade (via ccxt directly) - and if that fails, open an issue with kucoin (i strongly doubt it's a ccxt problem, but verbose mode of ccxt can help you find this, and if it is an issue with ccxt, raise an issue there).

As it's working for me - i'll not be looking at this much further for now unless there are some new findings.
Freqtrade seems to work fine as long as the exchange returns responses according to their documentation - which kucoin is not in your instance.

I'm happy to get a PR fixing this should that be required - but being a community vetted exchange - the assumption is that the community will also look at such problems, and eventually follow this up with the exchange..

---

For your order - you seem to be placing all market orders (at least based on the database). You'll therefore never see an order in open orders - but in order history (as well as trade history)

on kucoin, we must assume all orders as open once they're placed - as kucoin only returns the order id - not the full response.
this will make sure that the order is processed appropriately. It's a cheap workaround for an instable API, where a proper fix is not really worth my time..

**Comment by perkmeister** [comment] 2023-07-19 17:05
OK.

> Well that "last" log seems fine - the bot stops on SIGINT - which is basically pressing `ctrl+c`. It's got nothing in it that i'd find strange.

Of course, I stopped the bot after the log output. This bit I find strange:

`2023-07-19 12:39:13,921 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=35, pair=NAKA/USDT, amount=109.72490000, is_short=False, leverage=1.0, open_rate=0.46642269, open_since=2023-07-14 01:15:01)`

and the later log after it had checked the exchange and found it had filled:

`2023-07-19 12:39:13,956 - freqtrade.persistence.trade_model - INFO - MARKET_BUY has been fulfilled for Trade(id=35, pair=NAKA/USDT, amount=58.54410000, is_short=False, leverage=1.0, open_rate=0.45082723, open_since=2023-07-14 01:15:01).
2023-07-19 12:39:13,956 - freqtrade.persistence.trade_model - WARNING - Got different open_order_id None != 64b1e6319111660001d51716`

The database did not contain any open order, or any order with None as the ID, I proved that on the VPS and browsed it also to check before starting the bot (screenshot in previous post). So why did it detect an open order? Why did it say `open_order_id None != 64b1e6319111660001d51716`, and what does that really mean? I assume it's looking at the database to detect open orders before trying to confirm their status on the exchange. To me this doesn't make sense.

**Comment by xmatthias** [comment] 2023-07-19 17:37
> Got different open_order_id None != 64b1e6319111660001d51716

that's a different - mostly obsolete warning that's checking if the order the trade assumed to have open (`.open_order_id`) corresponds to the one we're closing.
The closing itself happens on startup for all non-finished trades which closed on exchange - which can lead to this problem.
Considering the problems you've had, this is no surprise if i'm honest.

**Comment by perkmeister** [comment] 2023-07-19 18:09
Thanks. Further to this, it finds the open order only after the None order entry had been made (after a buy), and then that is removed from the database, and then bot then restarted. It goes away on a subsequent restart, so maybe some hangover from that. My understanding of what's going on in freqtrade is increasing, thanks Matthias!

**Comment by perkmeister** [comment] 2023-07-19 18:30
Just going to check something. Kucoin is starting to push KYC, I'm wondering if they've (silently) disabled the API, or I need to create a new one? The first thing I'll try is creating a new API key.

**Comment by xmatthias** [comment] 2023-07-19 18:35
in theory - no, not the api key (unless it's permissions).
if the api key is wrong - freqtrade won't start as the call to "/balance" will fail.

"disabled" trading due to KYC (or for other reasons, maybe limited to that pair) are very well possible - my account is verified (since months/years) - so i can't really comment on that.

**Comment by perkmeister** [comment] 2023-07-19 18:58
Oh look, need KYC to create a new key...
 
![API_needs_KYC](https://github.com/freqtrade/freqtrade/assets/28675875/69f20cea-e855-47ac-a16a-fd370b22588a)

**Comment by perkmeister** [comment] 2023-07-19 19:32
It worked!! The sneaky little buggers. I only actually needed to send a passport number to get to the next level, but it allowed me to create a new key and orders are being created as normal. Well well.. :-O

Thanks for all your help Matthias.

**Comment by xmatthias** [comment] 2023-07-20 17:40
Will be fixed in ccxt - https://github.com/ccxt/ccxt/pull/18608

**Closed as completed** 2023-07-21 19:19 UTC
Labels: CCXT
