### ISSUE TITLE
Rest API stops reponding when reloading config

### ISSUE THREAD

**Issue by Th0masL** [freqtrade/freqtrade#4461] opened 2021-02-28 15:40 UTC
## Describe your environment

  * Operating system: Docker
  * Python Version: 3.9.2
  * CCXT version: 1.42.45
  * Freqtrade Version: 2021.2

## Describe the problem:

It's probably not a problem for most people, but I've realized that the Rest API stops responding during couple of seconds when the config gets reloaded.

### Steps to reproduce:

  1. reload the config
  2. query the REST API just after
  
### Observed Results:

  * What happened?
  The REST API stops responding and throws a `WARNING - Connection error`
  * What did you expect to happen?
  The REST API responds that the bot is currently in `reload_config` state

### Relevant code exceptions or logs

```
# while [ 1 ]; do date && python3 scripts/rest_client.py --config config_binance.json show_config | jq -r '.state' && sleep 1 && echo "----"; done

Sun Feb 28 15:28:53 UTC 2021
running
----
Sun Feb 28 15:28:55 UTC 2021
running
----
Sun Feb 28 15:28:57 UTC 2021
reload_config
----
Sun Feb 28 15:28:59 UTC 2021
reload_config
----
Sun Feb 28 15:29:01 UTC 2021
2021-02-28 15:29:02,292 - ft_rest_client - WARNING - Connection error
null
----
Sun Feb 28 15:29:03 UTC 2021
2021-02-28 15:29:04,119 - ft_rest_client - WARNING - Connection error
null
----
Sun Feb 28 15:29:05 UTC 2021
2021-02-28 15:29:05,948 - ft_rest_client - WARNING - Connection error
null
----
Sun Feb 28 15:29:07 UTC 2021
2021-02-28 15:29:07,797 - ft_rest_client - WARNING - Connection error
null
----
Sun Feb 28 15:29:09 UTC 2021
2021-02-28 15:29:09,618 - ft_rest_client - WARNING - Connection error
null
----
Sun Feb 28 15:29:12 UTC 2021
running
----
```

It's a bit annoying for me as I'm monitoring the state of my bot by querying the REST API, and I get false positive alerts that the bot is down when in fact it's simply reloading the configuration.

I would be happy to try to find a way to improve the behavior of the REST API to be able to always return `reload_config` when the bot is currently reloading the configuration, instead of not responding anything and throwing an error.

Would anyone have an idea in which part of the code I should dig into to try to fix that ?

**Comment by xmatthias** [comment] 2021-02-28 16:05
this is intended behaviour and not something that should be fixed.

using `/reload_config` will terminate everything except for the outermost wrapper, and initialize everything from scratch (including the strategy, config, and all modules (pairlists, protections, rpc)).

While you think it's an annoyance - simply widen the monitoring net to allow a few seconds of "non-responding".

Doing it this way will allow you to change settings without stopping / starting the bot in every aspect, including changes to settings related to the rest api (for example change the CORS configuration, or the password).

**Comment by Th0masL** [comment] 2021-03-01 00:17
Ok, that makes sense, then my problem is simply that I'm using the command /reload_config where in fact I would only need to reload the pair_whitelist.

Out of curiosity, would there be a way to only reload the value of pair_whitelist ?

I'm not really updating any other values than the pair_whitelist, so I'm wondering if eventually there could be a command that allows to tell the bot to only refresh the pair_whitelist from the config ?

I'm thinking of something like `/reload_pairwhitelist`

That's eventually something I could investigate, if you think it's not too complicated to do.

**Comment by xmatthias** [comment] 2021-03-01 05:50
I've had an idea for something similar in the past - but it might not be a "quick" solution.

we could have a `UserPairlist` (name to define - this one is not good) pairlist, which will either provide a full pairlist (simliar to staticpairlist) - or inject additional pairs to the pairlist.

this `UserPairlist` get's the pairlist from a (new) database table - allowing full control to RPC by adding and removing pairs from this userpairlist at will (it's empty by default, but persisted across restarts by beeing in the database).

as the pairlist is refreshed quite often (once every iteration, unless the pairlist implements some caching) - you could simply add / remove your pair, and it'd magically appear without changing configuration or whatever.

obviously blacklist (and such) will still apply as usual, so you can't whitelist pairs that are in a blacklist - but that shouldn't really be a problem i'd hope.

**Comment by Th0masL** [comment] 2021-03-01 20:52
That's indeed interesting, I like the idea !

But I have the feeling that the dedicated Database table is a bit too much over-engineered solution to a problem that seems quite basic :smile: 

Don't you think we could simply improve the method `StaticPairList` in `pairlists`, and that there would be no need to create a new variable and a new table ?

We could add a `refresh` option under `StaticPairList` method so the user can specify at which frequency freqtrade should refresh the value of `exchange.pair_whitelist` and `exchange.pair_blacklist` from the config.json file.

That could look like that :

```
    "pairlists": [
        {
            "method": "StaticPairList",
            "refresh": "5m"
        },
```

**Comment by xmatthias** [comment] 2021-03-02 05:31
StaticPairlist is refreshed every iteration - in theory, you can just inject it into the config object's pair_whitelist and it should work.

the problem is - assume you do frequent changes, and you added 20 pairs (maybe at once, maybe over time)- and now you restart/reload the bot (for whatever reason) ...

all your 20 changed pairs are now lost, and you need to add them again (because you use a modified config object, and the data is not persisted to the config).
That's why the database is important in my opinion, as otherwise it'll simply reset - and it'll become an unused feature.

while persisting to the config json may seem tempting, you really can't write to it because 
* especially in docker, config files may not be writable (i usually mount config with `:ro`)
* we can use multiple config files - so it'll not be clear to which you should write.

**Comment by Th0masL** [comment] 2021-03-06 00:03
Yeah, you are right about doing persisting edits in the config.json file, they are not really convenient in a Docker and/or multi config setup.

But that's what I'm doing right now anyway, as I find it to be the only way to be able to reload the bot without losing the pair.

So yeah, the Database idea would indeed be the best practice.

I will try to see if I can spend some time investigating that.

Feel free to ping me some resources or point me to specific files / methods that I could use as example to understand how the freqtrade DB/methods works.

**Comment by xmatthias** [comment] 2021-03-06 12:33
`models.py`? :laughing: 

i don't think it'll be a huge problem - but obviously i'm used to work with sqlalchemy models ...

**Comment by xmatthias** [comment] 2021-03-06 19:25
I'm going to close this in favor of #4493.

The title (and first few posts) are quite missleading to what the rest of the discussion revolves around.

**Closed as completed by xmatthias** 2021-03-06 19:25 UTC
Labels: Question, Wont fix / Not a bug
