### ISSUE TITLE
Persistence not updated when asset sold on exchange

### ISSUE THREAD

**Issue by yazeed** [freqtrade/freqtrade#2836] opened 2020-02-02 10:13 UTC
### Describe the problem:

Not sure if this is intentional but persistence does not seem to resync if for any reason you terminate a trade remotely from the exchange, or simply get disconnected while any trades occur.

### Steps to reproduce:

  1. Run freqtrade, and have it buy some pairs.
  2. Disconnect freqtrade.
  3. Sell the pairs directly on the exchange.
  4. Reconnect freqtrade.
  5. You immediately notice two things:

 - Upon booting it logs `freqtrade.persistence - INFO - Found open trade: Trade(id=27, pair=ATOM/BTC, amount=7.64000000, open_rate=0.00046930, open_since=2020-02-01 02:25:29)` even though that pair's quantity no longer exists on my account.
 - It also started generating the following error once it fully loaded, due to it attempting to create a stoploss on no longer existing positions.
  
### Observed Results:

  * What happened?
    * Persistence failed to recognize that the stoploss no longer needs to be created since the account is no longer holding that pair.
  * What did you expect to happen?
    * I expected it to recognize that the pair is non-existent. Also, expected it to either reflect it on the database without recognizing it's ROI or sell reason. OR attempt to read orders from account, if that same pair with the same quantity was sold, adjust it in database accordingly. This scenario should be covered without breaking the normal workflow of freqtrade. I think the database should attempt to record what it can, but the account should reflect the source of truth when needed to resync.

### Relevant code exceptions or logs:

  ```
Traceback (most recent call last):
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/freqtradebot.py", line 667, in create_stoploss_order
    rate=rate * LIMIT_PRICE_PCT)
  File "/Users/yazeed/Sites/freqtradeLATEST/freqtrade/exchange/binance.py", line 73, in stoploss_limit
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market XZC/BTC.Tried to sell amount 20.83 at rate 0.0007147. Message: binance Account has insufficient balance for requested action.
  ```

**Comment by yazeed** [comment] 2020-02-02 18:22
@xmatthias @hroff-1902 I'm sure you guys know already about this, I'm curious to know what your take on this is.

**Comment by xmatthias** [comment] 2020-02-02 18:54
I'm not certain this is a bug (it's kind of intended behaviour to me).
If any, then it's an enhancement - but i'm have strong doubts about the implementation part - and being wrong once can mean 100% loss of that position (bot assumes trade was sold - but it's not and the coins value drops and the coin "vanishes")

---

Yes, you did sell the trades on the Exchange and the database does not catch up.
The errors are clear - we have the [sql cheatsheet](https://www.freqtrade.io/en/latest/sql_cheatsheet/#fix-trade-still-open-after-a-manual-sell-on-the-exchange) which shows how to fix that.
Maybe it's not 100% clear from the remainder of the documentation - definitely a point to improve.


#### My doubts: 

How would you expect the bot to fix such a case? 
* Delete the trade from the database because it did not find any balance of XZC on the exchange? This would hide that the trade ever happened - which i think is wrong as it can lead to second-quessing of backtesting / live alignment - the bot did not buy even though the signals were there and it should have.
* Closing it with "unknown" (or something else) will mess with statistics as it's unknown at what rate the asset was sold precisely.

For these reasons, i think the best is to let the user decide himself how to fix this - by either updating the table - or deleting this trade from the table.

--- 
I think you're assuming that the bot is controlling the whole account.
but you always need to consider that that's not the case and a user only gives the bot a subsection of the bot's balance.

Trying to fix this automatically can be risky and very error-prone.

In addition to that - I would not know how to resync the database correctly (assume the bot bought  XZC/BTC - but you sold XZC/ETH)? That's a case you are unable to cover.
Also, if the bot bought XZC/BTC - and you bought XZC/ETH - and then sold "all" again (by mistake)? The asset is gone - but not against the stake currency you bought it for...


That's not a "matching" trade where amount is correct, so even using `fetch_my_trades()` won't help you (letalone the fact that running that for multiple trades in quick succession can block you very quickly).


To me, switching the bot off and closing trades manually on the exchange is a scenario which will have to require manual intervention.

---- 

>  I'm sure you already know about this, I'm curious to know what your take on this is.

Yes - i do know about this - manually messing with trades / positions the bot opened is simply not supported at the moment.
It works for stoploss-on-exchange (the bot will simply recreate the order) - but not if you sell funds "belonging" to the bot.

> This scenario should be covered without breaking the normal workflow of freqtrade

That's the least worrying part to me - as you can simply call this once during startup - it's the 100% reliable implementation that i have my doubts.

**Comment by yazeed** [comment] 2020-02-02 21:54
Thanks for the elaborate coverage on this issue. I think there's two discussions being made here.

The **first discussion** being about persistence not updating when asset is sold on exchange.

My personal preference here would be to keep the trade in the database, mark it as unknown in terms of when/how it closed, and cover for it in performance reports.

My second preference would be to have freqtrade prompt to delete it all-together, even if it was at the cost of losing consistency in terms of what signals were originated from the strategy, it seems to me that this is kind of expected when freqtrade stops running for any reason, and also since persistence is unable to determine what actually happened to the pair (there are too many scenarios to try and cover for).

The **second discussion** is regarding preventing the scenario where freqtrade attempts to create a stoploss for a pair that doesn't really exist anymore. This is _the_ bug I originally intended to refer to, but fixing it might depend on which approach we adopt in the first part of the discussion.

Would love to hear more of your thoughts about this.

**Comment by xmatthias** [comment] 2020-02-04 06:11
> My second preference in this case would be to have freqtrade prompt to delete it all-together

How? 
RPC / Telegram is not mandatory - and i'd avoid asking on the CLI in trade-mode - as that'll lead to a ton of stopped/blocked bots (assume they are running on a server (in a docker container) and are not constantly monitored).

i did fix part of the 2nd problem in #2799 ... but it'll not fix cases where the balance was modified on the exchange (that wasn't my intend there, either).

---- 

i suppose we can apply the same logic (`_safe_sell_amount()`) to stoplosses creation - but very selectively (not for trailing-stop - if the bot cancelled the trade, you'll need to time it perfectly to even be able to sell the asset between cancel and reapply of the stoploss.

In the end however, stoploss is only the symptom - so we'd be fixing the wrong thing.

Yes, you do notice it on stoploss creation - but assume you don't use stoploss_on_exchange - the same exact problem (unsellable trade) would apply during a limit / market sell based on a sell-signal.

**Comment by yazeed** [comment] 2020-02-04 12:41
> i suppose we can apply the same logic (`_safe_sell_amount()`) to stoplosses creation - but very selectively (not for trailing-stop - if the bot cancelled the trade, you'll need to time it perfectly to even be able to sell the asset between cancel and reapply of the stoploss.
> 
> In the end however, stoploss is only the symptom - so we'd be fixing the wrong thing.
> 
> Yes, you do notice it on stoploss creation - but assume you don't use stoploss_on_exchange - the same exact problem (unsellable trade) would apply during a limit / market sell based on a sell-signal.

Then, I'm back to the same area, I think we should be prepared to accept pairs that disappear as unknown. Then, we can simply stop attempts to act on a pair, like create a stoploss if that trade was decided as unknown.

**Comment by xmatthias** [comment] 2020-02-04 18:57
> I think we should be prepared to accept pairs that disappear as unknown

Yes - but i think the correct way is to let the user explicitly define how to handle this case - is it sold as 100% loss (or 100% gain?) - or removed from the database? or something else entirely?

On the other hand - we're talking about how to handle this - but i'm not sure we can identify these pairs correctly - and without that, all other discussion is obsolete.

**Comment by yazeed** [comment] 2020-02-07 03:10
Perhaps we can identify them as pairs that have open_rate but no close_rate in sqlite, and no longer exist on the account?

I wouldn't mind having freqtrade deleting the whole row, but we can also move it to another table just to keep it recorded for users in sqlite, while at the same time preventing freqtrade from acting on it anymore, simply because it is unable to track (what happened to that pair or order)

What do you think?

**Comment by xmatthias** [comment] 2020-02-07 06:25
> Perhaps we can identify them as pairs that have open_rate but no close_rate in sqlite, and no longer exist on the account?

well using `is_open` on the trade object will suffice ... 

But how are you going to detect the "no longer exist on the account" ? All discussion here refer to how to handle it in the database - but that's the smallest of the problems with this issue ...

**Comment by yazeed** [comment] 2020-02-07 15:34
> > Perhaps we can identify them as pairs that have open_rate but no close_rate in sqlite, and no longer exist on the account?
> 
> well using `is_open` on the trade object will suffice ...
> 
> But how are you going to detect the "no longer exist on the account" ? All discussion here refer to how to handle it in the database - but that's the smallest of the problems with this issue ...

How about if we query the exchange for orders matching **order_id** to see if it exists or not. For pairs, we can query list of owned pairs and try to match them by quantity.

**Comment by xmatthias** [comment] 2020-02-07 15:45
well but that's the whole point i'm trying to make - you sold it __manually__ on the exchange - so you don't have the order_id.

All you know is that sell-orders now fail - and that balance does not correspond to the bot's expectations.

**Comment by yazeed** [comment] 2020-02-07 16:02
Wait, let me get this, I feel that either I'm either missing something or we're not talking about the same thing, gotta re-read up.

What I meant was that, since order_id is still in the sqlite database, why can't we use it to query the exchange to check if the order exists or not anymore, if it doesn't, and there's no recorded close_rate on it, that means that it's gone without freqtrade witnessing what happened to it.

What's not possible to implement about the above criteria to determine what happened to the order?

Finally, I'm proposing that freqtrade moves trades in sqlite to a new table for such unwitnessed trades.

**Comment by xmatthias** [comment] 2020-02-07 16:08
Well this is the case where the order would stay unfilled on the exchange and you manually cancel it. This is a case that we do in fact handle - even if the bot is shutdown in the meantime.

This issue however (read your own first comment please) is about a filled order "waiting for sell conditions" in the bot.
You then 
* stop the bot (order is filled either before or after the bot is stopped)
*  sell the asset on the exchange 
* and start the bot back up.

 The bot will now (obviously) try to sell the asset (it thinks the account has 200 XYZ) - but you sold it already - it's not there anymore.

Order_id does not play a role after the order is filled - and the bot does know that (independently if it was shutdown when the order was filled or not).

**Comment by yazeed** [comment] 2020-02-08 23:43
OK, understood, my initial intent behind this issue was about exploring the possibility for resync but you're right it's not about the stoploss.

So now, what prevents us from moving a trade to a new table for these out-of-sync trades when detected by the bot? I just noticed the following output from the **exit_positions()** method, so our logic to move to do might be fitting to be added there.

`2020-02-08 20:48:54,593 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 8555.0, Wallet: 0`

**Comment by xmatthias** [comment] 2020-02-09 10:07
I wouldn't move it to another table - but give it a "specific" sell-type which makes it easy to identify these trades. 
However, as said before - let's **FIRST** make sure we're able to identify these trades - and then decide how to handle them.

The question is - is wallet < trade-amount enough to detect this reliably?
By how much lower? you can't compare to 0 - if a user is not using BNB fees, then comparing to 0 will fail due to "binance dust" ...

Depending if fees are handled correctly (they are for me - but i've seen time and time again that it's not always the case) wallet-amount may be 1% lower than trade-amount. Sell-logic does handle this - but that means that `if wallet < trade-amount` will identify way too many trades.

Once we know FOR SURE that this position has been sold manually - we can try to query `fetch_my_trades` to determine the actual sell price - and calculate profit/loss (just because it's sold manually does not mean it was sold at a loss, after all).

As said above multiple times - it's the identification part that worries me most - once we are able to do this RELIABLY (and that's the key point here i have my doubts) - then we can close the trade and assign it a "sell_type.Manual" .... which makes identifying these trades easy.

**Closed** 2023-05-13 14:35 UTC
Labels: Enhancement
