### ISSUE TITLE
Last tick is 941 minutes old

### ISSUE THREAD

**Issue by majubewi** [freqtrade/freqtrade#4287] opened 2021-01-31 21:24 UTC
## Describe your environment

  * Operating system: Ubuntu 20.04
  * Python Version: Python 3.8.5 (`python -V`)
  * CCXT version: 1.40.99 (`pip freeze | grep ccxt`)
  * Freqtrade Version: freqtrade develop-1e51054b (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

No matter what Bitcoin Pair I am trying to trade with Strategy005 on Bittrex in Dry-run, I always get the Warning:

`2021-01-31 22:10:05,514 - freqtrade.strategy.interface - WARNING - Outdated history for pair MEME/BTC. Last tick is 941 minutes old`

### Steps to reproduce:

  1. Clone the repo
  2. Use config https://pastebin.com/SqdEN1Dp with the example strategy Strategy005 from your repos
  3. run `python3 ./freqtrade/main.py trade -s Strategy005 -v`
  
### Observed Results:

No trades being made for over a week, all pairs throw the following warning:

2021-01-31 22:21:33,145 - freqtrade.strategy.interface - WARNING - Outdated history for pair MEME/BTC. Last tick is 941 minutes old

### Relevant code exceptions or logs

2021-01-31 22:21:33,116 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2021-01-31 22:21:33,116 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair LRC/BTC.
2021-01-31 22:21:33,121 - freqtrade.strategy.interface - DEBUG - Populating buy signals for pair LRC/BTC.
2021-01-31 22:21:33,123 - freqtrade.strategy.interface - DEBUG - Populating sell signals for pair LRC/BTC.
2021-01-31 22:21:33,126 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2021-01-31 22:21:33,126 - freqtrade.strategy.interface - DEBUG - TA Analysis Launched
2021-01-31 22:21:33,126 - freqtrade.strategy.interface - DEBUG - Populating indicators for pair HEDG/BTC.
2021-01-31 22:21:33,131 - freqtrade.strategy.interface - DEBUG - Populating buy signals for pair HEDG/BTC.
2021-01-31 22:21:33,133 - freqtrade.strategy.interface - DEBUG - Populating sell signals for pair HEDG/BTC.
2021-01-31 22:21:33,136 - freqtrade.strategy.interface - DEBUG - Loop Analysis Launched
2021-01-31 22:21:33,141 - freqtrade.freqtradebot - DEBUG - create_trade for pair MEME/BTC
2021-01-31 22:21:33,145 - freqtrade.strategy.interface - WARNING - Outdated history for pair MEME/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,145 - freqtrade.freqtradebot - DEBUG - create_trade for pair ADK/BTC
2021-01-31 22:21:33,149 - freqtrade.strategy.interface - WARNING - Outdated history for pair ADK/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,149 - freqtrade.freqtradebot - DEBUG - create_trade for pair BFT/BTC
2021-01-31 22:21:33,153 - freqtrade.strategy.interface - WARNING - Outdated history for pair BFT/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,153 - freqtrade.freqtradebot - DEBUG - create_trade for pair DOGE/BTC
2021-01-31 22:21:33,157 - freqtrade.strategy.interface - WARNING - Outdated history for pair DOGE/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,157 - freqtrade.freqtradebot - DEBUG - create_trade for pair 4ART/BTC
2021-01-31 22:21:33,162 - freqtrade.strategy.interface - WARNING - Outdated history for pair 4ART/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,162 - freqtrade.freqtradebot - DEBUG - create_trade for pair MRPH/BTC
2021-01-31 22:21:33,166 - freqtrade.strategy.interface - WARNING - Outdated history for pair MRPH/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,166 - freqtrade.freqtradebot - DEBUG - create_trade for pair UNI/BTC
2021-01-31 22:21:33,170 - freqtrade.strategy.interface - WARNING - Outdated history for pair UNI/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,170 - freqtrade.freqtradebot - DEBUG - create_trade for pair AAVE/BTC
2021-01-31 22:21:33,174 - freqtrade.strategy.interface - WARNING - Outdated history for pair AAVE/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,174 - freqtrade.freqtradebot - DEBUG - create_trade for pair ZEN/BTC
2021-01-31 22:21:33,178 - freqtrade.strategy.interface - WARNING - Outdated history for pair ZEN/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,178 - freqtrade.freqtradebot - DEBUG - create_trade for pair LRC/BTC
2021-01-31 22:21:33,182 - freqtrade.strategy.interface - WARNING - Outdated history for pair LRC/BTC. Last tick is 941 minutes old
2021-01-31 22:21:33,182 - freqtrade.freqtradebot - DEBUG - create_trade for pair HEDG/BTC
2021-01-31 22:21:33,186 - freqtrade.strategy.interface - WARNING - Outdated history for pair HEDG/BTC. Last tick is 941 minutes old

**Comment by xmatthias** [comment] 2021-02-01 05:44
Please use the search to try and identify similar issues.

Best make sure your time is uptodate (correct time + timezone). 

This is actually a duplicate of #4181. Best subscribe there for further updates. 
As you'll see there, i'm not able to replicate this (i simply do not get this problem), so my best assumption for now is that something with the clock is off ..

**Closed as completed by xmatthias** 2021-02-01 05:44 UTC
Labels: Duplicate
