### ISSUE TITLE
plot is not possible with RL freqai model

### ISSUE THREAD

**Issue by CryptoRahino** [freqtrade/freqtrade#8624] opened 2023-05-10 11:38 UTC
## Describe your environment

  * Operating system: ubuntu 22
  * Python Version: 3.10
  * CCXT version: 3.0.75
  * Freqtrade Version: 2023.4
  
## Your question

i'm using RL model, run backtest on it.
now i want to plot the results and i get the error:
`2023-05-10 14:31:36,763 - freqtrade - ERROR - Trying to access pretrained model with `identifier` but found different features furnished by current strategy.Change `identifier` to train from scratch, or ensure thestrategy is furnishing the same features as the pretrainedmodel. In case of --strategy-list, please be aware that FreqAI requires all strategies to maintain identical feature_engineering_* functions`
executed command:
plot-dataframe -c user_data/config_ada.json --strategy rl_ada --timerange 20210401-20230423 --freqaimodel ReinforcementLearner --export-filename user_data/backtest_results/backtest-result-2023-05-09_21-06-28.json

i didn't change anything in the strategy nor in config file
i wonder what am i doing wrong?

**Comment by xmatthias** [comment] 2023-05-10 13:59
this is a duplicate of #8535 - which was fixed quite recently (and is therefore not yet part of the stable version).

We've fixed this in the develop version - so by using develop - this should work fine.

**Comment by CryptoRahino** [comment] 2023-05-10 18:50
tested this scenario with develop branch. same failure as before

**Comment by xmatthias** [comment] 2023-05-10 18:59
did you run the backtest with the develop version as well? what's the precise version you're on now? (`freqtrade -V`)

**Comment by robcaulk** [comment] 2023-05-12 06:00
Also, please ensure you are using a new `identifier` before running your new test.

**Comment by CryptoRahino** [comment] 2023-05-15 13:25
thanks for answers @robcaulk & @xmatthias 
did re based to develop and changed the `identifier` in the config file.
2 important notes:
1. i use RL 
2. in strategy > populate_indicators() I've populated with the same technical features as in feature_engineering_expand_all() but with a static `period` rather as in feature_engineering_expand_all that it gets it from config. 

this setup cause the following error:
```
2023-05-15 15:50:29,816 - freqtrade.freqai.freqai_interface - WARNING - Training ADA/USDT:USDT raised exception ValueError. Message: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters., skipping.
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 347, in start_backtesting
    self.model = self.train(dataframe_train, pair, dk)
  File "/opt/freqtrade/freqtrade/freqai/RL/BaseReinforcementLearningModel.py", line 109, in train
    data_dictionary: Dict[str, Any] = dk.make_train_test_datasets(
  File "/opt/freqtrade/freqtrade/freqai/data_kitchen.py", line 160, in make_train_test_datasets
    ) = train_test_split(
  File "/home/rahino/anaconda3/envs/freqtrade_orig1/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2448, in train_test_split
    n_train, n_test = _validate_shuffle_split(
  File "/home/rahino/anaconda3/envs/freqtrade_orig1/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2126, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
2023-05-15 15:50:29,820 - freqtrade.freqai.freqai_interface - INFO - Saving metadata to disk.
2023-05-15 15:50:31,641 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/opt/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
  File "/opt/freqtrade/freqtrade/commands/plot_commands.py", line 24, in start_plot_dataframe
    load_and_plot_trades(config)
  File "/opt/freqtrade/freqtrade/plot/plotting.py", line 649, in load_and_plot_trades
    df_analyzed = strategy.analyze_ticker(data, {'pair': pair})
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 833, in analyze_ticker
    dataframe = self.advise_indicators(dataframe, metadata)
  File "/opt/freqtrade/freqtrade/strategy/interface.py", line 1341, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/opt/freqtrade/freqtrade/user_data/strategies/RL_ada.py", line 250, in populate_indicators
    dataframe = self.freqai.start(dataframe, metadata, self)
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 159, in start
    dk = self.start_backtesting(dataframe, metadata, self.dk, strategy)
  File "/opt/freqtrade/freqtrade/freqai/freqai_interface.py", line 363, in start_backtesting
    self.dd.save_metadata(dk)
  File "/opt/freqtrade/freqtrade/freqai/data_drawer.py", line 425, in save_metadata
    dk.data["training_features_list"] = list(dk.data_dictionary["train_features"].columns)
KeyError: 'train_features'
```

my questions are:
1. should the training started although I've asked to plot backtest results?
`
plot-dataframe -c user_data/config_ada.json --strategy rl_ada --timerange 20220901-20230511 --freqaimodel ReinforcementLearner --export-filename backtest-result-2023-05-15_15-38-47.json
`
2. it seems that the exception above is caused by freqtrade/freqai/data_kitchen.py > filter_features() that drops all columns with NaNs. But NaNs are expected as rolling window is used.
should startup_candle_count be increased in strategy to the same number is the backtest uses? (~2300)?
could the same mechanism be used with plot on RL model?

**Comment by xmatthias** [comment] 2023-05-19 05:13
just tested exactly your usecase (backtesting RL -> plotting) with these commands:

```
freqtrade backtesting --config user_data/config_rl.json --freqaimodel ReinforcementLearner -s XmattFreqRLStrategy1 --timerange 20230101-20230105
freqtrade plot-dataframe --config user_data/config_rl.json --freqaimodel ReinforcementLearner -s XmattFreqRLStrategy1 --timerange 20230101-20230105 --pair ALGO/USDT:USDT
```

The strategy is the example strategy, with the things necessary for RL added.

Plotting is working perfectly fine, and i get NO new training.
_(Results are not convincing (i reduced training time greatly) - but that's not the point of this test)._

Before running the above tests, i started with an empty `userdata/models` directory.

I'd also advise not to use an explicit `--export-filename` - freqtrade will determine the latest backtest result itself - which usually yields better results.

**Closed as completed** 2023-05-21 06:22 UTC
Labels: Duplicate, Question, Plotting, freqAI
