### ISSUE TITLE
Multiple sell targets

### ISSUE THREAD

**Issue by alexpunct** [freqtrade/freqtrade#5930] opened 2021-11-20 19:27 UTC
## Describe the enhancement

I would really like to have the ability to close only part of the position at specific profit targets. For example I would like to sell 50% of the position when the current profit is 100% and so on. This way I could catch the parabolic moves in coins without having to sell the entire position.
I'm sorry if this was discussed someone else, I tried to search for it but I can't find anything.

**Comment by xmatthias** [comment] 2021-11-21 07:29
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.

---

In fact, this is a duplicate of #1519 - but you'll need to know what to look for.

While that issue is rather old - it's not implemented (and won't be in the near future i think) - as it'll require rather large changes to freqtrade internals - and current focus is on other topics (margin/short).

I'd suggest to subscribe to that linked issue to get notified on updates to that topic.

**Closed as completed by xmatthias** 2021-11-21 07:29 UTC
Labels: Duplicate, Question
