### ISSUE TITLE
/reload_config crashes the bot

### ISSUE THREAD

**Issue by 20flint12** [freqtrade/freqtrade#10851] opened 2024-10-28 08:58 UTC
## Describe your environment

  * Operating system: Debian
  * Python Version: 3.12 (`python -V`)
  * CCXT version: ____2024.9_ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
  ```

**Comment by froggleston** [comment] 2024-10-28 09:56
Please provide more information, notably bot logs. We cannot assist with no information.

**Comment by kazmorebig** [comment] 2024-10-28 15:06
I think I have faced the similar issue. I used FreqUI to reload strategies and got the following lines in log:
The log is reversed (read from bottom to top)
```
Oct 28 22:04:23 raspberrypi systemd[3994]: freqtrade.service: Scheduled restart job, restart counter is at 5.
Oct 28 22:04:23 raspberrypi systemd[3994]: freqtrade.service: Consumed 26min 4.275s CPU time.
Oct 28 22:04:23 raspberrypi systemd[3994]: freqtrade.service: Failed with result 'exit-code'.
Oct 28 22:04:23 raspberrypi systemd[3994]: freqtrade.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 22:04:17 raspberrypi freqtrade[20872]: AttributeError: 'NoneType' object has no attribute '_abort'
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     ^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     self._ssl_protocol._abort()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/usr/lib/python3.11/asyncio/sslproto.py", line 247, in abort
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     transport.abort()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 462, in _close
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     self._close()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 432, in close
Oct 28 22:04:17 raspberrypi freqtrade[20872]:            ^^^^^^^^^^^^^^^
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     return super().close()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 867, in close
Oct 28 22:04:17 raspberrypi freqtrade[20872]:           ^^^^^^^^^^^^^^^^^^^^^^^
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     await self._connector.close()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1198, in close
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     await self.session.close()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/.venv/lib/python3.11/site-packages/ccxt/async_support/base/exchange.py", line 125, in close
Oct 28 22:04:17 raspberrypi freqtrade[20872]:            ^^^^^^^^^^^^^^^
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     return future.result()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     self.loop.run_until_complete(self._api_async.close())
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/freqtrade/exchange/exchange.py", line 311, in close
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     self.exchange.close()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/freqtrade/freqtradebot.py", line 219, in cleanup
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     self.freqtrade.cleanup()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/freqtrade/worker.py", line 218, in _reconfigure
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     self._reconfigure()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/freqtrade/worker.py", line 80, in run
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     worker.run()
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
Oct 28 22:04:17 raspberrypi freqtrade[20872]:                   ^^^^^^^^^^^^^^^^^^
Oct 28 22:04:17 raspberrypi freqtrade[20872]:     return_code = args["func"](args)
Oct 28 22:04:17 raspberrypi freqtrade[20872]:   File "/home/pi/freqtrade/freqtrade/main.py", line 44, in main
Oct 28 22:04:17 raspberrypi freqtrade[20872]: Traceback (most recent call last):
Oct 28 22:04:17 raspberrypi freqtrade[20872]: 2024-10-28 22:04:17,356 - freqtrade - ERROR - Fatal exception!
Oct 28 22:04:17 raspberrypi freqtrade[20872]: 2024-10-28 22:04:17,102 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
Oct 28 22:04:17 raspberrypi freqtrade[20872]: 2024-10-28 22:04:17,098 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
Oct 28 22:04:17 raspberrypi freqtrade[20872]: 2024-10-28 22:04:17,097 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}

```

**Comment by xmatthias** [comment] 2024-10-28 18:29
@kazmorebig well what's your python version (exact, minor) ... ? (`python --version`)?

you can take your pick if the error comes out of aiohttp - or from the internal asyncio module (internal to python - more likely).
Trying reloads on a more recent version of python doesn't show this behavior - at least not after doing a few test reloads.

Now my python is 3.12 - but that won't mean a more recent 3.11 wouldn't fix it - not if it's known.

I wouldn't know how else to handle this if i'm honest - freqtrade does close the ccxt exchange object as documented / requested (calling `await exchange.close()`). 


also - the uppermost line `Scheduled restart job` - does suggest that you're using systemd to restart the bot (periodically, the 5th time) - most likely via `RuntimeMaxSec` (?)
As such - it's not a "/reload_config" scenario (what this issue is about) - but a "kill it and restart it" operatoin - where you'll have to look at how systemd is shutting down the process - and depending on the signal it sends to the process (look at systemd docs?) - it might simply kill it forcefully - which may lead to problems - but not ones we can solve.

**Comment by kazmorebig** [comment] 2024-10-29 04:14
Thanks for answering, @xmatthias . My python version is `Python 3.11.2`. 
```
ccxt: 4.4.17
aiohttp: 3.10.10
```
Yes it's not `/reload_config` scenario, may be i'm wrong writing this in this topic. I see that errors while pressing reload config button in frequi.
I'm using systemd for restarting, not via `RuntimeMaxSec` but via `Restart=on-failure`. The issue doesn't reproduce when client works less than 3-4 hours.
Honestly saying it's not a critical issue for me. Because the only problem I see as a user is just longer (around 30 sec) reload configuration process. Which is fine for me and the only reason I wrote is just my guess what @20flint12 has faced.

**Comment by xmatthias** [comment] 2024-10-29 05:41
well the current 3.11 is 3.11.9 ... so i'd strongly recommend to update to that version (should be easily available on a RPI).

**Comment by 20flint12** [comment] 2024-11-01 16:13
```
2024-11-01 16:44:56,028 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:46:01,004 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:47:01,010 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:48:01,015 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:49:01,021 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:50:06,000 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RUNNING'
2024-11-01 16:50:26,002 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'reload_config'}
2024-11-01 16:50:26,003 - freqtrade.worker - INFO - Changing state from RUNNING to: RELOAD_CONFIG
2024-11-01 16:50:26,004 - freqtrade.worker - INFO - Bot heartbeat. PID=36096, version='2024.9', state='RELOAD_CONFIG'
2024-11-01 16:50:26,011 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-11-01 16:50:26,016 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-11-01 16:50:26,017 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2024-11-01 16:50:26,017 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2024-11-01 16:50:26,044 - uvicorn.error - INFO - Shutting down
2024-11-01 16:50:26,146 - uvicorn.error - INFO - Waiting for application shutdown.
2024-11-01 16:50:26,147 - uvicorn.error - INFO - Application shutdown complete.
2024-11-01 16:50:26,147 - uvicorn.error - INFO - Finished server process [36096]
2024-11-01 16:50:26,149 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2024-11-01 16:50:26,333 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-11-01 16:50:26,334 - telegram.ext.Application - INFO - Application.stop() complete
2024-11-01 16:50:28,639 - freqtrade.exchange.exchange_ws - INFO - Resetting WS connections.
2024-11-01 16:50:28,642 - freqtrade.exchange.exchange_ws - INFO - XRP/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,643 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - ETH/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,643 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - TIA/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - USDC/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - FDUSD/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - TROY/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,644 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - WLD/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,645 - freqtrade.exchange.exchange_ws - INFO - MASK/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,645 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - NEIRO/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,645 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - WIF/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,646 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - TAO/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,646 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - BOME/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,646 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - FET/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - BTC/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - SHIB/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - ENA/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,647 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - SUI/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,648 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - SOL/USDT, 5m, spot - Task finished -
cancelled
2024-11-01 16:50:28,648 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - PEPE/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:28,649 - [freqtrade.exchange.exchange](https://freqtrade.exchange.exchange/)_ws - INFO - DOGE/USDT, 5m, spot - Task finished - cancelled
2024-11-01 16:50:29,049 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2024-11-01 16:50:29,049 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2024-11-01 16:50:29,050 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2024-11-01 16:50:29,054 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2024-11-01 16:50:29,307 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/admin/Documents/freqtrade/freqtrade/main.py", line 45, in main
    return_code = args"func"
                  ^^^^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/freqtrade/commands/trade_commands.py", line 25, in start_trading
    worker.run()
  File "/home/admin/Documents/freqtrade/freqtrade/worker.py", line 80, in run
    self._reconfigure()
  File "/home/admin/Documents/freqtrade/freqtrade/worker.py", line 218, in _reconfigure
    self.freqtrade.cleanup()
  File "/home/admin/Documents/freqtrade/freqtrade/freqtradebot.py", line 218, in cleanup
    self.exchange.close()
  File "/home/admin/Documents/freqtrade/freqtrade/exchange/exchange.py", line 310, in close
    self.loop.run_until_complete(self._api_async.close())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/ccxt/async_support/base/[exchange.py](https://exchange.py/)", line 125, in close
    await self.session.close()
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/client.py", line 1192, in close
    await self._connector.close()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 833, in close
    return super().close()
           ^^^^^^^^^^^^^^^
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/connector.py", line 433, in close
    self._close()
  File "/home/admin/Documents/freqtrade/.venv/lib/python3.11/site-packages/aiohttp/[connector.py](https://connector.py/)", line 463, in _close
    transport.abort()
  File "/usr/lib/python3.11/asyncio/sslproto.py", line 247, in abort
    self._ssl_protocol._abort()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_abort'
```

crashes every time after "reload_config"

Help please

**Comment by xmatthias** [comment] 2024-11-01 16:24
@20flint12 same question to you - what exact python version are you using? (`python --version`)

**Comment by 20flint12** [comment] 2024-11-01 17:08
3.11.2

**Comment by xmatthias** [comment] 2024-11-02 07:29
as stated above (https://github.com/freqtrade/freqtrade/issues/10851#issuecomment-2443264467)

the current 3.11 is 3.11.9 ... can you please update your python version and let us  know if that fixes it? 
From the stack trace, the error comes out of core python code - it's likely not something we can fix at the freqtrade level.

**Comment by 20flint12** [comment] 2024-11-03 15:40
I noticed that when I stop the bot and make "reload_config" the bot does not break. Maybe this will help the developers with this issue.

**Comment by xmatthias** [comment] 2024-11-03 18:18
well the way it stands at this point - it's an issue with python 3.11.2 - not something we'll be looking at under the assumption that python had it fixed in the (several) years since python 3.11.2.

Is it still happening on python 3.11.9 (the lastest in the 3.11 branch) - or with python 3.12?

**Comment by xmatthias** [comment] 2024-11-14 06:21
Closing this as in my eyes, it's a bug in python 3.11.2 (haven't seen such an error with any other python version) - which will be fixed by using a more uptodate python version.

So please update your Python to get rid of this.

**Closed as completed by xmatthias** 2024-11-14 06:21 UTC
Labels: Question - Outdated Version

**Comment by xmatthias** [comment] 2024-11-14 19:13
in #10933 - we got confirmation that a newer python version will fix this issue.

As such, please update your python if you're affected by this.
On debian 12, your best bet currently will be either through pyenv or using uv - which both will allow to install a separate version of python (we recommend to go with the latest version of python 3.12 at this point).

**Comment by 20flint12** [comment] 2024-11-17 10:29
Updating to python3.12.7 solves the problem. Thanks for help!
