### ISSUE TITLE
BadRequest Exception when Loading Leverage Tiers for GLMR/USDT:USDT on OKX Exchange

### ISSUE THREAD

**Issue by wassertim** [freqtrade/freqtrade#8515] opened 2023-04-17 15:56 UTC
Describe your environment
Operating system: ubuntu
Python Version: 3.10.10
CCXT version: 3.0.23
Freqtrade Version: freqtrade docker-2023.3.dev-298f5685

Describe the problem:
I'm receiving "Could not load leverage tiers for GLMR/USDT:USDT due to BadRequest" exception when running a strategy with the OKX exchange.

Steps to reproduce:

- Set up a strategy with the OKX exchange, trading mode "futures" and margin mode isolated
- Run the strategy
- Observe the BadRequest exception in logs

Observed Results:

- The bot fails to load leverage tiers for the GLMR/USDT:USDT market on OKX exchange, raising a BadRequest exception.
- I expected the bot to successfully load leverage tiers and continue its operation.

Relevant code exceptions or logs
```
2023-04-17 15:44:36,828 - freqtrade.exchange.exchange - INFO - Initializing leverage_tiers for 127 markets. This will take about a minute.
2023-04-17 15:44:37,285 - freqtrade.exchange.common - WARNING - get_market_leverage_tiers() returned exception: "Could not load leverage tiers for GLMR/USDT:USDT due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter uly  error"}". Retrying still for 4 times.
2023-04-17 15:44:37,832 - freqtrade.exchange.common - WARNING - get_market_leverage_tiers() returned exception: "Could not load leverage tiers for GLMR/USDT:USDT due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter uly  error"}". Retrying still for 3 times.
2023-04-17 15:44:38,393 - freqtrade.exchange.common - WARNING - get_market_leverage_tiers() returned exception: "Could not load leverage tiers for GLMR/USDT:USDT due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter uly  error"}". Retrying still for 2 times.
2023-04-17 15:44:39,030 - freqtrade.exchange.common - WARNING - get_market_leverage_tiers() returned exception: "Could not load leverage tiers for GLMR/USDT:USDT due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter uly  error"}". Retrying still for 1 times.
2023-04-17 15:44:39,571 - freqtrade.exchange.common - WARNING - get_market_leverage_tiers() returned exception: "Could not load leverage tiers for GLMR/USDT:USDT due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter uly  error"}". Giving up.
2023-04-17 15:44:39,571 - freqtrade.commands.trade_commands - ERROR - cannot unpack non-iterable TemporaryError object
2023-04-17 15:44:39,571 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/commands/trade_commands.py", line 24, in start_trading
    worker = Worker(args)
  File "/freqtrade/freqtrade/worker.py", line 37, in __init__
    self._init(False)
  File "/freqtrade/freqtrade/worker.py", line 53, in _init
    self.freqtrade = FreqtradeBot(self._config)
  File "/freqtrade/freqtrade/freqtradebot.py", line 68, in __init__
    self.exchange = ExchangeResolver.load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 34, in load_exchange
    exchange = ExchangeResolver._load_exchange(
  File "/freqtrade/freqtrade/resolvers/exchange_resolver.py", line 60, in _load_exchange
    exchange = ex_class(**kwargs)
  File "/freqtrade/freqtrade/exchange/exchange.py", line 193, in __init__
    self.fill_leverage_tiers()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2436, in fill_leverage_tiers
    leverage_tiers = self.load_leverage_tiers()
  File "/freqtrade/freqtrade/exchange/exchange.py", line 2395, in load_leverage_tiers
    for symbol, res in results:
TypeError: cannot unpack non-iterable TemporaryError object
```

P.S. I will create a PR for this later

**Comment by xmatthias** [comment] 2023-04-17 17:43
This is actually a duplicate of #8512 - which was named in an unfortunate way, so it was difficult to find.

I'll have a fix for this ready soon.

**Closed as completed** 2023-04-17 17:52 UTC
Labels: Duplicate

**Comment by wassertim** [comment] 2023-04-17 20:32
@xmatthias thanks for fixing this so quick!
