### ISSUE TITLE
Performance improvement: Cuncurrency / Multithreading using Dask Distributed

### ISSUE THREAD

**Issue by Axel-CH** [freqtrade/freqtrade#1170] opened 2018-08-26 09:54 UTC
### The Problem
As I'm trading with more than 100 pairs and with a heavy strategy (600+ collumns in dataframe) the the synchronous loop that sequentially fetch ticker and make the analysis is too slow. It's making my strategy unusable on the 1m time frame as described [here](https://github.com/freqtrade/freqtrade/issues/746#issuecomment-411572008).

### The Work in progress Solutions

**1. Get each tickers data asyncronously ([PR](https://github.com/freqtrade/freqtrade/pull/1101) )**
   **_Advantages_**
        -Async so during the request waiting time the bot can perform other requests
   **_Remaining Problem_**
       -API call for each pairs, risk of reaching exchange API request limit
       -Still use one thread syncronously to do the analysis (get_signal)

**2. Get all tickers prices with only one API call ([ISSUE]**(https://github.com/freqtrade/freqtrade/issues/1046))
     **_Advantages_**
          -Only one API call per loop good for requests limits
          -Compute power saved by not handling multiple requests
     **_Remaining Problem_**
           -Still use one thread syncronously to do the analysis (get_signal)

I have a Huge preference for the solution 2 this solution. It will help to improve drastically the speed of the loop by removing the API request in it. 

### It will be enought?

In my case the analysis time remain a big problem. After optimizing the strategy I’m at a point where I don’t think more optimisation will be enought.
During my tests I found that my worst DeltaTime* can reach more than tree minutes. 
*DeltaTime: Time between candle close and end of Pair Analysis

### Solution: Scale Verticaly with Dask
The solution that I see is to alow freqtrade to use the full compute power of the host CPU by taking advantage of all his cores.
_My former AI profesor told me about a new amazing python library that manage multitreading and concurency without adding a lot of complexity : Dask. After some reasearch I found out that Dask could be one of the best solution to enhance the speed of freqtrade by alowing us to scale verticaly and horizontaly._

As Multiprocessing add complexity for debugging Dask have also a realtime monitoring and debuging dashboard. More info on the [official website](http://dask.pydata.org/en/latest/)

![ezgif com-crop 1](https://user-images.githubusercontent.com/7593404/44626872-6253a100-a8f2-11e8-8cfd-3de947454fc1.gif)

### The POC / Test
**Goal**
Validate that Dask can improve freqtrade speed
Explaination
I've tested tree different loop architecture:

**Option 0.** 
Equivalent of current loop with dask implementation (single thread)

**Option 1.** 
Dask implementation of multithreading with a system of Tasks Bags. Each bag have Bag have a Task capacity of dask client currents workers number. In my case I have a Intel I5 with four thread so Dask create automatically 4 workers. In the code I wait for four tasks to send the work to my workers in order to use them efficiently. The bumber of task bags will depend of the number of pairs.

**Option 2.**
Dask implementation of multithreading with one task bag for each function (get_history, get_signal)

### Time Result
**Option 0:**
    Loops executions times:
        45.83s
        43.89s
        42.14s
        42.50s
        42.80s
    Estimated Delta Times for best loop:
        minimum: 1s
        maximum: 42s

**Option 1:**
    Loops executions times:
        13.97s
        13.55s
        12.35s
        12.77s
        13.22s
    Estimated Delta Times for best loop:
        minimum: 3s (time / workers_number)
        maximum: 12s

**Option 2:**
    Loops executions times:
        10.99s
        10.91s
        10.44s
        16.56s
        16.77s
    Estimated Delta Times for best loop:
        minimum: 9s
        maximum: 10s

    ### Dask Task Stream
**Option 0**
<img width="1037" alt="freqtrade_loop_task_stream_option_0" src="https://user-images.githubusercontent.com/7593404/44626318-0c79fb80-a8e8-11e8-8d9e-f86292988ada.png">
**Option 1**
<img width="1035" alt="freqtrade_loop_task_stream_option_1" src="https://user-images.githubusercontent.com/7593404/44626336-5c58c280-a8e8-11e8-9231-c655c6dcd91f.png">
**Option 2**
<img width="1060" alt="freqtrade_loop_task_stream_option_2" src="https://user-images.githubusercontent.com/7593404/44626349-a346b800-a8e8-11e8-9f47-91a086daf39a.png">

### Conclusion
**Option 0** => BAD, Syncronous and only one worker used
**Option 1** => GOOD, Take advantage of all workers efficiently
**Option 2** => BAD, The workers are used efficiently but as we wait for all API responses the minimum DeltaTime explode

The best Option for the moment seem to be the  "Option 1" because it combine a good minimum and a moderate maximum delta time. Im my case **I obtain a almost X4 Performance gain** it's corralated my 4 cores and threads CPU. Now I just need to BUY a AMD Threadripper 2990WX (32 cores / 64 Threads) 😊

### POC Code
[dask-test.zip](https://github.com/freqtrade/freqtrade/files/2321399/dask-test.zip)

You can navigate on the Dask Dashboard once you lanched the code [HERE](http://127.0.0.1:8787/status)
NB: For the Moment the code concurrency is throught threads but it's synchronous, I was not able to use the Async feature of Dask (issues with map). I'm planning to open an Issue on their github soon.

**Comment by xmatthias** [comment] 2018-08-26 10:47
I think you might want to have a look at #1119 too - it analyzes the candles only once per ticker interval, which (depending on the strategy) makes a ton of sense as nothing "new" happens for the candle between that time.

`get-signal` is surely a problem which i guess will be taken on once async #1101 is merged, but when running async a lot of the problem is already gone.

having never aktively used dask (only played with it a bit) - i have a few (or one) question:

how does dask work with the "regular" indicator frameworks (ta-lib, ...)? does this still work flawlessly, but faster/in parallel, or do you need to write custom functions to convert dask Dataframe to pandas Dataframe and back?

would converting the DF to dask within the strategy be an alternative?

**Comment by Axel-CH** [comment] 2018-08-26 11:06
Hi @xmatthias I already tried #1119 but with no improvement, is't logical because as I mentioned [here](https://github.com/freqtrade/freqtrade/issues/746#issuecomment-411572008) the loop take more than 1min candle to finish. It's one loop each time not multiple analysis of the same datas.

The async will be an improvement for sure but the loop is taking too much time yet because of the strategy and the huge whitelist.

Concerning Dask I didn't use it actively like you but I am trying it. I as I know there is no need to write custom function. I will Integrate it in freqtrade shortly as an experimental feature and I will confirm you.

**Comment by mishaker** [comment] 2018-08-26 12:58
@Axel-CH seems like you are mixing up few concepts. 

* Fetching **candles** from an exchange. the "all market API" does not exist for that. only per market API. the only thing you can do about that is to try to save IO calls. this improvement is addressed here #1101 
* Fetching **tickers** all in once for all markets (all prices at once). this is not supported by all exchanges but at least for Binance. this is as far as I know a work in progress but it doesn't help analysis time. only sell/buy time. 
* Analyzing a DataFrame with huge amount of indicators and operations. this is a touchy one: Dask only allows you to optimize calculation time on data coming from the disk not in memory. in Freqtrade everything is memory. Native Pandas is faster than Dask on it (c.f. http://dask.pydata.org/en/latest/dataframe-performance.html)

**Comment by Axel-CH** [comment] 2018-08-26 16:53
@mishaker thank you for the clarifications.

However for the third point I'm not agree with you. Dask have multiple modules and usages. What you described is Dask Dataframes. What I use In this POC is Dask Distributed that use a scheduler to distribute asynchronously workload accros workers with Distincts ThreadPool.
You will find the doc of Dask Distributed [Here](https://distributed.readthedocs.io/en/latest/)

Feel free to try the [POC of Dask Distributed](https://github.com/freqtrade/freqtrade/files/2321694/dask-test.zip) that I joined

**Comment by iuvbio** [comment] 2019-02-19 22:12
Hi, this is a great initiative, I think there are quite some possibilities for performance improvements.

I've never used Dask, so please ignore my ignorance, but why would it be preferable to use it over the built-in `threading` or `multiprocessing` module? Is it worth introducing an additional dependency?

**Comment by Axel-CH** [comment] 2019-03-02 17:08
Hi @iuvbio One of the main advantage I see in using the Dask over the built-in python modules is the possibility to prioritize tasks over other. One use case would be to be able to check more often the price of pairs with an opened trade, without having to wait the next main loop iteration.
This way the bot will be more quick, that will open more possibilities to find a better exit for opened trades. 
You can get more informations on [dask website](https://dask.org/).

**Comment by Axel-CH** [comment] 2019-03-10 17:48
For Information I managed make freqtrade run with dask for live run. The performance improvement is really promising. The issue is that I have memory leak that make the bot crash after a few hours of running. It's related to [this issue](https://github.com/dask/distributed/issues/2068).
I will investigate with a memory profile to find if there is really leaks.

**Closed** 2019-06-20 02:04 UTC
Labels: enhancement

**Comment by jakubikan** [comment] 2022-02-01 07:13
Is There any update on this? 
I feel like the performance could be increased with freqtrade by spliting up the pair calculation on multiple cores. 
Currently mostly only one core used to do the calculation. 
I think this could be picked up again

**Comment by xmatthias** [comment] 2022-02-01 07:15
@jakubikan Please don't revive issues that are almost 4 (!) years old.

we will  surely not be implementing dask - as that will bear the risk of breaking people's strategies - as dask is similar - but not identical to pandas dataframes - so some methods would break.
Setup for non-experienced users is also non-trivial - which would mean we would be tasked with supporting that - which we quite frankly, don't have the capacity to.
