### ISSUE TITLE
Problem with pycharm debugger

### ISSUE THREAD

**Issue by CryptoRahino** [freqtrade/freqtrade#8960] opened 2023-07-24 12:42 UTC
## Describe your environment
Operating system: ubuntu 22
Python Version: 3.10 (python -V)
CCXT version: ccxt==4.0.17: (pip freeze | grep ccxt)
Freqtrade Version: 2023.6 (freqtrade -V or docker compose run --rm freqtrade -V for Freqtrade running in docker)

## Describe the enhancement

this issue is related to https://github.com/freqtrade/freqtrade/issues/8895.
happens only in pycharm debugger.
**Problem**:
due to functionality of pycharm's debugger, since version 2023.6 it fails to run in debug due to circular imports.
mainly because of `from types import GenericAlias` calls to `freqtrade/freqtrade/types/__init__.py`, as "types" naming confusing it.

**Solution**:
rename the folder `reqtrade/freqtrade/types` to other name.

**Comment by xmatthias** [comment] 2023-07-24 13:38
As mentioned in #8895, this seems to be a bug in pycharm, or rather, in the way you setup pycharm debugging (most likely calling the wrong thing).

I was unable to reproduce this with the setup we have documented (as mentioned in the other issue) - and you didn't provide any further feedback or information on how you've set it up - therefore i concluded that it's related to your setup (and i still stick to this opinion until you provide actual, actionable information.

Therefore, please either fix your setup to align it with the way we have it documented, or point us to some official documentation (either pycharm or python) which mentions the "forbidden" use of "types" in naming.


Please understand that i will not rename directories at will because of a random report saying "this needs to be renamed" - where the root of the problem is neither clear nor reproducible.

---

Also, please avoid opening the same issue multiple times. 
The other issue is not locked. It's been closed as you didn't provide any further feedback or information - and i'll approach this issue the same way.

Opening another issue with the same topic will force me to block you from opening issues here.

**Comment by CryptoRahino** [comment] 2023-07-24 17:21
for me the reproduction steps are as described in https://github.com/freqtrade/freqtrade/issues/8895. 
the solution is quite easy, renaming the directory, which is used by the buitin library `types`

**Comment by xmatthias** [comment] 2023-07-25 04:56
There are no reproducible steps, as they're missing most of the information (how was pycharm exactly configured, ...).
I followed your steps and it worked - so the error must be on your configuration.

I've also pointed out in #8895 that your stacktrace / startup script provided suggests that you're **not**  following the documentation in regards to setup - and i assume that still didn't change (please change it before retrying).

 Setting up pycharm the way we have it in the [documentation](https://www.freqtrade.io/en/stable/developer/#debug-configuration) does work. I've explicitly tested it for #8895, and i'll not waste more time on this topic unless we get proper information to reproduce this independently.

Please provide
* the EXACT steps you took
* The EXACT configuration you're using for your pycharm start (best use screenshots - pycharm doesn't seem to make sharing debug configurations easy)

**Comment by xmatthias** [comment] 2023-08-07 05:02
Closing this as we had no further feedback.

I cannot recreate what you're experiencing when setting up pycharm the way we have it documented (and we lack information on how YOU set it up to be able to recreate this).
My conclusion for now is therefore that it's due to your setup, not due to a problem with freqtrade.


If you still think this is an issue, i'm happy to reopen this once the the information requested above has been provided, so we can independently verify this.

**Closed as completed by xmatthias** 2023-08-07 05:02 UTC
Labels: Duplicate, Question

**Comment by issacnumb** [comment] 2023-08-12 07:36
> ## 描述您的环境
> 操作系统：ubuntu 22 Python 版本：3.10 (python -V) CCXT 版本：ccxt==4.0.17: (pip freeze | grep ccxt) Freqtrade 版本：2023.6 (freqtrade -V 或 docker compose run --rm freqtrade -V for Freqtrade 在 Docker 中运行）
> 
> ## 描述增强功能
> [这个问题与#8895](https://github.com/freqtrade/freqtrade/issues/8895)有关。 仅发生在 pycharm 调试器中。 **问题**： 由于 pycharm 调试器的功能，自版本 2023.6 起，由于循环导入，它无法在调试中运行。 主要是因为`from types import GenericAlias`对`freqtrade/freqtrade/types/__init__.py`, 作为“类型”命名的调用令人困惑。
> 
> **解决方案**： 将文件夹重命名`reqtrade/freqtrade/types`为其他名称。

meet the same problem

**Comment by xmatthias** [comment] 2023-08-12 13:42
@issacnumb you may have the same problem - but you're not providing more information.

I can debug with pycharm just fine (as mentioned above) - using the debug setup we have in the documentation. 
If you're having problems, then this setup will differ.

Unless someone can provide HOW their setup works - there will be no further help on this type of issues.
