### ISSUE TITLE
Backtesting on customised pairlist

### ISSUE THREAD

**Issue by bibinvargheset** [freqtrade/freqtrade#5833] opened 2021-11-04 12:28 UTC
The backtesting is hugely inaccurate beacuse of the inablity to have volume pairlist  as those with huge volumes in future is essentially the sucessful coins. George  have scripted a code for  [volume pair list](https://github.com/GeorgeMurAlkh/freqtrade-stuff)  creating the volume pairlist from past. This cannot be used directly on freqtrade currently. the only way is to divide the backtesting into parts and join. This also will result in truncation errors.  Hence my request is to implement timebound pairlist application on backtest so that backtest results are more reliable than what is now

**Comment by xmatthias** [comment] 2021-11-04 12:39
Please use the search to find already existing issues before opening new issues.

Closing as duplicate of #4401.

**Closed as completed by xmatthias** 2021-11-04 12:39 UTC
Labels: Duplicate, Backtest
