### ISSUE TITLE
ERROR - Maintenance margin rate for QNT/USDT is unavailable for Binance

### ISSUE THREAD

**Issue by tomjrtsmith** [freqtrade/freqtrade#7802] opened 2022-11-26 21:27 UTC
## Describe your environment

  * Operating system: ____ Ubuntu 22.04
  * Python Version: _____ (`python -V`) 3.10.4
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: ____ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker) 22.11.dev0
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered* The software crashes and requires restarting in a TMUX terminal

### Steps to reproduce:

  1. _____ Start Freqtrade with generic  config and leave running in a TMUX terminal
  2. _____
  3. _____
  
### Observed Results:

  * What happened? Freqtrade crashed
  * What did you expect to happen? The software to work / restart. I thought I had started the service as a daemon and that the freqtrade.service.watchdog would restart if it errored but this didn't happen so wondering steps to resolve. This has happened abt 3 times in 24 hours so wondering if it shouldn't be caught by error handling? 

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
2022-11-26 21:16:46,886 - freqtrade.commands.trade_commands - ERROR - Maintenance margin rate for QNT/USDT is unavailable for Binance
2022-11-26 21:16:46,886 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/ubuntu/freqtrade/freqtrade/commands/trade_commands.py", line 19, in start_trading
    worker.run()
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 75, in run
    state = self._worker(old_state=state)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 116, in _worker
    self._throttle(func=self._process_running, throttle_secs=self._throttle_secs,
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 147, in _throttle
    result = func(*args, **kwargs)
  File "/home/ubuntu/freqtrade/freqtrade/worker.py", line 180, in _process_running
    self.freqtrade.process()
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 211, in process
    self.manage_open_orders()
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 1235, in manage_open_orders
    fully_cancelled = self.update_trade_state(trade, trade.open_order_id, order)
  File "/home/ubuntu/freqtrade/freqtrade/freqtradebot.py", line 1771, in update_trade_state
    trade.set_liquidation_price(self.exchange.get_liquidation_price(
  File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 2707, in get_liquidation_price
    isolated_liq = self.dry_run_liquidation_price(
  File "/home/ubuntu/freqtrade/freqtrade/exchange/binance.py", line 187, in dry_run_liquidation_price
    mm_ratio, maintenance_amt = self.get_maintenance_ratio_and_amt(pair, stake_amount)
  File "/home/ubuntu/freqtrade/freqtrade/exchange/exchange.py", line 2807, in get_maintenance_ratio_and_amt
    raise InvalidOrderException(
freqtrade.exceptions.InvalidOrderException: Maintenance margin rate for QNT/USDT is unavailable for Binance
2022-11-26 21:16:46,893 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2022-11-26 21:16:46,893 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2022-11-26 21:16:46,893 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2022-11-26 21:16:46,897 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "14 open trades active.\n\nHandle these trades manually on Binance, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \nNote: Trades are simulated (dry run)."}
  ```

**Comment by xmatthias** [comment] 2022-11-27 07:10
22.11.dev0 is not a valid freqtrade version - freqtrade versions contain the commit hash at the end, telling us your precise version.

purely from the error, i can tell that your version is at least a few days old.

---

binance dry-runs are using cached maintenance rates (since the rates themselfs are behind the auth wall).

I've updated the tiers just this week - and QNT/USDT is now part of this file - so the error won't happen on uptodate develop versions.

This is a breaking error - intentionally stopping the bot - as this is a scenario we can't handle safely.
The equivalent for live would be that you enter a trade, but the exchange doesn't tell us the price (or rather, what it'll cost to stay in this position). 
we can't assume it's free (that's unrealistic) - and the rates themselfs differ quite strongly from pair to pair, and are also dependant on position size.


Closing this as duplicate of #7794.

**Closed as completed by xmatthias** 2022-11-27 07:10 UTC
Labels: Duplicate, Question
