### ISSUE TITLE
Negative EUR performance, but positive % performance

### ISSUE THREAD

**Issue by mathias5986** [freqtrade/freqtrade#4250] opened 2021-01-22 22:38 UTC
Hello,

I am wondering why I get a loss of 200 EUR while I have a positive performance of +9%. Can someone explain this to me?
[
<img width="365" alt="Screenshot 2021-01-22 at 23 30 25" src="https://user-images.githubusercontent.com/74938818/105556685-ce78a000-5d0a-11eb-9549-36930aace898.png">
](url)

Thanks!

**Comment by xmatthias** [comment] 2021-01-23 08:05
Please read the explanation in #3804 as to why this happens (it's a direct duplicate of that issue).

TLDR:
Currently, profit % calculations are summed up evenly (sum of each trade's profits).
The correct way would be to weight it based on the trade size (i assume you're using stake_amount=unlimited, OR you changed the stake-size sometime in the middle).

There's multiple issues related to this and i'm working on fixing them all - but profit calculations are used in many parts of the bot - so it may still take a bit.

**Closed as completed by xmatthias** 2021-01-23 08:05 UTC
Labels: Duplicate, Question

**Comment by mathias5986** [comment] 2021-01-23 11:57
Thank you, Matthias. Yes exactly, it actually needs to take into account the stake amount, because sometimes you have a partially filled buy order of +10% and sometimes you have a complete buy order of -10%, which is clearly not a break even point.

So from what I understand is that the EUR amount is correct?
