### ISSUE TITLE
Hyperopt claims indicator_space not found in my strategy file But the documentation says : its not needed anymore

### ISSUE THREAD

**Issue by lyncker** [freqtrade/freqtrade#4854] opened 2021-05-02 12:04 UTC
## Describe your environment

  * Operating system: Ubuntu20.x
  * Python Version: Dockerversion
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version:  2021.4
  
## Your question

I am trying to implement my Class like described in the documentation using the new format without a dedicated hyperopt class ... First I defined my hyperoptable paramenters directly in my class :
    buy_adx = IntParameter(20, 40, default=30)
    buy_rsi = IntParameter(20, 40, default=30)
then I wrote my populate_indicators function and the populate_buy_trend ...
after starten hyperopt it claims that I need to inlcude a indicator_space.. but the content of the indicator space is written directly in the class (see above) and the function from my old opt-class canot be copied to the strategy file due to different API defs in strategy and HyperoptClass files
What I am missing here?

**Comment by xmatthias** [comment] 2021-05-02 13:00
If you're using the new hyperopt parameters, you should not be passing a `--hyperopt` parameter at all - only then will it load the "AutoHyperopt" Parameters properly.

**Comment by lyncker** [comment] 2021-05-02 13:07
Hi xmatthias, thanks for your answer: here is my freqtrade call, I am not using the --hyperopt parameter ...

freqtrade hyperopt -c user_data/myconfig-static.json  -e 3000  --strategy ADXMomentum --hyperopt-loss SharpeHyperOptLossDaily  --timerange 20200101-20201231 --min-trades 100

Here is the full error message : 
2021-05-02 13:04:39,773 - freqtrade - ERROR - The 'buy' space is included into the hyperoptimization but indicator_space() method is not found in your custom Hyperopt class. You should either implement this method or remove the 'buy' space from hyperoptimization.

**Comment by xmatthias** [comment] 2021-05-02 13:08
can you share more of your class? the parameters need to be at class-level - with wrong indentation they might not be found ...

**Comment by lyncker** [comment] 2021-05-02 13:20
ok here the complete classfile : 
```
from freqtrade.strategy.interface import IStrategy
from pandas import DataFrame
from freqtrade.strategy import CategoricalParameter, DecimalParameter, IntParameter
import talib.abstract as ta


# --------------------------------


class ADXMomentum(IStrategy):


    # Minimal ROI designed for the strategy.
    # adjust based on market conditions. We would recommend to keep it low for quick turn arounds
    # This attribute will be overridden if the config file contains "minimal_roi"
   
   minimal_roi = {
        "0": 0.297,
        "285": 0.138,
        "509": 0.052,
        "1150": 0

    }

    # Optimal stoploss designed for the strategy
    stoploss = -0.336

    # Optimal timeframe for the strategy
    timeframe = '1h'

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 20
    adx_TF = IntParameter(6, 20, default=14)
    plusDI_value = IntParameter(0, 100, default=25)
    minusDI_value = IntParameter(0, 100, default=25)
    MOM_value = IntParameter(-5, 5, default=0)


    adx_enabled = CategoricalParameter([True, False]),
    minusDI_Enabled = CategoricalParameter([True, False]),
    plusDI_Enabled = CategoricalParameter([True, False]),
    MOM_Entabled = CategoricalParameter([True, False]),
   

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        
		for val in self.adx_TF.range:
            dataframe[f'adx_TF_{val}'] = ta.EMA(dataframe, timeperiod=val)

        dataframe['adx'] = ta.ADX(dataframe, timeperiod=14)
        dataframe['plus_di'] = ta.PLUS_DI(dataframe, timeperiod=14)
        dataframe['minus_di'] = ta.MINUS_DI(dataframe, timeperiod=14)
        dataframe['mom'] = ta.MOM(dataframe, timeperiod=14)
        dataframe['ADXslope'] = ta.LINEARREG_SLOPE(dataframe['adx'])

        return dataframe
    

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    if params.get('adx-enabled'):
                        conditions.append(dataframe[f'adx_buy_{self.buy_adx.value}'] > params['ADX-value'])

                    (dataframe['adx'] > 51) &
                    (dataframe['mom'] > 0) &
                    (dataframe['plus_di'] > 25) &
                    (dataframe['plus_di'] > dataframe['minus_di'])

            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                    (dataframe['adx'] < 0) &
                    (dataframe['mom'] < 0) &
                    (dataframe['minus_di'] > 25) &
                    (dataframe['plus_di'] < dataframe['minus_di'])

            ),
            'sell'] = 1
        return dataframe
```

**Comment by xmatthias** [comment] 2021-05-02 15:07
Parameters must eihter explicitly define a space `space='buy'` - or be named `buy_*` or `sell_*`.

As you do neither, they don't belong to any space - so the message you receive is correct.

**Comment by lyncker** [comment] 2021-05-02 19:36
ah great... ok I did not notice , that the name is relevant ... ok this seems to be working now , but now I have the next problem, I changed the populate_buy_trend to the format which is given in the Hyperopt Documentation , my function looks like this : 

```
def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        conditions = []
        # GUARDS AND TRENDS
        if self.buy_adx_enabled.value:
            conditions.append(dataframe['buy_adx'] > 10)

        conditions.append(dataframe['volume'] > 0)

        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'buy'] = 1

        return dataframe


```
I got the error: 

```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 86, in start_hyperopt
    hyperopt.start()
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 455, in start
    f_val = self.run_optimizer_parallel(parallel, asked, i)
  File "/freqtrade/freqtrade/optimize/hyperopt.py", line 371, in run_optimizer_parallel
    return parallel(delayed(
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/ftuser/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
AttributeError: 'tuple' object has no attribute 'value'
```


It seems to be the line :  if self.buy_adx_enabled.value: which makes the problem ... but I copied this from the documentation .. 
sorry Im lost ;(
By the way: the call freqtrade new-hyperopt produces only an legacy (old) format of the hyperopt file, is there a possability to get a working strategy file example ?

**Comment by MyDigitalLife** [comment] 2021-05-02 19:49
I ran into the same exception about the value attribute. The issue is that after the CategoricalParameter theres a comma. The issue is also in the documentation so that should be fixed asap.

**Comment by lyncker** [comment] 2021-05-02 21:21
thanks a lot  .. that worked ... the documentation should be updated ;)

**Comment by Epik1993** [comment] 2021-05-02 23:43
Hello lyncker I have the same problem
"freqtrade - ERROR - The 'buy' space is included into the hyperoptimization but indicator_space() method is not found in your custom Hyperopt class. You should either implement this method or remove the 'buy' space from hyperoptimization.""
Will you PLEASE show how you fixed the problem?

**Comment by xmatthias** [comment] 2021-05-03 04:27
> thanks a lot .. that worked ... the documentation should be updated ;)

The (latest) documentation was updated yesterday evening :)

**Comment by lyncker** [comment] 2021-05-03 06:00
@Epik1993 : sure, if you implement the  Hyperoptable parameters as shown in the documentation, there were some comma signs at the and of the CategoricalParameter code lines... like this : 

`buy_adx_enabled = CategoricalParameter([True, False]),`
remove that comma's and everything will be fine ;)

by the way dont forget to import the 
`from functools import reduce`
to the class file if you get the next error "reduce not found"....

**Comment by lyncker** [comment] 2021-05-03 06:10
@xmatthias thank you ... you guys are doing an awesome work here... its realy great !

**Comment by xmatthias** [comment] 2021-05-03 07:51
I've clarified this point in the documentation now ... hope this helps future users with the same problem.

**Closed as completed by xmatthias** 2021-05-03 07:51 UTC
Labels: Question, Hyperopt
