### ISSUE TITLE
Wrong usage of bids and asks from orderbook during sell

### ISSUE THREAD

**Issue by hroff-1902** [freqtrade/freqtrade#2637] opened 2019-12-09 18:04 UTC
If `use_order_book` is set to True in the `ask_strategy`, the `handle_trade()` implements its own way to calculate sell_rate -- it uses asks from the orderbook:

https://github.com/freqtrade/freqtrade/blob/aa335d8485cb7099fd5a084f685babd3f4b4d1dd/freqtrade/freqtradebot.py#L606-L626

else it calls `get_sell_rate()`, which also has a branch for calculating sell_rate when `use_order_book` is set to True -- using bid prices from either orderbook or from the ticker. However, this is not used, since `handle_trade()` calculates sell_rate by itself using ask prices. This price (calculated using asks) is then passed to `_check_and_execute_sell()`. The latter passes this sell_rate to `should_sell` and `execute_sell`. The latter finally calls `_notify_sell`. The latter calls `get_sell_rate()` again, which in this case has a chance to calculate the sell rate using bids, so the bid price is reported. In the same time, all logic in `should_sell` and `execute_sell` used the price calculated by `handle_trade` using ask prices.

In my opinion, the logic for defining sell_rate using asks should be imployed (moved, merged somehow) into the generic `get_sell_rate`. Even better, both bid price and ask prices should be fetched from either the ticker or the orderbook and passed to `should_sell` and `execute_sell` -- because it depends on the type of sell order, will it be a sell market (when bids should be used) order or a sell limit order (when asks should be used). Corresponding price (bid or ask, depending on a type of the sell order, market or limit, whether it's sell signal, roi or stoploss, the types may differ) should be used in all calculations inside `should_sell()`, in `stoploss_reached()` and `min_roi_reached()`, same should be reported in `_notify_sell()`

The explicit bug consists now in that `should_sell` logic uses ask prices and `_notify_sell` then reports bid price from the orderbook.

**Comment by hroff-1902** [comment] 2019-12-09 18:06
Seems to be related to #1667.

**Comment by hroff-1902** [comment] 2019-12-09 18:20
I would call it a bug, if you don't mind...

**Comment by xmatthias** [comment] 2019-12-09 18:38
to me, it's actually a duplicate of #1667 (apart from the fact that we never noticed that it's implemented twice).

Funnily, i've been looking at that particular issue 2 days ago - and thought that maybe we should close it, since using asks seemed like the correct way to go (obviously i didn't notice that we use the orderbook for selling twice).

After seeing this i agree, sell_rate logic should be combined into `get_sell_rate()` (odd we never noticed this duplication before ...).

using bids as sell_rate (as implemented in `get_sell_rate()`) is wrong anyway, since using the bid (no matter if it's the highest or 2nd highest...) will result in a market order (or marketable limit order), since the price we supply is the price the highest buyer is willing to pay.

**Comment by xmatthias** [comment] 2019-12-09 19:35
Looking at the code in handle_trade again, i don't think it can be merged into `get_sell_rate()`.

What it does is the following:

it get's the orderbook - and "checks" sell conditions "up the orderbook".
So basically, it'll (within the same iteration) check for sell-conditions at [100, 101, 102, 103, ...] (up to `order_book_max` orderbook spots).

This may allow to place the sell-order "early" - so you're further ahead in the queue.

Now thinking this through, this may conflict with other options (trailing stop / stoploss on exchange) ... and may be dangerous to use (since we don't track it as "early order" which will eventually be cancelled should the trade go wrong) - but i guess with using rather low sell-timeouts it can be useful.

Unfortunately, as #1583 points out - there is almost no documentation on how the orderbook feature really works - so i think almost noone will use this.

An enhancement (and probably not even a difficult one) could be #911 - which would (in the above scenario) place the orders between 2 orders (so 100.5, 101.5).

**Closed** 2020-03-04 13:07 UTC
Labels: Bug
