### ISSUE TITLE
Order not found: attempts to fetch non-existent stoploss order on Bybit

### ISSUE THREAD

**Issue by popperwin** [freqtrade/freqtrade#9587] opened 2023-12-23 00:18 UTC
## Describe your environment

  * Operating system: Ubuntu 18.04.3 LTS
  * Python Version: 3.10.13 (`python -V`)
  * CCXT version: 4.1.31 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2023.11-dev-8c2920eb1 (`freqtrade -V` or `docker compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

After stopping the bot and making modifications to my strategy, I restarted it and noticed that it attempts to fetch old orders from Bybit using fetch_order() which do not exist anymore. These orders are related to trades that have been verified as closed in the 'trades' table of the database. However, the bot still tries to fetch these orders several times before eventually cancelling them, resulting in a lengthy and inefficient process. Even after manually changing the status of these orders from 'open' to 'closed' in the database, the bot reports 855 open orders and attempts to fetch them.

I am using a custom stoploss function and also `stoploss_on_exchange` feature in my strategy.

For reference, my custom_stoploss function is defined as follows:

```
def custom_stoploss(self, pair: str, trade: 'Trade', current_time: datetime,
                    current_rate: float, current_profit: float, **kwargs) -> float:
    sl = *some logic*
    return stoploss_from_open(-sl, current_profit, is_short=trade.is_short)  
```

### Steps to reproduce:

  1. Stop the bot and modify the trading strategy.
  2. Restart the bot.
  3. Observe the bot attempting to fetch non-existent orders from Bybit.
  
### Observed Results:

  * What happened?
The bot repeatedly tries to fetch orders from Bybit that do not exist, leading to numerous error messages. It shows 855 orders as opened and attempts to fetch them, despite their status being manually changed to 'closed' in the database. To temporarily bypass this issue, I am using "skip_open_order_update": true in the config, but it's just a workaround.
  
  * What did you expect to happen?
The bot should recognize the updated status of orders in the database and not attempt to fetch non-existent orders from Bybit. The bot should accurately reflect the current status of orders without relying on workarounds.

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

Fetch execption
  ```
2023-12-22 19:31:41,825 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CVC/USDT:USDT id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). Message: Order xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx does not exist.". Retrying still for 5 times.
  ```
  
Order table of non closed order:

```
sqlite3
SQLite version 3.43.2 2023-10-10 12:14:04
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open live_run/bdd.sqlite

sqlite> SELECT * FROM orders 
WHERE status = 'open' ;

6|3|stoploss|CVC/USDT:USDT|1|2590.0|0.11138||xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|open|CVC/USDT:USDT|market|sell|||2590.0|0.0|2590.0|0.0|0.11138|2023-11-20 00:46:43.920000||2023-11-20 00:49:28.361113||
8|2|stoploss|YFI/USDT:USDT|1|0.0362|8630.0||xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|open|YFI/USDT:USDT|market|sell|||0.0362|0.0|0.0362|0.0|8630.0|2023-11-20 00:49:27.241000||2023-11-20 01:29:38.043918||
9|3|stoploss|CVC/USDT:USDT|1|2590.0|0.12089||xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|open|CVC/USDT:USDT|market|sell|||2590.0|0.0|2590.0|0.0|0.12089|2023-11-20 00:49:28.805000||2023-11-20 08:01:33.829639||
12|4|stoploss|DYDX/USDT:USDT|1|94.7|3.79||xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|open|DYDX/USDT:USDT|market|buy|||94.7|0.0|94.7|0.0|3.79|2023-11-20 02:40:53.172000||2023-11-20 02:41:56.921434||
13|4|stoploss|DYDX/USDT:USDT|1|94.7|3.531||xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|open|DYDX/USDT:USDT|market|buy|||94.7|0.0|94.7|0.0|3.531|2023-11-20 02:41:57.662000||2023-11-20 04:57:19.386047||
15|5|stoploss|ILV/USDT:USDT|1|3.43|104.515||xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx|open|ILV/USDT:USDT|market|buy|||3.43|0.0|3.43|0.0|104.515|2023-11-20 03:16:10.638000||2023-11-20 03:17:15.098939||

```

Also, this SQL request shows that the only open order are ft_order_side=stoploss

```
sqlite> SELECT DISTINCT ft_order_side FROM orders WHERE status = 'open';
stoploss
```

**Comment by xmatthias** [comment] 2023-12-23 07:16
first off, your select is wrong - freqtrade will use something around the following:

```
select * 
from orders
where ft_is_open = 1
```

As long as orders are open based on this query, the bot HAS to attempt to close them - as they've not been properly handled before.


This can for example happen if
* the bot was stopped for a lengthy period of time
* you stopped the bot and canceled these orders manually on exchange
* the original bot was started with a very old version and was updated then
* You modified the database in some way (update queries, ...)
* you stopped the bot forcefully (ctrl+c multiple times) - and then moved the database file WITHOUT moving the corresponding -shm and -wal files - which would revert the database to some prior state (how much prior is not exactly specified).

In any case, this will be a one-off exercise - and once it went through all orders, they'll all be marked as canceled (assuming the orders are more than 5 days old).

---

What you're seeing now is simply the effect - what actually happened, you'll have to look at in the old logs (from before the restart) - which should tell us why have these orders not been closed?.
Without these - i'll have to treat this as question - as there's no actual info to move forward.

What happens now is by design - and leaving it move through the process once will not have it do the same again.

**Comment by popperwin** [comment] 2023-12-23 12:14
Thanks for your reply.

In the database the two sql command seems to return the same line. But from what you said I understand that I need to change also `ft_is_open` to 0  to avoid the bot trying to fetch those orders.

Concerning the possible reasons you said, none of this happened:
This can for example happen if

-  **the bot was stopped for a lengthy period of time:** No I stopped only 5 minutes, the time to change something in the exit logic and I restarted it
-  **you stopped the bot and canceled these orders manually on exchange:** No , the bot was running smoothly during for one month, without no interruption, and I have never done something directly by myself on the exchange
-  **the original bot was started with a very old version and was updated then:** No, I didn't changed the bot. However, the first time I have seen the error, I have updated the bot from `2023.11-dev-8c2920eb1`to `freqtrade 2023.12-dev-fc5b78299`
-  **You modified the database in some way (update queries, ...):** No I didn't
-  **you stopped the bot forcefully (ctrl+c multiple times) - and then moved the database file WITHOUT moving the corresponding -shm and -wal files - which would revert the database to some prior state (how much prior is not exactly specified):** No, I have stopped with the kill command. Here are the logs of termination


```
2023-12-22 19:11:19,991 - freqtrade.commands.trade_commands - INFO - SIGINT received, aborting ...
2023-12-22 19:11:19,991 - freqtrade.commands.trade_commands - INFO - worker found ... calling exit
2023-12-22 19:11:19,991 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2023-12-22 19:11:19,992 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2023-12-22 19:11:20,000 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': "1 open trades active.\n\nHandle these trades manually on Bybit, or '/start' the bot again and use '/stopentry' to handle open trades gracefully. \n"}
2023-12-22 19:11:20,001 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
2023-12-22 19:11:20,001 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.apiserver ...
2023-12-22 19:11:20,004 - freqtrade.rpc.api_server.webserver - INFO - Stopping API Server
2023-12-22 19:11:20,021 - uvicorn.error - INFO - Shutting down
2023-12-22 19:11:20,022 - uvicorn.error - INFO - connection closed
2023-12-22 19:11:20,022 - freqtrade.rpc.api_server.ws.channel - INFO - Disconnected from channel - WebSocketChannel(01a6eea7, ('127.0.0.1', 60414))
2023-12-22 19:11:20,122 - uvicorn.error - INFO - Waiting for application shutdown.
2023-12-22 19:11:20,123 - uvicorn.error - INFO - Application shutdown complete.
2023-12-22 19:11:20,123 - uvicorn.error - INFO - Finished server process [21803]
2023-12-22 19:11:20,124 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc.telegram ...
2023-12-22 19:11:20,186 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2023-12-22 19:11:20,187 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-12-22 19:11:20,198 - telegram.ext.Application - INFO - Application.stop() complete
```

I have checked in the logs for a specific id to understand what is happening : `adeffab3-4542-4ecd-ae44-xxxxxxxxxxxx`

This id appear only one time on the 20 November:
```
2023-11-20 01:49:28,017 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair CVC/USDT:USDT (orderid:adeffab3-4542-4ecd-ae44-xxxxxxxxxxxx) in order to add another one ...
2023-11-20 01:49:28,017 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38)
2023-11-20 01:49:28,883 - freqtrade.exchange.exchange - INFO - stoploss market order added for CVC/USDT:USDT. stop price: 0.12089. limit: None
```
And the next time this id appears is after the restart yesterday:

```
2023-12-22 19:15:38,042 - freqtrade.exchange.common - WARNING - fetch_order() returned exception: "Order not found (pair: CVC/USDT:USDT id: adeffab3-4542-4ecd-ae44-xxxxxxxxxxxx). Message: Order adeffab3-4542-4ecd-ae44-039a888989f9 does not exist.". Retrying still for 5 times.

```

It seems line that when the bot tried to cancel the stoploss order the 20 November, the order in the database have not correctly updated , explaining why after rebooting he starts again to fetch it.

**Comment by xmatthias** [comment] 2023-12-23 14:31
Can you provide more logs for 2023-11-20 01:49:28,883 - freqtrade.exchange.exchange - INFO - stoploss market order added for CVC/USDT:USDT. stop price: 0.12089. limit: None?

search for `CVC/USDT:USDT` after that point in time - all (until that trade ACTUALLY closes) might be relevant.

As a side note - `2023.11-dev-8c2920eb1` is an interesting version...
the 2nd part is a commit - but 8c2920eb1 is not a known commit to this repository ...

**Comment by popperwin** [comment] 2023-12-23 20:04
Here are the logs from the opening to the close of this trade:
```
2023-11-20 01:46:37,922 - freqtrade.freqtradebot - INFO - Long signal found: about create a new trade for CVC/USDT:USDT with stake_amount: 324.1369571121 ...
2023-11-20 01:46:38,445 - freqtrade.freqtradebot - INFO - Order 55a93410-1092-4415-90bc-bf23c2903f4f was created for CVC/USDT:USDT and status is open.
2023-11-20 01:46:39,437 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 3, 'type': entry, 'buy_tag': 'enter_777', 'enter_tag': 'enter_777', 'exchange': 'Bybit', 'pair': 'CVC/USDT:USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.12514, 'open_rate': 0.12514, 'order_type': 'limit', 'stake_amount': 324.1369571121, 'stake_currency': 'USDT', 'base_currency': 'CVC', 'fiat_currency': 'USD', 'amount': 2590.1946389012305, 'open_date': datetime.datetime(2023, 11, 20, 0, 46, 38, 446256, tzinfo=datetime.timezone.utc), 'current_rate': 0.12514, 'sub_trade': False}
2023-11-20 01:46:40,937 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.19463890, is_short=False, leverage=1.0, open_rate=0.12514000, open_since=2023-11-20 00:46:38)
2023-11-20 01:46:40,956 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=3, pair=CVC/USDT:USDT, amount=2590.19463890, is_short=False, leverage=1.0, open_rate=0.12514000, open_since=2023-11-20 00:46:38) [buy]: 0.17824769 USDT - rate: 0.00055 
2023-11-20 01:46:40,956 - freqtrade.persistence.trade_model - INFO - LIMIT_BUY has been fulfilled for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38).
2023-11-20 01:46:42,068 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'trade_id': 3, 'type': entry_fill, 'buy_tag': 'enter_777', 'enter_tag': 'enter_777', 'exchange': 'Bybit', 'pair': 'CVC/USDT:USDT', 'leverage': 1.0, 'direction': 'Long', 'limit': 0.12513, 'open_rate': 0.12513, 'order_type': 'limit', 'stake_amount': 324.0867, 'stake_currency': 'USDT', 'base_currency': 'CVC', 'fiat_currency': 'USD', 'amount': 2590.0, 'open_date': datetime.datetime(2023, 11, 20, 0, 46, 38, 446256, tzinfo=datetime.timezone.utc), 'current_rate': 0.12514, 'sub_trade': False}
2023-11-20 01:46:43,998 - freqtrade.exchange.exchange - INFO - stoploss market order added for CVC/USDT:USDT. stop price: 0.11138. limit: None
2023-11-20 01:48:00,920 - freqtrade.persistence.trade_model - INFO - Found open trade: Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38)
2023-11-20 01:49:28,017 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair CVC/USDT:USDT (orderid:adeffab3-4542-4ecd-ae44-039a888989f9) in order to add another one ...
2023-11-20 01:49:28,017 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38)
2023-11-20 01:49:28,883 - freqtrade.exchange.exchange - INFO - stoploss market order added for CVC/USDT:USDT. stop price: 0.12089. limit: None
2023-11-20 09:01:33,474 - freqtrade.freqtradebot - INFO - Cancelling current stoploss on exchange for pair CVC/USDT:USDT (orderid:64e4b157-6c3b-4c66-a9c1-6b65fb1f87d4) in order to add another one ...
2023-11-20 09:01:33,474 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38)
2023-11-20 09:01:35,360 - freqtrade.exchange.exchange - INFO - stoploss market order added for CVC/USDT:USDT. stop price: 0.1209. limit: None
2023-11-20 14:24:08,447 - freqtrade.freqtradebot - INFO - Exit for CVC/USDT:USDT detected. Reason: custom_exit
2023-11-20 14:24:08,740 - freqtrade.freqtradebot - INFO - Canceling stoploss on exchange for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38)
2023-11-20 14:24:10,864 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit, 'trade_id': 3, 'exchange': 'Bybit', 'pair': 'CVC/USDT:USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.12933, 'order_rate': 0.12933, 'order_type': 'limit', 'amount': 2590.0, 'open_rate': 0.12513, 'close_rate': 0.12933, 'current_rate': 0.12933, 'profit_amount': 10.48321148, 'profit_ratio': 0.03232915, 'buy_tag': 'enter_777', 'enter_tag': 'enter_777', 'sell_reason': 'tp_exit', 'exit_reason': 'tp_exit', 'open_date': datetime.datetime(2023, 11, 20, 0, 46, 38, 446256, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2023, 11, 20, 13, 24, 10, 864615, tzinfo=datetime.timezone.utc), 'stake_amount': 324.0867, 'stake_currency': 'USDT', 'base_currency': 'CVC', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2023-11-20 14:24:13,384 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38)
2023-11-20 14:24:13,399 - freqtrade.freqtradebot - INFO - Fee for Trade Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38) [sell]: 0.15303919 USDT - rate: 0.00045678
2023-11-20 14:24:13,399 - freqtrade.persistence.trade_model - INFO - LIMIT_SELL has been fulfilled for Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=2023-11-20 00:46:38).
2023-11-20 14:24:13,401 - freqtrade.persistence.trade_model - INFO - Marking Trade(id=3, pair=CVC/USDT:USDT, amount=2590.00000000, is_short=False, leverage=1.0, open_rate=0.12513000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2023-11-20 14:24:13,743 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 3, 'exchange': 'Bybit', 'pair': 'CVC/USDT:USDT', 'leverage': 1.0, 'direction': 'Long', 'gain': 'profit', 'limit': 0.129359343, 'order_rate': 0.129359343, 'order_type': '', 'amount': 2590.0, 'open_rate': 0.12513, 'close_rate': 0.129359343, 'current_rate': None, 'profit_amount': 10.59040054, 'profit_ratio': 0.03265971, 'buy_tag': 'enter_777', 'enter_tag': 'enter_777', 'sell_reason': 'tp_exit', 'exit_reason': 'tp_exit', 'open_date': datetime.datetime(2023, 11, 20, 0, 46, 38, 446256, tzinfo=datetime.timezone.utc), 'close_date': datetime.datetime(2023, 11, 20, 13, 24, 10, 801000, tzinfo=datetime.timezone.utc), 'stake_amount': 324.0867, 'stake_currency': 'USDT', 'base_currency': 'CVC', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 10.59040054}2023-11-20 14:24:13,755 - cooldown_period - INFO - Cooldown for CVC/USDT:USDT for 12 candles. 
2023-11-20 14:24:13,762 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': protection_trigger, 'base_currency': 'CVC', 'id': 12, 'pair': 'CVC/USDT:USDT', 'lock_time': '2023-11-20 13:24:13', 'lock_timestamp': 1700486653750, 'lock_end_time': '2023-11-20 14:25:00', 'lock_end_timestamp': 1700490300000, 'reason': 'Cooldown period for 12 candles.', 'side': '*', 'active': True}

```

Very interesting part on the git version. I always update my freqtrade version by doing a git pull. 
I went from 2023.5 to 2023.11, and yesterday after the issue I went to 2023.12
I have done  some modifications in the source code, so whenever I pull I'm asked to commit and merge, explaining my very own commit id
Here are the current modifications between my version and the current develop branch. I don't see anything which can cause this issue:
 
```
git diff HEAD origin/develop
diff --git a/freqtrade/data/history/history_utils.py b/freqtrade/data/history/history_utils.py
index a9b170be6..1ad1060a4 100644
--- a/freqtrade/data/history/history_utils.py
+++ b/freqtrade/data/history/history_utils.py
@@ -21,14 +21,10 @@ from freqtrade.util import dt_ts, format_ms_time
 from freqtrade.util.binance_mig import migrate_binance_futures_data
 from freqtrade.util.datetime_helpers import dt_now
 
-from concurrent.futures import ThreadPoolExecutor,ProcessPoolExecutor
-from functools import partial
-
 
 logger = logging.getLogger(__name__)
 
 
-
 def load_pair_history(pair: str,
                       timeframe: str,
                       datadir: Path, *,
@@ -68,79 +64,6 @@ def load_pair_history(pair: str,
                                    )
 
 
-# def load_data(datadir: Path,
-#               timeframe: str,
-#               pairs: List[str], *,
-#               timerange: Optional[TimeRange] = None,
-#               fill_up_missing: bool = True,
-#               startup_candles: int = 0,
-#               fail_without_data: bool = False,
-#               data_format: str = 'json',
-#               candle_type: CandleType = CandleType.SPOT,
-#               user_futures_funding_rate: Optional[int] = None,
-#               ) -> Dict[str, DataFrame]:
-#     """
-#     Load ohlcv history data for a list of pairs.
-
-#     :param datadir: Path to the data storage location.
-#     :param timeframe: Timeframe (e.g. "5m")
-#     :param pairs: List of pairs to load
-#     :param timerange: Limit data to be loaded to this timerange
-#     :param fill_up_missing: Fill missing values with "No action"-candles
-#     :param startup_candles: Additional candles to load at the start of the period
-#     :param fail_without_data: Raise OperationalException if no data is found.
-#     :param data_format: Data format which should be used. Defaults to json
-#     :param candle_type: Any of the enum CandleType (must match trading mode!)
-#     :return: dict(<pair>:<Dataframe>)
-#     """
-#     result: Dict[str, DataFrame] = {}
-#     if startup_candles > 0 and timerange:
-#         logger.info(f'Using indicator startup period: {startup_candles} ...')
-
-#     data_handler = get_datahandler(datadir, data_format)
-
-#     for pair in pairs:
-#         hist = load_pair_history(pair=pair, timeframe=timeframe,
-#                                  datadir=datadir, timerange=timerange,
-#                                  fill_up_missing=fill_up_missing,
-#                                  startup_candles=startup_candles,
-#                                  data_handler=data_handler,
-#                                  candle_type=candle_type,
-#                                  )
-#         if not hist.empty:
-#             result[pair] = hist
-#         else:
-#             if candle_type is CandleType.FUNDING_RATE and user_futures_funding_rate is not None:
-#                 logger.warn(f"{pair} using user specified [{user_futures_funding_rate}]")
-#             elif candle_type not in (CandleType.SPOT, CandleType.FUTURES):
-#                 result[pair] = DataFrame(columns=["date", "open", "close", "high", "low", "volume"])
-
-#     if fail_without_data and not result:
-#         raise OperationalException("No data found. Terminating.")
-#     return result
-
-def _load_pair(pair: str, timeframe: str, datadir: Path, timerange: Optional[TimeRange],
-               fill_up_missing: bool, startup_candles: int, data_handler,
-               candle_type: CandleType, user_futures_funding_rate: Optional[int]) -> Tuple[str, Optional[DataFrame]]:
-
-
-    hist = load_pair_history(pair=pair, timeframe=timeframe,
-                             datadir=datadir, timerange=timerange,
-                             fill_up_missing=fill_up_missing,
-                             startup_candles=startup_candles,
-                             data_handler=data_handler,
-                             candle_type=candle_type,
-                             )
-    if not hist.empty:
-        return pair, hist
-    else:
-        if candle_type is CandleType.FUNDING_RATE and user_futures_funding_rate is not None:
-            logger.warn(f"{pair} using user specified [{user_futures_funding_rate}]")
-        elif candle_type not in (CandleType.SPOT, CandleType.FUTURES):
-            return pair, DataFrame(columns=["date", "open", "close", "high", "low", "volume"])
-    return pair, None
-
-
 def load_data(datadir: Path,
               timeframe: str,
               pairs: List[str], *,
@@ -151,8 +74,7 @@ def load_data(datadir: Path,
               data_format: str = 'feather',
               candle_type: CandleType = CandleType.SPOT,
               user_futures_funding_rate: Optional[int] = None,
-              ) -> Dict[str, DataFrame]:    
-    
+              ) -> Dict[str, DataFrame]:
     """
     Load ohlcv history data for a list of pairs.
 
@@ -167,31 +89,33 @@ def load_data(datadir: Path,
     :param candle_type: Any of the enum CandleType (must match trading mode!)
     :return: dict(<pair>:<Dataframe>)
     """
-    
-    
     result: Dict[str, DataFrame] = {}
     if startup_candles > 0 and timerange:
         logger.info(f'Using indicator startup period: {startup_candles} ...')
 
     data_handler = get_datahandler(datadir, data_format)
 
-    with ProcessPoolExecutor() as executor:
-        load_pair_func = partial(_load_pair, timeframe=timeframe, datadir=datadir, timerange=timerange,
-                                 fill_up_missing=fill_up_missing, startup_candles=startup_candles,
-                                 data_handler=data_handler, candle_type=candle_type,
-                                 user_futures_funding_rate=user_futures_funding_rate)
-        results = executor.map(load_pair_func, pairs)
-
-    for pair, hist in results:
-        if hist is not None:
+    for pair in pairs:
+        hist = load_pair_history(pair=pair, timeframe=timeframe,
+                                 datadir=datadir, timerange=timerange,
+                                 fill_up_missing=fill_up_missing,
+                                 startup_candles=startup_candles,
+                                 data_handler=data_handler,
+                                 candle_type=candle_type,
+                                 )
+        if not hist.empty:
             result[pair] = hist
+        else:
+            if candle_type is CandleType.FUNDING_RATE and user_futures_funding_rate is not None:
+                logger.warn(f"{pair} using user specified [{user_futures_funding_rate}]")
+            elif candle_type not in (CandleType.SPOT, CandleType.FUTURES):
+                result[pair] = DataFrame(columns=["date", "open", "close", "high", "low", "volume"])
 
     if fail_without_data and not result:
         raise OperationalException("No data found. Terminating.")
     return result
 
 
-
 def refresh_data(*, datadir: Path,
                  timeframe: str,
                  pairs: List[str],
diff --git a/freqtrade/data/history/idatahandler.py b/freqtrade/data/history/idatahandler.py
index 35b03e675..d8c063f2a 100644
--- a/freqtrade/data/history/idatahandler.py
+++ b/freqtrade/data/history/idatahandler.py
@@ -24,7 +24,6 @@ from freqtrade.exchange import timeframe_to_seconds
 
 logger = logging.getLogger(__name__)
 
-import traceback
 
 class IDataHandler(ABC):
 
@@ -444,4 +443,4 @@ def get_datahandler(datadir: Path, data_format: Optional[str] = None,
     if not data_handler:
         HandlerClass = get_datahandlerclass(data_format or 'feather')
         data_handler = HandlerClass(datadir)
-    return data_handler
\ No newline at end of file
+    return data_handler
diff --git a/freqtrade/exchange/exchange.py b/freqtrade/exchange/exchange.py
index d6800fb28..34d5e007b 100644
--- a/freqtrade/exchange/exchange.py
+++ b/freqtrade/exchange/exchange.py
@@ -44,7 +44,6 @@ from freqtrade.plugins.pairlist.pairlist_helpers import expand_pairlist
 from freqtrade.util import dt_from_ts, dt_now
 from freqtrade.util.datetime_helpers import dt_humanize, dt_ts
 
-from time import sleep
 
 logger = logging.getLogger(__name__)
 
@@ -1262,7 +1261,6 @@ class Exchange:
             order = self._order_contracts_to_amount(order)
             return order
         except ccxt.OrderNotFound as e:
-            sleep(10) #Bybit issue with order not found when market is crashing. Sleep to let time to cache. Don't know if it's a good pratice but let's test
             raise RetryableOrderError(
                 f'Order not found (pair: {pair} id: {order_id}). Message: {e}') from e
         except ccxt.InvalidOrder as e:
diff --git a/freqtrade/optimize/hyperopt.py b/freqtrade/optimize/hyperopt.py
index 22b1b17f5..5d5d15b03 100644
--- a/freqtrade/optimize/hyperopt.py
+++ b/freqtrade/optimize/hyperopt.py
@@ -107,7 +107,7 @@ class Hyperopt:
                                  'hyperopt_results' / 'hyperopt_tickerdata.pkl')
         self.total_epochs = config.get('epochs', 0)
 
-        self.current_best_loss = 1000000000
+        self.current_best_loss = 100
 
         self.clean_hyperopt()
```

**Comment by xmatthias** [comment] 2023-12-25 10:58
Well the logs are inconclusive, and don't contain any sign of why stop orders wouldn't be closed properly.

What you can try is run the bot with `log_responses=True` (in the exchange section of the configuration) to enable response logging - which might contain more signs.

obviously, that'll only work for new trades - based on the assumption that you have new trades with adjusting stoploss - where the canceled stoploss isn't properly canceled.

**Comment by xmatthias** [comment] 2024-01-05 10:39
I'll close this for now - please comment below should the problem reappear with the requested logs so we can reopen and actually look at this.

**Closed as completed by xmatthias** 2024-01-05 10:39 UTC
Labels: Stoploss, Triage Needed
