### ISSUE TITLE
Funding fees are not calculated correctly

### ISSUE THREAD

**Issue by liaogx** [freqtrade/freqtrade#7291] opened 2022-08-25 14:37 UTC
## Describe your environment

 * Operating system: MacOS Monterey 12.5.1
 * Python Version: 3.8.5
 * CCXT version: 1.92.20
 * Freqtrade Version: freqtrade 2022.8.dev

## Describe the problem:

Funding fees are calculated wrong.

### Steps to reproduce:

- set `"stake_amount": 1000, "dry_run_wallet": 10000, "tradable_balance_ratio": 0.99,` in the config file
- use x10 leverage in my futures trading strategy
- run `freqtrade backtesting -c config_initial.json --strategy DOT_SuperATR_10m --timerange 20220709-20220715`

The strategy timeframe is 5m, but bots trade in 10m by resampling data, also use 30m data as informative pairs. I just tested one DOT/USDT future trade and calculated funding fees manually.
  
```python
===================== SUMMARY METRICS =====================
| Metric                      | Value                     |
|-----------------------------+---------------------------|
| Backtesting from            | 2022-07-09 16:50:00       |
| Backtesting to              | 2022-07-14 23:50:00       |
| Max open trades             | 1                         |
|                             |                           |
| Total/Daily Avg Trades      | 1 / 0.2                   |
| Starting balance            | 10000 USDT                |
| Final balance               | 10695.649 USDT            |
| Absolute profit             | 695.649 USDT              |
| Total profit %              | 6.96%                     |
| CAGR %                      | 13455.65%                 |
| Profit factor               | 0.00                      |
| Trades per day              | 0.2                       |
| Avg. daily profit %         | 1.39%                     |
| Avg. stake amount           | 286.26 USDT               |
| Total trade volume          | 286.26 USDT               |
|
```

 - Let be simple, the above shows the `total profit %` is 6.96%

```python
      "trades": [
        {
          "pair": "DOT/USDT",
          "stake_amount": 286.26008,
          "amount": 400.7,
          "open_date": "2022-07-10 01:00:00+00:00",
          "close_date": "2022-07-14 15:50:00+00:00",
          "open_rate": 7.144,
          "close_rate": 6.536,
          "fee_open": 0.0004,
          "fee_close": 0.0004,
          "trade_duration": 6650,
          "profit_ratio": 0.6959647765953801,
          "profit_abs": 695.648601,
          "exit_reason": "long signal appears",
          "initial_stop_loss_abs": 7.43,
          "initial_stop_loss_ratio": -0.4,
          "stop_loss_abs": 6.602,
          "stop_loss_ratio": -0.1,
          "min_rate": 5.94,
          "max_rate": 7.182,
          "is_open": false,
          "enter_tag": "short: 2 candles breakout downwords",
          "is_short": true,
          "open_timestamp": 1657414800000,
          "close_timestamp": 1657813800000,
          "orders": [
            {
              "amount": 1399.7,
              "safe_price": 7.144,
              "ft_order_side": "sell",
              "order_filled_timestamp": 1657414800000,
              "ft_is_entry": true
            },
            {
              "amount": 69.9,
              "safe_price": 6.933,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657460400000,
              "ft_is_entry": false
            },
            {
              "amount": 199.4,
              "safe_price": 6.796,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657465200000,
              "ft_is_entry": false
            },
            {
              "amount": 56.5,
              "safe_price": 6.827,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657465800000,
              "ft_is_entry": false
            },
            {
              "amount": 268.4,
              "safe_price": 6.613,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657576200000,
              "ft_is_entry": false
            },
            {
              "amount": 281.9,
              "safe_price": 6.523,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657579800000,
              "ft_is_entry": false
            },
            {
              "amount": 52.3,
              "safe_price": 6.548,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657580400000,
              "ft_is_entry": false
            },
            {
              "amount": 70.6,
              "safe_price": 6.1,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657716000000,
              "ft_is_entry": false
            },
            {
              "amount": 400.7,
              "safe_price": 6.536,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657813800000,
              "ft_is_entry": false
            }
          ]
        }
      ],
```

The above are trades in backtesting json file:
- Total sell stake is `1399.7 * 7.144 = 9999.46`

- Total buy stake is `69.9 * 6.933 + 199.4 * 6.796 + 56.5 * 6.827 + 268.4 * 6.613 + 281.9 * 6.523 + 52.3 * 6.548 + 70.6 * 6.1 + 400.7 * 6.536 = 9231.32`

- Trading fees in the config file is `0.04%`, thus the total profit is: `sell_stake - buy_stake - (sell_stake + buy_stake) * fee_rate = 9999.46 - 9231.32 - (9999.46 + 9231.32) * 0.0004 = 760.99`

- The total profit ratio is `760.99 / 10000 = 7.61%`

So, which means `funding fees` of this trade is `760.99 - 695.65 = 65.34`, here is the issue, the below was DOT/USDT perpetual futures `funding fee rates` over this trade time:

- the trade timestamp start from `1657386000000` to `1657785000000` (UTC+ 00:00)

```python
  [
    1657411200001,-
    -0.00002517,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657440000002,
    -0.00018879,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657468800001,
    -0.00019416,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657497600000,
    -0.00024915,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657526400003,
    -0.00022317,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657555200001,
    -0.00025434,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657584000000,
    -0.00041353,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657612800021,
    -0.00004232,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657641600000,
    -0.0002823,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657670400012,
    -0.00017465,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657699200022,
    -0.00016759,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657728000005,
    -0.00037442,
    0.0,
    0.0,
    0.0,
    0.0
  ],
  [
    1657756800017,
    -0.00015528,
    0.0,
    0.0,
    0.0,
    0.0
  ],

```
All `funding fee rates` were negative over this short trade, for calculating the **max** `funding fees`, let's say bot didn't decrease position until it's closed, and use the open price for calculation, so I just calculated manually the `funding fees` is 27.45, not 65.34, there must be some calculation mistake when funding rates are applied to the trade object.

**Comment by liaogx** [comment] 2022-08-25 14:46
Another thing that confused me,  I manually changed `DOT_USDT-8h-funding_rate.json` for testing purpose, set all `funding rate` to `0` in the file.
 
 - trades in backtesting result json file when use original `DOT_USDT-8h-funding_rate.json`

```python
      "trades": [
        {
          "pair": "DOT/USDT",
          "stake_amount": 286.26008,
          "amount": 400.7,
          "open_date": "2022-07-10 01:00:00+00:00",
          "close_date": "2022-07-14 15:50:00+00:00",
          "open_rate": 7.144,
          "close_rate": 6.536,
          "fee_open": 0.0004,
          "fee_close": 0.0004,
          "trade_duration": 6650,
          "profit_ratio": 0.6959647765953801,
          "profit_abs": 695.648601,
          "exit_reason": "long signal appears",
          "initial_stop_loss_abs": 7.43,
          "initial_stop_loss_ratio": -0.4,
          "stop_loss_abs": 6.602,
          "stop_loss_ratio": -0.1,
          "min_rate": 5.94,
          "max_rate": 7.182,
          "is_open": false,
          "enter_tag": "short: 2 candles breakout downwords",
          "is_short": true,
          "open_timestamp": 1657414800000,
          "close_timestamp": 1657813800000,
          "orders": [
            {
              "amount": 1399.7,
              "safe_price": 7.144,
              "ft_order_side": "sell",
              "order_filled_timestamp": 1657414800000,
              "ft_is_entry": true
            },
            {
              "amount": 69.9,
              "safe_price": 6.933,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657460400000,
              "ft_is_entry": false
            },
            {
              "amount": 199.4,
              "safe_price": 6.796,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657465200000,
              "ft_is_entry": false
            },
            {
              "amount": 56.5,
              "safe_price": 6.827,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657465800000,
              "ft_is_entry": false
            },
            {
              "amount": 268.4,
              "safe_price": 6.613,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657576200000,
              "ft_is_entry": false
            },
            {
              "amount": 281.9,
              "safe_price": 6.523,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657579800000,
              "ft_is_entry": false
            },
            {
              "amount": 52.3,
              "safe_price": 6.548,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657580400000,
              "ft_is_entry": false
            },
            {
              "amount": 70.6,
              "safe_price": 6.1,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657716000000,
              "ft_is_entry": false
            },
            {
              "amount": 400.7,
              "safe_price": 6.536,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657813800000,
              "ft_is_entry": false
            }
          ]
        }
      ],

```

 - trades in backtesting result json file when all `funding rate` are changed to 0.
 ```python
      "trades": [
        {
          "pair": "DOT/USDT",
          "stake_amount": 286.26008,
          "amount": 400.7,
          "open_date": "2022-07-10 01:00:00+00:00",
          "close_date": "2022-07-14 15:50:00+00:00",
          "open_rate": 7.144,
          "close_rate": 6.536,
          "fee_open": 0.0004,
          "fee_close": 0.0004,
          "trade_duration": 6650,
          "profit_ratio": 0.760787012265032,
          "profit_abs": 760.44138804,
          "exit_reason": "long signal appears",
          "initial_stop_loss_abs": 7.43,
          "initial_stop_loss_ratio": -0.4,
          "stop_loss_abs": 6.602,
          "stop_loss_ratio": -0.1,
          "min_rate": 5.94,
          "max_rate": 7.182,
          "is_open": false,
          "enter_tag": "short: 2 candles breakout downwords",
          "is_short": true,
          "open_timestamp": 1657414800000,
          "close_timestamp": 1657813800000,
          "orders": [
            {
              "amount": 1399.7,
              "safe_price": 7.144,
              "ft_order_side": "sell",
              "order_filled_timestamp": 1657414800000,
              "ft_is_entry": true
            },
            {
              "amount": 69.9,
              "safe_price": 6.933,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657460400000,
              "ft_is_entry": false
            },
            {
              "amount": 199.4,
              "safe_price": 6.796,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657465200000,
              "ft_is_entry": false
            },
            {
              "amount": 56.5,
              "safe_price": 6.827,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657465800000,
              "ft_is_entry": false
            },
            {
              "amount": 268.4,
              "safe_price": 6.613,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657576200000,
              "ft_is_entry": false
            },
            {
              "amount": 281.9,
              "safe_price": 6.523,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657579800000,
              "ft_is_entry": false
            },
            {
              "amount": 52.3,
              "safe_price": 6.548,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657580400000,
              "ft_is_entry": false
            },
            {
              "amount": 70.6,
              "safe_price": 6.1,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657716000000,
              "ft_is_entry": false
            },
            {
              "amount": 400.7,
              "safe_price": 6.536,
              "ft_order_side": "buy",
              "order_filled_timestamp": 1657813800000,
              "ft_is_entry": false
            }
          ]
        }
      ],

```
Everything is exactly the same except two fields, `profit_ratio` and `profit_abs`, why?

**Comment by xmatthias** [comment] 2022-08-25 14:59
with negative funding fees - you'll pay for fees on a short - so it'll have to be subtracted from your profits (which it is).

> When the funding rate is positive, the price of the perpetual contract is higher than the mark price, thus, traders who are long pay for short positions. Conversely, a negative funding rate indicates that perpetual prices are below the mark price, which means that short positions pay for longs. 
[source](https://www.binance.com/en/blog/futures/a-beginners-guide-to-funding-rates-421499824684900382).

---

The data you have above is not sufficient though - you'll also need the mark price - as well as the amount at each moment of the trade to calculate this correctly. You then do the multiplication of `mark_price * amount * funding-rate` [source](https://www.binance.com/en/support/faq/360033525031) for the whole timerange the trade is open - (every 8 hours) - and need to aggregate this to get the resulting funding fee.

I'm not sure where else (other than profit fields) you'd expect this to show up - as it is mainly (or actually only) impacting your profit in the end.
backtesting does not export all fields a trade has internally - and neither should it - as that'd explode the filesize for no good reason.

**Comment by liaogx** [comment] 2022-08-25 15:14
Yeah, I know how to calculate funding fees, I just calculated it in a 'maximum way', if calculate precisely, "at each moment of the trade with mark price" as you said, then this trade funding fee will be absolutely less than 27.45, further away from 65.34(calculated from backtesting results). There must have some calculation mistakes!

And, I'm not saying expect more fields show up. I mean, why trades info in backtesting results are same whether `funding fee rates` are normal or 0? Only two fields, `profit_ratio` and `profit_abs` are different.

**Comment by xmatthias** [comment] 2022-08-25 18:26
> And, I'm not saying expect more fields show up. I mean, why trades info in backtesting results are same whether `funding fee rates` are normal or 0? Only two fields, `profit_ratio` and `profit_abs` are different.

I'd not know which other field should be different, as funding-fees won't impact trade size, nor open or close rates.

**Comment by xmatthias** [comment] 2022-08-27 06:39
One thing to be clear - if you expect this to be worked on further, i'll need a stable reproduction for this (basically where i can run backtesting and get the same results). 
I can make up most things - but not your strategy.

Trying with the strategy you shared last time - i get a trade duration of 3 days (10 total applications of funding fees) - and a funding fee of -13$ - which seems quite okish - and is a funding fee per period of ~1.8$ (depending on the actual fees, obviously).

**Comment by liaogx** [comment] 2022-08-27 07:11
> One thing to be clear - if you expect this to be worked on further, i'll need a stable reproduction for this (basically where i can run backtesting and get the same results). I can make up most things - but not your strategy.
> 
> Trying with the strategy you shared last time - i get a trade duration of 3 days (10 total applications of funding fees) - and a funding fee of -13$ - which seems quite okish - and is a funding fee per period of ~1.8$ (depending on the actual fees, obviously).

Yes, you've already reproduced that! $13 funding fee plus `trading_volume * 0.04%`(trading fee),  it's different from what calculated from backtesting trade results. **profit_abs = total_sell_stake - total_buy_stake - funding fee - trading fee**

**Comment by xmatthias** [comment] 2022-08-27 07:18
i'm not sure i understand what you mean

**Comment by liaogx** [comment] 2022-08-27 08:30
> i'm not sure i understand what you mean

In backtesting results json file, we've got orders list, one trade may have several orders(DCA or partial exit), each order have `amount` and `safe_price`, thus we can calculate the total entry stake and total exit stake, then minus trading fee and funding fee, which is `profit_abs`. It should be the same as what `SUMMARY METRICS` shows, right?

**Comment by xmatthias** [comment] 2022-08-27 08:33
this issue is becoming highly confusing - and i'm tempted to close it just to have you state the actual problem properly without switching to something else mid-discussion.

so what is this about?
* Calculation of funding fees (which is what the title and the whole discussion suggests)
* Calculation of profit_abs - and how it's displayed / used? (which is what you suggest in the last 2 comments)


> which is profit_abs. It should be the same as what SUMMARY METRICS shows, right?

Nothing above suggests otherwise - profit_abs is aligned to the profit shown in the summary metrics (where it's rounded).
No other comment (than the initial one) includes both metrics - so i don't see why this would be wrong.

**Comment by liaogx** [comment] 2022-08-28 08:45
Okay, since it's really hard to explain. I'll close this now. May you could check out the codes about funding fee calculation, I guess it's calculated twice or other miscalculation.

**Comment by xmatthias** [comment] 2022-08-28 09:21
If you think it's still wrong - there's no point in closing it (that won't make it correct).

By closing it - you're basically saying "I've been wrong - this is no longer necessary" - and i'll treat it as such.

If you expect actions to be taking (as you assume it's still incorrect) - then you should try to explain the problem in a way we understand it.
First - it was "funding fee calculation is wrong" - then "profit_abs is misaligned between trade and summary" .... which are two different problems altogether (and the latter one is clearly not the case).

Please understand that i'll not be investigating problems where the problem isn't clear - and where the issue has been closed.

**Comment by xmatthias** [comment] 2022-09-01 17:10
the 27.xx$ made it quite difficult to reason - however that assume fee is way higher than the real funding fee - which currently is applied once per exit order.

**Closed as completed** 2022-09-06 17:21 UTC
Labels: Bug, Non-spot
