### ISSUE TITLE
USD fiat value shows as zero

### ISSUE THREAD

**Issue by dompaks10** [freqtrade/freqtrade#6574] opened 2022-03-21 03:50 UTC
2022-03-21 03:48:39,031 - freqtrade.rpc.fiat_convert - WARNING - Found multiple mappings in goingekko for usdt.
2022-03-21 03:48:39,038 - freqtrade.rpc.fiat_convert - WARNING - unsupported crypto-symbol usdt - returning 0.0

The error just happened

**Comment by xmatthias** [comment] 2022-03-21 05:24
Please get used to fill out the issue template. Repeat offenders to this will have their issues closed without further comment.
We're asking some very basic questions - by deleting the issue template, you're explicitly choosing not to answer our questions - which makes me doubt why you think we should chose to answer your questions.


---

Duplicate of #6541 , #6519  and #6518.

It's fixed in develop - and will be fixed in the next release.

**Closed as completed by xmatthias** 2022-03-21 05:24 UTC
Labels: Duplicate
