### ISSUE TITLE
Freqtrade bot installation on Termux 

### ISSUE THREAD

**Issue by Nai-mul** [freqtrade/freqtrade#3232] opened 2020-04-29 07:20 UTC
A heartfelt thank you to the developer for giving us a gift (freqtrade bot). I was just amazed to see pictures of it and so far i haven’t used it. 
I tried to install it in Termux following the approach of Linux but failed everytime :(
Can Someone help me by uploading this installation video Youtube? Please...

**Comment by aak-dev** [comment] 2020-04-29 07:30
Check out the readme:
Minimal (advised) system requirements: 2GB RAM, 1GB disk space, 2vCPU

You wont have this on phone, so won't work.

**Comment by hroff-1902** [comment] 2020-04-29 07:45
although it's definitely not a platform which can be used to run the bot, I just wonder which errors do you have...

do you have python and pip installed in termux?

**Comment by aak-dev** [comment] 2020-04-29 07:53
yes git, python, pip are available and i did try running freqtrade on it but the build failed. Will send the log screenshot soon.

**Comment by hroff-1902** [comment] 2020-04-29 07:57
so you have installed it with no problems during installation?
then how did you do it, with easy install script?

**Comment by Nai-mul** [comment] 2020-04-29 08:06
Sir thanks for fast reply. My phone model was Redmi 5 plus, it’s has 3 GB RAM 32 GB memory and The phone runs on Snapdragon Octa core processor.
My Opinion was, If we can handle it over a android, It's can always be turned on without VPS. Besides uses of telegram more easyer then pc.
If we need 2 GB of RAM with 1 GB disk space to run it.  Well, we can manage new phone.  However, if you upload the installation process on YouTube we will be very benefited.

**Comment by aak-dev** [comment] 2020-04-29 08:15
termux have stable packages which can be easily installed.
@Nai-mul even though our phones have 8gb ram and huge storage space. The main os will use bulk of it and wont allow a single app to have it. And the ram of phone will never be same as a pc, phone rams are made for specific tasks so they wont be powerful enough.

**Comment by hroff-1902** [comment] 2020-04-29 08:20
no youtube movie since no one has tried it I guess

could YOU try it and then make a movie on youtube for this, if successful?
if not, what kind of errors do you have?

**Comment by Nai-mul** [comment] 2020-04-29 08:30
@aak-dev Thank you sir, I understand your thinking.  Still, don't be discouraged and keep an eye on the matter. Hopefully one day in the future we will see it running on the phone.

**Comment by Nai-mul** [comment] 2020-04-29 08:32
@hroff-1902, ok :)

**Comment by hroff-1902** [comment] 2020-04-29 08:35
> @aak-dev Thank you sir, I understand your thinking. Still, don't be discouraged and keep an eye on the matter. Hopefully one day in the future we will see it running on the phone.

do not think it's a good idea
but you (and someone else interested in it) can try to accomplish it

**Comment by hroff-1902** [comment] 2020-04-29 08:39
I'm closing it for now since there is no more to discuss here.

Feel free to post here (or in the new issues) particular problems you found, I do not see any reported above (just a general question we cannot answer more than it was done, so closing).

**Closed by hroff-1902** 2020-04-29 08:39 UTC
Labels: Question

**Comment by xmatthias** [comment] 2020-04-29 08:45
I would discourage you (and any future readers) from trying to run freqtrade on a phone.

Freqtrade relies on having a stable internet connection available - which is usually not the case with a phone you carry around.
Also, since it'll have to be constantly running, it'll result in a huge battery drain (if the phone is off, freqtrade can't get you out of a loosing (or winning) trade).

Simply put - Freqtrade is not intended to be used on a Phone, and i can think of only drawbacks over running it on a cheap, 5$/mo VPS. 

For that reason, we will not support installations (or installation attempts) made on phones. If you're sucessfull anyway - great - but if you encounter bugs, please try to reproduce them on a supported device first.

**Comment by Xakir-Hussain** [comment] 2024-11-11 03:30
I am successfully running freqtrade on termux. I used Xiaomi Pad 6. It runs smoothly over wifi. No battery drain issue. Battery lasts more than 3 days.

![Image](https://github.com/user-attachments/assets/7dcfb632-522a-4276-b21d-655e56e746a3)![Image](https://github.com/user-attachments/assets/634f8cc8-f7c4-4198-be7d-9519d485b631)
 #
