### ISSUE TITLE
Last candle disappeared

### ISSUE THREAD

**Issue by vforv** [freqtrade/freqtrade#9813] opened 2024-02-13 19:24 UTC
I've initiated a new issue following the unexpected deletion of my previous one. Below, you will find detailed information about the bug in question. I hope for a resolution; otherwise, I may need to explore alternative solutions for the trading bot.

Here is API call for BLZ (I got this after running freqtrade with -vvv option):

![Screenshot from 2024-02-13 20-05-11](https://github.com/freqtrade/freqtrade/assets/10942178/16219315-401e-4558-9a1c-2eb5d282993b)
![Screenshot from 2024-02-13 20-05-11](https://github.com/freqtrade/freqtrade/assets/10942178/6a98acab-ce77-48cc-955b-b9f3155330e1)

As you can see API returned this 2 last candles for BLZ:

![Screenshot from 2024-02-13 20-12-00](https://github.com/freqtrade/freqtrade/assets/10942178/5d13d212-6687-43b3-9b2a-4d2585482ad1)

Last close price is 0.32202 and previous is 0.32260

And here is how last candle inside freqtrade UI look like for BLZ:

![Screenshot from 2024-02-13 20-08-50](https://github.com/freqtrade/freqtrade/assets/10942178/3b39280c-1b8e-47bd-bccb-d2c75a84cc7c)

As illustrated, the close price is registered at 0.32260, corresponding to the previous candle at 18:45. However, there appears to be a discrepancy with the new candle, which has a close price of 0.32202 at 19:00. This is missing, despite being clearly retrieved from the API.

**This happen only if I use timeframes 5m, 15m or 30m. Everything work fine with 1h+ timeframes,**

**Comment by froggleston** [comment] 2024-02-13 20:45
The CCXT API most recent value will be indexed by the last *open* candle timestamp. Freqtrade stores *closed* candles *only*. There is no lag.

Secondly, please don't delete the issue template. We ask for the version information etc for a reason.

**Comment by vforv** [comment] 2024-02-13 20:46
That is the thing last closed candle is not stored.

**Comment by froggleston** [comment] 2024-02-13 20:48
Closed candles are indexed by their open timestamp, not their closed. You have all the data. Print out the main dataframe.

**Comment by vforv** [comment] 2024-02-13 20:54
I already tried multiple times it not finding last closed candle for 15m timeframe...

For example this: 
```
                         date    open   high     low  close    volume        adx        rsi      fastd  ...  bb_lowerband  bb_middleband  bb_upperband  bb_percent  bb_width       sar      tema    htsine  htleadsine
998 2024-02-13 20:30:00+00:00  3.0388  3.048  3.0354  3.036  357732.0  28.636251  72.430046  78.973892  ...      2.873419       2.970503      3.067588    0.837317  0.065366  3.002904  3.040445  0.395192   -0.370104
```

but candle needs to be with timestamp 2024-02-13 20:45:00 because now is 2024-02-13 20:55:00

It  work for 1h timeframe but not for 15m. There is no logic why it would find last closed candle for 1h but not for 15m...

I am using` freqtrade 2024.2-dev-9e89567ee` version

**Comment by perkmeister** [comment] 2024-02-13 21:36
If the time now is 20:55:00, the current candle is that which opened at 20:45:00, _and has not yet_closed_ . Since freqtrade only stores closed candles, the last candle to close would be the one that opened at 20:30:00, and freqtrade stores closed candles indexed by their open date so the date column says 20:30:00.

**Comment by vforv** [comment] 2024-02-13 21:47
The last closed candle is at 20:45:00  which is verifiable via API call if you call it at 20:55:00, since it is 15m timeframe each candle closes after 15m. So open from 20:30:00- closed at 20:45:00, then open from 20:45:00 and then closed at 21:00:00
And since last closed candle is at 20:45:00, it should be displayed on chart but not one closed at 20:30:00

**Comment by perkmeister** [comment] 2024-02-13 21:58
Freqtrade only stores closed candles, with a date of the open date for that candle. So you've just said that the candle that opened at 20:45:00 would close at 21:00:00, and the current time is 20:55:00. So the candle **isn't yet closed** and freqtrade would not have stored it. The last candle closed at 20:45:00 with an open date i.e. the date freqtrade stores for that candle of 20:30:00. The chart shows closed candles.

**Comment by vforv** [comment] 2024-02-13 22:08
I'm not referring to the candlestick that opened at 20:45 and closed at 21:00. My focus is on the candlestick that opened at 20:30 and closed at 20:45. It's perplexing why freqtrade would overlook this last closed candlestick when the exchange provides it. This oversight is baffling because such data is crucial for making accurate predictions.

**Comment by stash86** [comment] 2024-02-13 22:12
There is no lag. I have use this for 3 years. I'm not sure if there is a lag in frequi because I rarely use frequi, but for the bot itself, there is no lag.

**Comment by stash86** [comment] 2024-02-13 22:13
You can try to put log print inside your strategy to see the last candle that the bot really use

**Closed as completed by stash86** 2024-02-13 22:12 UTC
Labels: Wont fix / Not a bug

**Comment by vforv** [comment] 2024-02-13 22:15
I don't mean to offend, but it's essential to grasp the basics before diving into bot creation. I'll be stepping back from this discussion.

It's clear there's a misunderstanding regarding the concepts of open/close and timeframes. I hope in the future, once it becomes apparent where the confusion lies, you'll be able to address and rectify these issues.

**Comment by stash86** [comment] 2024-02-13 22:20
There is no confusion and misunderstanding. We know the concepts of open/close and timeframes. Instead of comparing the ccxt with frequi, please compare it with the actual value within the freqtrade bot.

**Comment by vforv** [comment] 2024-02-13 22:34
I also compared it with the values within the bot's populate_indicators function, and essentially, the bot does not utilize the latest candle for predictions. It's important to note that this observation applies specifically to the 5-minute, 15-minute, and 30-minute timeframes. For other timeframes, the bot does indeed consider the last candle in its calculations.

**Comment by xmatthias** [comment] 2024-02-14 06:08
> It's clear there's a misunderstanding regarding the concepts of open/close and timeframes. I hope in the future, once it becomes apparent where the confusion lies, ~you'll be able to address and rectify these issues~.

Yes, we hope that you'll understand the difference beween **open** and **closed** at some point.

an **open** candle (at 20:55, the 15m candle from 20:45 -> 21:00 is **open**) - while the candle from 20:30 is **closed** (it goes from 20:30 to 20:45).

If you query ccxt repeatedly between 20:46 and 20:59 and _carefully_ look at the last candle, you'll notice that it's timestamp will remain at 20:45 (the candle's open timestamp) - but the values change (at least on pairs with decent volume - best test with BTC/USDT).
As such - this candle is **open** (all values except it's open value will change over time - until that candle is actually closed.

Calculating indicators on such a candle will lead to repainting - indicators that change within the candle (as the values also change). In consequence, this will lead to ghost signals (signals that trigger a trade, but are gone once the candle closes -making it seem like a random entry without reason to enter (There's no signal anymore).

This leads to 2 problems - backtesting becomes quite inaccurate - as backtesting cannot simulate these ghost signals (we won't know the internals of a candle - at least not at the required level).
The 2nd problem is the users not understanding this as problem - as "they need uptodate info". 
Once you look at a chart however - you'll see "oh these indicators came close, but didn't cross - clearly not a _signal_ " That's based on closed candles. Within the candle, these indicators might very well have crossed for a few seconds (or even minutes) - which would've triggered a trade - as the candle would not have been closed.

As such - this is not a bug, but intended behavior.

---

For future issues - please use the issue template. Repeat offenders will have their issues closed without further warning or discussion.

Also - we don't need duplicate issues. 
The first issue was closed (correctly), with the explanation of what you're seeing. 
You can still _comment_ below that issue if you still have questions or concerns - there's no need to open a duplicate issue for the same question. The minimum this leads to is frustration (we need to explain the same thing again, the issue is drawn apart for no good reason for future readers). 
Thanks for your understanding.
