### ISSUE TITLE
Binance Futures Config Not working

### ISSUE THREAD

**Issue by Offensive-Cyber** [freqtrade/freqtrade#4109] opened 2020-12-23 09:24 UTC
## Describe your environment
  * Operating system: Ububtu 20
  * Python Version: 3.8 (`python -V`)
  * CCXT version: 1.38.13 (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.11 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*
###Backtest And Download Data not working with binance future config but working without futures config. It says """Pair BTC/USDT is not available on Binance. Please remove BTC/USDT from your whitelist."""###

### Observed Results:

  * What happened? Could'nt find a way to fix it.
  * What did you expect to happen? Download historical data & Backtest & Trade for binance futures

### Relevant code exceptions or logs

"stake_currency": "USDT",
.....
"ccxt_config": {"enableRateLimit": true, "options": {"defaultType": "future"}},
        "ccxt_async_config": {
            "enableRateLimit": true,
            "rateLimit": 200,
	    "options": {"defaultType": "future"}
        },
        "pair_whitelist": [
            "BTC/USDT"
        ],
.....

  // paste your log here

root@static:~/freqtrade# freqtrade download-data -c config.json --timeframe 1d --days 120
2020-12-23 12:49:59,852 - freqtrade.configuration.configuration - INFO - Using config: config.json ...
2020-12-23 12:49:59,852 - freqtrade.loggers - INFO - Verbosity set to 0
2020-12-23 12:49:59,853 - freqtrade.configuration.configuration - INFO - Using user-data directory: /root/freqtrade/user_data ...
2020-12-23 12:49:59,853 - freqtrade.configuration.configuration - INFO - Using data directory: /root/freqtrade/user_data/data/binance ...
2020-12-23 12:49:59,853 - freqtrade.configuration.configuration - INFO - timeframes --timeframes: ['1d']
2020-12-23 12:49:59,853 - freqtrade.configuration.configuration - INFO - Detected --days: 120
2020-12-23 12:49:59,853 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-12-23 12:49:59,853 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-12-23 12:49:59,853 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-12-23 12:49:59,853 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-12-23 12:49:59,856 - freqtrade.commands.data_commands - INFO - About to download pairs: ['BTC/USDT'], intervals: ['1d'] to /root/freqtrade/user_data/data/binance
2020-12-23 12:49:59,856 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-12-23 12:49:59,856 - freqtrade.exchange.exchange - INFO - Using CCXT 1.35.34
2020-12-23 12:49:59,856 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'options': {'defaultType': 'future'}}
2020-12-23 12:49:59,859 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'options': {'defaultType': 'future'}, 'rateLimit': 200}
2020-12-23 12:49:59,863 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-12-23 12:49:59,863 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-12-23 12:49:59,863 - freqtrade.exchange.exchange - INFO - Markets were not loaded. Loading them now..
2020-12-23 12:50:00,546 - freqtrade - ERROR - Pair BTC/USDT is not available on Binance. Please remove BTC/USDT from your whitelist.

**Comment by xmatthias** [comment] 2020-12-23 09:47
This is effectively a duplicate of #2312.

Neither futures nor Margin orders are currently supported by Freqtrade.

While you can use futures through ccxt by changing the default-type, this is NOT standardized by ccxt as of yet, therefore would require a custom logic for each exchange. 
This custom logic may then conflict with the unification ccxt is planning to do, so we would waste contributor's time.


Feel free to subscribe to the other issue (#2312) for progress on this topic (i assume futures and margin will most likely work at the same time).
If that's not the case, feel free to open a new issue once the other issue has been implemented. 
For now i don't see why we should keep 2 issues for almost the same topic, and i'm therefore closing this issue.

Thanks for your understanding.

**Closed by xmatthias** 2020-12-23 09:47 UTC
Labels: Duplicate, Question
