### ISSUE TITLE
Hyperopt of Strategies containing "Informative Pairs"

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3623] opened 2020-07-24 12:30 UTC
## Describe your environment
(if applicable)

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.4
  * CCXT version: ccxt==1.31.37
  * Freqtrade Version: freqtrade develop-3955fc61

## Describe the enhancement

I really Love this recently implemented feature -> https://www.freqtrade.io/en/latest/strategy-customization/#current_whitelist

It allows to design some very efficient strategies - as the next step it should be possible to "hyperopt" strategies containing this feature.

**Comment by xmatthias** [comment] 2020-07-24 13:42
This is a duplicate of #2608. 

There are multiple issues with this - simply adding dataprovider will break hyperopt completely - so please don't expect any movement anytime soon.

**Closed by xmatthias** 2020-07-24 13:42 UTC

**Comment by Prossi79** [comment] 2020-07-24 14:04
:) okay thank you! lets see
