### ISSUE TITLE
Different results with backtest/hyperopts

### ISSUE THREAD

**Issue by gitgitgat** [freqtrade/freqtrade#2036] opened 2019-07-18 18:48 UTC
hyperopts: python3 freqtrade -c config.json hyperopt --customhyperopt Test -i 1h -e 100 -s all--timerange 20190713 - 20190718
5 trade avg profit 3.02% 15.12% total

backtest: freqtrade -s hyperteststrategy -c config.json backtesting --timerange 201907 - 20190718
avg.profit 0.31% ı cum profit 0.31% ı tot profit 0.10%

**Comment by hroff-1902** [comment] 2019-07-18 19:02
what exchange and how many pairs are used?

**Comment by gitgitgat** [comment] 2019-07-18 19:26
binance, btc/usdt

**Comment by hroff-1902** [comment] 2019-07-19 20:42
The user was using old (June 12) version of freqtrade, that have not yet included #2009 fix yet.

Not a bug, closing it.

**Closed by hroff-1902** 2019-07-19 20:43 UTC
Labels: Triage Needed, backtest, hyperopt
