### ISSUE TITLE
Translation to persian

### ISSUE THREAD

**Issue by AlirezaM02** [freqtrade/freqtrade#5961] opened 2021-11-24 18:16 UTC
## For Iranian users

Due to many appeals from Iranians for a bot with such abilities, I've started to translate the bot UI and some other parts if possible to Persian language

**Comment by xmatthias** [comment] 2021-11-24 18:18
Duplicate of #5960. Please don't post the same message again and again, i've answered in your original issue already.

**Closed as completed by xmatthias** 2021-11-24 18:18 UTC
Labels: Duplicate
