### ISSUE TITLE
freqtrade.exchange.common - WARNING - _async_get_candle_history()

### ISSUE THREAD

**Issue by focamonca** [freqtrade/freqtrade#4575] opened 2021-03-19 14:09 UTC
* Operating system: Raspbian
  * Python Version:  Python 3.7.3
  * Freqtrade Version: develop-0d5833ed
  
## Describe the problem:

randomly getting

freqtrade.exchange.common - WARNING - _async_get_candle_history()

### Steps to reproduce:

  1. run the bot 
  2. 

### Relevant code exceptions or logs

  ```
2021-03-19 14:48:33,843 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:49:33,847 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:50:38,264 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:51:38,268 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:52:38,272 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:53:38,276 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:54:38,281 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'
2021-03-19 14:55:15,879 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair DREP/USDT due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/klines?symbol=DREPUSDT&interval=5m&limit=1000"
2021-03-19 14:55:15,879 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times
2021-03-19 14:55:16,181 - asyncio - ERROR - SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xac868d50>
transport: <_SelectorSocketTransport fd=19 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-03-19 14:55:17,880 - freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair WTC/USDT due to RequestTimeout. Message: binance GET https://api.binance.com/api/v3/klines?symbol=WTCUSDT&interval=5m&limit=1000"
2021-03-19 14:55:17,880 - freqtrade.exchange.common - WARNING - retrying _async_get_candle_history() still for 4 times
2021-03-19 14:55:18,027 - asyncio - ERROR - SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0xac868c70>
transport: <_SelectorSocketTransport fd=24 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
2021-03-19 14:55:40,620 - freqtrade.worker - INFO - Bot heartbeat. PID=17676, version='develop-0d5833ed', state='RUNNING'

  ```

**Comment by xmatthias** [comment] 2021-03-19 16:01
The error (`SSL error in data received`) suggests a problem with your connection / network, or with the exchange.

This can either be a SSL inspecting proxy (which disconnected you after discovering what you were up to) - or a very unstable / unreliable connection in general.
It can also be that the exchange either experienced problems / downtime.

You should also make sure that the rate-limits are in place while downloading data - otherwise the exchange may block you (although this usually looks very different).

Based on a search for the error (`ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify `) - (https://github.com/aio-libs/aiohttp/issues/3535) it could also be caused by a python bug in 3.7.

Either way, it's not something we'll be able to fix or handle at freqtrade level.

**Comment by xmatthias** [comment] 2021-03-25 08:50
Closing this as i think your question has been answered, and there is not much we can do for this case.

Feel free to comment below / reopen if you still encounter this in a reproducible manner

**Closed as completed by xmatthias** 2021-03-25 08:50 UTC
Labels: Question, Triage Needed
