### ISSUE TITLE
Backtesting Error (after update)

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#3363] opened 2020-05-23 11:30 UTC
## Step 2: Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.7.4
  * CCXT version: ccxt==1.27.91
  * Branch: Develop
  * Last Commit ID: b50d072d824339110e1957c804d3f47766ac9a2a

  
## Step 3: Describe the problem:

backtesting not working after update in Dev branch

### Steps to reproduce:

1. backtest done, okay
2. update on latest dev version
3. same CLI command as before, backtesting not working anymore

  
### Observed Results:

 see log below

### Relevant code exceptions or logs:

  ```
  freqtrade backtesting  --strategy-list ADXMomentum AdxSmas ASDTSRockwellTrading AverageStrategy AwesomeMacd BbandRsi BinHV27 BinHV45 CCIStrategy ClucMay72018 CMCWinner CofiBitStrategy CombinedBinHAndCluc EMASkipPump Low_BB MACDStrategy MACDStrategy_crossed MultiRSI Quickie ReinforcedQuickie ReinforcedSmoothScalp Scalp Simple SmoothScalp Ichimoku BbandRsi_AP4 Bblow_AP Bblow_AP1 --config config_pairs1.json  --timerange=20180801-20200515 --export trades --ticker-interval 1h
2020-05-23 13:10:49,365 - freqtrade.loggers - INFO - Verbosity set to 0
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Parameter -i/--ticker-interval detected ... Using ticker_interval: 1h ...
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20180801-20200515 ...
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/andreas/freqtrade/user_data ...
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Using data directory: /home/andreas/freqtrade/user_data/data/binance ...
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Using strategy list of 28 strategies
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Overriding ticker interval with Command line argument
2020-05-23 13:10:49,365 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2020-05-23 13:10:49,366 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-05-23 13:10:49,366 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-05-23 13:10:49,366 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-05-23 13:10:49,366 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-05-23 13:10:49,367 - freqtrade.commands.optimize_commands - INFO - Starting freqtrade in Backtesting mode
2020-05-23 13:10:49,367 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-05-23 13:10:49,367 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-05-23 13:10:49,369 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 5000}
2020-05-23 13:10:49,371 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-05-23 13:10:50,218 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-05-23 13:10:50,219 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist StaticPairList from '/home/andreas/freqtrade/freqtrade/pairlist/StaticPairList.py'...
2020-05-23 13:10:50,219 - freqtrade.resolvers.iresolver - INFO - Using resolved pairlist PrecisionFilter from '/home/andreas/freqtrade/freqtrade/pairlist/PrecisionFilter.py'...
2020-05-23 13:10:50,220 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/commands/optimize_commands.py", line 48, in start_backtesting
    backtesting = Backtesting(config)
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 67, in __init__
    self.pairlists = PairListManager(self.exchange, self.config)
  File "/home/andreas/freqtrade/freqtrade/pairlist/pairlistmanager.py", line 38, in __init__
    pairlist_pos=len(self._pairlist_handlers)
  File "/home/andreas/freqtrade/freqtrade/resolvers/pairlist_resolver.py", line 42, in load_pairlist
    'pairlist_pos': pairlist_pos},
  File "/home/andreas/freqtrade/freqtrade/resolvers/iresolver.py", line 136, in load_object
    kwargs=kwargs)
  File "/home/andreas/freqtrade/freqtrade/resolvers/iresolver.py", line 113, in _load_object
    return module(**kwargs)
  File "/home/andreas/freqtrade/freqtrade/pairlist/PrecisionFilter.py", line 20, in __init__
    self._stoploss = self._config['stoploss']
KeyError: 'stoploss'

  ```

**Comment by xmatthias** [comment] 2020-05-26 04:50
after looking at this a bit, i think we must restrict backtesting to StaticPairlist - at least if `--strategy-list` is used.

Otherwise, results will not be comparable / reproducible, as each strategy may result in a different pairlist, so you'd be comparing one strategy running on 20 pairs with another strategy running on 5 pairs.

Stoploss is just a symptom here ... 

I can solve it for single strategies easily - but i don't think there should be a solution for multiple strategies - in that case it's best to use `freqtrade test-pairlist` - and then use a staticpairlist instead.

**Comment by Prossi79** [comment] 2020-05-26 12:22
okay, I see the point you are making - but I dont understand how this happens. My understanding is the following:

1.) I got one config in which I use all filters (except volume) on top of my static pair-list
2.) result will be a dynamic pair-list on which all strategies in my list will be backtested

of course this is a snapshot, but all strategies in the list are backtested based on the same (dynamic pairlist), hence they are comparable, right?

or is FT creating a new pair list between each backtest? in this case results would of course be not comparable...

**Comment by xmatthias** [comment] 2020-05-26 13:36
The problem is that your configuration does not contain a stoploss (which is valid) - but is using the stoploss from the strategy - which may or may not be different between the strategies.

Now PrecisionFilter uses this stoploss value - as it's checking if you're allowed to create a stoploss below the entry price (so it needs to know this stoploss value).

The strategy-list logic does not write this stoploss value back to the global config (otherwise it would be set identical for all strategies), but keeps it in it's local config.

A quick fix is to disable PrecisionFilter automatically when it's not used (that's how it worked before) - but it'll only hide the problem, and it'll not be obvious that it was disabled, nor why.

**Comment by Prossi79** [comment] 2020-05-26 13:45
okay, got you - clear now ... means precision filter needs to be removed from the global config if working with the strategy list CLI command

merci!

**Comment by xmatthias** [comment] 2020-05-26 14:28
well that'll fix it short term for you - yes - but it won't fix the real problem 😆

**Comment by hroff-1902** [comment] 2020-05-26 15:23
I know this problem (stoploss is saved in the pairlist handler attribute and is not refreshed when a new strategy from the list is loaded) and I was looking at it while cleaning up/refactoring the pairlist handlers, but decided to leave it as it is to keep the current behavior... (but also maybe it's me who introduced it in one of the commits, need to compare with the previous master closer)

**Comment by xmatthias** [comment] 2020-05-26 17:19
yes you did - but because i asked you to ... i remember that line and almost exactly my comment ... 
but it's not relevant - the previous behaviour (disabling PrecisionFilter) was not better - this at least exposed this problematic behaviour.

**Comment by hroff-1902** [comment] 2020-05-26 18:52
It can be fixed easily -- simply do not fetch and save into the pairlist class attributes anything from configuration in the `__init__` method, instead, fetch values from configuration (stoploss, in this case) later in `gen_pairlist()` and in `filter_pairlist()`...

**Comment by xmatthias** [comment] 2020-05-27 05:25
not true - backtesting updates the pairlist before loading any strategy.

As mentioned above - to handle this the same way than when backtesting one strategy, we'd need to refresh the pairlist between every strategy - however that would defeat the purpose of `--strategy-list` - as it'll make the results non-comparable.

**Comment by acemi1** [comment] 2020-05-28 21:44
> The problem is that your configuration does not contain a stoploss (which is valid) - but is using the stoploss from the strategy - which may or may not be different between the strategies.
> 
> Now PrecisionFilter uses this stoploss value - as it's checking if you're allowed to create a stoploss below the entry price (so it needs to know this stoploss value).
> 
> The strategy-list logic does not write this stoploss value back to the global config (otherwise it would be set identical for all strategies), but keeps it in it's local config.
> 
> A quick fix is to disable PrecisionFilter automatically when it's not used (that's how it worked before) - but it'll only hide the problem, and it'll not be obvious that it was disabled, nor why.

I did not fully understand. Is it a problem caused by the person using this bot?

**Comment by xmatthias** [comment] 2020-05-29 04:02
it's a configuration problem - if you use StaticPairList for backtesting, then it'll work fine.

**Closed** 2020-06-29 18:53 UTC
Labels: Backtest, Bug

**Comment by r3nd4n** [comment] 2021-05-26 02:39
how about this error 

![image](https://user-images.githubusercontent.com/40991678/119594594-a743f380-be0e-11eb-8ff0-4c45126ead6a.png)
