### ISSUE TITLE
Freqtrade does not know that its sales order has been fulfilled.

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#3529] opened 2020-06-28 10:51 UTC
## Describe your environment

  * Operating system: ____Ubuntu 18.04.4 LTS
  * Python Version: _____ Python 3.6.9
  * CCXT version: _____ ccxt==1.29.5
  * Freqtrade Version: ____ freqtrade develop-79933060
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

Freqtrade does not know that its sales order has been fulfilled.
 
### Observed Results:

  * What happened?
While the price was falling, the stoplos worked. Other coins have been sold. However, freqtrade one does not know that its sales order has been fulfilled(TOMO/USDT). It continues to act as if it were in my wallet.

  * What did you expect to happen?
Freqtrade should follow whether his orders are still active,
If the order is not available, it can check whether the coin is sold or not.
As a result: I would expect it to make the necessary corrections automatically.

I did not interfere with freqtreade's sales process. (I did not manually sell in Binance) During this process I did not turn the freqtrade off and on.

![binance tomo](https://user-images.githubusercontent.com/39681665/85945187-c14a2d00-b944-11ea-82be-a457231c14a0.JPG)

---------------------------------------------------------------------------------------------------------------

![Tomo binance Sell](https://user-images.githubusercontent.com/39681665/85945188-c27b5a00-b944-11ea-9af9-fb99a0f6147c.JPG)

---------------------------------------------------------------------------------------------------------------
Telegram report of 26 June
![tomo Telegram](https://user-images.githubusercontent.com/39681665/85945190-c27b5a00-b944-11ea-80e2-eef4910b6905.JPG)

**Comment by acemi1** [comment] 2020-06-28 11:00
Completely different from what I wrote above;

If something couldn't fix it automatically, I should have received an error message over telegram.
For example: If I made manual sales via binance (I did not do this. I guess there is a problem that may be encountered in the future.)

**Comment by xmatthias** [comment] 2020-06-28 11:13
well we'll need the logs for the time-period from when this happened (so from the 24th, afternoon).

Only then we can determine what happened and what went wrong.

**Comment by acemi1** [comment] 2020-06-28 13:57
https://github.com/freqtrade/freqtrade/issues/3104#issuecomment-602886740  I tried to get a report based on this previous speech.

journalctl --since "2020-06-24 14:00:00" --until "2020-06-24 23:59:00"
When I run this command, I only see reports of ip addresses connecting to the server.
There are no reports of Freqtrade.
Where am I doing wrong?

Need a command that tells him to keep reports while running freqtrade?

https://www.freqtrade.io/en/latest/advanced-setup/#logging-to-journald
I don't understand what's written here

**Comment by acemi1** [comment] 2020-06-28 14:03
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 749, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market TOMO/USDT.Tried to sell amount 86.76 at rate 0.4455. Message: binance Account has insufficient balance for requested action.
2020-06-28 17:01:06,217 - freqtrade.freqtradebot - INFO - Executing Sell for TOMO/USDT. Reason: SellType.ROI
2020-06-28 17:01:06,729 - freqtrade.wallets - INFO - Wallets synced.
2020-06-28 17:01:06,730 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 86.76, Wallet: 0
2020-06-28 17:01:10,719 - freqtrade.freqtradebot - ERROR - Unable to place a stoploss order on exchange.
Traceback (most recent call last):
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 566, in fetch
    response.raise_for_status()
  File "/root/freqtrade/.env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v3/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 75, in stoploss
    amount=amount, price=rate, params=params)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1199, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 450, in inner
    return entry(_self, **inner_kwargs)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1930, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 469, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 578, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/binance.py", line 1911, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, self.id + ' ' + message)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/ccxt/base/exchange.py", line 487, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/freqtradebot.py", line 749, in create_stoploss_order
    order_types=self.strategy.order_types)
  File "/root/freqtrade/freqtrade/exchange/binance.py", line 83, in stoploss
    f'Message: {e}') from e
freqtrade.exceptions.DependencyException: Insufficient funds to create stop_loss_limit sell order on market TOMO/USDT.Tried to sell amount 86.76 at rate 0.4455. Message: binance Account has insufficient balance for requested action.
2020-06-28 17:01:11,218 - freqtrade.freqtradebot - INFO - Executing Sell for TOMO/USDT. Reason: SellType.ROI
2020-06-28 17:01:12,202 - freqtrade.wallets - INFO - Wallets synced.
2020-06-28 17:01:12,203 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Not enough amount to sell. Trade-amount: 86.76, Wallet: 0

**Comment by acemi1** [comment] 2020-06-28 14:10
This is another mistake,
It happens at the time of purchase.
This was the last day.

![vetusdt](https://user-images.githubusercontent.com/39681665/85949892-04ff5f80-b962-11ea-89e7-11bef102e9bb.JPG)

**Comment by xmatthias** [comment] 2020-06-28 14:18
The logs unfortunately just show the effect - not the cause (which is at the top of the errors - before the first problem happens).

And yes - if it's a new problem, please a new issue (including the log of the problem - + a few lines before the problem (this will tell us what caused the exception - and is often more interresting than the exception itself).

**Comment by acemi1** [comment] 2020-06-29 08:08
https://github.com/freqtrade/freqtrade/issues/3529#issuecomment-650763629  Is the journalctl statement I wrote here correct?
Some of the report I received is in the attached txt file. Nothing useful in the report. I doubt I did it right.


https://github.com/freqtrade/freqtrade/issues/3529#issuecomment-650764582  Here I see that fraqtrade is aware that there is a problem but cannot solve it.

[log.txt](https://github.com/freqtrade/freqtrade/files/4844498/log.txt)

**Comment by xmatthias** [comment] 2020-06-29 12:27
No, Freqtrade just knows it doesn't have enough balance in the account to create a new order. How to handle this it does not know (most likely, there is an order on the exchange blocking the balance).

the interresting part is WHY this is the case - which is not in the logs you posted.

Your logs just show sshd logs - are you logging to journald? (unless you're running freqtrade as a service, this has to be enabled specifically).
You might try to filter by unit `journalctl -u freqtrade.service` - this should give you the right logs ...

**Comment by acemi1** [comment] 2020-06-29 13:43
https://www.freqtrade.io/en/latest/advanced-setup/#logging-to-journald
I have not tried to do what has been written here to this day.
I don't know Systemd and Logging to journald

**Comment by xmatthias** [comment] 2020-06-29 13:51
How do you run the bot, then? in a terminal? via docker? ... ?

**Comment by acemi1** [comment] 2020-06-29 14:28
On the VPS server, using the Screen command in Terminal.

**Comment by xmatthias** [comment] 2020-06-29 14:34
unless you're specifying `--log-file <somefile>`, then the logs will only be available as long as you're able to "scroll up" in screen (this should be possible via some key combination).

I doubt it'll go back several days though ...

**Comment by acemi1** [comment] 2020-06-29 16:13
Since the bot reports an error about TOMO / USDT all the time, I can't even see the articles from 10 minutes ago.

In order for novices like me to encounter the same problem after this date; Is it possible to create the log file by default?

Just like for dry run and live bots by default, separate database file is used. (tradesv3.sqlite and tradesv3.dryrun.sqlite)

**Comment by xmatthias** [comment] 2020-06-29 17:52
I've been thinking about this too - but that would collide with the options of allowing journald / systemd logging.

To be fair - i do think that this issue is a duplicate of #3499 (and a few others) ... should hopefully be fixed soon.

**Closed** 2020-06-29 18:08 UTC
Labels: Triage Needed
