### ISSUE TITLE
Proposed way to keep the RSI symmetric

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7345] opened 2022-09-04 20:28 UTC
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: Python 3.10.6
  * CCXT version: ccxt==1.92.84
  * Freqtrade Version:  freqtrade docker-b53791fe

  
## Your question

Is there a proposed way to keep the RSI for instance symmetric.

enter_long = IntParameter(5, 45, default=30, space="buy")
print(f"typ von enter_long: {(enter_long.__dict__)}")
enter_short = 100 - enter_long

Does not work obviously. What is a way to achieve it?

**Comment by xmatthias** [comment] 2022-09-05 04:37
This is also to some extend a duplicate of #7189.

Having constraints is currently not possible due to scikit-optimize.
best follow https://github.com/scikit-optimize/scikit-optimize/pull/971 for information on this - we'll not be taking action on implementing or supporting this until the upstream dependency is merged. 

---

That said - your specific constraint may be possible by using the value of the object itself where you use it

so it'd become something around the below (details are left to you to properly implement, this is to give you an idea on how this can be approached).

``` python

enter_long = IntParameter(5, 45, default=30, space="buy")

def populate_enter_trend():
    dataframe.loc[
        qtpylib.crossed_above(dataframe['rsi'], enter_long.value)
     , 'enter_long'] = 1
    dataframe.loc[
        qtpylib.crossed_above(dataframe['rsi'],  100 - enter_long.value)
     , 'enter_short'] = 1

```

It'll only be 1 parameter which will always have the same value for long and short (i personally doubt you can reverse conditions like this for an effective short strategy - but that's a personal opinion) - but it'll keep your value symetric.

**Closed as completed** 2022-09-08 18:04 UTC
Labels: Question, Hyperopt

**Comment by HeinrichHaller** [comment] 2022-09-12 17:45
Thanks for the answer.
In regard of your opinion and that example specific, in my experience that asymmetric approach is quite prone to over-fitting. Usually, to model a time series, like here a cryptocurrency, some kind of geometric Brownian motion is used, without a major trend. A trend would be needed to justify an asymmetric approach.
