### ISSUE TITLE
Pandas warning while backtesting

### ISSUE THREAD

**Issue by jblestang** [freqtrade/freqtrade#3644] opened 2020-07-29 10:08 UTC
## Describe your environment

  * Operating system: Ubuntu 18.04
  * Python Version: 3.6
  * CCXT version: 1.30.48
  * Freqtrade Version: develop-d9d999ea

## Describe the problem:

*from time to time I get a warning while backtesting

### Steps to reproduce:

  1. Run backtesting
  
### Observed Results:

* An error while backtesting implying we try to
Modify the dataframe when we shall be only reading from the dataframe. 
* My dataframe contains data from a 4h ticker and merged data from daily and weekly timeframe (using the dataprovider)

### Relevant code exceptions or logs
```
2020-07-29 10:42:20,200 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
    backtesting.start()
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 416, in start
    position_stacking=position_stacking,
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 311, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 161, in _get_ohlcv_as_lists
    pair_data.loc[:, 'buy'] = 0  # cleanup from previous run
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexing.py", line 671, in _setitem_
    self._setitem_with_indexer(indexer, value)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexing.py", line 845, in _setitem_with_indexer
    self.obj[key] = _infer_fill_value(value)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2938, in _setitem_
    self._set_item(key, value)
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 3007, in _set_item
    self._check_setitem_copy()
  File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/generic.py", line 3729, in _check_setitem_copy
    raise com.SettingWithCopyError(t)
pandas.core.common.SettingWithCopyError:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```

The error can be made fatal in order to raise the exception and get the backtrack using the following setup option in Pandas

```
pd.options.mode.chained_assignment = 'raise'
```

**Comment by xmatthias** [comment] 2020-07-29 11:44
well - it's a warning on default settings, as long as you don't touch these - it'll remain a warning.

You'll also notice that you're not going to get this with each run - but only "sometimes" (in my opinion based on the strategy ... ) 

If you look into this deep enough (search pandas issues), you'll discover that pandas has a history of false positives with this error - and the common answer from folks at pandas for this is "it's a warning - best ignore".

Also - since this is very much tied to pandas, what's the pandas version you're getting this with?

I've just tried to recreate this with python 3.8, the latest pandas (pandas 1.0.5) using the SampleStrategy, but i don't get the warning - nor does it raise if i change the mode.


This leaves 2 options - it's related to the pandas / python version (you're on 3.6, i'm on 3.8)  - and/or it's related to how your strategy handles the dataframe.

If you can recreate this with the SampleStrategy - we can mabye have a look (although i'm not sure what we should fix ...) - but otherwise i would not know what there is to fix - as the problem is created / caused by the strategy.

**Comment by quantsirius** [comment] 2021-03-07 14:55
Hi. I get it right now with SampleStrategy only when not specify the end date for timerange:
"--timerange 20210124-"

Python 3.8.5
pip 21.0.1
pandas 1.2.2
freqtrade 2021.2

**Comment by mablue** [comment] 2021-04-02 19:44
> ## Describe your environment
> 
>     * Operating system: Ubuntu 18.04
> 
>     * Python Version: 3.6
> 
>     * CCXT version: 1.30.48
> 
>     * Freqtrade Version: develop-d9d999ea
> 
> 
> ## Describe the problem:
> 
> *from time to time I get a warning while backtesting
> ### Steps to reproduce:
> 
>     1. Run backtesting
> 
> 
> ### Observed Results:
> 
>     * An error while backtesting implying we try to
>       Modify the dataframe when we shall be only reading from the dataframe.
> 
>     * My dataframe contains data from a 4h ticker and merged data from daily and weekly timeframe (using the dataprovider)
> 
> 
> ### Relevant code exceptions or logs
> 
> ```
> 2020-07-29 10:42:20,200 - freqtrade - ERROR - Fatal exception!
> Traceback (most recent call last):
>   File "/root/freqtrade/freqtrade/main.py", line 36, in main
>     return_code = args['func'](args)
>   File "/root/freqtrade/freqtrade/commands/optimize_commands.py", line 49, in start_backtesting
>     backtesting.start()
>   File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 416, in start
>     position_stacking=position_stacking,
>   File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 311, in backtest
>     data: Dict = self._get_ohlcv_as_lists(processed)
>   File "/root/freqtrade/freqtrade/optimize/backtesting.py", line 161, in _get_ohlcv_as_lists
>     pair_data.loc[:, 'buy'] = 0  # cleanup from previous run
>   File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexing.py", line 671, in _setitem_
>     self._setitem_with_indexer(indexer, value)
>   File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/indexing.py", line 845, in _setitem_with_indexer
>     self.obj[key] = _infer_fill_value(value)
>   File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 2938, in _setitem_
>     self._set_item(key, value)
>   File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/frame.py", line 3007, in _set_item
>     self._check_setitem_copy()
>   File "/root/freqtrade/.env/lib/python3.6/site-packages/pandas/core/generic.py", line 3729, in _check_setitem_copy
>     raise com.SettingWithCopyError(t)
> pandas.core.common.SettingWithCopyError:
> A value is trying to be set on a copy of a slice from a DataFrame.
> Try using .loc[row_indexer,col_indexer] = value instead
> ```
> 
> The error can be made fatal in order to raise the exception and get the backtrack using the following setup option in Pandas
> 
> ```
> pd.options.mode.chained_assignment = 'raise'
> ```

I updated my kernel of linux and problem fixed!! :|
[https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/amd64/](https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/current/amd64/)

download all files and use this command to update and reboot:
`sudo dpkg -i *`

**Comment by synackSA** [comment] 2021-04-19 21:02
I'm getting this too. I'm running mine via the docker image:
```
docker-compose run --rm freqtrade backtesting -i 15m --data-format-ohlcv json --strategy-list TwoVWAPStrategy --export=trades
```

Stack Trace:
```
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 53, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 482, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 453, in backtest_one_strategy
    results = self.backtest(
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 354, in backtest
    data: Dict = self._get_ohlcv_as_lists(processed)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 192, in _get_ohlcv_as_lists
    pair_data.loc[:, 'buy'] = 0  # cleanup from previous run
  File "/root/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 692, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/root/.local/lib/python3.9/site-packages/pandas/core/indexing.py", line 1597, in _setitem_with_indexer
    self.obj[key] = value
  File "/root/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "/root/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3249, in _set_item
    self._check_setitem_copy()
  File "/root/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3936, in _check_setitem_copy
    raise com.SettingWithCopyError(t)
pandas.core.common.SettingWithCopyError:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
```

My Strategy File (It's still WIP, don't judge me):

```python
# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# isort: skip_file
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame, Series

from freqtrade.strategy.interface import IStrategy

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import pandas_ta as pta
import freqtrade.vendor.qtpylib.indicators as qtpylib
import logging
import warnings

pd.options.mode.chained_assignment = 'raise'

class TwoVWAPStrategy(IStrategy):
    """
    This is a sample strategy to inspire you.
    More information in https://www.freqtrade.io/en/latest/strategy-customization/

    You can:
        :return: a Dataframe with all mandatory indicators for the strategies
    - Rename the class name (Do not forget to update class_name)
    - Add any methods you want to build your strategy
    - Add any lib you need to build your strategy

    You must keep:
    - the lib in the section "Do not remove these libs"
    - the prototype for the methods: minimal_roi, stoploss, populate_indicators, populate_buy_trend,
    populate_sell_trend, hyperopt_space, buy_strategy_generator
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    # Check the documentation or the Sample strategy to get the latest version.
    INTERFACE_VERSION = 2

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi".
    minimal_roi = {
        "60": 0.01,
        "30": 0.02,
        "0": 0.04
    }

    # Optimal stoploss designed for the strategy.
    # This attribute will be overridden if the config file contains "stoploss".
    stoploss = -0.10

    # Trailing stoploss
    trailing_stop = False
    # trailing_only_offset_is_reached = False
    # trailing_stop_positive = 0.01
    # trailing_stop_positive_offset = 0.0  # Disabled / not configured

    # Optimal ticker interval for the strategy.
    timeframe = '15m'

    # Run "populate_indicators()" only for new candle.
    process_only_new_candles = False

    # These values can be overridden in the "ask_strategy" section in the config.
    use_sell_signal = True
    sell_profit_only = False
    ignore_roi_if_buy_signal = False

    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = 30

    # Optional order type mapping.
    order_types = {
        'buy': 'limit',
        'sell': 'limit',
        'stoploss': 'market',
        'stoploss_on_exchange': False
    }

    # Optional order time in force.
    order_time_in_force = {
        'buy': 'gtc',
        'sell': 'gtc'
    }

    plot_config = {
        'main_plot': {
            'D_VWAP': {'color': 'DeepSkyBlue'},
            'W_VWAP': {'color': 'Yellow'},
        },
        'subplots': {
            "SRSI": {
                'SRSI_K': {'color': 'DarkTurquoise'},
                'SRSI_D': {'color': 'DarkOrange'}
            },
            "RSI": {
                'RSI': {'color': 'DarkViolet'},
            },
            "ATR": {
                'ATR': {'color': 'OrangeRed'}
            }
        }
    }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds several different TA indicators to the given DataFrame

        Performance Note: For the best performance be frugal on the number of indicators
        you are using. Let uncomment only the indicator you are using in your strategies
        or your hyperopt configuration, otherwise you will waste your memory and CPU usage.
        :param dataframe: Dataframe with data from the exchange
        :param metadata: Additional information, like the currently traded pair
        :return: a Dataframe with all mandatory indicators for the strategies
        """

        srsi = pta.stochrsi(dataframe["close"], length=14, rsi_length=14, k=3, d=3)

        dataframe = dataframe.assign(D_VWAP=self.vwap(dataframe=dataframe, anchor="D"))
        dataframe = dataframe.assign(W_VWAP=self.vwap(dataframe=dataframe, anchor="W"))
        dataframe = dataframe.assign(ATR=pta.atr(high=dataframe["high"], low=dataframe["low"], close=dataframe["close"], length=14))
        dataframe = dataframe.assign(RSI=pta.rsi(close=dataframe["close"], length=14))
        dataframe = dataframe.assign(SRSI_K=srsi["STOCHRSIk_14_14_3_3"])
        dataframe = dataframe.assign(SRSI_D=srsi["STOCHRSId_14_14_3_3"])

        # logger.info(dataframe)
        
        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the buy signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """

        # logger.info("\n{}".format(qtpylib.crossed_above(dataframe['SRSI_K'], dataframe['SRSI_D'])))

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['SRSI_K'], dataframe['SRSI_D'])) &  # We have a SRSI Cross up
                (dataframe['D_VWAP'] > dataframe['W_VWAP']) &  # Short term VWAP is above teh long term VWAP
                (dataframe['close'] > dataframe['D_VWAP']) &  # Close is above the short term VWAP
                (dataframe['RSI'] < 60) &  # We aren't already too far in an up trend
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'buy'] = 1

        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the sell signal for the given dataframe
        :param dataframe: DataFrame populated with indicators
        :param metadata: Additional information, like the currently traded pair
        :return: DataFrame with buy column
        """
        
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['SRSI_D'], dataframe['SRSI_K'])) &  # We have a SRSI Cross down
                (dataframe['D_VWAP'] < dataframe['W_VWAP']) &  # Short term VWAP is below the long term VWAP
                (dataframe['close'] < dataframe['D_VWAP']) &  # Close is below the short term VWAP
                (dataframe['RSI'] < 30) &  # We aren't already too far in an down trend
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'sell'] = 1
            
        return dataframe


    def vwap(self, dataframe: DataFrame, anchor: str, offset: int=0) -> Series:
        """
        Indicator: Volume Weighted Average Price (VWAP)
        Based on TA Pandas VWAP function: https://github.com/twopirllc/pandas-ta/blob/master/pandas_ta/overlap/vwap.py
        Their function assumes an index that is a Datetime Index. 

        Args:
            dataframe: DataFrame [[date, open, high, low, close, volume]]
            anchor (str): How to anchor VWAP. Depending on the index values, it will
                implement various Timeseries Offset Aliases as listed here:
                https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#timeseries-offset-aliases
                Default: "D".
            offset (int): How many periods to offset the result. Default: 0
        Returns:
            pd.Series: New feature generated.        
        """

        # Setup
        df = dataframe.copy()
        df = df.assign(period_date=pd.to_datetime(df["date"]))

        # Validate Arguments
        anchor = anchor.upper() if anchor and isinstance(anchor, str) and len(anchor) >= 1 else "D"
        offset = self.get_offset(offset)
        name = f"VWAP_{anchor}"

        # Get Typical Price
        df = df.assign(typical_price=self.hlc3(dataframe=df))

        # data.tz_localize(None).to_period(freq=freq)

        # Calculate Result
        df = df.assign(wp=df["typical_price"] * df["volume"])

        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=UserWarning)
            vwap = df["wp"].groupby(df["period_date"].dt.to_period(anchor)).cumsum()
            vwap /= df["volume"].groupby(df["period_date"].dt.to_period(anchor)).cumsum()

        # Offset
        if offset != 0:
            vwap = vwap.shift(offset)

        return vwap

    def hlc3(self, dataframe: DataFrame, offset: int=None, **kwargs) -> Series:
        """Indicator: HLC3"""

        # Validate Arguments
        offset = self.get_offset(offset)

        # Calculate Result
        hlc3 = (dataframe["high"] + dataframe["low"] + dataframe["close"]) / 3.0

        # Offset
        if offset != 0:
            hlc3 = hlc3.shift(offset)

        # Name & Category
        hlc3.name = "HLC3"

        return hlc3

    def get_offset(self, x: int) -> int:
        """Returns an int, otherwise defaults to zero."""
        return int(x) if isinstance(x, int) else 0
```

Wouldn't we be better off changing:
```
pair_data.loc[:, 'buy'] = 0
```
to
```
pair_data = pair_data.assign(buy=0)
```

**Comment by xmatthias** [comment] 2021-04-20 04:12
I would not see why ...
the exception explicitly states that using `Try using .loc[row_indexer,col_indexer] = value instead` would be the correct way.

Assign is that it returns a new object.
As backtesting potentially deals with big dataframes, this can become problematic from a memory perspective, and if you got large (wide) dataframes, you'll see performance impacts too.

> Returns a new object with all original columns in addition to new ones. Existing columns that are re-assigned will be overwritten.

[source](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html)


You can also confirm that this does not cause the copy.
Raise is insofar pointless as it's showing you where the warning appears - not what causes the copy of the dataframe (which would be the cause).
using `.loc[]` is however not causing copies - and is the correct way to assign values to a dataframe without creating a new one.

```
print(dataframe._is_copy)
dataframe.loc[:, 'buy'] = 0
print(dataframe._is_copy)
```

**Comment by xmatthias** [comment] 2021-09-28 17:44
I'm going to close this now - as i'm unable to recreate this issue with any of the above methods - so i assume one of the (many) changes will have implicitly fixed this.

**Closed by xmatthias** 2021-09-28 17:44 UTC
Labels: Backtest, Triage Needed
