### ISSUE TITLE
Telegram message and buy signal

### ISSUE THREAD

**Issue by Fimap9to1** [freqtrade/freqtrade#7103] opened 2022-07-18 14:12 UTC
Operating system: Linus 20.04 LTS
    Python Version: Python 3.8.5
    CCXT version: ccxt==1.81.16
    Freqtrade Version: freqtrade develop-65ab6d246

  
Dear Matthias, I've met up with a rare behaviour. As far asa I know an entry signal occurs on one candle and the entry actually occurs on the next one.

So I don't get why, the bot gets the message on telegram in a mixed way. Sometimes it sends the message on the entry signal, sometimes on the actual entry.

Here an example were the bot buys at 12:25 but the message on telegram arrives at 12:20 on the entry signal:

![1](https://user-images.githubusercontent.com/74922424/179530196-e2bea443-2d91-46f8-b4dc-44c26215696f.png)

Here an example were the bot buys at 12:25 but the message arrives at 12:25 on the actual entry:

![12](https://user-images.githubusercontent.com/74922424/179530519-1ab1e341-0c96-4d76-aaa0-49e24cde0e58.png)

Is this normal or there's an issue? The bot was running live dry-run and the plots are from the backtest of the same period.

**Comment by xmatthias** [comment] 2022-07-18 17:41
well honestly - there's nothing showing when the messages were sent. 
you should also not refer to telegram for this - but to the log.

without the log - it's just a tale someone told (unconfirmed) - which can be caused by many things - most likely by out of sync clocks.

**Comment by Fimap9to1** [comment] 2022-07-18 19:23
If they are out of sync clocks, why sometimes is punctual and sometimes is not?
If it were always late I could agree, but is not the case.

**Comment by xmatthias** [comment] 2022-07-19 05:24
Please understand that i'll not investigate / look at this any further without any (corresponding) logs.

Without that, it's guessing / fishing in the dark based on a tale - which i am not going to do.

**Comment by Fimap9to1** [comment] 2022-07-19 07:09
Don't worry I completely understand. If I get the logs in the right moment I will send them here. Thankyou anyway.

**Comment by xmatthias** [comment] 2022-07-31 06:45
If you get the logs, feel free to reopen / comment below.

For now - this is nothing we can act on - therefore closing.

**Closed as completed by xmatthias** 2022-07-31 06:45 UTC
Labels: Question
