### ISSUE TITLE
Captcha verification on kraken.com

### ISSUE THREAD

**Issue by pittybitty** [freqtrade/freqtrade#3204] opened 2020-04-23 16:05 UTC
I have used freqtrade successfully on kraken.com for a while but now it is not possible to start freqtrade because kraken wants to verify a CAPTCHA. Freqtrade shows a lot of HTML code but stops working because the CAPTCHA was not solved. Is there any possibility to start kraken with an active CAPTCHA verification or is freqtrade now unusable on kraken.com?

Here is the output with the relevant parts:

`2020-04-23 17:46:27,001 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-04-23 17:46:27,005 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'rateLimit': 1000}
2020-04-23 17:46:27,009 - freqtrade.exchange.exchange - INFO - Using Exchange "Kraken"
2020-04-23 17:46:33,184 - freqtrade.exchange.exchange - WARNING - Unable to initialize markets. Reason: GET https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size- 403 Forbidden <!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <title>Security check</title>
  <style>body{background:#03363d;color:#fff;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen-Sans,Ubuntu,Cantarell,Helvetica Neue,Arial,sans-serif;font-size:14px;font-style:normal;font-variant:normal;line-height:1.6;margin:1.6rem}h1{font-size:22px;line-height:1.4em;margin-top:0;padding-top:0}article,h1,p{margin:0}:link,:visited{color:#fff}.l-max-readable-width{max-width:40em}.l-centered{margin-left:auto;margin-right:auto}.l-v-padded{padding-bottom:.8rem}.l-top-padded,.l-v-padded{padding-top:.8rem}.l-padded-bottom{margin-bottom:.8rem}.err__page-heading{font-size:1rem;font-weight:400;padding-bottom:1.6rem}@media screen and (min-width:400px){.err__page-heading{font-size:1.6rem;font-weight:300}}@media screen and (min-width:520px){.err__page-heading{font-size:2rem}}.err__container{background:#fff;border-radius:.2rem;color:#012b30;padding:1.2rem 1.6rem}.err__container :link,.err__container :visited{color:#1f73b7}.err__additional-translation:before{background:#56777a;content:"";display:block;height:.4rem;margin:.8rem 0;overflow:hidden;width:2.4rem}.err__details-content h1{font-size:1em;font-weight:600;line-height:inherit}.err__details-content ul{margin-bottom:0;margin-top:0}.c-btn{-moz-user-select:none;-ms-user-select:none;-webkit-font-smoothing:subpixel-antialiased;-webkit-touch-callout:none;-webkit-user-select:none;background-color:transparent;border:1px solid #5293c7;border-radius:4px;box-sizing:border-box;color:#1f73b7;cursor:pointer;display:inline-block;font-family:inherit;font-size:14px;font-weight:400;line-height:38px;margin:0;min-width:8.57143em;overflow:hidden;padding:0 1.92857em;text-align:center;text-decoration:none;text-overflow:ellipsis;transition:border-color .25s ease-in-out,box-shadow .1s ease-in-out,background-color .25s ease-in-out,color .25s ease-in-out;user-select:none;vertical-align:middle;white-space:nowrap}.c-btn.c-btn--primary{background-color:#1f73b7;border-color:transparent}.c-btn.c-btn--primary{color:#fff}.c-btn.is-hovered.is-hovered,.c-btn:hover:hover{background-color:#5293c7;border-color:transparent;color:#fff;text-decoration:none}.c-btn.is-focused,.c-btn:focus:focus{box-shadow:0 0 0 3px rgba(31,115,183,.35);outline:none}.c-btn.is-active.is-active,.c-btn:active:active{background-color:#144a75;border-color:transparent;color:#fff;text-decoration:none;transition:border-color .1s ease-in-out,background-color .1s ease-in-out,color .1s ease-in-out}.u-fine-print-on-white{color:#2d5e64;font-size:.785rem}.u-centered{text-align:center}</style>
  <meta name="viewport" content="width=device-width">
</head>

<body>
  
  <article class="l-max-readable-width l-centered">

    <h1 class="err__page-heading">
      Complete the security check to access this page
    </h1>

    <div class="err__container l-padded-bottom">
      <div class="l-top-padded err__details-content">
        <form class="challenge-form" id="challenge-form" action="/hc/en-us/articles/205893708-What-is-the-minimum-order-size-?__cf_chl_captcha_tk__=4febcad62a4d496776f16ccdb717f8dae8464a86-1587656793-0-AVQ-3ak1zJCVCQm-2MVmqO1VNL1A3prYi5QLcIQvebCMBUAT-nDePdUwJ2yxod5LDOgqu7WLMOoA0fXQdFLx1pbdeEjwtJsbriUH7d9Q_xTfo-YcqJrmwgW0NPagglfVnNYIYN0OhA4v3kzi6PP48Bqx1qe4p3r6DJUMWZOxqvRZwA-bhflnC3lbIumBhJa5UAjQ4gMAWpn7Whu2d00bi_V5DtU7AwlFcfQPUsIfYAKAlQX2ZDK217B9AFtmqah2c1XhN8BQkmVZgQ8kbOvt_WD2Q_wDAsjyTQCMgANb-n57vAwYVmmiGvxXoiaDf7Vto1nw7ObYD1TdNaw92zq0dDdg42woCYlS3I3bKZ6qo55ThB6rP548YWjb2vlrKOZdNn0QxuINrrwDrpsZCcbX4FaH31iQZhBaiIgFUFthaQlJmY9Sl9eiTs1qv3zDfL5j-VN6QkMbMXCGFFYbxyLN4cSfVQahOIa6bnk6nDu5ex1gcB1HBt7pcCJg9nch8OXBDNUVtMNDnIl8Rb6y2nrwgK1YW4sMNNT4DK5rOL7xUl1QRs39XKEMWyTdvf0YSEmFZkAEBQJOXhXecNbD0VhA8TV-jbsTzCi_9aLNYWPE44sOFCGQzdi9NOp9OwQ0zDJHIA" method="POST" enctype="application/x-www-form-urlencoded">
  <input type="hidden" name="r" value="e449e2852ba20fb0ba63b51439be446b4da8d921-1587656793-0-AVBQuw7ZCGiciwgAAQGm1rnHpWhockx0TqgbBvmMyRVNPrF8bbNh7Jbs26CDEZbG7LpBKsQ4mC4EUBDKHJgtRxonrTRZzIzHGa1oZSSbgQxlQ0NgFwRR2e7jI3Ew5vtisvxY//NnqaQMm3f/WZUZB67Rd/pBCaDDsStfJ08xGPo7skDiHt+Oa6h9f39wEM7kuvCaGELfmqneYNfHvEnVElkS/eYjmXIbgsr4rbrP27h76vp3F0/dyd0dqa1YITJQkzPuyWPSaRmH1EQkYRzw+4TqEUtf3RCL/HW5EZ2SXcdIdbUFZDA94VYieByrGdO/illhauj+IBoDdWiqnHY4+2A3BTtHCqYXszk69Wnha/tALO0035k2SqpJrHBqP0kByV166e080qAqPCwABzRTascBlwEDh1mn3Sz8mH+hv6yr0z31T7urF2QGPsJPFrx0NgmZK3qMYE+LaG/wOh62o9kS41DA7Pbc9S7//nI0Ts6jFkX7PFaYxtoln5yeoaAsfGlNwxlcEH33Y3hcROM7At6FPeXTdGv4Dho3lZo1LuxKdT5li8TpYKvAo9PwdlmW6pF7XbTq/+jwZ5RuMNASlELqV4lDnkdQ2qau4Cv1XdeJHOfyj5cHz384jXUuOHRiv6zVwDa4NMLltOwFrXPXVw71huiwtUSF553qhTQExUUmsBlnrCKg/6OiGMBwzL33K4zWia/GP/Gt4Bu68FcvoFeKPVy7F/U2wpBZ/3fzcIMri759SGak7/IaHZZpP1sSeODiRKiEisfSelX7Uf1D8hadPQxZZF3Ytqio6NoAWzd/2xH5+UEjpslo6AezdB1IF2H/9BQ9a7bIhnsfGenM6Y0JH0AuCmNb/wduUG647SUz1kgVX1GpOO8rqYt/b7RR3U8jwKpuRcWV6hQTagTmtH3yv5muTPtf5880nGmlNlactmN+Um51RsKYMjhByryMuITr4+2B6k54lcnKV3OP3aPauLjcTFOGamPZjHL8vN0f/E5Xh9zw6wWsC+afujBPBnwdRdp9SyfOu4px9wTDNwTs1OReCiE21RW1j8s3K638HBhZ0RAiuQKMmHeQyyFjqaUJZmVRQx+rDs1KTKLA3p+be7NFcgaPDAn0BWQVY/mpsLjiaA5GgZl3uCc0OapmjT1yPoxFiitUIHR8vm9vKFeZLbxp6iiB/4TKDzJ3DgCl3HHkd8nOVPR5dZIAHaWfGffn+AQg97/7aDiZJF+4Ciuxpa24faXTuGIlH/bMZFj/dz3EtPM+tLsXEExXv9dlkkJKco/fzQeyQTIaVijcHs51N+oJ700ahfzBC5a4TDjsC76La5rz6SNMKGy02/0wgqVNUHciNTFJiIVPPNh00tTLPxgW53ed/yDukQ6A4EsQ">
  <input type="hidden" name="cf_captcha_kind" value="h">
  <script type="text/javascript" src="/cdn-cgi/scripts/hcaptcha.challenge.js" data-type="normal"  data-ray="5888b7cd2a2afa38" async data-sitekey="33f96e6a-38cd-421b-bb68-7806e1764460"></script>
  <noscript id="cf-captcha-bookmark" class="cf-captcha-info">
  <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="trk_captcha_js" style="background-image:url('/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=5888b7cd2a2afa38')"></div>
</form>

        <hr>
      </div>
      <p>
        Completing a CAPTCHA proves you are a human and gives you temporary access to this page.
        <br>
        Make sure your home and work devices are regularly scanned for malware to reduce the need to complete the CAPTCHA.
        <hr>
        RayID: 5888b7cd2a2afa38
        <br>
        IP: 77.21.83.176
      </p>
    </div>

    <div class="l-v-padded">
      <div lang="pt-br" class="err__additional-translation">
        <h3>
          Conclua essa verificação de segurança para acessar essa página
        </h3>
        <p class="l-top-padded">
          Completar o CAPTCHA comprova que você é humano e fornece acesso temporário à página. Verifique regularmente seus dispositivos domésticos e comerciais quanto a infecções de malware para reduzir a necessidade de conclusão do CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="es-419" class="err__additional-translation">
        <h3>
          Complete la verificación de seguridad para tener acceso a esta página
        </h3>
        <p class="l-top-padded">
          La verificación CAPTCHA se encarga de comprobar que usted es un ser humano, y le da acceso temporal a esta página. Asegúrese de analizar regularmente sus dispositivos personales y de trabajo en busca de malware para reducir la necesidad de una verificación CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="de" class="err__additional-translation">
        <h3>
          Sicherheitsprüfung zum Zugriff auf diese Seite erforderlich
        </h3>
        <p class="l-top-padded">
          Die CAPTCHA-Prüfung beweist, dass es sich bei Ihnen um einen echten Menschen handelt, und gibt Ihnen vorübergehend Zugriff auf diese Seite. Achten Sie darauf, dass Ihre Geräte zuhause und im Büro regelmäßig auf Malware geprüft werden, damit CAPTCHA nur in Ausnahmefällen erforderlich ist.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="fr" class="err__additional-translation">
        <h3>
          Veuillez effectuer la vérification de sécurité pour accéder à cette page
        </h3>
        <p class="l-top-padded">
          Une vérification CAPTCHA nous permet de nous assurer que vous êtes une personne réelle afin de vous donner un accès temporaire à cette page. Vérifiez régulièrement l’absence de logiciels malveillants sur vos appareils personnels et professionnels pour réduire la nécessité d’effectuer une vérification CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="nl" class="err__additional-translation">
        <h3>
          Voltooi de beveiligingscontrole om toegang tot deze pagina te krijgen
        </h3>
        <p class="l-top-padded">
          Door een CAPTCHA in te vullen, bewijst u dat u een mens bent en krijgt u tijdelijk toegang tot deze pagina. Zorg ervoor dat uw apparaten voor persoonlijk en zakelijk gebruik regelmatig worden gescand op malware. Zo wordt het invullen van een CAPTCHA minder noodzakelijk.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ru" class="err__additional-translation">
        <h3>
          Для доступа к этой странице необходимо пройти проверку безопасности
        </h3>
        <p class="l-top-padded">
          Успешное прохождение теста CAPTCHA доказывает, что вы человек, и дает вам временный доступ к этой странице. Чтобы не проходить тест CAPTCHA слишком часто, регулярно проверяйте свои устройства дома и на работе на отсутствие вредоносных программ.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ja" class="err__additional-translation">
        <h3>
          このページにアクセスするには、セキュリティチェックを完了してください
        </h3>
        <p class="l-top-padded">
          CAPTCHAを正しく入力すると人間による入力であることが証明され、このページへの一時的なアクセスが提供されます。CAPTCHAを入力する必要性を減らすには、マルウェアが存在しないか自宅と職場の機器を定期的にスキャンするようにしてください。
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="it" class="err__additional-translation">
        <h3>
          Completa il controllo di sicurezza per accedere a questa pagina
        </h3>
        <p class="l-top-padded">
          Il superamento del test CAPTCHA dimostra che sei un essere umano e ti concede l’accesso temporaneo a questa pagina. Assicurati di sottoporre a scansione i dispositivi che usi a casa e al lavoro per escludere la presenza di malware e ridurre la necessità di eseguire il test CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="ar" class="err__additional-translation">
        <h3 dir="rtl">
          أكمل الفحص الأمني للوصول إلى هذه الصفحة
        </h3>
        <p class="l-top-padded" dir="rtl">
          يثبت إكمال اختبار CAPTCHA أنك إنسان ويمنحك وصولاً مؤقتًا لهذه الصفحة. تأكد من إجراء مسح دوري على أجهزة منزلك وعملك لاستكشاف البرامج المضرة لتقليل الحاجة إلى إكمال اختبار   CAPTCHA.
        </p>
      </div>
    </div>

    <div class="l-v-padded">
      <div lang="zh-cn" class="err__additional-translation">
        <h3>
          完成安全检查以访问此页面
        </h3>
        <p class="l-top-padded">
          完成 CAPTCHA 可证明您是真人，将为您提供对此页面的临时访问权限。请确保您的家庭和工作设备定期进行恶意软件扫描，以降低需要完成 CAPTCHA 的频率。
        </p>
      </div>
    </div>
  </article>
</body>
</html>
2020-04-23 17:46:33,187 - freqtrade.exchange.exchange - WARNING - Markets were not loaded. Loading them now..
^C2020-04-23 17:46:40,835 - freqtrade.commands.trade_commands - INFO - SIGINT received, aborting ...
`

**Comment by hroff-1902** [comment] 2020-04-23 16:12
seems to be duplicate of https://github.com/freqtrade/freqtrade/issues/3171

update ccxt lib (`pip install -U ccxt`)

**Comment by xmatthias** [comment] 2020-04-25 14:35
I'll assume this as fixed by updating ccxt.

Feel free to comment if you're still having problems.

**Closed by xmatthias** 2020-04-25 14:35 UTC
Labels: CCXT, Duplicate
