### ISSUE TITLE
Proposed way for additional constraints in Hyperopt

### ISSUE THREAD

**Issue by HeinrichHaller** [freqtrade/freqtrade#7344] opened 2022-09-04 20:18 UTC
## Describe your environment

  * Operating system: Ubuntu LTS
  * Python Version: Python 3.10.6
  * CCXT version: pip freeze | grep ccxt
  * Freqtrade Version: freqtrade docker-b53791fe

  
## Your question

Is there a proposed way to write constraints for the optimization? To ensure a relation between optimimizable parameters for instance like param1 > param2 etc?

**Comment by xmatthias** [comment] 2022-09-05 04:31
Duplicate of #7345 (which asks the question in a more specific way) - as well as #7189.

Please avoid opening duplicate issues in the future - and use the search to find closed issues that already answer your question - thanks.

**Closed as completed by xmatthias** 2022-09-05 04:31 UTC
Labels: Duplicate, Question, Hyperopt
