### ISSUE TITLE
Why backtesting displays trades for the last day but my live bot did absolutely no trades?

### ISSUE THREAD

**Issue by c0d3r34d3r** [freqtrade/freqtrade#3907] opened 2020-10-30 08:34 UTC
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3.8.6 (`python -V`)
  * CCXT version: _____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: 2020.9.1 (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
## Your question

So I've got a live bot running for few days now but it has executed no trades. I downloaded data of the last day and run backtesting on it with the same algorithm/config and it showed 3 trades. Live bot however did execute no trades in the same period of time.

What could be the cause of this?

Does it have something to do with by bid/ask strategy?
```
	"bid_strategy": {
		"price_side": "bid",
		"ask_last_balance": 0.0,
		"use_order_book": false,
		"order_book_top": 1,
		"check_depth_of_market": {
			"enabled": false,
			"bids_to_ask_delta": 1
		}
	},
	"ask_strategy": {
		"price_side": "ask",
		"use_order_book": false,
		"order_book_min": 1,
		"order_book_max": 1,
		"use_sell_signal": true,
		"sell_profit_only": false,
		"ignore_roi_if_buy_signal": false
	},
```

**Comment by xmatthias** [comment] 2020-10-30 09:57
bid/ask strategy define how the order is priced - not **if** a trade is entered.

If you had the 3 trades posted to the exchange, but they were cancelled (check the telegram notifications / exchange order log) - then this can be an issue related to this configuration section.

If the trades were never posted - then you're most likely having a general problem in your strategy, that it's using data it has access to in backtesting, but not in live/dry runs.

Did this strategy make any trades in your dry-run tests (You did test the strategy in dry-run - right?)

**Comment by c0d3r34d3r** [comment] 2020-10-30 10:12
> Did this strategy make any trades in your dry-run tests (You did test the strategy in dry-run - right?)

No, I haven't tested it in dry-run.

> If the trades were never posted - then you're most likely having a general problem in your strategy, that it's using data it has access to in backtesting, but not in live/dry runs.

In my strategy I'm using informative pairs like this:
```
    def informative_pairs(self):
        pairs = self.dp.current_whitelist()
        informative_pairs = [(pair, '1d') for pair in pairs]
        return informative_pairs
...
        dataframe['rocr'] = ta.ROCR(dataframe, timeperiod=7)
        inf_tf = '1d'
        informative = self.dp.get_pair_dataframe(pair=metadata['pair'], timeframe=inf_tf)
        informative['rocr'] = ta.ROCR(informative, timeperiod=7)
        dataframe = merge_informative_pair(dataframe, informative, self.timeframe, inf_tf, ffill=True)
```

Could this be the issue?

**Comment by xmatthias** [comment] 2020-10-30 10:18
i don't think so - this code doesn't look wrong.

Best go through [this list](https://www.freqtrade.io/en/latest/strategy-customization/#common-mistakes-when-developing-strategies) of common strategy gotchas ... It's probably not complete - but it should cover the most common gotchas.

**Comment by jafarlihi** [comment] 2020-10-30 10:48
@xmatthias 
Is it possible that my live bot didn't do the trades that happen in backtesting because I had `max_open_trades` set to 200 and with my 50$ stake amount, it amounted to 0.25$ which was below the exchange's minimum limit for trades?

**Comment by c0d3r34d3r** [comment] 2020-10-30 10:49
@xmatthias 
Is it possible that my live bot didn't do the trades that happen in backtesting because I had `max_open_trades` set to 200 and with my 50$ stake amount, it amounted to 0.25$ which was below the exchange's minimum limit for trades?

**Comment by xmatthias** [comment] 2020-10-30 12:55
that's impossible to tell for me - details of this will be in your logs - but it seems quite likely ...

**Comment by xmatthias** [comment] 2020-11-02 09:43
I'll assume the problem was caused by the configuration as you explained above.

Feel free to comment below / reopen if that's not the case.

**Closed by xmatthias** 2020-11-02 09:43 UTC
Labels: Question
