### ISSUE TITLE
OKX Upgrade to the latest version failed to start

### ISSUE THREAD

**Issue by byte-flylf** [freqtrade/freqtrade#7667] opened 2022-10-30 14:37 UTC
## Describe your environment

  * Operating system: _centos7___
  * Python Version: _Python 3.10.6____ (`python -V`)
  * CCXT version: __ccxt==2.0.58___ (`pip freeze | grep ccxt`)
  * Freqtrade Version: _freqtrade 2022.11.dev-bd051cb___ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
### Observed Results:

  * What happened?
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here
2022-10-30 22:22:17,006 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/account/balance HTTP/1.1" 200 None
2022-10-30 22:22:17,197 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instId=%5B%5D HTTP/1.1" 400 58
2022-10-30 22:22:17,198 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}". Retrying still for 4 times.
2022-10-30 22:22:17,396 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instId=%5B%5D HTTP/1.1" 400 58
2022-10-30 22:22:17,397 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}". Retrying still for 3 times.
2022-10-30 22:22:17,595 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instId=%5B%5D HTTP/1.1" 400 58
2022-10-30 22:22:17,596 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}". Retrying still for 2 times.
2022-10-30 22:22:17,799 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instId=%5B%5D HTTP/1.1" 400 58
2022-10-30 22:22:17,800 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}". Retrying still for 1 times.
2022-10-30 22:22:17,996 - urllib3.connectionpool - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instId=%5B%5D HTTP/1.1" 400 58
2022-10-30 22:22:17,997 - freqtrade.exchange.common - WARNING - fetch_positions() returned exception: "Could not get positions due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}". Giving up.
2022-10-30 22:22:17,997 - freqtrade.commands.trade_commands - ERROR - Could not get positions due to BadRequest. Message: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}
2022-10-30 22:22:17,998 - freqtrade.commands.trade_commands - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://www.okx.com/api/v5/account/positions?instId=%5B%5D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/FT/freqtrade/freqtrade/exchange/exchange.py", line 1372, in fetch_positions
    positions: List[Dict] = self._api.fetch_positions(symbols)
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/okx.py", line 3878, in fetch_positions
    response = self.privateGetAccountPositions(self.extend(request, params))
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/base/exchange.py", line 500, in inner
    return entry(_self, **inner_kwargs)
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2612, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2609, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/base/exchange.py", line 636, in fetch
    skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/okx.py", line 5268, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], code, feedback)
  File "/root/miniconda3/envs/freqtrade-conda/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2882, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.BadRequest: okx {"code":"51000","data":[],"msg":"Parameter instId  error"}

  ```

**Comment by xmatthias** [comment] 2022-10-31 16:31
This was caused by a bug in [ccxt #15468](https://github.com/ccxt/ccxt/issues/15468) - which is now fixed.

For develop, this is closed in b3f612ecfba13322a29f786decf29b7e4ef02506.

**Closed as completed by xmatthias** 2022-10-31 16:31 UTC
Labels: Bug, CCXT
