### ISSUE TITLE
release locks manually

### ISSUE THREAD

**Issue by scientes** [freqtrade/freqtrade#4450] opened 2021-02-26 21:37 UTC
## Describe the enhancement

It would be nice to release/delete locks made trough protections manually through telegram similar to the `/delete` functionality for trades.

**Comment by xmatthias** [comment] 2021-02-27 07:15
Please use the search to search for open issues before opening a new issue.

Duplicate of #4386

**Closed as completed by xmatthias** 2021-02-27 07:15 UTC
Labels: Duplicate
