### ISSUE TITLE
continuous freqtrade.plugins.pairlistmanager - INFO logging

### ISSUE THREAD

**Issue by Deleriumdelicious** [freqtrade/freqtrade#7686] opened 2022-11-02 11:41 UTC
## Describe your environment

  * Operating system: Ubuntu 22.04 x64
  * Python Version: Python 3.10.6
  * CCXT version: ccxt==2.0.96
  * Freqtrade Version: freqtrade 2022.11.dev-2ed04916a
  * Script installation used
  
## Describe the problem:

When strating the bot in LIVE mode everything seems to work properly, only the log seems wrong and continuous to show a freqtrade.plugins.pairlistmanager - INFO line every couple of seconds next to the normal heartbeat line. 

### Steps to reproduce:

  1. Update freqtrade and use develop branch
  2.  run bot with freqtrade trade -s POP2 -c config_binance-POP2.json -c binance-POP-DRY.json --db-url sqlite:///user_data/tradesBIN.live.sqlite
 

### Relevant code exceptions or logs

2022-11-02 10:52:25,275 - freqtrade.worker - INFO - Changing state to: RUNNING
2022-11-02 10:52:25,276 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "*Exchange:* `binance`\n*Stake per trade:* `unlimited BUSD`\n*Minimum ROI:* `{'0': 0.1, '5': 0.04, '120': 0.02, '240': 0.008}`\n*Trailing Stoploss:* `-0.072`\n*Position adjustment:* `Off`\n*Timeframe:* `15m`\n*Strategy:* `POP2`"}
2022-11-02 10:52:25,276 - freqtrade.rpc.telegram - INFO - Notification 'startup' not sent.
2022-11-02 10:52:25,276 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': "Searching for BUSD pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 35 volume pairs.'}, {'PriceFilter': 'PriceFilter - Filtering pairs priced below 0.01000000.'}, {'AgeFilter': 'AgeFilter - Filtering pairs with age less than 30 days'}, {'RangeStabilityFilter': 'RangeStabilityFilter - Filtering pairs with rate of change below 0.0005 over the last days.'}, {'ShuffleFilter': 'ShuffleFilter - Shuffling pairs.'}]"}
2022-11-02 10:52:25,276 - freqtrade.rpc.telegram - INFO - Notification 'startup' not sent.
2022-11-02 10:52:25,276 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': startup, 'status': 'Using Protections: \nCooldownPeriod - Cooldown period of 120 minutes.\nStoplossGuard - Frequent Stoploss Guard, 2 stoplosses with profit < 0.00% within 90 minutes.\nStoplossGuard - Frequent Stoploss Guard, 1 stoplosses with profit < 0.00% within 90 minutes.'}
2022-11-02 10:52:25,276 - freqtrade.rpc.telegram - INFO - Notification 'startup' not sent.
2022-11-02 10:52:25,299 - freqtrade.freqtradebot - INFO - Updating 0 open orders.
2022-11-02 10:52:25,342 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['NEAR/BUSD', 'MATIC/BUSD', 'PHA/BUSD', 'APE/BUSD', 'ETC/BUSD', 'LTC/BUSD', 'BTC/BUSD', 'INJ/BUSD', 'XRP/BUSD', 'ADA/BUSD', 'ETH/BUSD', 'DOGE/BUSD', 'USTC/BUSD', 'CHZ/BUSD', 'AVAX/BUSD', 'LIT/BUSD', 'LUNA/BUSD', 'RNDR/BUSD', 'PROS/BUSD', 'MASK/BUSD', 'SOL/BUSD', 'GALA/BUSD', 'RUNE/BUSD', 'SAND/BUSD', 'ENS/BUSD', 'VIB/BUSD', 'LINK/BUSD', 'KLAY/BUSD', 'ATOM/BUSD']
2022-11-02 10:52:34,374 - freqtrade.worker - INFO - Bot heartbeat. PID=690389, version='2022.11.dev-2ed04916a', state='RUNNING'
2022-11-02 10:52:34,403 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ETH/BUSD', 'INJ/BUSD', 'SAND/BUSD', 'SOL/BUSD', 'LIT/BUSD', 'LUNA/BUSD', 'DOGE/BUSD', 'ETC/BUSD', 'KLAY/BUSD', 'ADA/BUSD', 'PROS/BUSD', 'RUNE/BUSD', 'GALA/BUSD', 'BTC/BUSD', 'MATIC/BUSD', 'MASK/BUSD', 'RNDR/BUSD', 'PHA/BUSD', 'ENS/BUSD', 'VIB/BUSD', 'CHZ/BUSD', 'XRP/BUSD', 'USTC/BUSD', 'LINK/BUSD', 'LTC/BUSD', 'APE/BUSD', 'ATOM/BUSD', 'AVAX/BUSD', 'NEAR/BUSD']
2022-11-02 10:52:41,147 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['NEAR/BUSD', 'KLAY/BUSD', 'XRP/BUSD', 'ADA/BUSD', 'GALA/BUSD', 'AVAX/BUSD', 'VIB/BUSD', 'PROS/BUSD', 'DOGE/BUSD', 'LUNA/BUSD', 'LIT/BUSD', 'USTC/BUSD', 'MATIC/BUSD', 'INJ/BUSD', 'RNDR/BUSD', 'ETC/BUSD', 'APE/BUSD', 'LINK/BUSD', 'ETH/BUSD', 'SOL/BUSD', 'LTC/BUSD', 'BTC/BUSD', 'ENS/BUSD', 'ATOM/BUSD', 'MASK/BUSD', 'SAND/BUSD', 'CHZ/BUSD', 'PHA/BUSD', 'RUNE/BUSD']
2022-11-02 10:52:47,657 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ADA/BUSD', 'GALA/BUSD', 'PROS/BUSD', 'LUNA/BUSD', 'RNDR/BUSD', 'ENS/BUSD', 'NEAR/BUSD', 'XRP/BUSD', 'VIB/BUSD', 'DOGE/BUSD', 'PHA/BUSD', 'USTC/BUSD', 'SAND/BUSD', 'APE/BUSD', 'KLAY/BUSD', 'ETH/BUSD', 'LTC/BUSD', 'LIT/BUSD', 'LINK/BUSD', 'BTC/BUSD', 'CHZ/BUSD', 'SOL/BUSD', 'RUNE/BUSD', 'INJ/BUSD', 'ATOM/BUSD', 'MATIC/BUSD', 'AVAX/BUSD', 'ETC/BUSD', 'MASK/BUSD']
2022-11-02 10:52:54,236 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['NEAR/BUSD', 'ATOM/BUSD', 'ETH/BUSD', 'MATIC/BUSD', 'RUNE/BUSD', 'ENS/BUSD', 'APE/BUSD', 'VIB/BUSD', 'LINK/BUSD', 'SAND/BUSD', 'CHZ/BUSD', 'USTC/BUSD', 'DOGE/BUSD', 'KLAY/BUSD', 'SOL/BUSD', 'LTC/BUSD', 'LUNA/BUSD', 'GALA/BUSD', 'AVAX/BUSD', 'ADA/BUSD', 'PHA/BUSD', 'MASK/BUSD', 'BTC/BUSD', 'PROS/BUSD', 'ETC/BUSD', 'INJ/BUSD', 'XRP/BUSD', 'RNDR/BUSD', 'LIT/BUSD']
2022-11-02 10:53:01,667 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ETH/BUSD', 'GALA/BUSD', 'RNDR/BUSD', 'ATOM/BUSD', 'SOL/BUSD', 'PHA/BUSD', 'CHZ/BUSD', 'PROS/BUSD', 'LIT/BUSD', 'LTC/BUSD', 'ADA/BUSD', 'DOGE/BUSD', 'LUNA/BUSD', 'USTC/BUSD', 'APE/BUSD', 'SAND/BUSD', 'LINK/BUSD', 'INJ/BUSD', 'VIB/BUSD', 'XRP/BUSD', 'NEAR/BUSD', 'RUNE/BUSD', 'AVAX/BUSD', 'KLAY/BUSD', 'ENS/BUSD', 'BTC/BUSD', 'MATIC/BUSD', 'MASK/BUSD', 'ETC/BUSD']
2022-11-02 10:53:08,722 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ADA/BUSD', 'ETC/BUSD', 'GALA/BUSD', 'ENS/BUSD', 'CHZ/BUSD', 'MATIC/BUSD', 'LIT/BUSD', 'PROS/BUSD', 'BTC/BUSD', 'XRP/BUSD', 'LINK/BUSD', 'SOL/BUSD', 'USTC/BUSD', 'KLAY/BUSD', 'AVAX/BUSD', 'VIB/BUSD', 'RUNE/BUSD', 'INJ/BUSD', 'NEAR/BUSD', 'ATOM/BUSD', 'RNDR/BUSD', 'LTC/BUSD', 'SAND/BUSD', 'PHA/BUSD', 'ETH/BUSD', 'MASK/BUSD', 'DOGE/BUSD', 'APE/BUSD', 'LUNA/BUSD']
2022-11-02 10:53:15,424 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['LINK/BUSD', 'ADA/BUSD', 'USTC/BUSD', 'DOGE/BUSD', 'ETH/BUSD', 'SAND/BUSD', 'GALA/BUSD', 'LUNA/BUSD', 'ATOM/BUSD', 'AVAX/BUSD', 'SOL/BUSD', 'PROS/BUSD', 'BTC/BUSD', 'ENS/BUSD', 'INJ/BUSD', 'CHZ/BUSD', 'APE/BUSD', 'ETC/BUSD', 'XRP/BUSD', 'PHA/BUSD', 'RUNE/BUSD', 'MASK/BUSD', 'LTC/BUSD', 'MATIC/BUSD', 'VIB/BUSD', 'KLAY/BUSD', 'NEAR/BUSD', 'LIT/BUSD', 'RNDR/BUSD']
2022-11-02 10:53:22,129 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['DOGE/BUSD', 'PROS/BUSD', 'GALA/BUSD', 'ETH/BUSD', 'NEAR/BUSD', 'CHZ/BUSD', 'ATOM/BUSD', 'RNDR/BUSD', 'KLAY/BUSD', 'XRP/BUSD', 'ENS/BUSD', 'MATIC/BUSD', 'LIT/BUSD', 'SAND/BUSD', 'APE/BUSD', 'MASK/BUSD', 'ETC/BUSD', 'VIB/BUSD', 'RUNE/BUSD', 'LTC/BUSD', 'ADA/BUSD', 'USTC/BUSD', 'INJ/BUSD', 'AVAX/BUSD', 'BTC/BUSD', 'PHA/BUSD', 'SOL/BUSD', 'LUNA/BUSD', 'LINK/BUSD']
2022-11-02 10:53:28,896 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['NEAR/BUSD', 'RUNE/BUSD', 'INJ/BUSD', 'ETH/BUSD', 'PROS/BUSD', 'LUNA/BUSD', 'KLAY/BUSD', 'SAND/BUSD', 'MASK/BUSD', 'LIT/BUSD', 'ETC/BUSD', 'APE/BUSD', 'ATOM/BUSD', 'RNDR/BUSD', 'LTC/BUSD', 'GALA/BUSD', 'VIB/BUSD', 'AVAX/BUSD', 'DOGE/BUSD', 'MATIC/BUSD', 'ADA/BUSD', 'LINK/BUSD', 'PHA/BUSD', 'ENS/BUSD', 'BTC/BUSD', 'SOL/BUSD', 'USTC/BUSD', 'CHZ/BUSD', 'XRP/BUSD']
2022-11-02 10:53:35,543 - freqtrade.worker - INFO - Bot heartbeat. PID=690389, version='2022.11.dev-2ed04916a', state='RUNNING'
2022-11-02 10:53:35,572 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['USTC/BUSD', 'CHZ/BUSD', 'AVAX/BUSD', 'XRP/BUSD', 'PROS/BUSD', 'KLAY/BUSD', 'BTC/BUSD', 'ETH/BUSD', 'RNDR/BUSD', 'VIB/BUSD', 'ETC/BUSD', 'NEAR/BUSD', 'RUNE/BUSD', 'SOL/BUSD', 'MASK/BUSD', 'MATIC/BUSD', 'LTC/BUSD', 'GALA/BUSD', 'INJ/BUSD', 'LUNA/BUSD', 'SAND/BUSD', 'ATOM/BUSD', 'LIT/BUSD', 'ENS/BUSD', 'LINK/BUSD', 'DOGE/BUSD', 'PHA/BUSD', 'ADA/BUSD', 'APE/BUSD']
2022-11-02 10:53:42,480 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['MATIC/BUSD', 'ATOM/BUSD', 'LINK/BUSD', 'ENS/BUSD', 'AVAX/BUSD', 'RUNE/BUSD', 'ETC/BUSD', 'XRP/BUSD', 'KLAY/BUSD', 'LIT/BUSD', 'SOL/BUSD', 'BTC/BUSD', 'GALA/BUSD', 'INJ/BUSD', 'ADA/BUSD', 'RNDR/BUSD', 'PROS/BUSD', 'LUNA/BUSD', 'SAND/BUSD', 'USTC/BUSD', 'DOGE/BUSD', 'NEAR/BUSD', 'CHZ/BUSD', 'PHA/BUSD', 'LTC/BUSD', 'VIB/BUSD', 'MASK/BUSD', 'ETH/BUSD', 'APE/BUSD']
2022-11-02 10:53:49,090 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['NEAR/BUSD', 'KLAY/BUSD', 'PROS/BUSD', 'USTC/BUSD', 'LTC/BUSD', 'ETC/BUSD', 'ENS/BUSD', 'CHZ/BUSD', 'RNDR/BUSD', 'LUNA/BUSD', 'ATOM/BUSD', 'SOL/BUSD', 'LINK/BUSD', 'APE/BUSD', 'DOGE/BUSD', 'GALA/BUSD', 'AVAX/BUSD', 'VIB/BUSD', 'INJ/BUSD', 'MATIC/BUSD', 'LIT/BUSD', 'XRP/BUSD', 'PHA/BUSD', 'MASK/BUSD', 'ADA/BUSD', 'RUNE/BUSD', 'BTC/BUSD', 'SAND/BUSD', 'ETH/BUSD']
2022-11-02 10:53:55,776 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ADA/BUSD', 'ENS/BUSD', 'NEAR/BUSD', 'USTC/BUSD', 'PROS/BUSD', 'APE/BUSD', 'KLAY/BUSD', 'LTC/BUSD', 'RNDR/BUSD', 'BTC/BUSD', 'DOGE/BUSD', 'SAND/BUSD', 'LINK/BUSD', 'AVAX/BUSD', 'MATIC/BUSD', 'GALA/BUSD', 'LIT/BUSD', 'ETC/BUSD', 'VIB/BUSD', 'SOL/BUSD', 'CHZ/BUSD', 'LUNA/BUSD', 'PHA/BUSD', 'ATOM/BUSD', 'MASK/BUSD', 'ETH/BUSD', 'XRP/BUSD', 'RUNE/BUSD', 'INJ/BUSD']
2022-11-02 10:54:02,401 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['KLAY/BUSD', 'MASK/BUSD', 'LIT/BUSD', 'DOGE/BUSD', 'RUNE/BUSD', 'RNDR/BUSD', 'LINK/BUSD', 'ENS/BUSD', 'NEAR/BUSD', 'APE/BUSD', 'ADA/BUSD', 'PROS/BUSD', 'XRP/BUSD', 'ATOM/BUSD', 'VIB/BUSD', 'SAND/BUSD', 'CHZ/BUSD', 'AVAX/BUSD', 'INJ/BUSD', 'LTC/BUSD', 'ETC/BUSD', 'MATIC/BUSD', 'SOL/BUSD', 'USTC/BUSD', 'PHA/BUSD', 'ETH/BUSD', 'BTC/BUSD', 'LUNA/BUSD', 'GALA/BUSD']
2022-11-02 10:54:09,440 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['BTC/BUSD', 'GALA/BUSD', 'SAND/BUSD', 'LTC/BUSD', 'ATOM/BUSD', 'DOGE/BUSD', 'APE/BUSD', 'AVAX/BUSD', 'SOL/BUSD', 'KLAY/BUSD', 'LINK/BUSD', 'XRP/BUSD', 'INJ/BUSD', 'VIB/BUSD', 'MASK/BUSD', 'ENS/BUSD', 'PHA/BUSD', 'LIT/BUSD', 'RUNE/BUSD', 'CHZ/BUSD', 'ETC/BUSD', 'USTC/BUSD', 'ADA/BUSD', 'RNDR/BUSD', 'NEAR/BUSD', 'MATIC/BUSD', 'LUNA/BUSD', 'ETH/BUSD', 'PROS/BUSD']
2022-11-02 10:54:16,107 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ETC/BUSD', 'ETH/BUSD', 'KLAY/BUSD', 'AVAX/BUSD', 'MATIC/BUSD', 'DOGE/BUSD', 'LIT/BUSD', 'SAND/BUSD', 'LTC/BUSD', 'CHZ/BUSD', 'BTC/BUSD', 'INJ/BUSD', 'ENS/BUSD', 'LUNA/BUSD', 'LINK/BUSD', 'APE/BUSD', 'PHA/BUSD', 'USTC/BUSD', 'VIB/BUSD', 'NEAR/BUSD', 'RNDR/BUSD', 'GALA/BUSD', 'ADA/BUSD', 'XRP/BUSD', 'MASK/BUSD', 'RUNE/BUSD', 'SOL/BUSD', 'PROS/BUSD', 'ATOM/BUSD']
2022-11-02 10:54:22,618 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ADA/BUSD', 'MATIC/BUSD', 'USTC/BUSD', 'ETH/BUSD', 'SAND/BUSD', 'CHZ/BUSD', 'PROS/BUSD', 'RNDR/BUSD', 'XRP/BUSD', 'LUNA/BUSD', 'MASK/BUSD', 'PHA/BUSD', 'LTC/BUSD', 'ENS/BUSD', 'LIT/BUSD', 'GALA/BUSD', 'KLAY/BUSD', 'ATOM/BUSD', 'AVAX/BUSD', 'SOL/BUSD', 'BTC/BUSD', 'RUNE/BUSD', 'DOGE/BUSD', 'LINK/BUSD', 'NEAR/BUSD', 'ETC/BUSD', 'INJ/BUSD', 'VIB/BUSD', 'APE/BUSD']
2022-11-02 10:54:29,183 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['SAND/BUSD', 'SOL/BUSD', 'LINK/BUSD', 'CHZ/BUSD', 'RUNE/BUSD', 'XRP/BUSD', 'VIB/BUSD', 'PHA/BUSD', 'APE/BUSD', 'MASK/BUSD', 'PROS/BUSD', 'LTC/BUSD', 'DOGE/BUSD', 'LUNA/BUSD', 'NEAR/BUSD', 'USTC/BUSD', 'BTC/BUSD', 'ATOM/BUSD', 'RNDR/BUSD', 'INJ/BUSD', 'ENS/BUSD', 'LIT/BUSD', 'GALA/BUSD', 'AVAX/BUSD', 'ETC/BUSD', 'KLAY/BUSD', 'MATIC/BUSD', 'ADA/BUSD', 'ETH/BUSD']
2022-11-02 10:54:35,776 - freqtrade.worker - INFO - Bot heartbeat. PID=690389, version='2022.11.dev-2ed04916a', state='RUNNING'
2022-11-02 10:54:35,805 - freqtrade.plugins.pairlistmanager - INFO - Whitelist with 29 pairs: ['ENS/BUSD', 'RNDR/BUSD', 'APE/BUSD', 'PHA/BUSD', 'ADA/BUSD', 'MASK/BUSD', 'BTC/BUSD', 'RUNE/BUSD', 'INJ/BUSD', 'ATOM/BUSD', 'XRP/BUSD', 'USTC/BUSD', 'LINK/BUSD', 'PROS/BUSD', 'VIB/BUSD', 'SAND/BUSD', 'GALA/BUSD', 'KLAY/BUSD', 'SOL/BUSD', 'AVAX/BUSD', 'ETC/BUSD', 'DOGE/BUSD', 'ETH/BUSD', 'MATIC/BUSD', 'LTC/BUSD', 'CHZ/BUSD', 'LIT/BUSD', 'LUNA/BUSD', 'NEAR/BUSD']

**Comment by stash86** [comment] 2022-11-02 12:01
That's just shufflepairlist on work

**Comment by xmatthias** [comment] 2022-11-02 12:26
Duplicate of #7658 .
as correctly pointed out - shufflepairlist at work - the message would be cached once it no longer changes - which is unlikely / impossible with shufflefilter.

**Closed as completed by xmatthias** 2022-11-02 12:26 UTC
Labels: Duplicate, Question
