### ISSUE TITLE
Unable to analyze ticker for pair WRX/BTC: negative dimensions are not allowed

### ISSUE THREAD

**Issue by acemi1** [freqtrade/freqtrade#2866] opened 2020-02-05 08:43 UTC
I shut down the boot and restarted it. I encountered this error message

```
2020-02-05 11:39:13,738 - VolumePairList - INFO - Searching 20 pairs: ['XRP/BTC', 'ICX/BTC', 'ETH/BTC', 'MATIC/BTC', 'ENJ/BTC', 'WRX/BTC', 'EOS/BTC', 'AION/BTC', 'TRX/BTC', 'LTC/BTC', 'ETC/BTC', 'ADA/BTC', 'XTZ/BTC', 'WAN/BTC', 'BAT/BTC', 'MTL/BTC', 'XLM/BTC', 'ATOM/BTC', 'LINK/BTC', 'RVN/BTC']
2020-02-05 11:39:13,750 - freqtrade.rpc.rpc_manager - INFO - Enabling rpc.telegram ...
2020-02-05 11:39:13,957 - freqtrade.rpc.telegram - INFO - rpc.telegram is listening for following commands: [['status'], ['profit'], ['balance'], ['start'], ['stop'], ['forcesell'], ['forcebuy'], ['performance'], ['daily'], ['count'], ['reload_conf'], ['show_config'], ['stopbuy'], ['whitelist'], ['blacklist'], ['edge'], ['help'], ['version']]
2020-02-05 11:39:13,978 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'running'}
2020-02-05 11:39:14,076 - freqtrade.worker - INFO - Changing state to: RUNNING
2020-02-05 11:39:14,077 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': warning, 'status': 'Dry run is enabled. All trades are simulated.'}
2020-02-05 11:39:14,117 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': custom, 'status': "*Exchange:* `binance`\n*Stake per trade:* `1 BTC`\n*Minimum ROI:* `{'0': 0.21}`\n*Trailing Stoploss:* `-0.2`\n*Ticker Interval:* `1h`\n*Strategy:* `strateji1`"}
2020-02-05 11:39:14,158 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': "Searching for BTC pairs to buy and sell based on [{'VolumePairList': 'VolumePairList - top 20 volume pairs.'}]"}
2020-02-05 11:39:19,559 - freqtrade.strategy.interface - WARNING - Unable to analyze ticker for pair WRX/BTC: negative dimensions are not allowed
2020-02-05 11:39:20,710 - freqtrade.freqtradebot - INFO - Bot heartbeat. PID=16343
2020-02-05 11:39:21,135 - freqtrade.strategy.interface - WARNING - Unable to analyze ticker for pair WRX/BTC: negative dimensions are not allowed
2020-02-05 11:39:26,142 - freqtrade.strategy.interface - WARNING - Unable to analyze ticker for pair WRX/BTC: negative dimensions are not allowed
^C2020-02-05 11:39:26,244 - freqtrade.utils - INFO - SIGINT received, aborting ...
2020-02-05 11:39:26,245 - freqtrade.utils - INFO - worker found ... calling exit
2020-02-05 11:39:26,245 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': status, 'status': 'process died'}
2020-02-05 11:39:26,283 - freqtrade.freqtradebot - INFO - Cleaning up modules ...
2020-02-05 11:39:26,283 - freqtrade.rpc.rpc_manager - INFO - Cleaning up rpc modules ...
```

**Comment by xmatthias** [comment] 2020-02-05 10:22
It's basically #1067 - and i think the same solution will apply here, too.

WRX/BTC is a new pair - new pairs usually have a spike in volume the first day - so they're picked up by VolumePairlist.

The error you're receiving is because this pair does not have the full history (it only started trading yesterday) - and depending on how the strategy is build, having only a few records in the history can create this problem.

PrecisionFilter is usually able to filter these pairs out as they start low-priced - so i'd encourage using that filter as a solution - as this can and will happen in the future.

**Comment by acemi1** [comment] 2020-02-05 10:55
thank you for answering in a short time

**Comment by hroff-1902** [comment] 2020-02-05 13:00
@xmatthias should we check this in appropriate place in the code and return an exception with som more user-friendly message instead of generic python error?

**Comment by xmatthias** [comment] 2020-02-05 17:03
If you look at where this message comes from - then this IS the user-friendly version.

https://github.com/freqtrade/freqtrade/blob/b5ee4f17cb610cba273c2663112d6fe4f60154b9/freqtrade/strategy/interface.py#L257-L265

This exception is caused by the too short history - in this case.
However, the error itself is generic - and happens within strategy code - so it could also happen for other reasons (error in the strategy, using an inexisting column, for example).

**Comment by hroff-1902** [comment] 2020-02-06 02:21
opening this for now as the reminder to have a look at this, to make the message less generic in this case...

**Comment by xmatthias** [comment] 2020-02-06 05:22
I don't understand how you'd do that / how you'd "less generalize" this message.

there's many things within the strategy could cause a ValueError - and "not enough history" will definitely be the most uncommon one.

example:
using 
``` python
...
    if dataframe:

```

will cause a ValueError.
It's not even relevant if the dataframe has 500, 5000 or 0 rows - it's simply raising a ValueError.

**Comment by hroff-1902** [comment] 2020-02-08 00:33
closing it since 1) @xmatthias PR will improve the general message and 2) for my idea I need to find a way to reproduce the "negative dimensions are not allowed" exception, which I'm currently unable, even with "WRP/BTC" in the whitelist and a high timeframe (1d). I'll recall this (I hope) when I met these conditions in the future, closing for now, nothing to change.

**Closed by hroff-1902** 2020-02-08 00:33 UTC
