### ISSUE TITLE
Backtesting same strategy different results

### ISSUE THREAD

**Issue by ovresko** [freqtrade/freqtrade#3680] opened 2020-08-13 20:28 UTC
## Describe your environment

  * Operating system: WIN 10
  * Python Version: _____ 2.8
  * CCXT version: _____  
  * Freqtrade Version: ____ master
  
So i know this is a beginner question, but i've 2 strategies A and B (same periode, stake_amount, timeframe....)
when i run backtesting on A alone it gives me a result, but when i combine it with B both give identical results and A is no longer like the initial test, not even close.

**Comment by xmatthias** [comment] 2020-08-14 04:10
Well it's not clear what you're trying to do.

when you say "combine" - how do you combine them?

**Comment by ovresko** [comment] 2020-08-15 21:13
I mean backtesting with --strategy-list A B give different results then --strategy A alone

**Comment by xmatthias** [comment] 2020-08-16 06:38
backtesting multiple strategies will give you the results of both strategies, so the output format is slightly different.

Since you didn't provide any precise version above, it's also possible that you run into old bugs (master is not a version, but a branch - which will be a "Moving target" over time).

**Comment by xmatthias** [comment] 2020-08-25 06:12
I'll close this here as i think it's a duplicate of #3132.
You did not provide any version - so it's a very likely that you have the same problem.

To quickly summarize the solution: 
the previous ta-lib version had a bug, where one changed parameter was "kept" for subsequent calls to this method.
so if one strategy calls `ta.RSI(dataframe, 25)` (for example, all methods were affected) - all subsequent calls (`ta.RSI(dataframe)`) without specifying the lookback period would have used 25 as well (the default is 14 i think). 
For that reason, results depended on the sequence of the strategies (and depending on which strategy was used).

This version was however updated sometime in April. 
Best make sure you've got the latest version of both freqtrade and ta-lib installed.

**Closed by xmatthias** 2020-08-25 06:12 UTC
Labels: Question
