### ISSUE TITLE
Backtesting Error Msg - TypeError

### ISSUE THREAD

**Issue by Prossi79** [freqtrade/freqtrade#2798] opened 2020-01-23 17:13 UTC
## Step 1: Have you search for this issue before posting it?

If you have discovered a bug in the bot, please [search our issue tracker](https://github.com/freqtrade/freqtrade/issues?q=is%3Aissue). 
If it hasn't been reported, please create a new issue.

## Step 2: Describe your environment

  * Operating system: Ubuntu
  * Python Version: Python 3.7.4
  * CCXT version: ccxt==1.21.76
  * Branch: Develop
  * Last Commit ID: eb6c7f8595e826ce7d9ff6413b5b6352c9a5382a
  
## Step 3: Describe the problem:

*Explain the problem you have encountered*

### Steps to reproduce:

 Tried to backtest my stratety with following cmd

freqtrade backtesting  -s BbandRsi_AP4 -c config_base.json -c configB1.json --timerange=20191205-20200119 --export trades --ticker-interval 1h
  
### Observed Results:

see log below

### Relevant code exceptions or logs:

  ```
freqtrade backtesting  -s BbandRsi_AP4 -c config_base.json -c configB1.json --timerange=20191205-20200119 --export trades --ticker-interval 1h
2020-01-23 18:09:04,528 - freqtrade.loggers - INFO - Verbosity set to 0
2020-01-23 18:09:04,528 - freqtrade.configuration.configuration - INFO - Parameter -i/--ticker-interval detected ... Using ticker_interval: 1h ...
2020-01-23 18:09:04,528 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 3 ...
2020-01-23 18:09:04,528 - freqtrade.configuration.configuration - INFO - Parameter --timerange detected: 20191205-20200119 ...
2020-01-23 18:09:04,530 - freqtrade.configuration.configuration - INFO - Using user-data directory: /home/andreas/freqtrade/user_data ...
2020-01-23 18:09:04,530 - freqtrade.configuration.configuration - INFO - Using data directory: /home/andreas/freqtrade/user_data/data/binance ...
2020-01-23 18:09:04,530 - freqtrade.configuration.configuration - INFO - Overriding ticker interval with Command line argument
2020-01-23 18:09:04,530 - freqtrade.configuration.configuration - INFO - Parameter --export detected: trades ...
2020-01-23 18:09:04,530 - freqtrade.configuration.check_exchange - INFO - Checking exchange...
2020-01-23 18:09:04,530 - freqtrade.configuration.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
2020-01-23 18:09:04,530 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
2020-01-23 18:09:04,530 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `experimental.use_sell_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ask_strategy.use_sell_signal` setting in your configuration instead.
2020-01-23 18:09:04,530 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `experimental.sell_profit_only` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ask_strategy.sell_profit_only` setting in your configuration instead.
2020-01-23 18:09:04,530 - freqtrade.configuration.deprecated_settings - WARNING - DEPRECATED: The `experimental.ignore_roi_if_buy_signal` setting is deprecated and will be removed in the next versions of Freqtrade. Please use the `ask_strategy.ignore_roi_if_buy_signal` setting in your configuration instead.
2020-01-23 18:09:04,531 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-01-23 18:09:04,532 - freqtrade.optimize - INFO - Starting freqtrade in Backtesting mode
2020-01-23 18:09:04,532 - freqtrade.exchange.exchange - INFO - Instance is running with dry_run enabled
2020-01-23 18:09:04,532 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True}
2020-01-23 18:09:04,534 - freqtrade.exchange.exchange - INFO - Applying additional ccxt config: {'enableRateLimit': True, 'ratelimit': 1000}
2020-01-23 18:09:04,535 - freqtrade.exchange.exchange - INFO - Using Exchange "Binance"
2020-01-23 18:09:05,431 - freqtrade.resolvers.exchange_resolver - INFO - Using resolved exchange 'Binance'...
2020-01-23 18:09:05,466 - freqtrade.resolvers.iresolver - WARNING - Could not import /home/andreas/freqtrade/user_data/strategies/MultiRSI.py due to 'No module named 'technical''
2020-01-23 18:09:05,476 - freqtrade.resolvers.iresolver - INFO - Using resolved strategy BbandRsi_AP4 from '/home/andreas/freqtrade/user_data/strategies/BbandRsi_AP4.py'...
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ticker_interval' with value in config file: 1h.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'process_only_new_candles' with value in config file: False.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'order_types' with value in config file: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_currency' with value in config file: USDT.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'stake_amount' with value in config file: 999.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'unfilledtimeout' with value in config file: {'buy': 10, 'sell': 30}.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'use_sell_signal' with value in config file: True.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'sell_profit_only' with value in config file: True.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Override strategy 'ignore_roi_if_buy_signal' with value in config file: False.
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using minimal_roi: {'200': 0.02, '80': 0.03, '40': 0.04, '0': 0.05}
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ticker_interval: 1h
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stoploss: -0.15
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop: False
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_stop_positive_offset: 0.0
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using trailing_only_offset_is_reached: False
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using process_only_new_candles: False
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_types: {'buy': 'limit', 'sell': 'limit', 'stoploss': 'limit', 'stoploss_on_exchange': True, 'stoploss_on_exchange_interval': 60}
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using order_time_in_force: {'buy': 'gtc', 'sell': 'gtc'}
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_currency: USDT
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using stake_amount: 999
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using startup_candle_count: 100
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using unfilledtimeout: {'buy': 10, 'sell': 30}
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using use_sell_signal: True
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using sell_profit_only: True
2020-01-23 18:09:05,476 - freqtrade.resolvers.strategy_resolver - INFO - Strategy using ignore_roi_if_buy_signal: False
2020-01-23 18:09:05,476 - freqtrade.configuration.config_validation - INFO - Validating configuration ...
2020-01-23 18:09:05,478 - freqtrade.optimize.backtesting - INFO - Using stake_currency: USDT ...
2020-01-23 18:09:05,478 - freqtrade.optimize.backtesting - INFO - Using stake_amount: 999 ...
2020-01-23 18:09:05,479 - freqtrade.data.history - INFO - Using indicator startup period: 100 ...
2020-01-23 18:09:05,503 - freqtrade.data.history - WARNING - Missing data at end for pair XRP/USDT, data ends at 2019-12-03 12:00:00
2020-01-23 18:09:05,605 - freqtrade.data.history - WARNING - Missing data at end for pair IOTA/USDT, data ends at 2019-12-03 12:00:00
2020-01-23 18:09:05,639 - freqtrade.data.history - WARNING - Missing data at end for pair QTUM/USDT, data ends at 2019-12-03 12:00:00
2020-01-23 18:09:05,672 - freqtrade.data.history - WARNING - Missing data at end for pair ICX/USDT, data ends at 2019-12-03 12:00:00
2020-01-23 18:09:05,685 - freqtrade.optimize.backtesting - INFO - Loading data from 2019-11-30T20:00:00+00:00 up to 2020-01-18T23:00:00+00:00 (49 days)..
2020-01-23 18:09:05,685 - freqtrade.optimize.backtesting - INFO - Running backtesting for Strategy BbandRsi_AP4
2020-01-23 18:09:05,714 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/andreas/freqtrade/freqtrade/main.py", line 36, in main
    return_code = args['func'](args)
  File "/home/andreas/freqtrade/freqtrade/optimize/__init__.py", line 44, in start_backtesting
    backtesting.start()
  File "/home/andreas/freqtrade/freqtrade/optimize/backtesting.py", line 398, in start
    min_date, max_date = history.get_timerange(preprocessed)
  File "/home/andreas/freqtrade/freqtrade/data/history.py", line 456, in get_timerange
    for frame in data.values()
  File "/home/andreas/freqtrade/freqtrade/data/history.py", line 456, in <listcomp>
    for frame in data.values()
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/arrow/factory.py", line 184, in get
    return self.type.fromdatetime(arg)
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/arrow/arrow.py", line 232, in fromdatetime
    tzinfo,
  File "/home/andreas/freqtrade/.env/lib/python3.7/site-packages/arrow/arrow.py", line 83, in __init__
    year, month, day, hour, minute, second, microsecond, tzinfo
TypeError: integer argument expected, got float

  ```

**Comment by xmatthias** [comment] 2020-01-23 18:28
you can probably best debug this yourself by changing the following function in history.py to look as below:

``` python
def get_timerange(data: Dict[str, DataFrame]) -> Tuple[arrow.Arrow, arrow.Arrow]:
    """
    Get the maximum common timerange for the given backtest data.

    :param data: dictionary with preprocessed backtesting data
    :return: tuple containing min_date, max_date
    """
    print([(pair, frame['date'].min(), frame['date'].max())
        for pair, frame in data.items()
    ])
    timeranges = [
        (arrow.get(frame['date'].min()), arrow.get(frame['date'].max()))
        for frame in data.values()
    ]
    return (min(timeranges, key=operator.itemgetter(0))[0],
            max(timeranges, key=operator.itemgetter(1))[1])
```

Note: this function is called multiple times, the "really" relevant output is the one from the 2nd time this is called.

I suspect that your strategy is assigning some number to the 'date' column - which then causes this problem.

my ouptut for the above looks as follows - you'rs will too (the first round) - but i guess it won't when it hits this function the 2nd time (right after `Running backtesting for Strategy xxx`).


```
[('TRX/ETH', Timestamp('2018-08-01 00:00:00+0000', tz='UTC'), Timestamp('2018-09-14 23:55:00+0000', tz='UTC')), ('XRP/ETH', Timestamp('2018-08-01 00:00:00+0000', tz='UTC'), Timestamp('2018-09-14 23:55:00+0000', tz='UTC')), ('ADA/ETH', Timestamp('2018-08-01 00:00:00+0000', tz='UTC'), Timestamp('2018-09-14 23:55:00+0000', tz='UTC'))
```

**Comment by hroff-1902** [comment] 2020-01-23 21:58
@Prossi79 ,
@xmatthias asked you above ^^ to make this because we do not see these errors locally.

If this is too complicated, could you send me that BbandRsi_AP4 strategy on Slack in a PM? So that I could try to reproduce it...

@xmatthias I'm suspecting this is due to resampling made in the strategy...

**Comment by xmatthias** [comment] 2020-01-24 05:17
well the "original" BbandRsi strategy in the strategy repo does not have any resampling.

Also, i do have multiple resampling strategies - none of which has ever shown this problem.

It's more like a `dataframe['date'] = bollinger['upper']` ... (or some other indicator ...).

**Comment by Prossi79** [comment] 2020-01-24 07:05
Good morning! Thanks for your quick reply!

@hroff-1902  .. I will send you my strat file to reproduce the error

**Comment by hroff-1902** [comment] 2020-02-03 13:41
@xmatthias I forgotten about this (did not corellate PM at slack with this issue), seems I have the strat from @Prossi79 in the Slack PM

**Comment by xmatthias** [comment] 2020-02-21 07:53
has this been fixed in the meantime ?

**Comment by xmatthias** [comment] 2020-04-25 14:37
I'll assume this as closed due to no activity.

Feel free to comment if you've not been able to solve this.

**Closed by xmatthias** 2020-04-25 14:37 UTC
Labels: Question, Triage Needed

**Comment by anyn99** [comment] 2021-03-07 23:18
Hi there!

I have exactly this problem with the recent develop branch and Python 3.8!

Everything works fine until i set the variable "startup_candle_count"

I tried printing the pairs and start/end timestamp by altering the get_timestamp function inside history-util.py, as suggested above. All timestamps where ok, but the ones with no history dataframes showed for both timeframes "NaT"!
```
('OMG/EUR', Timestamp('2021-01-01 00:00:00+0000', tz='UTC'), Timestamp('2021-03-05 14:10:00+0000', tz='UTC')), 
('BTC/EUR', NaT, NaT),
```

Without "startup_candle_count", those "NaT" got filtered out as i see the message 
```
2021-03-07 23:33:37,899 - freqtrade.data.history.idatahandler - WARNING - No history data for pair: "BTC/EUR", timeframe: 5m. Use `freqtrade download-data` to download the data
```
only then.
