### ISSUE TITLE
okx short wrong profit calc

### ISSUE THREAD

**Issue by byte-flylf** [freqtrade/freqtrade#7341] opened 2022-09-04 09:36 UTC
## Describe your environment

  * Operating system: Centos7.9
  * Python Version: __Python 3.10.5___ (`python -V`)
  * CCXT version: _ccxt==1.92.52____ (`pip freeze | grep ccxt`)
  * Freqtrade Version: __freqtrade 2022.8__ (`freqtrade -V` or `docker-compose run --rm freqtrade -V` for Freqtrade running in docker)
  
Note: All issues other than enhancement requests will be closed without further comment if the above template is deleted or not filled out.

## Describe the problem:

 Using freqtrade triggered a short trade, and the trade entered normally. After a while, it exited because of ROI trading. However, the information sent by the freqtrade system to telgram is a positive profit，In fact, it is a loss, but freqtrade shows that it is profitable
  
### Observed Results:

  * What happened?
 ```
 CPFreqtradeBot, [2022/9/4 星期日 14:50]
🔵 Okx: Short ETH/USDT:USDT (#6)
Candle OHLC: 1550.7, 1551.59, 1543.0, 1545.48
Enter Tag: down >= 0.8
Amount: 0.00000000
Leverage: 5.0
Open Rate: 1546.48000000
Current Rate: 1545.43000000
Total: (139.614 USDT, 139.614 USD)

CPFreqtradeBot, [2022/9/4 星期日 14:50]
✓ Okx: Shorted ETH/USDT:USDT (#6)
Candle OHLC: 1550.7, 1551.59, 1543.0, 1545.48
Enter Tag: down >= 0.8
Amount: 0.40000000
Leverage: 5.0
Open Rate: 1546.48000000
Total: (123.718 USDT, 123.718 USD)

CPFreqtradeBot, [2022/9/4 星期日 16:15]
✳️ Okx: Exiting ETH/USDT:USDT (#6)
Candle OHLC: 1549.91, 1551.42, 1547.1, 1549.54
Unrealized Profit: 3.20% (profit: 3.95461397 USDT / 3.959 USD)
Enter Tag: down >= 0.8
Exit Reason: roi
Direction: Short
Leverage: 5.0
Amount: 0.40000000
Open Rate: 1546.48000000
Current Rate: 1549.20000000
Exit Rate: 1549.20000000
Duration: 1:25:07 (85.1 min)

CPFreqtradeBot, [2022/9/4 星期日 16:15]
✳️ Okx: Exited ETH/USDT:USDT (#6)
Candle OHLC: 1549.91, 1551.42, 1547.1, 1549.54
Profit: 3.20% (profit: 3.95461397 USDT / 3.959 USD)
Enter Tag: down >= 0.8
Exit Reason: roi
Direction: Short
Leverage: 5.0
Amount: 0.40000000
Open Rate: 1546.48000000
Exit Rate: 1549.20000000
Duration: 1:25:17 (85.3 min)
```
  * What did you expect to happen?

### Relevant code exceptions or logs

Note: Please copy/paste text of the messages, no screenshots of logs please.

  ```
  // paste your log here

2022-09-04 16:15:11,673 - {/root/freqtrade/freqtrade/exchange/exchange.py:1532} - DEBUG - Using cached exit rate for ETH/USDT:USDT.
2022-09-04 16:15:11,673 - {/root/freqtrade/freqtrade/rpc/rpc_manager.py:81} - INFO - Sending rpc message: {'type': exit, 'trade_id': 6, 'exchange': 'Okx', 'pair': 'ETH/USDT:USDT', 'leverage': 5.0, 'direction': 'Short', 'gain': 'profit', 'limit': 1549.2, 'order_type': 'limit', 'amount': 0.4, 'open_rate': 1546.48, 'close_rate': 1549.2, 'current_rate': 1549.2, 'profit_amount': 3.95461397, 'profit_ratio': 0.03197103, 'buy_tag': 'down >= 0.8', 'enter_tag': 'down >= 0.8', 'sell_reason': 'roi', 'exit_reason': 'roi', 'open_date': datetime.datetime(2022, 9, 4, 6, 50, 4, 845638), 'close_date': datetime.datetime(2022, 9, 4, 8, 15, 11, 673820), 'stake_amount': 123.7184, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 0.0}
2022-09-04 16:15:11,674 - {/root/freqtrade/freqtrade/rpc/rpc_manager.py:87} - DEBUG - Forwarding message to rpc.telegram

  ```

**Comment by xmatthias** [comment] 2022-09-04 13:42
Please don't use titles this long, but a short, descriptive titles.

What you have in the title is a description - which is wrong, and very difficult to read, as github does not render the full title in all cases if it's this long.

You can move your description to the text (which is lacking that information) - but a title this long is not helpful - and will only be confusing.


We'll also need quite a bit more information to start working on this.

the output of the following command (obviously fitted to your environment):`freqtrade show-trades --db-url sqlite:///<trades.sqlite> --print-json --trade-ids <tradeid>`
proper logs from the time of the sell (ideally a few logmessages before and after the sell).

**Comment by byte-flylf** [comment] 2022-09-04 15:54
The display of the production environment lacks parameters, but they have actually been passed. The test run mode is normal
```
(.env) [root@testhost freqtrade]# ls -trl tradesv3.*
-rw-r--r-- 1 root root 114688 Sep  3 16:41 tradesv3.dryrun.sqlite
-rw-r--r-- 1 root root  25600 Sep  4 22:29 tradesv3.sqlite
-rw-r--r-- 1 root root  32768 Sep  4 23:02 tradesv3.sqlite-shm
-rw-r--r-- 1 root root   9464 Sep  4 23:02 tradesv3.sqlite-wal
-rw-r--r-- 1 root root      0 Sep  4 23:20 tradesv3.dryrun.sqlite-wal
-rw-r--r-- 1 root root  32768 Sep  4 23:20 tradesv3.dryrun.sqlite-shm
(.env) [root@testhost freqtrade]# 
(.env) [root@testhost freqtrade]# 
(.env) [root@testhost freqtrade]# pwd
/root/freqtrade
```

(.env) [root@testhost freqtrade]# freqtrade show-trades --config user_data/config.json --db-url sqlite:///tradesv3.sqlite --trade-ids 6 --print-json
2022-09-04 23:20:19,441 - {/root/freqtrade/freqtrade/configuration/load_config.py:92} - INFO - Using config: user_data/config.json ...
2022-09-04 23:20:19,442 - {/root/freqtrade/freqtrade/loggers.py:132} - INFO - Verbosity set to 0
2022-09-04 23:20:19,443 - {/root/freqtrade/freqtrade/configuration/configuration.py:185} - INFO - Using user-data directory: /root/freqtrade/user_data ...
2022-09-04 23:20:19,443 - {/root/freqtrade/freqtrade/configuration/configuration.py:188} - INFO - Using data directory: /root/freqtrade/user_data/data/okx ...
2022-09-04 23:20:19,443 - {/root/freqtrade/freqtrade/configuration/configuration.py:501} - INFO - Parameter --print-json detected ...
2022-09-04 23:20:19,443 - {/root/freqtrade/freqtrade/configuration/configuration.py:501} - INFO - Filtering on trade_ids: ['6']
2022-09-04 23:20:19,443 - {/root/freqtrade/freqtrade/configuration/check_exchange.py:28} - INFO - Checking exchange...
2022-09-04 23:20:19,454 - {/root/freqtrade/freqtrade/configuration/check_exchange.py:56} - INFO - Exchange "okx" is officially supported by the Freqtrade development team.
2022-09-04 23:20:19,454 - {/root/freqtrade/freqtrade/configuration/configuration.py:531} - INFO - Using pairlist from configuration.
2022-09-04 23:20:19,454 - {/root/freqtrade/freqtrade/configuration/config_validation.py:90} - INFO - Validating configuration ...
2022-09-04 23:20:19,460 - {/root/freqtrade/freqtrade/main.py:55} - ERROR - --db-url is required for this command.
(.env) [root@testhost freqtrade]# freqtrade show-trades --config user_data/config.json --db-url sqlite:///tradesv3.dryrun.sqlite --trade-ids 6 --print-json
2022-09-04 23:20:58,868 - {/root/freqtrade/freqtrade/configuration/load_config.py:92} - INFO - Using config: user_data/config.json ...
2022-09-04 23:20:58,870 - {/root/freqtrade/freqtrade/loggers.py:132} - INFO - Verbosity set to 0
2022-09-04 23:20:58,870 - {/root/freqtrade/freqtrade/configuration/configuration.py:152} - INFO - Parameter --db-url detected ...
2022-09-04 23:20:58,870 - {/root/freqtrade/freqtrade/configuration/configuration.py:185} - INFO - Using user-data directory: /root/freqtrade/user_data ...
2022-09-04 23:20:58,871 - {/root/freqtrade/freqtrade/configuration/configuration.py:188} - INFO - Using data directory: /root/freqtrade/user_data/data/okx ...
2022-09-04 23:20:58,871 - {/root/freqtrade/freqtrade/configuration/configuration.py:501} - INFO - Parameter --print-json detected ...
2022-09-04 23:20:58,871 - {/root/freqtrade/freqtrade/configuration/configuration.py:501} - INFO - Filtering on trade_ids: ['6']
2022-09-04 23:20:58,871 - {/root/freqtrade/freqtrade/configuration/check_exchange.py:28} - INFO - Checking exchange...
2022-09-04 23:20:58,882 - {/root/freqtrade/freqtrade/configuration/check_exchange.py:56} - INFO - Exchange "okx" is officially supported by the Freqtrade development team.
2022-09-04 23:20:58,882 - {/root/freqtrade/freqtrade/configuration/configuration.py:531} - INFO - Using pairlist from configuration.
2022-09-04 23:20:58,882 - {/root/freqtrade/freqtrade/configuration/config_validation.py:90} - INFO - Validating configuration ...
2022-09-04 23:20:58,887 - {/root/freqtrade/freqtrade/commands/list_commands.py:214} - INFO - Using DB: "sqlite:///tradesv3.dryrun.sqlite"
2022-09-04 23:20:58,964 - {/root/freqtrade/freqtrade/commands/list_commands.py:222} - INFO - Printing 1 Trades: 
[
    {
        "trade_id": 6,
        "pair": "ETH/USDT:USDT",
        "base_currency": "ETH",
        "quote_currency": "USDT",

**Comment by byte-flylf** [comment] 2022-09-04 15:55
```
2022-09-04 16:15:16,086 - {/root/freqtrade/freqtrade/worker.py:142} - DEBUG - Throttling with '_process_running()': sleep for 4.83 s, last iteration took 0.17 s.
2022-09-04 16:15:20,913 - {/root/freqtrade/freqtrade/worker.py:138} - DEBUG - ========================================
2022-09-04 16:15:20,927 - {/root/freqtrade/freqtrade/exchange/exchange.py:1871} - DEBUG - Refreshing candle (OHLCV) data for 1 pairs
2022-09-04 16:15:20,927 - {/root/freqtrade/freqtrade/exchange/exchange.py:1890} - DEBUG - Using cached candle (OHLCV) data for ETH/USDT:USDT, 5m, futures ...
2022-09-04 16:15:20,928 - {/root/freqtrade/freqtrade/strategy/interface.py:689} - DEBUG - TA Analysis Launched
2022-09-04 16:15:20,928 - {/root/freqtrade/freqtrade/strategy/interface.py:1181} - DEBUG - Populating indicators for pair ETH/USDT:USDT.
2022-09-04 16:15:21,044 - {/root/freqtrade/freqtrade/strategy/interface.py:1200} - DEBUG - Populating enter signals for pair ETH/USDT:USDT.
2022-09-04 16:15:21,062 - {/root/freqtrade/freqtrade/strategy/interface.py:1217} - DEBUG - Populating exit signals for pair ETH/USDT:USDT.
2022-09-04 16:15:21,063 - {/root/freqtrade/freqtrade/strategy/interface.py:725} - DEBUG - Loop Analysis Launched
2022-09-04 16:15:21,081 - {/root/freqtrade/.env/lib/python3.10/site-packages/urllib3/connectionpool.py:456} - DEBUG - https://www.okx.com:443 "GET /api/v5/trade/order?instId=ETH-USDT-SWAP&ordId=486569931325222914 HTTP/1.1" 200 675
2022-09-04 16:15:21,083 - {/root/freqtrade/freqtrade/freqtradebot.py:1774} - INFO - Found open order for Trade(id=6, pair=ETH/USDT:USDT, amount=0.40000000, is_short=True, leverage=5.0, open_rate=1546.48000000, open_since=2022-09-04 06:50:04)
2022-09-04 16:15:21,091 - {/root/freqtrade/freqtrade/freqtradebot.py:1906} - INFO - Fee for Trade Trade(id=6, pair=ETH/USDT:USDT, amount=0.40000000, is_short=True, leverage=5.0, open_rate=1546.48000000, open_since=2022-09-04 06:50:04) [buy]: 0.123936 USDT - rate: 0.0002
2022-09-04 16:15:21,091 - {/root/freqtrade/freqtrade/persistence/trade_model.py:600} - INFO - Updating trade (id=6) ...
2022-09-04 16:15:21,091 - {/root/freqtrade/freqtrade/persistence/trade_model.py:620} - INFO - LIMIT_BUY has been fulfilled for Trade(id=6, pair=ETH/USDT:USDT, amount=0.40000000, is_short=True, leverage=5.0, open_rate=1546.48000000, open_since=2022-09-04 06:50:04).
2022-09-04 16:15:21,092 - {/root/freqtrade/freqtrade/persistence/trade_model.py:657} - INFO - Marking Trade(id=6, pair=ETH/USDT:USDT, amount=0.40000000, is_short=True, leverage=5.0, open_rate=1546.48000000, open_since=closed) as closed as the trade is fulfilled and found no open orders for it.
2022-09-04 16:15:21,278 - {/root/freqtrade/.env/lib/python3.10/site-packages/urllib3/connectionpool.py:456} - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instType=SWAP HTTP/1.1" 200 782
2022-09-04 16:15:21,477 - {/root/freqtrade/.env/lib/python3.10/site-packages/urllib3/connectionpool.py:456} - DEBUG - https://www.okx.com:443 "GET /api/v5/account/balance HTTP/1.1" 200 None
2022-09-04 16:15:21,679 - {/root/freqtrade/.env/lib/python3.10/site-packages/urllib3/connectionpool.py:456} - DEBUG - https://www.okx.com:443 "GET /api/v5/account/positions?instType=SWAP HTTP/1.1" 200 772
2022-09-04 16:15:21,681 - {/root/freqtrade/freqtrade/wallets.py:174} - INFO - Wallets synced.
2022-09-04 16:15:21,690 - {/root/freqtrade/freqtrade/rpc/rpc_manager.py:81} - INFO - Sending rpc message: {'type': exit_fill, 'trade_id': 6, 'exchange': 'Okx', 'pair': 'ETH/USDT:USDT', 'leverage': 5.0, 'direction': 'Short', 'gain': 'profit', 'limit': 1549.2, 'order_type': '', 'amount': 0.4, 'open_rate': 1546.48, 'close_rate': 1549.2, 'current_rate': None, 'profit_amount': 3.95461397, 'profit_ratio': 0.03197103, 'buy_tag': 'down >= 0.8', 'enter_tag': 'down >= 0.8', 'sell_reason': 'roi', 'exit_reason': 'roi', 'open_date': datetime.datetime(2022, 9, 4, 6, 50, 4, 845638), 'close_date': datetime.datetime(2022, 9, 4, 8, 15, 21, 91718), 'stake_amount': 123.7184, 'stake_currency': 'USDT', 'fiat_currency': 'USD', 'sub_trade': False, 'cumulative_profit': 3.95461397}
2022-09-04 16:15:21,690 - {/root/freqtrade/freqtrade/rpc/rpc_manager.py:87} - DEBUG - Forwarding message to rpc.telegram
2022-09-04 16:15:22,092 - {/root/freqtrade/freqtrade/rpc/rpc_manager.py:87} - DEBUG - Forwarding message to rpc.apiserver
```

**Comment by xmatthias** [comment] 2022-09-04 17:30
> The display of the production environment lacks parameters, but they have actually been passed. The test run mode is normal

Unfortunately, the output of this is missing the most critical part - the actual, full trade object. That's cut off after ~4 lines - which basically don't contain any information.

**Comment by xmatthias** [comment] 2022-09-06 17:45
@cuipanfeng without the requested full output of the show-trades output (it's truncated above) - we'll not be able to analyze this further and will have to close this as "can't reproduce".

**Comment by xmatthias** [comment] 2022-09-15 05:04
Will have to close this due to lack of information.

If it's still an issue, please provide the information requested above (completely not only part of the output) and reopen this issue so we can investigate.

**Closed as completed by xmatthias** 2022-09-15 05:04 UTC
Labels: Triage Needed, Non-spot
