### ISSUE TITLE
fee culculate error make sell failure on Huobipro

### ISSUE THREAD

**Issue by yaotian** [freqtrade/freqtrade#1185] opened 2018-09-02 10:11 UTC
Buy:
1.5532 EOS, huobipro will make 0.00310 EOS as fee, which means you have only 1.5503 EOS to sell

Sell:
freqtrade still use 1.5532 to sell, which make the sell action failed like below

log info:
2018-09-02 07:03:08,685 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market EOS/USDT.Tried to sell amount 1.5532 at rate 6.5478 (total 10.170042959999998).Message: huobipro {"status":"error","err-code":"account-frozen-balance-insufficient-error","err-msg":"trade account balance is not enough, left: `1.5503`","data":null}

**Comment by xmatthias** [comment] 2018-09-02 10:49
can you please post the corresponding row from the database

```sql
select * from trades where id = <whatever trade id>;
```

thanks.

**Comment by yaotian** [comment] 2018-09-02 13:01
I did the reset and can't provide the database information. Maybe next time.

**Comment by yaotian** [comment] 2018-09-02 13:09
question: how to query from the database? I used sqlite but can not to open it.

sqlite test.sqlite
Unable to open database "test.sqlite": file is encrypted or is not a database

**Comment by xmatthias** [comment] 2018-09-02 15:00
the correct command is `sqlite3` - or sqlitebrowser if you prefer a gui.

Sorry i did not provide that info initially

**Comment by xmatthias** [comment] 2018-09-04 17:26
i'm going to close this one as duplicate - #1086 (and potentially #1084) are about the same issue (but on different exchange / pairs) - so there is a problem, but i don't think it makes sense to keep multiple issues around for the same stuff.

Thanks for reporting, should it happen again i would appreciate if you could post the database row in order for us to try and identify the root bug, either here, or in one of the 2 other issues, thanks.

**Comment by xmatthias** [comment] 2018-09-05 12:30
Thanks for this 
unfortunately (or fortunately?) the data confirms the logic is working as expected (which you also mention above) - so it doesn't really bring us closer to a solution - as it does not confirm that no bug exists in this area.

## Analysis
looking at the first trade - buying with a stake of `10` and a open rate of `6.5566`:
the fee_open column was reset to 0 - so the fee was applied on buy (to EOS).
```
stake_amount  / open_rate = requested_amount
10 / 6.5566 = 1.525180733916969
```
the row lists `1.52195` as the really bought amount (which was updated with the real value after the order is filled).
That's `0.003230` EOS lower than the "requested" amount, which is roughly the 0.002% (more like 0.003% - but I'm not familiar with Hubipro's fee model) of the fee applied on sell. 

You should be able to verify the "real fee" in the Exchange for this order - but my assumption is that it should match the 0.003230 EOS (eventually split across multiple trades)

The same calculation also works for the 2nd trade - while the 3rd trade is not yet sold (but the calculation works here too)
```
10 / 6.4998  = 1.5385088771962214
```
Table has  `1.535423` - so the difference is `0.003085` (which should be again confirmable in the exchange).

**Comment by yaotian** [comment] 2018-09-06 02:17
thanks for detailed info. I will post once the issue happened again.

**Comment by xmatthias** [comment] 2018-09-06 04:34
as mentioned before, i'll close this in favor of #1086, which shows the same problem.

It's good to see it's working as intended (even though apparently not always).

**Comment by yaotian** [comment] 2018-09-14 08:15
this issue happed again.

log:

```
2018-09-14 08:09:27,057 - freqtrade.freqtradebot - WARNING - Unable to sell trade: Insufficient funds to create limit sell order on market EOS/USDT.Tried to sell amount 1.8812 at rate 5.3282 (total 10.02340984).Message: huobipro {"status":"error","err-code":"account-frozen-balance-insufficient-error","err-msg":"trade account balance is not enough, left: `1.8781`","data":null}
```

from sqlite:

```
15|huobipro|EOS/USDT|1|0.002|0.002|5.3156|5.3156||||10.0|1.8812|2018-09-14 00:30:15.847297|||5.431674232371|5.209288|5.5337||MultiRSI|5
```

**Comment by xmatthias** [comment] 2018-09-14 10:02
the sqlite shows that the fee was not updated after buy...

anything in the logs when the buy occured?
the sell is when the error surfaces - but not when it happens unfortunately

**Comment by yaotian** [comment] 2018-09-14 10:13
@xmatthias found something from the log.

```
2018-09-14 00:30:17,284 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=15, pair=EOS/USDT, amount=1.88125517, open_rate=5.31560000, open_since=just now)
2018-09-14 00:30:21,312 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=15, pair=EOS/USDT, amount=1.88125517, open_rate=5.31560000, open_since=just now) failed: myTrade-Dict empty found
2018-09-14 00:30:21,313 - freqtrade.persistence - INFO - Updating trade (id=15) ...
2018-09-14 00:30:21,314 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=15, pair=EOS/USDT, amount=1.88120000, open_rate=5.31560000, open_since=just now).
```

**Comment by xmatthias** [comment] 2018-09-14 11:37
the line showing that there is an error is the following

`2018-09-14 00:30:21,312 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=15, pair=EOS/USDT, amount=1.88125517, open_rate=5.31560000, open_since=just now) failed: myTrade-Dict empty found`

**Comment by yaotian** [comment] 2018-09-15 02:08
@xmatthias 
This error did not happened 100%. 
id(1-14) was updated successfully.
id(15) got failure 
Maybe some logic have error when two ids got updated at the same time.

**Comment by xmatthias** [comment] 2018-09-15 07:59
i'll be honest - i do struggle to recreate this issue.

would you do me the favor and run the following code and paste the output:

```python
import ccxt
import arrow
ct = ccxt.binance( {'apiKey': '<your apikey>',
                   'secret': '<your apisecret>'
                  })
pair='EOS/USDT'
t = arrow.get(2018, 9, 14, 0, 30, 21)
print(f"trade_timestamp: {t.timestamp}")
trades = ct.fetchMyTrades(pair, since=t.timestamp - 100)
trades
```
please insert your keys into the code above before running (don't paste them here!)

feel free to remove any subsequent trades - and to change this to the exchange used for the above trade if it's not binance.
the way freqtrade does query for trades is by using the open-timestamp (without `-100`).

I would now like to compare the timestamps between the database (contained a few posts above) and the exchange.
Maybe adding the -100 would solve the issue in the code - but i'd like to make sure before implementing anything like that.

Should this not return the trade in question (which happened at the time in the database) - please play with the offset until you get it returned.

thanks in advance

**Comment by xmatthias** [comment] 2018-09-15 15:42
"trades" does not output anything? 
sorry - i should have added 
`print(trades)` ...

**Comment by yaotian** [comment] 2018-09-15 18:09
```
trade_timestamp: 1536885021
[{'info': {'id': 2489078331, 'order-id': 12054945574, 'match-id': 19252694073, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.089500000000000000', 'filled-amount': '1.964800000000000000', 'filled-fees': '0.003929600000000000', 'filled-points': '0.0', 'created-at': 1536507309571}, 'id': '2489078331', 'order': '12054945574', 'timestamp': 1536507309571, 'datetime': '2018-09-09T15:35:09.571Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.0895, 'amount': 1.9648, 'cost': 9.999849600000001, 'fee': {'cost': 0.0039296, 'currency': 'EOS'}}, {'info': {'id': 2490609819, 'order-id': 12073228362, 'match-id': 19280851444, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.115400000000000000', 'filled-amount': '1.960800000000000000', 'filled-fees': '0.020060552640000000', 'filled-points': '0.0', 'created-at': 1536527110407}, 'id': '2490609819', 'order': '12073228362', 'timestamp': 1536527110407, 'datetime': '2018-09-09T21:05:10.407Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.1154, 'amount': 1.9608, 'cost': 10.03027632, 'fee': {'cost': 0.02006055264, 'currency': 'USDT'}}, {'info': {'id': 2491105654, 'order-id': 12078454066, 'match-id': 19288888157, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.004200000000000000', 'filled-amount': '1.998300000000000000', 'filled-fees': '0.003996600000000000', 'filled-points': '0.0', 'created-at': 1536532524169}, 'id': '2491105654', 'order': '12078454066', 'timestamp': 1536532524169, 'datetime': '2018-09-09T22:35:24.169Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.0042, 'amount': 1.9983, 'cost': 9.99989286, 'fee': {'cost': 0.0039966, 'currency': 'EOS'}}, {'info': {'id': 2491213439, 'order-id': 12079634096, 'match-id': 19290711898, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '4.904500000000000000', 'filled-amount': '0.833300000000000000', 'filled-fees': '0.008173839700000000', 'filled-points': '0.0', 'created-at': 1536533669676}, 'id': '2491213439', 'order': '12079634096', 'timestamp': 1536533669676, 'datetime': '2018-09-09T22:54:29.676Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 4.9045, 'amount': 0.8333, 'cost': 4.08691985, 'fee': {'cost': 0.0081738397, 'currency': 'USDT'}}, {'info': {'id': 2491213454, 'order-id': 12079634096, 'match-id': 19290711898, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '4.904500000000000000', 'filled-amount': '1.161000000000000000', 'filled-fees': '0.011388249000000000', 'filled-points': '0.0', 'created-at': 1536533669716}, 'id': '2491213454', 'order': '12079634096', 'timestamp': 1536533669716, 'datetime': '2018-09-09T22:54:29.716Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 4.9045, 'amount': 1.161, 'cost': 5.6941245, 'fee': {'cost': 0.011388249, 'currency': 'USDT'}}, {'info': {'id': 2491398914, 'order-id': 12081702205, 'match-id': 19293906603, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '4.949700000000000000', 'filled-amount': '2.019100000000000000', 'filled-fees': '0.004038200000000000', 'filled-points': '0.0', 'created-at': 1536535813475}, 'id': '2491398914', 'order': '12081702205', 'timestamp': 1536535813475, 'datetime': '2018-09-09T23:30:13.475Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 4.9497, 'amount': 2.0191, 'cost': 9.99393927, 'fee': {'cost': 0.0040382, 'currency': 'EOS'}}, {'info': {'id': 2492378705, 'order-id': 12092334265, 'match-id': 19310339266, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.052400000000000000', 'filled-amount': '2.015000000000000000', 'filled-fees': '0.020361172000000000', 'filled-points': '0.0', 'created-at': 1536546907620}, 'id': '2492378705', 'order': '12092334265', 'timestamp': 1536546907620, 'datetime': '2018-09-10T02:35:07.620Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.0524, 'amount': 2.015, 'cost': 10.180586, 'fee': {'cost': 0.020361172, 'currency': 'USDT'}}, {'info': {'id': 2493129046, 'order-id': 12100722412, 'match-id': 19323404013, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.008300000000000000', 'filled-amount': '1.996500000000000000', 'filled-fees': '0.003993000000000000', 'filled-points': '0.0', 'created-at': 1536555913128}, 'id': '2493129046', 'order': '12100722412', 'timestamp': 1536555913128, 'datetime': '2018-09-10T05:05:13.128Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.0083, 'amount': 1.9965, 'cost': 9.99907095, 'fee': {'cost': 0.003993, 'currency': 'EOS'}}, {'info': {'id': 2493871168, 'order-id': 12109175137, 'match-id': 19336456227, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.061600000000000000', 'filled-amount': '0.010000000000000000', 'filled-fees': '0.000101232000000000', 'filled-points': '0.0', 'created-at': 1536565217036}, 'id': '2493871168', 'order': '12109175137', 'timestamp': 1536565217036, 'datetime': '2018-09-10T07:40:17.036Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.0616, 'amount': 0.01, 'cost': 0.050616, 'fee': {'cost': 0.000101232, 'currency': 'USDT'}}, {'info': {'id': 2493874197, 'order-id': 12109175137, 'match-id': 19336515685, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.061600000000000000', 'filled-amount': '1.982500000000000000', 'filled-fees': '0.020069244000000000', 'filled-points': '0.0', 'created-at': 1536565258941}, 'id': '2493874197', 'order': '12109175137', 'timestamp': 1536565258941, 'datetime': '2018-09-10T07:40:58.941Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.0616, 'amount': 1.9825, 'cost': 10.034622, 'fee': {'cost': 0.020069244, 'currency': 'USDT'}}, {'info': {'id': 2494344002, 'order-id': 12114946686, 'match-id': 19344810202, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.032800000000000000', 'filled-amount': '1.986200000000000000', 'filled-fees': '0.003972400000000000', 'filled-points': '0.0', 'created-at': 1536572714021}, 'id': '2494344002', 'order': '12114946686', 'timestamp': 1536572714021, 'datetime': '2018-09-10T09:45:14.021Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.0328, 'amount': 1.9862, 'cost': 9.99614736, 'fee': {'cost': 0.0039724, 'currency': 'EOS'}}, {'info': {'id': 2495054035, 'order-id': 12123645948, 'match-id': 19358147966, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.015700000000000000', 'filled-amount': '1.982200000000000000', 'filled-fees': '0.019884241080000000', 'filled-points': '0.0', 'created-at': 1536582912475}, 'id': '2495054035', 'order': '12123645948', 'timestamp': 1536582912475, 'datetime': '2018-09-10T12:35:12.475Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.0157, 'amount': 1.9822, 'cost': 9.94212054, 'fee': {'cost': 0.01988424108, 'currency': 'USDT'}}, {'info': {'id': 2512982814, 'order-id': 12339915453, 'match-id': 19685925386, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '4.960200000000000000', 'filled-amount': '2.014900000000000000', 'filled-fees': '0.004029800000000000', 'filled-points': '0.0', 'created-at': 1536816913254}, 'id': '2512982814', 'order': '12339915453', 'timestamp': 1536816913254, 'datetime': '2018-09-13T05:35:13.254Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 4.9602, 'amount': 2.0149, 'cost': 9.994306980000001, 'fee': {'cost': 0.0040298, 'currency': 'EOS'}}, {'info': {'id': 2513809132, 'order-id': 12349244340, 'match-id': 19700230385, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '4.955100000000000000', 'filled-amount': '2.010800000000000000', 'filled-fees': '0.019927430160000000', 'filled-points': '0.0', 'created-at': 1536827406768}, 'id': '2513809132', 'order': '12349244340', 'timestamp': 1536827406768, 'datetime': '2018-09-13T08:30:06.768Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 4.9551, 'amount': 2.0108, 'cost': 9.96371508, 'fee': {'cost': 0.01992743016, 'currency': 'USDT'}}, {'info': {'id': 2516914688, 'order-id': 12380328963, 'match-id': 19747653891, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.437900000000000000', 'filled-amount': '1.838900000000000000', 'filled-fees': '0.003677800000000000', 'filled-points': '0.0', 'created-at': 1536859808011}, 'id': '2516914688', 'order': '12380328963', 'timestamp': 1536859808011, 'datetime': '2018-09-13T17:30:08.011Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.4379, 'amount': 1.8389, 'cost': 9.99975431, 'fee': {'cost': 0.0036778, 'currency': 'EOS'}}, {'info': {'id': 2517062940, 'order-id': 12381955820, 'match-id': 19750137875, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.476700000000000000', 'filled-amount': '1.835200000000000000', 'filled-fees': '0.020101679680000000', 'filled-points': '0.0', 'created-at': 1536861407159}, 'id': '2517062940', 'order': '12381955820', 'timestamp': 1536861407159, 'datetime': '2018-09-13T17:56:47.159Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.4767, 'amount': 1.8352, 'cost': 10.05083984, 'fee': {'cost': 0.02010167968, 'currency': 'USDT'}}, {'info': {'id': 2517078716, 'order-id': 12382155400, 'match-id': 19750442277, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.477700000000000000', 'filled-amount': '1.825500000000000000', 'filled-fees': '0.003651000000000000', 'filled-points': '0.0', 'created-at': 1536861611341}, 'id': '2517078716', 'order': '12382155400', 'timestamp': 1536861611341, 'datetime': '2018-09-13T18:00:11.341Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.4777, 'amount': 1.8255, 'cost': 9.99954135, 'fee': {'cost': 0.003651, 'currency': 'EOS'}}, {'info': {'id': 2517522994, 'order-id': 12387452532, 'match-id': 19758578102, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.379800000000000000', 'filled-amount': '1.821800000000000000', 'filled-fees': '0.019601839280000000', 'filled-points': '0.0', 'created-at': 1536867183215}, 'id': '2517522994', 'order': '12387452532', 'timestamp': 1536867183215, 'datetime': '2018-09-13T19:33:03.215Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.3798, 'amount': 1.8218, 'cost': 9.800919640000002, 'fee': {'cost': 0.01960183928, 'currency': 'USDT'}}, {'info': {'id': 2517537929, 'order-id': 12387622835, 'match-id': 19758795983, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.378700000000000000', 'filled-amount': '1.859100000000000000', 'filled-fees': '0.003718200000000000', 'filled-points': '0.0', 'created-at': 1536867310610}, 'id': '2517537929', 'order': '12387622835', 'timestamp': 1536867310610, 'datetime': '2018-09-13T19:35:10.610Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.3787, 'amount': 1.8591, 'cost': 9.99954117, 'fee': {'cost': 0.0037182, 'currency': 'EOS'}}, {'info': {'id': 2517961514, 'order-id': 12392530187, 'match-id': 19766321027, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.422100000000000000', 'filled-amount': '1.855300000000000000', 'filled-fees': '0.020119244260000000', 'filled-points': '0.0', 'created-at': 1536872168234}, 'id': '2517961514', 'order': '12392530187', 'timestamp': 1536872168234, 'datetime': '2018-09-13T20:56:08.234Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.4221, 'amount': 1.8553, 'cost': 10.059622130000001, 'fee': {'cost': 0.02011924426, 'currency': 'USDT'}}, {'info': {'id': 2518074412, 'order-id': 12393910803, 'match-id': 19768401145, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.393000000000000000', 'filled-amount': '1.854100000000000000', 'filled-fees': '0.003708200000000000', 'filled-points': '0.0', 'created-at': 1536873619760}, 'id': '2518074412', 'order': '12393910803', 'timestamp': 1536873619760, 'datetime': '2018-09-13T21:20:19.760Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.393, 'amount': 1.8541, 'cost': 9.9991613, 'fee': {'cost': 0.0037082, 'currency': 'EOS'}}, {'info': {'id': 2518341884, 'order-id': 12397074890, 'match-id': 19773286476, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.432800000000000000', 'filled-amount': '1.850300000000000000', 'filled-fees': '0.020104619680000000', 'filled-points': '0.0', 'created-at': 1536877035235}, 'id': '2518341884', 'order': '12397074890', 'timestamp': 1536877035235, 'datetime': '2018-09-13T22:17:15.235Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.4328, 'amount': 1.8503, 'cost': 10.052309840000001, 'fee': {'cost': 0.02010461968, 'currency': 'USDT'}}, {'info': {'id': 2518857424, 'order-id': 12402513938, 'match-id': 19781784360, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.393200000000000000', 'filled-amount': '1.851800000000000000', 'filled-fees': '0.003703600000000000', 'filled-points': '0.0', 'created-at': 1536882608214}, 'id': '2518857424', 'order': '12402513938', 'timestamp': 1536882608214, 'datetime': '2018-09-13T23:50:08.214Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.3932, 'amount': 1.8518, 'cost': 9.98712776, 'fee': {'cost': 0.0037036, 'currency': 'EOS'}}, {'info': {'id': 2519086798, 'order-id': 12404829686, 'match-id': 19785428552, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'spot-api', 'price': '5.309700000000000000', 'filled-amount': '1.848000000000000000', 'filled-fees': '0.019624651200000000', 'filled-points': '0.0', 'created-at': 1536884997423}, 'id': '2519086798', 'order': '12404829686', 'timestamp': 1536884997423, 'datetime': '2018-09-14T00:29:57.423Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.3097, 'amount': 1.848, 'cost': 9.812325600000001, 'fee': {'cost': 0.0196246512, 'currency': 'USDT'}}, {'info': {'id': 2519089198, 'order-id': 12404847562, 'match-id': 19785455053, 'symbol': 'eosusdt', 'type': 'buy-limit', 'source': 'spot-api', 'price': '5.315400000000000000', 'filled-amount': '1.881200000000000000', 'filled-fees': '0.003762400000000000', 'filled-points': '0.0', 'created-at': 1536885015605}, 'id': '2519089198', 'order': '12404847562', 'timestamp': 1536885015605, 'datetime': '2018-09-14T00:30:15.605Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'buy', 'price': 5.3154, 'amount': 1.8812, 'cost': 9.999330480000001, 'fee': {'cost': 0.0037624, 'currency': 'EOS'}}, {'info': {'id': 2522066891, 'order-id': 12434287522, 'match-id': 19829964465, 'symbol': 'eosusdt', 'type': 'sell-limit', 'source': 'web', 'price': '5.140100000000000000', 'filled-amount': '1.878100000000000000', 'filled-fees': '0.019307243620000000', 'filled-points': '0.0', 'created-at': 1536915607160}, 'id': '2522066891', 'order': '12434287522', 'timestamp': 1536915607160, 'datetime': '2018-09-14T09:00:07.160Z', 'symbol': 'EOS/USDT', 'type': 'limit', 'side': 'sell', 'price': 5.1401, 'amount': 1.8781, 'cost': 9.65362181, 'fee': {'cost': 0.01930724362, 'currency': 'USDT'}}]
```

**Comment by mishaker** [comment] 2018-09-15 18:31
@xmatthias isn't it worth to include NTP on installation and also have a clock check between exchange and local once the bot boots ?

**Comment by xmatthias** [comment] 2018-09-15 18:36
i would not want a program installation to install a ntp daemon - there are multiple out there (i use chrony - others use ntpd).

also, ntp is a problem when running in docker ... as you can't control the systems time from there.

i thought we have something about clock accuracy in the documentation ... but i struggle to find that at the moment.
Still - ntp does not guarantee you 100% accuraccy on the exchange side ... :(

**Comment by yaotian** [comment] 2018-09-24 05:53
Happened again. 

from sqlite

```
11|huobipro|EOS/USDT|0|0.0|0.002|5.708|5.708|5.8299|5.8299|0.01931327|10.0|1.7483962|2018-09-21 15:40:19.009884|2018-09-21 16:05:19.501511||5.53676|5.53676|5.708|sell_signal|MultiRSI|5
12|huobipro|EOS/USDT|1|0.002|0.002|6.0571|6.0571||||10.0|1.6509|2018-09-21 20:55:11.856475|||5.875387|5.875387|6.0571||MultiRSI|5
```

from log

```
2018-09-21 20:55:10,507 - freqtrade.rpc.rpc_manager - INFO - Sending rpc message: {'type': buy, 'exchange': 'Huobi pro', 'pair': 'EOS/USDT', 'market_url': '', 'limit': 6.0571, 'stake_amount': 10, 'stake_currency': 'USDT', 'fiat_currency': 'USD'}
2018-09-21 20:55:10,535 - freqtrade.fiat_convert - ERROR - Error in _find_price: 'JSONDecodeError' object is not subscriptable
2018-09-21 20:55:12,451 - freqtrade.freqtradebot - INFO - Found open order for Trade(id=12, pair=EOS/USDT, amount=1.65095508, open_rate=6.05710000, open_since=just now)
2018-09-21 20:55:16,475 - freqtrade.freqtradebot - INFO - Applying fee on amount for Trade(id=12, pair=EOS/USDT, amount=1.65095508, open_rate=6.05710000, open_since=just now) failed: myTrade-Dict empty found
2018-09-21 20:55:16,476 - freqtrade.persistence - INFO - Updating trade (id=12) ...
2018-09-21 20:55:16,476 - freqtrade.persistence - INFO - LIMIT_BUY has been fulfilled for Trade(id=12, pair=EOS/USDT, amount=1.65090000, open_rate=6.05710000, open_since=just now).
```

from  exchange

**Comment by yaotian** [comment] 2018-09-24 11:10
I saw this fix did not get merged. 
I saw the code. The fix is good. 
Agree with xmatthias. Don't need NTP check.
My best guess is some API of the exchange got some time gap after it was called.  @xmatthias @mishaker

**Comment by mishaker** [comment] 2018-09-27 09:42
@yaotian the PR is approved and will be merged soon. I am going to close this issue but don't hesitate to reopen it in case ...

**Closed by mishaker** 2018-09-27 09:42 UTC
Labels: bug, ccxt, duplicate
