### ISSUE TITLE
Implementation Buy Reason 

### ISSUE THREAD

**Issue by yari0757** [freqtrade/freqtrade#5280] opened 2021-07-17 10:28 UTC
## Describe the enhancement

*Thanks to all contributors. Freqtrade is great! I learn a lot.
my feature request is simple and straight forward. is there any way to implement Buy reason some thing like sell reason? After using Freqtrade more than 4 month, I have more than 30 buy conditions in populate_buy_trend  function and it should be great idea to see why buying some coin in telegram  and witch condition triggered?*

**Comment by xmatthias** [comment] 2021-07-17 13:54
Please use the search to look for similar issues before opening duplicates.

Duplicate of #3081.

**Closed as completed by xmatthias** 2021-07-17 13:54 UTC
Labels: Duplicate
